### ISSUE TITLE
[Feature Request] Add disk cache and Token streaming

### ISSUE THREAD

**Issue by Silver267** [oobabooga/text-generation-webui#10]
Hi, thanks for making this app! I have some ideas of further improvement.

Although my computer possesses 32GB of memory and 8GB of VRAM, experiments still indicated that these are not enough to load the 13b models. It would be a great help to add disk cache function so larger models could load. Ideally, I would love the cache to be generated once-and-for-all (generate once and reads the generated cache the next time instead of re-generating), so I don't have to push too much load on my ssd, but that's just an extra request.

For Token streaming, it would be a great help to add token streaming (displays token while they are being generated) into this app since many people (like me) are not very patient with the AI. The generation time could go up to minutes and it would be helpful to directly view the generating text.

Just some thoughts about adding features to this program.

**Comment by neuralinternet** [comment]
Token streaming would be a great addition!

**Comment by oobabooga** [comment]
Text streaming has been implemented. It is still experimental, but it seems to work. Can you try it?

**Comment by Silver267** [comment]
> 

Text streaming did work, however, I think it introduced other bugs - in chat mode, the generate button would sometimes not respond and the input box will not automatically be cleared after generate button is clicked, and input box sometimes clears itself when typing. The other modes seems to be working properly though.

**Comment by Silver267** [comment]
@oobabooga Text streaming did work, however, I think it introduced other bugs - in chat mode, the generate button would sometimes not respond and the input box will not automatically be cleared after generate button is clicked, and input box sometimes clears itself when typing. The other modes seems to be working properly though.

**Comment by oobabooga** [comment]
Can you `git pull` and try again? I might have fixed those inconsistencies with the latest commits.

**Comment by Silver267** [comment]
Your fix worked. I'll still remain this issue as open since the other request (disk cache that generates once-and-for-all) isn't implemented yet, but take your time. Thanks for the work!

**Comment by oobabooga** [comment]
I am glad to hear that. For now, I have moved the stream work into a separate `stream` branch because the streaming caused a 50% decrease in performance on my GPU. Once things become more stable I will move it back to the main branch.

**Comment by oobabooga** [comment]
The `--disk` option has been implemented. With it, I have been able to load a 30b model on my RTX 3090 with

`python server.py --model galactica-30b --auto-devices --disk`

The performance is crap (like 1 word every 10 seconds), but it works.
