### ISSUE TITLE
"no GPU has been detected" even though I ran the gpu install bat file

### ISSUE THREAD

**Issue by chausies** [oobabooga/text-generation-webui#100]
I have a 3080ti and web-ui for image generation works perfectly fine for me on GPU. But when using Oobabooga, I get the message
```
Loading pygmalion-6b...
Warning: no GPU has been detected.
Falling back to CPU mode.
```
This is even though I have fully updated GPU drivers and have ran install-nvidia.bat.
Any help is appreciated.

**Comment by Slug-Cat** [comment]
I had the same error, I had to uninstall system torch for it to work again.

**Comment by chausies** [comment]
@Slug-Cat Thanks so much for the response! Care to give me a relatively quick/simple way to do it? Maybe a command or something I can run in terminal? Or just point me in the right direction. I normally use WSL mainly, so I don't know where all the bat files have been installing all their bat files, etc.

**Comment by Slug-Cat** [comment]
I just opened a normal cmd.exe window and ran `pip uninstall torch`. No idea how it works with WSL, I haven't used it before.

**Comment by chausies** [comment]
Okay, I think I found the problem, and the best fix. It was that I first ran "install-cpu.bat" before "install-nvidia.bat".
The fix is to delete the folder, and re-install. This time, only run install-nvidia.bat. And then download-model.bat. After that, it works like a charm, running on GPU.

Cheers! Keep up the great work!
