### ISSUE TITLE
Bot spams random numbers or does not load

### ISSUE THREAD

**Issue by Kouchola** [oobabooga/text-generation-webui#1000]
### Describe the bug

Hello,
I installed oobabooga with the one click installer and I can not load the facebook_opt-2.7b (I copied the console into the log).
I also installed the gpt4x alpaca model with the automatic installer(download-model.bat). If I chat with it, it just spams random 2 and 4 (I took a screenshot and pasted it down below). If I manually install the gpt4x model (with the help of this tutorial: https://youtu.be/nVC9D9fRyNU?t=162 ), I get the same output as the Facebook model in the log. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Automatic installer
2. let download-model.bat download anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g or follow this tutorial:
3. let download-model.bat download one model from the list
4. start-webui.bat has following arguments: python server.py --auto-devices  --chat --wbits 4 --groupsize 128

### Screenshot

![image](https://user-images.githubusercontent.com/125409728/230895729-d2f12173-81a5-4de6-9296-71845906ab01.png)

### Logs

```shell
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: C:\Users\Caner\Documents\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary C:\Users\Caner\Documents\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
The following models are available:

1. anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g
2. facebook_opt-2.7b

Which one do you want to load? 1-2

2

Loading facebook_opt-2.7b...
Could not find the quantized model in .pt or .safetensors format, exiting...
Drücken Sie eine beliebige Taste . . .
```

### System Info

```shell
Windows 10 Version 22H2, Amd Ryzen 5800x, Palit Gamingpro Rtx 3080.
```

**Comment by Yeecy-sketch** [comment]
The facebook_opt-2.7b model couldn't be loaded because it is not a 4 bit model, you have to launch it without the `--wbits 4 --groupsize 128` parameters. But you try adding `--load-in-8bit` for less memory usage.
Final command for it could look something like this: `python server.py --load-in-8bit --auto-devices --chat`

**Comment by Kouchola** [comment]
Alright thanks for the Info!

**Comment by jllllll** [comment]
I just updated the GPTQ-for-LLaMa wheel to broaden GPU architecture support. Either completely re-install using the latest installer or open `micromamba-cmd.bat` and enter this command:
```
python -m pip install https://github.com/jllllll/GPTQ-for-LLaMa-Wheels/raw/main/quant_cuda-0.0.0-cp310-cp310-win_amd64.whl --force-reinstall
```

**Comment by Kouchola** [comment]
I already did a fresh install and tried to use your command but the AI still communicates like this

![image](https://user-images.githubusercontent.com/125409728/230930207-3cc258dc-8614-447c-8ea5-a53c75c839ea.png)

**Comment by Kouchola** [comment]
This one did it For me!
Thank for your help!
https://github.com/oobabooga/text-generation-webui/issues/931#issuecomment-1501259566
