### ISSUE TITLE
[Issue] Invalid model name with flexgen

### ISSUE THREAD

**Issue by Manimap** [oobabooga/text-generation-webui#102]
So I was curious about flexgen and went straight to the 30b opt one, converted it to flexgen, but when I launch it I get the following error : 

The following models are available:
1. GPT-NeoX-20B-Erebus
2. OPT-13B-Erebus
3. opt-30b
4. opt-30b-np
5. pygmalion-6b
6. pygmalion-6b_dev

Which one do you want to load? 1-6
4

Loading opt-30b-np...
Traceback (most recent call last):
  File "D:\text-generation-webui\server.py", line 944, in <module>
    model, tokenizer = load_model(model_name)
  File "D:\text-generation-webui\server.py", line 145, in load_model
    opt_config = get_opt_config(f"facebook/{model_name}")
  File "C:\Users\USER\miniconda3\envs\textgen\lib\site-packages\flexgen-0.0.0-py3.10.egg\flexgen\opt_config.py", line 116, in get_opt_config
ValueError: Invalid model name: opt-30b-np

OS : Windows 10
Launch parameters don't seem to matter but I used : python server.py --cai-chat --no-stream --flexgen --percent 0 0 100 0 100 0

**Comment by oobabooga** [comment]
Choose option 3 (opt-30b) instead of 4 and let me know if it works.

**Comment by oobabooga** [comment]
This technique becomes slower if you allocate more memory to the GPU (don't ask me why). Try `0, 100, 100, 0, 100, 0` if you can

**Comment by oobabooga** [comment]
Thanks for the tip. These are my results for opt-30b using a RTX 3090 on Linux:

* `--flexgen --compress-weight`: 0.99 seconds per token
* `--flexgen --compress-weight --percent 100 0 100 0 100 0`: 0.765 seconds per token

So it's faster to use the GPU memory, at least in this case.
