### ISSUE TITLE
Notification sound

### ISSUE THREAD

**Issue by dronelove** [oobabooga/text-generation-webui#1020]
**Description**

Similar to Automatic1111, It would be cool to have a feature to have the webui play notification.mp3 at the end of output generation. Useful for slower systems.

**Comment by j4ded** [comment]
seconded. it's good for big models too.
if you want to include a sound with it, [here](https://pixeldrain.com/l/cXyZ1fJx) are two i made myself for sd. anyone can do whatever they want with them. i have all kinds of these. the 2nd one was made for nostalgia and included for fun.
they're wavs, so you can decide how you want to encode.

**Comment by HappyWorldGames** [comment]
I made a pull request, to add a sound notification after text generation(https://github.com/oobabooga/text-generation-webui/pull/1075). So wait for it to be accepted, and if not, you know what to do to add it.
