### ISSUE TITLE
Gibberish output and OOM errors with 65b

### ISSUE THREAD

**Issue by thot-experiment** [oobabooga/text-generation-webui#1029]
Running using two different GPUs (GV100 + 1080Ti) for a total of 43Gb of vram w/ this model https://huggingface.co/Neko-Institute-of-Science/LLaMA-65B-4bit-128g , finally got the model loaded with the following command:
```
python server.py --wbits 4  --gpu-memory 27 10 --model Neko-Institute-of-Science_LLaMA-65B-4bit-128g --listen --groupsize 128
```
but output is gibberish no matter which sampler settings I use.

![image](https://user-images.githubusercontent.com/94414189/231021381-9bbee9c2-679e-4063-9298-b103ef9fd822.png)

Wondering if this is some sort of an issue specific to my configuration or something else? Appreciate any hints on how to get this running.

Device map for reference:
```
Using the following device map for the 4-bit model: {'model.embed_tokens': 0, 'model.layers.0': 0, 'model.layers.1': 0, 'model.layers.2': 0, 'model.layers.3': 0, 'model.layers.4': 0, 'model.layers.5': 0, 'model.layers.6': 0, 'model.layers.7': 0, 'model.layers.8': 0, 'model.layers.9': 0, 'model.layers.10': 0, 'model.layers.11': 0, 'model.layers.12': 0, 'model.layers.13': 0, 'model.layers.14': 0, 'model.layers.15': 0, 'model.layers.16': 0, 'model.layers.17': 0, 'model.layers.18': 0, 'model.layers.19': 0, 'model.layers.20': 0, 'model.layers.21': 0, 'model.layers.22': 0, 'model.layers.23': 0, 'model.layers.24': 0, 'model.layers.25': 0, 'model.layers.26': 0, 'model.layers.27': 0, 'model.layers.28': 0, 'model.layers.29': 0, 'model.layers.30': 0, 'model.layers.31': 0, 'model.layers.32': 0, 'model.layers.33': 0, 'model.layers.34': 0, 'model.layers.35': 0, 'model.layers.36': 0, 'model.layers.37': 0, 'model.layers.38': 0, 'model.layers.39': 0, 'model.layers.40': 0, 'model.layers.41': 0, 'model.layers.42': 0, 'model.layers.43': 0, 'model.layers.44': 0, 'model.layers.45': 0, 'model.layers.46': 0, 'model.layers.47': 0, 'model.layers.48': 0, 'model.layers.49': 0, 'model.layers.50': 0, 'model.layers.51': 0, 'model.layers.52': 0, 'model.layers.53': 0, 'model.layers.54': 0, 'model.layers.55': 0, 'model.layers.56': 0, 'model.layers.57': 0, 'model.layers.58': 0, 'model.layers.59': 0, 'model.layers.60': 0, 'model.layers.61': 0, 'model.layers.62': 0, 'model.layers.63': 0, 'model.layers.64': 1, 'model.layers.65': 1, 'model.layers.66': 1, 'model.layers.67': 1, 'model.layers.68': 1, 'model.layers.69': 1, 'model.layers.70': 1, 'model.layers.71': 1, 'model.layers.72': 1, 'model.layers.73': 1, 'model.layers.74': 1, 'model.layers.75': 1, 'model.layers.76': 1, 'model.layers.77': 1, 'model.layers.78': 1, 'model.layers.79': 1, 'model.norm': 1, 'lm_head': 1}
```

History/context/previous attempts:

Previously I was using the g32 model and was getting cuda OOM errors, tried `--auto-devices`, `--gpu-memory 32 11` and `--gpu-memory 31 10` etc but all configs result in a cuda OOM (though the last one results in an OOM on the Ti vs the GV, and I just tried to repro so I could paste the error and now it's just silently crashing 😬 ) Same with the working one until I stumbled on the lucky command line flags by trial and error.

Can anyone explain to me what's happening with the rest of my vram, this GPU isn't being used by the OS? 

`11.00 GiB total capacity; 9.65 GiB already allocated; 0 bytes free; 9.71 GiB reserved in total by PyTorch`

where's the other 1.3GiB going?

**`nvidia-smi`** shows 0 vram used on the 1080 and 250mb on the gv100 before i run the webui
```
|   0  Quadro GV100       WDDM  | 00000000:81:00.0  On |
| 29%   35C    P0    25W / 250W |    243MiB / 32768MiB |3%
+-------------------------------+----------------------+
|   1  NVIDIA GeForce ... WDDM  | 00000000:C1:00.0 Off |
| 23%   23C    P8     9W / 250W |      0MiB / 11264MiB |0%
```
full error
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 1; 11.00 GiB total capacity; 9.65 GiB already allocated; 0 bytes free; 9.71 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by practicaldreamer** [comment]
Need to update a couple files. Transformer update broke some stuff. Check here https://github.com/oobabooga/text-generation-webui/issues/931#issuecomment-1501892602

**Comment by thot-experiment** [comment]
thanks, unfortunately this doesn't appear to have made any difference for me, still getting the same sort of gibberish `TATATATAT` etc, I've also tired the `tokenizer_config.json` and `special_tokens_map.json` from (this repo)[https://huggingface.co/hf-internal-testing/llama-tokenizer/tree/main] with a similar result

**Comment by CryptoRUSHGav** [comment]
I noticed it worked when using the `triton` branch of `https://github.com/qwopqwop200/GPTQ-for-LLaMa`.
This means, if you use Windows, you'll most likely need to run oobabooga through WSL.

**Comment by thot-experiment** [comment]
That's a regression that should be addressed. I'm not eager to install WSL.

**Comment by thot-experiment** [comment]
Closing this out as I am no longer getting OOM issues and the gibberish output appears to be unrelated to to the model size as per #931, will continue this discussion over there. 

However if someone comes across this in the future with any information regarding this stuff I'm still very curious to understand what's happening here (more info in OP)

> Can anyone explain to me what's happening with the rest of my vram, this GPU isn't being used by the OS?
> 
> 11.00 GiB total capacity; 9.65 GiB already allocated; 0 bytes free; 9.71 GiB reserved in total by PyTorch
> 
> where's the other 1.3GiB going?
