### ISSUE TITLE
RTX 2070 - CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 6.63 GiB already allocated

### ISSUE THREAD

**Issue by miguelgargallo** [oobabooga/text-generation-webui#1041]
### Describe the bug

File "E:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 209, in forward
    key_states = torch.cat([past_key_value[0], key_states], dim=2)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 6.63 GiB already allocated; 0 bytes free; 7.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 6.34 seconds (0.32 tokens/s, 2 tokens, context , seed 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

just prompt text

### Logs

```shell
File "E:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 209, in forward
    key_states = torch.cat([past_key_value[0], key_states], dim=2)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 6.63 GiB already allocated; 0 bytes free; 7.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 6.34 seconds (0.32 tokens/s, 2 tokens, context , seed
```

### System Info

```shell
MSI GE 66, WIN 11
```

**Comment by miguelgargallo** [comment]
This seems to fix
![imagen](https://user-images.githubusercontent.com/5947268/231263375-7e07b483-6450-4fc9-b377-c018eb105f01.png)

**Comment by Ph0rk0z** [comment]
Yea.. your response can only be 48 tokens long.

**Comment by botchi09** [comment]
6GB here. I don't know much but it seems odd the model is 3.5GB but I get similar OOM errors.

**Comment by EyeDeck** [comment]
> This seems to fix

That's because by setting `max_new_tokens` to 2000, you're limiting input context size to just 48 tokens. Larger context size = larger memory requirements.
