### ISSUE TITLE
Does FlexGen support other generation params?

### ISSUE THREAD

**Issue by hivaze** [oobabooga/text-generation-webui#106]
Hello! As I can see here theris a if else for gen params when flexgen is on https://github.com/oobabooga/text-generation-webui/blob/main/server.py#L370.

I know that in the original flexgen repo they used only these params in research, but why if/else condition is needed here?
```
generate_params = [
            f"do_sample={do_sample}",
            f"temperature={temperature}",
            f"stop={n}",
        ]
```

**Comment by oobabooga** [comment]
FlexGen is not integrated into huggingface and does not inherit the same generation parameters. See the definition for the generate function here:

https://github.com/FMInference/FlexGen/blob/main/flexgen/flex_opt.py#L812
