### ISSUE TITLE
Add RAM/VRAM requirements to wiki when using FlexGen

### ISSUE THREAD

**Issue by minipasila** [oobabooga/text-generation-webui#109]
It seems to consume much more RAM and VRAM (shared memory) than other modes (8-bit or 16-bit) from my testing. So, what are the requirements for RAM and VRAM with FlexGen (on different models)? ~~Because I'm only able to run the 1.3B model, anything higher and I run out of memory and it won't start and shuts down automatically.~~ (I have 16GB of RAM and 8GB of VRAM, also I did try the --compress-weight which didn't seem to really do anything)
Edit: So I guess you just have to play around the --percent numbers until it hopefully works and doesn't crash/freeze your PC.

**Comment by oobabooga** [comment]
@minipasila the first 2 numbers after --percent are the GPU and CPU allocations in % respectively. If the sum of the 2 is less than 100, the remaining layers will be offloaded to the disk, by default into the `text-generation-webui/cache/` folder.

Try something like

`python server.py --flexgen --compress-weight --percent 0 50 100 0 100 0`

**Comment by minipasila** [comment]
ok thanks
