### ISSUE TITLE
The Case Against Conda

### ISSUE THREAD

**Issue by USBhost** [oobabooga/text-generation-webui#1093]
https://github.com/oobabooga/text-generation-webui/commit/0fad92160bca08138ae4e960691c335bcddc2273#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

I started writing a guide on avoiding Conda but is this something people even want? It would allow people to simply use their python install from automatic here. Since Conda was only used to provide python do we even need it? It just adds more bloat than we need. Linux users already have python installed so there's no need for conda.

**Comment by Ph0rk0z** [comment]
In linux some distros limit the version of python. It's slow but I kind of like conda. It's easier for me to remember than the normal python venv commands. I already reuse environments.

I thought it didn't matter which virtual environment you use as long as the packages are all there.

**Comment by USBhost** [comment]
@nathanielsuchy in my experience we do not even need conda installed. You do everything just skip the conda stuff and use the normal venv.
```
git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui
python3 -m venv venv
. venv/bin/activate; # or just venv/bin/activate; on PowerShell 
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip install -r pip install -r requirements.txt
```
That's it your free from conda

**Comment by darthdeus** [comment]
Have you had any luck getting this to work with the Pygmalion model at https://huggingface.co/mayaeary/pygmalion-6b-4bit-128g? I tried so many ways but always getting stuck on getting https://github.com/mayaeary/GPTQ-for-LLaMa/tree/gptj-v2 to compile with CUDA.

**Comment by UnconnectedBedna** [comment]
Sorry for necro thread, but I cant find anything anywhere else...
I tried above, and still when running `start_linux.sh`:

```
Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Linux-x86_64.sh to /home/bedna/temp/text-generation-webui/installer_files/miniconda_installer.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 69.7M  100 69.7M    0     0  10.9M      0  0:00:06  0:00:06 --:--:-- 11.0M
PREFIX=/home/bedna/temp/text-generation-webui/installer_files/conda
Unpacking payload ...
                                                                                                                                                                                                                    
Installing base environment...
```

I have a perfectly fine venv working and activated that I want to use.
Is conda somehow a requirement anyway?
