### ISSUE TITLE
[Issue] Soft Prompt not working with Linux

### ISSUE THREAD

**Issue by Jerryhuh** [oobabooga/text-generation-webui#112]
OS: Ubuntu 22.0.2
GPU: 3060 Ti 8 GB
Model: Pygmalion 6B Main

Running with DeepSpeed ZeRO 3 Offload.

Tried several soft prompts and none work,  When I select the soft prompt and send a reply, nothing happens and I receive this error in Terminal.  If I change the soft prompts back to "None" the chat works again.

![image](https://user-images.githubusercontent.com/126207474/221045779-fed8574e-e958-4650-ae4b-15c2437f24fc.png)

**Comment by oobabooga** [comment]
Thanks for reporting, this was indeed a bug with the softprompts when deepspeed was active. It should be fixed now, can you test?

**Comment by Jerryhuh** [comment]
It works perfect now!  Thx ooba!
