### ISSUE TITLE
Micromamba not found

### ISSUE THREAD

**Issue by Hatsu03** [oobabooga/text-generation-webui#1124]
### Describe the bug

install.bat give me error, "Micromamba not found."

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

![cmd_xbhRu443cG](https://user-images.githubusercontent.com/117382083/231665139-860347bb-15a1-4652-99be-94190e017bac.png)

### Screenshot

![cmd_xbhRu443cG](https://user-images.githubusercontent.com/117382083/231665139-860347bb-15a1-4652-99be-94190e017bac.png)

### Logs

```shell
What is your GPU?

A) NVIDIA
B) None (I want to run in CPU mode)

Input> a
"Downloading Micromamba from https://github.com/mamba-org/micromamba-releases/releases/download/1.4.0-0/micromamba-win-64 to D:\AI\oobabooga-windows\installer_files\mamba\micromamba.exe"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 8220k  100 8220k    0     0  3154k      0  0:00:02  0:00:02 --:--:-- 4855k
Micromamba version:
Micromamba not found.
Press any key to continue . . .
```

### System Info

```shell
Windows 10, laptop
```

**Comment by bloodsign** [comment]
Can you post the install.bat that you used?
If you are using the old install.bat, there are a couple of changes in the newer version. You might be using that one.

**Comment by jllllll** [comment]
There haven't been any changes to that part of the script. Check that `micromamba.exe` is located in the path it claims to have downloaded to. If it is not there, you may want to check if your anti-virus removed it.

**Comment by xNul** [comment]
You can also try to install via my one-click install script which uses Miniconda instead of Micromamba https://github.com/oobabooga/one-click-installers/pull/21

**Comment by Hatsu03** [comment]
> Can you post the install.bat that you used? If you are using the old install.bat, there are a couple of changes in the newer version. You might be using that one.

ofc

**Comment by Hatsu03** [comment]
> Can you post the install.bat that you used? If you are using the old install.bat, there are a couple of changes in the newer version. You might be using that one.

ofc
[install.txt](https://github.com/oobabooga/text-generation-webui/files/11224995/install.txt)

**Comment by Hatsu03** [comment]
> There haven't been any changes to that part of the script. Check that `micromamba.exe` is located in the path it claims to have downloaded to. If it is not there, you may want to check if your anti-virus removed it.

Antivirus and firewall are disabled. The file path is correct.

**Comment by Hatsu03** [comment]
> This is the current one: https://github.com/oobabooga/one-click-installers Either use the current one or the one that xNul linked. There are critical changes missing in the one that you were using.

Same error

**Comment by xNul** [comment]
My guess is the download for Micromamba is being blocked on your network for some reason. My one-click install script uses Miniconda so maybe you'll have better luck with it.

**Comment by Hatsu03** [comment]
> My guess is the download for Micromamba is being blocked on your network for some reason. My one-click install script uses Miniconda so maybe you'll have better luck with it.

I used your files if I understood correctly but didn't help. Can you upload your install.bat in TXT format?

I used VPN but didn't help - same error.

**Comment by xNul** [comment]
I'm not sure what you're doing. Just download [this zip](https://github.com/xNul/one-click-installers/archive/refs/heads/oobabooga-windows.zip), extract it to another folder, and double click on the "start_windows.bat" file to run it. There's no copying TXT or anything like that.

**Comment by Hatsu03** [comment]
> I'm not sure what you're doing. Just download [this zip](https://github.com/xNul/one-click-installers/archive/refs/heads/oobabooga-windows.zip), extract it to another folder, and double click on the "start_windows.bat" file to run it. There's no copying TXT or anything like that.


Im launch istall.bat >>>
What is your GPU?

A) NVIDIA
B) None (I want to run in CPU mode)

Input> a
"Downloading Micromamba from https://github.com/mamba-org/micromamba-releases/releases/download/1.4.0-0/micromamba-win-64 to D:\one-click-installers-oobabooga-windows\installer_files\mamba\micromamba.exe"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 8220k  100 8220k    0     0  1563k      0  0:00:05  0:00:05 --:--:-- 1851k
Micromamba version:

Micromamba not found.
Press any key to continue . . .

**Comment by xNul** [comment]
@Hatsu03 you didn't download and run the bat I gave you. You're still running the old bat. Please try to follow my instructions exactly or else you will have problems

**Comment by skaba04** [comment]
@xNul i used your zip for the installation of the Web UI works fine but how do i install more models that are not on the list?

**Comment by Hatsu03** [comment]
@xNul 
I Installed, a new error in the console When installing models, when I copy the code on the site. 'git' is not internal or external
command, executable program, or batch file. What to do?
![msedge_tHD0szT1J8](https://user-images.githubusercontent.com/117382083/232136719-7e1ab3b2-43cc-42a5-b589-94e277b247ad.png)
![cmd_0y9TS8P8mn](https://user-images.githubusercontent.com/117382083/232136787-b0399cd4-f29b-4595-9fe6-b51c4090b5b5.png)

**Comment by Hatsu03** [comment]
> @Hatsu03 @Centurion-Rome my bad. I gave you guys the wrong zip to download. Here is the right zip. https://github.com/xNul/one-click-installers/archive/refs/heads/universal.zip

It works.

**Comment by xNul** [comment]
> @xNul i used your zip for the installation of the Web UI works fine but how do i install more models that are not on the list?

In the webui, there's a tab called "Models" and in that tab, there's an option to download more models. You enter the model you want from Hugging Face like "Drararara/llama-7b-ggml" and webui will download it
