### ISSUE TITLE
Move the "Clear history" button further away and add an additional confirmation step

### ISSUE THREAD

**Issue by Xabab** [oobabooga/text-generation-webui#116]
I lost too many chats miss clicking this darn thing

**Comment by oobabooga** [comment]
I agree that it could be moved further away, but to be honest, I don't know a better way to organize the buttons. Do you have an idea?

**Comment by oobabooga** [comment]
New disposition:

![what](https://user-images.githubusercontent.com/112222186/221374051-eaa1bd76-0bfb-437c-8e4f-93ab52ee25aa.png)

**Comment by Xabab** [comment]
This grouping seem actually better! 

I would only swap 'remove last' and 'stop', as I feel 'remove last' is used more often (same on mobile version). Also clear history still nukes the chat with a single click only, wouldn't hurt to make it differently colored (I would have moved it to the bottom of the page, tho it breaks the symmetry).

I don't know how to to this, but would have been useful to make a poll which buttons (after 'generate' of course) are used most often and do the order depending on the results. If you want to be extra fancy, you could make a config file in ./oobabooga-data/ and allow users to redefine the order themselves.

**Comment by oobabooga** [comment]
Gradio is a very simple UI framework that basically defines buttons, menus, and event functions to call functions. There is no easy way to create a popup with an additional button afaik.

Generate/Stop can be combined into a single button with some javascript. I intend to do this at some point, so let's leave things like this for now.

**Comment by Xabab** [comment]
@oobabooga Leaving it as it is, with a single click to nuke and in the main cluster of buttons is definitely a bad UX/UI decision.
I would either:
+ make it double click to perform (akin this https://stackoverflow.com/questions/24899021/click-twice-to-perform-action or https://codepen.io/johnmcdowall/pen/DqPzmW)
+ move it down to the bottom of the page
+ at least make it red

**Comment by Xabab** [comment]
I fumbled with Gradio a bit yesterday, and it seems while it is possible to change a button's appearance when clicking on it with a check for a timed state, it couldn't be changed back with a timer. At least I did had not found a way to set context explicitly.

The best solution imo would be to change button's variant from `secondary` (default) to `stop` (red) and move it into the "Chat Settings -> Chat History" tab.

**Comment by oobabooga** [comment]
This would be a way, but the ideal solution would be to add a `onclick=confirm()` event using javascript: https://www.w3schools.com/jsref/met_win_confirm.asp

I have asked here about this:

https://github.com/gradio-app/gradio/issues/3324

**Comment by oobabooga** [comment]
This should settle it https://github.com/oobabooga/text-generation-webui/commit/611010e8af5d9566eb50a8eaa0b64192b918f469

![a](https://user-images.githubusercontent.com/112222186/221594058-cb737efd-d99a-40d7-962f-392ba095adaa.png)
![b](https://user-images.githubusercontent.com/112222186/221594067-5fd01f49-87a7-4171-a2a1-e73e714e4e8a.png)
