### ISSUE TITLE
Improve Databricks Dolly support (special tokens?)

### ISSUE THREAD

**Issue by mcmonkey4eva** [oobabooga/text-generation-webui#1161]
Dolly: https://www.databricks.com/blog/2023/04/12/dolly-first-open-commercially-viable-instruction-tuned-llm
Can grab 12B variant from https://huggingface.co/databricks/dolly-v2-12b

-----

I think Dolly has its format inputs encoded as special tokens, or something? `### Instruction:`, `### Response:`,` ### End` are its 3 magic labels.

I noticed while running that they seem to "disappear" from the `--verbose` log. My initial guess is, what happens is they get encoded to a special token, and the decode stage doesn't restore them properly.

This theory is backed up, by, yknow, `special_tokens_map.json` having them marked as special tokens. (I notice it also has bos/pad/unk set as `<|endoftext|>` which seems questionable but idk).

The tokenizer is a `json` file, so I can actually see that these are tokens 50277, 50278, 50279, all considered `"special": true`.
I imagine the `special` status affects either the encode or decode stage in some way.

----

More importantly than `verbose` having them missing, I've noticed that after it's done generating, it will output additional lines starting with `ing` or similar. My theory is that it outputs `### End` and that token isn't recognized as the end piece, and so it tries to continue from there as `Ending (... more sentence here)`.
I tried setting stop phrase to `### End` but that doesn't appear to work as the stop.

Based on that, my secondary guess is maybe `encode` entirely fails to process the special tokens, and they're being omitted entirely?

(Which would explain why `### End` as stop input would be emitted by the LLM but not found by the stop token search)

----

I'm submitting this as a feature request as (A) Dolly is a new model and so _adding support_ is a new feature, and (B) the bug-report issue template isn't particularly conducive to this topic.

**Comment by oobabooga** [comment]
This is also an issue with galactica and open assistant, which depend on special tokens to perform certain tasks. I have hard coded a regex for the model names in the decode function as a workaround:

https://github.com/oobabooga/text-generation-webui/blob/main/modules/text_generation.py#L59

which is not ideal.

**Comment by mcmonkey4eva** [comment]
Adding `dolly` to that matcher indeed fixes the `--verbose` output to contain the text properly. However while testing it generated:
```
### End!

More unwanted text here
```

Despite having
![image](https://user-images.githubusercontent.com/4000772/231927461-567bdc1b-979b-486e-866e-f8702cd01e74.png)

Which I guess would be because `sentinel_token_ids = [encode(string, add_special_tokens=False) for string in st]` special tokens are blocked there?

Why *are* special tokens skipped normally? Would it work to just globally permit special tokens?

If not, is there potentially something in the tokenizer that we could use to more stably determine which setting is better (eg if there's common special tokens that we know are never wanted, then we can skip special tokens for models that use those, and allow tokens for models outside that range)?

If there isn't an autodetect setup that we can get working easily, perhaps it'd be better to have a user-selectable setting for it, so users just have to note that when running galactica/dolly you gotta toss in `--specialtokens true`

**Comment by oobabooga** [comment]
I think that the best way to handle this would be to have a checkbox like "show special tokens" in the Parameters tab, and then define a default value for this checkbox through the model-specific parameters framework introduced here

https://github.com/oobabooga/text-generation-webui/pull/1167

It would be an entry like this in `models/config.yaml`

```yaml
.*(galactica|dolly|oasst)
  keep_special_tokens: true
```

**Comment by oobabooga** [comment]
> Why are special tokens skipped normally? Would it work to just globally permit special tokens?

I have set this quite a while ago, but my experience was that keeping the special tokens resulted in lots of weird stuff appearing in the output like `<endoftext>` and similar. 

I'm 95% sure that keeping the special tokens by default is the best option in terms of user experience.

**Comment by mcmonkey4eva** [comment]
Oo, that PR is a really good improvement. Definitely a good way to fix the dolly issue too.

... Is that config automatically applied in the UI? ie, can a user swap model via UI to something different (eg between an 8bit model and a 4bit one) without having to completely restart? If so, that's a *massive* step forward in user-friendliness!

**Comment by oobabooga** [comment]
> can a user swap model via UI to something different (eg between an 8bit model and a 4bit one) without having to completely restart

Yes =) everything is set automatically. For instance, if the user loads pygmalion in chat mode + 16-bit precision initially, and then selects "anon8231489123_vicuna-13b-GPTQ-4bit-128g" from the dropdown menu, the interface will automatically set wbits to 4, groupsize to 128, the chat mode to instruct, and the chat template to Vicuna. This is general and any interface parameter can be changed based on the model name.

The goal is to make command-line arguments completely optional.

**Comment by oobabooga** [comment]
I have added a `skip_special_tokens` checkbox here https://github.com/oobabooga/text-generation-webui/pull/1218

Apparently Dolly uses the Alpaca model format, so it should work.

I couldn't determine so far if this checkbox is working as intended. The code seems correct, but I couldn't get a generation without the special tokens that I typed in the input field.

**Comment by mcmonkey4eva** [comment]
The primary distinction from Alpaca format is it has `### End` as a dedicated stop token. In my earlier tests it output the token consistently but having it as stopping string didn't work in the webui (and so instead it just spams lines like `### Endings are so whatever etc`)

**Comment by mcmonkey4eva** [comment]
I can confirm aside from a typo I commented on that, and having my own Dolly file (Alpaca + stop string) and model config, that PR mostly works. Only limitation is the End of turn string doesn't stop generations.
![image](https://user-images.githubusercontent.com/4000772/232208958-bdf2d4d4-4eeb-4778-b22d-4dc3850d85de.png)

![image](https://user-images.githubusercontent.com/4000772/232208950-7cd8f359-2748-4c98-b8be-e9ab3f9d00f4.png)
(Note: I've confirmed via verbose logging in console that it is indeed exactly `### End` being output)

Model config I used that I think accounts for everything:
```yml
.*dolly-v[0-9]-[0-9]*b:
  mode: 'instruct'
  instruction_template: 'Dolly'
  skip_special_tokens: false
```
Could arguably narrow it down further if wanted and replace `.*` at the front with `(databricks_)?`

**Comment by oobabooga** [comment]
I think that the `### End` issue should have been resolved after the last commits in https://github.com/oobabooga/text-generation-webui/pull/1218/

@mcmonkey4eva can you check if the model is working as intended on your end? For me it seems to be working well.

> Could arguably narrow it down further if wanted and replace .* at the front with (databricks_)?

It's probably safer to use it as you proposed, as fine tunes by different authors might be uploaded.

**Comment by mcmonkey4eva** [comment]
Indeed appears to be working perfectly now! And right out of the box too, all automated, I love it.
