### ISSUE TITLE
Doesn't run on FireFox

### ISSUE THREAD

**Issue by nakatamaho** [oobabooga/text-generation-webui#1178]
### Describe the bug

text-generation-web-ui doesn't run when accessed by firefox.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

access by firefox on windows 10, docker image
Windows

### Screenshot

![image](https://user-images.githubusercontent.com/4800446/232057283-0bdb6f89-c1b2-46ee-9a5d-0570c82d09d4.png)
it doesn't proceed since "loading..."
However, when I change the browser to chrome or Microsoft Edge, web-ui works.

### Logs

```shell
nothing
```

### System Info

```shell
Windows 10
```

**Comment by jllllll** [comment]
I use FireFox and it works fine for me. Try clearing your browser cache.

**Comment by ltngonnguyen** [comment]
Another thing to take note it Firefox's aggressive adblock and tracker blocking. Turn off your adblocker, Firefox's default Tracking Protection (
![image](https://user-images.githubusercontent.com/72481740/232119325-60931c4e-d405-4714-b595-e636f9ab824d.png) ), at least for 127.0.0.1:7860 or localhost:7860 (assuming your port for Text Generation WebUI is 7860). 

Or just try it in Private Browsing mode. 

Mine was not loading before either, but after turing Chameleon, Adblock Plus, Privacy Badger and Tracking Protection, it worked.

**Comment by nakatamaho** [comment]
Hmm, none of them works for me. anyway, it does not seem to be a bug, and this issue can be closed.
