### ISSUE TITLE
GPTQ-for-LLaMa fork still uses Transformers from github

### ISSUE THREAD

**Issue by Malrama** [oobabooga/text-generation-webui#1182]
### Describe the bug

In the requirement.txt file of the GPTQ-for-LLaMa fork by oobabooga is still the github transformers. I will still trigger the installation of the current github version rather than 4.28.0 when running the 1 click installer.

This might also be changed to 4.28.0 like in the requitement.txt of text-generation-webui

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

No need

### Logs

```shell
No need
```

### System Info

```shell
No need
```

**Comment by oobabooga** [comment]
Fixed here https://github.com/oobabooga/GPTQ-for-LLaMa/blob/cuda/requirements.txt
