### ISSUE TITLE
RuntimeError: Triton Error [CUDA]: device kernel image is invalid

### ISSUE THREAD

**Issue by GenTxt** [oobabooga/text-generation-webui#1183]
Good news is that previous webui cuda repo, kernels,  and models still work 100% on 2 gpus. Those are keepers.

Large triton llama models will load on 2 gpus but the issue is with inference. 

All requirements installed as per current gptq-triton and webui.

Have tested in conda activate textgen and local python3.10 under Ubuntu 22.04

1) python server.py --wbits 4 --model triton-llama-30b-4bit-32g --groupsize 32 --listen --no-stream --gpu-memory 14 18

Loaded the model in 108.09 seconds.
Running on local URL:  http://0.0.0.0:7860

gpu0 14566MiB gpu1 5172MiB

2) python api-example.py

Traceback (most recent call last):
  File "<string>", line 21, in matmul_248_kernel
KeyError: ('2-.-0-.-0-83ca8b715a9dc5f32dc1110973485f64-d6252949da17ceb5f3a278a70250af13-3b85c7bef5f0a641282f3b73af50f599-3d2aedeb40d6d81c66a42791e268f98b-3498c340fd4b6ee7805fd54b882a04f5-e1f133f98d04093da2078dfc51c36b72-b26258bf01f839199e39d64851821f26-d7c06e3b46e708006c15224aac7a1378-f585402118c8a136948ce0a49cfe122c', (torch.float16, torch.int32, torch.float16, torch.float16, torch.int32, torch.int32, 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32', 'i32'), (16, 128, 32, 8), (True, True, True, True, True, True, (False, False), (True, False), (True, False), (False, False), (False, False), (True, False), (False, True), (True, False), (False, True), (True, False), (False, True), (True, False), (True, False)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

etc.

RuntimeError: Triton Error [CUDA]: device kernel image is invalid.

Same error if opening url in browser

Perhaps, one of the requirements needs to be upgraded?

**Comment by sgsdxzy** [comment]
What gpus are you using?
It seems you have two different gpus. You can try placing your old gpu before your new gpu (CUDA_VISIBLE_DEVICES=1,0)

**Comment by GenTxt** [comment]
RTX 3090 and refurbished RTX 6000.

And, unfortunately, loading triton models just got worse on this end.

I updated webui and gptq-triton to the latest versions and this time the model wouldn't load and quickly generated:

RuntimeError: Triton Error [CUDA]: device kernel image is invalid.

The worst part is that I didn't make a note of the commits I was using when first posted this issue. :(

Been trying various commit combos but no luck. If you can suggest a few I'll continue with trial and error.

Testing with (CUDA_VISIBLE_DEVICES=1,0)

**Comment by sgsdxzy** [comment]
Do you have all the cuda build environment (nvcc, cudnn, gcc, ninja, etc) installed? I have 2080Ti which is very similar to RTX6000 and I haven't had problem using triton.

**Comment by GenTxt** [comment]
Running under cuda 11.8 with all dependencies installed. No issues using standard HF models like neox 20b or opt in fp16 etc. Memory is shared on both cards.

Gptq has changed so much from last month and it looks like it's going to keep changing for better (or worse) based on the comments and issues in both repos.

Closing this as particular to my setup and will continue trial and error until hopefully something works.

Cheers

**Comment by GenTxt** [comment]
Found the culprit. The refurbished 6000 won't load triton kernels.

(CUDA_VISIBLE_DEVICES=0,1) loads 30b-4bit on gpu0 (3090) and executes 100%

(CUDA_VISIBLE_DEVICES=1,0) starts to load on gpu1 (6000) but at about 400+ megs generates

RuntimeError: Triton Error [CUDA]: device kernel image is invalid.

Will stick with large cuda models for now as they work perfectly with both gpus.
