### ISSUE TITLE
Add the Character's Memory section

### ISSUE THREAD

**Issue by Xabab** [oobabooga/text-generation-webui#119]
Putting statements after character's definition and after `<START>` statement but before the chat history is a great way to set up a custom memory, for example, putting this fragment:

+ `You:    Hello, my name is Name, I am 25, male and 1.7 meters tall`
+ `Giant: *you seem small, I tower above you with my 12 meters of height*`

I noticed it helps immensely against some things such as ignoring difference in height, butchering user's name, confusing user's pronouns or any other info that characters are usually struggling with.
It could be left as it is, but on each load of a character, a `<START>` statement is added at the end at the moment.

**Comment by oobabooga** [comment]
I have changed how the example dialogue is handled. Now it is added to the context string (which is never truncated) instead of the chat history. This way, the Character's Memory that you describe can now simply be added at the top of the example dialogue when creating or editing a character.

**Comment by Xabab** [comment]
Wouldn't call it a good solution, as it has to be unique to chat history, not per character. Plus the changes to the context text box aren't saved, so it is just as burdensome of a process, as you need to save your 'memory' elsewhere or edit json by hand quite often

**Comment by Xabab** [comment]
Hm. This actually produces another problem, as the example dialog eats up short-term memory, leaving less space for recent dialog. 

Maybe would be better to check the description for containing `<START>` or `Scenario: ` or both sub-strings?

**Comment by oobabooga** [comment]
Just make the character definition shorter.
