### ISSUE TITLE
When I click "Click Me" on (Character screen) it no longer generates a log of the current chat/instruction. 

### ISSUE THREAD

**Issue by viperwasp** [oobabooga/text-generation-webui#1203]
### Describe the bug

When I click "Click Me" on (Character screen) it no longer generates a log of the current chat/instruction. 

This either got caused when I did an update to the whole program. Reinstall does not fix. I also ran some Antivirus and registry changes. I can generate new note pads and I reinstalled notepad on my PC. 

I've of course restarted my pc and I've tried firefox and opera as the host browser. This is a new problem just from today. But I did a few things on my PC. 

Note pad is also missing from my right click "Create new" list. However it is is in my folders create new list. The one you can click on in the top menu settings inside explorer. The first thing is I guess I need to rule out if others having the issue or not. Next it would be nice to get some utility to auto save all logs or something as an option. 

Thanks for any advice anyone. If it's a bug I will simply wait for a fix. It's possible I may have messed something but but it may also be a design flaw of the program if it's dependant on just one specific thing to save the chat log. 

I have no logs or other info to share at this time. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

For me it's easy. Issue persists even if I restart PC, update or reinstall oobabooga. It worked last night. Today it does not work. 

### Logs

```shell
Not applicable.
```

### System Info

```shell
12700K, Nvidia 4080, Windows 10. Running locally on my PC not a colab etc. Like I said I tried firefox and opera. Issue seems persistent.
```

**Comment by oobabooga** [comment]
Fixed here https://github.com/oobabooga/text-generation-webui/commit/c4aa1a42b156b9c5ddcfb060cc497b2fba55430f
