### ISSUE TITLE
Extension of the 2048 token limit

### ISSUE THREAD

**Issue by AstroOrbis** [oobabooga/text-generation-webui#1214]
**Description**

A way to modify the 2048 token limit mentioned in [the wiki](https://github.com/oobabooga/text-generation-webui/wiki/Custom-chat-characters).

**Additional Context**

Could be useful, I don't know

**Comment by da3dsoul** [comment]
That depends on the model. LLaMA can only handle 2048 tokens, and that's just a part of the model. Better-read people may comment, but that's what I came to from my reading

**Comment by AstroOrbis** [comment]
Does the webui allow changing the maximum depending on the model then?

**Comment by da3dsoul** [comment]
I don't believe so

**Comment by oobabooga** [comment]
This is already a slider in the interface, and the minimum/maximum values can be set using a settings.json file

Most models only with with 2048 context size
