### ISSUE TITLE
Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack

### ISSUE THREAD

**Issue by VertexMachine** [oobabooga/text-generation-webui#122]
I tried to follow the instructions as much as I can and I clicked on link you provided to GPT-NEO models (https://huggingface.co/models?pipeline_tag=text-generation&sort=downloads&search=eleutherai+%2F+gpt-neo) selected the 20b version and downloaded it with:

`python download-model.py EleutherAI/gpt-neox-20b`

And now when I try to run it, I get 

```
Traceback (most recent call last):
  File "F:\LLMs\text-generation-webui\server.py", line 949, in <module>
    model, tokenizer = load_model(model_name)
  File "F:\LLMs\text-generation-webui\server.py", line 185, in load_model
    model = eval(command)
  File "<string>", line 1, in <module>
  File "C:\Users\USERNAME\mambaforge\envs\textgen\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\USERNAME\mambaforge\envs\textgen\lib\site-packages\transformers\modeling_utils.py", line 2275, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models\gpt-neox-20b.
```

The error message is correctly pointing out to those files are being missing for this model. This happens with some others as well.

Is there something I can do to convert the model to the expected format?

**Comment by oobabooga** [comment]
This usually means that the download was interrupted and some files are missing or corrupt. Try downloading again.

**Comment by VertexMachine** [comment]
Thanks for the quick answer! On it, redownloading. Will updated after it finishes.

**Comment by VertexMachine** [comment]
Didn't work. Downloaded without issues, here is a screenshot of the end of download:

![image](https://user-images.githubusercontent.com/35311995/221194560-7a192d0d-d1a7-4077-97ce-39679f4d7495.png)


(the last line is from my rc file that just puts name of environment there)

**Comment by VertexMachine** [comment]
this is the content of the models/gpt-neox-20b directory after download:

![image](https://user-images.githubusercontent.com/35311995/221195196-19c3a6e0-48c6-4b29-97bb-d4bd0cd5044f.png)

**Comment by oobabooga** [comment]
This was indeed a bug caused by gpt-neox-20b having too many files in the repository, so that the page had a "Load more" button.

I have updated the download script. Try doing this to download the files that you are missing:

```
git pull
python download-model.py EleutherAI/gpt-neox-20b --text-only
```

**Comment by VertexMachine** [comment]
Fantastic! It works perfectly now!

**Comment by Lennart-Lucas** [comment]
I have the same issue with mayaeary/pygmalion-6b_dev-4bit-128g.
I tried running the download-model.py with the following command:
`python download-model.py mayaeary/pygmalion-6b_dev-4bit-128g --text-only`

But this gives the following error:
```
C:\Users\USER\Documents\Github\oobabooga-windows\text-generation-webui>python3 download-model.py mayaeary/mayaeary/pygmalion-6b_dev-4bit-128g --text-only
Traceback (most recent call last):
  File "C:\Users\USER\Documents\Github\oobabooga-windows\text-generation-webui\download-model.py", line 260, in <module>
    links, sha256, is_lora = get_download_links_from_huggingface(model, branch, text_only=args.text_only)
  File "C:\Users\USER\Documents\Github\oobabooga-windows\text-generation-webui\download-model.py", line 103, in get_download_links_from_huggingface
    fname = dict[i]['path']
KeyError: 0
```

**Comment by StingrayA** [comment]
> This was indeed a bug caused by gpt-neox-20b having too many files in the repository, so that the page had a "Load more" button.
> 
> I have updated the download script. Try doing this to download the files that you are missing:
> 
> ```
> git pull
> python download-model.py EleutherAI/gpt-neox-20b --text-only
> ```

where to put this command?

**Comment by gandolfi974** [comment]
same problem with model "TheBloke_Wizard-Vicuna-13B-Uncensored-GPTQ"

**Comment by oobabooga** [comment]
Try adding `--wbits 4 --groupsize 128` (or selecting those settings in the interface and reloading the model)

**Comment by Johnnycyan** [comment]
> Try adding `--wbits 4 --groupsize 128` (or selecting those settings in the interface and reloading the model)

Adding those for me with TheBloke_Wizard-Vicuna-30B-Uncensored-GPTQ just loads the model into ram and then immediately quits, unloads the model and says
"Done!"
Press any key to continue...

**Comment by vipen07** [comment]
Download pytorch_model.bin file separately and delete previous file and reupload that file under your pretrained model in your editor

**Comment by FunkyRatz** [comment]
Apparently mayaeary/pygmalion-6b-4bit-128g is missing those files. None of them can be found on It's Huggingface page (https://huggingface.co/mayaeary/pygmalion-6b-4bit-128g/tree/main)

**Comment by Diogovidro33** [comment]
im a newbie i dont know what to do
