### ISSUE TITLE
10x slowdown using Vicuna 13b 4bit commit f2bf1a2 onwards

### ISSUE THREAD

**Issue by Grimulkan** [oobabooga/text-generation-webui#1220]
### Describe the bug

Commit 5744b315930c6b0fd4dc6c1df96b2724253366d8 is fine (~10 tok/s).
Commit f2bf1a2c9e0074ea7cb98e6d9176940998ba0559 and later is 10x slower in streaming mode (<1 tok/s) 

All other package installs & options are the same between the 2 commits.

I only tested chat mode with streaming, and only Vicuna 13b 4-bit 128g true-seq, so I don't know if other situations are impacted. I am using custom stopping strings (\n###) to shut Vicuna up.

Hopefully narrowing it down to the commit helps figure out the issue.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Any text generation, any length, is slower on anything later than the stated commit.

### Logs

```shell
No errors generated
```

### System Info

```shell
Windows 10 (non-WSL) with CUDA (2x RTX4090, 2x RTX3090, though only one 4090 is being used for this test). Using oobabooga's fork of GPTQ (CUDA branch).
```

**Comment by oobabooga** [comment]
You may be loading two different models in the two different commits

**Comment by Grimulkan** [comment]
I didn't change the command line, but you mean something might have overridden it? I'll reload the model in the UI and check. The startup message showed the same model name for both loads.

**Comment by bloodsign** [comment]
No issues on my side. I'm running anon's vicuna-4bit-128g and also TheBlokes new vicuna-1.1-4bit-128g models.

**Comment by HideLord** [comment]
Yeah, same here, kind of. Just reverted back to `5744b31` and got ~7 tokens for gpt4-x-alpaca. With the latest commit, I'm getting variable 3-5 tokens, sometimes going to 1.

Here's my start script:
```
cd text-generation-webui
python server.py --gpu-memory 20 20 --sdp-attention --model chavinlo_gpt4-x-alpaca --xformers --chat --load-in-8bit
```

**Comment by Ph0rk0z** [comment]
What file are the models loading, post yer logs.

**Comment by Grimulkan** [comment]
Common to both runs:
```
Command Line: python server.py --chat --cpu-memory 200GiB --auto-devices --listen-port 6565 --wbits 4 --groupsize 128 --model vicuna-13b-4bit-128g --model_type LLaMA
Prompt: Write a paragraph about the state of the world
Seed: 1
```

On commit 5744b315930c6b0fd4dc6c1df96b2724253366d8 (the older good one):
```
Loading vicuna-13b-4bit-128g...
Found the following quantized model: models\vicuna-13b-4bit-128g\vicuna-13b-4bit-128g.pt
Loading model ...
Done.
Loaded the model in 24.36 seconds.
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:6565

To create a public link, set `share=True` in `launch()`.
Output generated in 10.39 seconds (12.51 tokens/s, 130 tokens, context 22, seed 1)
```

And on commit f2bf1a2c9e0074ea7cb98e6d9176940998ba0559 (the very next commit):
```
Loading vicuna-13b-4bit-128g...
Found the following quantized model: models\vicuna-13b-4bit-128g\vicuna-13b-4bit-128g.pt
Loading model ...
Done.
Using the following device map for the quantized model: {'model.embed_tokens': 0, 'model.layers.0': 0, 'model.layers.1': 0, 'model.layers.2': 0, 'model.layers.3': 0, 'model.layers.4': 0, 'model.layers.5': 0, 'model.layers.6': 0, 'model.layers.7': 1, 'model.layers.8': 1, 'model.layers.9': 1, 'model.layers.10': 1, 'model.layers.11': 1, 'model.layers.12': 1, 'model.layers.13': 1, 'model.layers.14': 1, 'model.layers.15': 1, 'model.layers.16': 1, 'model.layers.17': 1, 'model.layers.18': 2, 'model.layers.19': 2, 'model.layers.20': 2, 'model.layers.21': 2, 'model.layers.22': 2, 'model.layers.23': 2, 'model.layers.24': 2, 'model.layers.25': 2, 'model.layers.26': 2, 'model.layers.27': 2, 'model.layers.28': 2, 'model.layers.29': 3, 'model.layers.30': 3, 'model.layers.31': 3, 'model.layers.32': 3, 'model.layers.33': 3, 'model.layers.34': 3, 'model.layers.35': 3, 'model.layers.36': 3, 'model.layers.37': 3, 'model.layers.38': 3, 'model.layers.39': 3, 'model.norm': 3, 'lm_head': 3}
Loaded the model in 8.33 seconds.
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:6565

To create a public link, set `share=True` in `launch()`.
Output generated in 64.02 seconds (2.03 tokens/s, 130 tokens, context 22, seed 1)
```

In the 2nd case: model actually loaded faster, but the inference speed was much slower. The response text was the same in both cases. 

I also tried a non-quantized model (alpaca-13b):

On commit 5744b315930c6b0fd4dc6c1df96b2724253366d8:
```
Loading checkpoint shards: 100%|¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 6/6 [00:27<00:00,  4.56s/it]
Loaded the model in 27.95 seconds.

Output generated in 49.41 seconds (2.63 tokens/s, 130 tokens, context 22, seed 2)
```

and on commit f2bf1a2c9e0074ea7cb98e6d9176940998ba0559:
```
Loading checkpoint shards: 100%|¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 6/6 [02:38<00:00, 26.39s/it]
Loaded the model in 158.94 seconds.

Output generated in 43.81 seconds (2.97 tokens/s, 130 tokens, context 22, seed 2)

```
The inference speed between the 2 commits is similar for the non-quantized model. 

I am using https://github.com/qwopqwop200/GPTQ-for-LLaMa by the way (for both runs).

**Comment by Ph0rk0z** [comment]
So what looks to be happening is that you are using different device maps for offloading between those 2 versions. i don't think the commit is what did it. Get rid of CPU memory and see what happens and then get rid of auto devices. Make it only dispatch to one GPU.

**Comment by Grimulkan** [comment]
Just tried with this command line (no auto devices and CPU mem):
`python server.py --chat --listen-port 6565 --wbits 4 --groupsize 128 --model vicuna-13b-4bit-128g --model_type LLaMA`

Same results as before unfortunately :( If anything, it is slower. On the new commit:
`Output generated in 72.25 seconds (1.80 tokens/s, 130 tokens, context 22, seed 1)`

The device map doesn't show in the log automatically for the previous commit. Is there a way I can capture it?

Also, I mistakenly pasted the wrong GPTQ repo I was using. I'm  using https://github.com/oobabooga/GPTQ-for-LLaMa CUDA branch (no other choice, since I foolishly updated Windows 10 to the latest release branch, with no way to get WSL + GPU support for Triton, even on insider).

**Comment by Grimulkan** [comment]
No, actually you were correct. Somehow it manage to put it on multiple GPUs. Forcing CUDA_VISIBLE_DEVICES=0 got it to work. On newer commit:
`Output generated in 11.20 seconds (11.61 tokens/s, 130 tokens, context 22, seed 1)`

So the automatic device mapping was changed in that commit maybe?

**Comment by Grimulkan** [comment]
Confirmed: it works fine on the latest commit as long as I set CUDA_VISIBLE_DEVICES=0. Even with my original command line.

Guess I'll just manually enable CUDA devices & control the device map depending on what model I load. Maybe there's a way to figure out the best way to do that automatically.

**Comment by Ph0rk0z** [comment]
Yea.. you have too many GPUs... and all this makes me real sad for how multi-processing behaves in accelerate and pytorch.

I want to make a ML server but it looks like more GPUs will only help training or putting them on specific tasks like SD/TTS.

**Comment by Dmpozd** [comment]
Pls tell me where I can set CUDA_VISIBLE_DEVICES=0 ? I have the same problem//

**Comment by Grimulkan** [comment]
You can do it in the batch file in Windows that launches the web ui. After you call activate.bat, set CUDA_VISIBLE_DEVICES=0 (export instead of set in Linux/WSL)
