### ISSUE TITLE
AVX-512 support for llama.cpp models

### ISSUE THREAD

**Issue by RahulVivekNair** [oobabooga/text-generation-webui#1223]
**Description**

Currently when loading llama.cpp models through the webui, on inspecting the command line, only avx2 flags have been set. I want to enable avx-512 like in regular llama.cpp to improve the speed. Any way I can compile it with the avx-512 flag?

![image](https://user-images.githubusercontent.com/68507071/232201308-0198581c-b014-4c98-97d0-f07cebbcb66d.png)

**Comment by gabriel-peracio** [comment]
Edit the `CMakeLists.txt` and change the proper flags from `OFF` to `ON`, then build again. Then they will be detected. Doesn't seem to change the speed at all, though.

**Comment by RahulVivekNair** [comment]
Can't find CMakeLists.txt, it seems to be using a python binding to llama.cpp instead. Cant find where to compile with the flags ON. @gabriel-peracio

**Comment by gabriel-peracio** [comment]
Ah, right. I was talking about [this](https://github.com/ggerganov/llama.cpp/blob/master/CMakeLists.txt#L57)
I wonder if you can just swap the binaries in your installation... they do release AVX512 binaries in their [releases section](https://github.com/ggerganov/llama.cpp/releases)
But to be clear, don't expect major changes when turning those on.
