### ISSUE TITLE
It's very likely that GPTQ's code won't work.

### ISSUE THREAD

**Issue by qwopqwop200** [oobabooga/text-generation-webui#1224]
The location of the current GPTQ file has been changed and the name of the function has also been changed.
ex: make_quant -> quant.make_quant_linear
See this function.
https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/triton/llama.py#L8
https://github.com/qwopqwop200/GPTQ-for-LLaMa/blob/triton/llama.py#L234
Added [fused MLP](https://github.com/fpgaminer/GPTQ-triton/commit/600e214dc6590049f61c86477cbc95b4301450ca) for additional speed boost. I saw a speedup of roughly 10%. 
@oobabooga

**Comment by sgsdxzy** [comment]
I have prepared a patch for webui. The problem is, I myself cannot get the new fused_mlp to work https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/179

**Comment by Ph0rk0z** [comment]
Triton support for pre volta cards isn't finished.

**Comment by sgsdxzy** [comment]
> Triton support for pre volta cards isn't finished.

Yes, but I have 2080 Ti, which is Turing, after Volta.

**Comment by diegomontoya** [comment]
@qwopqwop200 Can you verify that the latest changes did not break inference? Inference appears to be broken on my 30b 4bit, groupsize=-1 model with latest changes. Or do we need to re-quantize using latest code?

Currently re-quantizing to see if it makes any difference.

**Comment by qwopqwop200** [comment]
No I wouldn't have broken the inference.  I've confirmed that it works for at least 128groupsize.

**Comment by diegomontoya** [comment]
@qwopqwop200  I have confirmed the breakage is at commit which modified attention code. New tokens, tokens beyond the prompt, are all 1 which is strange. Checking out to a commit before the change is fine. 

https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/183

**Comment by oobabooga** [comment]
I think that this should have been fixed.
