### ISSUE TITLE
No model is loaded! Select one in models tab

### ISSUE THREAD

**Issue by kaorts** [oobabooga/text-generation-webui#1230]
### Describe the bug

after installing files for the graphics card and later after downloading the models. when i run the file start-webui this is what i get
Starting the web UI...
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
No model is loaded! Select one in the Model tab.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

after installing files for the graphics card and later after downloading the models. when i run the file start-webui this is what i get
Starting the web UI...

### Logs

```shell
Starting the web UI...
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
No model is loaded! Select one in the Model tab.
```

### System Info

```shell
OS Name	Microsoft Windows 11 Home Single Language
Processor	12th Gen Intel(R) Core(TM) i7-12700H, 2700 Mhz, 14 Core(s), 20 Logical Processor(s)
Installed Physical Memory (RAM)	16.0 GB
nvidia geforce rtx 3060  laptop gpu 8gb
```

**Comment by bloodsign** [comment]
Go to models tab and select the models you downloaded from the dropdown. 
![image](https://user-images.githubusercontent.com/12083007/232225686-760da08b-c344-443e-ab4f-09bf0cf7fd33.png)

**Comment by elcotek** [comment]
I have the same problem when I try to activate the google translator. It can no longer be activated and the program surface then crashes completely. If selected but not yet restarted, you can no longer reload models. This is definitely a bug that didn't exist before.

**Comment by Loli-Kyn** [comment]
I put the model, but he still writes that it is not there
![image](https://user-images.githubusercontent.com/52761837/236065698-45d48b91-f636-452d-b7c1-58ad564fcf5d.png)

**Comment by KeepCreatingOnline** [comment]
im having this issue as well
