### ISSUE TITLE
--gpu-memory Not working

### ISSUE THREAD

**Issue by Bennett-Fourr** [oobabooga/text-generation-webui#1235]
### Describe the bug

Adding --gpu-memory 6 dose not change how much GPU memory is being used. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use the auto installer
In the run bat file add --gpu-memory 
load a moddle 

### Screenshot

In the batch file I do this 
![Screenshot 2023-04-15 101726](https://user-images.githubusercontent.com/94060774/232230027-0b46e1ec-a606-439c-8575-5f7df60d0400.png)
But it showes this when loading
![Screenshot 2023-04-15 101749](https://user-images.githubusercontent.com/94060774/232230065-34385feb-eabb-4a0f-9754-df5505761693.png)

### Logs

```shell
Auto-assiging --gpu-memory 7 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
```

### System Info

```shell
GPU-RTX 3060-TI
```

**Comment by oobabooga** [comment]
This should be fixed now
