### ISSUE TITLE
start webui won't ask me wich model i want to use.

### ISSUE THREAD

**Issue by LeitTheLich** [oobabooga/text-generation-webui#1238]
Installed 2 Models to see if it was because i only hade one model befor, still after multiple trys i dont find a solution myself, It just wont ask me wich model i want to use.

On Windows
NVIDIA installation way

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/130851904/232233645-e6a9c959-6e11-466c-b1d5-8b313a2effe7.png">

**Comment by Steelman14aUA** [comment]
Open webui, and select it from models..

**Comment by oobabooga** [comment]
Use --model-menu if you want the old menu
