### ISSUE TITLE
Flatpak build 

### ISSUE THREAD

**Issue by LeandroStanger** [oobabooga/text-generation-webui#1246]
Please, consider supporting [Flatpak](http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak) and publishing **Text generation web UI** on [Flathub](https://github.com/flathub/flathub/wiki/App-Submission).

**Comment by sarutobiumon** [comment]
Please support this initiative as it would turn the world's number 1 School/Education focused Linux distro "Endless OS" into a truely endless OS. 

https://www.endlessos.org/os

**Comment by LeandroStanger** [comment]
##.

**Comment by RasheedAZ** [comment]
Related to #6167 Please reopen this issue. Thanks.
