### ISSUE TITLE
No model is loaded! Select one in the Model tab

### ISSUE THREAD

**Issue by Sempai2233** [oobabooga/text-generation-webui#1255]
### Describe the bug

everytime i try to load up start-webui i get the message :
Starting the web UI...
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.---- (blurred)

then i launch the web page, i dont even have to pick a model or something, and i try to say something and it tells me this : 
No model is loaded! Select one in the Model tab.

i have no clue what to do, please help.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

i just fire up start-webui. 

i dont know what i am doing wrong

### Screenshot

![Knipsel2](https://user-images.githubusercontent.com/125715812/232260998-3702e66d-07c1-4488-b413-69d68b29ff11.JPG)

### Logs

```shell
Starting the web UI...
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
No model is loaded! Select one in the Model tab.
```

### System Info

```shell
os: windows 10
gpu 3070
cpu ryzen 9 5900x
```

**Comment by oobabooga** [comment]
Select a model in the Model tab

**Comment by WhatDeFuuu** [comment]
bruh that doesnt explain what we gotta do

**Comment by kalon43** [comment]
for me it still doesn´t work

**Comment by Jordunnn** [comment]
why you deleting my genuine criticism? Why reply ignorantly to an issue several users have and not even address it

**Comment by KabaTubare** [comment]
Having the same issue even though I downloaded the model from terminal and it is visible within the tab where I am asked to select. Despite selecting the model, setting the parameters at wbits 4 and group size 128  and model type as llama, and saving and reloading I still get this error after multiple attempts: 2023-06-14 10:56:23 ERROR:No model is loaded! Select one in the Model tab.
2023-06-14 10:56:52 ERROR:No model is loaded! Select one in the Model tab.
2023-06-14 10:57:06 ERROR:No model is loaded! Select one in the Model tab.
2023-06-14 10:57:26 ERROR:No model is loaded! Select one in the Model tab.
2023-06-14 10:57:34 INFO:Saved /Users/txxxxxxxxxxxx/text-generation-webui/prompts/2023-06-14-105733.txt.
2023-06-14 10:58:27 ERROR:No model is loaded! Select one in the Model tab.
2023-06-14 10:58:30 ERROR:No model is loaded! Select one in the Model tab.
2023-06-14 10:58:34 ERROR:No model is loaded! Select one in the Model tab.
2023-06-14 10:58:36 ERROR:No model is loaded! Select one in the Model tab.

**Comment by Zaklearnin** [comment]
same exact situation as @KabaTubare  , hope we get a resolution soon

**Comment by GuruGhantal** [comment]
I have already downloaded the model from webui download model tab STILL showing no model loaded, help, same situation as Kara tura

**Comment by catastrophical0** [comment]
same

**Comment by Tecquo** [comment]
Yeah, same.

**Comment by Gintas2002** [comment]
same

**Comment by JoNoahBros** [comment]
Same

**Comment by StepIg** [comment]
hahahaha, what a help, right?

**Comment by cleberbr10** [comment]
estou esse erro aqui ?ERROR    No model is loaded! Select one in the Model tab.
