### ISSUE TITLE
When using Instruct mode with vicuna and relaunch the browser the stop pattern will be wrong again

### ISSUE THREAD

**Issue by shawhu** [oobabooga/text-generation-webui#1265]
### Describe the bug

Context:
When using a vicuna model the instruct with vicuna is the only way to chat normally without AI continue on its own.

set instruct in the settings.json and launch with it as a param and,
If I close the browser and reopen it, the Mode is still set to Instruct and vicuna was selected. But the AI will continue on its own just like the Instruct->vicuna was not in effect.  If I select another one and reselect vicuna again, the problem will be fixed

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. select instruct mode, select vicuna
2. close the browser
3. reopen the browser and try to chat, the AI will continue by itself, it doesn't stop when it should.

### Logs

```shell
No error shows in the prompt windows. It's not an error on the server side, It's just js code or frontend bug. I guess.
```

### System Info

```shell
Windows 10 with nvidia rtx 3090
```

**Comment by catalpaaa** [comment]
try vicuna v1.1

**Comment by shawhu** [comment]
I was using v1.1 and I am aware that problem I saw it on huggingface discussion.
Anyway, today I pull the latest updates and it seeems the problem has gone. I'm closing this issue.
