### ISSUE TITLE
api-example-stream doesn't work. Changed fn_index?

### ISSUE THREAD

**Issue by Cohee1207** [oobabooga/text-generation-webui#1268]
### Describe the bug

api-example-stream script produces a console error, no text is streamed to the output. Possibly Gradio changed fn_index?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Update Textgen UI to the latest version
2. Run it with the model. Make sure no_stream option is not checked
3. Run python api-example stream.py
4. Observe the issue below

### Logs

```shell
textgen output


    output = await app.get_blocks().process_api(
  File "C:\Users\User\miniconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 1191, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "C:\Users\User\miniconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 1027, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "C:\Users\User\miniconda3\envs\textgen\lib\site-packages\gradio\blocks.py", line 1014, in validate_inputs
    raise ValueError(
ValueError: An event handler (do_train) didn't receive enough input values (needed: 20, got: 1).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [textbox, checkbox, number, slider, slider, number, textbox, slider, slider, slider, slider, dropdown, dropdown, dropdown, number, dropdown, slider, slider, checkbox, checkbox]
Received inputs:
    ["["What I would like to say is the following: ", {"max_new_tokens": 200, "do_sample": true, "temperature": 0.5, "top_p": 0.9, "typical_p": 1, "repetition_penalty": 1.05, "encoder_repetition_penalty": 1.0, "top_k": 0, "min_length": 0, "no_repeat_ngram_size": 0, "num_beams": 1, "penalty_alpha": 0, "length_penalty": 1, "early_stopping": false, "seed": 3, "add_bos_token": true, "truncation_length": 2048, "custom_stopping_strings": [], "ban_eos_token": false}]"]
```

api-example-stream output

```
{"session_hash": "ah79d9lcc", "fn_index": 29, "data": ["[\"What I would like to say is the following: \", {\"max_new_tokens\": 200, \"do_sample\": true, \"temperature\": 0.5, \"top_p\": 0.9, \"typical_p\": 1, \"repetition_penalty\": 1.05, \"encoder_repetition_penalty\": 1.0, \"top_k\": 0, \"min_length\": 0, \"no_repeat_ngram_size\": 0, \"num_beams\": 1, \"penalty_alpha\": 0, \"length_penalty\": 1, \"early_stopping\": false, \"seed\": 3, \"add_bos_token\": true, \"truncation_length\": 2048, \"custom_stopping_strings\": [], \"ban_eos_token\": false}]"]}Traceback (most recent call last):  File "C:\text-generation-webui\api-example-stream.py", line 93, in <module>    asyncio.run(get_result())
  File "C:\Users\User\miniconda3\envs\textgen\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\User\miniconda3\envs\textgen\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\text-generation-webui\api-example-stream.py", line 86, in get_result
    async for response in run(prompt):
  File "C:\text-generation-webui\api-example-stream.py", line 76, in run
    yield content["output"]["data"][0]
KeyError: 'data'
```
```


### System Info

```shell
1. Windows 11
2. Nvidia RTX 3090
3. Model: llama-13b-4bit-128g
```

**Comment by bmoconno** [comment]
Yeah looks like it's 45 now? I'd say give that a try and see if it works, if so, you can put in a PR to update the value.

**Comment by MikoAL** [comment]
I have the same issue, could it be that the wanted inputs and received input are completely different?

NOTE: I am very new to programming as a whole, so my answer could be completely stupid, sorry in advance.

**Comment by MikoAL** [comment]
> Yeah looks like it's 45 now? I'd say give that a try and see if it works, if so, you can put in a PR to update the value.

I tried  GRADIO_FN = 45

ValueError: An event handler (regenerate_wrapper) didn't receive enough input values (needed: 2, got: 1).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [state, state]
Received inputs:
    ["["What I would like to say is the following: ", {"max_new_tokens": 200, "do_sample": true, "temperature": 0.5, "top_p": 0.9, "typical_p": 1, "repetition_penalty": 1.05, "encoder_repetition_penalty": 1.0, "top_k": 0, "min_length": 0, "no_repeat_ngram_size": 0, "num_beams": 1, "penalty_alpha": 0, "length_penalty": 1, "early_stopping": false, "seed": -1, "add_bos_token": true, "truncation_length": 2048, "custom_stopping_strings": [], "ban_eos_token": false}]"]

The wanted inputs changed? but I don't think it's the correct number for GRADIO_FN

**Comment by MikoAL** [comment]
After a google search on ws, I think I found mine.
It should be possible in theory to do this programmatically?
Tho I lack the knowledge and intellect to do that.

**Comment by MikoAL** [comment]
So um new problem?
The results of the api-example-stream.py is always 
None
None

I checked the websocket of the browser dev network tab and found out that first, the requests by the script is not in there (Though that might be normal? I really don't know)
and second, even when I was using the web ui to generate the responses, the thing that the script is trying to print as result

content["output"]["data"][0]

was always returning Null?

Here is the thing
{"msg": "process_completed", "output": {"data": [null, ""], "is_generating": false, "duration": 0.0, "average_duration": 0.00016287962595621744}, "success": true}

Any ideas?

**Comment by digiwombat** [comment]
I tried 0-50 just for kicks. I couldn't get data back across any of them with Tavern.

The webui itself is sending calls to fn_index numbers of 35, 36, and 37.

I didn't get any console errors on 35 or 45, and Tavern's API reported success, but no text got generated. Dunno if the message structure changed or anything. Only recent thing I see is the eos_token change revert in generate_reply.

**Comment by oobabooga** [comment]
This seems to have fixed it: https://github.com/oobabooga/text-generation-webui/commit/4e035cc3fb45e5e5464710b9f060598f6064b346

I don't really know how to find this index automatically. An alternative is to use this API with streaming extension in this PR https://github.com/oobabooga/text-generation-webui/pull/990

@Cohee1207 can you check if this would be a good alternative for your project? I haven't accepted it yet because there are already two available APIs (with 2 ways to use the gradio native one) and I thought it would be confusing to have a third one.

**Comment by digiwombat** [comment]
I think the raw Gradio endpoint feels a bit fragile given this exact issue so a streaming API extension might be just the ticket.

Then you don't have to pay any mind to your overall code structure in regards to external calls that want streaming and maintainers for other projects that want to ingest streaming tokens have a stable way to do it that won't require changes even if the code-base changes. Raw Gradio API is rough for maintainers, rough for end users, and hard to troubleshoot even for power users.

It might be also worth formalizing the gradio non-streaming api into a base `api` extension, the Kobold API would become `api_kobold` so it's clear it's for an outside compatibility API, and `api_streaming` for people who want the websocket version.

Or having the base API extensions contain native streaming and non-streaming endpoints to avoid having two extensions.

So something like  
`api/v1/reply`  
and  
`api/v1/reply/stream`

**Comment by oobabooga** [comment]
> Or having the base API extensions contain native streaming and non-streaming endpoints to avoid having two extensions.

That's a great idea.

**Comment by oobabooga** [comment]
FYI: the old gradio API has been removed and replaced with an updated version of the API extension. This new API has two endpoints, one for streaming at `/api/v1/stream` port 5005 and one for blocking at `/api/v1/generate` por 5000. It should work by simply starting the web UI with

```
python server.py --model MODEL --api
```

Optionally, a public cloudfare URL can be generated with 

```
python server.py --model MODEL --public-api
```

The examples have been updated:

https://github.com/oobabooga/text-generation-webui/blob/main/api-example.py
https://github.com/oobabooga/text-generation-webui/blob/main/api-example-stream.py

PR link: https://github.com/oobabooga/text-generation-webui/pull/990
