### ISSUE TITLE
References to "Windows" in requirements.txt breaks install with conda --file requirements.txt

### ISSUE THREAD

**Issue by tensiondriven** [oobabooga/text-generation-webui#1271]
### Describe the bug

Can't install on Ubuntu using conda w/ requirements.txt:

Clean system w/ Miniconda3

```
$ conda install --file requirements.txt 

CondaValueError: could not parse 'https://github.com/abetlen/llama-cpp-python/releases/download/v0.1.34/llama_cpp_python-0.1.34-cp310-cp310-win_amd64.whl; platform_system == "Windows"' in: requirements.txt
```

Removing all of the references to "Windows" solves it for me.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1) Clean ubuntu w/ nvidia-smi working (Ubuntu 22.04)
2) Clone repo at a3eec62b50cae3fda149380d75ae5b4b01b91dcb
3) Install miniconda
4) `conda install --file requirements.txt`

### Logs

```shell
See issue body
```

### System Info

```shell
Ubuntu 22.04LTS
```

**Comment by jllllll** [comment]
Requirements.txt file is intended to be installed using pip. Those 'windows' entries are for compatibility with Windows as some packages don't work with Windows and some only work with Windows.

**Comment by tensiondriven** [comment]
Ok, I'll close.  Follow-on question: is requirements.txt generally considered to be compatible with Conda?

**Comment by jllllll** [comment]
Not really. It can be, but generally you want to have a package list that is written specifically for Conda. The standard format for listing packages for a Conda environment is [Conda's environment YAML](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually).

This is used by Conda's `conda env create -f environment.yml` command. Micromamba has a similar command, but also supports specifying a YAML file with it's install command `micromamba install -f environment.yml`.
