### ISSUE TITLE
Character images in selector

### ISSUE THREAD

**Issue by Slug-Cat** [oobabooga/text-generation-webui#128]
A feature I particularly like in TavernAI is the presence of accompanying images for characters who have them in the selection menu. I don't know how this would work with Gradio, but it would be quite convenient when searching through the long list of names without referring back to the images in the character folder.

**Comment by oobabooga** [comment]
It should be possible to create an extension that shows a table with the characters and their images using an HTML gradio element. That would be pretty cool.

https://github.com/oobabooga/text-generation-webui/wiki/Extensions

**Comment by oobabooga** [comment]
Here it is. It doesn't do anything, but it at least gives a reference for each character. Use with

```
--extensions gallery
``` 

Source:
https://github.com/oobabooga/text-generation-webui/blob/main/extensions/gallery/script.py

![print](https://user-images.githubusercontent.com/112222186/221420817-3475db2d-a078-4be5-a1aa-4bccc4124204.png)

**Comment by Slug-Cat** [comment]
> Here it is. It doesn't do anything, but it at least gives a reference for each character. Use with
> 
> ```
> --extensions gallery
> ```
> 
> Source: https://github.com/oobabooga/text-generation-webui/blob/main/extensions/gallery/script.py
> 
> ![print](https://user-images.githubusercontent.com/112222186/221420817-3475db2d-a078-4be5-a1aa-4bccc4124204.png)

Neato. Not exactly what I had in mind, but it serves the same purpsoe well enough. Thanks.

**Comment by oobabooga** [comment]
The elements are clickable now too. 

https://github.com/oobabooga/text-generation-webui/commit/7a776ccf8715bbe4e6934772fd135d54e4d24f78
