### ISSUE TITLE
 Adding a database for long term memory

### ISSUE THREAD

**Issue by treeoflovely** [oobabooga/text-generation-webui#1281]
I have been working with chat GPT4 to add a memory feature to this interface. We have completed scripts and a database, etc but how do we implement it? Would it work as a module, api interface? I know very little to nothing about coding so if someone things this is worthwhile let's work on it.

**Comment by Ph0rk0z** [comment]
You mean like this? https://github.com/oobabooga/text-generation-webui/discussions/675
