### ISSUE TITLE
Can't choose groupsize 128 on the Model Tab

### ISSUE THREAD

**Issue by BadisG** [oobabooga/text-generation-webui#1286]
### Describe the bug

Hello,
I can't choose 128 in the groupsize parameter even though the model I try to load was quantized with groupsize 128
![NEDtwuv](https://user-images.githubusercontent.com/110173477/232348551-1a99fc80-009f-41de-9aff-a4b76c23445b.png)

That means I can't load my models anymore, has someone a fix on that? 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

my cmdline arg

python server.py --wbits 4 --groupsize 128 --notebook

### Logs

```shell
No logs
```

### System Info

```shell
Windows 10 + WSL2
```

**Comment by oobabooga** [comment]
This shouldn't be possible. The 128 option is hard coded

https://github.com/oobabooga/text-generation-webui/blob/main/server.py#L342

**Comment by BadisG** [comment]
Well, you can see on the screen there's no 128 in there, for the 7 models I have there's 5 of them that I can't choose 128, meaning I can load them anymore.

And for the 2 others I can load... I have this now...
![kHualLT](https://user-images.githubusercontent.com/110173477/232614984-3732593f-4273-435b-8917-d5dac0372b3b.png)

That never happened before on any of my models, and because of that, the models loads in 200 seconds instead of the regular 30-40 seconds before

Something's definitely broken from the new commits

**Comment by BadisG** [comment]
@oobabooga Oh yeah sorry dude, I was using a google chrome extension that removes some buttons and I didn't notice it removed the "128" button.

Now it works as intended, still having the problem with the metadata but...
