### ISSUE TITLE
Break models into pieces / safetensors support / keep session state

### ISSUE THREAD

**Issue by Silver267** [oobabooga/text-generation-webui#13]
- [x] Implement a mechanic to sync conversation and panel state between all devices connected to the gradio link.

- [x] Add option (or another python file) to convert pytorch to safetensor (and make it not require that much ram...) - it loads faster, could load in-place when using disk cache (aka no need to extract model and add a bunch of writes to disk), and is safe from pickles. Convogpt is currently the only model using it.

- [x] Support resharding models into smaller pieces using ram/nvme offload.

**Comment by oobabooga** [comment]
Answering 3/5 of your suggestions below. Please make 1 issue per suggestion in the future, it is overwhelming to deal with long lists of vague suggestions.

>RLHF

Beyond the scope of this web ui, and also beyond the scope of everyone except openai (there isn't any open source model fine tuned with RLHF).

>convert-to-pytoch only supports loading entire model into gpu

I would like this too, but it is a limitation of the accelerate library.

>breaking a model into smaller pieces

What do you mean by that?

**Comment by Silver267** [comment]
Update: convert pytorch to safetensor is implemented [here](https://github.com/Silver267/pytorch-to-safetensor-converter)

**Comment by Silver267** [comment]
Since most features I originally requested was implemented / partially implemented to the best of ability, I think it's the right time to close this issue.
