### ISSUE TITLE
Gibberish output

### ISSUE THREAD

**Issue by ukrolelo** [oobabooga/text-generation-webui#1308]
### Describe the bug

Latest version of oobabooga

anon8231489123_vicuna-13b-GPTQ-4bit-128g
call python server.py --auto-devices --chat --wbits 4 --groupsize 128
INPUT: hello
OUTPUT: angularjsunit Gilliganism SpectrumptyaumontaneousIOSantonựufebudProgress Bundhmenync Mi
And then crash with inserted log

eachadea_ggml-vicuna-13b-1.1
is working fine but its only CPU from what i can see

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

call python server.py --auto-devices --chat --wbits 4 --groupsize 128

### Logs

```shell
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 2.00 GiB total capacity; 1.66 GiB already allocated; 0 bytes free; 1.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 92.81 seconds (0.23 tokens/s, 21 tokens, context 33, seed 1708064527)
```

### System Info

```shell
windows 11
2GB VRAM
32GB RAM
```

**Comment by Ph0rk0z** [comment]
Using act order + group size I bet.

**Comment by ukrolelo** [comment]
> Using act order + group size I bet.

call python server.py --auto-devices --chat --wbits 4 --groupsize 128 --pre_layer 7 --act-order

server.py: error: unrecognized arguments: --act-order

Did you ment i should not use the groupsize?

**Comment by jllllll** [comment]
@ukrolelo The Windows installer installs oobabooga's fork of GPTQ. If you want to upgrade to the latest, but are unable to compile kernels, you can install this precompiled wheel:
 ```
python -m pip install https://github.com/jllllll/GPTQ-for-LLaMa-Wheels/raw/main/610fdae6588c2b17bcf2726cacaaf795cd45077e/quant_cuda-0.0.0-cp310-cp310-win_amd64.whl --force-reinstall
```

**Comment by ukrolelo** [comment]
Thank you for suggestion.This after the step:
Starting the web UI...
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Loading anon8231489123_vicuna-13b-GPTQ-4bit-128g...
Found the following quantized model: models\anon8231489123_vicuna-13b-GPTQ-4bit-128g\vicuna-13b-4bit-128g.safetensors
Loading model ...
Press any key to continue . . .

and GUI:
Something went wrong
Connection errored out.

---
I have put your command to start-webui.bat and then removed i guess this is the only way as it is opening in virt.env

**Comment by ukrolelo** [comment]
@jllllll Installed through your repository, works okay :) and i changed GPU to 3060 12GB :X
Thank you
P.S. after some inputs in foreign language it starts to write gibberish, but its fine for now. Will wait for other updates :)
