### ISSUE TITLE
Add Support for MiniGPT-4

### ISSUE THREAD

**Issue by xNul** [oobabooga/text-generation-webui#1312]
**Description**

MiniGPT-4 adds the ability to use images with Vicuna-13b. Adding support would give multimodal capabilities similar to GPT-4 but for webui.

**Additional Context**

https://minigpt-4.github.io/
https://github.com/Vision-CAIR/MiniGPT-4

**Comment by Ph0rk0z** [comment]
I saw this in the morning too. It's pretty cool and I hope it works with any model, not just censored AALM vicuna.

**Comment by Wojtab** [comment]
Adding the support should be simple based on the new LLaVA extension (https://github.com/oobabooga/text-generation-webui/tree/main/extensions/llava), it's the same architecture, just with VIT+QFormer instead of CLIP, and slightly different way of embedding, but there are no super major differences

**Comment by oobabooga** [comment]
Support has been added here by @Wojtab 

https://github.com/oobabooga/text-generation-webui/pull/1741

Documentation with examples of commands: https://github.com/oobabooga/text-generation-webui/tree/main/extensions/multimodal
