### ISSUE TITLE
Not big fan of forced instruct mode.

### ISSUE THREAD

**Issue by Ph0rk0z** [oobabooga/text-generation-webui#1315]
### Describe the bug

I load llama and alpaca models in --chat but the settings yaml forces instruct mode. I then have issues in character history where my name becomes instruction and doesn't go away until I refresh the page.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load server.py --chat and then set up models from the interface.

### Screenshot

![instruct](https://user-images.githubusercontent.com/59298527/232520084-46ff2483-7c09-42c1-9d3a-c49afe6a6dbd.png)

### Logs

```shell
logs?
```

### System Info

```shell
you know
```

**Comment by oobabooga** [comment]
Instruct is only forced for alpaca, not llama. Alpaca doesn't work with characters

**Comment by Ph0rk0z** [comment]
Says who? And there is gpt-x-alpaca-13b-native-4bit-128g and now 30bit that works great with characters.. but it loads in instruct.

**Comment by iceandstorm** [comment]
@oobabooga  No, that is wrong. I really like alpaca gpt4-x-alpaca-13b-native4bit-128g with characters - it works very well. It also copes with custom instruct patterns and the complex-memory a lot better than other models I tried.

**Comment by iceandstorm** [comment]
> Says who? And there is gpt-x-alpaca-13b-native-4bit-128g and now 30bit that works great with characters.. but it loads in instruct.
> 
> here is a whole service using alpaca with characters: https://alpaca.point.space/

the 30b ? ... i did not hear that so far, where could i get it? :)

**Comment by oobabooga** [comment]
I have changed the character loader to select the default name when a new character is picked. This should solve the problem of your name persisting as `### Instruction:` or similar. https://github.com/oobabooga/text-generation-webui/commit/c544386824cf739759dabab31631a5f794c17234

For overriding the behavior of assigning instruct mode for instruct models, you can add this to `models/config-user.yaml`:

```yaml
.*$:
  mode: 'cai-chat'
  instruction_template: 'None'
```

**Comment by Ph0rk0z** [comment]
@iceandstorm  https://huggingface.co/MetaIX/GPT4-X-Alpaca-30B-Int4/tree/main

Thanks. I will incorporate that.
