### ISSUE TITLE
Multi-turn conversations: to clarify

### ISSUE THREAD

**Issue by alexl83** [oobabooga/text-generation-webui#1323]
Dear All, what's needed to achieve some level of multi-turn-conversation abilities in textgen?
E.g.
turn-1
PROMPT: please summarize this text: 'text'
OUTPUT: 'summarized text'
turn-2
PROMPT: now please take the text you summarized and trasnlate it to German
OUTPUT: Here's the text I summarized for you before, translated to German: 'summarized and translated text'

Is an available (or incoming) feature of text-generation-webui?
Does it depend on the LLM, must be provided by inference code, or other?

Thank you to anyone who might clarify this matter to me: I'm new to the technology and can't wrap my head around the topic.

A clear and concise description of what you want to be implemented.

**Additional Context**

If applicable, please provide any extra information, external links, or screenshots that could be useful.

**Comment by oobabooga** [comment]
That's what chat/instruct modes do
