### ISSUE TITLE
Update text-generation-webui wiki with correct example of loading a converted flexgen model.

### ISSUE THREAD

**Issue by GenTxt** [oobabooga/text-generation-webui#1325]
Ubuntu 22.04, python3.10, 2x 24gig RTX, both cuda and triton versions of webui

1) Conversion works 100% with local downloaded model:

   python convert-to-flexgen.py models/opt-1.3b

creates models/opt-1.3b-np

Errors occur when launching server.py with above flexgen model:

2) python server.py --model opt-1.3b  --flexgen

OSError: models/opt-1.3b is not a local folder and is not a valid model 
identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to 
this repo with `use_auth_token` or log in with `huggingface-cli login` and pass 
`use_auth_token=True`.

Makes sense because it's named 'opt-1.3b-np'

3) python server.py --model opt-1.3b-np  --flexgen

ValueError: Invalid model name: opt-1.3b-np (opt_config.py)

Mentioned here but not clear how to edit 'opt_config.py' to prevent downloading new opt models to cache and allowing access to local models as per example above.

https://github.com/oobabooga/text-generation-webui/issues/741

4) Without local model from step 1)

python server.py --model opt-1.3b  --flexgen

Downloads to huggingface cache, converts, and copies from cache and to 'models/opt-1.3b-np'

followed by the same error:

OSError: models/opt-1.3b is not a local folder and is not a valid model 
identifier listed on 'https://huggingface.co/models'

Required: Step-by-step edits required so that local flexgen models created with 'convert-to-flexgen.py' can be loaded 
by server.py as per any other working model.

Eventually want to attempt loading this: https://huggingface.co/Neko-Institute-of-Science/OPT-175B-NumPy
once multi-gpu is added to flexgen.

Thanks

**Comment by oobabooga** [comment]
Try renaming `facebook_opt-1.3b` to `opt-1.3b` at the beginning of the process, otherwise it won't work because flexgen has hardcoded names

**Comment by GenTxt** [comment]
Ahh, I see. Need to change 'config.json' in local model folder:

"_name_or_path": "facebook/opt-1.3b",

change to:

"_name_or_path": "opt-1.3b",

then run 'convert-to-flexgen.py'

converted -np model now loads from "models"

Worth adding a similar note to wiki

Thanks
