### ISSUE TITLE
Cannot run local. Getting error: "Warning: no GPU has been detected. Falling back to CPU mode."

### ISSUE THREAD

**Issue by ceria117** [oobabooga/text-generation-webui#133]
I have an RTX 2070, msinfo: (https://i.imgur.com/8qh4Xc7.png) My graphics drivers are up to date as of 2/08/2023
I installed using the 1 click method first. Install-nvidia, download-model, then start-webui.
I installed using 1 click again, but this time running in admin. (for some reason, it installed in system 32 folder, but I still got the exact same error)
finally, I installed manually using anaconda3 and got the same error.
https://i.imgur.com/HQcH9r1.png
https://i.imgur.com/ds6KOUG.png

**Comment by oobabooga** [comment]
See if this helps: https://github.com/oobabooga/text-generation-webui/issues/100

In particular, try opening a terminal and typing

```
pip uninstall torch
```

and then reinstalling.

**Comment by ceria117** [comment]
I was doing that as I was typing up this case. It looks like it worked. https://i.imgur.com/jt3nxOB.png
