### ISSUE TITLE
The MPS backend is supported on MacOS 12.3+.Current OS version can be queried using `sw_vers`

### ISSUE THREAD

**Issue by SimFG** [oobabooga/text-generation-webui#1337]
### Describe the bug

from the readme.md, i executed:

```
 git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui

conda create -n textgen python=3.10.9
conda activate textgen

pip install -r requirements.txt

python download-model.py facebook/opt-1.3b
python server.py
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

ditto

### Logs

```shell
text-generation-webui/venv/lib/python3.10/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "


Loading facebook_opt-1.3b...
Traceback (most recent call last):
  File "/Users/derek/xxx/text-generation-webui/server.py", line 905, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/Users/derek/xxx/text-generation-webui/modules/models.py", line 59, in load_model
    model = model.to(device)
  File "/Users/derek/xxx/text-generation-webui/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1896, in to
    return super().to(*args, **kwargs)
  File "/Users/derek/xxx/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/Users/derek/xxx/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/derek/xxx/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/derek/xxx/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/Users/derek/xxx/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/Users/derek/xxx/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: The MPS backend is supported on MacOS 12.3+.Current OS version can be queried using `sw_vers`
```

### System Info

```shell
mac x64

2.3 GHz Quad-Core Intel Core i7
Intel Iris Plus Graphics 1536 MB
32 GB 3733 MHz LPDDR4X
13.0.1 (22A400)
```

**Comment by silasdao** [comment]
Have the issue but with the 30b llama

**Comment by SimFG** [comment]
@silasdao you can try add `--cpu` param when starting the server

**Comment by FrankDMartinez** [comment]
> @silasdao you can try add `--cpu` param when starting the server

Any other suggestions? I am getting the same error even with the `--cpu` param.

**Comment by SimFG** [comment]
@FrankDMartinez you can try replace `mps` to `cpu`

**Comment by FrankDMartinez** [comment]
To make sure I am clear, here is what I tried:

- ./start_macos.sh --cpu
- ./start_macos.sh --mps
- ./start_macos.sh --cpu --mps
- ./start_macos.sh --mps --cpu

All of them give the same error.

Any additional ideas would be appreciated.

**Comment by SimFG** [comment]
change all, you can try it
![image](https://user-images.githubusercontent.com/21985684/235062826-bf1391d0-374a-44c1-a7e3-0e9236eb6ae4.png)
Replace all `torch.device('mps')` in the project.
torch.device('mps') -> torch.device('cpu')

**Comment by FrankDMartinez** [comment]
That worked, thanks! I have a new error but at least I got past that one. :-)

**Comment by moonskys** [comment]
@SimFG I also have this problem, may I ask which file should be replaced with the corresponding parameter?

**Comment by SimFG** [comment]
@moonskys all files. you need to search all files and replace.
torch.device('mps') -> torch.device('cpu')

**Comment by Manoz** [comment]
> @SimFG I also have this problem, may I ask which file should be replaced with the corresponding parameter? I can't find the modules/LoRa.py files.

Are you sure you're looking inside the `text-generation-webui` folder?
If you don't have `modules/LoRA.py` I guess there's something wrong. You might need to clone the repository again. If you know how to use `git` make sure you're on the `main` branch, that you have the latest changes and that nothing is missing.

Here's all files containing `torch.device('mps')` in my current folder.
<img width="334" alt="Screenshot 2023-05-06 at 23 00 09" src="https://user-images.githubusercontent.com/1554207/236646410-2db3bfe2-855d-45fd-9f48-4261dd69b249.png">

**Comment by appleguy** [comment]
Are there any plans to merge these changes so that macOS users can follow the instructions and get MPS working?

I've walked through those steps a few times myself, as some of this had been figured out on other threads, but it never got past the error shown here.

I haven't yet done the find-and-replace and will try that soon, but still wanted to ask if the base repository can be fixed.

**Comment by milezzz** [comment]
Just did a fresh git pull as well the 3 file edits above mps --> cpu. Exact same error on MacOS 13.3.1 on a MBP M1, 32GB.

```UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "```

Has a single person been able to get this running on M1 MacOS w/ GPU support?
