### ISSUE TITLE
SD_api_pictures: using the loaded model to translate the prompt in english.

### ISSUE THREAD

**Issue by cmhamiche** [oobabooga/text-generation-webui#1344]
Getting SD_api_pictures to do a translation from user's language to a prompt in english using the currently loaded model before the call to Stable Diffusion, so everything's running locally.

I'm using Open Assistant llama's model (oasst-llama13b-4bit-128g) and it's very capable at languages like french or german and pretty decent at translations.

I'd love to be able to use the Stable Diffusion API pictures for TextGen extension but unfortunately if I'm having a conversation in french it will send a prompt to Stable Diffusion... in french. Results are off to say the least.

An option for SD_api_pictures to translate the prompt in the background before calling Stable Diffusion would make everything simpler and would also make Stable Diffusion multilingual, sort of.

Here's an other extensions I'm aware of:

For Stable-Diffusion-webui:

Stable-Diffusion-Webui-Prompt-Translator: 
It's either using an online service (or an AI translation engine that wou'd have to setup called MarianM which apparently isn't that good anyway). Clicking the "Translate" button in stable diffusion's interface is required, not ideal.
https://github.com/butaixianran/Stable-Diffusion-Webui-Prompt-Translator

For text-generation-webui:
google_translate extension: It's also using an online service.
https://github.com/oobabooga/text-generation-webui/blob/main/extensions/google_translate/script.py

**Comment by janvarev** [comment]
I'm waiting for my PR to be merged: https://github.com/oobabooga/text-generation-webui/pull/1321
PR allow to use in google_translate extension offline server LibreTranslate, so it'll be easier to integrate it with sd_api_extension.

**Comment by cmhamiche** [comment]
Thank you, I'd probably use it if there's no alternatives but I'd really appreciate a simple offline solution like using the model if it is good enough for translation. I think that even llama 7B 4bit would give devent results at it.

**Comment by janvarev** [comment]
> Edit: I didn't realize that it could be used offline, I'll give it a try.

Also, it significantly faster than GPT model, and can be succesfully run on CPU. In my installation it requires near 0.5-1 seconds to translate.

**Comment by cmhamiche** [comment]
I did some comparisons. I've tried it locally and while LibreTranslate is extremely fast at translating, there's a lot of context lost in translation when it's not completely wrong and the responses are slower on my system than just conversing in french.

There's also an issue where the pic comes back with a very verbose prompt that has not been translated at all. I'll try to get the details of that issue tomorrow.

Still, that extension is a great addition for people who can't get finetuned models for their languages and it's really trivial to set up.

**Comment by janvarev** [comment]
Thanks for reply!
As I understand, you make some requests to  llama 7B 4bit to make translation of text. Could you provide some good examples of them? I wanna try such a way too.

**Comment by janvarev** [comment]
@cmhamiche Please, try my updated google_translation ext. I've added option to translate using local already loaded Alpaca model - as you say, it works better in some cases.
https://github.com/oobabooga/text-generation-webui/pull/1321#issuecomment-1513829366

**Comment by cmhamiche** [comment]
Man, that is incredible. 

I'm currently using oasst-llama13b-4bit-128g which is pretty good at translating but requires 10 gb ram if I remember correctly.
There's some language stats here, it is multilingual. https://open-assistant.io/fr/stats
But I used to struggle with alpaca 7B 4bits just a few days ago on a 1060 6gb and it was doing translation fine in french, so I'll also test that. Thank you.

Let me switch back to ubuntu, I'll try real quick and report back.

**Comment by cmhamiche** [comment]
Thanks for the hints.

**Comment by Brawlence** [comment]
@cmhamiche 
IMO this shouldn't be a part of SD_api_pictures logic itself. But I can always make the prompts for generation which go into the model be customizable; then one could provide it with custom request phrase (like for example "describe 'the thing' it but in English")

**Comment by cmhamiche** [comment]
Yeah, I glanced at the script real quick, what I want is fairly trivial so it's up to you. 
It could be a temporary fork in the meantime also.

If implementing the changes you suggested for non english and multilingual models can wait I'm fine with it, it will probably be confusing for newcomers. It will happen when everything gets localized eventually.

I've never coded but I'll definitely be able to edit the script to my liking, thanks to the comments. Thanks guys.
