### ISSUE TITLE
Feature request: Increase max_new_tokens (because many models can produce many more than 2000)

### ISSUE THREAD

**Issue by dogjamboree** [oobabooga/text-generation-webui#1350]
Please increase the slider value for max_new_tokens above 2000. In llama.cpp I set it to -1 and it sometimes generates literally pages of text, which is great for stories, etc. 

I personally find 2000 limiting.

**Comment by bloodsign** [comment]
would love to see this. Can fit in more context into conversations. Definitely gonna help have bots to have more character.

**Comment by alexl83** [comment]
> 

You can increase the slider value direcly in settings-template.json

**Comment by dogjamboree** [comment]
THanks -- I'll give it a shot!

**Comment by Ph0rk0z** [comment]
Does it generate pages in 1 go or does it keep hitting continue in llama cpp..  iirc the model has a max 2048 of context and output all together.

**Comment by oobabooga** [comment]
Nonsense issue

**Comment by Jackaroo1432** [comment]
Considering 8k context length possible now, increasing this as the OP suggested would make sense and be be beneficial. 

I have tried changing the limit in the preset AND in the console, it still will not produce longer than 2000 tks

**Comment by Ph0rk0z** [comment]
Yea we have NTK for tokens the model can see.. but I'm not sure that applies to output tokens. The MPT-7b supposedly has actual higher token limit.

**Comment by dogjamboree** [comment]
After this issue was closed I left oobabooga and now use llama.cpp exclusively. A normal session for me in llama.cpp consists of generating anywhere between 5-10k tokens per response before I intervene. As a creative writer 2k tokens is nothing and this limitation render the app completely useless for my purposes (and many others doing verbose storywriting).

I have a mac with 128gb unified memory so generating that many tokens, along with 16k context, is completely doable with headroom leftover on my system.

**Comment by Ph0rk0z** [comment]
The limit has been bumped in any case. I'm happy it does work to generate more. It was always a simple setting in one file. I don't usually get such long responses for chat even if I raise it. The model moves to start talking for me.
