### ISSUE TITLE
[Error] Flexgen Invalid model name

### ISSUE THREAD

**Issue by Jerryhuh** [oobabooga/text-generation-webui#137]
Saw that you updated models.py so tried to run Flexgen today. 

Converted OPT-13B-Erebus using "python convert-to-flexgen.py models/OPT-13B-Erebus/".  Ran with "python server.py --model OPT-13B-Erebus --flexgen" and received this error.  Tried also with "python server.py --model OPT-13B-Erebus-np--flexgen"  for added measure.  Doesn't work.

![image](https://user-images.githubusercontent.com/126207474/221438418-e5463bcd-1b07-4f6c-b17b-8a319ff1afe8.png)

**Comment by oobabooga** [comment]
OPT-erebus and is not supported by FlexGen yet, just the default OPT models.

**Comment by Jerryhuh** [comment]
> OPT-erebus and is not supported by FlexGen yet, just the default OPT models.

Oh ok understood,  Thank you!
