### ISSUE TITLE
Bad results generated from llama-65b-4bit-128g model

### ISSUE THREAD

**Issue by Yiximail** [oobabooga/text-generation-webui#1378]
### Describe the bug

I encountered an issue when attempting to use the `llama-65b-4bit-128g` model. The output results I generated were mostly composed of empty spaces or symbols.
![20230419194828](https://user-images.githubusercontent.com/15323975/233085920-69dcaeea-c3db-4a44-9cce-6d7281f7c7c8.png)
I am running on Runpod and have tried using 2x RTX3090 as well as 1x A6000, but have got the same results.
And I have limited the max_length to 200. Each generation only stops when it reaches 199.

I have tried these two models:
[Neko-Institute-of-Science/LLaMA-65B-4bit-128g](https://huggingface.co/Neko-Institute-of-Science/LLaMA-65B-4bit-128g)
[catid/llama-65b-4bit](https://huggingface.co/catid/llama-65b-4bit)

By the way, I was able to successfully run and output normal results based on the code provided by catid.
```bash
# Install git-lfs
sudo apt install git git-lfs

# Clone the code
git clone https://github.com/catid/GPTQ-for-LLaMa-65B-2GPU
cd GPTQ-for-LLaMa-65B-2GPU

# Clone the model weights
git lfs install
git clone https://huggingface.co/catid/llama-65b-4bit

# Set up conda environment
conda create -n gptq python=3.10
conda activate gptq

# Install script dependencies
pip install -r requirements.txt

# Work around protobuf error
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

# Run a test
python llama_inference.py llama-65b-4bit --load llama-65b-4bit/llama65b-4bit-128g.safetensors --groupsize 128 --wbits 4 --text "I woke up with a dent in my forehead.  " --max_length 128 --min_length 32
```
![Q$_UA{MS{D172) GQ24{T6W](https://user-images.githubusercontent.com/15323975/233087172-c5d1e54f-a62d-497c-812a-81bdf3ea0184.png)

Before I tried the 65B model. I tired alpaca-30b-4bit, it works perfectly fine with one 3090.
I have tried running 2x RTX3090 for 30B, although only gpu1 loaded the entire model, the output was still normal.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```bash
cd /workspace
# clone text-generation-webui
git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui

# I used venv to save my enviroment
python -m venv .venv
source .venv/bin/activate

# install requirements for text-generation-webui
pip install -r requirements.txt --upgrade


# clone GPTQ-for-LLaMa
mkdir -p /workspace/text-generation-webui/repositories
cd /workspace/text-generation-webui/repositories
git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
cd GPTQ-for-LLaMa

# install requirements for GPTQ-for-LLaMa and install
pip install -r requirements.txt --upgrade
python setup_cuda.py install

# install xformers and deepspeed
pip install xformers deepspeed --upgrade
```
I am using the following code to run with 2x RTX3090:
```bash
python server.py --auto-devices --gpu-memory 20 20 --xformers --listen \
   --wbits 4 --groupsize 128 --model_type LLaMA --model llama-65b-4bit-128g
```
I am using the following code to run with 1x A6000:
```bash
python server.py --auto-devices --gpu-memory 48 --xformers --listen \
   --wbits 4 --groupsize 128 --model_type LLaMA --model llama-65b-4bit-128g
# and tried in deepspeed
deepspeed --num_gpus=1 server.py --auto-devices --gpu-memory 48 --xformers --listen \
   --wbits 4 --groupsize 128 --model_type LLaMA --model llama-65b-4bit-128g
```
They all encountered the issue mentioned above.

I am using the following code to run with 1x RTX3090:
```bash
deepspeed --num_gpus=1 server.py --auto-devices --gpu-memory 24 --xformers --listen \
   --wbits 4 --groupsize 128 --model_type LLaMA --model alpaca-30b-4bit
```
It is Okay.

### Logs

```shell
That's all I said above.
```

### System Info

```shell
Linux version 5.4.0-137-generic (buildd@lcy02-amd64-009) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023

2x RTX 3090
1x A6000
```

**Comment by mcmonkey4eva** [comment]
Related to: https://github.com/oobabooga/text-generation-webui/issues/931

One of those files was converted with act-order, the other with a custom GPTQ fork.

You'll have to use a GPTQ branch/fork that matches your model.

(In both cases I think _triton_ is required and cuda won't work)

(Or get the original 65B files and quantize them on cuda yourself, or find a cuda-quantized 65B)

**Comment by Yiximail** [comment]
> Related to: #931
> 
> One of those files was converted with act-order, the other with a custom GPTQ fork.
> 
> You'll have to use a GPTQ branch/fork that matches your model.
> 
> (In both cases I think _triton_ is required and cuda won't work)
> 
> (Or get the original 65B files and quantize them on cuda yourself, or find a cuda-quantized 65B)

Thank you for your reply. The model owner did provide the Triton branch, which I overlooked.
