### ISSUE TITLE
「Issue] Google Translate Extension not working in DeepSpeed

### ISSUE THREAD

**Issue by Jerryhuh** [oobabooga/text-generation-webui#138]
I believe the same issue is without DeepSpeed．Extensions work as I have tried it with character＿bias.　It's just not working with google_translate.

![image](https://user-images.githubusercontent.com/126207474/221440962-b396b1cb-0e23-4e50-861e-60c76f2a6cb4.png)

**Comment by oobabooga** [comment]
Try

```
pip install -r extensions/google_translate/requirements.txt
```

**Comment by Jerryhuh** [comment]
Thank you that did it.
