### ISSUE TITLE
Support models larger than RAM / VRAM

### ISSUE THREAD

**Issue by Rudd-O** [oobabooga/text-generation-webui#1380]
**Description**

[A clear and concise description of what you want to be implemented.](https://huggingface.co/blog/accelerate-large-models) indicates it should be possible to execute models larger than the RAM available on the GPU.

Can oobabooga implement this or an analogue of this?

Thanks in advance!  Your project is extremely cool.  I hope to continue pushing new PRs as I continue to discover more and more about this project.

EDIT: this ticket is more or less about either documenting this facility in a prominent place, or making one of these modes the default and document how to disable or change mode.

**Comment by Ph0rk0z** [comment]
Offloading already works in this repo. With deepspeed, flexgen, and accelerate.

**Comment by Ph0rk0z** [comment]
It probably depends on how you sharded the model too. If it's in 3 chunks yea.. might be a problem.

**Comment by Ph0rk0z** [comment]
If even the quantized model is > than your ram you will have to make a big swap file and load it that way. You can also use pre-layer for llama.

**Comment by Rudd-O** [comment]
Note: at least on my machine, DeepSpeed is no faster than `--auto-devices` with or without `--8bits`.

**Comment by HWiese1980** [comment]
I'm seeing the same behavior. Big safetensor file (MetalX/GPT4-X-Alpaca-30B-4bit), relevant settings like @mrdc's previous comment, crash with no error message in `model.load_state_dict`. I have 32GB of CPU RAM, 24GB of VRAM, and a big swap file of 128GB. It *should* work, not sure why it isn't...

**Comment by askmyteapot** [comment]
Weirdly, If using 0cc4m's KoboldAI latestgptq branch (https://github.com/0cc4m/KoboldAI) i can load a model without going out of RAM or paging massive amounts to swap. But, if i try to load the same file in Ooba, it errors out after paging out 140GB of Swap. 

This is using the same conda environment and manually running either. 

Model i'm trying to load is a Safetensor. Doesnt matter if its the 30B GPT4-X or the newest openassist 30B. 

Oh, and using 0cc4m's GPTQ branch in both. (and i have tested with Ooba's GPTQ branch and it doesnt make a difference)

Weirdly, there is a spike of SWAP usage before line  47: model = model.eval() in GPTQ_Loader.py, however nothing appears to be written to SWAP, as my SSD doesnt start to write until the model starts the following loading model... step. 

I'm not good enough to figure out what the difference is. But there is proof that large models can be loaded without blowing out swap.

**Comment by Ph0rk0z** [comment]
kobold uses lazyload.

**Comment by alkeryn** [comment]
could we have a mmap option ?
on my laptop there is a 13B model that llamma.cpp can run, but ooba cannot because i run out of ram (not vram) and get oom'd.

**Comment by Ph0rk0z** [comment]
I thought that is a function of the CPP python module.

**Comment by alkeryn** [comment]
@Ph0rk0z yes it is, but it would be nice to be able to use it on the non cpp version as well.
it should be possible to copy the model directly to vram without first having to load it fully in ram.
it kinda sucks for low ram high vram systems.

**Comment by Ph0rk0z** [comment]
I assume the person who wrote the wrapper has to update it. I actually want to turn mmap off and see if I get faster speeds loading the whole thing in ram.

**Comment by alkeryn** [comment]
@Ph0rk0z in my experience mmap is faster to load, especialy if you kill llama and start it again as it'll still be cached in ram.
disabling it guarantees you are not offloading it though.
if it ram + vram i don't think it change anything in terms of speed.
