### ISSUE TITLE
Gradio some error

### ISSUE THREAD

**Issue by IdkMaybeGamer** [oobabooga/text-generation-webui#1385]
### Describe the bug

So i cant figure out how to fix this mostly solutions i saw didnt work for me

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Idk

### Logs

```shell
File "C:\Users\pavli\OneDrive\Plocha\oobabooga_windows\text-generation-webui\server.py", line 17, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
```

### System Info

```shell
Microsoft Windows 10 Home
Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz, 2496 Mhz
```

**Comment by oobabooga** [comment]
Your installation probably didn't finish. Try doing it outside a OneDrive disk
