### ISSUE TITLE
Add support for longer context size

### ISSUE THREAD

**Issue by Silver267** [oobabooga/text-generation-webui#1389]
**Description**

With the release of StableLM and rwkv with 8192 context size, it's necessary to enable the user to set a context size above 2048.

**Comment by oobabooga** [comment]
I have been preparing for this moment

![prepared](https://user-images.githubusercontent.com/112222186/233193562-fddfeff0-ae8b-4997-b91a-d3858b574f17.png)

Also increased the upper bound to 8192 (from 4096) https://github.com/oobabooga/text-generation-webui/commit/702fe92d42eaff7536b439d2b2c40e70b8caf02d
