### ISSUE TITLE
4 bit models don't work for One-click installers

### ISSUE THREAD

**Issue by rengecky** [oobabooga/text-generation-webui#1398]
### Describe the bug

New One-click installers after installing and downloading a 4 bit model and running with --wbits 4 --groupsize 128 don't work. On the old version that I downloaded 3 weeks ago, everything works.

EDIT:
The problem is that some of the 4-bit models are not loaded. I have now checked on all that I have and made a list:
Work fine:
vicuna-13b-GPTQ-4bit-128g
mayaeary/pygmalion-6b-4bit-128g
llama-13b-4bit-128g
Don't work:
koala-13B-GPTQ-4bit-128g
instruct-13b-4bit-128g
alpaca-13b-lora-int4
ShreyasBrill/Vicuna-13B
Solutions: 
I should have loaded pytorch_model.bin.index.json. Now without this file, the model doesn't work.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Launched One-click installers. Downloaded the model, added --wbits 4 --groupsize 128. Started the server. Tried to switch to Example and got an error.

### Logs

```shell
Gradio HTTP request redirected to localhost :)
bin S:\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Loading alpaca-13b-lora-int4...
Found the following quantized model: models\alpaca-13b-lora-int4\alpaca-13b-4bit-128g.safetensors
Loading model ...
Done.
Loaded the model in 4.49 seconds.
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "S:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "S:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "S:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "S:\oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "S:\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "S:\oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "S:\oobabooga-windows\text-generation-webui\modules\chat.py", line 436, in load_character
    file_contents = open(filepath, 'r', encoding='utf-8').read()
FileNotFoundError: [Errno 2] No such file or directory: 'characters\\instruction-following\\Example.json'
```
Error in the model tab:
```shell
Traceback (most recent call last):
File “S:\oobabooga-windows\text-generation-webui\[server.py](http://server.py/)”, line 100, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name)
File “S:\oobabooga-windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 56, in load_model
model = LoaderClass.from_pretrained(Path(f"{shared.args.model_dir}/{shared.model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.bfloat16 if shared.args.bf16 else torch.float16, trust_remote_code=trust_remote_code)
File “S:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py”, line 471, in from_pretrained
return model_class.from_pretrained(
File “S:\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py”, line 2405, in from_pretrained
raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models\alpaca-13b-lora-int4.
```

### System Info

```shell
3060 12 gigabytes. 32 gigabytes of RAM. AMD Ryzen 5 3600 6-Core Processor 3.59 GHz, Windows 10 Pro
```

**Comment by helix4u** [comment]
so.... switch to cai-chat after relaunching and then open the galllery and select example... I think it may get around it... i can at least sometimes load a character now lol

**Comment by helix4u** [comment]
from the chat and instruct and others,  yeah it seems broken for me too

**Comment by jllllll** [comment]
Why are you trying to select the example character in the first place? Alpaca is an instruct model, which the example character is not made for. Either way, this is not an issue with the installers or 4-bit models. The webui is currently looking for instruct characters when using an instruct model and incorrectly displays the example character as a selectable option.

I don't see how this amounts to "4 bit models don't work for One-click installers".

**Comment by helix4u** [comment]
Thats right. it's not a 4 bit problem imho, its a UI/UX problem.

**Comment by helix4u** [comment]
We're all saying the same things.... sigh.

**Comment by rengecky** [comment]
> Bug as I see it: UI exposes features on pages that break functionality related to character creation. Examples should be added or the UI elements shown only in the correct locations where they can be used without error.

No. The problem is that some of the 4-bit models are not loaded. I have now checked on all that I have and made a list:
Work fine:
vicuna-13b-GPTQ-4bit-128g
mayaeary/pygmalion-6b-4bit-128g
llama-13b-4bit-128g
Don't work:
koala-13B-GPTQ-4bit-128g
instruct-13b-4bit-128g
alpaca-13b-lora-int4
ShreyasBrill/Vicuna-13B

I'm sorry I didn't check earlier. A week ago, 4 bit models didn't work at all, although everything works well on the old ui that is 3 weeks old.
