### ISSUE TITLE
Chat format for RWKV "Raven" Models

### ISSUE THREAD

**Issue by BlinkDL** [oobabooga/text-generation-webui#1401]
Please take a look @oobabooga :)

When you build a RWKV chatbot, please always check the text corresponding to the state, in order to prevent bugs.

1. Never call raw forward() directly. Instead, put it in a function that will record the text corresponding to the state.

2. The best chat format (check whether your text is of this format):
```Bob: xxxxxxxxxxxxxxxxxx\n\nAlice: xxxxxxxxxxxxx\n\nBob: xxxxxxxxxxxxxxxx\n\nAlice:```

* There should not be any space after the final "Alice:". The generation result will have a space in the beginning, and you can simply strip it.
* You can use \n in xxxxx, but avoid \n\n. So simply do ```xxxxx = xxxxx.strip().replace('\r\n','\n').replace('\n\n','\n')```

**Comment by oobabooga** [comment]
Thanks @BlinkDL, I'll make a template for the RWKV chatbot.

**Comment by Sdssourcing** [comment]
#

**Comment by oobabooga** [comment]
A special prompt template has been added for RWKV Raven in https://github.com/oobabooga/text-generation-webui/commit/a777c058aff905e142700b912cd8e3ddbd3fe8e1. It is automatically set whenever a model with 'raven' in its lower case name is loaded in chat mode.
