### ISSUE TITLE
Error while creating share link for public URL

### ISSUE THREAD

**Issue by ostix360** [oobabooga/text-generation-webui#1417]
### Describe the bug

When I start the web ui with `python server.py --auto-devices --chat --model-menu --listen --listen-port 31409 --share --auto-launch`
There is this error 

```
Closing server running on port: 31409
Loading the extension "gallery"... Ok.
Running on local URL:  http://0.0.0.0:31409

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app
```

And of course I check my internet connection and the gradio server's statue
I'm on a window machine 
Thanks for your help

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Launch the file server.py with `python server.py --auto-devices --chat --model-menu --listen --listen-port 31409 --share --auto-launch`
In my case the command is inside the webui.py file line 146 in the run_model function

### Logs

```shell
Closing server running on port: 31409
Loading the extension "gallery"... Ok.
Running on local URL:  http://0.0.0.0:31409

Could not create share link. Please check your internet connection or our status page: https://status.gradio.app

Idk where is the log file
So this is the log in the cmd
```

### System Info

```shell
I'm on a window machine with 16Go RAM, AMD Ryzen 5 3600, Nvidia 1660 super (6Go RAM)
```

**Comment by ostix360** [comment]
For those who have this problem it's just window defender that block a file and you need to allow this file to exist otherwise the link creation failed

**Comment by ItzSwapnil** [comment]
i am having this error as well but i am using ubuntu
