### ISSUE TITLE
Bark - Free amazing TTS extension

### ISSUE THREAD

**Issue by GiusTex** [oobabooga/text-generation-webui#1423]
**Description**
We need a TTS extension for [Bark](https://github.com/suno-ai/bark) from suno-ai.
I haven't still tried it locally, but it says "On modern GPUs and PyTorch nightly, Bark can generate audio in roughly realtime"; on default colab, as said in the comments of the video down there, the intro audio took 4 mins though.
It supports 16 languages and can also sing!
It looks also quite easy to install, I think.

**Additional Context**
Example [video](https://youtu.be/84LzaXAo6vE) and [colab](https://colab.research.google.com/drive/1eJfA2XUa-mXwdMy7DoYKVYHI1iTd9Vkt?usp=sharing).

**Comment by wsippel** [comment]
I'm working on it. Just got it to to speak its first reply by modifying the Silero extension a few minutes ago. It's very impressive! It's insanely easy to use, and the way it changes cadence and inflection based on context is insane. I have some weird clipping issues and artefacts I'd like to iron out, though. And the hardware requirements are steep. Running Vicuna 13b and Bark at the same time pushes my VRAM load well beyond 16GB, so this is probably only usable for people with at least 20GB VRAM or lots of RAM and patience.

**Comment by wsippel** [comment]
Here's what I quickly hacked together: https://github.com/wsippel/bark-tts

It's 4am for me, so I really need to go to bed, but I'll continue working on it once I had some sleep.

**Comment by bmoconno** [comment]
I also tried to get this running locally last night and got a lot of artifacts in the audio, like sometimes weird sirens, sometimes the voices were unbearably high-pitched, and sometimes it sounded like it was trying to put music in the background even though I didn't use any of the decorators to add music or anything.

Hopefully it gets sorted out soon, because I do like the quality and the ability to use decorators like `...` and `[laughs]`

It does use a hefty amount of VRAM though and isn't as fast as Silero

**Comment by wsippel** [comment]
OK, my extension is somewhat usable now. I added speaker selection (only the ten provided english voices for now) so it's more consistent between generations now, and I exposed the temperature settings in the UI. Works as you'd expect, higher temperature leads to more randomness. Be aware that Bark can totally go off the rails, and there seems to be a 40 token generation limit for some reason, which translates to around 15 seconds. There's no documentation yet, so I'm not sure how or even if that can be changed. A quick glance at the source code didn't help either, but I might have missed it...

**Comment by Ph0rk0z** [comment]
Someone will have to reverse engineer the voice cloning. Sounds like they want to "mitigate risk" by hosting their own service and charging money for it.

**Comment by wsippel** [comment]
It is (pretty much) done:
https://github.com/wsippel/bark_tts

Renamed the repository to fit conventions, sorry for the confusion. Silero specific code has been removed, and I reduced generation temperature a bit. I think stricter settings work better for an assistant, but feel free to crank it if you want

There's not really much I can do about the token limit, though. The Suno devs consider implementing a way to split generation into sensible chunks under the hood if the text input gets too long, but until that's implemented, you might have to dial down your generation limit. Be aware that 40 audio tokens are not the same thing as 40 text tokens, and there are many factors that influence how many audio tokens a text of any given length will require.

**Comment by wsippel** [comment]
If you don't mind getting your hands dirty, compile bark manually from this PR: https://github.com/suno-ai/bark/pull/27 and grab the extension from this branch: https://github.com/wsippel/bark_tts/tree/k/v - for me, it's four to five times faster with those changes and, dare I say, almost actually useful.

**Comment by 3dluvr** [comment]
Take a look at this repo: https://github.com/JonathanFly/bark instead of the suno-ai, as more work was done to it.

**Comment by wsippel** [comment]
Most of the new features in [JonathanFly/bark](https://github.com/JonathanFly/bark) are not very useful for my extension, and upstream got a few optimisations that make it a lot faster that are not in the fork yet. And I've since implemented my own solution to handle generation of arbitrary length. While JonathanFly's approach splits the input by either word or lines, I use NLTK to split by sentence. 

I also just added support for custom voices generated using either [JonathanFly/bark](https://github.com/JonathanFly/bark) or [serp-ai/bark-with-voice-clone](https://github.com/serp-ai/bark-with-voice-clone). Just throw the .npz files in the new `voices` folder. I think they should be prefixed with a language code if they don't have one, so if you have an English custom voice, make sure it's named `en_myspeaker.npz`.

**Comment by Ph0rk0z** [comment]
They aready fixed the cloning.. this will be very good then. TTS with expression and the character's voice is literally gold.

**Comment by 3dluvr** [comment]
By default it's storing the models in ~/.cache folder, which to me is unacceptable when running in VENV.

I did submit an issue about it and they came back pretty fast with an updated README. Now you can use XDG_CACHE_HOME env variable to specify an alternative path for models.

**Comment by Ph0rk0z** [comment]
Yea.. I don't want to d\l these models twice, one for the cloning fork and one for the reggo. I made the notebook into a script because I'm not running on any other people's servers.

[clone-voice.py.txt](https://github.com/oobabooga/text-generation-webui/files/11303966/clone-voice.py.txt)

**Comment by TrainzLuvr** [comment]
Yeah, I don't like running anything in the "cloud", so everything is local as much as possible.

**Comment by 3dluvr** [comment]
Yeah, I don't like running anything in the "cloud", so everything is local as much as possible.

**Comment by GiusTex** [comment]
I noticed that in the extensions page there is bark_tts by [minemo](https://github.com/minemo/text-generation-webui-barktts) and no reference to the alternative by [wsippel](https://github.com/wsippel/bark_tts), which for me has more options and seems fancier, also if I'm still downloading the wsippel dependencies (the models) to try his exten., so I don't know how is the minemo one.
Should we point out that exists also the wsippel exten.? Maybe minemo can do a merge or something

**Comment by gitmylo** [comment]
> Yea.. I don't want to d\l these models twice, one for the cloning fork and one for the reggo. I made the notebook into a script because I'm not running on any other people's servers.
> 
> [clone-voice.py.txt](https://github.com/oobabooga/text-generation-webui/files/11303966/clone-voice.py.txt)
> 
> they are going to: .cache/suno/bark_v0

I improved voice cloning by training a model to create actual semantics, It's better, more consistent and does not require a transcript. https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer

This could help if your cloned voices aren't sounding enough like the voice you're trying to clone.
