### ISSUE TITLE
Argument in Text ++ is different.

### ISSUE THREAD

**Issue by AyannoMoon** [oobabooga/text-generation-webui#1429]
### Describe the bug

I have been trying to follow the tutorial and good to troubleshoot, but i'm not sure exactly what to do.

![image_2023-04-20_195025808](https://user-images.githubusercontent.com/131413315/233509606-8ed31e4f-baca-4c2b-bb16-10a79381f18d.png)

This is how mine looks. I have checked the elements and made sure that miniconda AND anaconda are downloaded to the correct places.

![image](https://user-images.githubusercontent.com/131413315/233509662-7d1557fe-b9b7-41c0-86c0-35547bbdb334.png)

This is how it looks in the video. I am using the start_windows.bat

...any ideas? thanks :)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I did it exactly how was shown in the video except my ooba folder is extracted in users (so is anaconda3). without that I would keep getting an invalid archive error. 

### Logs

```shell
Included in images above.
```

### System Info

```shell
Windows 11 Home 64-Bit (10.0, Build 22621)

GPU: NVIDIA GeForce RTX 3050
```

**Comment by altoiddealer** [comment]
I'm having the same issue I think?

from INSTRUCTIONS.TXT 
>Adding flags like --chat, --notebook, etc
Edit the "start" script using a text editor and add the desired flags
to the line that says
run_cmd("python server.py --auto-devices --chat --model-menu")
For instance, to add the --notebook flag, change it to
run_cmd("python server.py --auto-devices --notebook --model-menu")

And then, none of the .bat files contain "run".

And so I just assume its supposed to be the same as it was in prior versions (add the args after "call python webui.py ")

...but then when I run the webui

<img width="777" alt="Screenshot 2023-04-21 100623" src="https://user-images.githubusercontent.com/1613484/233656837-b5eae38d-9bf6-47b9-ac5c-2e9d2a27609d.png">

**Comment by AyannoMoon** [comment]
> Quick update... I was only able to get cmd args to work if I edited webui.py directly.
> 
> This is pretty lame, though, because webui.py isn't going to update if there are updates available.
> 
> <img alt="Screenshot 2023-04-21 103350" width="1010" src="https://user-images.githubusercontent.com/1613484/233663011-a2b44edf-1e14-4e77-a702-1a3fd88fe2d2.png">

Thank you! That helped :)
