### ISSUE TITLE
API returns only none, none 

### ISSUE THREAD

**Issue by CyberTimon** [oobabooga/text-generation-webui#1445]
### Describe the bug

When using the api-example-stream.py I only get "None None" in the output. When I remove to get only the data of the request I get this: 
`{'msg': 'process_completed', 'output': {'data': [None], 'is_generating': False, 'duration': 0.0002684593200683594, 'average_duration': 0.00038123130798339844}, 'success': True}
{'msg': 'process_completed', 'output': {'data': [None], 'is_generating': False, 'duration': 0.0002684593200683594, 'average_duration': 0.00038123130798339844}, 'success': True}`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use api-example-stream.py and you will get this

### Logs

```shell
(base) cybertimon@server:~/Repositorys/CT AI Vicuna$ python3 api-example-stream.py
None
None
(base) cybertimon@server:~/Repositorys/CT AI Vicuna$ python3 api-example-stream.py
{'msg': 'process_completed', 'output': {'data': [None], 'is_generating': False, 'duration': 0.0002684593200683594, 'average_duration': 0.00038123130798339844}, 'success': True}
{'msg': 'process_completed', 'output': {'data': [None], 'is_generating': False, 'duration': 0.0002684593200683594, 'average_duration': 0.00038123130798339844}, 'success': True}
(base) cybertimon@server:~/Repositorys/CT AI Vicuna$
```

### System Info

```shell
2x3060 12gb
i5 13600kf
64gb
```

**Comment by mashdragon** [comment]
I am also getting this error. It makes using the webui very frustrating. Sometimes it works after I restart the UI and refresh the page, but it is inconsistent. When I finally get it working, it might fail on the next prompt or the one after, too. I am using the cpu only.

**Comment by CyberTimon** [comment]
Closing this as it is fixed with the new api
