### ISSUE TITLE
Add --pin-weight to FlexGen

### ISSUE THREAD

**Issue by minipasila** [oobabooga/text-generation-webui#145]
It's another way to reduce memory usage by up to 20% according to FlexGen's [readme](https://github.com/FMInference/FlexGen#handle-out-of-memory). I'm unable to use it with the current version of this UI.

**Comment by oobabooga** [comment]
https://github.com/oobabooga/text-generation-webui/commit/ed8b35efd2c6304d9debf84c494ba69139c2f20e
