### ISSUE TITLE
Instruct mode is the forced Default (Settings.json / --chat both ignored)

### ISSUE THREAD

**Issue by altoiddealer** [oobabooga/text-generation-webui#1450]
### Describe the bug

Hello, after updating about a week ago **_the WebUI will always launch into Instruct mode._**

I just did a fresh Windows install hoping that perhaps it was resolved, but that's not the case.

Note that I have tried every combination of "cai-chat" and "chat", omitting one or the other from one file and the other... **there is no combination that will stop it from defaulting to Instruct mode.**

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use text-generation-webui

### Screenshot

<img width="1418" alt="Screenshot 2023-04-21 104907" src="https://user-images.githubusercontent.com/1613484/233666605-d13e3c4b-05b6-4e37-832a-0e98bc6f86d1.png">

### Logs

```shell
N/A
```

### System Info

```shell
Windows 11, Nvidia Gigabyte RTX 4070ti
```

**Comment by Ph0rk0z** [comment]
https://github.com/oobabooga/text-generation-webui/issues/1315

**Comment by altoiddealer** [comment]
Woops, I didn't see that because I searched only for Open issues

**Comment by Ph0rk0z** [comment]
Mainly, it has the fix in it.

**Comment by altoiddealer** [comment]
It's unfortunate that there isn't a cmd arg to just override this behavior, like one may override many of the other default behaviors.

Thank you, I followed that advice and got it working.

The only setback is that, if I do add a "config-user.yaml" and customize it - it will work, but it seems like oobabooga still analyzes the default "config.yaml" and throws up errors in the cmd window.

Currently, I renamed the default "config.yaml".

Just one more thing to remember I had to change when it comes to fetching future updates

**Comment by Ph0rk0z** [comment]
I edited my config.yaml, I don't really want instruct mode by name for any model.

**Comment by oobabooga** [comment]
I won't change it because my tests clearly show that instruct modes have higher perplexity for general text generation tasks like chat. They are meant to be used with their corresponding templates. But you can override the default behavior as @Ph0rk0z pointed out.

**Comment by Interpause** [comment]
The Instruct form is awkward for character roleplay, making it hard to use Instruct-based models, which perform better, for roleplay. I think it might make sense to allow using chat mode for instruct given some system to make the character prompts instruct-compliant. So far, I have manually done that for my own character profile I wish to use with oasst-based models.

**Comment by oobabooga** [comment]
@Interpause since this issue was created I also made it such that, when Instruct mode is selected by the loader, the character data is no longer lost. If you select "chat" instead of "instruct" in the main tab, the character will reappear unchanged in the Character tab.

That said, there is an use case that I have seen around that is not currently covered, namely using an instruction template to generate the chat in the background while still using the chat html generator. Something like

```
Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Write a role-play chat between two people. Your goal is to write the next response in the chat.

### Input:
You: Hi
Character: Hello

### Response:
```

**Comment by Ph0rk0z** [comment]
I think this does what you mention: https://github.com/anon998/simple-proxy-for-tavern

also this https://github.com/Ph0rk0z/text-generation-webui-testing/blob/DualModel/extensions/long_prompt/script.py but not as well.
