### ISSUE TITLE
server.py: error: unrecognized arguments: --silero_tts

### ISSUE THREAD

**Issue by gzt567** [oobabooga/text-generation-webui#1455]
### Describe the bug

I just installed oobabooga and everything works but it seems I can't add the silero_tts extension because the webUI won't start anymore. I am super new to all of this. Sorry if it's an obvious question.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I edited the "webui.py" and changed line 146 "run_cmd("python server.py --auto-devices --chat --model-menu")" to "run_cmd("python server.py --auto-devices --chat --model-menu --silero_tts") but when I start oobabooga with the "start_windows.bat" it just says 

usage: server.py [-h] [--notebook] [--chat] [--cai-chat] [--model MODEL] [--lora LORA] [--model-dir MODEL_DIR]
                 [--lora-dir LORA_DIR] [--model-menu] [--no-stream] [--settings SETTINGS]
                 [--extensions EXTENSIONS [EXTENSIONS ...]] [--verbose] [--cpu] [--auto-devices]
                 [--gpu-memory GPU_MEMORY [GPU_MEMORY ...]] [--cpu-memory CPU_MEMORY] [--disk]
                 [--disk-cache-dir DISK_CACHE_DIR] [--load-in-8bit] [--bf16] [--no-cache] [--xformers]
                 [--sdp-attention] [--trust-remote-code] [--threads THREADS] [--wbits WBITS] [--model_type MODEL_TYPE]
                 [--groupsize GROUPSIZE] [--pre_layer PRE_LAYER] [--monkey-patch] [--no-quant_attn]
                 [--no-warmup_autotune] [--no-fused_mlp] [--flexgen] [--percent PERCENT [PERCENT ...]]
                 [--compress-weight] [--pin-weight [PIN_WEIGHT]] [--deepspeed] [--nvme-offload-dir NVME_OFFLOAD_DIR]
                 [--local_rank LOCAL_RANK] [--rwkv-strategy RWKV_STRATEGY] [--rwkv-cuda-on] [--listen]
                 [--listen-host LISTEN_HOST] [--listen-port LISTEN_PORT] [--share] [--auto-launch]
                 [--gradio-auth-path GRADIO_AUTH_PATH]
server.py: error: unrecognized arguments: --silero_tts

### Logs

```shell
Gradio HTTP request redirected to localhost :)
usage: server.py [-h] [--notebook] [--chat] [--cai-chat] [--model MODEL] [--lora LORA] [--model-dir MODEL_DIR]
                 [--lora-dir LORA_DIR] [--model-menu] [--no-stream] [--settings SETTINGS]
                 [--extensions EXTENSIONS [EXTENSIONS ...]] [--verbose] [--cpu] [--auto-devices]
                 [--gpu-memory GPU_MEMORY [GPU_MEMORY ...]] [--cpu-memory CPU_MEMORY] [--disk]
                 [--disk-cache-dir DISK_CACHE_DIR] [--load-in-8bit] [--bf16] [--no-cache] [--xformers]
                 [--sdp-attention] [--trust-remote-code] [--threads THREADS] [--wbits WBITS] [--model_type MODEL_TYPE]
                 [--groupsize GROUPSIZE] [--pre_layer PRE_LAYER] [--monkey-patch] [--no-quant_attn]
                 [--no-warmup_autotune] [--no-fused_mlp] [--flexgen] [--percent PERCENT [PERCENT ...]]
                 [--compress-weight] [--pin-weight [PIN_WEIGHT]] [--deepspeed] [--nvme-offload-dir NVME_OFFLOAD_DIR]
                 [--local_rank LOCAL_RANK] [--rwkv-strategy RWKV_STRATEGY] [--rwkv-cuda-on] [--listen]
                 [--listen-host LISTEN_HOST] [--listen-port LISTEN_PORT] [--share] [--auto-launch]
                 [--gradio-auth-path GRADIO_AUTH_PATH]
server.py: error: unrecognized arguments: --silero_tts
```

### System Info

```shell
Windows 10
NVIDIA RTX 4070
```

**Comment by Ph0rk0z** [comment]
--extensions silero_tts?

**Comment by gzt567** [comment]
> 

Oh my... I feel so dumb now! Thank you for giving me eyesight!
