### ISSUE TITLE
cuBLAS support

### ISSUE THREAD

**Issue by Priestru** [oobabooga/text-generation-webui#1457]
https://github.com/ggerganov/llama.cpp/pull/1065

BLAS is an absolute gamechanger on llama.cpp that basically brings GPU fast context evaluation to any CPU model without any VRAM requirements. I tried it myself and can't go back. Please add support for it.

**Comment by Loufe** [comment]
BLAS, from what I understand, is a method of acceleration for CPUs. What Slaren is doing there is completely in fact moving part of what had been crunched with BLAS and moving it to the GPU. I don't see the crossover here for GPTQ (i.e. GPU based inference) here. 

That said, the recent changes brought by Slaren, SW, and GG may not yet be available through https://github.com/abetlen/llama-cpp-python so you could speak with abetlen to make sure llama.cpp inference through the webui is able to take advantage of these gains.

**Comment by oobabooga** [comment]
I'm just the UI maker, this improvement should come upstream from llama-cpp-python as pointed by @Loufe.

**Comment by Priestru** [comment]
> I'm just the UI maker, this improvement should come upstream from llama-cpp-python as pointed by @Loufe.

It's already there, the problem that default installation with install.bat or micromamba-cmd.bat doesn't enable `LLAMA_CUBLAS=1` flag

https://github.com/abetlen/llama-cpp-python/issues/101#issuecomment-1518367392
