### ISSUE TITLE
LoRA training not resuming from most recent checkpoint

### ISSUE THREAD

**Issue by InconsolableCellist** [oobabooga/text-generation-webui#1459]
### Describe the bug

It seems that the training tab won't resume from a LoRA checkpoint.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Steps to reproduce:
1. Start ooba. Go to the Training tab
2. Set a name for your LoRA, save every n steps to 50, add a raw text file dataset
3. Click Start LoRA Training
4. After checkpoints have been saved in folders in <install dir>/loras/<lora name> click interrupt
5. Reload the UI, set the same parameters by clicking "Copy parameters from <lora name>"
6. Ensure "override existing files" is unchecked, such that it should resume
7. Click Star LoRA Training again

Observed results:
Training resumes at step 0. The total training steps aren't reduced by the previously completed steps. Checkpoints are overwritten in the existing folders. Loss is back up to where it started rather than the loss in the latest checkpoint.

Expected results:
The largest checkpoint folder is used to load the LoRA, and training resumes from there. Total steps should be reduced and new saves should be in new checkpoint folders that occur after the resumed checkpoint. E.g., if you got up to "<install dir>/loras/<lora_name>/checkpoint-1000" and have save steps set to 100, the next save should be in "checkpoint-1100", not "checkpoint-100"

Related issues:
This was asked in a question in #827 

### Logs

```shell
$ cat adapter_config.json 
{
  "base_model_name_or_path": "",
  "bias": "none",
  "fan_in_fan_out": false,
  "inference_mode": true,
  "init_lora_weights": true,
  "lora_alpha": 64,
  "lora_dropout": 0.05,
  "modules_to_save": null,
  "peft_type": "LORA",
  "r": 32,
  "target_modules": [
    "q_proj",
    "v_proj"
  ],
  "task_type": "CAUSAL_LM"
}
```

End of training run 1:
```
...
{'loss': 2.2615, 'learning_rate': 0.00023624999999999997, 'epoch': 0.64}                                                                                                            
{'loss': 2.2391, 'learning_rate': 0.0002352083333333333, 'epoch': 0.65}                                                                                                             
{'loss': 2.2458, 'learning_rate': 0.00023416666666666665, 'epoch': 0.66}                                                                                                            
{'loss': 2.2551, 'learning_rate': 0.000233125, 'epoch': 0.67}                                                                                                                       
{'loss': 2.258, 'learning_rate': 0.00023208333333333333, 'epoch': 0.69}                                                                                                             
{'loss': 2.2453, 'learning_rate': 0.00023104166666666667, 'epoch': 0.7}                                                                                                             
{'loss': 2.2393, 'learning_rate': 0.00023, 'epoch': 0.71}   
LoRA training run is completed and saved.
Training interrupted.
```

Start of Run 2, attempted resume:
```
CUDA_VISIBLE_DEVICES=1,0 python server.py --auto-devices --gpu-memory 15 23 --model LLaMA-HF-4bit-128g/llama-30b-4bit-128g --wbits 4 --listen --notebook --model_type LLaMA --groupsize 128 --load-in-8bit --monkey-patch
Gradio HTTP request redirected to localhost :)
Loading LLaMA-HF-4bit-128g/llama-30b-4bit-128g...
Warning: applying the monkey patch for using LoRAs in 4-bit mode.
It may cause undefined behavior outside its intended scope.
Triton not found. Please run "pip install triton".
Loading Model ...
The safetensors archive passed at models/LLaMA-HF-4bit-128g/llama-30b-4bit-128g/4bit-128g.safetensors does not contain metadata. Make sure to save your model with the `save_pretrained` method. Defaulting to 'pt' metadata.
Loaded the model in 203.50 seconds.
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Loading raw text file dataset...
Loading existing LoRA data...
Starting training...
```

Not much to see but in my loras/testLora/ folder it starts editing checkpoint-84, checkpoint-126, etc., rather than resuming at my latest, which was checkpoint-14238
```


### System Info

```shell
Environment:
Model: LLaMA-HF-4bit-128g
HW: 2x 3090s, CUDA, 128 GB system RAM
OS: Artix Linux

HEAD:
commit c4f4f413897ff41266e66c35f253405ecafccbfb (HEAD -> main, origin/main, origin/HEAD)
  Author: oobabooga <112222186+oobabooga@users.noreply.github.com>
  Date:   Fri Apr 21 00:20:33 2023 -0300
  
      Add an "Evaluate" tab to calculate the perplexities of models (#1322)
```

**Comment by oobabooga** [comment]
I think that the idea of the "resume" option is to manually select an existing LoRA and then train on top of it rather than automatically finding the last updated index of a given LoRA and loading it automatically. @mcmonkey4eva

**Comment by InconsolableCellist** [comment]
Thanks for the reply. I can give that a try. I was scared away from doing that by the scary "Warning: Training LoRA over top of another LoRA. May have unexpected effects."

I wonder how hard it'd be to resume from a checkpoint. I'll look into the code.

**Comment by InconsolableCellist** [comment]
I think this will load the "adapter_model.bin" weights from the lora folder, but not the checkpoint subdirectories. If you copy the bin from the checkpoint folder manually this may have the same effect as resuming, sans a reduced number of training steps. I'm waiting (a significant amount of time) to see what the first reported loss looks like after attempting to resume in this way.

**Comment by mcmonkey4eva** [comment]
Don't load the LoRA on the Models tab (if you have LoRAs loaded there you'll want to clear them out and/or reload base model) - go to the train tab and use the same name as an existing LoRA, and same Rank/other core params. You can use the "Copy Parameters From" dropdown to just automate the entirety of that away. As long as "Override" is unchecked, it will load the LoRA by the same name and resume training from there.
(Note: the reason removing loaded LoRAs isn't automated is that there are cases where it can be genuinely useful)

Checkpoint subdirectories are there more for your own usage rn rather than any automation - if your LoRA is overtrained you can grab an earlier checkpoint, if it crashes hard you can use that to recover, etc.

And correct it doesn't currently try a _direct_ resume in terms of picking back up at the step it stopped at, it's a 'new' training run, using the old data as a starting point.
It _is_ possible to save that secondary training-run state data (HF Trainer's internal checkpoints can do this if we enable and use them), though I'm not sure how much actual benefit that adds? And it adds a lot of mess to the files as it also saves a lot of data that definitely doesn't have a use alongside it.

**Comment by tensiondriven** [comment]
@mcmonkey4eva Somewhat orthagonal question - Can you point me to documentation on how to run inference with a checkpoint?  I can't seem to find any info on how to load a model and then apply a checkpoint to it for inference.  (What I tried was to copy my checkpoint folder into "models", then copy the base model and related files into the same directory, and run with something like this:)
```
$ python text-generation-webui/server.py --listen --listen-port 8000 --wbits 4 \
  --model-dir /mnt/ml-metamind/ml/models/checkpoint/  --model llama-30b-4bit \
  --chat  --extensions api
Loading llama-30b-4bit...
...
ModuleNotFoundError: No module named 'llama_inference_offload'
```
Though this may be because my lora and my model are 4-bit.

**Comment by mcmonkey4eva** [comment]
Er... LoRAs are loras, not models. The 'models' are the big fat base things and LoRAs are a special embedding of changes to that base model.

You load the base model as normal, then select the LoRA from the Models tab and click "Apply Selected LoRAs"
(I think you can also do `--lora yourloraname`

(There's some understandable confusion on that as prior to LoRAs being so easy to load, the community would often merge loras into base models and release it that way)

**Comment by tensiondriven** [comment]
@mcmonkey4eva Oh, I get that - I'm asking how one can make use of the checkpoints that are generated during training.  Are they *only* useful for restarting training from a given checkpoint?  My understanding is that they could be used for inference, too, but I can't figure out how to load one against my model.

For example, if you generated a checkpoint every epoch, or half epoch or something, you could run a few test prompts through inference at each checkpoint, and then determine when the model starts over-fitting.  (That was my thinking, anyway.)

**Comment by mcmonkey4eva** [comment]
The LoRA checkpoints are just saved copies of the LoRA. Just pull it out of the subfolder and put it in its own LoRA folder. Aside from the folder its in in, its otherwise exactly the same as a regular LoRA file save. Same content, same format, etc.

(If you're on an outdated copy of the WebUI, they previously saved in a distinct format (HF Trainer Data) that was not so easy to work with)

**Comment by InconsolableCellist** [comment]
Thanks for the answer, it clears it up. There may be another benefit to keeping those training parameters around though (perhaps in the checkpoint folders): the learning rate won't spike back up to the initial value you started training at. I think stopping and starting could have weird effects due to the learning rate being reset, unless you manually set it to the value when you paused training.

The clarification about the checkpoint folders and how it *does* resume would be good to add here: https://github.com/oobabooga/text-generation-webui/wiki/Using-LoRAs

Github doesn't support PRs on wikis, but I'd suggest a clarifying statement or two. Like:

> You can interrupt and resume LoRA training in the "training" tab: if name and rank are the same, training will resume using the "adapter_model.bin" in your LoRA folder. You can resume from a past checkpoint by replacing this file using the contents of one of the checkpoint folders. Note that the learning rate and steps will be reset, and you may want to set the learning rate to the last reported rate in the console output.

**Comment by oobabooga** [comment]
I have moved the wiki entirely into the repository after reaching the conclusion that nobody was reading it: https://github.com/oobabooga/text-generation-webui/tree/main/docs

Contributions to the documentation are welcome.

**Comment by InconsolableCellist** [comment]
I made a small PR for the doc change here: #1474
