### ISSUE TITLE
Clearer documentation

### ISSUE THREAD

**Issue by Zambadulio** [oobabooga/text-generation-webui#1463]
I would like the creators or some charitable user to create a simple and understandable documentation.  Some ideas are:

1. A dedicated page for a wiki
2. Detailed and clear explanations
3. Faq of questions and most common errors
4. Multiple languages

Thanks for reading.

**Comment by InconsolableCellist** [comment]
Have you visited the wiki here? https://github.com/oobabooga/text-generation-webui/wiki There are 15 pages. What guides should be added?

**Comment by Zambadulio** [comment]
Thanks!

**Comment by RayHell** [comment]
Here's one, with the windows installer the INTRUCTION.TXT have this instruction: 
```
Edit the "start" script using a text editor and add the desired flags
to the line that says run_cmd("python server.py --auto-devices --chat --model-menu")
```

The only "start" file is names "start_windows" and inside and it's refering to "call python webui.py"

There's no other file inside oobabooga_windows or text-generation-webui folder named start,
