### ISSUE TITLE
Requesting Autoplay for ElevenLabs TTS

### ISSUE THREAD

**Issue by bubbabug** [oobabooga/text-generation-webui#1471]
I am requesting autoplay functionality for the elevenlabs_tts extension. I am utilizing this extension and it defaults to click to play. I have checked script.py and cannot find a valid variable to manipulate via binary logic.

I do not know if this is an easy fix or not and require assistance implementing this feature. I have exhausted my limited abilities in getting this to work so far.

**Comment by bubbabug** [comment]
I have ported the logic from siler_tts and have gotten autoplay function and show_text working, but I am having a problem where instead of rcording a new message based on current output, I am getting an older message from earlier in the chat. This applies to both the auto played message and when playing the recorded message.

**Comment by bubbabug** [comment]
After removing the previously cached responses, I am now having an issue where audio only generates sporadically. It will not generate during first response, then it will generate on the next response, then it will not generate on the next response, etc. I have looked over the code and cannot find a reason for this behavior, but my abilities are admittedly limited.

**Comment by bubbabug** [comment]
[script.txt](https://github.com/oobabooga/text-generation-webui/files/11328650/script.txt)

Here is the finished script with show text and autoplay implemented. Remember to save as .py and input your api key. I could not get replace messages working, but otherwise it is pretty nice to have.

**Comment by TechnoTaff** [comment]
Fixed via https://github.com/oobabooga/text-generation-webui/pull/1830
