### ISSUE TITLE
Character bias very regulary produce a blank answer

### ISSUE THREAD

**Issue by douchesfeedboard** [oobabooga/text-generation-webui#148]
When using the character bias extension, the bot often produce a blank answer (no text is seen at all into the chat).
When checking into the terminal (because the --verbose is set) , the answer seem truncated.
Here an example with the default bot Chiharu Yamada. I simply asked her how she felt right after her default message :

```
You: How do you feel?
Chiharu Yamada: *I am so h* 
--------------------

Output generated in 0.55 seconds (0.45 it/s, 2 tokens)

```
---

Only 2 tokens were generated for answer which look blank into the chat.

If I ask her to try again, I get the same answer. We can even see in the terminal her previous answer is indeed a blank answer :

```
You: How do you feel?
Chiharu Yamada: 
You: Can you repeat me how do you feel?
Chiharu Yamada: *I am so h* 
--------------------

Output generated in 0.55 seconds (0.46 it/s, 2 tokens)
```

---

A fresh attempt with character bias disabled (still loaded with --extensions but disable with the checkbox) give a correct output (55 tokens).

The issue was reproducible with many attempts (way more blank answers generated than successful output)

**Comment by oobabooga** [comment]
This is expected, the model just doesn't know what to generate after `*I am so h*`. Try something that looks like a realistic sentence beginning like

```
*I am very happy* 
```

Which the model could expand to

```
*I am very happy* So, what shall we do today?
```

**Comment by douchesfeedboard** [comment]
I see. I better understand how it's working now. Seem it was a bad way to ask her about her mood to... check her mood (with the bias) ah ah
With different sentences to try to force her to give a more expanded answer, I got normal results.
Thank you.
