### ISSUE TITLE
Support setting/persisting Character

### ISSUE THREAD

**Issue by tensiondriven** [oobabooga/text-generation-webui#1508]
**Description**
A common use case is to load certain model and character, so that model can be used easily for inference.  Currently, 

- Character cannot be set in settings file
- Refreshing the page loses any settings not in settings file

Having support for setting character via settings file (and ideally API and command line) would allow for more flexibility and improved user experience.

**Additional Context**

This issue could be solved in isolation, but I think this is an example of a whole class of issues that could be solved with a more general solution to state persistence / management.

Overall, TGWUI is great, but the user and developer ergonomics leave a lot to be desired.  I get ghat we're all too busy/excited adding new features to worry about  things like UX and DX, but as the project grows, I think it'll become more important for things like settings and features to be easily dynamically selectable and to have such features be enabled/disabled easily.  This is really a separate feature (preset manager, setting registry, decouple gradio from data model), but worth mentioning, as doing this groundwork would solve this particular issue.

**Comment by tensiondriven** [comment]
Oops, I think this overlaps with #661, which I created about a month ago out of a similar need.

**Comment by oobabooga** [comment]
Too much complaining
