### ISSUE TITLE
Having trouble switching models

### ISSUE THREAD

**Issue by doodooextinction** [oobabooga/text-generation-webui#1526]
### Describe the bug

Hi there,

I’m having quite a bit of trouble switching between models within the UI. If I load the model on start up, it works, but if I switch it while running, it doesn’t work. I set the `—model_type` to `llama` to load certain models such as Alpaca native 7b 4 bit 128g, GPT4 x Alpaca 4 bit 128g, and Alpacino 13b 4 bit 128g.

I have `—wbits 4 —groupsize 128` set, so that’s not the problem.

It’s strange, because I can load Alpacino and it works, then I switch to Pygmalion 6b (which is GPT J 6b based, not LLaMa) and it also works. Then I can switch to GPT4 x Alpaca from Pygmalion (sometimes). But if I try to switch from either of the aforementioned models back to Alpacino it will tell me it cannot determine the model by name. 

Strange!

My first instinct was to add `llama` to the file name; that didn’t work. Then I looked through the bugs list and was told to check the config.json for `”model_type”: “llama”` and found that it was already set.

It could very well be the models I’m using. They may have not been quantized correctly, but they don’t output gibberish when I get them working, so I don’t know.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

UI -> Models Tab -> Change Model Dropdown

### Logs

```shell
`Cannot determine model type by file name. Please use —model_type in args to specify` or something like that
```

### System Info

```shell
Windows 11
Ryzen 5 3600
Nvidia RTX 3060 12gb VRAM
32gb RAM
On C: drive:
Cuda 11.7 & 12.1
Python 3.10.10
Torch 2.0.0 + Cuda 11.8
```

**Comment by Juqowel** [comment]
> My first instinct was to add `llama` to the file name; that didn’t work.

File name or folder name? Try to add "alpaca" to the folder name.

**Comment by doodooextinction** [comment]
Right! So, I said “file name” but as soon as Input llama as part of the folder name (separated with dashes) it worked. Funny!
