### ISSUE TITLE
Bypassing 2k Token Limit: Using LLM to Compress Stories into Summaries for Role-playing Sessions

### ISSUE THREAD

**Issue by Priestru** [oobabooga/text-generation-webui#1531]
I am not sure if this idea has already been put into practice, but I have found a simple solution to bypass the 2k token limit by compressing the story with the help of the language model itself.

In my personal experience, I have successfully compressed entire stories into "story so far" summaries using AI and fed them back to the conversational AI. This technique proved useful during very long role-playing sessions, as it prevented characters from forgetting crucial information.

I believe that implementing a "summary" button that semi-automatically compresses the last 1k tokens into a short summary with a temp 0 setting is feasible. Additionally, I think that users should have the ability to manually adjust the summary as needed.

Compared to trying to remember 2k tokens of a conversation with unsupervised cutting of the latest messages, this technique is immensely superior because entire story arcs can often be condensed into a single sentence.

**Comment by Brawlence** [comment]
https://github.com/Cohee1207/SillyTavern#ui-extensions

>memory

**Comment by Priestru** [comment]
I see. Thank for this link. I'll close issue then.
