### ISSUE TITLE
Inconsistent white space on continued generations

### ISSUE THREAD

**Issue by silvestron** [oobabooga/text-generation-webui#1545]
### Describe the bug

A white space is always added in the middle when using the Continue button. 
Ex. if the response reaches max new tokens and end with an `you`, something like this happens `... you 're ...` if you use the Continue button.

The "Generation attempts (for longer replies)" slider has a different problem, it removes any kind of space between the previous and next generation, such as `... thatwas ...`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Using the Continue button, or the "Generation attempts (for longer replies)" slider to continue interrupted or manually edited responses.

### Logs

```shell
Doesn't generate logs
```

### System Info

```shell
Windows 11 using the one click installer
RTX 3060 desktop with 12GB of VRAM
```

**Comment by oobabooga** [comment]
I think that this should have fixed it https://github.com/oobabooga/text-generation-webui/commit/15940e762e9f9a257fb8ce4f711b5e1ca7740616

**Comment by silvestron** [comment]
It is fixed now for "Generation attempts (for longer replies)", but when using the Continue button the issue is still present. @oobabooga
