### ISSUE TITLE
Bot writes "Human: ..." and "Assistant: ..." after the answer, it's annoying!

### ISSUE THREAD

**Issue by RealAbltanarana** [oobabooga/text-generation-webui#1577]
### Describe the bug

I write the bot and after it responds, it talks to itself as a human and assistant. That messes up the whole conversation
Use Vicuna Model

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

load vicuna model (before 1.1, the 1.1 dont work with webUI)
write in input and press enter

### Screenshot

![Human](https://user-images.githubusercontent.com/131857567/234637138-3093ae4c-4c4f-433f-90ad-f4facb5463df.png)

### Logs

```shell
Starting the web UI...
Gradio HTTP request redirected to localhost :)
bin D:\Programme\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
No model is loaded! Select one in the Model tab.
Loading vicuna-13b-GPTQ-4bit-128g...
Found the following quantized model: models\vicuna-13b-GPTQ-4bit-128g\vicuna-13b-4bit-128g.safetensors
Loading model ...
Done.
Loaded the model in 3.65 seconds.
Output generated in 8.74 seconds (13.61 tokens/s, 119 tokens, context 495, seed 311954708)
Output generated in 1.04 seconds (2.88 tokens/s, 3 tokens, context 611, seed 6965454)
Output generated in 1.09 seconds (2.76 tokens/s, 3 tokens, context 611, seed 471513063)
Output generated in 1.07 seconds (2.81 tokens/s, 3 tokens, context 611, seed 161692402)
Output generated in 1.04 seconds (2.89 tokens/s, 3 tokens, context 611, seed 1206778296)
```

### System Info

```shell
RTX 3090TI (Gigabyte)
i7 12700
64GB RAM
Windows 11
```

**Comment by RandomLegend** [comment]
I have the same issue

**Comment by oobabooga** [comment]
Vicuna is an instruct model, not a general model. Use the proper template

**Comment by RandomLegend** [comment]
But it worked perfectly fine before...

**Comment by oobabooga** [comment]
See if this fixed it https://github.com/oobabooga/text-generation-webui/commit/1d8b8222e95e7669dd431a60866ebdc786ea76dd

**Comment by RandomLegend** [comment]
Sadly not...it's also super slow to write in cai-chat.

using eachaeda vicuna 13b i was on 3,5 tokens / s using cpu before. Now it dropped to 0.69 and takes a very long time to initiate the writing.

**Comment by RandomLegend** [comment]
Oh no, screw my last answer. It works now. Something didn't properly update on my side.

Thank you so much!!
