### ISSUE TITLE
New precise prompts break eachadea_ggml-vicuna-13b-1.1

### ISSUE THREAD

**Issue by nsvrana** [oobabooga/text-generation-webui#1578]
### Describe the bug

These changes seem to break a "default" install of eachadea/ggml-vicuna-13b-1.1-q4, acquired via the UI, both _0 and _2. I now receive blank responses in cai-chat, chat, and instruct modes using both the vicuna and vicuna v0 templates. 

Confirmed it was caused in commit a777c05 by testing commit a840942 which resolves the issue.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Pull commit a777c05 or later. Start the application with 

`python server.py --chat --model eachadea_ggml-vicuna-13b-1.1 --auto-devices --gpu-memory 8`

Use the chat window.

### Screenshot

![image](https://user-images.githubusercontent.com/4226491/234644445-c23f2d33-5d13-42c4-8ad1-b0c2a0005b51.png)

### Logs

```shell
None.
```

### System Info

```shell
Windows 11 using WSL Ubuntu 22.04
Ryzen 3700x
32gb ram
nvidia 2060 Super 8gb
```

**Comment by nsvrana** [comment]
This PR fixed it for me: https://github.com/oobabooga/text-generation-webui/pull/1579

**Comment by RandomLegend** [comment]
@nsvrana how can i implement this PR on my local install? Sorry no idea

**Comment by nsvrana** [comment]
It would be much easier to run `git checkout a840942` which reverts you to before the breaking change while you wait for oobabooga to implement the fix. Once a fix has been implemented you would run:

`git pull`
`git checkout main`

to return to the up-to-date code.

**Comment by RandomLegend** [comment]
Thanks...i did that but apparently i still broke something in my webui.py or something...hmm

**Comment by nsvrana** [comment]
I’m not sure. Looks like oobabooga just pushed the fix, so hop back to main and see if it works. The Assistant/Human thing is a different bug. I can’t help you there.
