### ISSUE TITLE
Contrastive search with API mode

### ISSUE THREAD

**Issue by pi-infected** [oobabooga/text-generation-webui#1585]
Hi, 

Does the following parameters in API mode (https://localhost:5000/api/v1/generate) enables Contrastive Search ?

{'penalty_alpha': 0.6, 'top_k': 4}

It seems enabling it but I'am not sure, it's hard to tell if there is a difference. I'am using vicuna-13B-1.1-GPTQ-4bit-128g on the GPU. 

Best regards,

**Comment by oobabooga** [comment]
You have to also set do_sample=False, otherwise contrastive search doesn't activate

**Comment by pi-infected** [comment]
Perfect, thank you, it is working.
