### ISSUE TITLE
Eleven Labs API as a better alternative to Silero?

### ISSUE THREAD

**Issue by MetaIX** [oobabooga/text-generation-webui#159]
Would it be possible to add support for Eleven Labs through this? https://github.com/lugia19/elevenlabslib

I believe having this implemented along with the inevitable fine-tuned LLaMA would take the chat experience to a completely different level.

**Comment by oobabooga** [comment]
I am not interested in using proprietary services, but feel free to PR if you manage to come up with an extension. It should be simple to modify the silero extension to work with an external API

https://github.com/oobabooga/text-generation-webui/blob/main/extensions/silero_tts/script.py
