### ISSUE TITLE
Please bump llama-cpp-python to enable support for Q5_0 and Q5_1

### ISSUE THREAD

**Issue by Priestru** [oobabooga/text-generation-webui#1597]
Also after i updated it manually, i got the following:

```
 File "server.py", line 914, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/mnt/e/LLaMA/Ubuntu/text-generation-webui/modules/models.py", line 138, in load_model
    model_file = list(Path(f'{shared.args.model_dir}/{model_name}').glob('*ggml*.bin'))[0]
```
    
 So i had to rename file from ggml-vic13b-q5_0.bin to ggml-vic13b-q4_3.bin to load it.
I wonder where model list range is, but we need to update it to include q5_0 and q5_1

It feels wierd that we must have such a strict and limited syntax to just load a model.
llama.cpp itself doesn't need it at all to work, cus it identified proper format nevertheless:

```
llama.cpp: loading model from /mnt/e/LLaMA/oobabooga-windows/text-generation-webui/models/ggml-vic13b-q4_3.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 8 (mostly Q5_0)
```

related to: https://discord.com/channels/1076964370942267462/1090427154141020190/1101036359990390784
and: https://github.com/abetlen/llama-cpp-python/commit/9339929f56ca71adb97930679c710a2458f877bd

**Comment by Ph0rk0z** [comment]
It is because models are only sorted by filename or parameter. There is no real metadata.

**Comment by nsvrana** [comment]
For what it is worth, renaming q5_1.bin to q4_3.bin (or any other q4 as far as a I can tell) did not work for me. I was able to load the model but any chat action failed.

**Comment by Priestru** [comment]
> For what it is worth, renaming q5_1.bin to q4_3.bin (or any other q4 as far as a I can tell) did not work for me. I was able to load the model but any chat action failed.

Did you update your llama_cpp? You need to git pull vendor folder and then python setup.py develop (with cuda or without), after that grab your new files from llama_cpp and move them to your_env'lib\python3.10\site-packages\llama_cpp or build whl and pip install it.

**Comment by nsvrana** [comment]
> > For what it is worth, renaming q5_1.bin to q4_3.bin (or any other q4 as far as a I can tell) did not work for me. I was able to load the model but any chat action failed.
> 
> Did you update your `llama_cpp`? You need to git pull `vendor` folder and then `python setup.py develop` (with cuda or without), after that grab your new files from llama_cpp and move them to `[your_env]\lib\python3.10\site-packages\llama_cpp` or build `whl` and `pip install` it. If you do it on windows then files you need to replace are there `oobabooga-windows\installer_files\env\Lib\site-packages\llama_cpp`

Ahh, I somehow just blanked that part and saw the rename part (wishful thinking I guess!), that would explain it.

**Comment by jayfalls** [comment]
Still an issue for me, so just running 
pip install llama-cpp-python==0.1.39 
in the textgen conda environment fixed this for me

**Comment by oobabooga** [comment]
Done

**Comment by micsthepick** [comment]
don't forget to run `pip instal -U -r requirements.txt` after pulling latest changes!
