### ISSUE TITLE
Adding Fastattention support

### ISSUE THREAD

**Issue by nRuaif** [oobabooga/text-generation-webui#1599]
https://github.com/NVIDIA/FasterTransformer
Implementing FasterTransformer may increase speed, reduce memory usage for many models

**Comment by nRuaif** [comment]
@Ph0rk0z yup, you are right. Maybe implementing flash attention would be better? Flash attention increase speed by 20-30% while reduce context memory.

**Comment by Ph0rk0z** [comment]
Flash attention caused errors and wouldn't run. You can give it a try.
https://github.com/johnsmith0031/alpaca_lora_4bit/blob/main/monkeypatch/llama_flash_attn_monkey_patch.py


This is definitely worth seeing if it helps at all but it looks like huge headache.
