### ISSUE TITLE
LLAMA model. RuntimeError: The expanded size of the tensor (2048) must match the existing size (2095)

### ISSUE THREAD

**Issue by perkel666** [oobabooga/text-generation-webui#160]
Error:

RuntimeError: The expanded size of the tensor (2048) must match the existing size (2095) at non-singleton dimension 0. Target sizes: [2048]. Tensor sizes: [2095]

Cause: Initial implementation of LLAMA models in text-generation doesn't seem to clean context and it runs out of context space after you reach 2048 token limit.

Under 2048 tokens generation works well.

**Comment by Ph0rk0z** [comment]
I have this problem too sometimes. Once you get enough context it overflows.

```
 File "/home/mint/text-generation-webui/llama/llama/generation.py", line 37, in generate
    tokens[k, : len(t)] = torch.tensor(t).long()
RuntimeError: The expanded size of the tensor (2048) must match the existing size (2062) at non-singleton dimension 0.  Target sizes: [2048].  Tensor sizes: [2062]
```

**Comment by oobabooga** [comment]
Running the new branch with the HF implementation should fix this issue

https://github.com/oobabooga/text-generation-webui/issues/147#issuecomment-1454987216
