### ISSUE TITLE
Collecting package metadata (current_repodata.json): \ Conda environment creation failed.

### ISSUE THREAD

**Issue by aviatiq** [oobabooga/text-generation-webui#1604]
### Describe the bug

Collecting package metadata (current_repodata.json): \
Conda environment creation failed.

It just kept happening, I don't know what I've done wrong. All the solutions out there seem to be useless.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

**Start start_windows.bat**
```
Packages to install:
Collecting package metadata (current_repodata.json): -
Conda environment creation failed.
Press any key to continue . . .

``` 

### Screenshot

![image](https://user-images.githubusercontent.com/65436219/234994353-4db11afc-6fbe-433c-b88c-df24064d38d1.png)

### Logs

```shell
Packages to install:
Collecting package metadata (current_repodata.json): -
Conda environment creation failed.
Press any key to continue . . .
```

### System Info

```shell
Windows 10 Pro
AMD RX580
I3-12100F
16GB DDR4 RAM
```

**Comment by xNul** [comment]
@aviatiq a new update was released to the one-click installer. Try downloading it and trying again. Make sure to extract the zip to a new folder and know that it might say conda env creation failed a few times but just ignore those and let it finish

**Comment by aviatiq** [comment]
> @aviatiq a new update was released to the one-click installer. Try downloading it and trying again. Make sure to extract the zip to a new folder and know that it might say conda env creation failed a few times but just ignore those and let it finish

That's exactly what I did. I deleted the previous folder and extract the new one.

Still didn't work as there's also no way to continue.

![image](https://user-images.githubusercontent.com/65436219/235909804-4883f5da-6bcb-4d1a-b1cd-84ea621ca82a.png)

**Comment by xNul** [comment]
@aviatiq very strange. If you open `cmd_windows.bat` does it give you any errors?

**Comment by aviatiq** [comment]
> @aviatiq very strange. If you open `cmd_windows.bat` does it give you any errors?

This happens:
![image](https://user-images.githubusercontent.com/65436219/236013693-77e07150-9eca-44da-acbf-a5c4ec915083.png)

**Comment by xNul** [comment]
@aviatiq if you download Miniconda https://repo.anaconda.com/miniconda/Miniconda3-py310_23.1.0-1-Windows-x86_64.exe, open up a command prompt normally (*not* via `cmd_windows.bat`), cd to the location of your downloaded Miniconda exe, and try installing it with `Miniconda3-py310_23.1.0-1-Windows-x86_64.exe /InstallationType=JustMe /NoShortcuts=1 /AddToPath=0 /RegisterPython=0 /NoRegistry=1 /S /D=%cd%\installer_files\conda` does it work?

**Comment by aviatiq** [comment]
> @aviatiq if you download Miniconda https://repo.anaconda.com/miniconda/Miniconda3-py310_23.1.0-1-Windows-x86_64.exe, open up a command prompt normally (_not_ via `cmd_windows.bat`), cd to the location of your downloaded Miniconda exe, and try installing it with `Miniconda3-py310_23.1.0-1-Windows-x86_64.exe /InstallationType=JustMe /NoShortcuts=1 /AddToPath=0 /RegisterPython=0 /NoRegistry=1 /S /D=%cd%\installer_files\conda` does it work?

Seems like nothing happens and I'm still getting the same error.
![image](https://user-images.githubusercontent.com/65436219/236271522-270dff87-6717-4d38-9abc-4e5700c398e4.png)

**Comment by aviatiq** [comment]
> @aviatiq is there now a folder called `installer_files` in your Downloads folder? If so, try running this command for me while command prompt is in the Downloads folder `"%cd%\installer_files\conda\_conda.exe" create --no-shortcuts -y -k --prefix "%cd%\installer_files\env" python=3.10`. Does it work?

There's no "installer_files" in  my downloads folder after installing Miniconda, but when I CD Obabooga's installer_files (Assuming you were talking about that), it just hangs and nothing happens.
![image](https://user-images.githubusercontent.com/65436219/236289417-d62c784b-1030-476b-aa9b-710aac0eaea9.png)

**Comment by xNul** [comment]
@aviatiq ok try one more thing for me. In your `oobabooga_windows` folder, run this command `"%cd%\installer_files\conda\_conda.exe" create --no-shortcuts -y --prefix "%cd%\installer_files\env2" python=3.10`

It's slightly different than the one you ran before

**Comment by aviatiq** [comment]
> @aviatiq ok try one more thing for me. In your `oobabooga_windows` folder, run this command `"%cd%\installer_files\conda\_conda.exe" create --no-shortcuts -y --prefix "%cd%\installer_files\env2" python=3.10`
> 
> It's slightly different than the one you ran before

Still nothing.
![image](https://user-images.githubusercontent.com/65436219/236296262-da40dc14-744d-4092-b433-539e535b6e2a.png)

**Comment by xNul** [comment]
@aviatiq in that case, there is a problem with Miniconda on your system. This isn't a problem on our end. Open an issue here http://github.com/conda/conda, explain to them that you can't create an environment with Miniconda and once that's resolved, you'll be able to use the one-click installer

**Comment by aviatiq** [comment]
> @aviatiq in that case, there is a problem with Miniconda on your system. This isn't a problem on our end. Open an issue here [http://github.com/conda/conda](https://github.com/conda/conda), explain to them that you can't create an environment with Miniconda and once that's resolved, you'll be able to use the one-click installer

Interestingly, I tried it on my other computer (Which is a laptop running Windows 11 but with no GPU), it managed to go further than that error and in fact, no error so far has happened.

I guess it might be a problem with my Conda on my desktop that something's messed up.

![image](https://user-images.githubusercontent.com/65436219/236513700-20cf6546-4b98-4478-b6e8-bbd17db31d93.png)

![image](https://user-images.githubusercontent.com/65436219/236513716-2840d64d-9dc3-43e1-a3cc-deeb47de6e35.png)

**Comment by aviatiq** [comment]
> @aviatiq in that case, there is a problem with Miniconda on your system. This isn't a problem on our end. Open an issue here [http://github.com/conda/conda](https://github.com/conda/conda), explain to them that you can't create an environment with Miniconda and once that's resolved, you'll be able to use the one-click installer

Update:
I've ran into this problem again, even though I selected "CPU". I have ran into problems like this, but I was able to solve it by adding ARGS (on Stable Diffusion, I meant). However, I'm not sure about this one:
![image](https://user-images.githubusercontent.com/65436219/236517280-69b8c915-5010-47f4-baf4-88bdf3c38ba1.png)

**Comment by xNul** [comment]
@aviatiq the first part makes sense. It makes sense using another computer would work because the problem is definitely specific to your particular computer and install. If you want to fix it on your computer, I'd recommend opening an issues with the conda team.

For the second part, that CUDA error is happening because you're trying to run a model which uses CUDA when you have it set to CPU mode. CUDA is run on the GPU so CUDA-based models can only run on the GPU. You've set CPU so the model cannot run. Try using either `ggml` or `hf` models if you're running on the CPU.

**Comment by aviatiq** [comment]
> @aviatiq the first part makes sense. It makes sense using another computer would work because the problem is definitely specific to your particular computer and install. If you want to fix it on your computer, I'd recommend opening an issue with the conda team.
> 
> For the second part, that CUDA error is happening because you're trying to run a model which uses CUDA when you have it set to CPU mode. CUDA is run on the GPU so CUDA-based models can only run on the GPU. You've set CPU so the model cannot run. Try using either `ggml` or `hf` models if you're running on the CPU.

Okay got it.
I found a GGML for pygmailion,  but then this happens.
![image](https://user-images.githubusercontent.com/65436219/236580870-0dd8c741-4230-43da-bb04-1453e9d7f91a.png)

**Comment by xNul** [comment]
@aviatiq the author says this ggml model can only be used with this person's personal fork https://huggingface.co/alpindale/pygmalion-6b-ggml/discussions/1#643bf31921686867003e92be Should find another model which is compatible with LLaMA.cpp

**Comment by xNul** [comment]
This model will work for example. I've tested it myself https://huggingface.co/Drararara/llama-7b-ggml

**Comment by aviatiq** [comment]
> @aviatiq the author says this ggml model can only be used with this person's personal fork https://huggingface.co/alpindale/pygmalion-6b-ggml/discussions/1#643bf31921686867003e92be Should find another model which is compatible with LLaMA.cpp

Yup, I realized my mistake there. After doing a bit more googling, this works:
https://huggingface.co/waifu-workshop

**Comment by aviatiq** [comment]
Update: It's now fully resolved. I installed Windows 11 on my other SSD and without installing ANYTHING else, it works like a charm.

![image](https://user-images.githubusercontent.com/65436219/236678092-e61f90bb-da9e-4f82-b1a0-8caa28a69a45.png)
