### ISSUE TITLE
Script not replacing <USER> with my username.

### ISSUE THREAD

**Issue by AlexysLovesLexxie** [oobabooga/text-generation-webui#162]
![Screenshot 2023-02-27 020428](https://user-images.githubusercontent.com/126999069/222938463-2bad399d-a473-435f-98e8-163e330519c7.png)

The model is generating responses that contain the tag `<USER>`, but the script is not replacing the tag with my username.  By editing the response, I can see that the tag was there, but the tag is not being interpreted/replaced properly by the script.

Is this a fixable issue?

See above screenshot.

**Comment by oobabooga** [comment]
This should have solved it https://github.com/oobabooga/text-generation-webui/commit/2af66a4d4cd570f22a5d1e1b509f767828357089. Can you make some experiments and see if it worked?

**Comment by AlexysLovesLexxie** [comment]
![Screenshot 2023-03-06 011249](https://user-images.githubusercontent.com/126999069/223067215-68e59038-9a4b-4f97-b0d8-8828b4954b4f.png)

Still not working, unfortunately.  Interestingly, in an earlier chat with her she did use my name properly a couple of times.
I set my name as soon as I pull up the browser window, then I select her character profile.  As I type this, I am trying to get her to generate a new message, but she generated another response with the same thing.

![Screenshot 2023-03-06 012249](https://user-images.githubusercontent.com/126999069/223069419-45dc75be-0afd-4b68-8bda-afd26c25ef8f.png)

**Comment by AlexysLovesLexxie** [comment]
> This should have solved it [2af66a4](https://github.com/oobabooga/text-generation-webui/commit/2af66a4d4cd570f22a5d1e1b509f767828357089). Can you make some experiments and see if it worked?

![Screenshot 2023-03-07 022106](https://user-images.githubusercontent.com/126999069/223394473-2b6ed9aa-dcea-475e-8486-0c94ca00f8b1.png)

Seems to be happening more and more frequently now.  I always make sure to update my install before each run, and I set my name in the UI before choosing my character.

**Comment by oobabooga** [comment]
It is working fine for me, I can't get the chat to display <USER>. It is always replaced by my name.

Make sure that your `chat.py` file contains this line, otherwise it is not up to date.

https://github.com/oobabooga/text-generation-webui/blob/19a34941ed9daeeb93ab951645b61957e4df5376/modules/chat.py#L130

**Comment by AlexysLovesLexxie** [comment]
> It is working fine for me, I can't get the chat to display `<USER>`. It is always replaced by my name.
> 
> Make sure that your `chat.py` file contains this line, otherwise it is not up to date.
> 
> https://github.com/oobabooga/text-generation-webui/blob/19a34941ed9daeeb93ab951645b61957e4df5376/modules/chat.py#L130

I think I see what's going on.
running `install.bat` to update the one-click server install isn't pulling in the replacement.
I will re-download the server and unpack it over what I have and re-run the install.

**Comment by AlexysLovesLexxie** [comment]
Further update - I made the mistake of running install.bat as administrator.

The files were being pulled into `windows/system32/installer_files` and `windows/system32/text-generation-webui` and as such the install was not being updated.

I removed these directories and ran install.bat with normal permissions.  The chat.py now contains the appropriate changes at line 130.

I'm a dumb-butt.

**Comment by AlexysLovesLexxie** [comment]
Issue appears to be fixed.  I was pulling the updates to the wrong place (for weeks, evidently).
