### ISSUE TITLE
JSON Upload Error

### ISSUE THREAD

**Issue by doodooextinction** [oobabooga/text-generation-webui#1643]
### Describe the bug

Whenever I try to load a CharName.json file, whether I upload it or place it directly in the folder, I get an error. Every field in the Character tab says error. I don’t understand what I have done wrong. I query the bot, but it does not appear the bot has any knowledge of the information in the json.

I even get this error when I try to load Example.yaml that came with the install.

*Also, I downloaded and installed with the one-click installer within the last week and don’t know how to I would git pull to update.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I loaded a .json from the UI, then after I tried manually placing it in the folder.

### Screenshot

![IMG_0574](https://user-images.githubusercontent.com/36977651/235273157-8d500a7d-6e51-4494-8a88-49c5546fd354.jpeg)

### Logs

```shell
New character saved to "characters/CharName.json".
Traceback (most recent call last):
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 916, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\oobabooga_windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\oobabooga_windows\text-generation-webui\modules\chat.py", line 435, in load_character
    file_contents = open(filepath, 'r', encoding='utf-8').read()
FileNotFoundError: [Errno 2] No such file or directory: 'characters\\instruction-following\\CharName.json'
```

### System Info

```shell
Windows 11
Nvidia 3060
Local Install
```

**Comment by doodooextinction** [comment]
Strange.

After some testing I got it to work but it’s not point a click.

Here’s what I found:

If I put CharName.json with a single entry in \text-generation-ui\characters AND a file with the same name (CharName.json) with all of my character data, it works. Call me optimistic but I don’t think you meant for it to be like that.

**Comment by boricuapab** [comment]
I've been getting this error as well with either a yaml or json character file, my workaround has been to select the cai-chat or chat radio buttons before selecting a character and I bypass the error.  Then I check on the instruct radio button and start conversing.

@doodooextinction so your fix is to copy the json into both of those directories, but what do you mean by single entry? do you mean just having the first line with the character name?

**Comment by doodooextinction** [comment]
So, in the character folder I put a file called Jason.json, the contents of which were:

`{“any”:”thing”}`

Then I’m the instruction-following folder I put another file called Jason.json with everything in it:

`{“char_name”: “Jason”, “et”: “cetera”}

If the first file contains no contents or empty brackets it responds with an error.

I read the traceback again and I think I know what the problem is. Whatever command sends the json file to the instruction-following folder is putting quotes around the path name. That’s why the backslashes are being escaped. I have encountered this issue in other places, but I’m not smart enough to fix it.

**Comment by boricuapab** [comment]
Thanks this workaround is great of copying the yaml/json files into both locations, I can start chatting immediately via instruct mode.

**Comment by doodooextinction** [comment]
I updated the program and the problem above has been fixed. My workaround makes the program buggy. If you are getting the error above please update your system. The workaround above will bug the program out.
