### ISSUE TITLE
downloading models doesn't include required sub-directories

### ISSUE THREAD

**Issue by matatonic** [oobabooga/text-generation-webui#1658]
### Describe the bug

Not all required files in sub-folders are downloaded automatically. 

Example.

The HugginFace model sentence-transformers/all-MiniLM-L6-v2 : the subfolder "1_Pooling" is required and contains the config.json. The sub-folder path is referenced in modules.json (ironically, it also references a 2_Normalize folder which is non-existent).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Via the webui, download: sentence-transformers/all-MiniLM-L6-v2
the 1_Pooling/config.json is missing and required.

### Logs

```shell
n/a
```

### System Info

```shell
Ubuntu
```

**Comment by Ph0rk0z** [comment]
That is a weird model with special case. If someone puts a model with non standard folders you will have to do some manual intervention to even run it.

**Comment by matatonic** [comment]
The reason I bring it up is because that kind of model (SentenceTransformer) is used by two extensions so far, openai API and the long term memory. It's going to be a regular issue for people to install those models. I'm a bit busy with other stuff but if I get around to implementing a fix for this would it be acceptable? To me it makes the user experience with the add-on modules pretty seamless and shouldn't cause any harm.

I wouldn't think it needs to download every sub-folder, it shouldn't, but it does reference the sub folder in the modules.json, so it seems like any path added to modules.json is worth downloading.

**Comment by Ph0rk0z** [comment]
I thought long term memory downloaded the model by itself. Yea, I see it being an issue in the future. Just a hard one to solve.

**Comment by matatonic** [comment]
Huh, you are correct, I've updated my code and this is no longer needed, so closing.
