### ISSUE TITLE
moving dockerfiles into docker folder breaks things

### ISSUE THREAD

**Issue by loeken** [oobabooga/text-generation-webui#1710]
just a fy the dockerfile/docker-compose do use relative links so by moving them into the docker folder you basically made them not function anymore

**Comment by Darwishavocado** [comment]
alr, then, where do you put the dockerfile?

**Comment by therealpygon** [comment]
> just a fy the dockerfile/docker-compose do use relative links so by moving them into the docker folder you basically made them not function anymore

There are instructions, which include linking the files into the parent folder:
https://github.com/oobabooga/text-generation-webui#alternative-docker
