### ISSUE TITLE
How to use only GPU

### ISSUE THREAD

**Issue by hdpklm** [oobabooga/text-generation-webui#1738]
### Describe the bug

Hello
I use this command to run the model in GPU but its still run cpu,

```sh
python server.py --chat --gpu-memory 6 6 --auto-devices --bf16
```

usage:
| type | processor | memory | comment |
|------|------------|-----------|------------|
| cpu | 88% | 9G | |
| GPU0 | 16% | 0G | intel |
| GPU1 | 19% | 0G | nvidea |

I want to use total power of NVIDEA GPU, and nothing or a littel of CPU

its posible ???

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

(C:\hassan\from-laptop\hassan\gpt\Vicuna\oobabooga_windows\installer_files\env) C:\hassan\from-laptop\hassan\gpt\Vicuna\oobabooga_windows\text-generation-webui>python server.py --chat --gpu-memory 6 6 --auto-devices --bf16  --pre_layer 4
Gradio HTTP request redirected to localhost :)
bin C:\hassan\from-laptop\hassan\gpt\Vicuna\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Loading eachadea_legacy-ggml-vicuna-13b-4bit...
llama.cpp weights detected: models\eachadea_legacy-ggml-vicuna-13b-4bit\ggml-vicuna-13b-4bit-rev1.bin

llama.cpp: loading model from models\eachadea_legacy-ggml-vicuna-13b-4bit\ggml-vicuna-13b-4bit-rev1.bin
llama_model_load_internal: format     = ggjt v1 (latest)
llama_model_load_internal: n_vocab    = 32001
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =  73.73 KB
llama_model_load_internal: mem required  = 9807.47 MB (+ 1608.00 MB per state)
llama_init_from_file: kv self size  = 1600.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

### Logs

```shell
nothing
```

### System Info

```shell
windows 10 pro 64bit
NVIDEA RTX2070
```

**Comment by nsvrana** [comment]
Not an expert, but I think you have two problems:

- Remove `--auto-devices` from the command. That automatically splits between GPU and CPU. 
- You're using a ggml model, which is optimized for CPUs. To use eachdea's Vicuna models, you'll want to use the ones from the https://huggingface.co/eachadea/vicuna-7b-1.1 or https://huggingface.co/eachadea/vicuna-13b-1.1 repositories.
