### ISSUE TITLE
WS API Timeout with large models (solved)

### ISSUE THREAD

**Issue by olamedia** [oobabooga/text-generation-webui#1745]
**Description**

When using API with Tavern and large models (20B+), websocket server throws exception after some time.

**Additional Context**

It is possible to add `ping_interval=None` to avoid disconnect.

`extensions\api\streaming_api.py`
```py
async def _run(host: str, port: int):
    async with serve(_handle_connection, host, port, ping_interval=None):
        await asyncio.Future()  # run forever
```

**Comment by oobabooga** [comment]
https://github.com/oobabooga/text-generation-webui/commit/88cdf6ed3db406b317017aee6a9b9fb7d8f37a7d
