### ISSUE TITLE
Start up mem

### ISSUE THREAD

**Issue by Bennett-Fourr** [oobabooga/text-generation-webui#1747]
### Describe the bug

On start up the porgram can use up to 64 GB of RAM. --cpu-memory dose not fix this.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run a module like gpt-j-6B and watch task manager

### Logs

```shell
NA
```

### System Info

```shell
RTX 3060TI
i711700
64BG ram
```

**Comment by LaaZa** [comment]
Are you loading a model at startup?

**Comment by Bennett-Fourr** [comment]
I mean when the program starts up not windows start up.

**Comment by LaaZa** [comment]
That's what I'm asking about. How are you loading the model, as in what settings do you have?

**Comment by Bennett-Fourr** [comment]
python server.py --chat --model-menu --gpu-memory 6 --cpu-memory 32

**Comment by Bennett-Fourr** [comment]
GPTj-6b
