### ISSUE TITLE
llama.cpp sampler selection

### ISSUE THREAD

**Issue by nsvrana** [oobabooga/text-generation-webui#1764]
**Description**

Please enable, through the CLI or UI, the ability to select different samplers and adjust their parameters when using llama.cpp. In particular, mirostat is showing a lot of promise for improving the quality of text generation.

**Additional Context**

Here's the pull request on the llama.cpp side: https://github.com/ggerganov/llama.cpp/pull/1126

**Comment by oobabooga** [comment]
I have added mirostat in a recent commit, so I'll close this issue
