### ISSUE TITLE
Error in data type

### ISSUE THREAD

**Issue by hdpklm** [oobabooga/text-generation-webui#1766]
https://github.com/oobabooga/text-generation-webui/blob/60be76f0fc43c0f7fb5798cc5bf844c82f496d37/extensions/api/util.py#L35

I thing this parameter shuld be bool not int, because I get this error

```sh
'add_bos_token': int(body.get('add_bos_token', True)),
ValueError: invalid literal for int() with base 10: 'true'
```

**Comment by oobabooga** [comment]
Thanks https://github.com/oobabooga/text-generation-webui/commit/4bf7253ec5676c0927717d513a83a834c45ecaed
