### ISSUE TITLE
Support for Dolly

### ISSUE THREAD

**Issue by MilesQLi** [oobabooga/text-generation-webui#1776]
**Description**

I hope it can support Dolly model https://huggingface.co/databricks/dolly-v2-12b.

**Comment by Maykeye** [comment]
Seems to work fine without any special tweaking, at least

`$ python server.py --model databricks_dolly-v2-12b --load-in-8bit --api`

works

![image](https://user-images.githubusercontent.com/13607441/236111908-3258e012-8451-47b4-82f7-65ea3a77fa36.png)

**Comment by MilesQLi** [comment]
@Maykeye The context input should be written automatically not by the user

**Comment by ClayShoaf** [comment]
In chat mode, you can choose the "instruct" radio button, and then use "Alpaca" from the dropdown to get that formatting in the back end.
