### ISSUE TITLE
How to completely uninstall it

### ISSUE THREAD

**Issue by RYG81** [oobabooga/text-generation-webui#1792]
I feel i make some mistake and now I want to uninstall it completely. How to do that?

**Comment by Brawlence** [comment]
Hmmm.

Complete uninstallation would include:
* removing the text-gen-web-UI folder
* removing the venv folder
* (probably) removing torch hub local cache dir in your user directory
* Uninstalling any additional python libs you installed (if any)
* uninstalling python from the system (assuming you had none and got it during setup)

This should be everything IIRC

**Comment by RYG81** [comment]
any way where it uninstall only what it added? So my other stuff not get disturbed :(

**Comment by ClayShoaf** [comment]
You didn't include anything about your system or how you installed it. Are you on windows? Linux? Mac? Using Docker? One-click-installer? Base git repo?

**Comment by RYG81** [comment]
Ya, sorry for incomplete information-
I ma on windows 10 i used one click installer
I have 32 GB of RAM and Nvidia RTX 370Ti

I first run start_windows.bat and by mistake put run update_windows.bat. I am getting error for gradio missing. 

hope this enough, it would be great if a easy fix is available.

**Comment by ClayShoaf** [comment]
Just delete the folder and start over. It should install everything locally, from what I remember. I haven't booted into windows for a while, so I'm not entirely sure what's happening in the .bat, but if that doesn't work, I can probably boot into windows and take a look in the next few days, if no one helps you out before then.

**Comment by RYG81** [comment]
I reinstall it, it worked. Which model I should download for code generation?

**Comment by ClayShoaf** [comment]
As far as I know, superCOT 30B is probably your best bet. Maybe vicuna-13B-cocktail.
Could you close the issue if it is resolved?

**Comment by RYG81** [comment]
thank you.
