### ISSUE TITLE
Offering additional new features in the web ui

### ISSUE THREAD

**Issue by TRGLN** [oobabooga/text-generation-webui#18]
I suggest adding a couple of useful features in my opinion to the web ui:

1. The ability to restart the web ui with new parameters (for example --load-in-8 bit or --chat)

2. Ability to change Presets parameters in real time in webui.
(for example top_p,top_k,temperature,etc )

**Comment by oobabooga** [comment]
1. Not doable. The interface is not really a single thing, but 3 different interfaces that are loaded depending on your choice (notebook, chat, or default mode).
2. I have pondered about 2, and I think that this would clutter the interface and not be really useful. 10 high quality and diverse settings presets are included, and you can create your own as a text file under `presets/` if you like (just copy one of the existing presets and change the values).

**Comment by oobabooga** [comment]
2. Has been implemented.
