### ISSUE TITLE
Button to regenerate different response?

### ISSUE THREAD

**Issue by chigkim** [oobabooga/text-generation-webui#1803]
**Description**

Can we have a feature to replace the last response with different response?
Its like rolling a dice until you get a response you want to keep.

**Additional Context**

Right now, if you click regenerate, it just regenerate the same response.
Also if you click remove last, and generate, it generates the same thing.
You can edit the last response, but it will be more useful to have the model to rewrite like how TavernAI does it.

**Comment by ClayShoaf** [comment]
It should be regenerating different responses. If it's not, you are probably using a finetuned model (or LoRA merge) which will cause it to land on very similar replies, given the same parameters. You can test this by using a base LLaMA model, or you can probably see different replies if you change your presest to something like `NovelAI-Decadence`

**Comment by chigkim** [comment]
Ah thanks! I was using LLaMA-Precise preset which had top_p 0.1! That makes sense!

**Comment by ClayShoaf** [comment]
Hey, thanks for actually closing your issue! So many people get what they want and then leave the issue open, clogging things up.
