### ISSUE TITLE
is it possible to change the ui a little bit by myself?

### ISSUE THREAD

**Issue by drxmy** [oobabooga/text-generation-webui#1804]
**Description**
I did not see anything related in doc. Since this project is using gradio, I guess this is possible. Does text-generation-webui have such feature? Or could you please tell me which part of code to change? Or i just need to build my own with gradio?

Thank you

**Comment by LaaZa** [comment]
There is no specific feature to edit the UI apart from the different modes `chat, notebook and default`

You have to edit the UI code manually in the python files, mostly `server.py`.

What were you planning to change and why? Could be useful to know if it is something we could improve.

**Comment by drxmy** [comment]
For example, my model can do many different tasks like rewriting, GEC or some NLU. In the simplest case, these tasks are sloved by different prompts which are not visible to users. Then i need many buttons for these tasks.

**Comment by LaaZa** [comment]
So you just want different prompts?

You can use the default or notebook(basically the whole context) to write or select a pre-made prompt.

To add new prompts just make a text file in the prompts dir.

**Comment by drxmy** [comment]
I will give it try first. Thank you!
