### ISSUE TITLE
One-click-installer on Manjaro doesn't install gradio, tqdm, llama-cpp-python

### ISSUE THREAD

**Issue by F4ceMeltor** [oobabooga/text-generation-webui#1822]
### Describe the bug

Following instructions for one-click-install, during the initial install, this error message appears in the final line of the start_linux.sh process

![image](https://user-images.githubusercontent.com/4542271/236584421-9e68444a-e0e1-407b-a241-b827ef7f1a5f.png)

When I then try to run the start_linux.sh again to launch the webui server, this error message appears telling me that the modules gradio and tqdm are missing.

Apparently something prevents the script from installing gradio and tqdm. I have since used yay to install these packages on the PC but it seems to have changed nothing. Should I just reinstall to ubuntu or debian? Are those any easier?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install Manjaro fresh and try to run the one-click-installer.

### Logs

```shell
> Traceback (most recent call last):
>   File "/run/media/undead/VAULT/ailinuxretry/one-click-installers/text-generation-webui/download-model.py", line 19, in <module>
>     import tqdm
> ModuleNotFoundError: No module named 'tqdm'
> Traceback (most recent call last):
>   File "/run/media/undead/VAULT/ailinuxretry/one-click-installers/text-generation-webui/server.py", line 21, in <module>
>     import gradio as gr
> ModuleNotFoundError: No module named 'gradio'
```

### System Info

```shell
GTX 3060
Fresh install of Manjaro Linux
```

**Comment by F4ceMeltor** [comment]
I've reinstalled to Linux Mint and the exact same problem is happening. Something in the installer must be buggy.

**Comment by F4ceMeltor** [comment]
Found the issue, the build only works on the native Linux filesystem, not an extra hard drive.

**Comment by davidhsuUI** [comment]
How do you install them? I installed them under the conda env and for some reason it still doesnt detect them.

**Comment by davidhsuUI** [comment]
ah nevermind i was using "pip install" instead of "conda install"

**Comment by karehto** [comment]
did you ever get it sorted? I am having the same issue

**Comment by davidhsuUI** [comment]
my problem was i didnt run the update bat after installing. apparently you had to do that.. that should install most of the missing packages. if you still see missing packages after that, you need to activate the environment and type "conda install (missing package)" for each missing pacakge.
