### ISSUE TITLE
To load two models of Ancestral: Dolly_Shygmalion-6b-4bit-128g AND PPO_Shygmalion-6b-4bit-128g

### ISSUE THREAD

**Issue by AngelTs** [oobabooga/text-generation-webui#1834]
Can't load two models with custom commands in start_windows.bat:
>python server.py --model Ancestral_Dolly_Shygmalion-6b-4bit-128g\Dolly_Shygmalion-6b-4bit-128g.safetensors --wbits 4 --groupsize 128
>python server.py --model-dir models/Ancestral_PPO_Shygmalion-6b-4bit-128g --model PPO_Shygmalion-6b-4bit-128g.safetensors --wbits 4 --groupsize 128

Produce respective errors:
1.OSError: It looks like the config file at 'models\Ancestral_Dolly_Shygmalion-6b-4bit-128g\Dolly_Shygmalion-6b-4bit-128g.safetensors' is not a valid JSON file.
2.OSError: It looks like the config file at 'models\Ancestral_PPO_Shygmalion-6b-4bit-128g\PPO_Shygmalion-6b-4bit-128g.safetensors' is not a valid JSON file.

**Comment by LaaZa** [comment]
I'm pretty sure the model dir is supposed to be the directory with all model directories and model is the model directory name not the model filename. Also it doesn't make sense to load multiple models since there is no way to select which one you use for each interaction. Start two different instances of textgen instead.

**Comment by AngelTs** [comment]
> I'm pretty sure the model dir is supposed to be the directory with all model directories and model is the model directory name not the model filename. Also it doesn't make sense to load multiple models since there is no way to select which one you use for each interaction. Start two different instances of textgen instead.

I start these two models consecutive, one after another, not parallels or multiple

**Comment by LaaZa** [comment]
But what are you even trying to do?

**Comment by AngelTs** [comment]
> But what are you even trying to do?

I just want to load the f...g model ...

**Comment by LaaZa** [comment]
No but why are you trying to load two models?

**Comment by AngelTs** [comment]
> python server.py --model Ancestral_PPO_Shygmalion-6b-4bit-128g --wbits 4 --groupsize 128

ERROR:Can't determine model type from model name. Please specify it manually using --model_type argument

**Comment by LaaZa** [comment]
Right, sorry. Add --model_type llama

**Comment by AngelTs** [comment]
> Right, sorry. Add --model_type gptj
FInally the model is loaded
>python server.py --model_type gptj --model Ancestral_PPO_Shygmalion-6b-4bit-128g --wbits 4 --groupsize 128
Thank you,

**Comment by LaaZa** [comment]
Sorry, I'm so sleep depraved. Remember to close the issue.
