### ISSUE TITLE
Need extra dependencies to use Vicunia

### ISSUE THREAD

**Issue by matthew-mcallister** [oobabooga/text-generation-webui#1866]
### Describe the bug

When trying to load vicuna-13b-GPTQ-4bit-128g, the operation fails to find the module `llama_inference_offload`.

This can be fixed by cloning https://github.com/qwopqwop200/GPTQ-for-LLaMa, installing its dependencies, and adding the repo to PYTHONPATH.

Ideally, this dependency could added to the repo as a git submodule and installed via script, or installed via PyPI.

### Is there an existing issue for this?

- [X] I have searched the existing issues

EDIT: I suspect that this PR would fix this issue: https://github.com/oobabooga/text-generation-webui/pull/1668

### Reproduction

Try to load vicuna-13b-GPTQ-4bit-128g. The model seems to be GPU accelerated when I run it, so this might only occur with a GPU present.

### Screenshot

![image](https://user-images.githubusercontent.com/6722367/236653536-0ba7e191-1f37-499c-ac58-2807fa313431.png)

### Logs

```shell
Traceback (most recent call last):
File “/home/mattmcal/drive/text-generation-webui/server.py”, line 59, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name)
File “/home/mattmcal/drive/text-generation-webui/modules/models.py”, line 157, in load_model from modules.GPTQ_loader import load_quantized
File “/home/mattmcal/drive/text-generation-webui/modules/GPTQ_loader.py”, line 15, in import llama_inference_offload
ModuleNotFoundError: No module named ‘llama_inference_offload’
```

### System Info

```shell
OS: Debian bookworm
CPU: AMD Ryzen 9 5950X 16-Core Processor
RAM: 64G
GPU: NVIDIA GeForce RTX 3080 Lite Hash Rate
```

**Comment by oobabooga** [comment]
Literally read the documentation

https://github.com/oobabooga/text-generation-webui/blob/main/docs/GPTQ-models-(4-bit-mode).md
