### ISSUE TITLE
Can't load extensions

### ISSUE THREAD

**Issue by ShmuelRonen** [oobabooga/text-generation-webui#1898]
### Describe the bug

When I try to load extansions "send_pictures" "sd_api_pictures" I got this Error:

INFO:Loaded the model in 41.89 seconds.
INFO:Loading the extension "send_pictures"...
INFO:Loading the extension "sd_api_pictures"...
Traceback (most recent call last):
  File "C:\oobabooga_windows\text-generation-webui\server.py", line 885, in <module>
    create_interface()
  File "C:\oobabooga_windows\text-generation-webui\server.py", line 803, in create_interface
    extensions_module.create_extensions_block()
  File "C:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 150, in create_extensions_block
    extension.ui()
  File "C:\oobabooga_windows\text-generation-webui\extensions\send_pictures\script.py", line 44, in ui
    lambda picture, name1, name2: input_hijack.update({"state": True, "value": generate_chat_picture(picture, name1, name2)}), [picture_select, shared.gradio['name1'], shared.gradio['name2']], None).then(
KeyError: 'name1'

Done!
Press any key to continue . . .

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Include

### Screenshot

![Capture](https://user-images.githubusercontent.com/80190186/236721870-e7b375e4-1b96-4787-bc7a-ef5affbcad54.JPG)

### Logs

```shell
Include
```

### System Info

```shell
Device name	DESKTOP-89OI1TC
Processor	AMD Ryzen 7 6800H with Radeon Graphics            3.20 GHz
Installed RAM	32.0 GB (31.2 GB usable)
Device ID	57F773B6-2052-4400-9EEE-5DA99ADC9758
Product ID	00331-20350-00000-AA537
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
GPU		Nvidia RTX 3090
```

**Comment by oobabooga** [comment]
These extensions only work in chat mode, try --chat

**Comment by ShmuelRonen** [comment]
> These extensions only work in chat mode, try --chat

Thanks!
