### ISSUE TITLE
HTML tab while running the 4chan model isnt formatting correctly.

### ISSUE THREAD

**Issue by BushyToaster88** [oobabooga/text-generation-webui#19]
Its just doing a white background with black text and nothing else.
![image](https://user-images.githubusercontent.com/67993175/213872424-eb1b7dc6-75f1-4a33-8209-52d83473e4eb.png)

**Comment by oobabooga** [comment]
Did you put the model under `models/gpt4chan_model_float16` or `models/gpt4chan_model`?

**Comment by BushyToaster88** [comment]
> Did you put the model under `models/gpt4chan_model_float16` or `models/gpt4chan_model`?

Changing it to `models/gpt4chan_model` worked, thanks.
