### ISSUE TITLE
Chat log no longer dims when generating

### ISSUE THREAD

**Issue by AlexysLovesLexxie** [oobabooga/text-generation-webui#191]
The chat log area no longer dims when responses are being generated.
![Screenshot 2023-03-08 031454](https://user-images.githubusercontent.com/126999069/223699419-50a0d2ee-5388-49e6-a1db-132023e2ce94.png)

Not sure if this is intended as part of one of the new upgrades.  If so, is there any way yo make this a toggle-able feature, as it provides more of a visual feedback to let me know that the server is doing its thing.

**Comment by Ph0rk0z** [comment]
This was done in a commit. If you are scrolling down and looking at stuff you can miss when your reply is finished.

**Comment by oobabooga** [comment]
Yep, I changed this because I was annoyed by the chat blinking all the time. I felt like that broke immersion. 

There is still a gradio progress indicator at the top of the chat box.
