### ISSUE TITLE
Move Model Downloading And Selection to Web UI

### ISSUE THREAD

**Issue by MilesQLi** [oobabooga/text-generation-webui#1913]
**Description**

More convenient to use them than in console.

**Comment by Manoz** [comment]
What do you mean? You can already download models and loras in the "Model" tab

<img width="717" alt="Screenshot 2023-05-08 at 15 36 27" src="https://user-images.githubusercontent.com/1554207/236838519-6a6fac96-efd5-4389-be98-fc82a6e13ccc.png">
