### ISSUE TITLE
Is split offloading supported for 8bit mode?

### ISSUE THREAD

**Issue by RandomInternetPreson** [oobabooga/text-generation-webui#193]
It would be really great to run the LLaMA 30B model in 8bit mode, but right now I can't get the memory to split between gpu and CPU using 8bit mode.

I feel like if this were possible it would be the revolutionary!

**Comment by sgsdxzy** [comment]
It is possible, but requires some hack:
1. instead of pass `load_in_8bit=True` directly, construct a `BitsAndBytesConfig(load_in_8bit=True, llm_int8_enable_fp32_cpu_offload=True)` and pass as quantization_config to from_pretained. This is relative easy.
2. https://github.com/huggingface/transformers/issues/22018 of support offloading in auto device mapping is rejected in transformers. So we have to manually build our device map first. I'd rather monkey-patch from_pretained in transformers to just accept auto mapping...

**Comment by oobabooga** [comment]
That's new to me. @sgsdxzy, can you copy and paste the exact modifications that you had to make to get this working for clarity?

**Comment by oobabooga** [comment]
Related to #190

**Comment by ye7iaserag** [comment]
If this solution can be integrated here... the possibilities!

**Comment by sgsdxzy** [comment]
@oobabooga I was originally preparing a pr for you... now that the transformers part is rejected thing get a bit difficult.
The fastest way to get this to work:

1. edit text-generation-webui/modules/models.py line 102 from `params.append("load_in_8bit=True"...` to `params.append("quantization_config=BitsAndBytesConfig(load_in_8bit=True, llm_int8_enable_fp32_cpu_offload=True)")` (or you can just use `params.extend(["load_in_8bit=True", "llm_int8_enable_fp32_cpu_offload=True"]`)
2. edit python's site-packages\transformers\modeling_utils.py, in from_pretrained, search for " # Extend the modules to not convert to keys that are supposed to be offloaded to `cpu` or `disk`", copy the following part starting with `if isinstance(device_map, str):` (the part that convert device map from 'auto' to a dict) and paste before " # Extend the modules to not convert to keys that are supposed to be offloaded to `cpu` or `disk`"

And pass --load-in-8bit --auto-devices to server.py.

**Comment by RandomInternetPreson** [comment]
Oh my frick... thank you so much kind internet stranger. I was able to use your code and can bifurcate 8-bit between cpu and gpu oh my god, wow like absolutely incredible thank you so much!

**Comment by athu16** [comment]
> 1. params.append("quantization_config=BitsAndBytesConfig(load_in_8bit=True, llm_int8_enable_fp32_cpu_offload=True)")

@sgsdxzy I tried your method, however I get this error:

**Comment by oobabooga** [comment]
Fixed in #358. Just use `--load-in-8bit --gpu-memory 10` or similar.
