### ISSUE TITLE
504 Server Error Gateway Time-out for url when downloading a model

### ISSUE THREAD

**Issue by leszekhanusz** [oobabooga/text-generation-webui#1939]
### Describe the bug

I tried to download the [TheBloke/WizardLM-7B-uncensored-GPTQ model](https://huggingface.co/TheBloke/WizardLM-7B-uncensored-GPTQ) but I receive a 504 error code.

I'm not sure if I'm doing something wrong or if it's down for everybody.
The [HuggingFace status page](https://status.huggingface.co/) seems to indicate that everything is running smoothly for now.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
$ python download-model.py TheBloke/WizardLM-7B-uncensored-GPTQ
Traceback (most recent call last):
  File "/mnt/tera/git-repos/text-generation-webui/download-model.py", line 267, in <module>
    links, sha256, is_lora = get_download_links_from_huggingface(model, branch, text_only=args.text_only)
  File "/mnt/tera/git-repos/text-generation-webui/download-model.py", line 102, in get_download_links_from_huggingface
    r.raise_for_status()
  File "/mnt/tera/miniconda3/envs/textgen/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://huggingface.co/api/models/TheBloke/WizardLM-7B-uncensored-GPTQ/tree/main
```

### Logs

```shell
N/A
```

### System Info

```shell
N/A
```

**Comment by Cobrabb** [comment]
It seems like maybe the huggingface API is having trouble, because I tried to access "https://huggingface.co/api/models/facebook/opt-6.7b/tree/main" in the browser and it similarly timed out and gave a 504 error. Probably not an issue with this tool.

**Comment by Cobrabb** [comment]
Does anyone have a good guide for how to manually install models? I can see where the tool tells me to put them but I'm not sure what files I should put there and in what structure. With stable diffusion it's a single model file but it seems like these models are composed of multiple files. Do I put the whole folder?

**Comment by tandpastatester** [comment]
I'm having this issue since this morning. Either the API is unreachable or some address has changed.

@Cobrabb put the files inside the /models folder in the main dir of ooba. Or you can try `git clone https://huggingface.co/api/models/facebook/opt-6.7b` inside your /models folder.

**Comment by Baael** [comment]
both hf and git clone are giving me 504, github seems to have a lot of problems today too

**Comment by leszekhanusz** [comment]
It was fixed.
