### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by ArmourG2** [oobabooga/text-generation-webui#1973]
### Describe the bug

I try to run it in collab : https://github.com/eucdee/AI
When I run all the cell, it work perfectly. But can't launch it for some reason

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

.

### Logs

```shell
/content/drive/MyDrive/text-generation-webui
python server.py --share --model TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g --model_type LLaMa --settings settings-colab.json --groupsize 128 --load-in-8bit --extensions gallery --wbits 4
INFO:NumExpr defaulting to 2 threads.
INFO:Gradio HTTP request redirected to localhost :)
WARNING:The gradio "share link" feature downloads a proprietary and unaudited blob to create a reverse tunnel. This is potentially dangerous.
2023-05-10 13:10:20.526329: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
bin /usr/local/lib/python3.10/dist-packages/bitsandbytes/libbitsandbytes_cuda118.so
INFO:Loading settings from settings-colab.json...
INFO:Loading TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g...
INFO:Found the following quantized model: models/TheBloke_vicuna-13B-1.1-GPTQ-4bit-128g/vicuna-13B-1.1-GPTQ-4bit-128g.latest.safetensors
INFO:Loaded the model in 61.61 seconds.
INFO:Loading the extension "gallery"...
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/drive/MyDrive/text-generation-webui/server.py:934 in <module>       │
│                                                                              │
│   931 │   │   })                                                             │
│   932 │                                                                      │
│   933 │   # Launch the web UI                                                │
│ ❱ 934 │   create_interface()                                                 │
│   935 │   while True:                                                        │
│   936 │   │   time.sleep(0.5)                                                │
│   937 │   │   if shared.need_restart:                                        │
│                                                                              │
│ /content/drive/MyDrive/text-generation-webui/server.py:852 in                │
│ create_interface                                                             │
│                                                                              │
│   849 │   │   shared.gradio['interface'].load(partial(ui.apply_interface_val │
│   850 │   │   # Extensions block                                             │
│   851 │   │   if shared.args.extensions is not None:                         │
│ ❱ 852 │   │   │   extensions_module.create_extensions_block()                │
│   853 │                                                                      │
│   854 │   # Launch the interface                                             │
│   855 │   shared.gradio['interface'].queue()                                 │
│                                                                              │
│ /content/drive/MyDrive/text-generation-webui/modules/extensions.py:158 in    │
│ create_extensions_block                                                      │
│                                                                              │
│   155 │   │   │   for extension, name in iterator():                         │
│   156 │   │   │   │   if hasattr(extension, "ui"):                           │
│   157 │   │   │   │   │   gr.Markdown(f"\n### {name}")                       │
│ ❱ 158 │   │   │   │   │   extension.ui()                                     │
│   159                                                                        │
│                                                                              │
│ /content/drive/MyDrive/text-generation-webui/extensions/gallery/script.py:96 │
│ in ui                                                                        │
│                                                                              │
│   93 │   │   │   │   │   │   │    samples_per_page=50                        │
│   94 │   │   │   │   │   │   │    )                                          │
│   95 │   update.click(generate_html, [], gallery)                            │
│ ❱ 96 │   gallery.select(select_character, None, gradio['character_menu'])    │
│   97                                                                         │
╰──────────────────────────────────────────────────────────────────────────────╯
KeyError: 'character_menu'
```

### System Info

```shell
using google Colab notebook
```

**Comment by Ingrem** [comment]
Have same problem, i use: same model, collab and oobabooga/text-generation-webui
It seems "gallery" extension broken, so as a fix i comment this lines

text-generation-webui/modules/extensions.py
def ui():
    #with gr.Accordion("Character gallery", open=False):
        #update = gr.Button("Refresh")
        #gr.HTML(value="<style>" + generate_css() + "</style>")
        #gallery = gr.Dataset(components=[gr.HTML(visible=False)],
                             #label="",
                             #samples=generate_html(),
                             #elem_classes=["character-gallery"],
                             #samples_per_page=50
                             #)
    #update.click(generate_html, [], gallery)
    #gallery.select(select_character, None, gradio['character_menu'])
    
It still print errors, but actually skip extention load and run gradio web UI.

I guess we need to add some try catch for problems like this, then some extention block all program from running.

**Comment by beckettech** [comment]
I fixed this by cutting the settings portion of the cmd line. Here is what mine looks like:

# Starting the web UI
cmd = f"python server.py --share --model {model_load}"

**Comment by ArmourG2** [comment]
> I fixed this by cutting the settings portion of the cmd line. Here is what mine looks like:
> 
> Starting the web UI cmd = f"python server.py --share --model {model_load}"

This method won't allow us to use:
![chrome_ElJsRcjdDc](https://github.com/oobabooga/text-generation-webui/assets/109402288/8b46cac3-2cb1-41c2-8f47-b54857a0a00f)

I don't know what did I do but I delete this line at extensions.py:
![chrome_m0JUDD4Kxk](https://github.com/oobabooga/text-generation-webui/assets/109402288/df63205d-68a2-4801-9ef4-33080c03a6d3)

For now, this method seem to fix the problem. At least for me. Does anyone have any idea why?

**Comment by ms-KuroNeko** [comment]
I'm a Chinese, my English is not very well, and the following English parts are automatically generated by Bing Translator
【方便外国兄逮理解的英文都是机翻，你们不用认真看】

这个其实是作者没有写清楚导致的锅，你必须先使用 --chat 参数启动webui，进入对话模式
进入这个模式后 gallery 这个扩展会自动加载

This is actually a problem caused by the author not writing clearly, you must first use the --chat parameter to start WebUI and enter the dialogue mode
After entering this mode, the gallery extension will be loaded automatically

---------------------------

启动之后你们可能无法打开webui，会出现如下错误
After booting, you may not be able to open WebUI, and the following error will appear

> module pil.image has no attribute resampling

这是你们没有正确安装 pillow 或者版本低于10，你们需要
This is because you guys didn't install Pillow correctly or the version is lower than 10, which you need

> pip install pillow --upgrade
