### ISSUE TITLE
Character dropdown can't be clicked. 

### ISSUE THREAD

**Issue by kuso-ge** [oobabooga/text-generation-webui#1975]
### Describe the bug

Using commit 32481ec4d62f68f0fc22cb613f5711017e4bbb3f
Can't click the dropdown menu in Character tab. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Start webui
2. Load a model (maybe not necessary)
3. Go to Character tab
4. Navigate to character drop down.

Can't click the character drop down. The cursor turns into prohibition/no sign. 

### Screenshot

![343079924_569553048581146_6264846036331207569_n](https://github.com/oobabooga/text-generation-webui/assets/12083007/ae2a0b47-4271-4b05-aea0-401ea2eb1307)

### Logs

```shell
No console errors.
```

### System Info

```shell
GPU:RTX 3060 12GB VRAM
MEMORY: 16GB RAM
CPU: Ryzen 5 5600G
Webui: commit 32481ec4d62f68f0fc22cb613f5711017e4bbb3f
```

**Comment by Ph0rk0z** [comment]
Did you install correct gradio stuff from the requirements.txt? It just changed.

**Comment by NeuralBlankes** [comment]
Having a similar issue, but it appears that the problem, for me at least, is that it's looking for the character files (i.e. example.yaml) in the instruction-following folder that is found inside the character folder.  Attempting to select a character results in the console stating that the file cannot be found in the instruction-following directory.   However it's still looking in the main "characters" folder for the related image files (i.e. Example.png)
"FileNotFoundError: [Errno 2] No such file or directory: 'characters\\instruction-following\\Example.yaml"
I moved the Example.yaml file to this folder, and restarted, but it does not appear to recognize that the Example.yaml file is in the directory (the same applies to a .json character file I tested with).

**Comment by NeuralBlankes** [comment]
> pip install gradio_client==0.1.4 pip install gradio==3.25.0
> 
> It is working here and I just merged these same commits.
> 
> Also instruct vs chat. Get out of instruct mode to select chars. Otherwise select instruct template from the first page.

Thank you.  I didn't notice it was loading in instruct mode.
