### ISSUE TITLE
I want to use the CPU only mode but keep getting: AssertionError("Torch not compiled with CUDA enabled")

### ISSUE THREAD

**Issue by gsirvine** [oobabooga/text-generation-webui#1979]
### Describe the bug

I want to use the CPU only mode but keep getting: AssertionError("Torch not compiled with CUDA enabled")

I understand CUDA is for GPU's.  I have an AMD GPU though so I am selecting CPU only mode.  I have seen others having the same or similar torch CUDA error but it seems like in many cases they actually have a GPU with CUDA cores.

Maybe this has something to do with the models I'm testing out.  But I've tested quite a few.  Some even have other issues.  

My CPU is decently powerful, so it's not like I'm trying this on a laptop.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

CPU only mode is selected in the install.  On the last step of opening the start bat for windows.  This is where the error comes up.

I repeated the entire installation from scratch with all antivirus / firewalls disabled.  I even tried the following before the install.

pip uninstall torch
pip cache purge

Deleted "text-generation-webui" folder inside the "oobabooga_windows" folder

### Screenshot

![Screenshot](https://github.com/oobabooga/text-generation-webui/assets/32781300/bede9c27-c618-49be-a14c-efbfd1deffc2)

### Logs

```shell
INFO:Loading facebook_opt-6.7b...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [00:06<00:00,  3.02s/it]
Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\text-generation-webui\server.py", line 921, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\models.py", line 90, in load_model
    model = model.cuda()
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

### System Info

```shell
OS Version: 
Windows 10.0.19045 Build 19045

Processor: 
11th Gen Intel(R) Core(TM) i9-11900KF @ 3.50GHz, 3504 Mhz, 8 Core(s), 16 Logical Processor(s)

Installed Physical Memory (RAM):
64.0 GB
```

**Comment by jllllll** [comment]
You need to use the `--cpu` command-line flag to tell webui to run on CPU. Add it to line 167 of `webui.py`.

**Comment by gsirvine** [comment]
> You need to use the `--cpu` command-line flag to tell webui to run on CPU. Add it to line 167 of `webui.py`.


run_cmd("python server.py --chat --model-menu", environment=True,)  # put your flags here!

How do I add that flag?   I tried and there must have been a syntax error because it didn't work.

**Comment by jllllll** [comment]
> > You need to use the `--cpu` command-line flag to tell webui to run on CPU. Add it to line 167 of `webui.py`.
> 
> I found the following line: **run_cmd("python server.py --chat --model-menu", environment=True,) # put your flags here!**
> 
> How do I add that flag? I tried and there must have been a syntax error because it didn't work.

Change it to this:
```Python
run_cmd("python server.py --chat --model-menu --cpu", environment=True,) # put your flags here!
```

**Comment by gsirvine** [comment]
> > > You need to use the `--cpu` command-line flag to tell webui to run on CPU. Add it to line 167 of `webui.py`.
> > 
> > 
> > I found the following line: **run_cmd("python server.py --chat --model-menu", environment=True,) # put your flags here!**
> > How do I add that flag? I tried and there must have been a syntax error because it didn't work.
> 
> Change it to this:
> 
> ```python
> run_cmd("python server.py --chat --model-menu --cpu", environment=True,) # put your flags here!
> ```

Thanks it is running now!

**Comment by menelic** [comment]
unfortunately this fix does not work with the one-click linux installer. My webui.py looks different, so I added the flag here

![image](https://github.com/oobabooga/text-generation-webui/assets/5934115/614434f1-537c-47c9-9213-f6e58ea7963d)


with that the AssertionError: Torch not compiled with CUDA enabled disappeared and the process got to this stage:


![image](https://github.com/oobabooga/text-generation-webui/assets/5934115/63c16e84-84e7-411c-959a-ee911b29e6fc)


but with that, terminal closes - how can I make this work on Ubuntu 22.04?

**Comment by opria-arch** [comment]
> > > You need to use the `--cpu` command-line flag to tell webui to run on CPU. Add it to line 167 of `webui.py`.
> > 
> > 
> > I found the following line: **run_cmd("python server.py --chat --model-menu", environment=True,) # put your flags here!**
> > How do I add that flag? I tried and there must have been a syntax error because it didn't work.
> 
> Change it to this:
> 
> ```python
> run_cmd("python server.py --chat --model-menu --cpu", environment=True,) # put your flags here!
> ```

The webui notepad file looks like this. Where should I put the line that you mentioned exactly? I put it at the end after webui.py but it didn't recognize the command.
"@echo off

cd /D "%~dp0"

set PATH=%PATH%;%SystemRoot%\system32

echo "%CD%"| findstr /C:" " >nul && echo This script relies on Miniconda which can not be silently installed under a path with spaces. && goto end

@rem fix failed install when installing to a separate drive
set TMP=%cd%\installer_files
set TEMP=%cd%\installer_files

@rem config
set INSTALL_DIR=%cd%\installer_files
set CONDA_ROOT_PREFIX=%cd%\installer_files\conda
set INSTALL_ENV_DIR=%cd%\installer_files\env
set MINICONDA_DOWNLOAD_URL=https://repo.anaconda.com/miniconda/Miniconda3-py310_23.1.0-1-Windows-x86_64.exe
set conda_exists=F

@rem figure out whether git and conda needs to be installed
call "%CONDA_ROOT_PREFIX%\_conda.exe" --version >nul 2>&1
if "%ERRORLEVEL%" EQU "0" set conda_exists=T

@rem (if necessary) install git and conda into a contained environment
@rem download conda
if "%conda_exists%" == "F" (
	echo Downloading Miniconda from %MINICONDA_DOWNLOAD_URL% to %INSTALL_DIR%\miniconda_installer.exe

	mkdir "%INSTALL_DIR%"
	call curl -Lk "%MINICONDA_DOWNLOAD_URL%" > "%INSTALL_DIR%\miniconda_installer.exe" || ( echo. && echo Miniconda failed to download. && goto end )

	echo Installing Miniconda to %CONDA_ROOT_PREFIX%
	start /wait "" "%INSTALL_DIR%\miniconda_installer.exe" /InstallationType=JustMe /NoShortcuts=1 /AddToPath=0 /RegisterPython=0 /NoRegistry=1 /S /D=%CONDA_ROOT_PREFIX%

	@rem test the conda binary
	echo Miniconda version:
	call "%CONDA_ROOT_PREFIX%\_conda.exe" --version || ( echo. && echo Miniconda not found. && goto end )
)

@rem create the installer env
if not exist "%INSTALL_ENV_DIR%" (
  echo Packages to install: %PACKAGES_TO_INSTALL%
  call "%CONDA_ROOT_PREFIX%\_conda.exe" create --no-shortcuts -y -k --prefix "%INSTALL_ENV_DIR%" python=3.10 || ( echo. && echo Conda environment creation failed. && goto end )
)

@rem check if conda environment was actually created
if not exist "%INSTALL_ENV_DIR%\python.exe" ( echo. && echo Conda environment is empty. && goto end )

@rem activate installer env
call "%CONDA_ROOT_PREFIX%\condabin\conda.bat" activate "%INSTALL_ENV_DIR%" || ( echo. && echo Miniconda hook not found. && goto end )

@rem setup installer env
call python webui.py

echo.
echo Done!

:end
pause"

**Comment by jllllll** [comment]
@opria-arch
It needs to be in `webui.py` which was recently updated to include a spot towards the top to put args.
Change `CMD_FLAGS = '--chat --model-menu'` to `CMD_FLAGS = '--chat --model-menu --cpu'`

If you haven't updated the installer recently, then the line you need to change is line 167 near the bottom of the file.
