### ISSUE TITLE
running build_ext WinError 2 File Not Found

### ISSUE THREAD

**Issue by Paillat-dev** [oobabooga/text-generation-webui#1980]
### Describe the bug

I tought a lot before opening this pull request, because I'm sure there's an easy fix for that.

I am getting an error while installing the [4-bit GPTQ mode](https://github.com/oobabooga/text-generation-webui/blob/main/docs/GPTQ-models-(4-bit-mode).md). I am of course running it in the x64 console, and followed all steps.

I am getting this error in both the one click installer and the manual install. The install work fine except for that feature. I am also running o this issue when running the "update" one click script.

Already tried a lot of things including repairing visual studio (wich works fine btw) and adding it to path just to make sure (even if that shouldn't be needed if running it in the visual studio terminal)

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

Just install it in native windows and try to install the [4-bit GPTQ mode](https://github.com/oobabooga/text-generation-webui/blob/main/docs/GPTQ-models-(4-bit-mode).md) patch.

### Screenshot

I don't think a screenshot is needed.

### Logs

```shell
Successfully installed accelerate-0.18.0 datasets-2.10.1 safetensors-0.3.0 transformers-4.28.0

[notice] A new release of pip is available: 23.1.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Processing d:\09._ai_projects\openassistant\oobabooga_windows\text-generation-webui\repositories\gptq-for-llama
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: quant-cuda
  Building wheel for quant-cuda (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      running bdist_wheel
      running build
      running build_ext
      error: [WinError 2] Le fichier spécifié est introuvable
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quant-cuda
  Running setup.py clean for quant-cuda
Failed to build quant-cuda
ERROR: Could not build wheels for quant-cuda, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.1.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
```

### System Info

```shell
Windows 11 Home
Visual Studio 2019 community
Nvidia A4500
AMD EPYC 7543P 32-Core Processor
16GB ram
```

**Comment by poisenbery** [comment]
I'm also encountering this issue

**Comment by Paillat-dev** [comment]
Ok this is a duplicate of #1937
