### ISSUE TITLE
BUG - server.py: error: unrecognized arguments: --cai-chat

### ISSUE THREAD

**Issue by HorrySheet** [oobabooga/text-generation-webui#2010]
### Describe the bug

New installation (after deleting any relevant text generation and oobabooga folders on gdrive)  using the colab notebook I get..

/content/text-generation-webui
python server.py --share --model anon8231489123_vicuna-13b-GPTQ-4bit-128g --settings settings-colab.json --extensions silero_tts gallery --no-stream --wbits 4 --cai-chat --groupsize 128
INFO:NumExpr defaulting to 2 threads.
INFO:Gradio HTTP request redirected to localhost :)
usage: server.py
       [-h]
       [--notebook]
       [--chat]
       [--character CHARACTER]
       [--model MODEL]
       [--lora LORA [LORA ...]]
       [--model-dir MODEL_DIR]
       [--lora-dir LORA_DIR]
       [--model-menu]
       [--no-stream]
       [--settings SETTINGS]
       [--extensions EXTENSIONS [EXTENSIONS ...]]
       [--verbose]
       [--cpu]
       [--auto-devices]
       [--gpu-memory GPU_MEMORY [GPU_MEMORY ...]]
       [--cpu-memory CPU_MEMORY]
       [--disk]
       [--disk-cache-dir DISK_CACHE_DIR]
       [--load-in-8bit]
       [--bf16]
       [--no-cache]
       [--xformers]
       [--sdp-attention]
       [--trust-remote-code]
       [--threads THREADS]
       [--n_batch N_BATCH]
       [--no-mmap]
       [--mlock]
       [--wbits WBITS]
       [--model_type MODEL_TYPE]
       [--groupsize GROUPSIZE]
       [--pre_layer PRE_LAYER]
       [--checkpoint CHECKPOINT]
       [--monkey-patch]
       [--quant_attn]
       [--warmup_autotune]
       [--fused_mlp]
       [--flexgen]
       [--percent PERCENT [PERCENT ...]]
       [--compress-weight]
       [--pin-weight [PIN_WEIGHT]]
       [--deepspeed]
       [--nvme-offload-dir NVME_OFFLOAD_DIR]
       [--local_rank LOCAL_RANK]
       [--rwkv-strategy RWKV_STRATEGY]
       [--rwkv-cuda-on]
       [--listen]
       [--listen-host LISTEN_HOST]
       [--listen-port LISTEN_PORT]
       [--share]
       [--auto-launch]
       [--gradio-auth-path GRADIO_AUTH_PATH]
       [--api]
       [--public-api]
       [--multimodal-pipeline MULTIMODAL_PIPELINE]
server.py: error: unrecognized arguments: --cai-chat

The cell stops running. 
I can remove the -cai chat flag with the checkbox but I dont get a URL to the Gradio interface. 

SOLUTION: change it to "--chat" in your arguments..

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Starting a new colab..

### Logs

```shell
/content/text-generation-webui
python server.py --share --model anon8231489123_vicuna-13b-GPTQ-4bit-128g --settings settings-colab.json --extensions silero_tts gallery --no-stream --wbits 4 --cai-chat --groupsize 128
INFO:NumExpr defaulting to 2 threads.
INFO:Gradio HTTP request redirected to localhost :)
usage: server.py
       [-h]
       [--notebook]
       [--chat]
       [--character CHARACTER]
       [--model MODEL]
       [--lora LORA [LORA ...]]
       [--model-dir MODEL_DIR]
       [--lora-dir LORA_DIR]
       [--model-menu]
       [--no-stream]
       [--settings SETTINGS]
       [--extensions EXTENSIONS [EXTENSIONS ...]]
       [--verbose]
       [--cpu]
       [--auto-devices]
       [--gpu-memory GPU_MEMORY [GPU_MEMORY ...]]
       [--cpu-memory CPU_MEMORY]
       [--disk]
       [--disk-cache-dir DISK_CACHE_DIR]
       [--load-in-8bit]
       [--bf16]
       [--no-cache]
       [--xformers]
       [--sdp-attention]
       [--trust-remote-code]
       [--threads THREADS]
       [--n_batch N_BATCH]
       [--no-mmap]
       [--mlock]
       [--wbits WBITS]
       [--model_type MODEL_TYPE]
       [--groupsize GROUPSIZE]
       [--pre_layer PRE_LAYER]
       [--checkpoint CHECKPOINT]
       [--monkey-patch]
       [--quant_attn]
       [--warmup_autotune]
       [--fused_mlp]
       [--flexgen]
       [--percent PERCENT [PERCENT ...]]
       [--compress-weight]
       [--pin-weight [PIN_WEIGHT]]
       [--deepspeed]
       [--nvme-offload-dir NVME_OFFLOAD_DIR]
       [--local_rank LOCAL_RANK]
       [--rwkv-strategy RWKV_STRATEGY]
       [--rwkv-cuda-on]
       [--listen]
       [--listen-host LISTEN_HOST]
       [--listen-port LISTEN_PORT]
       [--share]
       [--auto-launch]
       [--gradio-auth-path GRADIO_AUTH_PATH]
       [--api]
       [--public-api]
       [--multimodal-pipeline MULTIMODAL_PIPELINE]
server.py: error: unrecognized arguments: --cai-chat
```

### System Info

```shell
win 11 , unknown work pc specs. Im running google colab anyway.
```

**Comment by oobabooga** [comment]
--cai-chat is deprecated, change it to --chat instead
