### ISSUE TITLE
Save the model setting got an error: KeyError - 'TheBloke_wizard-vicuna-13B-GPTQ$'.

### ISSUE THREAD

**Issue by mzbac** [oobabooga/text-generation-webui#2023]
### Describe the bug

I have recently updated to the latest main branch. After installing all required dependencies, the UI launches as expected. However, when I try to open an existing model on my local and save the settings, I get a KeyError - 'TheBloke_wizard-vicuna-13B-GPTQ$'.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Pull the latest main from old commit
- Launch UI
- Open existing model
- Make some changes and save the settings.
- Error showing up on console

### Logs

```shell
text-generation-webui/server.py", line 272, in save_model_settings
    user_config[model_regex][k] = state[k]
```

### System Info

```shell
ubuntu 22.4
```

**Comment by mzbac** [comment]
I suspect the bug was introduced by this [commit](https://github.com/oobabooga/text-generation-webui/commit/a77965e801d2966f73b68e98a4b4b8986df21d74) and I don't know how to use the object key for regex matching.

**Comment by oobabooga** [comment]
Fixed here https://github.com/oobabooga/text-generation-webui/commit/437d1c7eada48aae798918dc11083732e92daba2
