### ISSUE TITLE
Are websockets required? Looking into serverless hosting. (modal.com)

### ISSUE THREAD

**Issue by curtisshipley** [oobabooga/text-generation-webui#2026]
**Description**

I'm exploring the feasibility of using the text-generation-webui application in an environment where websockets and long-polling are not supported. My main concern is that the hosting platform I'm considering, modal.com, doesn't accommodate long-running connections. (The platform functions based on web requests to allow a per-second billing) Despite this limitation, modal.com is attractive because it allows inexpensive access to T4's and A100's.

The gradio documentation suggests that websockets are not mandatory and that POST requests should function properly. However, `app.queue()` turns them on, which is what text-generation-webui does. However, the only place the queue seems to be explicitly used is in the `Iteratorize` class.

Is it possible to use text-generation-webui, without calling `app.queue()`?

**Additional Context**

In order to work with modal.com's system I would create a proxy that would contain the attributes required by modal.com, then turn around a connect to the local text-generation-webui instance.

I found some resources indicating that Gradio can operate without websockets, or that websockets come into play only when queuing is enabled. Here are the links for reference:

Gradio's guide on setting up a demo for maximum performance:
https://gradio.app/setting-up-a-demo-for-maximum-performance/

The Iteratorize class that references the queue in the text-generation-webui codebase:
https://github.com/oobabooga/text-generation-webui/blob/146a9cb3930f43f1659d02f7cbc3fbd8a5f90227/modules/callbacks.py#LL49C1-L49C19

**Comment by curtisshipley** [comment]
So, this should work out of the box?

**Comment by stan7123** [comment]
Is this possible to disable websockets in favor of standard HTTP requests?

I tried to comment call to `.queue()` but got this error:
```
Traceback (most recent call last):
  File "/home/python_user/text-generation-webui/server.py", line 1021, in <module>
    create_interface()
  File "/home/python_user/text-generation-webui/server.py", line 923, in create_interface
    shared.gradio['interface'].launch(debug=True, enable_queue=False, prevent_thread_lock=True, share=shared.args.share, server_port=shared.args.listen_port, inbrowser=shared.args.auto_launch, auth=auth)
  File "/home/python_user/.pyenv/versions/3.10.9/lib/python3.10/site-packages/gradio/blocks.py", line 1732, in launch
    self.validate_queue_settings()
  File "/home/python_user/.pyenv/versions/3.10.9/lib/python3.10/site-packages/gradio/blocks.py", line 1578, in validate_queue_settings
    raise ValueError(
ValueError: Queue needs to be enabled! You may get this error by either 1) passing a function that uses the yield keyword into an interface without enabling the queue or 2) defining an event that cancels another event without enabling the queue. Both can be solved by calling .queue() before .launch()
```

**Comment by xieyufei1993** [comment]
> Is it possible to disable websockets in favor of standard HTTP requests?
> 
> I tried to comment call to `.queue()` but got this error:
> 
> ```
> Traceback (most recent call last):
>   File "/home/python_user/text-generation-webui/server.py", line 1021, in <module>
>     create_interface()
>   File "/home/python_user/text-generation-webui/server.py", line 923, in create_interface
>     shared.gradio['interface'].launch(debug=True, enable_queue=False, prevent_thread_lock=True, share=shared.args.share, server_port=shared.args.listen_port, inbrowser=shared.args.auto_launch, auth=auth)
>   File "/home/python_user/.pyenv/versions/3.10.9/lib/python3.10/site-packages/gradio/blocks.py", line 1732, in launch
>     self.validate_queue_settings()
>   File "/home/python_user/.pyenv/versions/3.10.9/lib/python3.10/site-packages/gradio/blocks.py", line 1578, in validate_queue_settings
>     raise ValueError(
> ValueError: Queue needs to be enabled! You may get this error by either 1) passing a function that uses the yield keyword into an interface without enabling the queue or 2) defining an event that cancels another event without enabling the queue. Both can be solved by calling .queue() before .launch()
> ```
meet the same error, how to solve?

**Comment by curtisshipley** [comment]
@oobabooga  Instead of just closing the issue as supported, can you respond? 

Is disabling websockets to enabled requests to go over HTTP supported? We're not asking if text-generation-webui can be run as an api server. We're asking if websockets can be turned off for all UI related things. If it is supported, there is not indication of how to do it.

**Comment by thundergolfer** [comment]
modal.com now supports websockets :) https://modal.com/docs/guide/webhooks#websockets
