### ISSUE TITLE
Doesn't working for me at all

### ISSUE THREAD

**Issue by crwpw** [oobabooga/text-generation-webui#2035]
### Describe the bug

This is something like a generator of random errors, starting with a Cuda package not installing, ending with a random curse about the lack of an installed package "einops", if you don't install ALL of the parts of Visual Studio with over 99999GB packages (because I have no Idea which one I have to download) so if you didn't - you have no chance to install this awesome webui for lm :D Really I love Automatic webui, because it's intuitive, and you even have a chance to install it, but this thing... it just IMPOSSIBLE :D you position your product as a autocatic-webui similar, but why are all the dependencies with cuda installed without any problems when I installed automatic-webui and use it very easily, but here we have no chance to install IT at all (also I'm not the python expert used as you can see)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I just following all steps from "Installation" instructions 

### Logs

```shell
from einops import rearrange
ModuleNotFoundError: No module named 'einops'
```

### System Info

```shell
RTX 3050
```

**Comment by crwpw** [comment]
Also If I missed the Cuda install because of VisualStudio BrainSexingPart, I can't install it later without reinstall all of the webui, because there is no any part about it, I already have a python Installed on my pc for sd-webui, so my every attempt to install the package bypassing the python 3.10 environment does not lead to anything, because conda is here, it is installed locally and I have no idea how to use it to install more packages inside this environment

really... looks like I just installed brainExplode package to my pc)

**Comment by Juqowel** [comment]
> I just following all steps from "Installation" instructions

All steps? Have you tried just installing via One-click installer?

**Comment by matatonic** [comment]
I noticed the need for einops to be installed when I tried the mpt-7b models.

**Comment by crwpw** [comment]
> > I just following all steps from "Installation" instructions
> 
> All steps? Have you tried just installing via One-click installer?

Yes indeed,  "1 click installer" generates many troubles if you doesn't install C or C++ compiler, also it would be great if this point will be critical and written in big red block as notice (version and link) because i just freaked out, and install several versions of compiler to just close that dependency, and reinstalled this pack for the seventh time already

also, yes I download a mpt-7b-instruct model, but I have no idea how to install einops by local conda, because call to path python directs "pip install einops" to my other environment doesn't connected with current)

**Comment by crwpw** [comment]
> I noticed the need for einops to be installed when I tried the mpt-7b models.

yes, I detailed all the steps above :(

**Comment by crwpw** [comment]
So... After all I just install c and c++ compiler, and manually copy to env/libs the "einops" folder from my stable diffusion site-packages and it runs

**Comment by Juqowel** [comment]
> also, yes I download a mpt-7b-instruct model, but I have no idea how to install einops by local conda, because call to path python directs "pip install einops" to my other environment doesn't connected with current)

To install additional packages, use `micromamba-cmd.bat`

**Comment by crwpw** [comment]
> > also, yes I download a mpt-7b-instruct model, but I have no idea how to install einops by local conda, because call to path python directs "pip install einops" to my other environment doesn't connected with current)
> 
> To install additional packages, use `micromamba-cmd.bat`

there is no file with that name :|

**Comment by Juqowel** [comment]
> there is no file with that name :|

Yes, I see. Now it's called `cmd_windows.bat.`

**Comment by crwpw** [comment]
> > there is no file with that name :|
> 
> Yes, I see. Now it's called `cmd_windows.bat`

Thanks now all is working!
