### ISSUE TITLE
Model generate unreadable text

### ISSUE THREAD

**Issue by chienhalan5000** [oobabooga/text-generation-webui#2037]
### Describe the bug

I run the **TheBloke/vicuna-7B-GPTQ-4bit-128g** model and it generate me a random text like the screenshot bellow while the **anon8231489123/vicuna-13b-GPTQ-4bit-128g** model is just fine. No ideas how to fix this.

This is the command I run to start the server: python server.py --share --auto-devices --chat --model-menu --wbits 4 --groupsize 128

Thanks!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

None

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/34291365/fe2c63e1-35a2-48d3-8b96-c9d287b7ee21)
![image](https://github.com/oobabooga/text-generation-webui/assets/34291365/83e00994-6c85-41c7-af14-95a79f261d2c)

### Logs

```shell
None
```

### System Info

```shell
Dual RTX 3060. Core i7-12700F.
```

**Comment by Ph0rk0z** [comment]
Maybe you used a triton model in non triton GPTQ

**Comment by vw1693** [comment]
Just read his [Model card](https://huggingface.co/TheBloke/vicuna-7B-GPTQ-4bit-128g). He literally provides a how to run this model.

**Comment by chienhalan5000** [comment]
Ok thank you guys.
My mistakes were install [GPTQ-for-LLaMa](https://github.com/qwopqwop200/GPTQ-for-LLaMa) on CUDA branch and after uninstall and then reinstall GPTQ-for-LLaMa (without `-b cuda`) these models work perfectly.
