### ISSUE TITLE
how to activate the public API on Google Colab for the Obabooga Text Web UI?

### ISSUE THREAD

**Issue by yoshuzx** [oobabooga/text-generation-webui#2050]
Does anyone know how to activate the public API on Google Colab for the Obabooga Text Web UI?

**Comment by profsher** [comment]
does anyone know how to activate the public API on Google Colab??

**Comment by eewann** [comment]
I was able to achieve this by using serveo.net and making a small change to the "extensions/api/script.py" file. The code I added is as follows.
```
import extensions.api.blocking_api as blocking_api
import extensions.api.streaming_api as streaming_api
from modules import shared
import asyncio
import multiprocessing
import os

# Here
def runserv():
    os.system('ssh -o ServerAliveInterval=60 -R 80:127.0.0.1:5000 serveo.net')

def setup():
    blocking_api.start_server(shared.args.api_blocking_port, share=shared.args.public_api)
    streaming_api.start_server(shared.args.api_streaming_port, share=shared.args.public_api)
    # And here
    proc = multiprocessing.Process(target=runserv)
    proc.start()

```

**Comment by m-i-n-g** [comment]
this worked for me @eewann . A couple of things to add:

- Make sure that the 'api' extension is actually used as part of the server.py launch parameters "python server.py  --extensions gallery api"
- Also, you need to configure SSH to ignore host checking, by adding 

!mkdir -p ~/.ssh && echo "Host *" > ~/.ssh/config && echo " StrictHostKeyChecking no" >> ~/.ssh/config
