### ISSUE TITLE
Suggestion to add: --autolaunch

### ISSUE THREAD

**Issue by lucasbr15** [oobabooga/text-generation-webui#209]
--autolaunch _open the webui URL in the system's default browser upon launch (is used on AUTOMATIC1111)_

**Comment by Ph0rk0z** [comment]
Definitely annoying at times when it opens chrome vs librewolf on kobold but no reason to not have an option.

**Comment by lucasbr15** [comment]
I get what you're saying, and I agree that some people might find it annoying to have the automatic opening option. But I still think it would be useful to have it, even if it's optional. As a Windows 10 user myself, it's just as much of a hassle for me to have to go into the cmd, select the link, and paste it into the browser as it is to have it open automatically! So, if you can, please add this feature. Thanks in advance!
