### ISSUE TITLE
这是什么问题？

### ISSUE THREAD

**Issue by wilac-pv** [oobabooga/text-generation-webui#2096]
![image](https://github.com/oobabooga/text-generation-webui/assets/15046956/c7bfa124-6e51-4058-a444-1ea1889933d5)

**Comment by Ph0rk0z** [comment]
Ahh yes.. I am on remote server and in the middle of training. This just happened to me. Need reconnect button badly.

For you it simply means the UI lost connection to server.py and was unable to reconnect within some time or get some error back.

**Comment by Ph0rk0z** [comment]
Training keeps going.
