### ISSUE TITLE
NSFW WD14 tagger support for send_pictures extension.

### ISSUE THREAD

**Issue by OrphBean** [oobabooga/text-generation-webui#2101]
Blip is cool and all, but its pretty basic.

WD14 tagging is way better - more detail, juicier tags. Its used in some Auto1111 taggers and is also an option for Kohya_ss

There's an SD implementation here: https://github.com/toriato/stable-diffusion-webui-wd14-tagger

I've tried to write the extension myself using gpt4 and based on the og send-pictures extension - but i cannot get the script to compile. I reckon there's a coder out there who actually knows how to code

**Comment by oobabooga** [comment]
https://github.com/oobabooga/text-generation-webui/pull/607 implemented something in this direction , but multimodal pipelines are so much better at understanding pictures that I think it's better to just use that instead

https://github.com/oobabooga/text-generation-webui/tree/main/extensions/multimodal
