### ISSUE TITLE
Kindly be more specific regarding MS Visual Studio Components Required

### ISSUE THREAD

**Issue by miles-du** [oobabooga/text-generation-webui#2102]
**Description**
Error during installation leaves me none the wiser. Please see the error below.
A clear and concise description of what you want to be implemented.
It would be great to have more clarity on what MS Visual Studio Components are needed to satisfy the webui installation process. Advising to just install 'Build Tools' is fair enough I guess, but for a lot of us non-programmers, the 12GB download and space required is a bit eye-watering when it is hinted that only a few components are actualy relevent. I saw that someone in a thread trying to help had suggested that you only needed to use the 'vs_BuildTools' Installer rather than 'VisualStudioSetup' - which will require the 12GB and has a baffling array of component options that has nothing like "CUDA Package", etc if you are trying to work out which bits of this bohemeth you can get away with. So I ran the 'vs_BuildTools' Installer and still got the error below, the webui installation continued but I'm unsure if it means I am running a less than optimal deploymenmt. Please advise, and I am so greatful for your work - just want to have it working as well as possible. :)
**Additional Context**

If applicable, please provide any extra information, external links, or screenshots that could be useful.
...
Successfully installed accelerate-0.18.0 datasets-2.10.1 safetensors-0.3.0 transformers-4.28.0
Processing e:\projects\ai_projects\chatai\text-generation-webui\repositories\gptq-for-llama
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: quant-cuda
  Building wheel for quant-cuda (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running bdist_wheel
      running build
      running build_ext
      E:\PROJECTS\AI_Projects\ChatAi\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'quant_cuda' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quant-cuda
  Running setup.py clean for quant-cuda
Failed to build quant-cuda
Installing collected packages: quant-cuda
  Running setup.py install for quant-cuda ... error
  error: subprocess-exited-with-error

  × Running setup.py install for quant-cuda did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      running install
      E:\PROJECTS\AI_Projects\ChatAi\installer_files\env\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      E:\PROJECTS\AI_Projects\ChatAi\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'quant_cuda' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> quant-cuda

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
ERROR: GPTQ CUDA kernel compilation failed.
Attempting installation with wheel.
Collecting quant-cuda==0.0.0
  Downloading https://github.com/jllllll/GPTQ-for-LLaMa-Wheels/raw/main/quant_cuda-0.0.0-cp310-cp310-win_amd64.whl (398 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 398.4/398.4 kB 1.9 MB/s eta 0:00:00
Installing collected packages: quant-cuda
Successfully installed quant-cuda-0.0.0
Wheel installation success!
...

**Comment by oobabooga** [comment]
The installer first tries to build gptq-for-llama manually, and if that fails, it installs a pre-compiled wheel as you can see from

```
Downloading https://github.com/jllllll/GPTQ-for-LLaMa-Wheels/raw/main/quant_cuda-0.0.0-cp310-cp310-win_amd64.whl (398 kB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 398.4/398.4 kB 1.9 MB/s eta 0:00:00
Installing collected packages: quant-cuda
Successfully installed quant-cuda-0.0.0
Wheel installation success!
```

**Comment by miles-du** [comment]
Ah, Excellent. Thanks for the clarification.
