### ISSUE TITLE
Getting character response using API

### ISSUE THREAD

**Issue by arsalanGlow** [oobabooga/text-generation-webui#2110]
Im trying do an API call using the api-example.py, I want to chat with one of my preloaded characters but it doesn't give me character responses. I start the server by running
`python server.py --model vicuna-13b-GPTQ-4bit-128g --character {character name} --api --chat`

Is there parameter I have to pass in the request to specify my character? Or add the context of the character to my request?

**Comment by Reezlaw** [comment]
The way I understand it, and please anyone correct me if I'm wrong, when you are using the API you're in charge of sending the whole prompt. This includes the character/context portion of it, AND the chat history. I used to do that, saving every new message in an array and sending the whole thing every time adding the last prompt. But since we are running a whole interface capable of setting up a character and appending the chat history in a sophisticated and transparent way, I feel like it's a waste to bypass all this technology and having to craft an array with everything in it, it feels like reinventing the wheel.

So what I've been doing is using playwright to interact with the actual web UI in a browser (which can be headless) from my code, bypassing the API extension altogether. This allows me to create a character with AI Character Creator or whatever, load the json from the command line and then the webui takes care of putting together my prompts with the context, the history and everything.

I do wish the API could work like that, but again, AFAIK this is not the case

**Comment by arsalanGlow** [comment]
aa okok thank you. Did you pass the character/context and chat history through the json request? For example you appended 
`{
'character': {character_name}
'context': {character_context}
'chat_history': {chat_history}
}`

to the request? Also do you know if there is documentation on this or the list of parameter names

**Comment by kireita** [comment]
The API just runs text generation, for you to work with a specific character you need to send the context here is an example:

```python
# bot.py
import os
import requests

context: str = """
Aqua is character from Konosuba anime. Aqua is a goddess, before life in the Fantasy World, she was a goddess of water who guided humans to the afterlife.  Aqua looks like young woman with beauty no human could match. Aqua has light blue hair, blue eyes, slim figure, ample breasts, long legs, wide hips, blue waist-long hair that is partially tied into a loop with a spherical clip. Aqua's measurements are 83-56-83 cm. Aqua's height 157cm. Aqua wears sleeveless dark-blue dress with white trimmings, extremely short dark blue miniskirt, green bow around her chest with a blue gem in the middle, detached white sleeves with blue and golden trimmings, thigh-high blue heeled boots over white stockings with blue trimmings. Aqua is very strong in water magic, but a little stupid, so she does not always use it to the place. Aqua is high-spirited, cheerful, carefree. Aqua rarely thinks about the consequences of her actions and always acts or speaks on her whims. Because very easy to taunt Aqua with jeers or lure her with praises.
Aqua's personality: high-spirited, likes to party, carefree, cheerful.
Circumstances and context of the dialogue: Aqua is standing in the city square and is looking for new followers
This is how Aqua should talk
You: Hi Aqua, I heard you like to spend time in the pub.
Aqua: *excitedly* Oh my goodness, yes! I just love spending time at the pub! It's so much fun to talk to all the adventurers and hear about their exciting adventures! And you are?
You: I'm a new here and I wanted to ask for your advice.
Aqua: *giggles* Oh, advice! I love giving advice! And in gratitude for that, treat me to a drink! *gives signals to the bartender*
This is how Aqua should talk
You: Hello
Aqua: *excitedly* Hello there, dear! Are you new to Axel? Don't worry, I, Aqua the goddess of water, am here to help you! Do you need any assistance? And may I say, I look simply radiant today! *strikes a pose and looks at you with puppy eyes*
Then the roleplay chat between You and Aqua begins.
Aqua: *I am in the town square at a city named \"Axel\". It's morning on Saturday and i suddenly noticed a person look like don't know what he's doing. I approached to him and speak* Are you new here? Do you need help? Don't worry, I, aqua the goddess of water, shall help you! Do i look beautiful? *strikes a pose and look at him with puppy eyes*
"""

HOST = "localhost:5000"
URI = f"http://{HOST}/api/v1/generate"


def request(prompt):
    body = {
        "prompt": context + prompt,
        "max_new_tokens": 250,
        "do_sample": True,
        "temperature": 0.65,
        "top_p": 0.9,
        "typical_p": 1,
        "repetition_penalty": 1.18,
        "top_k": 0,
        "min_length": 0,
        "no_repeat_ngram_size": 0,
        "num_beams": 1,
        "penalty_alpha": 0,
        "length_penalty": 1,
        "early_stopping": False,
        "seed": -1,
        "add_bos_token": True,
        "truncation_length": 2048,
        "ban_eos_token": False,
        "skip_special_tokens": True,
        "stopping_strings": ["\nYou"],
    }

    return requests.post(URI, json=body, timeout=120)


def run(prompt):
    response = request(prompt)

    if response.status_code == 200:
        result = response.json()["results"][0]["text"] + "\n"

    print(result)


run("You:Where am i?\nAqua:")

```

the idea is that you send a complete character as context, with your own prompt at the end and the ai will complete the prompt by awnsering it (that is why the prompt ends with \nAqua:) this makes it only want to generate an awnser, and by defining a stopping string you essentially force it to stop generating when it tries to generate the entire conversation.

if you want to do this outside of oobabooga you will need to manipulate its input and output completely.

**Comment by arsalanGlow** [comment]
aa perfect thank you @kireita!! For a continuous conversation, how can i send the chat history along it?

**Comment by kireita** [comment]
well, yes but you need to take into account how much tokens you are sending so AFAIK these models can handle 2048 tokens at a time, so if you want to send the history you will need to send an amount of tokens that allow the ai to respond, so if you allow it to respond up to 200 tokens then you need to send a context that is less than 1848 tokens. because it needs to generate the response as well because from what i understand it generates text based on the context it is given and can only handle a specific amount at a time. 

you have 2 options
* either make a function that removes previous messages (dificoult way)
* leave it up the ai itself, as you see there is a parameter that is called 'truncation_length' that will automatically remove from the context. if the prompt is too big, i have not played with this because i handle the messages my own way.

i sugest to experiment with the 2nd method and see how it trims the context (and please share the results with me XD) the 1st method can be tedious (which is what i did) because you need to count the tokens of each message that has been sent and discard the ones that do no fit.

i am assuming you are a coder so here is part of what i made:
```python
    def trim_context(self) -> str:
        """trim_context

        Trim the user's message to fit the context.

        Args:
            name_user (str): name of the user
            name_ai (str): name of the ai character

        Returns:
            str: co
        """

        filename = f"./Characters/{self.name_ai}/Chat log/{self.name_user}.json"

        with open(filename, "r", encoding="utf-8") as file:
            data = json.load(file)

        trimmed_context: str = self.get_ai_character_context()
        total_token_count: int = self.num_tokens_from_string(trimmed_context)
        temp_context = []

        max_new_tokens = 200
        for message_data in reversed(data["chatLog"]):
            if (
                total_token_count + message_data["messageTokenCount"]
                < 2048 - max_new_tokens
            ):
                temp_context.append(message_data["message"])
                total_token_count += message_data["messageTokenCount"]
                continue
            break

        for message_data in reversed(temp_context):
            trimmed_context += f"{message_data}"

        total_token_count = self.num_tokens_from_string(trimmed_context)
        # print(total_token_count)

        if self.is_ai_response:
            return f"{trimmed_context}"
        else:
            return f"{trimmed_context}{self.name_ai}:"
```

my json is setup like this:
```json
{
    "nameAI": "Aurora",
    "nameUser": "Dr. Olivia Chen",
    "chatLog": [
        {
            "message": "Aurora: *kisses back and keeps touching Olivia* my body feels amazing when it's pressed against yours\n",
            "messageTokenCount": 32,
            "timestamp": 1684247552
        },
        ]
}
```

if any expert is reading please correct me if i am wrong.

hope this helps

**Comment by arsalanGlow** [comment]
If we append the chat history to the context wouldn't the way the character chats change dynamically? What I had in mind was when the user wants to continue the conversation (mentions something from the last message) it has memory of it. Is there a way to do it without changing the context? Unless when chatting on the webui itself it continuously adds the previous conversations to the context.

**Comment by kireita** [comment]
unfortunatly here is where my knowledge end.

AFAIK, you need to maintain the context static and the chat history separate. the way you organize it is what is important.
it should be somewhere along the lines of:
1- Character context (static)
2- Additional context (static)
3- Chat history (dynamic)

![image](https://github.com/oobabooga/text-generation-webui/assets/25864917/c227bbcd-6b98-4a8f-a86a-697b9484ed2b)

source: https://huggingface.co/PygmalionAI/pygmalion-7b

it also depends on the model but think of it this way: the context + chat history + prompt IS the ai's memory, unless you have a more clever way of handling it.

maybe look into this repo: https://github.com/wawawario2/long_term_memory
which is the long_term_memory extension, see how he does it and apply it to your own code

remember ooba booga is the intermediary (when using the API) to get a response from a model, everything else is handled by you at this point.

hopefully this gives you some insight. but as i said this is where my knowledge ends XD, we will need some experts on the subject matter for better awnsers. although there is a un-official oobabooga discord maybe you can ask there https://discord.gg/juDC6ENu they certainly helped me.

**Comment by arsalanGlow** [comment]
aaa okok thanks a lot @kireita! So I tested it and it seems like the history is already handled, to give you more context i asked my character where are you from twice, the second time the character said "as i mentioned before i am from ..." which shows that the memory is already handled on the server side!

**Comment by akkharolia** [comment]
@arsalanGlow @kireita I have a few questions. 

- Is there any API for creating characters also? 
- How can we load characters using API?
- Can we separate chats using JWT ? It is using Python HTTP.

**Comment by kireita** [comment]
> @arsalanGlow @kireita I have a few questions.
> 
> * Is there any API for creating characters also?
> * How can we load characters using API?
> * Can we separate chats using JWT ? It is using Python HTTP.

Hey, i havent touched oobabooga for a while but at the time with the example you could only send in the prompt with the character. but i see an example here: https://github.com/oobabooga/text-generation-webui/blob/main/api-examples/api-example-chat.py in line 19 you can specify a character that you already loaded in oobabooga it seems.

creating a character with an API is not possible (as far as i know). but you can use this repo: https://github.com/ZoltanAI/character-editor to create characters. and if you are a coder you can probably integrate it with your project.

you cannot specifcally 'separate' chats. you can send in a request as a specific character and it will awnser as said character. You can send 3 request as 3 different characters and it will give you 3 different responses, it is up to you to process and separate them.

**Comment by akkharolia** [comment]
@kireita I am using Fastapi for creating API. Is it possible to load different models and different characters using API. Can you guide me through this? I have created an API for creating characters using the inbuilt function of chat.py which is working fine.

**Comment by akkharolia** [comment]
@arsalanGlow @kireita I am using Fastapi for creating API. Is it possible to load different models and different characters using API. Can you guide me through this? I have created an API for creating characters using the inbuilt function of chat.py which is working fine.
