### ISSUE TITLE
Is here embeddings (openAI) or augmented (OpenChatKit) feature to custom train AI chatbot using own data?

### ISSUE THREAD

**Issue by AngelTs** [oobabooga/text-generation-webui#2122]
I am not asking for classical training of the model, which is complex and expensive, but competitor fast and cheap system like embeddings of OpenAI and Extensible retrieval augmented system of OpenChatKit!

**Comment by oobabooga** [comment]
Let's use https://github.com/oobabooga/text-generation-webui/issues/2272
