### ISSUE TITLE
Communicate better with contributors

### ISSUE THREAD

**Issue by MillionthOdin16** [oobabooga/text-generation-webui#2142]
You closed one of the most active PR threads #1668 with discussions from important contributors without any warning and didn't respond to multiple requests to why the PR was closed. Now you just merged your own implementation. Communicate better. These are people who find and resolve bugs and deserve more than being ghosted.

**Comment by MillionthOdin16** [comment]
Really?

**Comment by ereish64** [comment]
I don't like this. If people are going out of their way to contribute to your repository, the least you could do is give them credit for what they contribute.

Maybe I'm missing something, but I really don't see any reason not to...
