### ISSUE TITLE
autolauncher in linux after server.py started

### ISSUE THREAD

**Issue by Recruiter2** [oobabooga/text-generation-webui#2166]
**Description**

add option to auto launch in browser after server.py started 

**Additional Context**

here how it can be done 
`import webbrowser`
`    # Launch the browser    
    webbrowser.open('http://127.0.0.1:7860/?__theme=dark')  `

![Capture d’écran du 2023-05-18 11-24-54](https://github.com/oobabooga/text-generation-webui/assets/39489591/3671bacf-92e7-4ea7-b8dc-bca3301d49df)

![Capture d’écran du 2023-05-18 11-24-33](https://github.com/oobabooga/text-generation-webui/assets/39489591/71d346dd-eba6-46e1-83f6-e5a6a9b6e6ee)

there might be more steps to add this option in the web ui such as adding a check option

**Comment by Yeecy-sketch** [comment]
Doesn't adding `--auto-launch` to the `server.py` parameters when launching do this already?

**Comment by ewebgh33** [comment]
Where do you add --auto-launch? What line in server.py I can't find a place to add this.
Google searched and searched issues here for this and there's basically no results.
Why would it not auto launch in browser by default?
I did a brand new install yesterday so obvious in Oct 2024 people still think NOT launching in browser on start, is a good idea?
