### ISSUE TITLE
Does it upload any data ?

### ISSUE THREAD

**Issue by suoko** [oobabooga/text-generation-webui#2167]
I asked the AI if it's connected to the internet and it replied it is.
Are my questions being uploaded somewhere ?
Is it an isolated AI or a connected AI ?
I'm using vicuna.

**Comment by Ph0rk0z** [comment]
Don't ever believe anything an LLM says without double checking it somewhere else.

**Comment by BetaDoggo** [comment]
Everything is offline unless you are using an extension that sends the output somewhere(Elevenlabs-tts for example). The webui itself also disabled all telemetry in gradio.

**Comment by oobabooga** [comment]
Your questions are 100% offline.
