### ISSUE TITLE
Model does not reply ( Is typing.. ) / MetaIX/GPT4-X-Alpaca-30B-4bit

### ISSUE THREAD

**Issue by ilnurshams** [oobabooga/text-generation-webui#2204]
### Describe the bug

Coul you please advise how can I fix the issue when a model does not reply to my message?
So there is an endless typing ( see pictures ). I've reduced token sizes to min.
Running on RTX4090 | 64GB RAM

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

![2023-05-20 030013](https://github.com/oobabooga/text-generation
![2023-05-20 025859](https://github.com/oobabooga/text-generation-webui/assets/132715928/d2cadc11-c486-4ff7-aacf-0bfef44274fa)
-webui/assets/132715928/2bcca845-6a5e-4c83-99c3-6e67d973ca8c)
![2023-05-20 030140](https://github.com/oobabooga/text-generation-webui/assets/132715928/932b5011-4b1d-4cfc-86f8-a9480285a15b)
![2023-05-20 030153](https://github.com/oobabooga/text-generation-webui/assets/132715928/72bdb01a-fc0b-4067-8d05-9546e24e50e0)

### Logs

```shell
bin C:\Users\Admin\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
INFO:Loading MetaIX_GPT4-X-Alpaca-30B-4bit...
WARNING:More than one .safetensors model has been found. The last one will be selected. It could be wrong.
INFO:Found the following quantized model: models\MetaIX_GPT4-X-Alpaca-30B-4bit\gpt4-x-alpaca-30b-4bit.safetensors
INFO:Loaded the model in 6.36 seconds.

INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
INFO:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\oobabooga_windows\text-generation-webui\modules\text_generation.py", line 306, in generate_reply_custom
    for reply in shared.model.generate_with_streaming(context=question, **generate_params):
  File "C:\Users\Admin\Desktop\oobabooga_windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LlamaForCausalLM' object has no attribute 'generate_with_streaming'
Output generated in 0.00 seconds (0.00 tokens/s, 0 tokens, context 234, seed 1950818439)
INFO:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
```

### System Info

```shell
Windows 11, RTX 4090, 64GB RAM
```

**Comment by ilnurshams** [comment]
Okay, I fixed it. I don't know what was the reason.

1. Fresh install of oobabooga one-click installers
2. Start start_windows file. Don't dowload any model!
3. I manually downloaded the necessary model files from https://huggingface.co/MetaIX/GPT4-X-Alpaca-30B-4bit/tree/main
( see picture in attachment ) and put in oobabooga models folder. 
4. I've installed pytorch and cuda via Conda ( download and install Conda first, then run Anaconda Prompt ( miniconda3 ) as admin ). There I run these code ( in order to install pytorch and cuda ). You also need to have python 3.10 as I had it already ( download it )!

conda create --name gptq python=3.10 -y
conda activate gptq
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia

( I used this tutorial, but it is for linux. https://github.com/qwopqwop200/GPTQ-for-LLaMa
I used only code from tutorial to install pytorch and cuda )

5. Then I run update_windows file in oobabooga main folder.

Done!

![Screenshot 2023-05-25 181833](https://github.com/oobabooga/text-generation-webui/assets/132715928/158d74b0-fd29-4afb-8e0d-5483d29c5715)

**Comment by Cebtenzzre** [comment]
This will happen if there are any files matching `*ggml*.bin` in the folder the model is in, even if the UI picks a GPTQ safetensors model to use. This seems like a bug to me, shouldn't I be able to git clone a repo and use it without deleting files?
