### ISSUE TITLE
Add stop tokens to API

### ISSUE THREAD

**Issue by moorehousew** [oobabooga/text-generation-webui#221]
Pretty much what it says on the tin- it'd be nice to be able to pass an array of strings to the API which will terminate a completion early if they're detected in the output.

**Comment by DavesDevFails** [comment]
Yes +1 on this for sure.

**Comment by oobabooga** [comment]
I think that this can be done through an extension that creates an additional API endpoint. I will try to do it later.

**Comment by DavesDevFails** [comment]
Thanks... is there any way to set a stop token / sequence at the moment in the webui? I can't seem to see anything.

**Comment by oobabooga** [comment]
This is now implemented in the API extension https://github.com/oobabooga/text-generation-webui/pull/744
