### ISSUE TITLE
Very slow token generation

### ISSUE THREAD

**Issue by Infexis95** [oobabooga/text-generation-webui#2216]
Hi. I'm new to all this, just started learning yesterday, but I've managed to set up oobabooga and I'm running Pygmalion-13b-4bit-128.safetensors on it.

My problem is that my token generation at around 0.7s/token, which feels extremely slow, but other than that it's working great.
I'm using --pre-layer 26 to dedicate about 8 of my 10gb VRAM to it, and it's eating about 12gb RAM as well, out of my 32gb availible, and about 50% of CPU power. 

I feel like I should be able to sped things up since I've got so much more RAM to give, but I don't know how or if it's even possible.

Here's my args:
--share --chat --auto-devices --model pyg13b --character May --api --pre_layer 26 --groupsize 128 --wbits 4 --model_type llama

I'm using the main branch of oobabooga as well. 

Anyone have any idea of how to speed things up a bit?

**Comment by Infexis95** [comment]
Checking my GPU usage, my dedicated GPU memory is set to about 80-90% of max, but when generating tokens my CUDA usage only goes up to max 35%.... That can't be right, can it?

**Comment by Ph0rk0z** [comment]
It's right because the GPU has to wait for the CPU.. all you can do is get a gpu with more memory or run a smaller model. A 13b doesn't fit in 8gb? I thought it did when quantized to int4.

**Comment by Infexis95** [comment]
If I wanted to force the gpu to take everything, just to see what would happen, what command would I use?

**Comment by wolfpixels** [comment]
+1 why is this so slow

**Comment by Infexis95** [comment]
> +1 why is this so slow

I started the server without using auto-device, and setting --cpu-memory to 0. Now it is blazing fast, makes a huge difference. I also set my --gpu-memory to near max of what I had to ensure I wouldnt go oom.

**Comment by Ph0rk0z** [comment]
Yep.. don't need pre-layer or auto devices unless the models don't fit.

**Comment by Infexis95** [comment]
> ok whats your final cmd to run it pls?

Not home to check right now but iirc it's : --wbits 4 --groupsize 128 --cpu-memory 0 --gpu-memory 8500MiB --model_type llama

Of course it'll change a bit depending on the model you use but for performance it's the cpu and memory options which are of interest.
