### ISSUE TITLE
Last message example leaks into conversation

### ISSUE THREAD

**Issue by Xabab** [oobabooga/text-generation-webui#2221]
### Describe the bug

All characters rely on the whatever ui user is using to include `<START>` at the start of conversation history. TGWUI adds `<START>` at the start of example messages (which often leads to double `<START>` token there, as autors include it there themselves) but not at the end (which leads to the last message example to leak into convo)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try to use any character in chat mode with example messages without `<START>` token at the end

### Logs

```shell
Not applicable
```

### System Info

```shell
Not applicable
```

**Comment by oobabooga** [comment]
That seems like a problem with the character card including <START> when it shouldn't
