### ISSUE TITLE
AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear4bit'. Did you mean: 'Linear8bitLt'?

### ISSUE THREAD

**Issue by StingrayA** [oobabooga/text-generation-webui#2227]
### Describe the bug
Using the current one click installer: After choosing a Model from hugging face (tried different ones), installing it and open start_windows batch file again, i get the log.
I don't know how to start the programm from here.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Using the current one click installer: After choosing a Model from hugging face (tried different ones), installing it and open start_windows batch file again, i get the issue above.

### Logs

```shell

bin G:\text_generation\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
Traceback (most recent call last):
  File "G:\text_generation\oobabooga_windows\text-generation-webui\server.py", line 47, in <module>
    from modules import chat, shared, training, ui, utils
  File "G:\text_generation\oobabooga_windows\text-generation-webui\modules\training.py", line 14, in <module>
    from peft import (LoraConfig, get_peft_model, prepare_model_for_int8_training,
  File "G:\text_generation\oobabooga_windows\installer_files\env\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "G:\text_generation\oobabooga_windows\installer_files\env\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "G:\text_generation\oobabooga_windows\installer_files\env\lib\site-packages\peft\peft_model.py", line 31, in <module>
    from .tuners import (
  File "G:\text_generation\oobabooga_windows\installer_files\env\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "G:\text_generation\oobabooga_windows\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 735, in <module>
    class Linear4bit(bnb.nn.Linear4bit, LoraLayer):
AttributeError: module 'bitsandbytes.nn' has no attribute 'Linear4bit'. Did you mean: 'Linear8bitLt'?

Done!
Press any key to continue . . .

```

### System Info

```shell
Windows 11
GPU: Nvidia RTX 3060ti
```

**Comment by ikt100** [comment]
Hey, I might have the solution, atleast for me it worked that I went and edited out the part of the lora.py file from the line 735 and till the end.

Instruction: Go to your lora.py file, "G:\text_generation\oobabooga_windows\installer_files\env\lib\site-packages\peft\tuners\lora.py" and go to the line 735 and either comment everything out till the end of the file or delete the whole segment.

**Comment by jasonmcaffee** [comment]
We logged issues one minute apart.
I have an easy one line fix to modify requirements.txt spelled out here:
https://github.com/oobabooga/text-generation-webui/issues/2228

**Comment by FeuerDrachenEinhorn** [comment]
> Hey, I might have the solution, atleast for me it worked that I went and edited out the part of the lora.py file from the line 735 and till the end.
> 
> Instruction: Go to your lora.py file, "G:\text_generation\oobabooga_windows\installer_files\env\lib\site-packages\peft\tuners\lora.py" and go to the line 735 and either comment everything out till the end of the file or delete the whole segment.

when doing this I get a bunch of other errors

**Comment by numbersmason** [comment]
> 

Idk about you, but I comment each and one of the remaining lines with "#" and it seems to work

**Comment by StingrayA** [comment]
> We logged issues one minute apart. I have an easy one line fix to modify requirements.txt spelled out here: #2228

where do I add the one line to? i pasted it in requirement.txt and it didn't work

**Comment by VoodooDog** [comment]
Have the same problem... :(
Does deleting the thing section work or not?

**Comment by oobabooga** [comment]
See https://github.com/oobabooga/text-generation-webui/issues/2228#issuecomment-1556002597

**Comment by VoodooDog** [comment]
> Hey, I might have the solution, atleast for me it worked that I went and edited out the part of the lora.py file from the line 735 and till the end.
> 
> Instruction: Go to your lora.py file, "G:\text_generation\oobabooga_windows\installer_files\env\lib\site-packages\peft\tuners\lora.py" and go to the line 735 and either comment everything out till the end of the file or delete the whole segment.

na, this works perfect!

**Comment by SpacePea** [comment]
> Hey, I might have the solution, atleast for me it worked that I went and edited out the part of the lora.py file from the line 735 and till the end.
> 
> Instruction: Go to your lora.py file, "G:\text_generation\oobabooga_windows\installer_files\env\lib\site-packages\peft\tuners\lora.py" and go to the line 735 and either comment everything out till the end of the file or delete the whole segment.

Uhm, after thats done, what do I do now? Where do I get the local http link? tried running cmd and start .bat files in the oogabooga folder, nothing happened

**Comment by ihongxx** [comment]
$ sudo apt install gcc-10 g++-10
$ export CC=/usr/bin/gcc-10
$ export CXX=/usr/bin/g++-10
$ export CUDA_ROOT=/usr/local/cuda
$ ln -s /usr/bin/gcc-10 $CUDA_ROOT/bin/gcc
$ ln -s /usr/bin/g++-10 $CUDA_ROOT/bin/g++
$ git clone https://github.com/timdettmers/bitsandbytes.git
$ cd bitsandbytes
$ CUDA_HOME=/usr/local/cuda-11.6 CUDA_VERSION=116 make cuda11x
$ python setup.py install
I succeeded！
