### ISSUE TITLE
Encountering Issue - LLaMA not loading in 8bit or 4bit precision

### ISSUE THREAD

**Issue by HeroMines** [oobabooga/text-generation-webui#225]
![Screenshot_2023_03_10-4](https://user-images.githubusercontent.com/22183857/224437949-3b486810-3686-447f-b5b0-607b2e35c1a8.png)

Trying to load LLaMA-7B in 4bit prompts this error. I have the proper HF weights and the proper .pt files, as well as CUDA and Visual Studio installed (was able to compile the quant_cuda). Trying to load LLaMA-7B in 8bit results in bitsandbytes hanging and it never loads. Loading LLaMA-7B in KoboldAI works fine.

**Comment by oobabooga** [comment]
Try this:

```
pip uninstall transformers
pip install git+https://github.com/zphang/transformers@llama_push
```

**Comment by HeroMines** [comment]
> Try this:
> 
> ```
> pip uninstall transformers
> pip install git+https://github.com/zphang/transformers@llama_push
> ```

Yeah, I had realized that might be a potential solution minutes after making this issue hahaa...Alright yeah that worked.
