### ISSUE TITLE
No more TavernAi/Kobold API link?

### ISSUE THREAD

**Issue by Juldnarr** [oobabooga/text-generation-webui#2254]
### Describe the bug

Oobabooga used to give you a Kobold API link after you launched it, but now it’s no longer there. How do you use Oobabooga with TavernAi now???

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I launch the EXE and in the command window there is no Kobold API link 

### Logs

```shell
N/a
```

### System Info

```shell
Windows 10 with a RTX 3060 Ti (8 gb )
```

**Comment by oobabooga** [comment]
Add --api flag
