### ISSUE TITLE
Old audio messages are autoplayed when page is refreshed

### ISSUE THREAD

**Issue by mkjellberg** [oobabooga/text-generation-webui#2255]
### Describe the bug

When updating anything like sending a new message or changing chat style old voice messages autoplays.
I've started up the program without whisper, silero, elevenlabs and its still happening on old messages.
Reinstalled oobabooga, restarted the computer.
There are no error messages.
Anyone know how to turn it off?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Dont know how to reproduce it

### Logs

```shell
no errors, this is the only thing:

Loading model ...
Done.
INFO:Loaded the model in 3.98 seconds.

INFO:HTTP Request: POST http://127.0.0.1:7861/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7861/api/predict "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7861/reset "HTTP/1.1 200 OK"
INFO:HTTP Request: POST http://127.0.0.1:7861/api/predict "HTTP/1.1 200 OK"
```

### System Info

```shell
win 11, nvidia 4090
```

**Comment by oobabooga** [comment]
See if this fixed it https://github.com/oobabooga/text-generation-webui/commit/a5d5bb93903a03ff9bb4699a91fd8f7e390473a5

**Comment by mkjellberg** [comment]
The most annoying thing seems fixed! It wont autoplay when committing a new chat message anymore. Thanks!

But it autoplays the last message when changing chat-style or change character. Not sure if thats how its supposed to be
