### ISSUE TITLE
Playback of Previous Chat Speeches with Silero_TTS

### ISSUE THREAD

**Issue by bitjockeypro** [oobabooga/text-generation-webui#2256]
### Discussed in https://github.com/oobabooga/text-generation-webui/discussions/2235

<div type='discussions-op-text'>

<sup>Originally posted by **alireza20144** May 20, 2023</sup>
Hey there!
I just wanted to share my excitement about the text-generation-webui. It's been an amazing tool that has helped me dive into the world of AI learning machines.
But here's the thing: I recently (now!) updated the webui and downloaded the snakers4_silero-models_master. Since then, I've been experiencing a little hiccup. Whenever I use the silero_tts feature during a chat, it starts playing all the previous chat speeches while generating the new speech. Has anyone else encountered this? I'd love to hear if you've found a solution or if you have any tips to make it solved.
Alireza</div>

**Comment by bitjockeypro** [comment]
Problem Statement:

Using the silero_tts extension will playback all previously generated chat responses, not just the latest one.

**Comment by oobabooga** [comment]
See if this fixed it https://github.com/oobabooga/text-generation-webui/commit/a5d5bb93903a03ff9bb4699a91fd8f7e390473a5

**Comment by bitjockeypro** [comment]
Didn't fix it, I made a comment on a possible (hackish) fix in the commit.

**Comment by oobabooga** [comment]
The solution is not good because silero is an extension, so its logic should be contained in its script.py and not in the main chat generator function

Can you see if now it works as expected? https://github.com/oobabooga/text-generation-webui/commit/1e5821bd9e90e11ef5d0cba487465410d430fe85

**Comment by bitjockeypro** [comment]
#https://github.com/oobabooga/text-generation-webui/commit/1e5821bd9e90e11ef5d0cba487465410d430fe85 works!

**Comment by oobabooga** [comment]
Yay! Thanks for testing.
