### ISSUE TITLE
Allow extensions to activate regen, and other things

### ISSUE THREAD

**Issue by kossLAN** [oobabooga/text-generation-webui#227]
This really isn't an issue, but I wasn't sure where else to post this, so if this is against issue posting then just feel free to close. However when making an extension you can access elements like generate using gradio events and calling the cai_chatbot_wrapper function, but as far I know there isn't an easy way to do it programmatically outside of using gradio events. If I'm wrong, and there is a way to do so please let me know.  While this really isn't an issue for generate since you can use the API for that, however accessing regenerate among other things would be helpful.

**Comment by oobabooga** [comment]
You can trigger a regenerate event in an extension like this

```python
import modules.chat as chat
import modules.shared as shared

def ui():
    button = gr.Button()
    button.click(chat.regenerate_wrapper, shared.input_params, shared.gradio['display'], show_progress=shared.args.no_stream))
```

This is just a copy paste of the regenerate event. Is that enough or are you thinking of something else?

**Comment by oobabooga** [comment]
I guess you could put code that changes variables inside the `while True` loop at the bottom of `server.py`:

https://github.com/oobabooga/text-generation-webui/blob/026d60bd3424b5426c5ef80632aa6b71fe12d4c5/server.py#L380

What use case do you have in mind?

**Comment by kossLAN** [comment]
Specifically, I'm using the webui as a backend for a discord bot, migrating off koboldai cause your webui creates better results.

**Comment by oobabooga** [comment]
In gradio, API endpoints are created with by passing `api_name='name'` to an event handler, like this for an endpoint called `regenerate`:

```python
button.click(chat.regenerate_wrapper, shared.input_params, shared.gradio['display'], show_progress=shared.args.no_stream), api_name='regenerate')
```


Maybe a variation of this would allow you to get the additional API functionality that you need through an extension?

**Comment by kossLAN** [comment]
Yea, I'll definitely experiment some more, thank you.
