### ISSUE TITLE
crash while loading llama.cpp model

### ISSUE THREAD

**Issue by alexl83** [oobabooga/text-generation-webui#2284]
### Describe the bug

Hi, I compiled and installed llama-cpp-python 0.1.53 - textgen was working with ggml-v3 before i pulled latest changes (I was behind around 1 week)

Now, trying to load Manticore-13B I get a crash

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`conda run -n textgen --live-stream python server.py --chat --listen --settings ~/oobabooga/settings.json --model Manticore-13B --api --n-gpu-layers 40`

### Screenshot

Not Applicable

### Logs

```shell
bin /home/alex/oobabooga/installer_files/conda/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so
INFO:Loading settings from /home/alex/oobabooga/settings.json...
Traceback (most recent call last):
  File "/home/alex/oobabooga/text-generation-webui/server.py", line 1042, in <module>
    update_model_parameters(model_settings, initial=True)  # hijacking the command-line arguments
  File "/home/alex/oobabooga/text-generation-webui/server.py", line 232, in update_model_parameters
    value = int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
ERROR conda.cli.main_run:execute(47): `conda run python server.py --chat --listen --settings /home/alex/oobabooga/settings.json --model Manticore-13B --api --n-gpu-layers 40` failed. (See above for error)
```

### System Info

```shell
Cuda 11.8
RTX4090
Ryzen 7 7700X
```

**Comment by michaelwhitford** [comment]
I am also getting errors trying to load LLaMA models that were working before I pulled the latest master today.
