### ISSUE TITLE
[REQUEST] Implement ChatLLaMA Instruct Model

### ISSUE THREAD

**Issue by Tophness** [oobabooga/text-generation-webui#229]
[ChatLLaMA](https://github.com/nebuly-ai/nebullvm/tree/main/apps/accelerate/chatllama)
If we can get it to support the 4bit models too that would be the holy grail.

**Comment by zoidbb** [comment]
This should already be supported if someone makes a ChatLLaMA model and publishes it.

**Comment by oobabooga** [comment]
This is a nonexisting model, but I encourage you to rent the GPUs, do the training and release it for us.
