### ISSUE TITLE
Error when trying to connecting through API. Using APi Example Chat stream

### ISSUE THREAD

**Issue by Amidazs** [oobabooga/text-generation-webui#2304]
### Describe the bug

When I start up the server everything works just fine, webUI works and the python code is connected.
However as soon as I call on the server through the python code, I get an error (see the attached screenshots)

The webUI still works fine even after the error. Any thoughts on what I am doing wrong?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the server for oobabooga - run the api_example_chat_stream.py

### Screenshot

![ErrormessagePython](https://github.com/oobabooga/text-generation-webui/assets/128653433/a2826ab3-8a1e-4ad8-8bc1-570cb2cba4c4)
![ErrormessageServer](https://github.com/oobabooga/text-generation-webui/assets/128653433/b3313147-df37-429d-aaee-7fe3f463d2f2)

### Logs

```shell
In the CMD:
ERROR:connection handler failed
Traceback (most recent call last):
  File "F:\AIVtuber\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\websockets\legacy\server.py", line 240, in handler
    await self.ws_handler(self)
  File "F:\AIVtuber\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\websockets\legacy\server.py", line 1186, in _ws_handler
    return await cast(
  File "F:\AIVtuber\oobabooga_windows\oobabooga_windows\text-generation-webui\extensions\api\streaming_api.py", line 21, in _handle_connection
    prompt = message['prompt']
KeyError: 'prompt'


In Python:
websockets.exceptions.ConnectionCloserError: received 1011 (unexpected error_; then sent 1011 (unexpected error)
```

### System Info

```shell
Windows
NVIDIA
```

**Comment by milobestcat** [comment]
same issue here, is it solved?

**Comment by aibarito-ua** [comment]
anyone who has this error change "api/v1/stream" to "api/v1/chat-stream"
