### ISSUE TITLE
poor it/s 

### ISSUE THREAD

**Issue by MrFelt** [oobabooga/text-generation-webui#231]
4th install, followed steps to a T.

One click installer, install.bat, llama 13b 4bit, followed this 
![image](https://user-images.githubusercontent.com/116107934/224465414-a33d3e69-2581-4fe7-a891-fde558d8f33c.png)

launch args= --chat --load-in-4bit --listen --listen-port 7861 --no-stream

resulting generation: 
![image](https://user-images.githubusercontent.com/116107934/224465311-935fa529-54f3-40e9-a1c5-91cfe7c0fbbf.png)
![image](https://user-images.githubusercontent.com/116107934/224465390-0177d039-3ee1-4f1a-99c3-902a9a283af3.png)
![image](https://user-images.githubusercontent.com/116107934/224465481-b222af8e-f6d9-413e-9e9a-9e5dadf99a89.png)

HW:
2x E5-2690 V1
80 GB
3060

**Comment by MrFelt** [comment]
I know removed --auto-devices, here is with, 
![image](https://user-images.githubusercontent.com/116107934/224465718-fb9d8f10-a5f2-4733-b60f-1dab8d50c898.png)

**Comment by MrFelt** [comment]
In the mean time, I will try the manual installation method.

**Comment by MrFelt** [comment]
Using manual install w/o the "load 8bit in windows" results in same so far.

**Comment by oobabooga** [comment]
On my RTX 3090, I get 0.4-0.8 it/s for the 4bit version of llama 13b, so your results look normal. Bear in mind that this is a gigantic model. GPT-2 was a huge deal a few years ago and it had 1.5b parameters.

**Comment by MrFelt** [comment]
> 

Ah ok. I
