### ISSUE TITLE
Connecting to OpenAI Model (Not Immitate OpenAI Api)

### ISSUE THREAD

**Issue by chigkim** [oobabooga/text-generation-webui#2349]
Can we have a way to connect to OpenAI model?
There's OpenAI extension but that's to make oobabooga to function as a fake OpenAI api.
This might have already requested, but couldn't find when I searched.
Thanks!

**Comment by ozzeruk** [comment]
I agree, this would be very useful. It would allow far easier comparisons between the OpenAI models via their API and locally hosted models.

**Comment by matatonic** [comment]
Do you mean to have the extensions/openai act as a proxy to real openai?

**Comment by chigkim** [comment]
Yes. Both TavernAI and KoboldAI let you enter your openai api key and let you chat with OpenAI Gpt.

**Comment by chigkim** [comment]
The same reasons why people want to use oobabooga instead of inference.py for local models: Good WebUI, character management, context manipulation, and so on.

**Comment by matatonic** [comment]
I see, so not for the extensions/openai to proxy, but for the webui to support real openai API as a backend. Got it, makes sense.
