### ISSUE TITLE
exllama support

### ISSUE THREAD

**Issue by jmoney7823956789378** [oobabooga/text-generation-webui#2369]
**Description**

exllama support when?

**Additional Context**

https://github.com/turboderp/exllama
exllama is awesomesauce... but nobody has said anything about it yet, so here I am.
thank you sir, redeem please.

**Comment by oobabooga** [comment]
Here you go https://github.com/oobabooga/text-generation-webui/pull/2444

**Comment by johnmoney83748932** [comment]
I saw this posted earlier in the general.
You're so awesome.

**Comment by atisharma** [comment]
Close?
