### ISSUE TITLE
incompatibility with pytorch 2.0.1 and --xformers

### ISSUE THREAD

**Issue by ReDXeoL** [oobabooga/text-generation-webui#2405]
### Describe the bug

when installing the xformers library, it updates pytorch 2.0.1 and some other libraries are also updated, causing it to generate an error:

bin A:\LLMs_LOCAL\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
R:\LLMs_LOCAL\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:34: User Warning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiply, and GPU quantization are not available.
warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found

the temporary solution is not to install pytorch 2.0.1 and  xformers

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

pip install -U xformers

### Screenshot

![241582376-4f8493d1-6835-456f-b922-269cb8274be3](https://github.com/oobabooga/text-generation-webui/assets/127172146/37eeb334-0f5b-407a-bc5e-0551dae0d542)

### Logs

```shell
bin A:\LLMs_LOCAL\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
R:\LLMs_LOCAL\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:34: User Warning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiply, and GPU quantization are not available.
warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
```

### System Info

```shell
rtx 3090 i7 10100 and 32 gb ram
```

**Comment by jlerausquin** [comment]
Same error for me. Any solution?

**Comment by SEVENID** [comment]
https://github.com/oobabooga/text-generation-webui/issues/2397#issuecomment-1574887793
