### ISSUE TITLE
Batch Query and Text File Export (automatic)

### ISSUE THREAD

**Issue by photogbill** [oobabooga/text-generation-webui#2407]
**Description**

I want to be able to provide multiple prompts, perhaps as a .txt file to have it run while I am away and to export the results into a .txt file

Frankly, when you have to pre_layer, it takes a long time to finish a query. Being able to plan a batch of queries will be extremely helpful when writing with AI.

**Comment by BarfingLemurs** [comment]
yeah, sometimes the generation results are great, and the exporting as json makes it hard to copy and paste.

**Comment by oobabooga** [comment]
The best option for that purpose is to use the API

**Comment by photogbill** [comment]
> The best option for that purpose is to use the API

How?  I tried and it didn't seem to have that feature at all.
