### ISSUE TITLE
The installed version of bitsandbytes was compiled without GPU support

### ISSUE THREAD

**Issue by GianlucaMattei** [oobabooga/text-generation-webui#2414]
### Describe the bug

I am trying to run oobabooga. I installed it and it works fine with some models but it crashes with others. I was wondering if it was due the warning message I get when I start it:

```
bin /home/gm/miniconda3/envs/chat/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/gm/miniconda3/envs/chat/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/gm/miniconda3/envs/chat/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32

```

Do someone know how to fix it and if it is a "big" problem I should solve?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
# remove everything
sudo apt-get remove --purge '*nvidia*'
# download and installed last nvidia drivers from settings -> driver manager -> software sources: NVIDIA driver metapackage from nvidia-driver-525 (proprietary, tested)
# install GUI
# from https://github.com/oobabooga/text-generation-webui
conda activate
conda create -n chat python=3.10.9
conda activate chat
pip3 install torch torchvision torchaudio
git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui
pip install -r requirements.txt
pip install -r requirements.txt --upgrade 

# I still need to apply the delta
# copy/pasted the script from the link https://huggingface.co/CarperAI/stable-vicuna-13b-delta/raw/main/apply_delta.py
# then
python3 apply_delta.py --base /media/gm/ext/text-generation-webui/models/CarperAI_stable-vicuna-13b-delta/ --target stable-vicuna-13b --delta CarperAI/stable-vicuna-13b-delta

# To use the GPTQ models I need to Install GPTQ-for-LLaMa and the monkey patch
mkdir repositories
cd repositories
git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa.git -b triton
cd GPTQ-for-LLaMa
pip install ninja
pip install -r requirements.txt
cd
cd text-generation-webui
# download random model
python download-model.py xxx/yyy
# try to start the gui
python server.py
# It returns this warning but it runs
bin /home/gm/miniconda3/envs/chat/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/gm/miniconda3/envs/chat/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/gm/miniconda3/envs/chat/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
```

### Logs

```shell
bin /home/gm/miniconda3/envs/chat/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/gm/miniconda3/envs/chat/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
warn("The installed version of bitsandbytes was compiled without GPU support. "
/home/gm/miniconda3/envs/chat/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so: undefined symbol: cadam32bit_grad_fp32
;
```

### System Info

```shell
System: ubuntu 22.04

GPU: 3060m
```

**Comment by gbajson-area22** [comment]
I have the same problem on Ubuntu 22.10 with Nvidia L4 card:
```
(py3.10.7) skyhook-user@local-llm-us:~/text-generation-webui$ nvidia-smi 
Mon May 29 16:09:31 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA L4           Off  | 00000000:00:03.0 Off |                    0 |
| N/A   47C    P8    17W /  72W |      0MiB / 23034MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by jackwiffs** [comment]
I tried to re-install or update, every time my anti-virus prevents pytorch due to virus.

The file .\installer_files\conda\pkgs\pytorch-2.0.0-py3.10_cuda11.7_cudnn8_0\Lib\site-packages\torch\bin\protoc.exe has been detected as infected with Gen:Suspicious.Cloud.4.UA0@aKNBTHj

**Comment by GianlucaMattei** [comment]
SOLVED:

find your cuda version

`nvcc --version
`
in case install cuda toolkit

`sudo apt install nvidia-cuda-toolkit`

locate the library of bitsandbytes

`locate libbitsandbytes_cuda*`

cd to the folder and create a backup of this file

`mv libbitsandbys_cpu.so backup_libbitsandbys_cpu.so
`
copy the file of your cuda version (nvcc --version)

`cp libbitsandbytes_cuda118.so libbitsandbytes_cpu.so`

**Comment by jllllll** [comment]
> I tried to re-install or update, every time my anti-virus prevents pytorch due to virus.
> 
> The file .\installer_files\conda\pkgs\pytorch-2.0.0-py3.10_cuda11.7_cudnn8_0\Lib\site-packages\torch\bin\protoc.exe has been detected as infected with Gen:Suspicious.Cloud.4.UA0@aKNBTHj Also same with pytorch-2.0.1-py3.10_cuda11.8_cudnn8_0
> 
> -So looking to other torch archives, I attempted to just copy the pytrch from them. An update to several antivirus now see the torch compiler as malware. : torch\bin\protoc.exe is infected with Gen:Suspicious.Cloud.4.TA0@aS8yjogi this file not being allowed causes it not to compile and run in CPU only.
> 
> VirusTotal reports the following antivirus software will see it as malware: BitDefender, eScan, MAX, Emsisoft, GData, Trellix (FireEye).

`Suspicious.Cloud` is essentially just your AV saying that not many people using your AV have used that file before. It's fairly new, and most people aren't running AI software yet, so that isn't surprising to see. The files are safe, your AV is just over-protective.

**Comment by Woisek** [comment]
> SOLVED:
> 
> find your cuda version `nvcc --version `
> 
> in case install cuda toolkit `sudo apt install nvidia-cuda-toolkit`
> 
> locate the library of bitsandbytes `locate libbitsandbytes_cuda*`
> 
> cd to the folder and create a backup of this file `mv libbitsandbys_cpu.so backup_libbitsandbys_cpu.so `
> 
> copy the file of your cuda version (nvcc --version) `cp libbitsandbytes_cuda118.so libbitsandbytes_cpu.so`

How can this be solved on WIndows? 🤔

**Comment by GianlucaMattei** [comment]
I think if you use the WSL you can use the same commands

**Comment by GianlucaMattei** [comment]
> > SOLVED:
> > find your cuda version `nvcc --version `
> > in case install cuda toolkit `sudo apt install nvidia-cuda-toolkit`
> > locate the library of bitsandbytes `locate libbitsandbytes_cuda*`
> > cd to the folder and create a backup of this file `mv libbitsandbys_cpu.so backup_libbitsandbys_cpu.so `
> > copy the file of your cuda version (nvcc --version) `cp libbitsandbytes_cuda118.so libbitsandbytes_cpu.so`
> 
> How can this be solved on WIndows? thinking

I think if you use the WSL you can use the same commands

**Comment by jamesljl** [comment]
> 

that's worked! thanks a lot!

**Comment by CREED404** [comment]
I get the same warning even though I am running it on CPU?
