### ISSUE TITLE
CPU version breaks when trying to load any ggml model

### ISSUE THREAD

**Issue by latent-variable** [oobabooga/text-generation-webui#2417]
### Describe the bug

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\AI\\cpu\\installer_files\\env\\bin'
I have tried both ggmlv3 and ggmlv2 models, on a fresh install with the same results 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install the WebUI using the CPU version and attempt to load any ggml models

### Logs

```shell
Traceback (most recent call last):
  File "C:\AI\cpu\text-generation-webui\server.py", line 1088, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\AI\cpu\text-generation-webui\modules\models.py", line 95, in load_model
    output = load_func(model_name)
  File "C:\AI\cpu\text-generation-webui\modules\models.py", line 263, in llamacpp_loader
    from modules.llamacpp_model import LlamaCppModel
  File "C:\AI\cpu\text-generation-webui\modules\llamacpp_model.py", line 11, in <module>
    from llama_cpp import Llama, LlamaCache
  File "C:\AI\cpu\installer_files\env\lib\site-packages\llama_cpp\__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "C:\AI\cpu\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py", line 73, in <module>
    _lib = _load_shared_library(_lib_base_name)
  File "C:\AI\cpu\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py", line 52, in _load_shared_library
    os.add_dll_directory(os.path.join(os.environ["CUDA_PATH"], "bin"))
  File "C:\AI\cpu\installer_files\env\lib\os.py", line 1118, in add_dll_directory
    cookie = nt._add_dll_directory(path)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\AI\\cpu\\installer_files\\env\\bin'
```
```


### System Info

```shell
Running on a windows desktop.
```

**Comment by latent-variable** [comment]
Error is with llama_cpp.py 
My computer has CUDA so it is detecting the path, but failing to properly pull the CUDA_PATH from

'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'

instead from
'C:\\AI\\cpu\\installer_files\\env\\bin'

` try:
      os.add_dll_directory(os.path.join(os.environ["CUDA_PATH"], "bin"))
      os.add_dll_directory(os.path.join(os.environ["CUDA_PATH"], "lib"))
  except:
      print('Failed: ', os.path.join(os.environ["CUDA_PATH"], "bin"))`

**Comment by latent-variable** [comment]
I was mistaken the issue is not with llama_cpp.py it is with  
**start_windows.bat**
```
set "CUDA_PATH=%INSTALL_ENV_DIR%"
set "CUDA_HOME=%CUDA_PATH%"
```

Those lines are updating the CUDA_PATH which CUDA was never installed in the CPU version, thus when llama_cpp.py is searching for the bin file it is not there. Removing those lines fixes the issue. In the general case, those paths should only be updated if the NVIDIA option was used. or if CUDA was actually installed in the installer_files

**Comment by jllllll** [comment]
> I was mistaken the issue is not with llama_cpp.py it is with **start_windows.bat**
> 
> ```
> set "CUDA_PATH=%INSTALL_ENV_DIR%"
> set "CUDA_HOME=%CUDA_PATH%"
> ```
> 
> Those lines are updating the CUDA_PATH which CUDA was never installed in the CPU version, thus when llama_cpp.py is searching for the bin folder that is not there. Removing those lines fixes the issue. In the general case, those paths should only be updated if the NVIDIA option was used. or if CUDA was actually installed in the installer_files

I have updated my pull request to create the `bin` folder as a workaround to this issue: https://github.com/oobabooga/one-click-installers/pull/75

The `CUDA_PATH` variable is not intended to be an indication of a valid CUDA Toolkit installation. Consider this scenario:
I have installed the CUDA Toolkit, which sets that variable, and used it to compile some code. Then, I delete the Toolkit as I no longer need it and it is taking up disk space.

In that scenario, the `CUDA_PATH` variable is set to a non-existent path and will cause llama-cpp-python to fail despite the Toolkit not being a required dependency.

**Comment by AmineDjeghri** [comment]
@mykeehu , I think all models work, you just need to not put the name '5_bits' or 'GPTQ' in the name of the directory inside the models folder

**Comment by Pwoerlevel** [comment]
pleas i have your error how can I fix this 
and where models to me download  to fix it 
and thanx you

**Comment by AmineDjeghri** [comment]
@Pwoerlevel 

if you get an error of a missing bin folder, you need to create the bin folder in the location where it's missing.

Also, I think the problem was solved since the pull request was merged. So try to use the latest version.
