### ISSUE TITLE
Move AutoGPTQ from models/ to repositories/

### ISSUE THREAD

**Issue by tensiondriven** [oobabooga/text-generation-webui#2419]
**Description**

The latest changes to the GPTQ documentation describe how to build AutoGPTQ, and suggest placing the resulting build files in the models directory. Previously, addon projects like this lived in the repositories directory.  Ideally, the AutoGPTQ library would live under repositories instead of models, if my understanding is correct.

**Additional Context**

In my case, I have a models directory that is shared across a network, and is managed separately from text-generation-webui.  I would like to keep text-generation-webui dependencies out of this models directory.  It would also be nice to maintain consistency with the repositories pattern used previously.

**Comment by oobabooga** [comment]
I think that I wasn't clear enough in my wording, sorry about that. What I meant is that AutoGPTQ (the library) needs to be installed before loading the model. 

This time it doesn't have to be cloned inside the `repositories` folder. It needs to be installed from source like transformers or peft. You can delete the AutoGPTQ folder afterwards.

https://github.com/oobabooga/text-generation-webui/commit/540a161a08b3f3fa1408a985d0abf0b6706e9323
