### ISSUE TITLE
Loading of big models ends in "Done!" *quit*

### ISSUE THREAD

**Issue by BusinessTechie** [oobabooga/text-generation-webui#2442]
### Describe the bug

Loading of big models ends in "Done!" *quit*

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Linux Fedora 38 with gcc-g++ downgraded to version 11.*
Basic setup works but when you select a bigger model like:

- mosaicml_mpt-7b
- orel12_ggml-gpt4all-j-v1.3-groovy

The loading of the model takes a few minutes and then in terminal it ends with "Done!" but quits back to command line.

my settings in the Model Tab of the website GUI:
gpu-memory for device 0: 4000
gpu-memory for device 1: 8000
gpu-memory for device 2: 8000
cpu-memory: 4000
pre-layer: 20
trust-remote-code

### Logs

```shell
INFO: Loading mosaicml_mpt-7b...
(Never ends)


INFO: Loading orel12_ggml-gpt4all-j-v1.3-groovy...
INFO: llama.cpp weights detected: models/orel12_ggml-gpt4all-j-v1.3-groovy/ggml-gpt4all-j-v1.3-groovy.bin

INFO: Cache capacity is 0 bytes
llama.cpp: loading model from models/orel12_ggml-gpt4all-j-v1.3-groovy/ggml-gpt4all-j-v1.3-groovy.bin

Done!
[user@fedora]$ _
```

### System Info

```shell
1x CPU Intel Celeron i3-7100 (12GB DDR4 RAM)
3x GPU Nvidia GeForce GTX 1070 (8GB)
```

**Comment by XeonG** [comment]
check https://github.com/oobabooga/text-generation-webui/issues/2384#issuecomment-1570617612  might be same issue

**Comment by BusinessTechie** [comment]
Duplicate of #2384
