### ISSUE TITLE
Llama wiki missing tokenizer.model info

### ISSUE THREAD

**Issue by kamyker** [oobabooga/text-generation-webui#246]
In wiki for 4bit there is:
```
python download-model.py --text-only decapoda-research/llama-7b-hf
```
But it doesn't download tokenizer.model making loading broken with weird error.

**Comment by neuhaus** [comment]
tokenizer.model is a file distributed by Meta.

**Comment by kamyker** [comment]
> tokenizer.model is a file distributed by Meta.

No, https://huggingface.co/decapoda-research/llama-7b-hf/tree/main

**Comment by oobabooga** [comment]
It does download tokenizer.model. This is what I get for your command:

```
config.json
generation_config.json
pytorch_model.bin.index.json
special_tokens_map.json
tokenizer_config.json
tokenizer.model
```

Is your local copy of the repository up to date?

**Comment by kamyker** [comment]
True, look like I got fixed
