### ISSUE TITLE
Wrong instruct for Guanaco

### ISSUE THREAD

**Issue by FartyPants** [oobabooga/text-generation-webui#2483]
### Describe the bug

The webui loads arbitrary Guanaco non-chat.yaml when you load any Guanaco.
Suggestion: kill Guanaco non-chat.yaml totally, it is for a weird model that nobody uses, not for the current guanaco

That "old" yaml is wrong.
For the Guanaco we have now (QLORA) , it should be:
```
user: "### Human:"
bot: "### Assistant:"
turn_template: "<|user|> <|user-message|>\n<|bot|> <|bot-message|></s>\n"
context: ""
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

load guanaco

### Logs

```shell
Wrong instruct (I suggest to kill Guanaco non-chat.yaml  totally - it's for a model that nobody uses)
```

### System Info

```shell
windows
```

**Comment by oobabooga** [comment]
@FartyPants can you submit a pull request?

**Comment by FartyPants** [comment]
> @FartyPants can you submit a pull request?
