### ISSUE TITLE
Manual VRAM/RAM layer adjustment 

### ISSUE THREAD

**Issue by Slug-Cat** [oobabooga/text-generation-webui#25]
Currently when I try to load a large model with the intention of using auto devices to split it across VRAM and system RAM, the model may load in successfully but crash as soon as I actually try to generate something due to not enough VRAM. It would be good if either the manual distribution of the model across VRAM/RAM was easier/more accessible like in KoboldAI or if the automatic splitting was just more accurate.

**Comment by Silver267** [comment]
you can manually adjust --gpu-memory parameter to lower values.

**Comment by oobabooga** [comment]
See here

https://github.com/oobabooga/text-generation-webui/wiki/Low-VRAM-guide
