### ISSUE TITLE
[extensions/openai] Improve error handling with no model loaded

### ISSUE THREAD

**Issue by LoopControl** [oobabooga/text-generation-webui#2505]
### Describe the bug

I was using a few days old version of webui (githash `6627f7f`) and openAI extension worked great.

After updating to latest ([19f7868](https://github.com/oobabooga/text-generation-webui/commit/19f78684e6d32d43cd5ce3ae82d6f2216421b9ae)), openAI extension throws an error on the `/completions` endpoint.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

* enable openai extension
* run the completions api (via any openai supporting tool)

### Logs

```python
127.0.0.1 - - [03/Jun/2023 08:52:27] "POST /v1/chat/completions HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 41928)
Traceback (most recent call last):
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/home/user/apps/anaconda3/envs/textgen/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/mnt/nvbig/ai/text-generation-webui/extensions/openai/script.py", line 355, in do_POST
    system_token_count = len(encode(system_msg)[0])
  File "/mnt/ai/text-generation-webui/modules/text_generation.py", line 44, in encode
    input_ids = shared.tokenizer.encode(str(prompt), return_tensors='pt', add_special_tokens=add_special_tokens)
AttributeError: 'NoneType' object has no attribute 'encode'
----------------------------------------
```

### System Info

```shell
linux
```

**Comment by LoopControl** [comment]
This was a derp on my part.

This error was thrown because I didn't have a model loaded. It would be nice to catch this error and output a clean error message to console or via the return on the completions api though (http 500 maybe?).

**Comment by matatonic** [comment]
Yes, you're right, that's a terrible error message. Error handling improvements planned, you can leave this open but can you change the bug to enhancement and subject "[extensions/openai] Improve error handling with no model loaded"?

Much appreciated, thanks.

**Comment by matatonic** [comment]
So far this looks related to the client not handling chunked encoding with a length, this is a new change and works with the official clients but perhaps there are conditions when it shouldn't be enabled. I'd like to see the fine details about how this looks different from official client requests. Namely, I'd like to see HTTP headers for the calls (if you enable OPENEDAI_DEBUG=1) environment variable and restart the server.py that would immensely helpful if you could share the logs of the requests that fail.

Thanks again for the report!
