### ISSUE TITLE
How to customize the model's input and output?

### ISSUE THREAD

**Issue by treya-lin** [oobabooga/text-generation-webui#2529]
Hello, I have succeeded in getting `server.py` to run in `chat` mode. I am wondering where in the backend I can control the input and the output of the model? I am getting a bit lost among the codes. 

To be more clear, sometimes my model generate contents that I don't want, so I wanna remove them before they return to the web interface. And I also wanna see where the service actually receive the input, make some adjustment before feeding them  into the model.

Any suggestion helps. Thanks!!

**Comment by SEVENID** [comment]
https://github.com/oobabooga/text-generation-webui/blob/main/docs/Extensions.md#how-to-write-an-extension

**Comment by oobabooga** [comment]
That's exactly the functionality offered by the extension framework, as pointed out above.
