### ISSUE TITLE
[Request] Support for OpenAssistant oasst-sft-1-pythia-12b

### ISSUE THREAD

**Issue by Daviljoe193** [oobabooga/text-generation-webui#253]
[The first OpenAssistant model is live](https://huggingface.co/OpenAssistant/oasst-sft-1-pythia-12b), and having a convenient way to run it would be great.

**Comment by oobabooga** [comment]
This is a fine tune of pythia, so it should just work.

```
python download-model.py OpenAssistant/oasst-sft-1-pythia-12b
python server.py --model "oasst-sft-1-pythia-12b"
```

**Comment by uff-valeu** [comment]
When I try to let the correctly formatted prompt complete, it just starts randomly within the sentence:
![image](https://user-images.githubusercontent.com/127551301/224565704-cc99146f-e7b4-484b-baef-4db30d1ed9c5.png)

Tried different settings without success. Also, maybe these prompt patterns should also be implemented in chat mode :)

**Comment by oobabooga** [comment]
I can confirm this issue, but I haven't been able to figure out yet why it is behaving like that.

**Comment by mastoca** [comment]
`python server.py --rwkv-cuda-on --rwkv-strategy "cuda fp16i8" --disk --gpu-memory 18` worked for me.

**Comment by oobabooga** [comment]
> `--rwkv-cuda-on --rwkv-strategy "cuda fp16i8"`

Those flags are for RWKV. OpenAssistant is something else

**Comment by mastoca** [comment]
> > `--rwkv-cuda-on --rwkv-strategy "cuda fp16i8"`
> 
> Those flags are for RWKV. OpenAssistant is something else

ah, I see the error now. 

Thanks for clarifying the flags for me, they didn't seem to make a difference here...which makes sense from the screenshot. smh.

**Comment by mastoca** [comment]
@oobabooga I added a `print(reply)` in decode(output_ids) inside the `modules/text_generation.py` file and this was the output showing this....
```Write a story about future of AI development
In
Write a story about future of AI development
In the
Write a story about future of AI development
In the year
Write a story about future of AI development
In the year 20
Write a story about future of AI development
In the year 20XX
Write a story about future of AI development
In the year 20XX,
Write a story about future of AI development
In the year 20XX, the
Write a story about future of AI development
In the year 20XX, the world
Write a story about future of AI development
In the year 20XX, the world is
Write a story about future of AI development
In the year 20XX, the world is on
Write a story about future of AI development
In the year 20XX, the world is on the
Write a story about future of AI development
In the year 20XX, the world is on the br
Write a story about future of AI development
In the year 20XX, the world is on the brink
Write a story about future of AI development
In the year 20XX, the world is on the brink of
Write a story about future of AI development
In the year 20XX, the world is on the brink of an
Write a story about future of AI development
In the year 20XX, the world is on the brink of an AI
Write a story about future of AI development
In the year 20XX, the world is on the brink of an AI revolution
Write a story about future of AI development
In the year 20XX, the world is on the brink of an AI revolution.
Write a story about future of AI development
In the year 20XX, the world is on the brink of an AI revolution. With
Write a story about future of AI development
In the year 20XX, the world is on the brink of an AI revolution. With advance
```
will try a few things tomorrow, I'm still learning this code base.

Btw, awesome work on this, I've been enjoying testing different models.

**Comment by oobabooga** [comment]
Good idea @mastoca, that allowed me to solve the problem: https://github.com/oobabooga/text-generation-webui/commit/b9e0712b92ab81eee50740253798d90ed835a43a

The output now:

> <|prompter|>Write a story about future of AI development<|endoftext|><|assistant|>In the year 20XX, the world is in the grip of an AI revolution. With the rise of powerful AI systems such as OpenAssistant and ChatGPT, humanity has never been more connected or informed.
> 
> However, this new era of AI also brings with it new challenges and ethical concerns. As AI systems become increasingly sophisticated, they are able to perform tasks that were once thought impossible - from creating lifelike virtual reality environments to generating personalized news articles.

**Comment by oobabooga** [comment]
I have added an Instruct mode in this commit https://github.com/oobabooga/text-generation-webui/commit/e722c240af56aa733c576f49e663ed7cafef5784

It is a subset of the chat interface, with the template specified in the form of a yaml pseudocharacter https://github.com/oobabooga/text-generation-webui/tree/main/characters/instruction-following

It works with Open Assistant out of the box.
 
![9lnhhnegp3sa1](https://user-images.githubusercontent.com/112222186/230279291-c437c042-ceb3-407a-a327-d53edcde8bff.png)
