### ISSUE TITLE
why FlexGen only works with the OPT model

### ISSUE THREAD

**Issue by Kuri-su** [oobabooga/text-generation-webui#2530]
**Description**

I saw FlexGen repo say  it's a high-throughput generation engine, They never say that FlexGen only works the OPT model. I want to know why.

**Comment by Pb-207** [comment]
FlexGen itself only support OPT models, though it's not mentioned in readme.
And this is implyed in Roadmap.
![摄像 2023_6_5 19_19_55](https://github.com/oobabooga/text-generation-webui/assets/51241613/7f1a4c22-3517-4eb7-a129-1e011503b714)

**Comment by Kuri-su** [comment]
> To solve the problem of lack in VRAM, I suggest using GPTQ, which is fast and low-precision-loss.

i will try it
