### ISSUE TITLE
Make a Python package out of this

### ISSUE THREAD

**Issue by Evan-Zhao** [oobabooga/text-generation-webui#254]
First of all, thank you very much for this good work! 

I'm wondering if we have a refactoring plan to make this repo a Python package (i.e., one that one can install by `pip`). This will help greatly with the reusability of the code.
For the code to work well as a package, I suppose we'll also need to cut back on the usage of global variables in `module.shared`.
Are we planning to do that? If not, am I welcome to create and publish a packaged version out of this (with all due credits)?

Thanks again.

**Comment by oobabooga** [comment]
I am following automatic1111's footsteps. If stable-diffusion-webui is not a python package, I guess it will not be possible to turn this into a Python package.

The dependency on CUDA also makes installation nontrivial. I think that it's not doable.
