### ISSUE TITLE
ModuleNotFoundError with pygmalion-13b-4bit-128g in text-generation-webui on Mac M1

### ISSUE THREAD

**Issue by yachty66** [oobabooga/text-generation-webui#2582]
### Describe the bug

The text-generation-webui application is experiencing an issue when selecting the notstoic/pygmalion-13b-4bit-128g model. It throws a ModuleNotFoundError: No module named ‘auto_gptq’ within the GUI. Notably, the application works fine when loading other models.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Install the text-generation-webui via the one-click installer for Mac.
2. Download the model notstoic/pygmalion-13b-4bit-128g with the command "python download-model.py notstoic/pygmalion-13b-4bit-128g".
3. Open the GUI of the text-generation-webui.
4. Attempt to select the downloaded model from the drop-down.
5. Observe the error that appears.

### Logs

```shell
Traceback (most recent call last): 
File “/Users/maxhager/Downloads/oobabooga_macos/text-generation-webui/server.py”, line 69, in load_model_wrapper 
shared.model, shared.tokenizer = load_model(shared.model_name) 
File “/Users/maxhager/Downloads/oobabooga_macos/text-generation-webui/modules/models.py”, line 94, in load_model 
output = load_func(model_name) 
File “/Users/maxhager/Downloads/oobabooga_macos/text-generation-webui/modules/models.py”, line 294, in AutoGPTQ_loader 
import modules.AutoGPTQ_loader 
File “/Users/maxhager/Downloads/oobabooga_macos/text-generation-webui/modules/AutoGPTQ_loader.py”, line 3, in 
from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig 
ModuleNotFoundError: No module named ‘auto_gptq’
```

### System Info

```shell
Operating System: macOS M1
No GPU used as I am running on a Mac.
```

**Comment by Ph0rk0z** [comment]
You need to load ggml models and use llama cpp.

**Comment by yachty66** [comment]
@Ph0rk0z do i need to do this for every os for pygmalion-13b-4bit-128g?

**Comment by Ph0rk0z** [comment]
GPTQ models only run on GPU systems. You have to convert them to GGML if you don't have a GPU with enough memory.

**Comment by yachty66** [comment]
done
