### ISSUE TITLE
Loading models is extremely slow on WSL comapred to Windows

### ISSUE THREAD

**Issue by AmineDjeghri** [oobabooga/text-generation-webui#2607]
### Describe the bug

I tried both loading models with
- cloning the repo on WSL 
-  running the installer on Windows 

For the same model named Samantha 7B ggml : 

with windows installer using start-windows.bat : 
`INFO:Loaded the model in 0.26 seconds.`

with WSL + building the repo using server.py: 
`INFO:Loaded the model in 113.06 seconds.`

However, number of generated tokens per second is the same for both:  (7t/s)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

For the same model named Samantha 7B ggml or any other model: 

with windows installer using start_windows.bat : 
- download the installer and run it
- download a model for example : Samantha 7B ggml q4_0
- run start-windows.bat
- load the model 
it should load fast : `INFO:Loaded the model in 7.16 seconds.`

with WSL + building the repo using server.py: 
- i followed the exact steps from the readme.py
- i run the model with  : `python server.py --chat`
i need to wait and get this `INFO:Loaded the model in 113.06 seconds.`

### Logs

with windows installer using start_windows.bat : 
first try : `INFO:Loaded the model in 7.16 seconds.`
second try is even faster : 

```shell
INFO:Loading Samantha-7B.ggmlv3.q4_0...
INFO:llama.cpp weights detected: models\Samantha-7B.ggmlv3.q4_0\Samantha-7B.ggmlv3.q4_0.bin

INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models\Samantha-7B.ggmlv3.q4_0\Samantha-7B.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.07 MB
llama_model_load_internal: mem required  = 5407.71 MB (+ 1026.00 MB per state)
.
llama_init_from_file: kv self size  = 1024.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
INFO:Loaded the model in 0.26 seconds.
```

with WSL + building the repo using server.py: 
```
INFO:Loading Samantha-7B.ggmlv3.q4_0...
INFO:llama.cpp weights detected: models/Samantha-7B.ggmlv3.q4_0/Samantha-7B.ggmlv3.q4_0.bin

INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models/Samantha-7B.ggmlv3.q4_0/Samantha-7B.ggmlv3.q4_0.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 4096
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 32
llama_model_load_internal: n_layer    = 32
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: ftype      = 2 (mostly Q4_0)
llama_model_load_internal: n_ff       = 11008
llama_model_load_internal: n_parts    = 1
llama_model_load_internal: model size = 7B
llama_model_load_internal: ggml ctx size =    0.07 MB
llama_model_load_internal: mem required  = 5407.71 MB (+ 1026.00 MB per state)
.
llama_init_from_file: kv self size  = 1024.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
INFO:Loaded the model in 113.06 seconds.
```

### System Info

```shell
CPU : R7 5800X
32GB ram 
GPU : RTX 3070TI (i'm not using GPU acceleration )
```

**Comment by AmineDjeghri** [comment]
I think I found why !
I moved the folder inside WSL (since it was on E partition inside windows) and the now it's very fast (0.07s to load) .

i tried to put it inside different locations outside WSL and it's very very slow.
So the solution, is to always to use the repos inside WSL

**Comment by EliEron** [comment]
Yeah slow filesystem performance outside of WSL is a known issue. There is a technical reason for it (Which you can find detailed [here](https://github.com/microsoft/WSL/issues/4197#issuecomment-604592340) if you are curious) but the TLDR is that reading a file outside of WSL will always be significantly slower due to the way the filesystem is mounted. This is not an Ooba specific issue but an issue for all WSL programs.

**Comment by AmineDjeghri** [comment]
@EliEron  thank you !
I contributed to the readme by mentioning that git clone should be inside WSL and not outside. 
Since it really impacts loading times
