### ISSUE TITLE
Yay, the new UI changes broke extensions on tabs

### ISSUE THREAD

**Issue by FartyPants** [oobabooga/text-generation-webui#2634]
### Describe the bug

Now extensions that use tabs are bellow the UI, the tabs don't appear on the main part of the toolbar
****

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load extension that use tabs, they are now bellow the UI

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/23346289/20eaec91-4f34-46a8-bc32-2641a80e3d59)

### Logs

```shell
none
```

### System Info

```shell
windoze, firefox
```

**Comment by oobabooga** [comment]
Fixed here https://github.com/oobabooga/text-generation-webui/commit/da5d9a28d8f58efa452ae4209e5213fa43d196cd
