### ISSUE TITLE
why cant the ai remember what i just said?

### ISSUE THREAD

**Issue by yesbroc** [oobabooga/text-generation-webui#2663]
### Describe the bug

basically, can't remember anything it's said or what i've said, super irritating.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

n/a

### Screenshot
(the model here is wizard vicuna uncensored)

![image](https://github.com/oobabooga/text-generation-webui/assets/99485225/fa6438a6-519d-4ae6-a901-41521111cb4b)

### Logs

```shell
n/a
```

### System Info

```shell
16gb ram
ryzen 7 4800h mobile
rtx 3050 ti mobile (bummer)
win 11 home
(not the one click installer)
```

**Comment by YakuzaSuske** [comment]
What model are you using? if you are using "TheBloke_Nous-Hermes-13B-GPTQ" That model doesn't work on chat mode. It works on Instruct mode and if you use it on Chat it won't remember much. It's mean to be used as instruct.

**Comment by Spencer10798** [comment]
I had a similar issue, the solution for me was on the Parameters tab. I believe that _max_new_tokens_ needs to be less than _chat_prompt_size_. I unintentionally created this issue for myself when I tried maxing out the _max_new_tokens_ value while having a smaller _chat_prompt_size_. Let me know if this helps.

**Comment by yesbroc** [comment]
> What model are you using? if you are using "TheBloke_Nous-Hermes-13B-GPTQ" That model doesn't work on chat mode. It works on Instruct mode and if you use it on Chat it won't remember much. It's meant to be used as instruct.

wizard vicuna uncensored

**Comment by yesbroc** [comment]
> I had a similar issue, the solution for me was on the Parameters tab. I believe that _max_new_tokens_ needs to be less than _chat_prompt_size_. I unintentionally created this issue for myself when I tried maxing out the _max_new_tokens_ value while having a smaller _chat_prompt_size_. Let me know if this helps.

can i have the settings you use?

**Comment by Spencer10798** [comment]
max_new_tokens = 1600
chat_prompt_size = 3900

I just randomly dragged them to those numbers, I haven't filled the context yet so I don't know if I'll encounter issues later.

**Comment by FartyPants** [comment]
Was vicuna even finetuned with followup questions? I thought it was simple Q/A

**Comment by yesbroc** [comment]
> max_new_tokens = 1600 chat_prompt_size = 3900
> 
> I just randomly dragged them to those numbers, I haven't filled the context yet so I don't know if I'll encounter issues later.

this works great, but im getting cuda out of mem on cublas dk if this caused it. chat_prompt_size seems to be theproble, max tokens can easily stay a 2000 and the model can retain contxt

**Comment by yesbroc** [comment]
come up with an error while on the temporary fix where llama runs out of tokens 
current ctx = 4096
llama model max = 2048
easy to understand, hard for me to fix

**Comment by yesbroc** [comment]
got new settings, it can recall conversational context without that bug (in theory)
truncation size: 2304
n_ctx: 2304

**Comment by yesbroc** [comment]
will close due to inactivity, (gonna repost this as its not fixed)
