### ISSUE TITLE
how to set `share=True` in `launch()

### ISSUE THREAD

**Issue by Regmas2** [oobabooga/text-generation-webui#267]
can pls someone help i dont know how to code or anything but i need just a small help i wanna make the UI/chat accessable on my tablet but i dont know how , where is this `launch()`

and how can i change it

To create a public link, set `share=True` in `launch()`

**Comment by oobabooga** [comment]
Just start the web ui with the `--share` flag.

There is also `--listen` that makes it accessible from your local network (you will need to find your computer's IP address, gradio prints `0.0.0.0` instead of the actual IP).

**Comment by Regmas2** [comment]
it worked an old friend told me  a minute ago but thanks anyway
