### ISSUE TITLE
Add "start_reply_with" to set "Start reply with" field in settings.json

### ISSUE THREAD

**Issue by Trahloc** [oobabooga/text-generation-webui#2692]
I love the new "Start reply with" option that was recently added. I'd really like the ability to have a permanent fill option set in settings.json. for example:

"start_reply_with": "Sure thing!",

Mostly because I occasionally have to hit f5 to reload the interface due to various bugs I get and then I have to retype the starter.  It can be blank, I just threw in the "Sure thing!" since that's the grayed out default. Thanks for considering this.

**Comment by oobabooga** [comment]
It's already there, just copy settings-template.yaml to settings.yaml and edit the value https://github.com/oobabooga/text-generation-webui/blob/main/settings-template.yaml#L25

**Comment by Trahloc** [comment]
Sonova... thanks dude sorry for pestering you.
