### ISSUE TITLE
Gptq model slow to load

### ISSUE THREAD

**Issue by kevkid** [oobabooga/text-generation-webui#2716]
I am able to load a 30b model into my 3090 but it took 800 seconds to load from disk. Inference is fast. I am using the docker version of this repo on a windows host. I have only 32gb of ram.

Are models this slow to load? How long should a 30b model take to load using this repo using gptq? 

Gpu: 3090
Cpu: i7 5th gen
Ram: 32gb

WizardLM-30b-uncensored

**Comment by kelheor** [comment]
12.93 seconds on Samsung 980 Pro, not using docker version, Windows 11

**Comment by oliverban** [comment]
Yeah, same here, about 10-20 sec loading 4bit GPTQ models.

**Comment by askmyteapot** [comment]
> took 800 seconds to load from disk

Are the model weights being stored on a mechanical HDD? If so, thats why. They only read at about 100MB/s.

**Comment by kevkid** [comment]
> > took 800 seconds to load from disk
> 
> Are the model weights being stored on a mechanical HDD? If so, thats why. They only read at about 100MB/s.
> 
> Actually... doing the math it's only loading at about 20MB/s. That to me sounds like its stored on a USB2.0 drive.

Yes, i just install a samsung 980 pro 7000mb/s ran crystal mark got like 3000mb/s (i think its on a pcie 8x rather than 16). Copied a few files getting like 2GB/s copying files from one location to another on the same disk. 

I look at the task manager and when i use gptq for llama the disk speed is something like 50 MB/s.

This is after i freshly installed win 11 on this disk and am running it under wsl2 with gptq compiled with gpu support. Autogptq also has gpu support.

Running cuda 11.7

Running text gen via python server.py --listen

Not really too sure what i can test.

**Comment by kevkid** [comment]
Found the solution. Just move the repo and models to naitive wsl2 disk rather than /mnt

**Comment by Starlento** [comment]
> Found the solution. Just move the repo and models to naitive wsl2 disk rather than /mnt

Do you know why it is the case? I am having the same issue, but when I use gpt4-for-llama it works well. There is no reason that autogptq is sensitive to that...

**Comment by Starlento** [comment]
> > > took 800 seconds to load from disk
> > 
> > 
> > Are the model weights being stored on a mechanical HDD? If so, thats why. They only read at about 100MB/s.
> > Actually... doing the math it's only loading at about 20MB/s. That to me sounds like its stored on a USB2.0 drive.
> 
> Yes, i just install a samsung 980 pro 7000mb/s ran crystal mark got like 3000mb/s (i think its on a pcie 8x rather than 16). Copied a few files getting like 2GB/s copying files from one location to another on the same disk.
> 
> I look at the task manager and when i use gptq for llama the disk speed is something like 50 MB/s.
> 
> This is after i freshly installed win 11 on this disk and am running it under wsl2 with gptq compiled with gpu support. Autogptq also has gpu support.
> 
> Running cuda 11.7
> 
> Running text gen via python server.py --listen
> 
> Not really too sure what i can test.
> 
> Edit: found the problem: wsl2 has poor performance on /mnt
> 
> Source: [microsoft/WSL#4197](https://github.com/microsoft/WSL/issues/4197)
> 
> Solution: move repo and models to the naitive wsl disk (not in /mnt) and you will see the speed difference.

But for me, loading a 13b 4bit takes 120 seconds. But using gptq-for-llama loading the same model takes 36 seconds. I think wsl2 /mnt is not the only reason.
