### ISSUE TITLE
New update broke on callback

### ISSUE THREAD

**Issue by jerryMeng100** [oobabooga/text-generation-webui#2726]
### Describe the bug

In callbacks.py it's giving TypeError: generate_reply_HF.<locals>.generate_with_callback() got multiple values for argument 'callback'

From commit 9f40032

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Pull latest, run any gptq model

### Logs

```shell
TypeError: generate_reply_HF.<locals>.generate_with_callback() got multiple values for argument 'callback'
```

### System Info

```shell
Linux
```

**Comment by sALTaccount** [comment]
I have the same issue

**Comment by oobabooga** [comment]
Thanks, I missed that. It should be fixed now https://github.com/oobabooga/text-generation-webui/commit/7f06d551a31d91053eb220c95e0dcea9c5ec91c5

**Comment by xanthousm** [comment]
Can confirm that models loaded with autoGPTQ, GPTQ-forLLama, and Transformers are working again. Thanks for the quick fix!

**Comment by oobabooga** [comment]
Thanks for the confirmation, @xanthousm
