### ISSUE TITLE
exllama doesn't respect --model-dir option

### ISSUE THREAD

**Issue by tensiondriven** [oobabooga/text-generation-webui#2728]
### Describe the bug

It looks like exllama is not looking for models in the specified models directory.

Additional exllama issues:
- ~The exllama documentation page doesn't say that you have to enable it as a "loader" in the Model tab.  That would be a good detail to add.~
- ~It isn't clear to me yet how I can specify to load exllama by default from the command line (which is necessary when using text-generaiton-webui headless)~

_edit: This is clear after seeing the `--loader` option in the cli options, awesome!  I submitted a PR to update the documentation which should make it clear to others:_

https://github.com/oobabooga/text-generation-webui/pull/2729

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Start TGWUI with a `--model-dir` param, i used:

```
python server.py --listen --listen-port 8000       --model-dir /mnt/ml-metamind/ml/model-repos   --model chronos-33b-GPTQ --model_type llama --chat --api --extensions api long_term_memory
```

On TGWUI at `b27f83c0e9deb1abe2e02a6ad308dd48c57c0f88`,

1) Clone exllama into repositories
2) Install as described
3) Start TGWUI
4) Test it out, it works (using autogptq, it finds the specified model and inference works)
4) Go to "Model" tab
5) Change loader to "Exllama"
* Exception (see below)

### Logs

```shell
Traceback (most recent call last):
  File "/home/j/text-generation-webui/server.py", line 73, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/text-generation-webui/modules/models.py", line 65, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/text-generation-webui/modules/models.py", line 277, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/text-generation-webui/modules/exllama.py", line 35, in from_pretrained
    config = ExLlamaConfig(str(model_config_path))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/j/text-generation-webui/repositories/exllama/model.py", line 34, in __init__
    with open(model_config_path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'models/chronos-33b-GPTQ/config.json'

^CTraceback (most recent call last):
  File "/home/j/text-generation-webui/server.py", line 1026, in <module>
    time.sleep(0.5)
```

**Comment by oobabooga** [comment]
Should be fixed by #2744
