### ISSUE TITLE
Building wheels failing.

### ISSUE THREAD

**Issue by Delor317** [oobabooga/text-generation-webui#2739]
### Describe the bug

My web ui wont load models and when i run the update i get this error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just ran my update windows file.

### Logs

```shell
Building wheels for collected packages: quant-cuda
  Building wheel for quant-cuda (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      No CUDA runtime is found, using CUDA_HOME='E:\Documents\AI_Chat\oobabooga_windows\installer_files\env'
      running bdist_wheel
      E:\Documents\AI_Chat\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_ext
      E:\Documents\AI_Chat\oobabooga_windows\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quant-cuda
  Running setup.py clean for quant-cuda
Failed to build quant-cuda
ERROR: Could not build wheels for quant-cuda, which is required to install pyproject.toml-based projects

Done!
Press any key to continue . . .
```

### System Info

```shell
CPU
	AMD Ryzen 5 2600
	Pinnacle Ridge 12nm Technology
RAM
	32.0GB Dual-Channel DDR4 @ 1064MHz (15-15-15-36)
Motherboard
	ASUSTeK COMPUTER INC. PRIME B450-PLUS (AM4)
Graphics
	V655-H9 (3840x2160@30Hz)
	4095MB NVIDIA GeForce RTX 2070 SUPER (Gigabyte)
```

**Comment by Delor317** [comment]
Also when i load the web ui i get this:

bin E:\Documents\AI_Chat\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
E:\Documents\AI_Chat\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
function 'cadam32bit_grad_fp32' not found
2023-06-17 18:26:02 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by jllllll** [comment]
The error when updating shouldn't be an issue as there haven't been any updates to `quant_cuda`.
The issue with bitsandbytes loading the cpu binary is something else. Far too many things can cause that.
Run `cmd_windows.bat` and enter this command and post the output:
```
python -m torch.utils.collect_env
```

**Comment by Delor317** [comment]
PyTorch version: 2.0.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.11 | packaged by Anaconda, Inc. | (main, May 16 2023, 00:55:32) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: False
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2070 SUPER
Nvidia driver version: 536.23
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3850
DeviceID=CPU0
Family=107
L2CacheSize=3072
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3850
Name=AMD Ryzen 5 2600 Six-Core Processor
ProcessorType=3
Revision=2050

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] torch==2.0.1
[pip3] torchvision==0.15.2
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi

**Comment by jllllll** [comment]
Run cmd_windows.bat and enter this command:
```
python -m pip install torch==2.0.1+cu117 --force-reinstall --no-deps --index-url https://download.pytorch.org/whl/cu117
```
No clue what is causing the CPU version of Pytorch to get installed on some people's systems. It's bizzare. The installer is set to very specifically install the CUDA 11.7 version of Pytorch, yet some people get the CPU-only version instead. I guess we'll just have to abandon Conda and go with just using pip to install Pytorch.

**Comment by Delor317** [comment]
ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'E:\\Documents\\AI_Chat\\oobabooga_windows\\installer_files\\env\\Lib\\site-packages\\~orch\\lib\\asmjit.dll'
Consider using the `--user` option or check the permissions.

**Comment by jllllll** [comment]
> ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'E:\Documents\AI_Chat\oobabooga_windows\installer_files\env\Lib\site-packages\~orch\lib\asmjit.dll' Consider using the `--user` option or check the permissions.

This is typically caused by overly restrictive file permissions on either the drive or one of the parent folders. Try running `cmd_windows.bat` as admin.

**Comment by Delor317** [comment]
it is now working again. thank you for the help and this is my prefered ui.
