### ISSUE TITLE
`stopping_strings` doesn't work in `exllama`

### ISSUE THREAD

**Issue by Yiximail** [oobabooga/text-generation-webui#2746]
### Describe the bug

using model: TheBloke/airoboros-65B-gpt4-1.2-GPTQ

when using `exllama`:
![image](https://github.com/oobabooga/text-generation-webui/assets/15323975/4268ebdb-f7a9-4a2e-962e-f3f6242b6995)

when using `autoGPTQ` by default:
![image](https://github.com/oobabooga/text-generation-webui/assets/15323975/4d98ff28-5e7a-4157-b778-d3a4443738e3)

and `Custom stopping strings` in webui is fine:
![image](https://github.com/oobabooga/text-generation-webui/assets/15323975/18ba9eca-61bd-4986-b19c-16082273af77)
![image](https://github.com/oobabooga/text-generation-webui/assets/15323975/fccd277f-0b4c-46c7-be7d-1dc811626571)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

{"prompt":"User: What are the names of Batman's parents? Describe them in detail.\nBot:","max_new_tokens":250,"do_sample":true,"temperature":1.3,"top_p":0.1,"typical_p":1,"repetition_penalty":1.18,"top_k":40,"min_length":0,"no_repeat_ngram_size":0,"num_beams":1,"penalty_alpha":0,"length_penalty":1,"early_stopping":true,"seed":-1,"add_bos_token":true,"truncation_length":2048,"ban_eos_token":false,"skip_special_tokens":true,"stopping_strings":["Martha", "martha"]}

### Logs

```shell
None
```

### System Info

```shell
ubuntu 22.04
text-generation-webui branche 5b4c0155
```

**Comment by Ph0rk0z** [comment]
Is it also broken for llama.cpp and rwkv? I don't see anything in generate_custom that actually uses stopping strings.

**Comment by Yiximail** [comment]
# **Update:**

**I said it wrong**

this bug can be triggered in default mode either, and it has nothing to do with whether using API or not.

![image](https://github.com/oobabooga/text-generation-webui/assets/15323975/76825dcb-58b3-4e92-a49e-23ebc0efecc3)

and `/api/v1/chat` could Cut Off the sentence
![image](https://github.com/oobabooga/text-generation-webui/assets/15323975/90fb2956-dc9a-4d51-ab9c-d2476146ab1b)

but did't stop generation too
![image](https://github.com/oobabooga/text-generation-webui/assets/15323975/bd4bb6bc-6d11-4317-b4a9-99db826da683)

### Reproduction

{"user_input": "What are the names of Batman's parents? Describe them in detail.","stopping_strings": ["Martha"],"max_new_tokens": 250,"history": {"internal": [], "visible": []},"mode": "instruct","character": "Example","instruction_template": "Vicuna-v1.1","your_name": "You","regenerate": false,"_continue": false,"stop_at_newline": false,"chat_prompt_size": 2048,"chat_generation_attempts": 1,"chat-instruct_command": "Continue the chat dialogue below. Write a single reply for the character \"<|character|>\".\n\n<|prompt|>","preset": "None", "do_sample": true,"temperature": 0.7,"top_p": 0.1,"typical_p": 1,"epsilon_cutoff": 0,"eta_cutoff": 0,"tfs": 1,"top_a": 0,"repetition_penalty": 1.18,"top_k": 40,"min_length": 0,"no_repeat_ngram_size": 0,"num_beams": 1,"penalty_alpha": 0,"length_penalty": 1,"early_stopping": false,"mirostat_mode": 0,"mirostat_tau": 5,"mirostat_eta": 0.1,"seed": -1,"add_bos_token": true,"truncation_length": 2048,"ban_eos_token": false,"skip_special_tokens": true     }

**Comment by oobabooga** [comment]
This is a transformers feature `transformers.StoppingCriteria`. It is not implemented for any of the custom loaders (llama.cpp/exllama/rwkv).

**Comment by CyberTimon** [comment]
I also noticed this. Hope there is a fix soon!

**Comment by Ph0rk0z** [comment]
In silly tavern it tends to keep generating but now I can hit the stop button. I've yet to try the PR to see if it fixes it.

Sometimes it does stop.. probably when the model outputs an eos token.

**Comment by Yiximail** [comment]
@CyberTimon @Ph0rk0z 

can try my branch `stopping_strings` not `main`

https://github.com/Yiximail/text-generation-webui/tree/stopping_strings

It should work, and as many as test is better

**Comment by tensiondriven** [comment]
@Yiximail I tried your branch and *i thought* worked for me on an initial test, but I couldn't reproduce it.  I am testing with `guanaco-65B-GPTQ` via the regular API (not the extension API), e.g:


```
10.1.1.52 - - [23/Jun/2023 18:12:22] "POST /api/v1/generate HTTP/1.1" 200 -
```

The steps I tried:

1) Clone your repo next to the existing one
2) cp -rp ../text-generation-webui/repositories .
3) Start with same configuration as I normally do:

```
python server.py --listen --listen-port 8000  --loader exllama        --gpu-split 16,24       --model 65/guanaco-65B-GPTQ --api
```

Here are my other params, if helpful:

```
perform_inference: %{
  do_sample: true,
  early_stopping: true,
  max_new_tokens: 500,
  prompt: "...",
  repetition_penalty: 1.18,
  seed: 81295,
  stopping_strings: ["\n"],
  temperature: 0.7,
  top_k: 40,
  top_p: 0.1,
  typical_p: 1.0
}
```

I also tried via the web interface, to no avail.  I tried a few combinations of `early_stopping:` and `stopping_strings`.

Did you implement this for the Kobold (extension) API only?

**Comment by Yiximail** [comment]
> @Yiximail I tried your branch and _i thought_ worked for me on an initial test, but I couldn't reproduce it. I am testing with `guanaco-65B-GPTQ` via the regular API (not the extension API), e.g:
> 
> ```
> 10.1.1.52 - - [23/Jun/2023 18:12:22] "POST /api/v1/generate HTTP/1.1" 200 -
> ```
> 
> The steps I tried:
> 
> 1. Clone your repo next to the existing one
> 2. cp -rp ../text-generation-webui/repositories .
> 3. Start with same configuration as I normally do:
> 
> ```
> python server.py --listen --listen-port 8000  --loader exllama        --gpu-split 16,24       --model 65/guanaco-65B-GPTQ --api
> ```
> 
> Here are my other params, if helpful:
> 
> ```
> perform_inference: %{
>   do_sample: true,
>   early_stopping: true,
>   max_new_tokens: 500,
>   prompt: "...",
>   repetition_penalty: 1.18,
>   seed: 81295,
>   stopping_strings: ["\n"],
>   temperature: 0.7,
>   top_k: 40,
>   top_p: 0.1,
>   typical_p: 1.0
> }
> ```
> 
> I also tried via the web interface, to no avail. I tried a few combinations of `early_stopping:` and `stopping_strings`.
> 
> Did you implement this for the Kobold (extension) API only?

Uh, actually, I haven't used the Kobold extension.

`python server.py --xformers --api --listen --loader exllama --model-menu`

![image](https://github.com/oobabooga/text-generation-webui/assets/15323975/5947a269-7a3c-4b92-b006-ef9e084819ac)

it should work, I tried it in postman

note that you need to use the `stopping_strings` branch, not `stopping-strings-for-HF`

**Comment by tensiondriven** [comment]
@Yiximail I was able to get it working after all. After switching to `stopping-strings-for-HF,` and changing my json payload to send an array instead of a string, it works like a charm.  Really, really great.

Side-question: What kind of gains do you get from passing `--xformers` when using exllama?  Does that do anything?

**Comment by Yiximail** [comment]
> 

works for `stopping-strings-for-HF` branch? sure you are using the `exllama` loader and not `exllama_HF`?

xformers barely affects anything for now
in theory it should improve performance, but it didn't

**Comment by tensiondriven** [comment]
oh, no, I switched the loader too:

```
python server.py --listen --listen-port 8000   --loader exllama_hf     --gpu-split 16,24       --model 65/guanaco-65B-GPTQ     --model_type llama   --chat  --api   --extensions api
```

**Comment by Yiximail** [comment]
> oh, no, I switched the loader too:
> 
> ```
> python server.py --listen --listen-port 8000   --loader exllama_hf     --gpu-split 16,24       --model 65/guanaco-65B-GPTQ     --model_type llama   --chat  --api   --extensions api
> ```

yeah
`stopping-strings-for-HF` branch only for `exllama_HF`
and
`stopping-strings` branch only for `exllama`

For the moment, I recommend you to use `exllama` which has better performance
