### ISSUE TITLE
Exllama 65B GPTQ with 2 GPU getting torch.cuda.OutOfMemoryError: CUDA out of memory 

### ISSUE THREAD

**Issue by gameveloster** [oobabooga/text-generation-webui#2752]
I am trying to load `TheBloke_guanaco-65B-GPTQ` on two 3090 using Exllama but it seems to be giving an OOM error when the first GPU has 23.96 GB VRAM used while 2nd GPU has only 7.87 GB used.

Attempted to start oobabooga using `--loader exllama` and `--gpu-split` with various combinations like `24,24`, `23.9,23.9`, `23,23`, also tried adding `--auto-devices` but all gave the OOM error.

```
$ python server.py --model TheBloke_guanaco-65B-GPTQ --listen --chat --loader exllama --gpu-split 24,24
bin /home/gameveloster/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so
2023-06-18 15:57:03 INFO:Loading TheBloke_guanaco-65B-GPTQ...
Traceback (most recent call last):
  File "/mnt/md0/text-generation-webui/server.py", line 1014, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/mnt/md0/text-generation-webui/modules/models.py", line 65, in load_model
    output = load_func_map[loader](model_name)
  File "/mnt/md0/text-generation-webui/modules/models.py", line 277, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
  File "/mnt/md0/text-generation-webui/modules/exllama.py", line 41, in from_pretrained
    model = ExLlama(config)
  File "/mnt/md0/text-generation-webui/repositories/exllama/model.py", line 630, in __init__
    tensor = tensor.to(device, non_blocking = True)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 23.69 GiB total capacity; 23.01 GiB already allocated; 35.12 MiB free; 23.01 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Tried oobabooga `5b4c0155f6ec084e18f481b42f06f68bc2072421` and `490a1795f090fda59934224919013f86914b2c1b`

Anyone knows the fix for this? Thanks :)

**Comment by Panchovix** [comment]
2x4090 here.

Try with 16,21. It should use about 22-23GB per card and it won't go above that. Remember that GPU 0 needs more for context.

**Comment by gameveloster** [comment]
@Panchovix Wow you fixed it for me! How did you figure out to use 16,21?

**Comment by Panchovix** [comment]
When testing with GTPQ for llama, I had to do that. Basically for 65B it needs about 5GB for context. Since EXLlama loads all in the first load (for 2048 context) it uses that.
