### ISSUE TITLE
Cannot load LLama

### ISSUE THREAD

**Issue by Urammar** [oobabooga/text-generation-webui#2761]
### Describe the bug

Other(flan5xl) models seem to load fine, but my llama.ccp model wont load.

Error is as follows

`Traceback (most recent call last): File “C:\MyShit\AI\Flan-t5-XXL\Obba\text-generation-webui\[server.py](http://server.py/)”, line 69, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name) File “C:\MyShit\AI\Flan-t5-XXL\Obba\text-generation-webui\modules\[models.py](http://models.py/)”, line 76, in load_model shared.model_type = find_model_type(model_name) File “C:\MyShit\AI\Flan-t5-XXL\Obba\text-generation-webui\modules\[models.py](http://models.py/)”, line 64, in find_model_type config = AutoConfig.from_pretrained(path_to_model, trust_remote_code=shared.args.trust_remote_code) File “C:\MyShit\AI\Flan-t5-XXL\Obba\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py”, line 958, in from_pretrained return config_class.from_dict(config_dict, **unused_kwargs) File “C:\MyShit\AI\Flan-t5-XXL\Obba\installer_files\env\lib\site-packages\transformers\configuration_utils.py”, line 701, in from_dict config = cls(**config_dict) File “C:\MyShit\AI\Flan-t5-XXL\Obba\installer_files\env\lib\site-packages\transformers\models\llama\configuration_llama.py”, line 112, in init super().init( File “C:\MyShit\AI\Flan-t5-XXL\Obba\installer_files\env\lib\site-packages\transformers\configuration_utils.py”, line 339, in init self.torch_dtype = getattr(torch, self.torch_dtype) AttributeError: module ‘torch’ has no attribute ‘int4’`

![Capture](https://github.com/oobabooga/text-generation-webui/assets/40313782/ea204169-a428-4b2e-9e7d-12a40a9755f0)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install lasted ooba, copy llama over, try to load model?

### Screenshot

![Capture](https://github.com/oobabooga/text-generation-webui/assets/40313782/bab45472-2666-4794-ae63-fa2c2d35c114)

### Logs

```shell
CMD log

bin C:\MyShit\AI\Flan-t5-XXL\Obba\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-06-19 20:56:06 INFO:Loading 7B...
```

### System Info

```shell
1080ti 64gb ram 12 core cpu
```

**Comment by m-from-space** [comment]
> Install lasted ooba, copy llama over, try to load model?
What do you mean by "copy llama over"? You don't have to copy anything since llama-cpp-python module is installed by default and will load GGML models.

Which model are you actually trying to load?

**Comment by Urammar** [comment]
So apparently you need to now have new editions/convert them to either GGML for gpu/cpu or GPTQ for gpu optimized versions

Also what is shown in the screenshot, while being what the installer installs, is very much the old ui. Run the update file to make sure your thing can actually do the thing.

You also need to check your loader settings, that you are loading the correct model with the correct loader. Then it works, there you go, future reader.
