### ISSUE TITLE
Turn template in Instruction template saving/loading incorrectly

### ISSUE THREAD

**Issue by simguy** [oobabooga/text-generation-webui#2762]
### Describe the bug

When inspecting an unedited Instruction template .yaml, it formats the Turn template with quotes but when I edit and save an Instruction template from within the Web UI it doesn't include the quotes. 

Should be this something like this:
turn_template: "<|user|> <|user-message|>\n<|bot|> <|bot-message|>&lt;/s&gt;\n"

But saves like this:
turn_template: <|user|> <|user-message|>\n<|bot|> <|bot-message|>&lt;/s&gt;\n

This is causing the Turn template to not load correctly, as \n will load as \\\n instead. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Using the Web UI, edit a Turn template property with a \n in it then save that Instruction template as a new one or overwrite an existing template. 
Load the Instruction template and notice the Turn template property doesn't properly load what was previously saved. (Specifically, \n will become \\\n)

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/11879268/033f85ca-b645-4ca9-af78-92b955cf2ae9)

### Logs

```shell
None
```

### System Info

```shell
Windows 10, EVGA GeForce RTX 3080 FTW3 ULTRA GAMING.
```

**Comment by oobabooga** [comment]
Fixed here https://github.com/oobabooga/text-generation-webui/commit/f31281a8de3ad81c06f03c360f3f1f80dc697c63
