### ISSUE TITLE
Use dicts to supply keyword args instead of using eval()

### ISSUE THREAD

**Issue by uff-valeu** [oobabooga/text-generation-webui#280]
Just a thing I noticed looking through the code. I might help you with refactoring this whenever I have some time.

Using eval is considered bad practice and not required in most cases, because Python allows list and dicts to be supplied as positional and keyword arguments to a function like this:

```py
my_function(1, 2, 3, a: 1, b:2)

# could be written as:
args = [1, 2, 3]
kwargs = {'a': 1, 'b': 2}
my_function(*args, **kwargs)
```

**Comment by oobabooga** [comment]
This has been implemented, part by me part in a user-contributed PR.
