### ISSUE TITLE
Not able to contact API of Stable Diffusion.

### ISSUE THREAD

**Issue by LanceLake** [oobabooga/text-generation-webui#2801]
### Describe the bug

File "C:\Coderoot\AI\oobabooga_windows\installer_files\env\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://127.0.0.1:7861/sdapi/v1/txt2img

The URL of http://127.0.0.1:7861 does bring it up. Besides the checkbox, is there anything else I need to set? 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load up the webui interface and make sure the sd_api_pictures is set. Also make sure that Stable Diffusion is running and the URL is the same as what it's running on the local computer.

### Logs

```shell
None
```

### System Info

```shell
Windows 10, NVIDIA graphics card.
```

**Comment by missionfloyd** [comment]
Did you enable the API in stable diffusion?
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API

**Comment by LanceLake** [comment]
No I didn't. Sorry about that. :)
