### ISSUE TITLE
Can we have a documentation on how to use superbooga extension?

### ISSUE THREAD

**Issue by chigkim** [oobabooga/text-generation-webui#2824]
How do you use superbooga extension for oobabooga? There's no readme or anything.

I enabled superbooga extension on oobabooga. Then I loaded a text file with information for some products, and it said it added the chunks to the database.

I asked what product was mentioned in the regular chat input box, and it says there was no mention of product or brand.

Then I ran with --verbose flag, and I noticed that the prompt had just question, no contents from the file.

Sorry if I missed it, but it would be great if there was some instruction on how to use it.

**Comment by EliEron** [comment]
There is technically documentation for it, but you are right that it's not super obvious. Right under the superbooga header there is a thin pane with the text "Click for more information..." if you click on that it will expand and give you a somewhat detailed explanation of how superbooga works.

But I can summarize the key information. For one, superbooga operates differently depending on whether you are using the chat interface or the notebook/default interface. In the chat interface it does not actually use the information you submit to the database, instead it automatically inserts old messages into the database and automatically retrieves them based on your current chat message.

To query information you have submitted you need to change to the notebook/default interface. In those modes you can insert the following three special tokens:
- `<|begin-user-input|>`
- `<|end-user-input|>`
- `<|injection-point|>`

Which are all pretty self-explanatory, you wrap your query in the user-input tags, and then place the injection point where you want the retrieved text to be placed. Once you start inference the tags will be stripped away and the contents that were retrieved from the database will be inserted automatically.

**Comment by chigkim** [comment]
Thanks for the info! That helps!
Choosing instruct for mode and Vicuna-v1 for instruct template worked!

Quick question...
I guess it's based on user query, but how does it decide which information to feed into context?
I tried loading a text file with bunch of reviews for a product and asking to summarize positive and negative feedbacks. By enabling --verbose flag to server.py, it was interesting to see what it decided to feed into the context.
It cobbled together different parts of reviews, fed into context, and generated a totally wrong narrative! lol I guess this is a major problem with LLM Confabulation.
