### ISSUE TITLE
Same LLama model, different GPU memory

### ISSUE THREAD

**Issue by s1530129650** [oobabooga/text-generation-webui#283]
When  I load the LLaMa-7B using its official code, the GPU memory takes up 22093MiB.
When  I load the LLaMa-7B using this repo's [code](https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model) , the GPU memory takes up 13778MiB.
What does make it different?

**Comment by BetaDoggo** [comment]
I believe the script in the official repo runs with a larger batch size. It might be a little bit slower but I don't think it makes too much of a difference.

**Comment by oobabooga** [comment]
Yep, the difference is in the batch size.

https://github.com/facebookresearch/llama/blob/main/example.py#L72
