### ISSUE TITLE
python setup.py bdist_wheel did not run successfully.

### ISSUE THREAD

**Issue by nemson-source** [oobabooga/text-generation-webui#2836]
### Describe the bug

I had to do a reinstall since the new update brock the web, and now I tried to fix the ``python setup. py bdist_wheel did not run successfully. `` Problem but with the commands I used it didn't fix it

here are the commands i used
1. python -m pip install torch==2.0.1+cu117 torchvision torchaudio --force-reinstall --no-deps --index-url https://download.pytorch.org/whl/cu117
2. conda install mamba -c conda-forge

this is the complet error

Building wheels for collected packages: quant-cuda
  Building wheel for quant-cuda (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running bdist_wheel
      running build
      running build_ext
      F:\AI\oobabooga\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'quant_cuda' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quant-cuda
  Running setup.py clean for quant-cuda
Failed to build quant-cuda
ERROR: Could not build wheels for quant-cuda, which is required to install pyproject.toml-based projects

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

reinstall the webui and run update.bat

### Logs

```shell
Building wheels for collected packages: quant-cuda
  Building wheel for quant-cuda (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      running bdist_wheel
      running build
      running build_ext
      F:\AI\oobabooga\installer_files\env\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'quant_cuda' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for quant-cuda
  Running setup.py clean for quant-cuda
Failed to build quant-cuda
ERROR: Could not build wheels for quant-cuda, which is required to install pyproject.toml-based projects
```

### System Info

```shell
windows 10 pro 22H2 x64
ASUS ROG Strix GeForce GTX 1660 SUPER
16GB ram
CPU: AMD Ryzen 3 1200 Quad-Core Processor
```

**Comment by nemson-source** [comment]
I got the problem resolved
The updater d'ident found the installed c++ tools I had to update them and now it works

**Comment by mytricker0** [comment]
what command did you use ?
because I did  `sudo apt update -y && sudo apt upgrade -y` and it still doesn´t work

**Comment by nemson-source** [comment]
I used these commands but they are windows commands, so I'm not sure what the commands are for Linux

python -m pip install torch==2.0.1+cu117 torchvision torchaudio --force-reinstall --no-deps --index-url https://download.pytorch.org/whl/cu117
conda install mamba -c conda-forge
