### ISSUE TITLE
ExLlama won't work - Yet ExLlama's built-in UI works fine

### ISSUE THREAD

**Issue by MildPanda** [oobabooga/text-generation-webui#2857]
### Describe the bug

Hello, I'm trying to use TheBloke/WizardLM-33B-V1.0-Uncensored-GPTQ on ExLlama however oobabooga keeps force switching to GPTQ-for-LLaMa model loader. I've successfully used the built in webui with ExLlama so I'm positive I have the required software to run ExLlama. Prior to the current issue loading TheBloke/WizardLM-33B-V1.0-Uncensored-GPTQ using ExLlama on oobabooga would enter an infinite loading attempt.

Keep in mind this is a fresh install of oobabooga as I got a new hard drive recently. I've also tried uninstalling torch and then installing the nightly build as that's the one ExLlama is developing on and that didn't fix it.
I even updated after I saw some changes to ExLlama (picture indicates the most recent commit I had updated to)
![image](https://github.com/oobabooga/text-generation-webui/assets/5686244/d915e12e-b716-42b3-b95f-cd88e607db75)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Not too sure. I've set --loader ExLlama and attempted to load a model in oobabooga.

### Screenshot

Video of me ensuring ExLlama is selected and then it just auto switches loaders and fails because it wants to try and use my system ram instead of GPU for who knows why.
https://streamable.com/alk56o

Video of me successfully running the benchmark test for ExLamma on the exact same model I just tried in the video above. _Sorry for the long video it's an unaltered benchmark test_ **a minute in** is about where additional benchmark info spits out.
https://streamable.com/n9w1bs

### Logs

```shell
I receive no errors for this. I checked for some sort of debugging flag for extra warnings/errors to be displayed but didn't see any.
```

### System Info

```shell
i7-8700k
3090 GPU
32GB Ram
Windows 11
```

**Comment by jllllll** [comment]
Does it work if you load the model after starting the WebUI and manually selecting the exllama loader?

**Comment by MildPanda** [comment]
> Does it work if you load the model after starting the WebUI and manually selecting the exllama loader?

This is what I do. No model loads as webui loads. I go into the UI, select ExLlama and it doesn't work.

**Comment by jllllll** [comment]
A pre-compiled module for exllama was added. Does it work if you uninstall that module?

To do this, run `cmd_windows.bat` and enter this command:
```
python -m pip uninstall exllama
```
This is assuming the use of the one-click-installer. If that wasn't used, just enter the python command as you needed.

**Comment by MildPanda** [comment]
> python -m pip uninstall exllama

Doing this produces the same results. Oobabooga auto switches to GPTQ-for-LLaMa and fails due to a ram issue.
I tried to python -m pip install exllama to reinstall it but that produces "no matching distribution"

**Comment by jllllll** [comment]
> Doing this produces the same results. Oobabooga auto switches to GPTQ-for-LLaMa and fails due to a ram issue. I tried to python -m pip install exllama to reinstall it but that produces "no matching distribution"

It is a custom build. Re-install with this:
```
python -m pip install https://github.com/jllllll/exllama/releases/download/0.0.3/exllama-0.0.3+cu117-cp310-cp310-win_amd64.whl
```
Try disabling `auto-load model` before loading it.

**Comment by MildPanda** [comment]
> > Doing this produces the same results. Oobabooga auto switches to GPTQ-for-LLaMa and fails due to a ram issue. I tried to python -m pip install exllama to reinstall it but that produces "no matching distribution"
> 
> It is a custom build. Re-install with this:
> 
> ```
> python -m pip install https://github.com/jllllll/exllama/releases/download/0.0.3/exllama-0.0.3+cu117-cp310-cp310-win_amd64.whl
> ```
> 
> Try disabling `auto-load model` setting before loading it.

Thanks so much for your help! Both the exllama module you provided and the default module (re-obtained running update_windows.bat) worked when I unchecked `auto-load model`.

_(Unnecessary read below)_
I've only recently been messing with my drivers as well and noticed I downloaded some old ones (v460s or something) but I downloaded those AFTER running into issues with ExLlama, not sure what version they were when I started messing with ExLlama.
