### ISSUE TITLE
No Oobabooga Discord or subReddit?

### ISSUE THREAD

**Issue by RandomInternetPreson** [oobabooga/text-generation-webui#286]
Just checking to make sure I stay on top of this amazing project!!  In my opinion this is by far the absolute best language AI Interface with phenomenal input from the creator <3

If there isn't a discord or subreddit for oobabooga, no problem, if it ain't broke don't fix it.  Mr Oobabooga is doing a fantastic job updating the code in the absence of a discord or subreddit forum.

I just wanted to say think you Mr. Oobabooga for all of your hard work and knowledge, you really have made the auto1111 for language models!

**Comment by ttio2tech** [comment]
I am able to run the LLaMA 13B model on 3080Ti using this library. Great works Mr. Oobabooga!  I also made a free to play discord bot, feel free to try it and discuss them. The server invite is https://discord.gg/SgmBydQ2Mn

**Comment by mcmonkey4eva** [comment]
Ooba doesn't want an official Discord, so I've created an unofficial community Discord: https://discord.gg/u27RhJECcW
