### ISSUE TITLE
what is llava?

### ISSUE THREAD

**Issue by Originalimoc** [oobabooga/text-generation-webui#2861]
### Describe the bug

Line 98 of https://github.com/oobabooga/text-generation-webui/blob/main/modules/models.py

`if not any(s in shared.model_name.lower() for s in ['llava', 'oasst']):`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

NA

### Logs

```shell
NA
```

### System Info

```shell
NA
```

**Comment by Ph0rk0z** [comment]
Hardly a bug.. it's a multi-modal model that describes images.
