### ISSUE TITLE
QUERY: Is there some form of log capture in Oobabooga?

### ISSUE THREAD

**Issue by sukhysall** [oobabooga/text-generation-webui#2895]
**Description**

It would be good if there was some form of automated log capture in the event that e.g. Oobabooga crashes thus taking the command window with it.

**Additional Context**

In my attempt to train a Lora, I use a lightweight OPT 2.7B model. However after a few minutes, something causes my PC to crash and reboot and unfortunately as I lose the display first, I can't tell what error output Oobabooga might have for me. 

Having some form of log file recording everything would be extremely helpful so it can be referenced after the PC has booted back up again.

**Comment by missionfloyd** [comment]
> However after a few minutes, something causes my PC to crash and reboot

That's likely a hardware problem. Your PSU might be able to handle it, or something could be overheating.

**Comment by sukhysall** [comment]
I'm running an rtx4090 with a core i9 and a 1000w psu. I've done lora training for stable diffusion without issue and very recently I was able to do a small training cycle with a dataset no more than 180kb in size against a gpt2.7b model on 1 epoch. 

When I then try 3 epoch, it crashes. Im looking for a pattern but the circumstances are not always consistent.  Some form of logging would really help if only to rule out oobabooga.

**Comment by missionfloyd** [comment]
You could redirect the output to a file.
`start_windows.bat > log.txt 2>&1`

**Comment by sukhysall** [comment]
Hi. Many thanks. Unfortunately it didn't work when I tried again. Dunno what about my rig might be causing this but I'm gonna close this feature request off.
