### ISSUE TITLE
I had do a simple fix for the GPTQ lib to make it work for LLaMA

### ISSUE THREAD

**Issue by ttio2tech** [oobabooga/text-generation-webui#290]
It might be due to my python version (3.8). It complains about the string doesn't have .endwith method. But it seems from the GPTQ dependency library. 
I change the line from checkpoint.endswith('.safetensors') to checkpoint.as_posix().endswith('.safetensors')        It then works great.  In case anyone has the same issue. 

I also made a free to play discord bot for my server, feel free to try it. https://github.com/ttio2tech/llama_discord_bot The server invite is https://discord.gg/SgmBydQ2Mn 
I will upload the code for the bot later. https://github.com/ttio2tech/llama_discord_bot 

@oobabooga The bot is using the API, I think the reported token/s may not be working properly as my3080TI reports less than 0.01t/s but acutally is much faster as you can try the bot. I will double check it. Would it be possible that you add the bot to the readme or wiki as it uses the API and it can be a good place for people to try different models and for discussion?

**Comment by oobabooga** [comment]
About the first part: this should have fixed it without the need to patch GPTQ https://github.com/oobabooga/text-generation-webui/commit/372363bc3d5383d8351e45ee77323ba686a59769
