### ISSUE TITLE
support to specify special tokens for prompts and replies

### ISSUE THREAD

**Issue by iurimatias** [oobabooga/text-generation-webui#292]
Models like the Open Assistant oasst-sft-1-pythia-12b use special tokens to indicate the assistant `<|assistant|>` and the user `<|prompter|>` .

Is there currently somewhat to configure this tokens when in chat mode?

**Comment by oobabooga** [comment]
Open Assistant seems to be a QA model trained on prompts formatted like this:

```
<|prompter|>Do you like AI?<|endoftext|><|assistant|>Yes, AI is the best<|endoftext|>
```

In chat mode there is a context string at the top, several messages, and then an empty `Bot: ` at the end. I am not sure where the special tokens should be placed or if the model would perform well in this context at all.

**Comment by iurimatias** [comment]
without those tokens the output is generally quite bad (night and day difference). The chat mode seems to assume models that rely on text completion, but models like this have these tags. So a possibility is to support configuring for each user a beginning and end tag (such as `<|prompter|>`/`<|assistant|>` and `<|endoftext|>`)

**Comment by michaelbogdan** [comment]
Other instruction-tuned models will have similar special tokens to denote the seperate roles and the chat interface is the natural way to interact with these instruction-tuned models. So there needs to be either a setting for how the chat is presented to the LLM or there needs to be a separate interface entirely.

**Comment by oobabooga** [comment]
I have added an Instruct mode in this commit https://github.com/oobabooga/text-generation-webui/commit/e722c240af56aa733c576f49e663ed7cafef5784

It is a subset of the chat interface, with the template specified in the form of a yaml pseudocharacter https://github.com/oobabooga/text-generation-webui/tree/main/characters/instruction-following

It works with Open Assistant and Alpaca out of the box.
 
![9lnhhnegp3sa1](https://user-images.githubusercontent.com/112222186/230279291-c437c042-ceb3-407a-a327-d53edcde8bff.png)
