### ISSUE TITLE
Exllama_hf reduces context?

### ISSUE THREAD

**Issue by chigkim** [oobabooga/text-generation-webui#2925]
### Describe the bug

When using a SuperHot-8K model, Exllama_hf reduces context to below 2k.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Load a SuperHot-8K model with --loader exllama_hf --max_seq_len 8192 --compress_pos_emb 4.
2. Put a extremely long text as an input. I.E. I put text that tiktoken counted as 10k tokens.
3. Generate
It works, but it seems it reduces context according to output.
Output generated in 14.36 seconds (8.01 tokens/s, 115 tokens, context 1848, seed 460104355)
If I load with regular exllama without _hf it throws an error for exceed max.

### Logs

```shell
Output generated in 14.36 seconds (8.01 tokens/s, 115 tokens, context 1848, seed 460104355)
```

### System Info

```shell
Colab with T4
```

**Comment by chigkim** [comment]
If I load the same model with exllama (without _hf), and put the same 
input, I get an error for going over the max limit.

**Comment by jepjoo** [comment]
> As a sanity check, are you also changing the "Truncate the prompt up to this length" setting under the parameters tab? I just ran a quick test using Exllama_hf along with superhot-30b-8k-no-rlhf and things seemed fine.
> 
> `Output generated in 36.77 seconds (2.50 tokens/s, 92 tokens, context 7957, seed 844919526)`

Yep, this solved it for me. Thanks!

**Comment by chigkim** [comment]
Yes! Truncate length was the key!
