### ISSUE TITLE
Privacy - Remove 3rd party libraries from CDNs being requested in HTML

### ISSUE THREAD

**Issue by chrisbward** [oobabooga/text-generation-webui#2933]
Hi,

I've noticed that the application cannot run offline, and that there are some libraries and assets being downloaded from Google Fonts and other CDNs.

These requests may have the potential to be backdoored at a later date.

Please resolve.

**Comment by oobabooga** [comment]
> the application cannot run offline

Not true

> downloaded from Google Fonts

Not true

> other CDNs (plural)

Not true. There was 1 harmless cloudfare request. I removed it anyway here https://github.com/oobabooga/text-generation-webui/commit/9aee1064a3b1fe4d10575961f4fa0d5403600433
