### ISSUE TITLE
Stopping strings not respected when using extended ctx mode in exllama/exllama_hf

### ISSUE THREAD

**Issue by official-elinas** [oobabooga/text-generation-webui#2946]
### Describe the bug

As the title says, I cannot get stopping strings to work when running exllama or exllama_hf using the extended context flags as well as using the API. Works fine without extending context. Using SillyTavern as a frontend to interface with the API.

I have not tested the Gradio interface as I exclusively use the API.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run either of the following commands

`python server.py --listen --api --model "mymodel-4bit" --loader exllama --max_seq_len 8192 --compress_pos_emb 4`

`python server.py --listen --api --model "mymodel-4bit" --loader exllama_hf --max_seq_len 8192 --compress_pos_emb 4`

Note I use `CUDA_VISIBLE_DEVICES=0` so it only runs on a single 3090.

### Logs

There is no error. I just get the stopping string(s) in the output defined as:

`stopping_strings: [ '\nYou:', '\nMyName:', '\n### Instruction:', '\n### Response:' ]`

Specifically `### Response` is printed in the output.

### System Info

```shell
Kubuntu 23.04
CPU: AMD EPYC 7B13 (128)
Memory: 256GB ECC
Motherboard: ROMED8-2T
GPU: 2x RTX 3090
```

**Comment by official-elinas** [comment]
Closing this as I was mainly testing on high context, which is not coherent past a point anyway (about 1.5k the original cutoff of the model)

**Comment by tensiondriven** [comment]
@official-elinas I've encountered this as well - not only with stopping_strings, but `no_repeat_engram_size` as well.  (`no_repeat_engram_size` is especially important with massive contexts.) Iirc there's a branch of exllama_hf which supports these, but I can't seem to find it - if you hear of anything, please post!
