### ISSUE TITLE
Slowdown for exllama on Pascal cards

### ISSUE THREAD

**Issue by ENjoyBlue2021** [oobabooga/text-generation-webui#2949]
### Describe the bug

Exllama is slow on pascal cards because of the prompt reading, there is a workaround here though:
https://github.com/turboderp/exllama/issues/111

Is it possible to implement a fix like this for pascal card users?
Changing it in the repositories/exllama/ didnt fix it for me.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See the exllama issue. 

### Logs

```shell
Output generated in 13.96 seconds (0.57 tokens/s, 8 tokens, context 39, seed 1543145771)
Output generated in 12.50 seconds (0.72 tokens/s, 9 tokens, context 39, seed 192406504
```

### System Info

```shell
1080ti+1080, ubuntu linux
```

**Comment by burgerlawful** [comment]
> Changing it in the repositories/exllama/ didnt fix it for me.

That's probably because it defaults to loading the pip installed version, only using the repositories/exllama if it isn't found. So if you pip uninstall exllama it might work

**Comment by jllllll** [comment]
Haven't tested it yet, but I have made wheels available for the latest changes here:
https://github.com/jllllll/exllama/releases/tag/0.0.5

**Comment by jllllll** [comment]
Hmm... Latest changes don't seem to fix the issue for me.

**Comment by ENjoyBlue2021** [comment]
@burgerlawful
Thanks, that worked for me!

I'm going to close this issue since this comes from exllama.
