### ISSUE TITLE
mode option from settings.yaml/settings.json is ignored

### ISSUE THREAD

**Issue by set-soft** [oobabooga/text-generation-webui#2973]
### Describe the bug

When indicating a mode in the settings file (like in the provided example that uses `mode: chat`) the code simply ignores it.

The code never transfers this value to `shared.args`, used by functions like `shared.is_chat`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Simply use the provided settings-example.yaml, it says chat mode, but you get default mode.

### Logs

```shell
No error generated
```

### System Info

```shell
Not relevant:
Debian GNU/Linux 11.7
Radeon RX 5500 XT
```

**Comment by oobabooga** [comment]
See https://github.com/oobabooga/text-generation-webui/pull/2975#issuecomment-1631791079

**Comment by set-soft** [comment]
> See [#2975 (comment)](https://github.com/oobabooga/text-generation-webui/pull/2975#issuecomment-1631791079)

Hi @oobabooga !
I'm really confused, how do you plan to implement some sort of persistence? To be more specific: you state the goal of your project is to be the equivalent to AUTOMATIC1111 WebUI for Stable Diffusion. In that tool you can save the settings, things that aren't saved in the settings are restored just loading an already generated image. But in this project the only way to achieve some sort of persistence is a combination of settings.yaml and the command line. Which is enough for me, but not for most users, just think about the server running on a remote server ... the user can't control the command line. Currently you must set the interface mode and the model (the most important options) from the command line. IMHO options to save/restore the state should be added. Various of my patches tried to at least add the needed restore part, so we could just implement the save part and close the loop.
