### ISSUE TITLE
Save logs to a local folder in normal and --notebook mode

### ISSUE THREAD

**Issue by jasonborn0** [oobabooga/text-generation-webui#299]
As titled. As this project is gaining attention it is quite necessary to set up a proper issue template, as well as document important keyboard shortcuts such as "ctrl+enter" in automatic1111. 

It might also be helpful if the program by default saves a log of text gen history to a local output folder.

Happy to work on this in a pr.

**Comment by oobabooga** [comment]
* Issue/bug report templates have been added
* There is just one shortcut: shift+enter to submit a text field in regular or `--notebook` mode. It's a gradio default for multiline input fields.

**Comment by oobabooga** [comment]
The ability to save logs in normal/notebook mode is indeed lacking. Do you have an idea for how to design this?

**Comment by oobabooga** [comment]
An option for saving the current prompt has been added recently.

**Comment by jlc42** [comment]
I want to be able to save my conversation with a character, and then load it back in. I can't seem to find a way to do that currently. I can upload a chat history, but there needs to be a good simple way to save the existing history to a file.
