### ISSUE TITLE
Answer being cut when using `<tokens>` in Galactica or Open Assistant

### ISSUE THREAD

**Issue by CreativeFriday** [oobabooga/text-generation-webui#300]
Hi,
When using the `<work>` token to enables step-by-step reasoning in Galactica it cuts of the beginning of the answer. Mostly it's not a big deal, but if the answer starts with an equation, chemical formula or similar it's sometimes nearly impossible to figure out. (using Pop OS and a 3090)

```
A force of 0.6N is applied to an object, which accelerates at 3m/s. What is its mass?

<work>tive: find the mass $m$

We can use Newton's second law:

$F = ma$ ......
```

Same problem in open assistant with `<|prompter|>, <|endoftext|> and <|assistant|>`
```
<|prompter|>What is a meme, and what's the history behind this word?<|endoftext|><|assistant|>ard Dawkins in his 1976 book The Selfish Gene. He used it to describe an idea or behavior ......
```

**Comment by oobabooga** [comment]
This should have solved it https://github.com/oobabooga/text-generation-webui/commit/a577fb1077ebbf2631276c5fc408fe4aff93d208

**Comment by CreativeFriday** [comment]
Thanks, works like a charm now - and a noticed that it also had been solved for Open Assistant in another bug fix.
