### ISSUE TITLE
Linux - AttributeError: 'ExLlamaConfig' object has no attribute 'calculate_rotary_embedding_base'

### ISSUE THREAD

**Issue by ItsJPrentice** [oobabooga/text-generation-webui#3004]
### Describe the bug

After attempting to test [the fix](https://github.com/oobabooga/text-generation-webui/commit/333075e726e8216ed35c6dd17a479c44fb4d8691) for #3003 on a clean Runpod instance, I am encountering a new error.

`AttributeError: 'ExLlamaConfig' object has no attribute 'calculate_rotary_embedding_base'`

Seemingly related to [this comment](https://github.com/oobabooga/text-generation-webui/issues/3003#issuecomment-1620373720).

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Initialize a new container on Runpod using `TheBloke LLMs` base image.
2. Download an 8k GPTQ image like [TheBloke/airoboros-33B-gpt4-1-4-SuperHOT-8K-GPTQ](https://huggingface.co/TheBloke/airoboros-33B-gpt4-1-4-SuperHOT-8K-GPTQ)
3. Set the following configuration...
	- Model Loader: `ExLlama_HF`
	- Max Sequence Length: `8192`
	- Positional embeddings compression: `4`
4. Attempt to load the model to receive the error

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/622332/d34794ba-1f03-4744-a373-4f6f5f44d9ec)

### Logs

```
Traceback (most recent call last): File “/workspace/text-generation-webui/server.py”, line 68, in load_model_wrapper shared.model, shared.tokenizer = load_model(shared.model_name, loader) File “/workspace/text-generation-webui/modules/models.py”, line 74, in load_model output = load_func_map[loader](https://5gidu3ykt5iin1-7860.proxy.runpod.net/model_name) File “/workspace/text-generation-webui/modules/models.py”, line 293, in ExLlama_HF_loader return ExllamaHF.from_pretrained(model_name) File “/workspace/text-generation-webui/modules/exllama_hf.py”, line 103, in from_pretrained config.calculate_rotary_embedding_base() AttributeError: ‘ExLlamaConfig’ object has no attribute ‘calculate_rotary_embedding_base’
```

### System Info

Runpod A100x1 instance.

**Comment by Panchovix** [comment]
Are you on latest exllama wheel/version? (0.0.5 if using the wheel)

That function got added recently to support NTK rope scaling

**Comment by ItsJPrentice** [comment]
@Panchovix - That may be the culprit. Running `pip show exllama` reveals that the base container installs `0.0.3+cu117`.

**Comment by CamelCoin** [comment]
@ItsJPrentice you can simply upgrade your exllama using this command

`pip install https://github.com/jllllll/exllama/releases/download/0.0.5/exllama-0.0.5+cu117-cp310-cp310-linux_x86_64.whl`

**Comment by Culpeo** [comment]
Same problem here. I'm running on a docker container, thebloke/cuda11.8.0-ubuntu22.04-oneclick:latest, see https://github.com/TheBlokeAI/dockerLLM/tree/main/cuda11.8.0-ubuntu22.04-oneclick. I guess ItsJPrentice does the same.

I'm not a Docker expert, but in [this docker file here](https://github.com/TheBlokeAI/dockerLLM/blob/main/cuda11.8.0-ubuntu22.04-textgen/Dockerfile) it says: "git clone https://github.com/turboderp/exllama". So _not_ jllllll/exllama. Could this be the reason?

**Comment by ItsJPrentice** [comment]
@CamelCoin - Bingo, after executing your suggested `pip install` command I am successfully able to load the models again.

**Comment by ItsJPrentice** [comment]
@Culpeo - Saw that too. I'll raise the issue in his repo since it appears that the issue may be with the base image rather than this project.

**Comment by Culpeo** [comment]
Thanks, @ItsJPrentice  :-)

**Comment by TheBloke** [comment]
I've updated my docker container so it should now be resolved.

The problem stems from the fact that `requirements.txt` now lists a static exllama pip.  ExLlama dynamically built its kernel extension on first load, but the statically defined pip overrides that.  So now I need to update the Docker any time there's a breaking change in ExLlama's extension.

Maybe I should update my docker to `grep -v exllama` from requirements.txt.  Then the extension will be auto-built by ExLlama on first use, and it can't ever be outdated (as the container does a `git pull` on both text-generation-webui and exllama on every boot.)

I'll test that and confirm it works and if so, do another update.

**Comment by HWiese1980** [comment]
Any news?
