### ISSUE TITLE
Api does not work

### ISSUE THREAD

**Issue by Yvonne-Aizawa** [oobabooga/text-generation-webui#3006]
### Describe the bug

i use the api to generate my text. this used to work untill a few days ago.
now it returns 200 OK but the content is empty
in the console however it returns an error code so i assume it is a bug with the text-generation-webui. In the webui itself it does work however

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

i used my own code but the examples (at least the chat one) gives the same result

### Screenshot

no screenshot necessary since logs are included

### Logs

```shell
----------------------------------------
127.0.0.1 - - [04/Jul/2023 18:28:52] "POST /api/v1/chat HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 51686)
Traceback (most recent call last):
  File "/mount/chonky-files/oobabooga/installer_files/env/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/mount/chonky-files/oobabooga/installer_files/env/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/mount/chonky-files/oobabooga/installer_files/env/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/mount/chonky-files/oobabooga/installer_files/env/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/mount/chonky-files/oobabooga/installer_files/env/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/mount/chonky-files/oobabooga/text-generation-webui/extensions/api/blocking_api.py", line 82, in do_POST
    generator = generate_chat_reply(
TypeError: generate_chat_reply() got multiple values for argument 'regenerate'
----------------------------------------
```

### System Info

```shell
Honestly not importent for this query but i use Linux, on an nvidia gpu (GeForce RTX 3060 Laptop GPU), i also run in the same issue on runpod using TheBloke's template
```

**Comment by Picus303** [comment]
I have the exact same issue on Windows.

**Comment by fikriazain** [comment]
It seems that using Google Colab, the content of the chat.py in modules folder remains unaltered.  
![Screenshot 2023-07-05 015501](https://github.com/oobabooga/text-generation-webui/assets/65524505/a54905bb-5a2d-47ac-8299-1c1235c5ab62)

But, if you use it on the updated file, it has a additional parameter.  
![Screenshot 2023-07-05 015750](https://github.com/oobabooga/text-generation-webui/assets/65524505/a686f5ab-e69d-4df4-99c2-81e806795c5c)

**Comment by cedonley** [comment]
Seem the fix is to add the history to generate_params, which is passed in as the state. Could modify line 221 in extensions/api/blocking_api.py to look as follows:

            generate_params['history'] = history
            generator = generate_chat_reply(
                user_input, generate_params, regenerate=regenerate, _continue=_continue, loading_message=False)

**Comment by Picus303** [comment]
I found a fix! It pretty simple. Should I make a pull request for it? It would be better than just to leave the explaination here but I have never made one before. Do you think it's a good idea?
