### ISSUE TITLE
Error when downloading model from UI

### ISSUE THREAD

**Issue by StephenQuirolgico** [oobabooga/text-generation-webui#3009]
### Describe the bug

I just downloaded the latest version of text-generation-webui on Ubuntu and started the UI but it is not longer allowing me to download a model from the UI. I tried to downloading 'anon8231489123/vicuna-13b-GPTQ-4bit-128g' but got the following error:

Traceback (most recent call last): File “/home/squirol/ben2/oobabooga_linux/text-generation-webui/server.py”, line 134, in download_model_wrapper downloader = downloader_module.ModelDownloader() TypeError: ModelDownloader.init() missing 1 required positional argument: ‘max_retries’

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Launch web UI using ./start_linux.sh
2. Open browser to http://127.0.0.1:7860/
3. Enter 'anon8231489123/vicuna-13b-GPTQ-4bit-128g' and select Download in UI
4. View exception under Download button

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/4974765/69a6d099-cce9-4b44-90b1-e05a891de8e0)

### Logs

```shell
N/A
```

### System Info

```shell
Ubuntu
NVIDIA
```

**Comment by proto-n** [comment]
Can confirm, also was able to quickly fix for myself by modifying server.py by modifying line 134 to read `downloader = downloader_module.ModelDownloader(max_retries=1)`

**Comment by martinkoeth** [comment]
> Can confirm, also was able to quickly fix for myself by modifying line 134 of server.py to read `downloader = downloader_module.ModelDownloader(max_retries=1)`

When I do this I get the following error: TypeError: ModelDownloader.init() got an unexpected keyword argument ‘max_retries’
