### ISSUE TITLE
Allow overriding 'Is typing...' placeholder message

### ISSUE THREAD

**Issue by Brawlence** [oobabooga/text-generation-webui#303]
**Description**

I want to have a method (maybe something similar to hijack_input) which allows the extensions to temporarily modify the default placeholder generation text (`'*Botname: Is typing...*'`) shown in the chat mode.

**Additional Context**

I'm currently working on an extension which integrates Stable Diffusion generation capabilities as a response to certain inputs. (Similar to the send_pictures extension, but in reverse.)

So far I've been able to accomplish everything I want but it would be nice to have a way to trigger `'*Botname: Is sending a picture...*'` placeholder message instead of the usual one.

I imagine, having it say `'*Botname: Is recording a voice message...*'` would also be useful for TTS generation as well.

---

If one is curious, examples of what the extension does are below:

<details>
<summary>Conversation 1</summary>

![EXA1](https://user-images.githubusercontent.com/42910943/224866564-939a3bcb-e7cf-4ac0-a33f-b3047b55054d.jpg)
![EXA2](https://user-images.githubusercontent.com/42910943/224866566-38394054-1320-45cf-9515-afa76d9d7745.jpg)
![EXA3](https://user-images.githubusercontent.com/42910943/224866568-10ea47b7-0bac-4269-9ec9-22c387a13b59.jpg)
![EXA4](https://user-images.githubusercontent.com/42910943/224866569-326121ad-1ea1-4874-9f6b-4bca7930a263.jpg)

</details>

<details>
<summary>Conversation 2</summary>

![Hist1](https://user-images.githubusercontent.com/42910943/224865517-c6966b58-bc4d-4353-aab9-6eb97778d7bf.jpg)
![Hist2](https://user-images.githubusercontent.com/42910943/224865527-b2fe7c2e-0da5-4c2e-b705-42e233b07084.jpg)
![Hist3](https://user-images.githubusercontent.com/42910943/224865535-a38d94e7-8975-4a46-a655-1ae1de41f85d.jpg)

</details>

<details>
<summary>Extension interface</summary>

![Interface](https://user-images.githubusercontent.com/42910943/224867102-a1cd8f3f-072e-4e9d-9058-d0cb03288b4b.jpg)

</details>

**Comment by oobabooga** [comment]
Here is what I could think of: https://github.com/oobabooga/text-generation-webui/commit/3fb8196e167d9fa466453496e9172d03f524d364

Probably not the most elegant solution, but it works.

Your extension looks amazing by the way, do you plan to upload it to GitHub?

**Comment by Brawlence** [comment]
Thanks! I can confirm that it works.

![Pic](https://user-images.githubusercontent.com/42910943/224875381-d3f9895c-7fed-4ff7-89d5-1e107d0cefde.png)

Yes, of course. It's currently unsophisticated and quirky, but this should serve as a good starting point.
How do I go about that? Should I just open the pull request with the whole repo included?

**Comment by oobabooga** [comment]
Since this seems like a complex extension, it may be better for you to create a dedicated repository that can be maintained independently. I can link it in the wiki (https://github.com/oobabooga/text-generation-webui/wiki/Extensions).

But if you prefer to submit it as a PR here, you are welcome to do that as well.
