### ISSUE TITLE
ERROR:Task exception was never retrieved

### ISSUE THREAD

**Issue by nagypal0121** [oobabooga/text-generation-webui#3042]
### Describe the bug

Right after installation i open the webui in the browser and i receive an error.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

Right after installation i open the webui in the browser and i receive this error.

### Logs

```shell
2023-07-07 21:25:11 ERROR:Task exception was never retrieved
future: <Task finished name='3s4vbrhqz8a_103' coro=<Queue.process_events() done, defined at D:\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\gradio\queueing.py:343> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': '3s4vbrhqz8a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing>
Traceback (most recent call last):
  File "D:\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "D:\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "D:\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\gradio\queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "D:\oobabooga\oobabooga_windows\installer_files\env\lib\site-packages\pydantic\main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...on_hash': '3s4vbrhqz8a'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
```

### System Info

```shell
Windows 11
EVGA RTX3080
```

**Comment by jackpisso** [comment]
same error;
RTX 4090

**Comment by enricoros** [comment]
Same error:
RTX 3090

**Comment by kevinandrewkramer** [comment]
Same error here.
Windows 11 - RTX3090

Seems to be related to Pydantic V2 switchover for gradio, hotfix is in progress.
https://github.com/gradio-app/gradio/pull/4835

I manually applied the changes to the gradio/data_classes.py from the commits in the hotfix branch, and can confirm all is working again.
https://github.com/gradio-app/gradio/compare/main...hotfix-pydantic

**Comment by leonardinius** [comment]
Same

Mac OS X,
Arm M1 Gpu

**Comment by Cornyyy11** [comment]
> Same error here. Windows 11 - RTX3090
> 
> Seems to be related to Pydantic V2 switchover for gradio, hotfix is in progress. [gradio-app/gradio#4835](https://github.com/gradio-app/gradio/pull/4835)
> 
> I manually applied the changes to the gradio/data_classes.py from the commits in the hotfix branch, and can confirm all is working again. [gradio-app/gradio@main...hotfix-pydantic](https://github.com/gradio-app/gradio/compare/main...hotfix-pydantic)

Can you please share what files have you changed and in what way?

**Comment by leonardinius** [comment]
The  `pip3 install 'gradio>=3.36.1'` fixed it for me. 
The 3.36.1 was released literally 15 minutes ago.

**Comment by NathanJGaul** [comment]
> The `pip3 install 'gradio>=3.36.1'` fixed it for me. The 3.36.1 was released literally 15 minutes ago.

Fixed the error for me as well. Thanks!

**Comment by GreySphynx** [comment]
> > The `pip3 install 'gradio>=3.36.1'` fixed it for me. The 3.36.1 was released literally 15 minutes ago.
> 
> Fixed the error for me as well. Thanks!

Hey, how do I fix that? Where do I put `pip3 install 'gradio>=3.36.1'`  ?

**Comment by jaidaken** [comment]
Open 'cmd_windows.bat' and type `pip3 install gradio==3.36.1`

**Comment by oobabooga** [comment]
I think that this fixes the issue without the need to update gradio (the latest version breaks some CSS styles in a nontrivial way)

https://github.com/oobabooga/text-generation-webui/commit/79679b3cfdce749badb85ac198ba5014946429aa

To apply, just run the update script again (or pip install -r requirements.txt --upgrade if you installed manually)

**Comment by daniel-furman** [comment]
Upgrading to gradio==3.36.1 worked for me as well!
