### ISSUE TITLE
After the update gptq-for-llama and autogptq stopped working.

### ISSUE THREAD

**Issue by liverwalk** [oobabooga/text-generation-webui#3052]
### Describe the bug

After the update GPTQ-for-llama and AutoGPTQ stopped working, just a few days ago everything was working fine.

Exllama still works fine, although it has always worked slower for me than GPTQ-for-llama.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Any gptq models don't work

### Logs

```shell
it just stops
```

### System Info

```shell
intel i5-4670K CPU @ 3.40GHz
16 GB
GTX 1060 6 GB
Windows 10 Pro 22H2; 19045.3086; Windows Feature Experience Pack 1000.19041.1000.0
```

**Comment by FartyPants** [comment]
They do, but you need to have them updated as well.
git pull will update only WebUI

**Comment by liverwalk** [comment]
> They do, but you need to have them updated as well. git pull will update only WebUI

I used the auto installer for windows.

**Comment by liverwalk** [comment]
Oh, it fixed itself after using update_windows.bat
