### ISSUE TITLE
send_picutres extension is not functioning correctly after Sessions update

### ISSUE THREAD

**Issue by RandomInternetPreson** [oobabooga/text-generation-webui#3053]
### Describe the bug

When sending a picture using send_picture, the picture is received by the AI.  However, the image disappears when I continue the chat and the text  ",[object Object]"  is "stuck" on the UI above the chat window.  The text isn't in its own chat bubble or anything, just text sort of stuck on the page.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use send_pictures to send a picture, you'll see the text and you'll see the picture disappear when you continue chatting.

### Screenshot

![image2](https://github.com/oobabooga/text-generation-webui/assets/6488699/50090a59-e482-41c1-883b-ccacb0c7236d)
![image1](https://github.com/oobabooga/text-generation-webui/assets/6488699/ffd5765d-c44b-4b38-a717-725c3ee1ec90)

### Logs

```shell
Nothing of note, there are no overt errors.
```

### System Info

```shell
Windows installation on window 10.
```

**Comment by oobabooga** [comment]
Fixed here (will go in the next release, v1.1)

https://github.com/oobabooga/text-generation-webui/commit/180420d2c9691eefcd8e60217b2fdb9efac1359b
