### ISSUE TITLE
Capabilities similar to PrivateGPT

### ISSUE THREAD

**Issue by ChrisBNECBT** [oobabooga/text-generation-webui#3059]
I'm wondering if you could add a feature so that users could upload documents and query them like **PrivateGPT**.

The reason for the request is that the current Oobabooga is able to load different LLMs more easily, comes with more controls and enables users to continue a broken response through a simple button on the WebUI.

_This will be good for more public adoption._

**Comment by B-altug** [comment]
I totally agree, I will be working on my book locally but I couldn't find such an application that really works. this extension is required.
