### ISSUE TITLE
support for uploading tavernAI format embedded character image

### ISSUE THREAD

**Issue by Slug-Cat** [oobabooga/text-generation-webui#31]
It would be nice to have for compatibility, some characters don't seem to have a JSON download.

**Comment by oobabooga** [comment]
I agree that this should be implemented. It is frustrating that they use a different fields to specify the characters:

`'name"`,`"description"`,`"personality"`,`"first_mes"`,`"avatar"`,`"chat"`,`"last_mes"`,`"mes_example"`,`"scenario"`,`"create_date'`
