### ISSUE TITLE
Bug with Vicuna=v1.1 Instruction Template (typo in Turn Template)

### ISSUE THREAD

**Issue by RandomInternetPreson** [oobabooga/text-generation-webui#3103]
### Describe the bug

There looks to be a typo in the formatting output for the Turn template for Vicuna-v1.1

It is currently this:
"<|user|> <|user-message|>\n<|bot|> <|bot-message|></s>\n"

for some reason "</s>" is not being shown in the text field here on github? 

it's the /s that is throwing things off <> removed show the characters are rendered in this text field
"<|user|> <|user-message|>\n<|bot|> <|bot-message|> /s \n"

that </s> is throwing things off and producing the issue where the model essentially talks to itself.

I've edited my template to look like this:
"<|user|> <|user-message|>\n<|bot|> <|bot-message|>\n"

And things are working as intended.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use airoboros-33B-gpt4-1-4-SuperHOT-8K-GPTQ and try the default template, it will mess up.

### Logs

```shell
None of note
```

### System Info

```shell
Windows installation, windows 10.
```

**Comment by berkut1** [comment]
Are you talking about `</s>` ?
This is part of the Vicuna template:
https://github.com/lm-sys/FastChat/blob/daa2b9abe20597ebf34dc5df164d450456610c74/fastchat/conversation.py#L257C21-L257C21

**Comment by berkut1** [comment]
Oh, yeah I see about what you are talking.
Sometimes model stops recognize the context, and talk like with itself.
But I don't think that problem exactly with template, because if you reload a template it again start to work correctly.

**Comment by RandomInternetPreson** [comment]
Interesting, thank you for the link.  You are probably right that it's not a typo, but I've tried reloading the temple again too and the problem persists.  The only way I was able to stop it from happening was to remove the /s.  🤷‍♂️

**Comment by berkut1** [comment]
@RandomInternetPreson you can create your own template (but you need to manually select it all the time after loading/reloading the model) and check how it works over a long distance. If this solves the problem, you can try making a PR.
It's a bad idea to change the default templates because they will revert to their original state after update.

**Comment by RandomInternetPreson** [comment]
Thanks all, I was in error in my identification of a bug.
