### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio' is not solved

### ISSUE THREAD

**Issue by mockinbirdy** [oobabooga/text-generation-webui#3105]
### Describe the bug

ModuleNotFoundError: No module named 'gradio'

I saw this problem discussed #835 but the issue is still there. And it cannot be fixed by running the proposed commands.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Reinstall this repo, try to use it

### Logs

```shell
ModuleNotFoundError: No module named 'gradio'
```

### System Info

```shell
windows 10
```

**Comment by Ph0rk0z** [comment]
You must be in the wrong environment where gradio isn't installed.

**Comment by Foxtr0t1337** [comment]
You can use the installer in the Release page. It will automatically install everything.

**Comment by mockinbirdy** [comment]
> You must be in the wrong environment where gradio isn't installed.

Everything was installed according to the instructions. Any fix to this? As I said, the workarounds proposed by people in another thread do nothing.

> You can use the installer in the Release page. It will automatically install everything.

I did exactly this, it does not work.

**Comment by Foxtr0t1337** [comment]
You mentioned that you can find a cmd file. Are you able to find that right now? If you can't I will try to figure that out.

**Comment by mockinbirdy** [comment]
I just reinstalled it all again, seemed to fix the problem. But now exllama does not want to work.

**Comment by fememystic** [comment]
I have the same error
"Total VRAM 24576 MB, total RAM 32512 MB
xformers version: 0.0.24
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Traceback (most recent call last):
  File "D:\_AI\ComfyUI\main.py", line 77, in <module>
    import server
  File "D:\_AI\ComfyUI\server.py", line 33, in <module>
    from app.user_manager import UserManager
  File "d:\_ai\comfyui\custom_nodes\stablesr\app.py", line 12, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'"

But your solution didn't help me...

**Comment by fememystic** [comment]
Comfy.ui, portable.
