### ISSUE TITLE
Decode bug in llama.py and even other models

### ISSUE THREAD

**Issue by Foxtr0t1337** [oobabooga/text-generation-webui#3106]
### Describe the bug

At llama.py
line 999 
`"text": self.detokenize([token]).decode(`

We can see that if the token only contains part of a character, things will go wrong.
The "ignore" arg makes it hard to spot.
The outcome is that some chars such as Chinese will be missing in the return value of function `generate(self, prompt, state, callback=None)` causing missing chars on the web UI.
After set it to "replace", I found that there is many '�' where chars are missing.
I CAN NOT fix this because there is other models which I can't test.
What I can do is only making "text" bytes and make it a problem for generate function.
I can't make a pull request because I can't fix only this model and cause more bugs.

Other models may contain this bug too but idk.
There are some issues which may relate to this bug which are still open.
Maybe some of you who have other models can test those and we come up with a final fix.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I used a llama.cpp model who can speak Chinese.
Just speak to them and some times there will be missing chars which looks like a training problem but not.

### Screenshot

After I change it to "replace"
<img width="738" alt="Screenshot 2023-07-12 at 8 47 38 AM" src="https://github.com/oobabooga/text-generation-webui/assets/48181014/e2da2523-48f2-4282-9cb1-078999d2d73b">

After some tweaking
<img width="409" alt="Screenshot 2023-07-12 at 9 37 30 AM" src="https://github.com/oobabooga/text-generation-webui/assets/48181014/10c80d9e-0c5c-425f-b41f-4612305bd41a">

### Logs

```shell
Not a crash.
```

### System Info

```shell
Apple M2 Max latest OS.
```

### Update

After tweaking some code I successfully fixed the bug on the model I've been using.
I decided that I will try to fix other models and do a pull request?

Me again.
There is no way I can do a pull request since llama.py and some other files are not belong to this repo.
However I am willing to contribute my code if somehow it is needed.

The main idea of my fix is making generate function return bytes and we decode this in generate_reply_wrapper function.
<img width="1176" alt="Screenshot 2023-07-12 at 10 01 33 AM" src="https://github.com/oobabooga/text-generation-webui/assets/48181014/fa3567bf-b426-4317-93ed-10ecf7e5f756">
This way we won't ignore any incomplete chars.
It is important to know that this screenshot is not all the code I changed.
Other changes are only replacing '' to b'' etc. and cancel decoding at llama.py line 999.
I really don't know where does llama.py come from since I only worked on this project 1 day.
If anyone can commit those changes without introducing new bugs then you are welcomed to use my code.

**Comment by oobabooga** [comment]
Please feel free to submit a PR and I will have a look.

**Comment by Foxtr0t1337** [comment]
> Please feel free to submit a PR and I will have a look.

I already created a pull request.
This is my very first formal pull request on Github so if there is any issue please correct me.

It is important to notice that I only changed the llamacpp_model.py which doesn't impact other modules.
I don't know whether other modules have this bug, but at least according to my tests llama.cpp will no longer have this bug.

Chat mode can work correctly with this fix.

Finally if there is any concerns about my fix please comment on my pull request page.
Thanks for your trust.

**Comment by Foxtr0t1337** [comment]
The newest package fixed the problem and this issue is solved after that.

**Comment by luanshaotong** [comment]
Your fix helped me! Why not merge this PR into the repository?

**Comment by Foxtr0t1337** [comment]
> Your fix helped me! I don‘t think the newest package fixed the problem.

Lol I didn't know that. I am sorry to hear that but my fix didn't use the cache thing so it may not be good. However you are welcome to use my fix anyway or even create your own PR maybe.

I recently didn't use this project so I can't tell if it is still a package problem. 

Maybe you didn't update the package? I saw last time it contains utf8 support.

**Comment by luanshaotong** [comment]
> > Your fix helped me! I don‘t think the newest package fixed the problem.
> 
> Lol I didn't know that. I am sorry to hear that but my fix didn't use the cache thing so it may not be good. However you are welcome to use my fix anyway or even create your own PR maybe.
> 
> I recently didn't use this project so I can't tell if it is still a package problem.
> 
> Maybe you didn't update the package? I saw last time it contains utf8 support.

I use the latest version (0.1.77) of llama-cpp-python to work with model [https://github.com/LinkSoul-AI/Chinese-Llama-2-7b](https://github.com/LinkSoul-AI/Chinese-Llama-2-7b). I didn't meet the decode error, but some characters are missing. Then, I just patch your PR #3108 and it fixed.

**Comment by Foxtr0t1337** [comment]
> > > Your fix helped me! I don‘t think the newest package fixed the problem.
> > 
> > Lol I didn't know that. I am sorry to hear that but my fix didn't use the cache thing so it may not be good. However you are welcome to use my fix anyway or even create your own PR maybe.
> > 
> > I recently didn't use this project so I can't tell if it is still a package problem.
> > 
> > Maybe you didn't update the package? I saw last time it contains utf8 support.
> 
> I used the latest version (0.1.77) of llama-cpp-python to work with model [https://github.com/LinkSoul-AI/Chinese-Llama-2-7b](https://github.com/LinkSoul-AI/Chinese-Llama-2-7b). I didn't meet the decode error, but some characters are missing. Then, I just patched your PR #3108 and it was fixed.
> 
> ![1691381215395](https://github.com/oobabooga/text-generation-webui/assets/14962503/fcb9132e-dbe6-4225-a994-337d138eb5b4)
> ![bU5OeMdetr](https://github.com/oobabooga/text-generation-webui/assets/14962503/01bf2161-c2f9-4cb0-9b7a-132803ba06b3)
> 

I will have a look rn.

**Comment by Foxtr0t1337** [comment]
After some testing I found that the newest package didn't work. So ... lol.

**Comment by oobabooga** [comment]
This is a known issue in llama-cpp-python: https://github.com/abetlen/llama-cpp-python/issues/372

**Comment by luanshaotong** [comment]
@oobabooga I'm not sure if the problem is exactly the same, because in my test results here, the same problem exists even if the streaming mode is turned off. Anyway, I've found a solution that works for my case. thank you for your help.
