### ISSUE TITLE
API always return 0 token in stream mode

### ISSUE THREAD

**Issue by sgsdxzy** [oobabooga/text-generation-webui#311]
### Describe the bug

When --no-stream is not passed, text-generation-webui always generate 0 tokens in 0.00 seconds when accessed by api.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Launch server: `python .\server.py --model llama-13b --gptq-bits 4` (I tried both llama-13b and OPT-6.7B and the bug is the same).
2. Launch TavernAI with support for using text-generation-webui as backend from https://github.com/TavernAI/TavernAI/pull/63
3. Let TavernAI connect to 127.0.0.1:7860 and start to chat.
4. I can see from TavernAI's console that requests are sent correctly. However text-generation-webui's console is filled with `generated 0 tokens in 0.00 seconds`.
5. If I add --no-stream to text-generation-webui's server, it works correctly. But having stream mode in chat is very nice.

### Logs

```shell
python .\server.py --model llama-13b --gptq-bits 4
Loading llama-13b...
Loading model ...
Done.
Loaded the model in 4.68 seconds.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Output generated in 0.18 seconds (0.00 tokens/s, 0 tokens)
Output generated in 0.04 seconds (0.00 tokens/s, 0 tokens)
Output generated in 0.03 seconds (0.00 tokens/s, 0 tokens)
......
```

### System Info

```shell
operating system: Windows 11
GPU: Nvidia RTX 3080Ti
Python: 3.10.8
Pytorch: 1.13.1+cu117
```

**Comment by Gitterman69** [comment]
Getting the same….

**Comment by jordylc1998** [comment]
I'm also getting this

**Comment by hpnyaggerman** [comment]
Same

**Comment by oobabooga** [comment]
The API usage with streaming is different: https://github.com/oobabooga/text-generation-webui/blob/main/api-example-stream.py

This is an issue on the PR code's end and not here.
