### ISSUE TITLE
ggml-vic7b-uncensored-q5_0.bin is working! Query it via http?

### ISSUE THREAD

**Issue by andrewarrow** [oobabooga/text-generation-webui#3136]
Sorry for the newbie question but I'm just so excited to finally see:

https://www.atpeaz.com/run-local-chatgpt-macbook/

this work for me. I went thru so many models that didn't work with python stack trace exception but finally `ggml-vic7b-uncensored-q5_0.bin` worked!

My question is with `oobabooga_macos $ ./start_macos.sh` running on http://127.0.0.1:7860/ is there any api I can hit to get back what is placed in the output textarea as json?

**Comment by toxuin** [comment]
It's right here in the readme: https://github.com/oobabooga/text-generation-webui#api

**Comment by andrewarrow** [comment]
doh! thank u
