### ISSUE TITLE
Add koboldcpp as a loader to Ooba

### ISSUE THREAD

**Issue by rombodawg** [oobabooga/text-generation-webui#3147]
As the title said we absolutely have to add koboldcpp as a loader for the webui. Its got significantly more features and supports more ggml models than base llamacpp. 

Alot of ggml models arent supported right now on text generation web ui because of llamacpp, including models that are based off of starcoder base model like starcoderplus and wizardcoder. But if we added koboldcpp, which for context is a fork of llamacpp with additional features, basically all models would be supported

Here is the repo to koboldcpp
https://github.com/LostRuins/koboldcpp

**Comment by oobabooga** [comment]
ctransformers will be added soon
