### ISSUE TITLE
Elevenlabs_tts extension not importing module when using start-webui.bat Windows

### ISSUE THREAD

**Issue by mynumu** [oobabooga/text-generation-webui#318]
### Describe the bug

The Elevenlabs_tts extension is not loading when using start-webui.bat Windows.

Loading the extension "silero_tts"... Ok.
Loading the extension "llama_prompts"... Ok.
Loading the extension "elevenlabs_tts"... Traceback (most recent call last):
  File "C:\Windows\System32\text-generation-webui\server.py", line 172, in <module>
    extensions_module.load_extensions()
  File "C:\Windows\System32\text-generation-webui\modules\extensions.py", line 12, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\Windows\System32\text-generation-webui\extensions\elevenlabs_tts\script.py", line 4, in <module>
    from elevenlabslib import *
**ModuleNotFoundError: No module named 'elevenlabslib'
Press any key to continue . . .**

Other extensions are working fine. Tested with silero and llama 

Silero and llama tested with calling a single extension as well

I have added my eleven labs api key into the extensions script but still see the same error message above

Thanks

@echo off

@echo Starting the web UI...

set INSTALL_ENV_DIR=%cd%\installer_files\env
set PATH=%INSTALL_ENV_DIR%;%INSTALL_ENV_DIR%\Library\bin;%INSTALL_ENV_DIR%\Scripts;%INSTALL_ENV_DIR%\Library\usr\bin;%PATH%
call conda activate
cd text-generation-webui
call python server.py --auto-devices --cai-chat --extensions silero_tts llama_prompts elevenlabs_tts

pause

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install other extensions and no issues found - webui loads fine
all python server.py --auto-devices --cai-chat --extensions silero_tts llama_prompts elevenlabs_tts

Tested with silero_tss and llama_prompts

all python server.py --auto-devices --cai-chat --extensions silero_tts

imports the module and runs ok

See issue when trying to load eleven labs

echo off

@echo Starting the web UI...

set INSTALL_ENV_DIR=%cd%\installer_files\env
set PATH=%INSTALL_ENV_DIR%;%INSTALL_ENV_DIR%\Library\bin;%INSTALL_ENV_DIR%\Scripts;%INSTALL_ENV_DIR%\Library\usr\bin;%PATH%
call conda activate
cd text-generation-webui
call python server.py --auto-devices --cai-chat --extensions elevenlabs_tts

pause

Starting the web UI...
Loading the extension "elevenlabs_tts"... Traceback (most recent call last):
  File "C:\Windows\System32\text-generation-webui\server.py", line 172, in <module>
    extensions_module.load_extensions()
  File "C:\Windows\System32\text-generation-webui\modules\extensions.py", line 12, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\Windows\System32\text-generation-webui\extensions\elevenlabs_tts\script.py", line 4, in <module>
    from elevenlabslib import *
ModuleNotFoundError: No module named 'elevenlabslib'
Press any key to continue . . .

### Screenshot

echo off

@echo Starting the web UI...

set INSTALL_ENV_DIR=%cd%\installer_files\env
set PATH=%INSTALL_ENV_DIR%;%INSTALL_ENV_DIR%\Library\bin;%INSTALL_ENV_DIR%\Scripts;%INSTALL_ENV_DIR%\Library\usr\bin;%PATH%
call conda activate
cd text-generation-webui
call python server.py --auto-devices --cai-chat --extensions elevenlabs_tts

pause

Starting the web UI...
Loading the extension "elevenlabs_tts"... Traceback (most recent call last):
  File "C:\Windows\System32\text-generation-webui\server.py", line 172, in <module>
    extensions_module.load_extensions()
  File "C:\Windows\System32\text-generation-webui\modules\extensions.py", line 12, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\Windows\System32\text-generation-webui\extensions\elevenlabs_tts\script.py", line 4, in <module>
    from elevenlabslib import *
ModuleNotFoundError: No module named 'elevenlabslib'
Press any key to continue . . .

### Logs

```shell
echo off

@echo Starting the web UI...

set INSTALL_ENV_DIR=%cd%\installer_files\env
set PATH=%INSTALL_ENV_DIR%;%INSTALL_ENV_DIR%\Library\bin;%INSTALL_ENV_DIR%\Scripts;%INSTALL_ENV_DIR%\Library\usr\bin;%PATH%
call conda activate
cd text-generation-webui
call python server.py --auto-devices --cai-chat --extensions elevenlabs_tts


pause

Starting the web UI...
Loading the extension "elevenlabs_tts"... Traceback (most recent call last):
  File "C:\Windows\System32\text-generation-webui\server.py", line 172, in <module>
    extensions_module.load_extensions()
  File "C:\Windows\System32\text-generation-webui\modules\extensions.py", line 12, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "C:\Windows\System32\text-generation-webui\extensions\elevenlabs_tts\script.py", line 4, in <module>
    from elevenlabslib import *
ModuleNotFoundError: No module named 'elevenlabslib'
Press any key to continue . . .
```

### System Info

```shell
Windows 10 installed via the one click installer
Added the API key to the elevenlabs script
```

**Comment by MetaIX** [comment]
It looks like the requirements aren't installed. Try installing the requirements listed in requirements.txt inside elevenlabs_tts folder.

**Comment by oobabooga** [comment]
It's exactly as @MetaIX said. You can install it with this on Linux

`pip install -r extensions/elevenlabs_tts/requirements.txt`

or this on Windows

`pip install -r extensions\elevenlabs_tts\requirements.txt`

You can add this to your install.bat and re-run it, just follow the other examples inside that file.

**Comment by mynumu** [comment]
Hi - my apologies it got flagged as an issue - I tried to troubleshoot the script but didnt realise - rookie mistake! Yes its an install error as I did the one click install rather than manual so didnt spot this. Thanks for taking the time to reply 

Thanks again
