### ISSUE TITLE
Weird behavior after updating/extremely slow generation

### ISSUE THREAD

**Issue by Frog-Lover-Antony** [oobabooga/text-generation-webui#3205]
### Describe the bug

I have been successfully using text-generation-webui since June 11th and have not updated since then.
Yesterday, I updated the webui using update_windows.bat and moved my `models/config-user.yaml` file. Now `Wizard-Vicuna-13B-Uncensored.ggmlv3.q5_1.bin`, `Manticore-13B.ggmlv3.q5_K_M.bin`, `pygmalion-13b.ggmlv3.q5_K_M.bin` and `llama-2-13b.ggmlv3.q5_0.bin` seem to load successfully using the autodetected llama-cpp backend (128 gpu layers), but 4 times faster than before.
I saw 4.7-9.6 tokens/second during generation on the previous version, 10-13% CPU load, 100% GPU load (100% memory controller load, 100% core load, 20-80% bus load).
Now the backend process uses 40-60% cpu 0-100% gpu, during gpu load spikes I can only see (gpu-z) 100% core load, 2% memory controller load, and 0% bus load. I get 0.2-0.8 tokens/second without text streaming. It seems that the backend is doing some weird loops while generating text purely on cpu.

Attempts made to fix the issue: reinstalling webui, rebooting, running with `--auto-devices` `--gpu-memory 11968MiB` `--cpu-memory 0` `--bf16`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Download [one-click-installer](https://github.com/oobabooga/text-generation-webui/releases/download/installers/oobabooga_windows.zip);
2. Unzip downloaded folder;
3. Execute start_windows.bat, wait for it to start the ui and close the console window;
4. Start `cmd_windows.bat`;
5. Paste and run `pip uninstall -y llama-cpp-python && set CMAKE_ARGS="-DLLAMA_CUBLAS=on" && set FORCE_CMAKE=1 && pip install llama-cpp-python --no-cache-dir`, wait for successful re-installation;
6. Move/Link/Copy model files into `text-generation-webui/models/`;
7. Change `webui.py` line 15 to `CMD_FLAGS = '--chat --listen'`;
8. Start `cmd_windows.bat` again, open the webui page in browser;
9. Go to `Model` tab;
10. Click on the dropdown menu, choose `Manticore-13B.ggmlv3.q5_K_M.bin`/(any llama model), wait until the UI displays `Model loader=llama.cpp` and shows settings;
11. Set `n-gpu-layers` to 128, click `Load`;
12. Go to `Text generation` tab, paste `write a story about a sad frog sitting in a puddle on a rainy day` (instruct mode automatically selected);
13. Click `Generate`

Expected result:
  After 2.5 seconds text starts appearing on screen, generating 6-8 tokens/second. GPU utilization is at 100%, CPU utilization at ~10%, RAM usage increases from 6.5 to 8Gb. 

Result:
  After 3 seconds task manager shows spikes in gpu and cpu utilization. After 3+ minutes generated text instantly comes up on screen. Generation won't actually stop upon pressing the stop button even though UI shows that nothing is happening.

### Logs

```shell
bin R:\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
2023-07-19 16:13:58 INFO:Loading the extension "gallery"...
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
2023-07-19 16:14:48 INFO:Loading Manticore-13B.ggmlv3.q5_K_M.bin...
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6
2023-07-19 16:14:49 INFO:llama.cpp weights detected: models\Manticore-13B.ggmlv3.q5_K_M.bin

2023-07-19 16:14:49 INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models\Manticore-13B.ggmlv3.q5_K_M.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 17 (mostly Q5_K - Medium)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 2077.52 MB (+ 1608.00 MB per state)
llama_model_load_internal: allocating batch_size x (640 kB + n_ctx x 160 B) = 480 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 40 repeating layers to GPU
llama_model_load_internal: offloading non-repeating layers to GPU
llama_model_load_internal: offloading v cache to GPU
llama_model_load_internal: offloading k cache to GPU
llama_model_load_internal: offloaded 43/43 layers to GPU
llama_model_load_internal: total VRAM used: 10762 MB
llama_new_context_with_model: kv self size  = 1600.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
2023-07-19 16:14:53 INFO:Loaded the model in 4.87 seconds.


llama_print_timings:        load time = 231058.71 ms
llama_print_timings:      sample time =    29.93 ms /   200 runs   (    0.15 ms per token,  6683.38 tokens per second)
llama_print_timings: prompt eval time = 231058.61 ms /    33 tokens ( 7001.78 ms per token,     0.14 tokens per second)
llama_print_timings:        eval time = 13803.76 ms /   199 runs   (   69.37 ms per token,    14.42 tokens per second)
llama_print_timings:       total time = 245199.02 ms
Output generated in 245.52 seconds (0.81 tokens/s, 200 tokens, context 32, seed 465247203)
Llama.generate: prefix-match hit

llama_print_timings:        load time = 231058.71 ms
llama_print_timings:      sample time =     3.87 ms /    26 runs   (    0.15 ms per token,  6718.35 tokens per second)
llama_print_timings: prompt eval time = 239967.01 ms /   210 tokens ( 1142.70 ms per token,     0.88 tokens per second)
llama_print_timings:        eval time =  1817.25 ms /    25 runs   (   72.69 ms per token,    13.76 tokens per second)
llama_print_timings:       total time = 241825.67 ms
Output generated in 242.13 seconds (0.10 tokens/s, 25 tokens, context 242, seed 635819702)
```

### System Info

```shell
`* Windows 10 Pro 10.0.19045`
`* CUDA 11.8 and 12.3 in PATH`
`* 1-click installer, recompiled llama-cpp without errors`
`* RTX 3060 12G`
`* Ryzen R5 5600`
`* 32Gb ddr4`
`* Running off nvme ssd (1.4G read/write)`
```

**Comment by iibw** [comment]
If you install llama.cpp without GPU acceleration, do things go back to normal? I think that could be your issue.

GGML models use llama.cpp and llama.cpp did not have GPU acceleration by June 11th. You installed it with GPU acceleration here so now it's using your GPU instead of your CPU to run the GGML model.

**Comment by berkut1** [comment]
@iibw I just checked the newest model https://huggingface.co/TheBloke/Llama-2-13B-GGML
And the GPU works wit no issues.
```
2023-07-19 17:49:09 INFO:Loading llama-2-13b.ggmlv3.q6_K.bin...
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 2080, compute capability 7.5
2023-07-19 17:49:10 INFO:llama.cpp weights detected: models\llama-2-13b.ggmlv3.q6_K.bin

2023-07-19 17:49:10 INFO:Cache capacity is 0 bytes
llama.cpp: loading model from models\llama-2-13b.ggmlv3.q6_K.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 4096
llama_model_load_internal: n_embd     = 5120
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 40
llama_model_load_internal: n_layer    = 40
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 18 (mostly Q6_K)
llama_model_load_internal: n_ff       = 13824
llama_model_load_internal: model size = 13B
llama_model_load_internal: ggml ctx size =    0.09 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 7865.51 MB (+ 1608.00 MB per state)
llama_model_load_internal: allocating batch_size x (640 kB + n_ctx x 160 B) = 640 MB VRAM for the scratch buffer
llama_model_load_internal: offloading 18 repeating layers to GPU
llama_model_load_internal: offloaded 18/43 layers to GPU
llama_model_load_internal: total VRAM used: 5108 MB
llama_new_context_with_model: kv self size  = 3200.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
2023-07-19 17:49:14 INFO:Loaded the model in 4.92 seconds.

Output generated in 83.84 seconds (1.60 tokens/s, 134 tokens, context 2063, seed 415569122)
Llama.generate: prefix-match hit
Output generated in 17.78 seconds (2.64 tokens/s, 47 tokens, context 2063, seed 312271115)
Llama.generate: prefix-match hit
Output generated in 49.88 seconds (2.71 tokens/s, 135 tokens, context 2063, seed 1683396371)
```

**Comment by Frog-Lover-Antony** [comment]
@iibw

> If you install llama.cpp without GPU acceleration, do things go back to normal?

If I reinstall llama-cpp-python package, models "load" in half a second. During generation I get 1.3-3.5 tokens/second, 70-80% CPU utilization. `n-gpu-layers` parameter has no effect because llama is not compiled with gpu offloading capabilities.


> llama.cpp did not have GPU acceleration by June 11th

But why did I have to follow the [same recompilation instruction](https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md#gpu-acceleration) and why did it work?

**Comment by Frog-Lover-Antony** [comment]
@berkut1

I did use this model yesterday and I was hoping that an update would make it run better.
You are using mixed inference (18 layes on gpu, 25 on cpu), while I have enough memory to load and run the whole model on the gpu, which gave me 6-8 tokens/second on previous version.

**Comment by Frog-Lover-Antony** [comment]
@berkut1 Thanks! I think I've mostly figured it out!

Model = Llama2-13b
Seed = 1 (responses DID vary a bit)
RAM data: from Task manager python process after execution;
VRAM data: from OpenHardwareMonitor+Task manager after execution;

--
Dialogue (chat):
	1. Hi!
		-"Hi! How can I help?"
	2. Tell me about large language models.
		-"Large language models are artificial intelligence systems that have been trained on massive amounts of text data, such as books, articles, and social media posts. They use this data to learn how to generate natural language responses in a variety of contexts. This technology has made it possible for computers to understand human language better than ever before, which is why they are called “large” models because they can process large amounts of text data quickly and accurately."


10 layers:
	1. 1.33 t/s
	2. 3.48 t/s
	
	6.02GB RAM
	5.0GB VRAM
	70% cpu util
	10-26% gpu util

30 layers:
	1. 3.34 t/s
	2. 6.94 t/s
	
	6.025GB RAM
	9.3GB VRAM
	75-80% cpu util
	40-50% gpu util

40 layers:
	1. 6.21 t/s
	2. 14.74 (!!) t/s
	
	4.993GB RAM
	11.4GB VRAM
	60% cpu util
	90% gpu util

43 layers:
	1. 3.17 t/s
	2. 13.08 t/s
	
	6.207GB RAM
	11.8GB VRAM
	55% cpu util
	95% gpu util
--
As OpenHardwareMonitor says, I've only got 120MB free VRAM left. Which already gets into the OS-reserved space.
I am running out of memory and there's nothing to tell me about it, while loading the model it says `total VRAM used: 10516 MB`, which is sadly not quite true (expected).
So previously the model was constantly moved between CPU and GPU but only the CPU could finish the full turn, while the GPU failed over and over without triggering OOM errors.

**Comment by Frog-Lover-Antony** [comment]
The only thing I still can't understand is why loading 43 layers still makes it run well enough while loading 128 makes it struggle in a loop.

**Comment by berkut1** [comment]
@Frog-Lover-Antony data moving between RAM and VRAM? Are you aware of an issue with Nvidia drivers?https://github.com/LostRuins/koboldcpp/discussions/262

If you're using the latest driver, then it's understandable why you didn't get OOM errors, as there's a silent shift from VRAM to RAM and therefore you lose performance.

**Comment by Frog-Lover-Antony** [comment]
@berkut1 Thank you.
