### ISSUE TITLE
More a question than a feature request. Is there a (“RESTful”) API that we can use instead of the GUI?

### ISSUE THREAD

**Issue by Vincent-Stragier** [oobabooga/text-generation-webui#3219]
Hello,

Is there a (“RESTful”) API that we can use instead of the GUI? If yes, where is the specific documentation, or where should I look?

Kind regards,
Vincent S.

**Comment by deonis1** [comment]
+1

**Comment by toxuin** [comment]
It's right here on the front page's README: https://github.com/oobabooga/text-generation-webui#api

There are also some examples on how to use the API: https://github.com/oobabooga/text-generation-webui/tree/main/api-examples

**Comment by Vincent-Stragier** [comment]
Thanks

**Comment by RageshAntony** [comment]
@Vincent-Stragier 
Also OpenAI APIs also supported 

explore extensions/openai/ folder's readme

**Comment by Vincent-Stragier** [comment]
For reference, I'm using the one click installer with a script to set up the API and a Ngrok tunnel. I installed Ngrok via pip.

```bash
#!/usr/bin/env bash

trap_with_arg() { # from https://stackoverflow.com/a/2183063/804678
  local func="$1"; shift
  for sig in "$@"; do
    trap "$func $sig" "$sig"
  done
}

stop() {
  trap - SIGINT EXIT
  printf '\n%s\n' "received $1, killing child processes"
  kill -s SIGINT 0
}

trap_with_arg 'stop' EXIT SIGINT SIGTERM SIGHUP

export OOBABOOGA_FLAGS="--api --extension api --loader exllama_hf --model  TheBloke_Llama-2-13B-chat-GPTQ --verbose --listen --chat --cpu --auto-devices --disk --max_seq_len 8192 --compress_pos_emb 4"

bash /path/to/oobabooga_linux/start_linux.sh &
sleep 30s
ngrok http --domain=my-ngrok-domain.ngrok-free.app 5000 &

while true; do read; done

```

Then I use `screen` to launch the script in the detached mode:
```bash
# api is the session name, -dm is to start the session in detached mode.
screen -dm -S api bash ~/start_api.sh
```

I can check if the `screen` session is running with:
```bash
screen -ls
```

And I can kill the session using:
```bash
screen -X -S api kill
```

But, I'm still battling with the API on the client side, trying to generate a working prompt…
