### ISSUE TITLE
After a clean WEB UI update the GGML model now 10 times slower for a first response.

### ISSUE THREAD

**Issue by Flanua** [oobabooga/text-generation-webui#3223]
### Describe the bug

After a clean WEB UI update the GGML model (CPU mode) takes now 10 times slower for the first response and slower overall that before. Have no idea what was actually changed in WEB UI but I never waited so long before. Was more than twice as fast before. I'm using my fav Wizard-Vicuna-30B-Uncensored.ggmlv3.q8_0 model.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Launch the WEB UI with Wizard-Vicuna-30B-Uncensored.ggmlv3.q8_0 and type your first question.

### Screenshot

![Screenshot 2023-07-19 042014](https://github.com/oobabooga/text-generation-webui/assets/140022879/30343053-3729-4355-991b-a6ecb29f830e)

### Logs

```shell
None
```

### System Info

```shell
GPU: GTX 980Ti MSI 6G
CPU: i9 9900KS 5GZ
DDR RAM: 128GB DDR4 3200Mhz
```

**Comment by SodaPrettyCold** [comment]
Indeed, luckily I left a backup before updating ......

**Comment by Flanua** [comment]
> Indeed, luckily I left a backup before updating ......

Me too. But I wish they fix it soon.

**Comment by ivnlpz** [comment]
I have also experienced this. Any idea which branch is unaffected?

**Comment by LoganDark** [comment]
Your llama.cpp is being built without GPU support. You can follow the instructions [here](https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md#gpu-acceleration) after entering the conda env to reinstall llama.cpp compiled for CUDA

**Comment by Flanua** [comment]
> Your llama.cpp is being built without GPU support. You can follow the instructions [here](https://github.com/oobabooga/text-generation-webui/blob/main/docs/llama.cpp-models.md#gpu-acceleration) after entering the conda env to reinstall llama.cpp compiled for CUDA

I know I built it intentionally without GPU support (it's GGML model afterall) because I don't have GPU to hold 30B model I have only 6GB ov video memory. I was happy with the speed in my CPU mode before the WEB UI updates..

**Comment by LoganDark** [comment]
@Flanua In my experience that's a mistake because you can still *partially* offload the model to the GPU, and not fill up all your VRAM. The first few layers do make a world of difference. Still though- updating the interface is the only thing you've done? Are you using the exact same model and everything as before?

**Comment by Flanua** [comment]
> In my experience that's a mistake because you can still _partially_ offload the model to the GPU, and not fill up all your VRAM. The first few layers do make a world of difference. Still though- updating the interface is the only thing you've done? Are you using the exact same model and everything as before?

Yes exactly the same model and everything as before thought.

**Comment by LoganDark** [comment]
It could be the newer versions of GGML starting to deprecate the older quantizations - try using the new k-quants? you can download a k-quant version of that model from [here](https://huggingface.co/TheBloke/Wizard-Vicuna-30B-Uncensored-GGML/tree/main) - you want the ones that have "_K", rather than just Q8_0, it'll be something like Q2_K or Q3_K_S and so on. As a bonus, you should *really* build llama.cpp with GPU support and offload *some* layers.

**Comment by Flanua** [comment]
> It could be the newer versions of GGML starting to deprecate the older quantizations - try using the new k-quants? you can download a k-quant version of that model from [here](https://huggingface.co/TheBloke/Wizard-Vicuna-30B-Uncensored-GGML/tree/main) - you want the ones that have "_K", rather than just Q8_0, it'll be something like Q2_K or Q3_K_S and so on. As a bonus, you should _really_ build llama.cpp with GPU support and offload _some_ layers. The first three or so at least are _really_ important.

Ok thank you for telling me about GGML deprecation it might indeed be the case I will definitely try to download some with _K.. Not sure what exactly to start downloading there is a lot of files with K but I will try.

**Comment by LoganDark** [comment]
> Not sure what exactly to start downloading there is a lot of files with K

The smaller ones will be able to fit more layers on GPU, if you want speed, you will want those ones. You want to maximize the number of layers on GPU, even if you can't quite fit all of them. That's how you make it fast.

**Comment by Flanua** [comment]
The problem is I don't want to download model with lover q8_0 number tho the model quality will degrade most probably.

**Comment by LoganDark** [comment]
> The problem is I don't want to download model with lover q8_0 number tho the model quality will degrade most probably.

It's a 30B model. People have crunched LLaMA down to 2-bits without significantly quality loss. Considering the Q2_K quant is actually around 2.875 bits per weight, you're not even going down that low.

Regardless, you won't know until you try.

**Comment by Flanua** [comment]
I might try just to see but it's still a problem with WEB UI update so hope it to be fixed soon because I'm more than sure the model will degrade with lower Fpoint numbers and quantization the model became especially bad at math calculations and coding and other stuff.

**Comment by LoganDark** [comment]
> it's still a problem with WEB UI update

I think there's no way to know for sure unless you still have your old configuration laying around or can downgrade the repository to see if older versions are still faster.

**Comment by Flanua** [comment]
> > it's still a problem with WEB UI update
> 
> I think there's no way to know for sure unless you still have your old configuration laying around or can downgrade the repository to see if older versions are still faster.

I have a copy so the old version definitely faster on older version I don't need to wait 25 min for the first response I usually wait around 5 min on older.

**Comment by LoganDark** [comment]
I'm a bit astonished that you're even putting up with 5 minutes per response because I get around 30 tokens per second...

**Comment by Flanua** [comment]
> I'm a bit astonished that you're even putting up with 5 minutes per response because I get around 30 tokens per second...

Only first response takes 5 min after that I having 25-30 tokens per response.

**Comment by LoganDark** [comment]
It takes me about 7.4 seconds to generate 200 tokens, so even the older build of yours is somewhat suspiciously slow.

Are you sure the k-quants don't help? Partial GPU offload doesn't either?

**Comment by Flanua** [comment]
> It takes me about 7.4 seconds to generate 200 tokens, so even the older build of yours is somewhat suspiciously slow, even for a 30B.
> 
> Are you sure the k-quants don't help? Partial GPU offload doesn't either?

I can only make CPU mode worjig if I built WEB UI without GPU support. And as I said I was ok with the speed in CPU mode it was pretty fast.

**Comment by LoganDark** [comment]
> I can only make CPU mode worjig if I built WEB UI without GPU support.

This confuses me. Are you saying you specifically selected the no-GPU option *when installing the web UI*? Like, on the menu where it asks you what kind of GPU you have?

**Comment by Flanua** [comment]
> > I can only make CPU mode worjig if I built WEB UI without GPU support.
> 
> This confuses me. Are you saying you specifically selected the no-GPU option _when installing the web UI_? Like, on the menu where it asks you what kind of GPU you have?

Yes.

**Comment by LoganDark** [comment]
And you installed the older version in the exact same way as well?

Keep in mind, selecting the nvidia option does not affect how llama.cpp is built. There is obviously something else wrong with your computer if that fails to work properly, because llama.cpp should still be performing CPU inference by default.

**Comment by LoganDark** [comment]
I don't think your computer is necessarily the cause of the sudden slowness here, but if you can try to locate a specific commit that caused the issue, that would be helpful.

**Comment by Flanua** [comment]
> And you installed the older version in the exact same way as well?
> 
> Keep in mind, selecting the nvidia option does not affect how llama.cpp is built. There is obviously something else wrong with your computer if that fails to work properly, because llama.cpp should still be performing CPU inference by default.

Maybe it can with fresh update but I remember was unable to make it work on older versions.

**Comment by Flanua** [comment]
> I don't think your computer is necessarily the cause of the sudden slowness here, but if you can try to locate a specific commit that caused the issue, that would be helpful.

The only way I can help is to upload the older build that I still have as a backup. So comparison could be done against the fresh version.

**Comment by Flanua** [comment]
I updated Oobabooga Web UI on Friday, 25 August 2023 and it even faster now than the older build it seems. So finally after this new updated changes in the code everything is running as it should. Not gonna lie I waited a long time for this to be fixed.
![Screens](https://github.com/oobabooga/text-generation-webui/assets/140022879/9b3128f1-86e9-4286-a12b-b8a5caba9927)
