### ISSUE TITLE
OpenAI Extension: InvalidRequestError.__init__() missing 1 required positional argument: 'param'

### ISSUE THREAD

**Issue by chigkim** [oobabooga/text-generation-webui#3228]
### Describe the bug

When trying to communicate via OpenAI Extension API, I get the error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Run the server with OpenAI extension
2. Send a message via OpenAI API

### Screenshot

N/A

### Logs

```shell
Traceback (most recent call last):
  File "/content/text-generation-webui/extensions/openai/script.py", line 95, in wrapper
    func(self)
  File "/content/text-generation-webui/extensions/openai/script.py", line 169, in do_POST
    response = OAIcompletions.chat_completions(body, is_legacy=is_legacy)
  File "/content/text-generation-webui/extensions/openai/completions.py", line 252, in chat_completions
    prompt, token_count = messages_to_prompt(body, req_params, max_tokens)
  File "/content/text-generation-webui/extensions/openai/completions.py", line 218, in messages_to_prompt
    raise InvalidRequestError(message=err_msg)
TypeError: InvalidRequestError.__init__() missing 1 required positional argument: 'param'
```

### System Info

```shell
Colab
```

**Comment by matatonic** [comment]
Sorry for any inconvenience this may have caused, this is fixed in https://github.com/oobabooga/text-generation-webui/pull/3122

**Comment by matatonic** [comment]
You are probably sending a message that is too large however, that error is from an error message (an error in the error handler).

**Comment by chigkim** [comment]
The PR worked. I guess wait to be merged.

**Comment by atisharma** [comment]
I'm also getting this error, looking forward to the merge.

**Comment by chigkim** [comment]
Is the PR merged? If so, should we close this?

**Comment by matatonic** [comment]
> Is the PR merged? If so, should we close this?

Yes it was, you can close it, thanks!
