### ISSUE TITLE
Getting this error installing the text generation webui

### ISSUE THREAD

**Issue by dachstheo** [oobabooga/text-generation-webui#3244]
### Describe the bug

ERROR: Wheel 'ffmpy' located at C:\users\timor\appdata\local\pip\cache\wheels\01\a6\d1\1c0828c304a4283b2c1639a09ad86f83d7c487ef34c6b4a1bf\ffmpy-0.3.1-py3-none-any.whl is invalid.
Command '"C:\tg\oobabooga_windows\installer_files\conda\condabin\conda.bat" activate "C:\tg\oobabooga_windows\installer_files\env" >nul && python -m pip install -r requirements.txt --upgrade' failed with exit status code '1'. Exiting...
Drücken Sie eine beliebige Taste . . .

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Hi ,
tried to install it manually with Anaconda and with  the automatic installer , but either way it aborts stating this issue:

ERROR: Wheel 'ffmpy' located at C:\users\timor\appdata\local\pip\cache\wheels\01\a6\d1\1c0828c304a4283b2c1639a09ad86f83d7c487ef34c6b4a1bf\ffmpy-0.3.1-py3-none-any.whl is invalid.
Command '"C:\tg\oobabooga_windows\installer_files\conda\condabin\conda.bat" activate "C:\tg\oobabooga_windows\installer_files\env" >nul && python -m pip install -r requirements.txt --upgrade' failed with exit status code '1'. Exiting...
Drücken Sie eine beliebige Taste . . . [ translation: push any key ...... }

### Logs

```shell
ERROR: Wheel 'ffmpy' located at C:\users\timor\appdata\local\pip\cache\wheels\01\a6\d1\1c0828c304a4283b2c1639a09ad86f83d7c487ef34c6b4a1bf\ffmpy-0.3.1-py3-none-any.whl is invalid.
Command '"C:\tg\oobabooga_windows\installer_files\conda\condabin\conda.bat" activate "C:\tg\oobabooga_windows\installer_files\env" >nul && python -m pip install -r requirements.txt --upgrade' failed with exit status code '1'. Exiting...
Drücken Sie eine beliebige Taste . . .
```

### System Info

```shell
Ryzen 2700X
16 gig ram
RTX 2080
```

**Comment by AntonioZC666** [comment]
Hello, do you have solved this problem? I met a similar problem.

**Comment by Triq1** [comment]
+1 here
