### ISSUE TITLE
Maintain conversation history beyond context using faiss index queries

### ISSUE THREAD

**Issue by thistleknot** [oobabooga/text-generation-webui#3264]
**Description**

Leverage langchain's message_history, and faiss indexing to track message history outside of context length.

**Additional Context**

There is no need to setup an external database.  This could all be done within current session.  Faiss index's by default fall back on a local file.  This file could be checked if it exists, and load it, else start a new one (maybe an input paramter in the ui to specify the name of a file to load).

Check out
https://archive.is/wip/ZEelb

I will be working on an implementation using your API, and once I have it 'gist' ready, I'll parse the code here.

**Comment by Flanua** [comment]
Sounds like a very good idea like a long term memory for AI outside of context length. Not sure how good it will work in reality though but would be nice to see something like that being implemented.

**Comment by thistleknot** [comment]
There is an extension called long term memory that already does this
https://github.com/wawawario2/long_term_memory/
