### ISSUE TITLE
This doesnt support quantised LLaMA models

### ISSUE THREAD

**Issue by Urammar** [oobabooga/text-generation-webui#329]
### Describe the bug

https://github.com/ggerganov/llama.cpp is, I strongly believe, a turning point for language models and the democratization of frontier AI language models, running locally on attainable consumer hardware.

After the quantization step (found under usage in this guide), the model is shrunk significantly in size, the 7b model from 13g to 4g, with similarly down-scaling ram requirements, and able to be inferenced in realtime sub 100ms per token on CPU, a significant statement and shift.

This web-ui is unable to parse these quantized .bin models, complaining that no config.json exists for the, alongside other issues.

`OSError: models\7B does not appear to have a file named config.json. Checkout 'https://huggingface.co/models\7B/None' for available files.`

`OSError: Unable to load weights from pytorch checkpoint file for 'models\7B\pytorch_model.bin' at 'models\7B\pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.`

This is a pretty massive oversight for the auto1111 of language models

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Quantize LLama-7b model and attempt to load it

### System Info

```shell
This isnt relevant. High end gaming hardware.
```

**Comment by oobabooga** [comment]
Yes it does 

https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model
