### ISSUE TITLE
Openai Batched generation 

### ISSUE THREAD

**Issue by Zoraman26** [oobabooga/text-generation-webui#3296]
**Description**

Batched API openai extension

![image](https://github.com/oobabooga/text-generation-webui/assets/88414058/af24f00b-dfde-4278-a04a-218079932a79)

**Comment by matatonic** [comment]
On my radar, I'll bump it up the priority list.

**Comment by matatonic** [comment]
> > On my radar, I'll bump it up the priority list.
> 
> Thanks a ton!

You can try it out in the PR here: https://github.com/oobabooga/text-generation-webui/pull/3309

**Comment by matatonic** [comment]
> > > > On my radar, I'll bump it up the priority list.
> > > 
> > > 
> > > Thanks a ton!
> > 
> > You can try it out in the PR here: #3309
> 
> Seems to work, new error unrelated to api support pretty sure its because of the way OpenDex works, my AI server isn't poweful enough to run models with a larger context size
> 
> Any models that have ~3500 context size and can be run in 12gb vram or 64gb main pool ram?
> 

The 13B llama-2 based (l2) models have a 4K context, and should just fit in around 12G. TheBloke has a few already. 


Matthew.
