### ISSUE TITLE
Large models won't load.

### ISSUE THREAD

**Issue by Ph0rk0z** [oobabooga/text-generation-webui#33]
Neither GPT-4chan or GPT-j-6b load on this UI. They load into kobold just fine. I have about 24gb of vram.

I get this error:

```
"/home/mint/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/gpt2/tokenization_gpt2.py", line 192, in __init__
    with open(merges_file, encoding="utf-8") as merges_handle:
TypeError: expected str, bytes or os.PathLike object, not NoneType


```

**Comment by oobabooga** [comment]
Did you install the requirements as written in the README?

**Comment by Ph0rk0z** [comment]
I hope so because I can load pygmalion but not these other larger models.

**Comment by Ph0rk0z** [comment]
Well you do know that I did run all of this:

```
conda create -n textgen
conda activate textgen
conda install torchvision torchaudio pytorch-cuda=11.7 git -c pytorch -c nvidia
git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui
pip install -r requirements.txt
```

The large models load for kobold/tavern.

**Comment by oobabooga** [comment]
Can you try deleting the model and downloading it again using  the `python download-model.py` script? It seems like it could be corrupt.

**Comment by Ph0rk0z** [comment]
Sure.. I just don't think they're corrupt because they generate fine on kobold. It's like something is wrong with the environment. 

The loading here is also different in that it uses more memory initially. The convert to pytorch script gave me similar errors or just run out of memory completely. Maybe 32gb isn't enough and I should buy more.

**Comment by athu16** [comment]
I'm having the exact same issue. Did you find any solution for it?

**Comment by Ph0rk0z** [comment]
I figured this out. merges.txt is required for the tokenizer on gpt2 based models.
