### ISSUE TITLE
GGML model does not offload to GPU, offloaded layers count glitches out

### ISSUE THREAD

**Issue by space-nuko** [oobabooga/text-generation-webui#3312]
### Describe the bug

I can't seem to get a GGML model to offload to GPU (I haven't tried other model types yet)
I have 24GB of VRAM available but it only ever uses ~700MB. Plus the number of offloaded layers is bugged.
Could it have to do with CUDA?

```
llama_model_load_internal: offloading -1530494976 repeating layers to GPU
llama_model_load_internal: offloaded -1530494976/63 layers to GPU
llama_model_load_internal: total VRAM used: 592 MB
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load a GGML model through the webui

### Logs

```shell
$ python server.py --model-dir /g/model/textgen --n-gpu-layers 128 --api --gpu-memory 22
bin E:\build\text-generation-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
Starting streaming server at ws://127.0.0.1:5005/api/v1/stream
Starting API at http://127.0.0.1:5000/api
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-07-25 22:03:11 INFO:Loading 30B-Lazarus-GGML...
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6
2023-07-25 22:03:13 INFO:llama.cpp weights detected: G:\model\textgen\30B-Lazarus-GGML\30b-Lazarus.ggmlv3.q5_K_M.bin

2023-07-25 22:03:13 INFO:Cache capacity is 0 bytes
llama.cpp: loading model from G:\model\textgen\30B-Lazarus-GGML\30b-Lazarus.ggmlv3.q5_K_M.bin
llama_model_load_internal: format     = ggjt v3 (latest)
llama_model_load_internal: n_vocab    = 32000
llama_model_load_internal: n_ctx      = 2048
llama_model_load_internal: n_embd     = 6656
llama_model_load_internal: n_mult     = 256
llama_model_load_internal: n_head     = 52
llama_model_load_internal: n_head_kv  = 52
llama_model_load_internal: n_layer    = 60
llama_model_load_internal: n_rot      = 128
llama_model_load_internal: n_gqa      = 1
llama_model_load_internal: rnorm_eps  = 1.0e-06
llama_model_load_internal: n_ff       = 17920
llama_model_load_internal: freq_base  = 10000.0
llama_model_load_internal: freq_scale = 1
llama_model_load_internal: ftype      = 17 (mostly Q5_K - Medium)
llama_model_load_internal: model size = 30B
llama_model_load_internal: ggml ctx size =    0.16 MB
llama_model_load_internal: using CUDA for GPU acceleration
llama_model_load_internal: mem required  = 22610.91 MB (+ 3120.00 MB per state)
llama_model_load_internal: offloading -1530494976 repeating layers to GPU
llama_model_load_internal: offloaded -1530494976/63 layers to GPU
llama_model_load_internal: total VRAM used: 592 MB
llama_new_context_with_model: kv self size  = 3120.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | VSX = 0 |
2023-07-25 22:03:26 INFO:Loaded the model in 14.93 seconds.
```

### System Info

```shell
NVIDIA RTX 3090
Windows Server 2022
```

**Comment by Flanua** [comment]
Did you tried to lower the layers to let's say --n-gpu-layers 64 ? And if you did, does the vram usage increased or decreased? Just trying to gather more information so it would be easier to figured out what is wrong.

**Comment by space-nuko** [comment]
Yes, I tried 64, 128 and a large number like 100000 but it doesn't change anything about VRAM usage

**Comment by Flanua** [comment]
Try to add --pre_layer 32 (or 64) (after CMD_FLAGS =) in your webui.py file that definitely should start to use your vram..

**Comment by space-nuko** [comment]
I'm confused, I don't have a `webui.py` in my checkout of the repo and I can't find it through code search in this repo either?

I added `--pre_layer` like you said and it works now, I guess I'm confused why there's also a `--n-gpu-layers` setting that doesn't seem to do anything. Could it be a documentation issue?

**Comment by Flanua** [comment]
> I'm confused, I don't have a `webui.py` in my checkout of the repo and I can't find it through code search in this repo either?
> 
> I added `--pre_layer` like you said and it works now, I guess I'm confused why there's also a `--n-gpu-layers` setting that doesn't seem to do anything. Could it be a documentation issue?

might be a documentation issue it was changed recently but hard to tell but --n-gpu-layers a bit different from --pre_layer so I glad it now works for you now if your issue is solved feel free to change the status to solved... I will attach my old webui.py file for you to download just in case. Y
[webui.zip](https://github.com/oobabooga/text-generation-webui/files/12186865/webui.zip)
ou can edit it how you like.

**Comment by Avodey** [comment]
Do you have an up to date version of this? or just a fix, I'm getting the same issue when it comes to GGML models where the ctx size is 0.16mb and responses are infinite
