### ISSUE TITLE
OpenAI extension message length issue

### ISSUE THREAD

**Issue by drexample** [oobabooga/text-generation-webui#3355]
### Describe the bug

![image](https://github.com/oobabooga/text-generation-webui/assets/19371983/bd6601dc-0f46-413d-a36f-d14ed1bb3d21)

This is displayed as a warning, despite generation not going through/no message being returned.

I have modified shared.py to have the truncation length be 8000, but nothing else.
No other errors are visible. After resetting convo the error returns with much smaller context.

![image](https://github.com/oobabooga/text-generation-webui/assets/19371983/03523bc9-69c2-4dc9-8636-3e54d7206379)

Couldn't be OOM either, the VRAM has good 5 gigs free.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Running FreeWilly2 GPTQ from Bloke's main branch.
Exllama_HF, context length is at 8k, compression is alpha at 4.

### Logs

```shell
None except for previously shown screenshots.
```

### System Info

```shell
Vast AI, A6000 48 GB, Xeon® E5-2683 v4, 64 gigs of RAM
```

**Comment by matatonic** [comment]
This message is shown as a warning but it should not stop generation, perhaps there is another reason you are not getting data back?

You have a problem with your settings however, I think you misunderstand how max_tokens is supposed to be used, it reserves context for token generation. If you want to allow all remaining space for generation (which seems to be the case with 8000 as the setting), just stop setting it and it will default to all remaining space.

See here for specifics on how it's used: https://platform.openai.com/docs/api-reference/chat/create#chat/create-max_tokens

> max_tokens integer Optional Defaults to inf
> The maximum number of tokens to generate in the chat completion.
> 
> The total length of input tokens and generated tokens is limited by the model's context length. Example Python code for counting tokens.


For the completions interface the message is a bit clearer:

> The token count of your prompt plus max_tokens cannot exceed the model's context length. Example Python code for counting tokens.

My advice if you're not trying to limit it is just remove it and the warning will go away and all context will be available.

**Comment by drexample** [comment]
Thank you for the reply. I was unable to reproduce the error after a reboot, and also thank you for the clarification on max tokens. 
Haven't encountered the generation issue (or anyone else experiencing it) so I'm closing this.
