### ISSUE TITLE
Saving your name at least?

### ISSUE THREAD

**Issue by Ph0rk0z** [oobabooga/text-generation-webui#338]
**Description**

Gradio UI refreshes to defaults when reloaded. Some kind of persistence would be nice, at least for name. I am simply getting tired of replacing "person 1" with something else. Even a generic "you" would be good.

Perhaps it would be good to use a cookie to save at least some parameters that are generic.

**Comment by oobabooga** [comment]
It is possible to do this by copying settings-template.json to settings.json, making your edits, and restarting the web ui.

**Comment by Ph0rk0z** [comment]
TIL. This will solve the problem of git complaining if I do a pull. I also see those parameters in shared.py. 
When I was looking at that yesterday I noticed it was out of sync with what was in there.
