### ISSUE TITLE
Consider adding Superlinter and pre-commit hooks to this repository

### ISSUE THREAD

**Issue by Vincent-Stragier** [oobabooga/text-generation-webui#3402]
Hello,

The codebase is not watched carefully, while a lot of good code is present in this repo, some obvious bad code practices are present… like (disclaimer, it's not the original code, since I ran a formatter, but the main errors are still present):

![Example of bad code practices.](https://github.com/oobabooga/text-generation-webui/assets/28227183/49ede137-3b18-44f7-9d09-acec86ea2138)

You could add Superlinter to analyse the codebase automatically via a GitHub Action, like this one, [linter.yml](https://github.com/Vincent-Stragier/text-generation-webui/blob/main/.github/workflows/linter.yml).

Additionally, you could ask the contributors to run pre-commit hooks. Using the Python package `precommit`, it is simple to install locally and run these hooks.

You must just add [.pre-commit-config.yaml](https://github.com/Vincent-Stragier/text-generation-webui/blob/main/.pre-commit-config.yaml) at the root of the repository. Furthermore, you can add configuration files for each hook, like [.flake8](https://github.com/Vincent-Stragier/text-generation-webui/blob/main/.flake8) for flake8, [.isort.cfg](https://github.com/Vincent-Stragier/text-generation-webui/blob/main/.isort.cfg) for isort or [pyproject.toml](https://github.com/Vincent-Stragier/text-generation-webui/blob/main/pyproject.toml) for black.

Kind regards,
Vincent S.

**Comment by oobabooga** [comment]
The repository is already linted

**Comment by Vincent-Stragier** [comment]
@oobabooga with which tool?
