### ISSUE TITLE
Are k-quant quantisation methods compatible with text-generation-webui?

### ISSUE THREAD

**Issue by 8ullyMaguire** [oobabooga/text-generation-webui#3438]
I've just read this

> New k-quant methods: q2_K, q3_K_S, q3_K_M, q3_K_L, q4_K_S, q4_K_M, q5_K_S, q6_K
>
> These new quantisation methods are only compatible with llama.cpp as of June 6th, commit 2d43387.
> 
> They will NOT be compatible with koboldcpp, text-generation-ui, and other UIs and libraries yet.

Can I only use this quantisations on webui?

> Original llama.cpp quant methods: q4_0, q4_1, q5_0, q5_1, q8_0

Or can I use the new k-quant methods?

**Comment by oobabooga** [comment]
Yes, just load them though the llama.cpp or llamacpp_HF loaders.
