### ISSUE TITLE
Add numa support when using llama.cpp

### ISSUE THREAD

**Issue by rankaiyx** [oobabooga/text-generation-webui#3444]
**Description**

The numa feature of llama.cpp does not seem to be supported, resulting in significant performance degradation on servers with multiple numa nodes.

Without numa enabled, when I loaded the model, memory was allocated to only one node, so that the bandwidth of all memory channels could not be utilized.
![image](https://github.com/oobabooga/text-generation-webui/assets/39045067/6c9bee9d-2e1c-4a65-a381-31a499085362)
![image](https://github.com/oobabooga/text-generation-webui/assets/39045067/278bc2f3-01cd-46f6-91e0-81174bb2d0d6)

For comparison, this is the performance with numa support enabled:
![image](https://github.com/oobabooga/text-generation-webui/assets/39045067/e3442259-2b40-4525-80c3-ae82d497114c)

Memory allocation is balanced on all nodes:
![image](https://github.com/oobabooga/text-generation-webui/assets/39045067/700c822c-119d-4aab-8169-e436afba9292)

**Additional Context**

NUMA support
--numa: Attempt optimizations that help on some systems with non-uniform memory access. This currently consists of pinning an equal proportion of the threads to the cores on each NUMA node, and disabling prefetch and readahead for mmap. The latter causes mapped pages to be faulted in on first access instead of all at once, and in combination with pinning threads to NUMA nodes, more of the pages end up on the NUMA node where they are used. Note that if the model is already in the system page cache, for example because of a previous run without this option, this will have little effect unless you drop the page cache first. This can be done by rebooting the system or on Linux by writing '3' to '/proc/sys/vm/drop_caches' as root.

https://github.com/ggerganov/llama.cpp/blob/master/examples/main/README.md

**Comment by StoyanStAtanasov** [comment]
So let's do some activity at Support for NUMA abetlen/llama-cpp-python#571

**Comment by StoyanStAtanasov** [comment]
I have created a pull request https://github.com/abetlen/llama-cpp-python/pull/704 (hopefully) implementing the parameter. Is it a lot of work to implement it here?

**Comment by rankaiyx** [comment]
great! llama-cpp-python has merged your pull. Now it has released the latest version that supports numa.

**Comment by StoyanStAtanasov** [comment]
I guess when they saw how naive my implementation was, they had to do it 😁. Maybe I should create a pull request here as well 😜

**Comment by rankaiyx** [comment]
😁
