### ISSUE TITLE
Trying to load 70b llama2 GGML :: Init Assert Self.Model is not None AssetionError

### ISSUE THREAD

**Issue by BracerJack** [oobabooga/text-generation-webui#3454]
### Describe the bug

![qqqqqqqqqqqqqqqqqqqq](https://github.com/oobabooga/text-generation-webui/assets/46036208/b63d8d0f-6b54-4855-b993-6e9e46172cfe)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Running on CPU, not GPU, ram = 32.
Trying to run the most minimum: llama2_70b_chat_uncensored.ggmlv3.q2_K.bin

### Logs

```shell
Is this a ram issue ?
```

### System Info

```shell
Or I missed a step.
```

**Comment by Flanua** [comment]
Just my two cents: My GGML 30B model overall required 44GB of ddr ram. You are using 70B model with only 32GB of ddr ram. Your Windows will use a swap page file for sure,

**Comment by BracerJack** [comment]
I appreciate your two cents Flanua, because I have no idea what I am doing so I appreciate your education :-)

**Comment by BracerJack** [comment]
Looks like it is just a matter of not enough Ram :D

**Comment by nuttintoseehere** [comment]
I get the same error with 64GB RAM. Tried updating first, then a fresh reinstall. No change. Same model too, TheBloke's llama2 chat uncensored. What can i do?
