### ISSUE TITLE
Installation instructions broken, possibly by new torchvision and torchaudio audio releases

### ISSUE THREAD

**Issue by MrCheeze** [oobabooga/text-generation-webui#347]
### Describe the bug

Following the current readme instructions leads to a python setup where torch.cuda.is_available() is False. Pip also prints a warning about torch version conflicts between 0.13 and 2.0, although I don't have the log anymore.

I suspect this was caused by the release of torchaudio 2.0 and torchvision 0.15 a few hours ago as of writing, since the install command doesn't specify a version for them.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
conda create -n textgen
conda activate textgen
conda install torchvision torchaudio pytorch-cuda=11.7 git -c pytorch -c nvidia
git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui
pip install -r requirements.txt
```

### Logs

Lost the logs, but there was:
1) A warning from pip that something required pytorch 0.13 and something required pytorch 2.0
2) A wording from text-generation-webui that cuda isn't available

### System Info

```shell
Windows 11
GTX 1660
```

**Comment by oobabooga** [comment]
Can you check if this works?

```
conda install torchvision=0.14.1 torchaudio=0.13.1 pytorch-cuda=11.7 git -c pytorch -c nvidia
```

**Comment by MrCheeze** [comment]
It does!

**Comment by oobabooga** [comment]
Great! Thanks for the information, I would never have found out about this on my own.

I have updated the one-click installers (https://github.com/oobabooga/one-click-installers) and the README to install those specific versions.

**Comment by Olivya-diff** [comment]
The same issue is in "one-cllick-installers" for AMD version.
