### ISSUE TITLE
Ooba failing to load Multiple GGML models using llamacpp due to unexpected keyword argument 'n_gqa'

### ISSUE THREAD

**Issue by bangkokpadang** [oobabooga/text-generation-webui#3485]
### Describe the bug

EDIT: It looks like someone else posted about this same issue while I was writing this out. My apologies for listing a duplicate issue, but i'll leave it up in case it helps pin it down. This is my first time reporting an issue so I'm not 100% sure on the etiquette. 

Ooba fails to load multiple GGML models using llamacpp (including previously known working models), indicating 'TypeError: Llama.init() got an unexpected keyword argument ‘n_gqa’'

stemming from line 74 of llamacpp_model.py

In the webui, n_gqa is set to zero, but I tried it with various values, from 1 to 8. My research indicates only llama2-70B based models use GQA (as far as llama 2 models that is.) so 0 should be the correct value for these models.

Replicated using TheBloke's chronos-hermes-13b-v2.ggmlv3.q6_K.bin and nous-hermes-llama2-13b.ggmlv3.q5_K_M.bin (the second of which has been known to work as of a few days ago).

I'm using TheBloke's DockerLLM on runpod, and I even tried starting a brand new pod. My understanding is that he has it built in a way that *should* update ooba on startup and on subsequent launches.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Occurs when attempting to load GGML models in text-generation-webui via llamacpp

### Logs

```shell
Traceback (most recent call last):

File “/workspace/text-generation-webui/modules/ui_model_menu.py”, line 179, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File “/workspace/text-generation-webui/modules/models.py”, line 78, in load_model

output = load_func_map[loader](model_name)
File “/workspace/text-generation-webui/modules/models.py”, line 241, in llamacpp_loader

model, tokenizer = LlamaCppModel.from_pretrained(model_file)
File “/workspace/text-generation-webui/modules/llamacpp_model.py”, line 74, in from_pretrained

result.model = Llama(**params)
TypeError: Llama.init() got an unexpected keyword argument ‘n_gqa’
```

### System Info

```shell
using thebloke's dockerLLM on runpod with an nvidia A6000 GPU
```

**Comment by lobabobloblaw** [comment]
Also getting this on TheBloke/Llama-2-7B-Chat-GGML:

```
Traceback (most recent call last):

File “/workspace/text-generation-webui/modules/ui_model_menu.py”, line 179, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File “/workspace/text-generation-webui/modules/models.py”, line 78, in load_model

output = load_func_map[loader](model_name)
File “/workspace/text-generation-webui/modules/models.py”, line 241, in llamacpp_loader

model, tokenizer = LlamaCppModel.from_pretrained(model_file)
File “/workspace/text-generation-webui/modules/llamacpp_model.py”, line 74, in from_pretrained

result.model = Llama(**params)
TypeError: Llama.init() got an unexpected keyword argument ‘n_gqa’
```

**Comment by thistleknot** [comment]
super annoying.  I got the model to load on localAI, but it won't load in text-generation-webui

**Comment by thistleknot** [comment]
pip install ctransformers (I saw ctransformers listed on hf model repo page, but I saw saw ctransformers mentioned in a support request for ggml 2 weeks ago by ooba).  Works now

**Comment by bangkokpadang** [comment]
I just wanted to close this issue out. It wasn't really an issue with llamacpp. I was updating ooba with `git pull` from the `text-generation-webui` but was not updating the `requirements.txt` first.

The solution was simply to SSH into my pod, change into the text-generation-webui with `cd /workspace/text-generation-webui` and update the requirements with`pip install -r requirements.txt --upgrade` and it installed the latest versions of llamacpp, llama-cpp-python, and llama_cpp_cuda which fixed the issue entirely.
