### ISSUE TITLE
Please add the --rope_freq_scale switch 

### ISSUE THREAD

**Issue by apcameron** [oobabooga/text-generation-webui#3489]
This switch is used by llama-cpp-python and is needed to get some models to work correctly.
Without it these models do not work.

See Switches below
<pre>usage: __main__.py [-h] [--model MODEL] [--model_alias MODEL_ALIAS]
                   [--n_ctx N_CTX] [--n_gpu_layers N_GPU_LAYERS]
                   [--tensor_split TENSOR_SPLIT]
                   [--rope_freq_base ROPE_FREQ_BASE]
                   [--rope_freq_scale ROPE_FREQ_SCALE] [--seed SEED]
                   [--n_batch N_BATCH] [--n_threads N_THREADS]
                   [--f16_kv F16_KV] [--use_mlock USE_MLOCK]
                   [--use_mmap USE_MMAP] [--embedding EMBEDDING]
                   [--low_vram LOW_VRAM]
                   [--last_n_tokens_size LAST_N_TOKENS_SIZE]
                   [--logits_all LOGITS_ALL] [--cache CACHE]
                   [--cache_type CACHE_TYPE] [--cache_size CACHE_SIZE]
                   [--vocab_only VOCAB_ONLY] [--verbose VERBOSE] [--host HOST]
                   [--port PORT] [--interrupt_requests INTERRUPT_REQUESTS]
                   [--n_gqa N_GQA] [--rms_norm_eps RMS_NORM_EPS]

options:
  -h, --help            show this help message and exit
  --model MODEL         The path to the model to use for generating
                        completions. (default: PydanticUndefined)
  --model_alias MODEL_ALIAS
                        The alias of the model to use for generating
                        completions.
  --n_ctx N_CTX         The context size. (default: 2048)
  --n_gpu_layers N_GPU_LAYERS
                        The number of layers to put on the GPU. The rest will
                        be on the CPU. (default: 0)
  --tensor_split TENSOR_SPLIT
                        Split layers across multiple GPUs in proportion.
  --rope_freq_base ROPE_FREQ_BASE
                        RoPE base frequency (default: 10000)
  --rope_freq_scale ROPE_FREQ_SCALE
                        RoPE frequency scaling factor (default: 1.0)
  --seed SEED           Random seed. -1 for random. (default: 1337)
  --n_batch N_BATCH     The batch size to use per eval. (default: 512)
  --n_threads N_THREADS
                        The number of threads to use. (default: 2)
  --f16_kv F16_KV       Whether to use f16 key/value. (default: True)
  --use_mlock USE_MLOCK
                        Use mlock. (default: True)
  --use_mmap USE_MMAP   Use mmap. (default: True)
  --embedding EMBEDDING
                        Whether to use embeddings. (default: True)
  --low_vram LOW_VRAM   Whether to use less VRAM. This will reduce
                        performance. (default: False)
  --last_n_tokens_size LAST_N_TOKENS_SIZE
                        Last n tokens to keep for repeat penalty calculation.
                        (default: 64)
  --logits_all LOGITS_ALL
                        Whether to return logits. (default: True)
  --cache CACHE         Use a cache to reduce processing times for evaluated
                        prompts. (default: False)
  --cache_type CACHE_TYPE
                        The type of cache to use. Only used if cache is True.
                        (default: ram)
  --cache_size CACHE_SIZE
                        The size of the cache in bytes. Only used if cache is
                        True. (default: 2147483648)
  --vocab_only VOCAB_ONLY
                        Whether to only return the vocabulary. (default:
                        False)
  --verbose VERBOSE     Whether to print debug information. (default: True)
  --host HOST           Listen address (default: localhost)
  --port PORT           Listen port (default: 8000)
  --interrupt_requests INTERRUPT_REQUESTS
                        Whether to interrupt requests when a new request is
                        received. (default: True)
  --n_gqa N_GQA         TEMPORARY: Set to 8 for Llama2 70B
  --rms_norm_eps RMS_NORM_EPS
                        TEMPORARY
</pre>

**Comment by berkut1** [comment]
already exist, read this https://github.com/oobabooga/text-generation-webui/pull/3083

**Comment by apcameron** [comment]
How would I set the value as this switch is currently not accepted --rope_freq_scale

**Comment by berkut1** [comment]
@apcameron read carefully the commit.
https://github.com/oobabooga/text-generation-webui/pull/3083#issuecomment-1639104718
Use `compress_pos_emb`

**Comment by Woisek** [comment]
Is this referring to errors such this? Then I would also know how to set this flag as I can't find it in the UI:

Traceback (most recent call last):
File “F:\Programme\oobabooga_windows\text-generation-webui\modules\ui_model_menu.py”, line 179, in load_model_wrapper
shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File “F:\Programme\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 78, in load_model
output = load_func_map[loader](model_name)
File “F:\Programme\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 241, in llamacpp_loader
model, tokenizer = LlamaCppModel.from_pretrained(model_file)
File “F:\Programme\oobabooga_windows\text-generation-webui\modules\llamacpp_model.py”, line 74, in from_pretrained
result.model = Llama(**params)
TypeError: Llama.init() got an unexpected keyword argument ‘rope_freq_base’

**Comment by berkut1** [comment]
@Woisek I have no that issue. Try to reinstall the text-generation-webui with latest version on one-click-installer

**Comment by apcameron** [comment]
Thank you for pointing me in the right direction
