### ISSUE TITLE
API docs?

### ISSUE THREAD

**Issue by jryebread** [oobabooga/text-generation-webui#35]
Would love to use this instead of kobold as an API + gui (kobold seems to be broken when trying to use pygmalion6b model) 

Feature request for api docs like kobold has, if there is not one already :) Great work on this! https://koboldai.net/api

**Comment by oobabooga** [comment]
The API that gradio generates is kind of self-documenting. Launch the web ui in normal mode (without `--chat` or `--cai-chat`) and click on "API" at the bottom. It gives you Python and Javascript snippets to use as starting points.
