### ISSUE TITLE
May I know how to use the API?

### ISSUE THREAD

**Issue by john012343210** [oobabooga/text-generation-webui#3511]
Is there an API available? May I know how to use the API? I would like to set up a server to serve some requests coming from website.    Is there any documentation?       I might be using Flask.

**Comment by Ram-Chandalada** [comment]
Example how to run the api
python server.py --model TheBloke_StableBeluga2-70B-GPTQ --api --gpu-memory 23 23 23 23 --no_inject_fused_attention

**Comment by iSuslov** [comment]
Can we turn on the API from UI? People use installers and `start_*` scripts to run models, would be nice to have such ability.
