### ISSUE TITLE
No module named 'xformers'

### ISSUE THREAD

**Issue by SmoothBrainApe** [oobabooga/text-generation-webui#3527]
### Describe the bug

I added --xformers to the cmd flags and this error appears

Traceback (most recent call last):
  File "/home/chupz22/oobabooga_linux/text-generation-webui/modules/llama_attn_hijack.py", line 14, in <module>
    import xformers.ops
ModuleNotFoundError: No module named 'xformers'

i tried pip install xformers and it says it is installed. I did under with conda activate textgen so its in the environment.

I can run no problems without xformers but it would be better to have it to save memory. Just wondering what else have I missed? Thanks

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

add --xformers to cmd flags

### Logs

```shell
Traceback (most recent call last):
  File "/home/chupz22/oobabooga_linux/text-generation-webui/modules/llama_attn_hijack.py", line 14, in <module>
    import xformers.ops
ModuleNotFoundError: No module named 'xformers'
```

### System Info

```shell
Linux Mint 21
AMD Ryzen 3 3300X
GPU NVIDIA 3060 12GB VRAM
```

**Comment by Ph0rk0z** [comment]
check that it's installed with `pip list`and that it didn't fail. works over here on 2 machines.

**Comment by SmoothBrainApe** [comment]
I got everything working now. All issues i am having was gone after uninstalling torch on the main unit and reinstalling torch on textgen environment. The issue i have now is other programs like automatic1111 cant run without torch on main. Im kinda lost here now.

**Comment by Ph0rk0z** [comment]
automatic111 is supposed to use venv

**Comment by SmoothBrainApe** [comment]
I know. That is why i am pulling my hair out trying to figure this out hahaha. Will update if i managed to fix this. Thanks

**Comment by SmoothBrainApe** [comment]
I got it working now. I used python venv instead of conda for textgen and it just magically worked together with other venv. I can use comfy, A1111, Roop, and textgen no worries now. I will leave this message here anycase someone else encounter the same problem.

**Comment by fyyyyy** [comment]
I fixed it by adding the last line to one_click.py. Remove after first start.

```python
# line 292...
if __name__ == "__main__":
    # Verifies we are in a conda environment
    check_env()
    
    # add this
    run_cmd("python -m pip install xformers", environment=True)
```
