### ISSUE TITLE
Make it possible to limit the number of tokens/s

### ISSUE THREAD

**Issue by BadisG** [oobabooga/text-generation-webui#3532]
Hello,

I would like to know if there is a possibility to limit the number of tokens/s generated by the model? Exllama is really fast but I really like when the speed of the output matches the speed of my reading (8-9 tokens/s).

Having the possibility to get such limitation would make the experience better for me... and maybe for others who had the same idea in mind of course.

**Comment by oobabooga** [comment]
It's an interesting idea. I have implemented it here: https://github.com/oobabooga/text-generation-webui/pull/3533

Can you test it?

**Comment by BadisG** [comment]
Nice! I gave you my feedback on the PR, thanks for the implementation.
