### ISSUE TITLE
Installs and uninstalls PyTroch Error

### ISSUE THREAD

**Issue by Ne01ynx** [oobabooga/text-generation-webui#355]
### Describe the bug

In the installation process, installs and uninstalls Torch several times. At the end, it tells you that Torch is not compatible with Cuda. I have tried both one-click-installer and anaconda installation.
How can I solve this?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

use one-click-installer

### Screenshot

<img width="947" alt="1" src="https://user-images.githubusercontent.com/122029553/225589371-10c2734e-025f-432c-9566-03015ebf5b31.png">
<img width="946" alt="2" src="https://user-images.githubusercontent.com/122029553/225589390-f84f53a6-af4b-4655-9f39-964faa2b5d5e.png">
<img width="666" alt="3" src="https://user-images.githubusercontent.com/122029553/225589404-017bdddf-690a-4f40-b05a-02d04b02b65c.png">

### Logs

```shell
errors in screenshots
```

### System Info

```shell
AMD Ryzen Threadripper 3960X 24-Core Processor 3.80 GHz
RTX 4090
Windows10
```

**Comment by Olivya-diff** [comment]
How did you solve it?

**Comment by Ne01ynx** [comment]
> How did you solve it?

I completely deleted the environment folder in anaconda. I installed CUDA version 11.7 and pytorch specifically for this version with the command: pip3 install torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117
Only then I re-installed the environment in anaconda according to the guide and the errors disappeared.

**Comment by Olivya-diff** [comment]
Thanks, but unfortunately i have the same issue but whit AMD card so i cant use CUDA (and i already try to do the same whit "pip3 install torchvision torchaudio --index-url https://download.pytorch.org/whl/pytorch-triton-rocm") but anyways thanks for the answer.
