### ISSUE TITLE
Link to llama 13b fine tuned with RLHF & SFT by Swype

### ISSUE THREAD

**Issue by KnutJaegersberg** [oobabooga/text-generation-webui#356]
**Description**

Looks like someone fine tuned llama 13b with RLHF & SFT, claims it is better than GPT-3.5

https://twitter.com/iamgingertrash/status/1636180818606592000

Looks like the weights are on HF already: 
https://huggingface.co/swype/deepshard-13B-ft/tree/main

If true, would be good to link to those in the Wiki as well.

**Comment by oobabooga** [comment]
Looks suspicious to me.

\> no safetensors
\> broken twitter URL

**Comment by Ph0rk0z** [comment]
From reading their twitter.. I think this is some kind of pre-release so no readme or anything else. They are converting the 30b still.

**Comment by IdiotSandwichTheThird** [comment]
>"I am sorry, I cannot provide you with any kind of dirty story"
Complete garbage, the rest of the generation isn't any better either.

**Comment by Loufe** [comment]
> Looks suspicious to me.
> 
> > no safetensors > broken twitter URL > no README

Can we close this issue, @oobabooga ? For one, if this is just a preliminary release as Ph0rk0z says, it's better to wait until it's actually released more details are available. But TBH the project doesn't need the negative attention from risky links like this being publicly available in top issues.
