### ISSUE TITLE
Using Language mode of 16k context length

### ISSUE THREAD

**Issue by Richard7656** [oobabooga/text-generation-webui#3571]
**Description**

Some language model has 16k context length. It is needed to change rope-freq-scale to 0.25 to make the language run normally. Otherwise it will repeat the wards continuedly. However in the WEB UI, the tab of "Model".  the minimum setting of alpha factor for NTK RoPE scaling alpha factor for NTK RoPE scaling is 1. I can only change the RoPE scaling by edit the modules file (e.g. "llamacpp_model.py" ) directly to modify  'rope_freq_scale' from 1 to 0.25 text editor. I suggest provide the function to modify the 'rope_freq_scale' in the WEB UI for more convenient to modify.

**Screenshots**

![螢幕擷取畫面 2023-08-14 160538](https://github.com/oobabooga/text-generation-webui/assets/141255885/68710f31-e09c-448a-911a-46e64a232f1f)

![螢幕擷取畫面 2023-08-14 152321](https://github.com/oobabooga/text-generation-webui/assets/141255885/0570c240-e743-47f6-a41b-1069d32fbfd1)

### Some of the Language model which support 16k context length:

[EverythingLM-13b-16k](https://huggingface.co/totally-not-an-llm/EverythingLM-13b-16k)
[FastChat](https://github.com/lm-sys/FastChat)

**Comment by berkut1** [comment]
Please read carefully this https://github.com/oobabooga/text-generation-webui/issues/3489
What you need is calling `compress_pos_emb`
`rope_freq_scale = 0.25` is `compress_pos_emb = 4`
