### ISSUE TITLE
Stop button can be used even if no streaming

### ISSUE THREAD

**Issue by mykeehu** [oobabooga/text-generation-webui#3573]
**Description**

If the Activate text streaming option is disabled, the Stop button cannot be used until the final text is generated. It would be better to stop the generation immediately, because on slow machines you may have to wait minutes for a response.

**Additional Context**

In case of GGML models (llama.cpp), it would definitely be a great help if the Stop button could be used immediately at any time, not only at the end of text generation.

**Comment by Barnplaid** [comment]
I am seeing problems too, the stop button doesn't work. I think it has to do with the new ability of the WebUI to do several things at once.

**Comment by Ph0rk0z** [comment]
In default mode on Autogptq it stops and the text that got generated is displayed.
In chat it stops and` Is typing...` is permanently in chat log. 
In proper notebook mode it is identical to default behavior.

I have not tried exllama yet to see as it's going to be more like llama.cpp.

**Comment by mykeehu** [comment]
This error is closed because the nostream switch is out. Previously it was relevant because Google Translate would also stream translate, but now it streams the English text first and then translates when it's done, so it's really redundant. And since you can stop it while streaming, the problem is solved.
