### ISSUE TITLE
Using Superbooga via API

### ISSUE THREAD

**Issue by tech-n1c** [oobabooga/text-generation-webui#3582]
Hi, I am recently discovered the text-generation-webui, and I really love it so far. I also tried the superbooga-extension to ask questions about my own files. But is it possible to use this functionality on the API, or is it just available on the web UI? Thanks in advance!

**Comment by PiotrEsse** [comment]
I am also fresh to this but you can try use plugin . there are 2 - one is mimicking openai API and second is an API itself. You need to enable plugins in session tab in webui itself.

**Comment by tech-n1c** [comment]
I tried the API, this works quite well - thank you! The thing I was trying to do was giving the Superbooga extension a file or URL. Do you know if this can only be done on the webui, or can I do that via the API too?

**Comment by PiotrEsse** [comment]
Sorry I didnt research that yet ;-)

**Comment by tech-n1c** [comment]
No problem, thank you!

**Comment by ChristianCCastro** [comment]
https://survey3.medallia.com/?QDGioE-Gduz2tYijElPAVp

**Comment by jianmomo** [comment]
请问成功了吗？我也需要这样一个api,但是我不知道如何做。我想知道现在官方提供的api是否有模糊上下文的能力

**Comment by tech-n1c** [comment]
If you Upload a file in the webui you can ask your LLM questione about it, also using the normal API. But I think you can't upload new files via the API.
