### ISSUE TITLE
Exllama wont load any model

### ISSUE THREAD

**Issue by RobinNekomancer** [oobabooga/text-generation-webui#3605]
### Describe the bug

Hi, kinda losing hope that it works for me. I am somewhat stupid and new when it comes to this kind of technicality. I read that Exllama is a faster more optimized way to load a model. Problem is that i am unable to load any model with the Exllama loader.

It always gives the same error message and so far i couldn't find anyone who had the same problem. I can load these models fine with (and only with) Transformers. I also tried adjusting (and putting in numbers) but nothing changed the outcome

Any help would be much appreciated 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I wish i could tell you. I have a fresh install of oobabooga Nvidia version. I have 2 Llama models i tried it with which i can load in transformers but not in Exllama
Start Oobabooga, head to Model, select Model louder ExLlama, error message

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/142467596/30526fbe-d968-48a3-ad19-e0d03e7141dd)

### Logs

```shell
Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\ui_model_menu.py", line 182, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\models.py", line 317, in ExLlama_loader
    model, tokenizer = ExllamaModel.from_pretrained(model_name)
  File "C:\AI\oobabooga_windows\text-generation-webui\modules\exllama.py", line 69, in from_pretrained
    model = ExLlama(config)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\exllama\model.py", line 732, in __init__
    with safe_open(self.config.model_path, framework = "pt", device = "cpu") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```

### System Info

```shell
Processor AMD Ryzen 9 7950X 16-Core Processor, 4501 Mhz, 16 Core(s), 32 Logical Processor(s)
CPU NVIDIA GeForce RTX 4070 Ti 12GB
```

**Comment by oobabooga** [comment]
ExLlama is for 4-bit GPTQ models, and your model seems to be in transformers format instead of GPTQ.

**Comment by RobinNekomancer** [comment]
Thanks for the response and sorry for the stupid question. Is it the models fault which i try to use or do i have to change something in the Oobabooba start_windows batch?
