### ISSUE TITLE
Remove last option bug with translated text!

### ISSUE THREAD

**Issue by mykeehu** [oobabooga/text-generation-webui#3612]
### Describe the bug

I use the program via Google Translate. I just got a bug that when I press the **Remove last** option, it doesn't insert the translated text, but the English version. It does not take the text from the "visible" block, but from the "internal" json block. Please fix this!
The same would be good to improve the **Copy last reply** option.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Chat with the stick in another language, then press **Remove last**. You will get the text back in English.

### Logs

```shell
-
```

### System Info

```shell
i9-13900K
64 GB RAM
RTX 3060 12 GB
Windows 10
```

**Comment by jllllll** [comment]
I don't think this is something we can fix as the translated text exists only within your browser and does not affect the webui itself in any way. Google Translate would need to be implemented directly into the webui for us to have any influence over it's behavior.

**Comment by oobabooga** [comment]
If you mean the Google Translate extension, this should fix it https://github.com/oobabooga/text-generation-webui/commit/c4733000d715e422d76f3bf58c12f596df03fc0d

I had these lines recently but it probably makes more sense this way.

**Comment by jllllll** [comment]
I had seen that `google_translate` extension many time, but my brain just completely blanked on what it actually was.

**Comment by oobabooga** [comment]
I think it was the first extension ever.

**Comment by mykeehu** [comment]
Unfortunately, I don't speak enough English not to use it, so it's on by default and I speak in Hungarian via the Google Translate extension. So it is nice to be able to rewrite the text in my own language. 
I tested the fix, it works, thank you very much! Can I request this for the **Copy last reply** button as well?

**Comment by mykeehu** [comment]
You are fantastic, thank you so much!
