### ISSUE TITLE
初学者使用体验不好

### ISSUE THREAD

**Issue by jianmomo** [oobabooga/text-generation-webui#3639]
我是一个初学者，项目需要对此进行了使用，但我并不知道加载模型后如何对软件进行使用。
我现在知识启动了它，但它的功能是否有用我一无所知。
希望可以添加简单的使用方式。如果有人知道怎么使用希望可以留下联系方式，我现在一头雾水

**Comment by p5ydn0** [comment]
> 
> 
> 我是一个初学者，项目需要对此进行了使用，但我并不知道加载模型后如何对软件进行使用。
> 
> 我现在知识启动了它，但它的功能是否有用我一无所知。
> 
> 希望可以添加简单的使用方式。如果有人知道怎么使用希望可以留下联系方式，我现在一头雾水

1. 用你妈的英文提问；
2. 加载了模型不会用和人家要使用说明，你应该去你妈的b里让把你重新做一遍加载一次重新开始学怎么点鼠标，而不是在这里浪费别人的时间；
3. 一头雾水关别人屁事；
4. 你妈个b你个蠢猪。

**Comment by jianmomo** [comment]
我用了英文提问，但是没有回复。我不知道我出了什么错误，我搭建好了，并且模型可以加载。所以我想知道是不是我的操作问题。

**Comment by jianmomo** [comment]
报歉，是我的安装问题。当时我找不到问题的原因，所以认为软件还需要做一些复杂的操作才能使用加载的模型，所以提了这样的要求。后来才发现是我安装的问题。
注：模型加载后就能使用。
