### ISSUE TITLE
Can't load text file

### ISSUE THREAD

**Issue by qayyumabro** [oobabooga/text-generation-webui#3671]
### Describe the bug

Throwing "Missing or invalid LoRA file name input."

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Converted pdf to txt file and tried to load in training.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/9138521/99178feb-512b-489b-8dec-3746b120a0fc)

### Logs

```shell
No logs
```

### System Info

```shell
Windows 11
Nvidia Geforce mx330
```

**Comment by bombel28** [comment]
Fill a name in that field above (top of page): 
Name
The name of your new LoRA file

**Comment by qayyumabro** [comment]
Yup missed that my bad. https://imghostr.com/a26df1_dmq  was focusing on 1.

**Comment by 13631368** [comment]
Thanks for all
