### ISSUE TITLE
transformers error loading Llama

### ISSUE THREAD

**Issue by svigx** [oobabooga/text-generation-webui#368]
### Describe the bug

Im not very good at this, just asking if someone can help me

 python server.py --gptq-bits 4 --model llama-7b
Loading llama-7b...
Traceback (most recent call last):
  File "/home/ailv/text-generation-webui/server.py", line 215, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/ailv/text-generation-webui/modules/models.py", line 93, in load_model
    model = load_quantized(model_name)
  File "/home/ailv/text-generation-webui/modules/GPTQ_loader.py", line 55, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
  File "/home/ailv/text-generation-webui/repositories/GPTQ-for-LLaMa/llama.py", line 220, in load_quant
    from transformers import LlamaConfig, LlamaForCausalLM
ImportError: cannot import name 'LlamaConfig' from 'transformers' (/home/ailv/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/__init__.py)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

python server.py --gptq-bits 4 --model llama-7b

### Logs

```shell
python server.py --gptq-bits 4 --model llama-7b
Loading llama-7b...
Traceback (most recent call last):
  File "/home/ailv/text-generation-webui/server.py", line 215, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/ailv/text-generation-webui/modules/models.py", line 93, in load_model
    model = load_quantized(model_name)
  File "/home/ailv/text-generation-webui/modules/GPTQ_loader.py", line 55, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
  File "/home/ailv/text-generation-webui/repositories/GPTQ-for-LLaMa/llama.py", line 220, in load_quant
    from transformers import LlamaConfig, LlamaForCausalLM
ImportError: cannot import name 'LlamaConfig' from 'transformers' (/home/ailv/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/__init__.py)
```

### System Info

```shell
GTX 1660
Windows 10 Pro
12GB Ram
```

**Comment by Gitterman69** [comment]
```
Loading llama-30b-hf...
Traceback (most recent call last):
  File "/home/user/text-generation-webui/server.py", line 215, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/user/text-generation-webui/modules/models.py", line 95, in load_model
    model = load_quantized(model_name)
  File "/home/user/text-generation-webui/modules/GPTQ_loader.py", line 55, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
  File "/home/user/text-generation-webui/repositories/GPTQ-for-LLaMa/llama.py", line 220, in load_quant
    from transformers import LLaMAConfig, LLaMAForCausalLM
ImportError: cannot import name 'LLaMAConfig' from 'transformers' (/home/user/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/__init__.py)
(textgen) user@DESKTOP-CR45CKF:~/text-generation-webui$
```

**Comment by Fenfel** [comment]
Same thing but in the beginning it says "CUDA extension not installed." I don't know what it is because I checked that the right version of cuda is installed

`(textgen) C:\Users\anton\Desktop\SD\text-generation-webui>python server.py --auto-devices --model LLaMA-13B --load-in-4bit --notebook
Warning: --load-in-4bit is deprecated and will be removed. Use --gptq-bits 4 instead.

Loading LLaMA-13B...
CUDA extension not installed.
Traceback (most recent call last):
  File "C:\Users\anton\Desktop\SD\text-generation-webui\server.py", line 215, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\anton\Desktop\SD\text-generation-webui\modules\models.py", line 95, in load_model
    model = load_quantized(model_name)
  File "C:\Users\anton\Desktop\SD\text-generation-webui\modules\GPTQ_loader.py", line 55, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
  File "C:\Users\anton\Desktop\SD\text-generation-webui\repositories\GPTQ-for-LLaMa\llama.py", line 220, in load_quant
    from transformers import LLaMAConfig, LLaMAForCausalLM
ImportError: cannot import name 'LLaMAConfig' from 'transformers' (C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\transformers\__init__.py)

(textgen) C:\Users\anton\Desktop\SD\text-generation-webui>conda install cuda -c nvidia/label/cuda-11.3.0 -c nvidia/label/cuda-11.3.1
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): done
Solving environment: done

 All requested packages already installed.`

**Comment by technoqz** [comment]
This bug is also discussed here  https://github.com/huggingface/transformers/issues/22222

**Comment by svigx** [comment]
thanks guys, i just had to install pip install git+https://github.com/huggingface/transformers

**Comment by Fenfel** [comment]
> thanks guys, i just had to install pip install git+https://github.com/huggingface/transformers

Still doesn't work

**Comment by svigx** [comment]
yes for me

**Comment by Fenfel** [comment]
> yes for me what does it says for you?

`Loading LLaMA-13B...
CUDA extension not installed.
Traceback (most recent call last):
  File "C:\Users\anton\Desktop\SD\text-generation-webui\server.py", line 215, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\anton\Desktop\SD\text-generation-webui\modules\models.py", line 95, in load_model
    model = load_quantized(model_name)
  File "C:\Users\anton\Desktop\SD\text-generation-webui\modules\GPTQ_loader.py", line 55, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits)
  File "C:\Users\anton\Desktop\SD\text-generation-webui\repositories\GPTQ-for-LLaMa\llama.py", line 220, in load_quant
    from transformers import LLaMAConfig, LLaMAForCausalLM
ImportError: cannot import name 'LLaMAConfig' from 'transformers' (C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\transformers\__init__.py)`

**Comment by svigx** [comment]
i am using wsl, i couldn't get it working with windows, just use that

**Comment by VincentRoma** [comment]
> > yes for me what does it says for you?
> 
> Loading LLaMA-13B... CUDA extension not installed. Traceback (most recent call last): File "C:\Users\anton\Desktop\SD\text-generation-webui\server.py", line 215, in shared.model, shared.tokenizer = load_model(shared.model_name) File "C:\Users\anton\Desktop\SD\text-generation-webui\modules\models.py", line 95, in load_model model = load_quantized(model_name) File "C:\Users\anton\Desktop\SD\text-generation-webui\modules\GPTQ_loader.py", line 55, in load_quantized model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits) File "C:\Users\anton\Desktop\SD\text-generation-webui\repositories\GPTQ-for-LLaMa\llama.py", line 220, in load_quant from transformers import LLaMAConfig, LLaMAForCausalLM ImportError: cannot import name 'LLaMAConfig' from 'transformers' (C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\transformers__init__.py)

You need to install CUDA for windows: 
https://developer.nvidia.com/cuda-zone

**Comment by Fenfel** [comment]
> > > yes for me what does it says for you?
> > 
> > 
> > Loading LLaMA-13B... CUDA extension not installed. Traceback (most recent call last): File "C:\Users\anton\Desktop\SD\text-generation-webui\server.py", line 215, in shared.model, shared.tokenizer = load_model(shared.model_name) File "C:\Users\anton\Desktop\SD\text-generation-webui\modules\models.py", line 95, in load_model model = load_quantized(model_name) File "C:\Users\anton\Desktop\SD\text-generation-webui\modules\GPTQ_loader.py", line 55, in load_quantized model = load_quant(str(path_to_model), str(pt_path), shared.args.gptq_bits) File "C:\Users\anton\Desktop\SD\text-generation-webui\repositories\GPTQ-for-LLaMa\llama.py", line 220, in load_quant from transformers import LLaMAConfig, LLaMAForCausalLM ImportError: cannot import name 'LLaMAConfig' from 'transformers' (C:\Users\anton\anaconda3\envs\textgen\lib\site-packages\transformers__init__.py)
> 
> You need to install CUDA for windows: https://developer.nvidia.com/cuda-zone

thx i fix that long time ago

**Comment by runzhi214** [comment]
fixed this bug by moving to python3.9
