### ISSUE TITLE
Training llama-2 with transformers not possible anymore

### ISSUE THREAD

**Issue by bombel28** [oobabooga/text-generation-webui#3681]
### Describe the bug

EDIT:  Most problems are solved by deactivating "Add EOS token" and saving training data in UTF-8 BOM instead of UTF-8.
I also opened an issue on transformers.
Seems like "Add EOS token" is obsolete or have to be enhanced in my tokenizer (I'm not familiar with it).

tokenization_llama.py", line 208, in tokenize
    if tokens[0] == SPIECE_UNDERLINE and tokens[1] in self.all_special_tokens:
UnboundLocalError: local variable 'tokens' referenced before assignment

This is, what I get, when training raw text with "\<s>-tokens" after last update.

I managed to make it work again with this modification in .\installer_files\env\lib\site-packages\transformers\models\llama\tokenization_llama.py:

```
 # Copied from transformers.models.t5.tokenization_t5.T5Tokenizer.tokenize
    def tokenize(self, text: "TextInput", **kwargs) -> List[str]:
        """
        Converts a string to a list of tokens. If `self.legacy` is set to `False`, a prefix token is added unless the
        first token is special.
        """
        if self.legacy:
            return super().tokenize(text, **kwargs)

        tokens = super().tokenize(SPIECE_UNDERLINE + text.replace(SPIECE_UNDERLINE, " "), **kwargs)

        if len(tokens) > 1 and tokens[0] == SPIECE_UNDERLINE and tokens[1] in self.all_special_tokens:
            tokens = tokens[1:]

        return tokens

```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load llama2 model, use raw text file with some <s>- or </s> tokens and start training

### Logs

```shell
File "C:\Users\myUser\GPT\installer_files\env\lib\site-packages\transformers\models\llama\tokenization_llama.py", line 208, in tokenize
    if tokens[0] == SPIECE_UNDERLINE and tokens[1] in self.all_special_tokens:
UnboundLocalError: local variable 'tokens' referenced before assignment
```

### System Info

```shell
RTX 4090, latest oobabooga update get with update-script
```

**Comment by bombel28** [comment]
not solved after all updates yet, still reproducable. Is this an issue with the model tokenizer or transformers?

**Comment by wagesj45** [comment]
I'm getting the same error on training `Llama-2-7B`. I don't always get the error, but once I cross from a 100k line raw file into a 400k line training file it emerges. I can't find a significant difference in the content of the two files, as far as character codes go.

**Comment by zwqjoy** [comment]
fixed:  upgrade to Successfully installed transformers-4.33.1

**Comment by bombel28** [comment]
I try to check my own training data now... maybe, I find a way to log the special chars into a file...

**Comment by bombel28** [comment]
Ok, the problem comes from activated function to set a token after hardcut. Texts with 6 linefeeds may set two eos tokens. But the tokenizer is not prepared for that. So, it would be fine to have the ability to set a range from two to ten linefeeds, for example.

**Comment by bombel28** [comment]
i found some problems with Unicode-characters, too. Beform last transformers bump, "\x{016b}" was not a problem. 

UnicodeEncodeError: 'charmap' codec can't encode character '\u016b' in position 13: character maps to <undefined>

**Comment by bombel28** [comment]
I am not sure whether this is solved, it is not important for me at the moment or while non others have problems with it... think we can close this for now.
