### ISSUE TITLE
Suggestions for a faster response?

### ISSUE THREAD

**Issue by DiGregorioC** [oobabooga/text-generation-webui#37]
Hello!

I wondering if you have any tips for a faster response, it takes about a minute for my characters. Thank you!

This is what I'm running the script with
`python server.py --cai-chat --auto-devices --gpu-memory 6 --no-stream`

**Comment by oobabooga** [comment]
Some things to try are

* Reducing the prompt size (smaller context strings, smaller "history size in prompt" value)
* Loading the model in 8-bit mode instead of offloading layers to the CPU (if possible)
* Using a smaller version of the model

**Comment by oobabooga** [comment]
With deepspeed it might be possible to get better speeds on low VRAM systems. See https://github.com/oobabooga/text-generation-webui/issues/40#issuecomment-1412038622
