### ISSUE TITLE
Bug or Not? (UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7`)

### ISSUE THREAD

**Issue by YakuzaSuske** [oobabooga/text-generation-webui#3701]
### Describe the bug

When using a Llama 2 model like `TheBloke_MythoMax-L2-13B-GPTQ` and use my own setting parameters i get this weird warning on the console saying:

```D:\OOBABOOGA\installer_files\env\lib\site-packages\transformers\generation\configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(```
  
```D:\OOBABOOGA\installer_files\env\lib\site-packages\transformers\generation\configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(```
  
```D:\OOBABOOGA\installer_files\env\lib\site-packages\transformers\generation\configuration_utils.py:372: UserWarning: `do_sample` is set to `False`. However, `typical_p` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `typical_p`.
  warnings.warn(```
  
```Output generated in 2.20 seconds (10.44 tokens/s, 23 tokens, context 592, seed 1174144596)```

It can generate an output fine with no issues, but the warning is what i'm curious about. Is this a bug or a weird warning that is just not to be worried about? I see no problems with my outputs at all and everything seems fine, it's just i get that weird warning on the console. Any clues?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Load TheBloke_MythoMax-L2-13B-GPTQ using ExLlama
2. Use parameters shown in screenshots.
3. Generate.
4. Warning on console.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/63294141/e08042c6-fb51-4bb5-928f-a4192a412d93)
![image](https://github.com/oobabooga/text-generation-webui/assets/63294141/c54a526b-4228-4fe4-b947-c7994b8775be)
![image](https://github.com/oobabooga/text-generation-webui/assets/63294141/532e9aa5-a7c9-4937-ac85-21e2af0e18b4)

### Logs

```shell
Starting the web UI...
bin D:\OOBABOOGA\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
2023-08-26 23:21:30 INFO:Loading the extension "send_pictures"...
Starting streaming server at ws://127.0.0.1:5005/api/v1/stream
2023-08-26 23:21:33 INFO:Loading the extension "gallery"...
Starting API at http://127.0.0.1:5000/api
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-08-26 23:32:13 INFO:Loading TheBloke_MythoMax-L2-13B-GPTQ...
2023-08-26 23:32:22 WARNING:models\TheBloke_MythoMax-L2-13B-GPTQ\tokenizer_config.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-08-26 23:32:22 WARNING:models\TheBloke_MythoMax-L2-13B-GPTQ\special_tokens_map.json is different from the original LlamaTokenizer file. It is either customized or outdated.
2023-08-26 23:32:22 INFO:Loaded the model in 8.58 seconds.

D:\OOBABOOGA\installer_files\env\lib\site-packages\transformers\generation\configuration_utils.py:362: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(
D:\OOBABOOGA\installer_files\env\lib\site-packages\transformers\generation\configuration_utils.py:367: UserWarning: `do_sample` is set to `False`. However, `top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
D:\OOBABOOGA\installer_files\env\lib\site-packages\transformers\generation\configuration_utils.py:372: UserWarning: `do_sample` is set to `False`. However, `typical_p` is set to `0` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `typical_p`.
  warnings.warn(
Output generated in 2.20 seconds (10.44 tokens/s, 23 tokens, context 592, seed 1174144596)
```

### System Info

```shell
Windows 10
RTX 3080Ti
32Gb Ram

Installed using 1 click install
```

**Comment by jllllll** [comment]
The `do_sample` option in the `Generation` settings is disabled. All of the settings in that side of the tab basically aren't being used while that is off.

**Comment by YakuzaSuske** [comment]
> The `do_sample` option in the `Generation` settings is disabled. All of the settings in that side of the tab basically aren't being used while that is off.
Ahh.. so it's more of a warning than an issue. Got it!
