### ISSUE TITLE
Download only one model when multiple are available in the Hugging Face repo

### ISSUE THREAD

**Issue by spreck** [oobabooga/text-generation-webui#3717]
I'm encountering an issue while attempting to utilize this file: https://huggingface.co/TheBloke/WizardCoder-Python-13B-V1.0-GGUF/blob/main/wizardcoder-python-13b-v1.0.Q5_K_M.gguf

When I input "TheBloke/WizardCoder-Python-13B-V1.0-GGUF" into the model download section of the webui it triggers the download of all available model versions, rather than just the specific one I intend to use. This leads to an unnecessary downloads and wasted space.

Is there a way to prevent this and only download the required model version to save on download size?

**Comment by 123LiVo321** [comment]
Hi there, I had the same struggle and its easy to solve! Its in the model card on each huggingface thebloke GPTQ model : 

How to download from branches
In text-generation-webui, you can add :branch to the end of the download name, eg TheBloke/WizardCoder-Python-34B-V1.0-GPTQ:gptq-4bit-32g-actorder_True
With Git, you can clone a branch with:
git clone --single-branch --branch gptq-4bit-32g-actorder_True https://huggingface.co/TheBloke/WizardCoder-Python-34B-V1.0-GPTQ

**Comment by bet0x** [comment]
It doesn't work for GGUF or GGML. You get everything.

**Comment by 123LiVo321** [comment]
my bad than, sorry

**Comment by NovNovikov** [comment]
Now this created a problem when gguf files are splitted into many files - since now they must be downloaded one by one.
