### ISSUE TITLE
ValueError: Target module Autograd4bitQuantLinear() is not supported.

### ISSUE THREAD

**Issue by jordankzf** [oobabooga/text-generation-webui#3765]
### Describe the bug

```
Currently, only the following modules are supported: torch.nn.Linear, torch.nn.Embedding, torch.nn.Conv2d, transformers.pytorch_utils.Conv1D.
```
I'm using `text-generation-webui`, but the same issue occurs even when using `alpaca_lora_4bit` directly. I have applied the monkey-patch (I think?):

```
2023-08-31 12:04:24 INFO:Loading TheBloke_Llama-2-13B-GPTQ...
2023-08-31 12:04:24 WARNING:Applying the monkey patch for using LoRAs with GPTQ models. It may cause undefined behavior outside its intended scope.
```

Loaded the model using `GPTQ-for-LLaMa`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Load any GPTQ model using `GPTQ-for-LLaMa`. ([Hint: try one from TheBloke](https://huggingface.co/TheBloke))
2. Attempt to finetune the model (Under the  `Training` tab)

[Note: Remember to follow the instructions here and apply the `--monkey-patch`](https://github.com/oobabooga/text-generation-webui/blob/main/docs/GPTQ-models-(4-bit-mode).md#using-loras-in-4-bit-mode)

### Screenshot
![image](https://github.com/oobabooga/text-generation-webui/assets/65149726/ba09be7b-6008-43f9-8c0a-26b4787cf8c5)

### System Info

```shell
Ubuntu via WSL (Windows 10) - Same issue even when running on Windows 10 natively

1x 3090 + AMD Ryzen 3600
```

**Comment by Ph0rk0z** [comment]
I just realized that here, unlike on my version, the monkeypatch relies on custom sterlind PEFT and in my repo I baked it into the alpaca_lora_4bit as a patch to any PEFT: https://github.com/Ph0rk0z/GPTQ-Merged/blob/dual-model/src/alpaca_lora_4bit/monkeypatch/peft_tuners_lora_monkey_patch.py

So sadly you have to install: https://github.com/sterlind/peft

Everybody has been using newer PEFT and so it fails like this because it's not patched to support the custom lora model it uses.

**Comment by jordankzf** [comment]
I get `ModuleNotFoundError: No module named 'autograd_4bit'` using `pip install git+https://github.com/sterlind/peft.git`

**Comment by Ph0rk0z** [comment]
Did you uninstall your old PEFT?

**Comment by jordankzf** [comment]
I did, it was not the issue.

**Comment by jordankzf** [comment]
Solution found at #148 ([See this comment](https://github.com/johnsmith0031/alpaca_lora_4bit/issues/148#issuecomment-1701971077))

[Commit for reference](https://github.com/johnsmith0031/alpaca_lora_4bit/commit/ed8bc8f4acd4f642a4532268848eb3e86d126d63)

**Comment by Ph0rk0z** [comment]
Yes, the updated one is better but I tend to use it stand alone. It doesn't work very well on the pascal card I have in here. And his new one has the patch built in as well, which is where I copied the idea from.
