### ISSUE TITLE
Linux installer fails because it tries to run an .exe on Linux

### ISSUE THREAD

**Issue by pmarreck** [oobabooga/text-generation-webui#3766]
### Describe the bug

`/home/pmarreck/Downloads/oobabooga_linux/installer_files/miniconda_installer.sh: line 352: /home/pmarreck/Downloads/oobabooga_linux/installer_files/conda/conda.exe: cannot execute: required file not found`

```
pmarreck 🟢 19ms
20230831000813 ~/ /oobabooga_linux bash> l2 installer_files/
Permissions Size User     Date Modified Name
drwxr-xr-x     - pmarreck 31 Aug 00:07   installer_files
drwxr-xr-x     - pmarreck 31 Aug 00:07  ├──  conda
.rwxr-xr-x   12M pmarreck 31 Aug 00:07  │  ├──  conda.exe
drwxr-xr-x     - pmarreck 31 Aug 00:07  │  └──  install_tmp
.rwxr--r--   73M pmarreck 31 Aug 00:07  └──  miniconda_installer.sh
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try to run `start_linux.sh` on a Linux install

### Logs

```shell
already included
```

### System Info

```shell
pmarreck@nixos
--------------
OS: NixOS 23.11pre520402.e7f38be3775b (Tapir) x86_64
Host: System76 Thelio Major
Kernel: 6.1.49
Uptime: 5 hours, 23 mins
Packages: 2566 (nix-system), 3197 (nix-user), 147 (nix-default), 47 (flatpak)
Shell: bash 5.2.15
Resolution: 3440x1440
DE: GNOME 44.3
WM: Mutter
WM Theme: Nordic
Theme: Adwaita [GTK2/3]
Icons: Adwaita [GTK2/3]
Terminal: WezTerm
CPU: AMD Ryzen Threadripper 3990X (128) @ 2.900GHz
GPU: NVIDIA GeForce RTX 2080 Ti Rev. A
GPU: NVIDIA GeForce RTX 3080 Ti
Memory: 52368MiB / 128556MiB
```

**Comment by bet0x** [comment]
Try to execute the .sh with bash -x to get a debug of the issue. It could be your NixOS not being supported by Conda.

**Comment by pmarreck** [comment]
See? It's looking for conda/bin/conda, but it's not there- instead there's a conda/conda.exe

I have conda available locally though:

```
bash> which conda
/home/pmarreck/.conda/bin/conda
```

**Comment by pmarreck** [comment]
oh wait, it's now working, LOL

For anyone else who ends up here while trying to make this work on Nix/NixOS:

1) Install Conda via Nix
2) Run `conda-shell` AND THEN `conda-install`. Stuff should now happen and it should install to `~/.conda/bin/conda`. Not sure about what adds this to PATH, but it was there (probably `conda-shell` does this).
3) NOW you can try running the `start_linux.sh` script and it should ask you what mode to use (GPU, etc) and then do its thing (oh, make all the .sh files executable as well, as well as probably the webui.py)

**Comment by bet0x** [comment]
@oobabooga We should add this to the README.MD as "NixOS installation steps" ?
