### ISSUE TITLE
Loading GPTQ model using AutoGPTQ can lead to the webui to end

### ISSUE THREAD

**Issue by Touch-Night** [oobabooga/text-generation-webui#3777]
### Describe the bug

如果在加载了GGML/GGUF模型之后，选择一个GPTQ模型并点击加载，那么程序会在加载了一会之后结束。 
English translated by BingChat: If you select a GPTQ model and click load after a GGML/GGUF model is loaded, the program will end after loading for a while.

Edit: Loading a GGML/GGUF model before loading a GPTQ model is not necessary to reproduce this issue. It may happen even if a GPTQ model is a first load, though the possibility is much lower than when it is not the first model loaded since the webui start. Load using Exllama or Exllama-HF won't trigger this issue.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load a GGUF model and play with it for a while, and then switch to a GPTQ model.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/102669562/fce93e50-676d-4ce9-893e-2bcc664821e6)

### Logs

```shell
No errors
```

### System Info

```shell
System: Windows 10;
GPU: Nvidia RTX 3050 Ti Laptop (modified to 8GB VRAM)
```

**Comment by hypersniper05** [comment]
I had this happen to me just now using a llama 1 GPTQ model

**Comment by Ph0rk0z** [comment]
When I unloaded GGML models, stuff would stick in GPU memory. Maybe related.

**Comment by Touch-Night** [comment]
Tested again on latest version, this issue is resolved.
