### ISSUE TITLE
Chat, instruct-chat or instruct in character profile

### ISSUE THREAD

**Issue by bombel28** [oobabooga/text-generation-webui#3843]
Since last update, instruct mode is not selected by default any more. Good for me, bad for some others (maybe).
Why not moving that selector into character profile? Would fit perfect there, I think.

BTW: Thank you for all the great work!

**Comment by missionfloyd** [comment]
The default can be set in [`settings.yaml`](https://github.com/oobabooga/text-generation-webui/blob/4affa088214b59a8bbefbd0f956523a396486bd7/settings-template.yaml#L4)
