### ISSUE TITLE
Typical_P?

### ISSUE THREAD

**Issue by Ne01ynx** [oobabooga/text-generation-webui#386]
I can't find a guide anywhere about typical_p and examples of how it affects text generation.

**Comment by Xabab** [comment]
probably this (at least the theory) https://towardsdatascience.com/mastering-p-values-in-machine-learning-bdc5bd0dd8ae

**Comment by Xabab** [comment]
The paper:
https://arxiv.org/pdf/2202.00666.pdf
Code:
https://github.com/cimeister/typical-sampling/blob/3e676cfd88fa2e6a24f2bdc6f9f07fddb87827c2/src/transformers/generation_logits_process.py#L242-L272
Some random youtube vid:
https://youtu.be/_EDr3ryrT_Y

As far as I understand, when choosing a next token, it cuts of low probability tokens (just like top_p; absurd, out of context words), *as well as* high probability tokens (most likely but boring words), effectively encouraging the model to use less common tokens a more, but not flattening the distribution like the temperature does.
