### ISSUE TITLE
Cannnot run text-generation-webui after updated on 11/9/2023

### ISSUE THREAD

**Issue by Richard7656** [oobabooga/text-generation-webui#3868]
### Describe the bug

During running the “update_windows”, three error message display separately. After that when I try to run text-generation-webui by “start_windows”, a error message display and cannot not enter the web UI.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Running the programme "update_windows" and 3 error meeage display. Then rung thr programme "start_windows”. 1 error message display and cannot enter the Web UI . Same error display when delete all the old file and use “start_windows” to reinstall them.

### Screenshot

![螢幕擷取畫面 2023-09-11 145501](https://github.com/oobabooga/text-generation-webui/assets/141255885/0ca3077a-2a97-4460-8047-be1fd572542d)

![螢幕擷取畫面 2023-09-11 145618](https://github.com/oobabooga/text-generation-webui/assets/141255885/e20c16a1-cfed-4135-99b3-b745e313c09f)

![螢幕擷取畫面 2023-09-11 145659](https://github.com/oobabooga/text-generation-webui/assets/141255885/eab63187-de8c-4a1c-903b-03ca077e1dde)

![螢幕擷取畫面 2023-09-11 144620](https://github.com/oobabooga/text-generation-webui/assets/141255885/98d715e6-85be-4320-8946-8b04aa9d5287)

### Logs

```shell
3 Error message at “update_windows”

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
elevenlabs 0.2.26 requires pydantic>=2.0, but you have pydantic 1.10.12 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastapi 0.95.2 requires pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2, but you have pydantic 2.3.0 which is incompatible.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openai-whisper 20230314 requires tiktoken==0.3.1, but you have tiktoken 0.4.0 which is incompatible.

1 Error message at “start_windows”

Traceback (most recent call last):
  File "E:\AI_app\oobabooga_windows\oobabooga_windows\text-generation-webui\server.py", line 12, in <module>
    import gradio as gr
  File "E:\AI_app\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "E:\AI_app\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\gradio\components.py", line 32, in <module>
    from fastapi import UploadFile
  File "E:\AI_app\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "E:\AI_app\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\fastapi\applications.py", line 16, in <module>
    from fastapi import routing
  File "E:\AI_app\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "E:\AI_app\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (E:\AI_app\oobabooga_windows\oobabooga_windows\installer_files\env\lib\site-packages\pydantic\fields.py)
請按任意鍵繼續 . . .
```

### System Info

```shell
Operating System: Windows 11 Professional 22H2 (Chinese Traditional)
CPU: AMD Ryzen 5 5600 6-Core Processor 3.50 GHz
GPU: GIGABYTE AMD Radeon RX 6650 XT (Driver Version 23.9.1)
RAM: 64GB
```

**Comment by mattieshadow** [comment]
I have the same issue

**Comment by YakuzaSuske** [comment]
same issue here...
![image](https://github.com/oobabooga/text-generation-webui/assets/63294141/d36e12bb-6338-4889-bf90-bb44dd64d522)

**Comment by l-schuette** [comment]
there seem to be contradicting requirements:
![image](https://github.com/oobabooga/text-generation-webui/assets/77062557/f67468f0-69df-47e0-ac5b-ab902f596c03)
![image](https://github.com/oobabooga/text-generation-webui/assets/77062557/39e544ba-f918-469d-bb77-dd208ed5bc33)

**Comment by YakuzaSuske** [comment]
yhea something prob got broken on the requirements.

**Comment by bparrott78** [comment]
I was able to fix it by going to oobabooga_windows\text-generation-webui and running pip install -r requirements.txt

**Comment by YakuzaSuske** [comment]
> I was able to fix it by going to oobabooga_windows\text-generation-webui and running pip install -r requirements.txt

i tried that just now but... same issue

**Comment by bparrott78** [comment]
Sorry I did a git reset --hard 66d5caba1b79b060ca1a5626d9c958711ba1e3b6 first, then went to text-generation-webui and did pip install -r requirements.txt

**Comment by YakuzaSuske** [comment]
> Sorry I did a git reset --hard [66d5cab](https://github.com/oobabooga/text-generation-webui/commit/66d5caba1b79b060ca1a5626d9c958711ba1e3b6) first, then went to text-generation-webui and did pip install -r requirements.txt

Nope... same issue again. Man i got no luck....

**Comment by biollas** [comment]
Same error, completely broken for me. Seems like a critical fix is in order.

**Comment by Richard7656** [comment]
The same error message still appear and cannot enter Web UI.

Instead of the txt file "requirements.txt", I also notice a txt file call "requirements_nocuda". This txt file do not has been added the ward "pydantic==1.10.12" as "requirements.txt" . Do this cause the error for whom cannot use cuda as using non Nvidia graphic Card ?

**Comment by l-schuette** [comment]
> > Same error, completely broken for me. Seems like a critical fix is in order.
> > Edit: https://www.reddit.com/r/Oobabooga/comments/16elrh4/help_getting_this_error_message_importerror/
> > This thread helped fix it for me.
> 
> Which one did you do first? The gradio and requirement or the pip install pydantic==1.10.11?

The following steps worked for me (from the reddit post):

change line 2 & 3 in requirements.txt to 
`fastapi==0.103.1
gradio_client==0.5.0`

> pip install --upgrade gradio
> pip install -r requirements.txt

**Comment by YakuzaSuske** [comment]
> > > Same error, completely broken for me. Seems like a critical fix is in order.
> > > Edit: https://www.reddit.com/r/Oobabooga/comments/16elrh4/help_getting_this_error_message_importerror/
> > > This thread helped fix it for me.
> > 
> > 
> > Which one did you do first? The gradio and requirement or the pip install pydantic==1.10.11?
> 
> The following steps worked for me (from the reddit post):
> 
> change line 2 & 3 in requirements.txt to `fastapi==0.103.1 gradio_client==0.5.0`
> 
> pip install --upgrade gradio pip install -r requirements.txt

Yup that worked.

**Comment by l-schuette** [comment]
> > > > Same error, completely broken for me. Seems like a critical fix is in order.
> > > > Edit: https://www.reddit.com/r/Oobabooga/comments/16elrh4/help_getting_this_error_message_importerror/
> > > > This thread helped fix it for me.
> > > 
> > > 
> > > Which one did you do first? The gradio and requirement or the pip install pydantic==1.10.11?
> > 
> > 
> > The following steps worked for me (from the reddit post):
> > change line 2 & 3 in requirements.txt to `fastapi==0.103.1 gradio_client==0.5.0`
> > pip install --upgrade gradio pip install -r requirements.txt
> 
> Yup that worked.

just be aware that elevenlabs and other extensions might not work for now because of those changes

**Comment by YakuzaSuske** [comment]
> > > > > Same error, completely broken for me. Seems like a critical fix is in order.
> > > > > Edit: https://www.reddit.com/r/Oobabooga/comments/16elrh4/help_getting_this_error_message_importerror/
> > > > > This thread helped fix it for me.
> > > > 
> > > > 
> > > > Which one did you do first? The gradio and requirement or the pip install pydantic==1.10.11?
> > > 
> > > 
> > > The following steps worked for me (from the reddit post):
> > > change line 2 & 3 in requirements.txt to `fastapi==0.103.1 gradio_client==0.5.0`
> > > pip install --upgrade gradio pip install -r requirements.txt
> > 
> > 
> > Yup that worked.
> 
> just be aware that elevenlabs and other extensions might not work for now because of those changes

i don't use elevenlabs so im fine with that. I only use API, Send picture and Share.

**Comment by oobabooga** [comment]
It looks to me like you are using an outdated version of the one-click-installer. Try overwriting your existing `webui.py` file  with this one:

https://raw.githubusercontent.com/oobabooga/one-click-installers/main/webui.py

After that, run the update script.

**Comment by l-schuette** [comment]
> It looks to me like you are using an outdated version of the one-click-installer. Try overwriting your existing `webui.py` file with this one:
> 
> https://raw.githubusercontent.com/oobabooga/one-click-installers/main/webui.py
> 
> After that, run the update script.

Yes, that fixed it, for me at least, thanks!

**Comment by bigsk1** [comment]
> It looks to me like you are using an outdated version of the one-click-installer. Try overwriting your existing `webui.py` file with this one:
> 
> https://raw.githubusercontent.com/oobabooga/one-click-installers/main/webui.py
> 
> After that, run the update script.

The last release showing Feb 9th, so I would have never thought to update ( download and add files a regular update windows bat file )  wouldn't do. Anyway to add a new release instead of editing existing release ?

**Comment by YakuzaSuske** [comment]
> It looks to me like you are using an outdated version of the one-click-installer. Try overwriting your existing `webui.py` file with this one:
> 
> https://raw.githubusercontent.com/oobabooga/one-click-installers/main/webui.py
> 
> After that, run the update script.
Yhea that fixed it for me too. Tho i had an older version of the one click install so i had to replace it with the new one. But now it is fixed. Thx.

**Comment by Richard7656** [comment]
> It looks to me like you are using an outdated version of the one-click-installer. Try overwriting your existing `webui.py` file with this one:
> 
> https://raw.githubusercontent.com/oobabooga/one-click-installers/main/webui.py
> 
> After that, run the update script.

After doing this all the error message disappear and can run the Web UI normally. Download the latest [oobabooga_windows.zip](https://github.com/oobabooga/text-generation-webui/releases/download/installers/oobabooga_windows.zip) and reinstalled the file also work. 

I notice the release column in github show the latest version of [Windows/Linux/MacOS installers](https://github.com/oobabooga/text-generation-webui/releases/tag/installers) is released on 10 Feb 2023. However this only show the released date of source. The release date of latest installer zip are in the last month. It is better to modify the way of displaying the latest release in github to let people more easily know the new release.

  
![螢幕擷取畫面 2023-09-13 151613](https://github.com/oobabooga/text-generation-webui/assets/141255885/afd9c267-447a-41cc-86b7-ee30f73933c5)
![螢幕擷取畫面 2023-09-13 152151](https://github.com/oobabooga/text-generation-webui/assets/141255885/3d0dba76-ff2a-406e-a473-039cf0ff02d2)
