### ISSUE TITLE
Silero TTS more languages

### ISSUE THREAD

**Issue by Dartvauder** [oobabooga/text-generation-webui#3871]
Hello. I want to know. Why are only english speakers available in Silero extension? How can I add other languages?

**Comment by missionfloyd** [comment]
Silero supports [these languages](https://github.com/snakers4/silero-models#models-and-speakers). You can change the language, model ID, and default speaker here.
https://github.com/oobabooga/text-generation-webui/blob/df123a20fccda29439d70c5590de2e33937acbed/extensions/silero_tts/script.py#L18-L20
And the list of speakers here.
https://github.com/oobabooga/text-generation-webui/blob/df123a20fccda29439d70c5590de2e33937acbed/extensions/silero_tts/script.py#L31
