### ISSUE TITLE
Listening on all local IPs and interfaces

### ISSUE THREAD

**Issue by AnnoyingTechnology** [oobabooga/text-generation-webui#3879]
Hello, 

How do you make the python server listen an all locals IPs ? 
ie. binding to `0.0.0.0` instead of `127.0.0.1`.

Thanks.

**Comment by AnnoyingTechnology** [comment]
Found it, in `text-generation-webui/server.py`

replace `server_name=None if not shared.args.listen else (shared.args.listen_host or '0.0.0.0'),` 
with `server_name=0.0.0.0`

**Comment by jamesbraza** [comment]
I think the right solution, instead of directly changing the source, is to pass `--listen` to `server.py`:

```bash
python server.py --listen
```
