### ISSUE TITLE
ExLlama v2 support with EXL2-quantized models

### ISSUE THREAD

**Issue by Thireus** [oobabooga/text-generation-webui#3882]
**Description**

ExLlama v2 has just been released - https://github.com/turboderp/exllamav2 with a new quantization format EXL2. It would be great if text-generation-webui could support it.

**Additional Context**

Overview of differences compared to V1

- Faster, better kernels
- Cleaner and more versatile codebase
- Support for a new quant format

**Comment by oobabooga** [comment]
This has been added here: https://github.com/oobabooga/text-generation-webui/pull/3881

**Comment by sammcj** [comment]
Nice work!

I'm now able to load in 70b Q2 models on a single RTX3090 - and it's _fast_:

<img width="1678" alt="image" src="https://github.com/oobabooga/text-generation-webui/assets/862951/552a5285-cd16-4650-9eb9-87582bd5ed26">
