### ISSUE TITLE
Exllama v2: unsupported GNU version!

### ISSUE THREAD

**Issue by Jongulo** [oobabooga/text-generation-webui#3883]
### Describe the bug

Loading 70b model on a 3090 gives massive error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Loading [LLama2-70B-chat-2.55bpw](https://huggingface.co/turboderp/LLama2-70B-chat-2.55bpw-h6-exl2) does not work and gives error. Using Exllama v2

### Logs

```shell
pasting link since github won't allow the length
https://pastebin.com/3H9Ap4Vv
```

### System Info

```shell
48gb ddr4 ram
Ryzen 3700x
Ubuntu 23.04
64-bit
Wayland
Linux 6.2.0-32-generic
```

**Comment by Ph0rk0z** [comment]
In theory this means you have to downgrade g++ version or add the flag it says. Maybe open an issue in the exllamav2 repo.

`#error -- unsupported GNU version! gcc versions later than 11 are not supported! The nvcc flag '-allow-unsupported-compiler' can be used to override this version check; however, using an unsupported host compiler may cause compilation failure or incorrect run time execution. Use at your own risk.`

**Comment by Ph0rk0z** [comment]
It can't find the cuda libs. https://stackoverflow.com/questions/9633881/usr-bin-ld-cannot-find-lcudart

**Comment by Jongulo** [comment]
> It can't find the cuda libs. https://stackoverflow.com/questions/9633881/usr-bin-ld-cannot-find-lcudart

still not sure exactly what I need to do

**Comment by Ph0rk0z** [comment]
You need to find out where the cuda libs are and if they're there and then link them to where the compiler can find them

https://askubuntu.com/questions/510176/usr-bin-ld-cannot-find-lcudart

**Comment by berrywoods** [comment]
Were you able to fix this? I have the same issue

**Comment by Jongulo** [comment]
> Were you able to fix this? I have the same issue

Nope

**Comment by Jongulo** [comment]
Using the docker image fixed this.
