### ISSUE TITLE
Unable to download models or convert them

### ISSUE THREAD

**Issue by Manimap** [oobabooga/text-generation-webui#39]
Hello,

I have a weird issue when trying to download models, it tells me that : 
File "D:\text-generation-webui\download-model.py", line 10, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

Except if I look at installs from requirements, I see that : 
Collecting bs4==0.0.1
  Using cached bs4-0.0.1-py3-none-any.whl

When trying to convert models, I get that : 
  File "D:\text-generation-webui\convert-to-torch.py", line 10, in <module>
    from transformers import AutoModelForCausalLM
ModuleNotFoundError: No module named 'transformers'

The only thing missing from the requirements is : 
ERROR: Could not find a version that satisfies the requirement mkl-fft==1.3.1 (from versions: none)
ERROR: No matching distribution found for mkl-fft==1.3.1

Can someone help me? It was working find 2 days ago.

**Comment by oobabooga** [comment]
Are you activating the conda environment with `conda activate textgen` prior to running these commands?
