### ISSUE TITLE
Opened Ai Api not working

### ISSUE THREAD

**Issue by TomiLikesToCode** [oobabooga/text-generation-webui#3908]
### Describe the bug

I tried using api with flowise because i cant find any other local llm api only localai and that is not working
but when i try to make a request via api i get error 503

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Put "--extensions openai" in CMD_FLAGS.txt and run start_windows.bat then make a request to a model that is installed

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/122990495/4a95acb9-0eed-40fc-b4bf-3eb653c82453)
Flowise image

### Logs

```shell
bin D:\AI\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117_nocublaslt.dll
2023-09-13 20:18:46 INFO:Loading the extension "openai"...
2023-09-13 20:18:47 INFO:Loading the extension "gallery"...
OpenAI compatible API ready at: OPENAI_API_BASE=http://127.0.0.1:5001/v1
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
127.0.0.1 - - [13/Sep/2023 20:20:27] "POST /v1/chat/completions HTTP/1.1" 503 -
127.0.0.1 - - [13/Sep/2023 20:20:28] "POST /v1/chat/completions HTTP/1.1" 503 -
127.0.0.1 - - [13/Sep/2023 20:20:30] "POST /v1/chat/completions HTTP/1.1" 503 -
127.0.0.1 - - [13/Sep/2023 20:20:34] "POST /v1/chat/completions HTTP/1.1" 503 -
127.0.0.1 - - [13/Sep/2023 20:20:48] "POST /v1/chat/completions HTTP/1.1" 503 -
127.0.0.1 - - [13/Sep/2023 20:21:17] "POST /v1/chat/completions HTTP/1.1" 503 -
```

### System Info

```shell
GTX 1060
Intel core i7-4770TE
16gb ram
```

**Comment by MinervaArgus** [comment]
You need to load a model first

**Comment by yhyu13** [comment]
@TomiLikesToCode Should you close this issue if it solved, please?
