### ISSUE TITLE
Chat keyboard shortcuts conflict with standard OS ones for cursor movement. Please allow disabling them?

### ISSUE THREAD

**Issue by MovingSymbols** [oobabooga/text-generation-webui#3915]
**Description**

The new chat keyboard shortcuts conflict with standard OS shortcuts for cursor movement when editing text (example: CTRL-Right is move cursor to next word) but the new keyboard shortcuts hijack this.

The result is frequent and accidental chat interactions such as triggering "continue" when attempting to move a cursor to edit text in the window before sending. CTRL-Up is also "move cursor up one line" but this gets turned into "remove last reply". The results are not ideal.

**Additional Context**

Providing an option to disable the keyboard shortcuts entirely (or at least turn off the CTRL- ones) would provide a workaround.

**Comment by oobabooga** [comment]
Eh, I didn't think of that. The best solution would be to find keyboard shortcuts without conflicts.

**Comment by MovingSymbols** [comment]
Well, CTRL- up/down/left/right move cursor up/down one line, and forward/back one word, respectively.
CTRL-Home is send cursor to beginning of text, 
CTRL-End is send cursor to end of text.

Avoiding those ought to do it, for Windows at least. On a Mac it's a mixture of CMD and OPTION. There's a summary I found here for cursor movement shortcuts for text: https://dev.to/jakewitcher/keyboard-shortcuts-for-moving-the-cursor-in-a-text-editor-o03

**Comment by Touch-Night** [comment]
> Eh, I didn't think of that. The best solution would be to find keyboard shortcuts without conflicts.

It would be even better if users could customize the keyboard shortcut layout.

**Comment by oderwat** [comment]
> Eh, I didn't think of that. The best solution would be to find keyboard shortcuts without conflicts.

Or just to bring back the buttons. Which were working just perfect instead of being stubborn to the user requests.

**Comment by MovingSymbols** [comment]
New keyboard shortcuts look great. Thanks!
