### ISSUE TITLE
rwkv 0.4.2 requires torch~=1.13.1, but you have torch 2.0.0 which is incompatible.

### ISSUE THREAD

**Issue by Murcielagoz99** [oobabooga/text-generation-webui#397]
### Describe the bug

Will not complete a clean install with torch & rwkv.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

This is using the simple installer.

I have looked high and low and cannot find 'torch-2.0.0'.

I also attempted to install torch 1.13.1 manually using pip and I get the same error.

After install, the application loads into CPU-only mode and provides the following message in the console.

Warning: torch.cuda.is_available() returned False.
This means that no GPU has been detected.
Falling back to CPU mode.

Please help!

### Logs

```shell
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 1.13.1
    Uninstalling torch-1.13.1:
      Successfully uninstalled torch-1.13.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rwkv 0.4.2 requires torch~=1.13.1, but you have torch 2.0.0 which is incompatible.
Successfully installed torch-2.0.0
```

### System Info

```shell
Windows 11
RTX 3080
```

**Comment by AlexysLovesLexxie** [comment]
Just had this happen upon performing a fresh install as well.  I'm using CPU as I do not have a worthy GPU.

**Comment by oobabooga** [comment]
rwkv has a torch dependency, which it shouldn't. I have removed it from requirements.txt until the author fixes this
