### ISSUE TITLE
docs, more info needed for API in wiki

### ISSUE THREAD

**Issue by chrisbward** [oobabooga/text-generation-webui#399]
### Describe the bug

https://github.com/oobabooga/text-generation-webui/wiki/Extensions

"and set the API URL to http://127.0.0.1:5000/api. "

how does one go about doing that? 

is that some kind of command line flag, or a setting in a config file?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

docs

### Logs

```shell
docs
```

### System Info

```shell
docs
```

**Comment by oobabooga** [comment]
That phrase refers to a setting inside the TavernAI interface.
