### ISSUE TITLE
TheBloke/Llama-2-13B-chat-GPTQ not loading using llama.cpp model loader on windows

### ISSUE THREAD

**Issue by Shreeyash01** [oobabooga/text-generation-webui#4003]
### Describe the bug

Error Message - 

Traceback (most recent call last):

File “D:\sih\oobabooga_windows\text-generation-webui\modules\ui_model_menu.py”, line 194, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File “D:\sih\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 77, in load_model

output = load_func_map[loader](model_name)
File “D:\sih\oobabooga_windows\text-generation-webui\modules\[models.py](http://models.py/)”, line 226, in llamacpp_loader

model_file = list(Path(f'{shared.args.model_dir}/{model_name}').glob('*.gguf'))[0]
IndexError: list index out of range

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

-

### Screenshot

-

### Logs

```shell
-
```

### System Info

```shell
-
```

**Comment by Liam-Nothing** [comment]
Same error

**Comment by ionescofung** [comment]
Same error :
2023-09-20 11:32:24 INFO:Loading Llama-2-7B-Chat-GGML...
2023-09-20 11:32:24 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/data/pyenv/tgwebui/text-generation-webui/modules/ui_model_menu.py", line 194, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
  File "/data/pyenv/tgwebui/text-generation-webui/modules/models.py", line 76, in load_model
    output = load_func_map[loader](model_name)
  File "/data/pyenv/tgwebui/text-generation-webui/modules/models.py", line 225, in llamacpp_loader
    model_file = list(Path(f'{shared.args.model_dir}/{model_name}').glob('*.gguf'))[0]
IndexError: list index out of range

**Comment by missionfloyd** [comment]
GGML isn't supported anymore. Use GGUF.
https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF

**Comment by Shreeyash01** [comment]
Thank you.

**Comment by Sqrlly** [comment]
Thanks!  I had to switch from GGML to GGUF too and working now!

I might recommend a more user friendly error message letting people know the model type is no longer supported and the suggested new type.
