### ISSUE TITLE
Bot not using its own name.

### ISSUE THREAD

**Issue by AlexysLovesLexxie** [oobabooga/text-generation-webui#401]
### Describe the bug

This issue may be unique to Kawaii (fresh install, haven't tested thoroughly) but when I asked her her name she returned `<bot>` as her reply instead of her name, butin the reply itself it was only a blank space. I had to load the line with "copy last reply" to see the tag.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Ask Kawaii her name.

### Screenshot

![Screenshot 2023-03-18 025159](https://user-images.githubusercontent.com/126999069/226101968-931e9581-8f82-4b2a-8b84-a557ca768eb4.png)

### Logs

```shell
none
```

### System Info

```shell
Windows 11
CPU only, No GPU
CPU : Ryzen 7 6800H
RAM : 32 Gb
```

**Comment by AlexysLovesLexxie** [comment]
This feels like the `<user>` bug all over again, only with the bot name this time.

**Comment by Ph0rk0z** [comment]
What does it sent when you put on verbose? The <BOT> placeholder not getting replaced?

**Comment by AlexysLovesLexxie** [comment]
> What does it sent when you put on verbose? The placeholder not getting replaced?

you mean the verbose profile, or `--verbose` in the startup batch file?
I will try both and post my findings.
