### ISSUE TITLE
GBNF prompting/BNF sampling support for llama.cpp

### ISSUE THREAD

**Issue by IkariDevGIT** [oobabooga/text-generation-webui#4019]
**Description**

Implement GBNF prompting/BNF sampling for UI and API please.

**Additional Context**

please implemet this [this](https://github.com/ggerganov/llama.cpp/blob/master/grammars/README.md)

**Comment by kalomaze** [comment]
I would really appreciate if custom GBNF was prioritized. It got added to kobold and it's been very helpful in controlling outputs; the main issue is the lack of people paying attention to it, imo.

<img width="821" alt="image" src="https://github.com/oobabooga/text-generation-webui/assets/66376113/7d81e058-bd5b-4c7f-8a7a-aaf22b3fe2f2">
