### ISSUE TITLE
API critical issue

### ISSUE THREAD

**Issue by dejanp777** [oobabooga/text-generation-webui#4027]
### Describe the bug

When I am sending message to  streaming server API (/api/v1/stream) via websockets from nodejs, I am getting error bellow. Everything worked few hours ago, so I am suspecting newest update broke the code.

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Reproduction

  request = {
    user_input: questions[question_index],
    max_new_tokens: 250,
    auto_max_new_tokens: false,
    max_tokens_second: 0,
    history: history,
    mode: "chat",
    character: "Example",
    instruction_template: "Vicuna-v1.1",
    your_name: "Dex",
    name1: 'Dex', // Optional
    name2: 'Chloe', // Optional
    //'context': 'character context', # Optional
    greeting: "Hello <USER> nice to meet you! My name is <BOT>", //Optional
    //'name1_instruct': 'You', # Optional
    //'name2_instruct': 'Assistant', # Optional
    //'context_instruct': 'context_instruct', # Optional
    //'turn_template': 'turn_template', # Optional
    prompt: "hello",
    regenerate: false,
    _continue: false,
    chat_instruct_command:
      'Continue the chat dialogue below. Write a single reply for the character "Example".\n\n',

    //Generation params. If 'preset' is set to different than 'None', the values
    //in presets/preset-name.yaml are used instead of the individual numbers.
    preset: "None",
    do_sample: true,
    temperature: 0.7,
    top_p: 0.1,
    typical_p: 1,
    epsilon_cutoff: 0,
    eta_cutoff: 0,
    tfs: 1,
    top_a: 0,
    repetition_penalty: 1.18,
    repetition_penalty_range: 0,
    top_k: 40,
    min_length: 0,
    no_repeat_ngram_size: 0,
    num_beams: 1,
    penalty_alpha: 0,
    length_penalty: 1,
    early_stopping: false,
    mirostat_mode: 0,
    mirostat_tau: 5,
    mirostat_eta: 0.1,
    guidance_scale: 1,
    negative_prompt: "",

    seed: -1,
    add_bos_token: true,
    truncation_length: 2048,
    ban_eos_token: false,
    skip_special_tokens: true,
    stopping_strings: [],
  };
  
  globalClient.send(JSON.stringify(request));

### Logs

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/server.py", line 240, in handler
    await self.ws_handler(self)
  File "/usr/local/lib/python3.10/dist-packages/websockets/legacy/server.py", line 1186, in _ws_handler
    return await cast(
  File "/content/text-generation-webui/extensions/api/streaming_api.py", line 93, in _handle_connection
    await _handle_chat_stream_message(websocket, message)
  File "/content/text-generation-webui/extensions/api/util.py", line 148, in api_wrapper
    return await func(*args, **kwargs)
  File "/content/text-generation-webui/extensions/api/streaming_api.py", line 60, in _handle_chat_stream_message
    generate_params = build_parameters(body, chat=True)
  File "/content/text-generation-webui/extensions/api/util.py", line 70, in build_parameters
    name1, name2, _, greeting, context, _ = load_character_memoized(character, str(body.get('your_name', shared.settings['name1'])), shared.settings['name2'], instruct=False)
KeyError: 'name2'
```

### System Info

```shell
Using Google Colab
```

**Comment by oobabooga** [comment]
Thanks for reporting. I believe that it should be fixed now.
