### ISSUE TITLE
One click installer only create installer_files folder and then stop

### ISSUE THREAD

**Issue by Touch-Night** [oobabooga/text-generation-webui#4041]
### Describe the bug

Fresh install  
`start_windows.bat` stops at [`(conda deactivate && conda deactivate && conda deactivate) 2>nul`](https://github.com/oobabooga/text-generation-webui/blob/4b4d283a4c422b46956af81ec7c59e91d51586e5/start_windows.bat#L21)  
I have conda 22.11.1 correctly installed and PATH variable correctly configured

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

git clone in a new folder, and follow the one click installation (run `start_windows.bat`).

### Logs

```shell
Nothing in command-line.
```

### System Info

```shell
Windows 10  
Nvidia RTX 3050Ti Laptop (modified to 8GB VRAM)  
Conda 22.11.1
```

**Comment by Touch-Night** [comment]
@rem the `conda deactive` line will make the one click installation work.

**Comment by jllllll** [comment]
Making a PR to remove the conda deactivate commands.
I can't figure out why this is broken. I can only assume that it is yet another CMD bug.
