### ISSUE TITLE
illegal instruction

### ISSUE THREAD

**Issue by thistleknot** [oobabooga/text-generation-webui#4053]
### Describe the bug

I took a very long path (https://github.com/ggerganov/llama.cpp/discussions/3323)

llama.cpp runs on gpu just fine with llama-cpp-python and/or main or llama_cpp imported

but when I try to run
python server.py --listen --api --model="./models/llama-2-7b-chat.Q2_K.gguf" --n-gpu-layers 24 --threads 2 --n_ctx 2048

or
(textgen) root@m4700:~/text-gen-install/text-generation-webui# python server.py --listen --api --model="./models/llama-2-7b-chat.Q2_K.gguf"

I get an illegal instruction

I tried looking at modules for llamacpp and indeed I can walk through import llamacpp just fine
```
from llama_cpp import Llama
llm = Llama(model_path="./models/llama-2-7b-chat.Q2_K.gguf",n_gpu_layers=32)
output = llm("Q: Name the planets in the solar system? A: ", max_tokens=32, stop=["Q:", "\n"], echo=True)
print(output)


```

![image](https://github.com/oobabooga/text-generation-webui/assets/5154106/72ac2ac8-5dfc-4f69-bdae-a0da3ae72460)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

llama.cpp built with cublas and avx and cuda 12.2 on oracle linux 8

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/5154106/9f8d7259-ecbb-4eb8-9eb1-bca7dc91f798)

./main -m /root/text-gen-install/text-generation-webui/models/llama-2-7b-chat.Q2_K.gguf --color -c 2048 --keep -1 -t 3 -b 10 -i -ins -ngl 24

![image](https://github.com/oobabooga/text-generation-webui/assets/5154106/cf3b4ee8-c664-47d7-952c-e7097fd9f911)
![image](https://github.com/oobabooga/text-generation-webui/assets/5154106/004fc493-9df6-4895-91ac-6c45eab85595)

### Logs

```shell
(textgen) root@m4700:~/text-gen-install/text-generation-webui# !1332
python server.py --listen --api --model="./models/llama-2-7b-chat.Q2_K.gguf" --n-gpu-layers 24 --threads 2 --n_ctx 2048
2023-09-23 15:56:34 INFO:Loading llama-2-7b-chat.Q2_K.gguf...
2023-09-23 15:56:34 INFO:llama.cpp weights detected: models/llama-2-7b-chat.Q2_K.gguf
2023-09-23 15:56:34 INFO:Cache capacity is 0 bytes
Illegal instruction
(textgen) root@m4700:~/text-gen-install/text-generation-webui#
```

### System Info

```shell
llama-cpp-python to work with cublas and avx and cuda 12.2 on oracle linux 8
```

**Comment by thistleknot** [comment]
I had to specifically pick these settings

i.e. cpu, low vram (may not have been necessary)

then it stopped failing

![image](https://github.com/oobabooga/text-generation-webui/assets/5154106/d34f28e4-d082-4c12-bf5b-7ea4bc595fee)

**Comment by dillfrescott** [comment]
Same error on my system, selecting cpu does not help. Please reopen this
