### ISSUE TITLE
Exlv2 8.13bit max quants output gibberish

### ISSUE THREAD

**Issue by 11415142513152119** [oobabooga/text-generation-webui#4089]
### Describe the bug

8.13bit exlv2 quants of some models output gibberish in the Webui.
I have done some quantization testing and determined that:
1) Some models do not exhibit that behavior at 8.13bit
2) Some models do
3) The models that do exhibit it, do not do so on quants lower than 8.13bit
4) It is not the fault of the measurements.json required for 8.13bit max quantization
5) The models that are broken in Ooba's, work perfectly fine in SillyTavern
Those factors make me believe that something in 8.13bit quants prevents some part of the tokenizer that some models require from loading in the Webui.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1) Download a 8.13bit exl2 quant, eg QMB15/mythomax-13B-8.13bit-MAX-exl2
2) Try to generate

### Screenshot

![1](https://github.com/oobabooga/text-generation-webui/assets/146097564/0500ac8a-cc18-4430-aedb-44211d4f75a2)
![2](https://github.com/oobabooga/text-generation-webui/assets/146097564/2232ff1f-3104-49c6-b552-f79ea9920563)

### Logs

```shell
Nothing relevant.
```

### System Info

```shell
Linux
```

**Comment by oobabooga** [comment]
I confirm that it generates gibberish, but only small prompts. For long ones (like 750 tokens) it generates coherent text.

In all likelihood, that's a quantization problem where the perplexity is too high when the context is small. I'd tell turboderp about it at https://github.com/turboderp/exllamav2

**Comment by 11415142513152119** [comment]
Oh, so it does. It's weird that some models don't exhibit this but getting a longer prompt does fix it.
