### ISSUE TITLE
[New Multiple modal LLM] Add NExT-GPT to multi-modal pipeline

### ISSUE THREAD

**Issue by yhyu13** [oobabooga/text-generation-webui#4105]
**Description**

[NExT-GPT](https://github.com/NExT-GPT/NExT-GPT)

NExt-GPT is built on top of existing pre-trained LLM, multimodal encoder and SoTA diffusion models, with sufficient end-to-end instruction tuning.

![image](https://github.com/oobabooga/text-generation-webui/assets/19365678/034b6cfe-338f-4e5f-8f54-5277e9706a4f)

Multimodal Encoding Stage. Leveraging established encoders to encode inputs in various modalities, where these representations are projected into language-like representations comprehensible to the LLM through a projection layer.
LLM Understanding and Reasoning Stage. Harnessing an existing open-sourced LLM as the core to process input information for semantic understanding and reasoning. The LLM not only directly generates text tokens but also produces unique “modality signal” tokens that serve as instructions to dictate the decoding layers whether & what modal content to output correspondingly.
Multimodal Generation Stage. Receiving the multimodal signals with specific instructions from LLM (if any), the Transformer-based output projection layers map the signal token representations into the ones that are understandable to following multimodal decoders.
For more technical details, kindly refer to the [paper](https://arxiv.org/pdf/2309.05519.pdf).

**Additional Context**

**Comment by saphtea** [comment]
This would be incredible!

**Comment by ChristianCCastro** [comment]
😺

**Comment by yhyu13** [comment]
It seems next gpt has trouble in making its offical demo running though https://github.com/NExT-GPT/NExT-GPT/issues/24.

So we need to suspend this
