### ISSUE TITLE
Docs request: superbooga README

### ISSUE THREAD

**Issue by jamesbraza** [oobabooga/text-generation-webui#4114]
**Description**

Can we add a `README` to the superbooga and superbooga v2 extensions just stating what they're for?

Where are docs on these extensions?  I am wondering what their useful to accomplish.

**Comment by jamesbraza** [comment]
Cc @HideLord since you just worked with this a bunch

**Comment by strikaco** [comment]
On all of the interface tabs, there is a nondescript dropdown that says "Click for more information..."

There is no indication that it has anything to do with superbooga, but there's where you'll find the docs.

```
About

This extension takes a dataset as input, breaks it into chunks, and adds the result to a local/offline Chroma database.

The database is then queried during inference time to get the excerpts that are closest to your input. The idea is to create an arbitrarily large pseudo context.

The core methodology was developed and contributed by kaiokendev, who is working on improvements to the method in this repository: https://github.com/kaiokendev/superbig
Data input

Start by entering some data in the interface below and then clicking on “Load data”.

Each time you load some new data, the old chunks are discarded.
Chat mode
Instruct

On each turn, the chunks will be compared to your current input and the most relevant matches will be appended to the input in the following format:

Consider the excerpts below as additional context:
...

The injection doesn’t make it into the chat history. It is only used in the current generation.
Regular chat

The chunks from the external data sources are ignored, and the chroma database is built based on the chat history instead. The most relevant past exchanges relative to the present input are added to the context string. This way, the extension acts as a long term memory.
Notebook/default modes

Your question must be manually specified between <|begin-user-input|> and <|end-user-input|> tags, and the injection point must be specified with <|injection-point|>.

The special tokens mentioned above (<|begin-user-input|>, <|end-user-input|>, and <|injection-point|>) are removed in the background before the text generation begins.

Here is an example in Vicuna 1.1 format:

A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.

USER:

<|begin-user-input|>
What datasets are mentioned in the text below?
<|end-user-input|>

<|injection-point|>

ASSISTANT:

⚠️ For best results, make sure to remove the spaces and new line characters after ASSISTANT:.

This extension is currently experimental and under development.

```

**Comment by jamesbraza** [comment]
Thanks for the response!

<img width="602" alt="screenshot of tabs" src="https://github.com/oobabooga/text-generation-webui/assets/8990777/4f12270f-7d61-49e7-b2ce-b53a0f7c7ba1">

Which one is the inferences tab?  I am trying to figure out how to navigate to the "Click for more information..." button

---

Also, the source code behind that description is here: https://github.com/oobabooga/text-generation-webui/blob/06fff3b2e918f37e0c7d477d111a08d042e72968/extensions/superboogav2/script.py#L178

**Comment by jamesbraza** [comment]
Update, I figured it out:

1. Session tab --> check superboogav2 under Available extensions --> select Apply flags/extensions and restart
2. Chat tab --> scroll down to controls --> "Click for more information..." dropdown is there below the Character gallery dropdown

I can make a quick README for this at some point

**Comment by oliverban** [comment]
Sure, I can get it activated and it is working. But entering a, let's say URL, into URL List and then asking the AI about that specific URL gives nothing. How are we suppose to work with it? The "Click for more information" Dropdown says nothing about it.

**Comment by strikaco** [comment]
> Sure, I can get it activated and it is working. But entering a, let's say URL, into URL List and then asking the AI about that specific URL gives nothing. How are we suppose to work with it? The "Click for more information" Dropdown says nothing about it.

Make sure you clicked on "load data" to actually retrieve the content from the URLs! This is easy to overlook!

For INSTRUCT-chat mode, you don't have to do anything more-- it should work as it is I think. If you ask about topics found at that URL, it should tell you about the associated content. **For regular chat mode, it ignores all of this** and is only used to retain an "infinite" memory as you go.

For notebook mode, you have to update your template to show where in your question the external content should be embedded as supplementary material. Use this template to start with-- the docs say this is for Vicuna, but it works well enough on Mistral and anything else trained as Alpaca:
```
A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.

USER:

<|begin-user-input|>
What datasets are mentioned in the text below?
<|end-user-input|>

<|injection-point|>

ASSISTANT:

```
If we use URL `http://textfiles.com/reports/broadpro.txt`, and ask for a written rebuttal, this is what gets sent over the wire:

```
A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.

USER:
Write a rebuttal to this article.

Consider the excerpts below as additional context:
This is an important movie for the broadcasting industry for many
   reasons.  Fisrt of all, to my knowledge there never before was a movie
   that dealt with the programming aspect of the broadcasting industry
   before (except for Switching Channels, which was released at approximately
   the same time).  Also, this movie depicts many things common to the 
   broadcasting world in a way which the average moviegoing viewer can relate
   to them, the same ones who watch the prime-time television news that this
   movie centers about.
     Moreover, Broadcast News shows the pressures and demands involved with
   broadcasting.  A great deal of work goes into the little subtleties in
   television situations that before I watched this movie I had taken for 
   granted.  One instance that sticks out in my head is when actress Holly
   Hunter and the rest of the news staff in Washington raced to get a tape
   into the machine which was to be broadcast nationally; the characters had
   talked like it was such a big deal if it were a few seconds late.  At 
   first, I didn't think that this was such a big deal; when an anchorman on
   a television news program announces a special report and there is a four
   or five second delay during which everything is blacked out, I noticed that
   I became slightly irritated, but not much.  But when you are dealing with a
   national audience and battling between two other major networks for the
   same people at the same time, I suppose that little things like this mean a
   lot.  Also, when Holly and her partner went on a special assignment to a
   warfront, they risked their lives for a thirty second spot on the newscast.
   It was incredible to realize that this happens every day, on three major
   networks, all for advertising dollars.  Even the small things like I
   mentioned earlier apparently mean a whole lot to the networks; in the
   movie Jack Nicholson laid off a slew of the Washington staff, "all because
   they just couldn't program Wednesday nights."
     Another thing that the movie did was to portray a bad image for anchor
   people, writing most of them off as people who just have to look good and
   not understand anything at all about what they are reporting about.  This 
   is also related to the subject of favoritism, in which a job is given to
   someone by who they know or what they look like rather than how they can 
   actually perform.  This often leads to the wrong person getting the job,
   and is common in any business industry (like in our resume worksheets in
   which the woman, who was better qualified, did not get the job).
     Lastly, this movie puts broadcasting in the spotlight - it exposes the
   weaknesses of commerciality in a comical, almost satrical way.  It shows
   how programming is often unoriginal, and how bad choices are made by
   programming executives in today's world in hopes of more money.  But if any
   of this is true, it is not just the programmer's fault - they need a job,
   and the networks need to operate.  Without advertising money, they cannot
   do that.  And advertisers won't pay to advertise on networks that people
   don't watch.  So maybe the movie is important because it shows the viewers
   that we could be our own biggest enemies by demanding shallow, stale
   television programming instead of fresh and different things.  In doing
   this, cleverly enough, the movie makes one big satire of itself.

ASSISTANT:
```
It likely won't retrieve the full article, just some snippets semantically-related to the question. This sounds screwy but works well in practice-- for example if your question specifically has to do with the topic of `advertisers`, it will pull in only the parts of the text related to advertising so you don't waste context with extraneous stuff.

Give it a shot and see if this works for you.

**Comment by tuxthepenguin84** [comment]
Anyone else having issues getting this extension to do anything? The extension loads fine and I copy in text and load it and then try to ask it questions about it but it appears to just respond nonsensically. I've tried also loading data from a URL but again it does the same thing. I even tried the exact scenario above with the prompt and loading data from http://textfiles.com/reports/broadpro.txt it seems to hallucinate a completely nonsensical answer. I've tried different models as well. Looking at the log there are no errors. I'm unsure of what I'm doing wrong.

**Comment by strikaco** [comment]
> Anyone else having issues getting this extension to do anything? The extension loads fine and I copy in text and load it and then try to ask it questions about it but it appears to just respond nonsensically. I've tried also loading data from a URL but again it does the same thing. I even tried the exact scenario above with the prompt and loading data from http://textfiles.com/reports/broadpro.txt it seems to hallucinate a completely nonsensical answer. I've tried different models as well. Looking at the log there are no errors. I'm unsure of what I'm doing wrong.

That's odd that it's happening across models.

I hate to nag, but in the chat interface, you selected Instruct, not Chat, right? Chat mode completely ignores your superbooga input because it uses it for extended chat history. Asking the chat-mode AI Assistant about stuff in the superbooga context will absolutely yield hallucinated nonsense...because it's not reading your context. You have to set it to Instruct mode to discuss your context.

Also check `Parameters > Instruct Template > Instruction Template` and make sure that reflects your choice of model. If in doubt, Alpaca usually works, but try to pick the right one.

My previous example advice above might be a little outdated (came directly from the docstring). Try this prompt in Default/Notebook instead:
```
Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

<|begin-user-input|>
### Instruction:
Write a 250-word summary of the text that captures the key points.
<|end-user-input|>

<|injection-point|>

### Response:
```
It does work; it returns for me (Mistral-7b-OpenOrca):
```
"Broadcast News" is a significant film for the broadcasting industry as it offers an insight into various aspects that are commonly experienced in the field. The movie highlights the competitive nature of news reporting and programming, showcasing how networks strive to capture viewers' attention with engaging content while also dealing with commercial pressures and demands from advertisers. It also emphasizes the importance of timing, precision, and teamwork within broadcasting teams.

The film portrays a negative image of anchors as individuals who often lack substance or understanding about the topics they report on, leading to instances of favoritism in hiring decisions. This theme is further explored through the characters' personal lives and relationships. Additionally, "Broadcast News" exposes the challenges faced by programmers working within commercial constraints, as they must balance creative vision with financial considerations from network executives.

Lastly, the movie serves as a commentary on viewer demand for shallow entertainment over more substantive content. By highlighting these issues, "Broadcast News" encourages viewers to reflect upon their role in perpetuating this cycle and potentially inspires them to demand higher quality programming from networks. Overall, the film offers a thought-provoking exploration of the broadcasting industry's inner workings while also raising important questions about media consumption habits and societal expectations.
```

**Comment by tuxthepenguin84** [comment]
I'm using TheBloke_Dolphin-Llama2-7B-GPTQ

I'm using Vicuna instruction template

URL Input: https://en.wikipedia.org/wiki/American_Civil_War
I load the text

Output
```
A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.

<|begin-user-input|>
USER:
Write a 250-word summary of the text that captures the key points.
<|end-user-input|>

<|injection-point|>
ASSISTANT: In this engaging conversation, a curious user discusses various topics with an artificial intelligence assistant. The AI provides informative, well-detailed, and courteous responses to address the user's concerns effectively. Overall, it is evident that both parties are eager to share knowledge and ensure a pleasant interaction.
```

**Comment by tuxthepenguin84** [comment]
If I unload the superboogav2 plugin, set the chat mod to instruct and paste in some text and tell it to summarize the text it appears to do that just fine though. 🤷🏻

**Comment by strikaco** [comment]
> If I unload the superboogav2 plugin, set the chat mod to instruct and paste in some text and tell it to summarize the text it appears to do that just fine though. 🤷🏻

Oh...if I read you right, I couldn't get v2 working myself. My examples assumed v1.

**Comment by tuxthepenguin84** [comment]
I haven't been able to get v1 installed and loaded. Well anyways thanks for your help.

**Comment by RandomInternetPreson** [comment]
> I haven't been able to get v1 installed and loaded. Well anyways thanks for your help.
I can't find it in any of the documentation, but if you are in the instruct chat tab you need to type "!c" before your question for the AI to reference the chroma database, I saw this in a random reddit post.  I have no clue how they figured it out.  I couldn't get v2 to work for me, it would digest the text but the AI would not reference the text unless I typed !c before my query of the text.

**Comment by strikaco** [comment]
> > I haven't been able to get v1 installed and loaded. Well anyways thanks for your help.
> > I can't find it in any of the documentation, but if you are in the instruct chat tab you need to type "!c" before your question for the AI to reference the chroma database, I saw this in a random reddit post.  I have no clue how they figured it out.  I couldn't get v2 to work for me, it would digest the text but the AI would not reference the text unless I typed !c before my query of the text.

Since we're talking about v2, it has a different docstring:

```
About

This extension takes a dataset as input, breaks it into chunks, and adds the result to a local/offline Chroma database.

The database is then queried during inference time to get the excerpts that are closest to your input. The idea is to create an arbitrarily large pseudo context.

The core methodology was developed and contributed by kaiokendev, who is working on improvements to the method in this repository: https://github.com/kaiokendev/superbig
Data input

Start by entering some data in the interface below and then clicking on "Load data".

Each time you load some new data, the old chunks are discarded.
Chat mode
Instruct

On each turn, the chunks will be compared to your current input and the most relevant matches will be appended to the input in the following format:

Consider the excerpts below as additional context:
...

The injection doesn't make it into the chat history. It is only used in the current generation.
Regular chat

The chunks from the external data sources are ignored, and the chroma database is built based on the chat history instead. The most relevant past exchanges relative to the present input are added to the context string. This way, the extension acts as a long term memory.
Notebook/default modes

Your question must be manually specified between <|begin-user-input|> and <|end-user-input|> tags, and the injection point must be specified with <|injection-point|>.

The special tokens mentioned above (<|begin-user-input|>, <|end-user-input|>, and <|injection-point|>) are removed in the background before the text generation begins.

Here is an example in Vicuna 1.1 format:

A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.

USER:
<|injection-point|>

<|begin-user-input|>What datasets are mentioned in the text above?<|end-user-input|>
ASSISTANT:
```
Notice that the order of the placeholders changed.

The `!c` thing is actually in the settings for v2, as the tooltip for the `is manual` checkbox. When manual mode is active, you have to do the `!c` thing but it doesn't work for me in any mode whether or not it's set. I get the impression it's supposed to be automatic like v1 otherwise.

**Comment by RandomInternetPreson** [comment]
@strikaco thanks for the reply I really appreciate it :3 SuperboogaV2 is amazing! I hope more people jump on board and start using it too.
