### ISSUE TITLE
Running the Alpaca LoRA does not work on GPU

### ISSUE THREAD

**Issue by Arargd** [oobabooga/text-generation-webui#412]
### Describe the bug

When attempting to run the LoRA on GPU results in nothing happening.

This occurs for my non-wsl, wsl, and seperate Linux boot on my machine. 

It does however generate and work properly when using the --cpu option. 

Also to note I had to replace the bitsandbytes_cpu.so with bitsandbytes_cuda117.so to function, if its in any way related.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

run the command-line: python server.py --listen --load-in-8bit, select 7b weights, go to parameters, select alpaca-lora-7b, using default prompt and parameters select generate, nothing happens other than a log with 0 tokens and a transformers warning.

### Logs

```shell
Output generated in 0.23 seconds (0.00 tokens/s, 0 tokens)

C:\Users\Arargd\miniconda3\envs\textgen\lib\site-packages\transformers\generation\utils.py:1374: UserWarning: You are calling .generate() with the `input_ids` being on a device type different than your model's device. `input_ids` is on cuda, whereas the model is on cpu. 
You may experience unexpected behaviors or slower generation. 
Please make sure that you have put `input_ids` to the correct device by calling for example input_ids = input_ids.to('cpu') before running `.generate()`.
```

### System Info

```shell
Windows 10 (both WSL and non WSL)
Linux Ubuntu 22.04.2
RTX 2070 8GB
32 GB 3600 MHz DDR4 RAM
```

**Comment by bartman081523** [comment]
can you give me a full log on your linux when running
`python server.py --listen --load-in-8bit --model llama-7b --lora alpaca-lora-7b
`and then generate a text?

 I guess that issue is related to my issue #383

**Comment by bartman081523** [comment]
It would help if you could post a full log of your wsl, non-wsl and linux machine, 
when running `python server.py --listen --load-in-8bit --model llama-7b --lora alpaca-lora-7b` and then generate text.

**Comment by bartman081523** [comment]
You can try this
https://github.com/oobabooga/text-generation-webui/issues/400#issuecomment-1474876859

**Comment by Arargd** [comment]
> You can try this [#400 (comment)](https://github.com/oobabooga/text-generation-webui/issues/400#issuecomment-1474876859)

I have commented in that issue, but yes that works for getting me to generate normally without LoRA. With LoRA attached it refuses to generate anything on GPU, however.

**Comment by bartman081523** [comment]
https://www.reddit.com/r/LocalLLaMA/comments/11o6o3f/how_to_install_llama_8bit_and_4bit/
https://github.com/oobabooga/text-generation-webui/issues/332

also please post a log, and have you updated the repo with `git pull`?
