### ISSUE TITLE
openAI API, token limit change ?

### ISSUE THREAD

**Issue by ramzeez88** [oobabooga/text-generation-webui#4152]
Is there a way to change token limit ? the current one is set to 2048 and I would like to change it to 4096.

**Comment by LanceLake** [comment]
go into your \text-generation-webui\extensions\openai\completions.py file and change the following.

#    req_params['truncation_length'] = shared.settings['truncation_length']
req_params['truncation_length'] = 8192

**Comment by ramzeez88** [comment]
> go into your \text-generation-webui\extensions\openai\completions.py file and change the following.
> 
> Replace req_params['truncation_length'] = shared.settings['truncation_length'] with req_params['truncation_length'] = 4096
> 
> It's a dirty fix, but it works.

This is it, thanks LanceLake :)

**Comment by bigsk1** [comment]
solved an issue I was having getting autogen to not max out on 2048 tokens. thanks
