### ISSUE TITLE
Correctly encode special tokens with exllama

### ISSUE THREAD

**Issue by grimulkan** [oobabooga/text-generation-webui#4183]
Not sure if I should label this as a bug, but when tokenizing text that has egs., EOS/BOS in it, we'd want the tokenizer to recognize the special tokens and tokenize correctly. This is important egs., in chat models which include `<s>` and `</s>` in the turn format (egs., Llama-chat).

I believe this requires passing `encode_special_tokens=True` in exllamav2 0.0.5 (which is not yet available in the pip installable package) when calling `tokenizer.encode` in the `exllamav2.py` module

If anyone knows better, let me know.

**Comment by Dampfinchen** [comment]
Open Orca Mistral has <|im_end|> as the EOS token, so yes special token support is very important.

**Comment by grimulkan** [comment]
This is now fixed in latest commit. Thanks!
