### ISSUE TITLE
Impossible resolution of `autoawq` for Python 3.11

### ISSUE THREAD

**Issue by jamesbraza** [oobabooga/text-generation-webui#4211]
### Describe the bug

Resolution of `autoawq` is currently impossible with Python 3.11:

```
> pip install -r requirements.txt
...
  ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11; 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
  ERROR: Could not find a version that satisfies the requirement autoawq==0.1.4 (from versions: none)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

With Python 3.11, run `pip install -r requirements.txt` on https://github.com/oobabooga/text-generation-webui/tree/d33facc9feea19158420ddcbc842509825a4e88b

### System Info

```shell
2021 MacBook with M1, macOS Ventura 13.5.2
```

**Comment by jamesbraza** [comment]
Cc @casper-hansen

**Comment by yhyu13** [comment]
@jamesbraza 

py 3.11 is currently poorly compatible. Have you tried to install autoawq from source? Pulled the autoawq repo and hit pip install -e . to install autoawq locally with py3.11.

It could be the case the author just has not built the package for py3.11 yet.

**Comment by casper-hansen** [comment]
AutoAWQ is compatible with Python 3.11: https://github.com/casper-hansen/AutoAWQ/releases/download/v0.1.4/autoawq-0.1.4-cp311-cp311-linux_x86_64.whl

**Comment by jamesbraza** [comment]
Thanks for the responses!  So, I am on macOS, which Python wheels see as different from Linux.

Trying to install `autoawq==0.1.4` outside of `text-generation-webui` into a fresh Python 3.11.4 virtual environment:

```bash
> pip install autoawq==0.1.4
Looking in indexes: https://pypi.org/simple, <redacted>
ERROR: Could not find a version that satisfies the requirement autoawq==0.1.4 (from versions: none)
ERROR: No matching distribution found for autoawq==0.1.4
```

So I don't think 3.11 with macOS is working

**Comment by casper-hansen** [comment]
> Thanks for the responses! So, I am on macOS, which Python wheels see as different from Linux.
> 
> Trying to install `autoawq==0.1.4` outside of `text-generation-webui` into a fresh Python 3.11.4 virtual environment:
> 
> ```shell
> > pip install autoawq==0.1.4
> Looking in indexes: https://pypi.org/simple, <redacted>
> ERROR: Could not find a version that satisfies the requirement autoawq==0.1.4 (from versions: none)
> ERROR: No matching distribution found for autoawq==0.1.4
> ```
> 
> So I don't think 3.11 with macOS is working

Oh, that makes better sense. AutoAWQ is only compatible with Nvidia GPUs and is not built for macOS

**Comment by oobabooga** [comment]
Use python 3.10 as instructed in the readme.

**Comment by jamesbraza** [comment]
It may make sense to add a `platform_system` specifier to the `pip install autoawq` line, like what's done for `exllamav2`.

It may also be good to make the 3.10 requirement more obvious, as it's only mention in the `README` is in `conda` environment creation instructions.  It not explicitly stated anywhere that 3.11 or 3.12 aren't supported.
