### ISSUE TITLE
How can I use the WebUI and model locally with GPU on a remote Linux VM?

### ISSUE THREAD

**Issue by matt-sharp** [oobabooga/text-generation-webui#4220]
I have a M with 2 x GPUS and plenty of RAM using a Linux environment which I connect to remotely using SSH.  How can I use TextGenWebUI to query the model using my remote VM?

**Comment by strikaco** [comment]
Install ooba on the remote machine and tunnel the ports using your ssh client.

You don't mention what you're connecting *from*. (I don't remember the ooba port offhand-- if it's not 7860, replace that to whatever it is.)

On Windows/Putty, go to `Connection > SSH > Tunnels`, set source port to `7860` and destination to `localhost:7860`. Save that to a profile, then launch it. Now on your client machine, go to `localhost:7860` on your web browser and everything is presented like you're using ooba while sitting at the remote box.

On Linux (and Apple?) using ssh from the commandline, I think the syntax is something like `ssh -C remotehost -L 7860:localhost:7860` which will achieve the same thing on your web browser, `localhost:7860`. The `-C` just enables compression.

**Comment by matt-sharp** [comment]
I solved the problem by using the share option:

`--share | Create a public URL. This is useful for running the web UI on Google Colab or similar.`




</body>
</html>
