### ISSUE TITLE
Deleted my log by oobabooga

### ISSUE THREAD

**Issue by mykeehu** [oobabooga/text-generation-webui#4222]
### Describe the bug

The program simply reset my log. The next steps were:
- when sending the chat text, the text was not sent.
- I refreshed the browser with F5, the text was left there in the text input.
- turned off the CMD window and restarted oobabooga, but left the browser
- when oobabooga started as a second instance browser, I closed the second window and sent the text in the first window.
- all my conversations with this character disappeared. It wiped the log. I didn't have a save either.

It would at least open a new file, but no. It overwrote the old one. It should check the previous file, and if it is not zero or a few bytes, don't overwrite it, but create a new one from the old copy and continue.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I can reproduce:
1. open an existing chat with a character (save before!)
2. close CMD and leave open browser window and start oobabooga again.
3. when the second window opens, close it and send something in the first window or press Remove last reply. Done, your chat log is deleted.

### Logs

```shell
None.
```

### System Info

```shell
i9-13900K
64 GB RAM
RTX 3090 12 GB
Windows 10
Chrome (latest)
```

**Comment by oobabooga** [comment]
Inflammatory title

**Comment by mykeehu** [comment]
I can rename the title, but that doesn't bring me back to my weekly chat...
