### ISSUE TITLE
flash_attn_2_cuda preventing the Web UI from starting

### ISSUE THREAD

**Issue by ashleykleynhans** [oobabooga/text-generation-webui#4238]
### Describe the bug

I am using commit: `2e471071af48e19867cfa522d2def44c24785c50`

And getting the following error:

```
Starting Oobabooba Text Generation UI: --listen --api --listen-port 3001 --api-blocking-port 5001 --api-streaming-port 5006
2023-10-09 07:04:12 WARNING:
You are potentially exposing the web UI to the entire internet without any access password.
You can create one with the "--gradio-auth" flag like this:

--gradio-auth username:password

Make sure to replace username:password with your own.
Traceback (most recent call last):
  File "/workspace/text-generation-webui/server.py", line 30, in <module>
    from modules import (
  File "/workspace/text-generation-webui/modules/chat.py", line 18, in <module>
    from modules.text_generation import (
  File "/workspace/text-generation-webui/modules/text_generation.py", line 24, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/workspace/text-generation-webui/modules/models.py", line 22, in <module>
    from modules import RoPE, llama_attn_hijack, sampler_hijack
  File "/workspace/text-generation-webui/modules/llama_attn_hijack.py", line 7, in <module>
    import transformers.models.llama.modeling_llama
  File "/workspace/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 45, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/workspace/venv/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/workspace/venv/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 8, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /workspace/venv/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
```
I did not experience this issue with commit `12220ad6e80194cdbec7f406b1a950835d4b9518`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Check out commit `2e471071af48e19867cfa522d2def44c24785c50` and install on Linux using CUDA 11.8.

### Logs

```shell
Starting Oobabooba Text Generation UI: --listen --api --listen-port 3001 --api-blocking-port 5001 --api-streaming-port 5006
2023-10-09 07:04:12 WARNING:
You are potentially exposing the web UI to the entire internet without any access password.
You can create one with the "--gradio-auth" flag like this:

--gradio-auth username:password

Make sure to replace username:password with your own.
Traceback (most recent call last):
  File "/workspace/text-generation-webui/server.py", line 30, in <module>
    from modules import (
  File "/workspace/text-generation-webui/modules/chat.py", line 18, in <module>
    from modules.text_generation import (
  File "/workspace/text-generation-webui/modules/text_generation.py", line 24, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/workspace/text-generation-webui/modules/models.py", line 22, in <module>
    from modules import RoPE, llama_attn_hijack, sampler_hijack
  File "/workspace/text-generation-webui/modules/llama_attn_hijack.py", line 7, in <module>
    import transformers.models.llama.modeling_llama
  File "/workspace/venv/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 45, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/workspace/venv/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/workspace/venv/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 8, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: /workspace/venv/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
```
```


### System Info

* RunPod Docker image.
* Ubuntu 22.04 LTS.
* Nvidia A5000 GPU.

**Comment by caterpillarpants** [comment]
I am having this issue too for a few days. I tried the fixes proposed at #4182, but to no avail, Then I tried the solutions proposed at #4172 and I admit I was a bit over my head, and didn't reinstall exllama2 from source, but I'm not using exllama2 to my knowledge. Anyway, I monkeyed with pytorch and flash_attention versions and couldn't get text-generation-webui to run.

I then did update_linux.sh and pip install -r requirements.txt, which hopefully reset webui to current, but it still doesn't start the web-ui.

my error:
`site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi`

my system:
nvidia 2070
linux mint 21.1

**Comment by ashleykleynhans** [comment]
Seems to have been introduced by this change:

https://github.com/oobabooga/text-generation-webui/commit/d33facc9feea19158420ddcbc842509825a4e88b#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R45

If I manually install the previous version of flash-attention, the Web UI starts successfully:

```bash
pip3 install https://github.com/Dao-AILab/flash-attention/releases/download/v2.3.0/flash_attn-2.3.0+cu117torch2.0cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
```

**Comment by Timboman** [comment]
> Seems to have been introduced by this change:
> 
> [d33facc#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R45](https://github.com/oobabooga/text-generation-webui/commit/d33facc9feea19158420ddcbc842509825a4e88b#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R45)
> 
> If I manually install the previous version of flash-attention, the Web UI starts successfully:
> 
> ```shell
> pip3 install https://github.com/Dao-AILab/flash-attention/releases/download/v2.3.0/flash_attn-2.3.0+cu117torch2.0cxx11abiFALSE-cp310-cp310-linux_x86_64.whl
> ```

Worked for my me, added this as a step to my DockerFile after the normal requirements.txt installation and now it's back to running as normal.

Thanks a ton!

**Comment by caterpillarpants** [comment]
Just updated and the web-ui now starts but the error reappears when trying to load a transformers model.

```
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):

/home/ana/text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi
```

**Comment by Ph0rk0z** [comment]
Uninstall flash attention.

**Comment by caterpillarpants** [comment]
Uninstalling flash attention did not work for me. Also I have noticed that none of my vicuna models work. Both vicuna 1.5 and the older one produce this error.

the others seem to work, so it's not all transformers models, just vicuna.

I hope this helps.

**Comment by Thireus** [comment]
Manually compiling exllamav2 worked for me https://github.com/oobabooga/text-generation-webui/issues/4182#issuecomment-1759512052

**Comment by caterpillarpants** [comment]
I ended up solving by doing a fresh install. now everything works again!

**Comment by tuxthepenguin84** [comment]
The following worked for me.

pip3 uninstall flash-attn
pip3 install -r requirements.txt
pip3 install bitsandbytes==0.38.1

Note the older version of bitsandbytes (I have a Tesla P40)

**Comment by ashleykleynhans** [comment]
> I ended up solving by doing a fresh install. now everything works again!

@caterpillarpants Can you confirm whether the fresh install works with or without uninstalling flash attention?

**Comment by ashleykleynhans** [comment]
Looks like a fresh install fixed it for me too, thanks!

**Comment by caterpillarpants** [comment]
> > I ended up solving by doing a fresh install. now everything works again!
> 
> @caterpillarpants Can you confirm whether the fresh install works with or without uninstalling flash attention?

the fresh install worked without uninstalling flash attention.

**Comment by binzhwang** [comment]
It works for me, thanks
