### ISSUE TITLE
LLaMa wont load when using deepspeed

### ISSUE THREAD

**Issue by catalpaaa** [oobabooga/text-generation-webui#424]
### Describe the bug

LLaMa wont load when using deepspeed, it will just get stucked on

> Loading llama-7b...

and taking up all the ram before freezing the system.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

fellow the tutorial for enable deepspeed, using llama 7b hf.

### Logs

```shell
only log shown is Loading llama-7b...
```

### System Info

```shell
3080ti 12gb on ubuntu 22
```

**Comment by catalpaaa** [comment]
Also it looks like whenever the model is splite into mutilple bins then stuff just freeze.
To me, deepspeed just doesnt wanna use the swap, it takes up all the buff/cache then dose nothing.
![image](https://user-images.githubusercontent.com/89681913/226373280-e45df0e5-bb45-463c-8d91-b6f45cf53119.png)

**Comment by cyrcule** [comment]
> Also it looks like whenever the model is splite into mutilple bins then stuff just freeze. To me, deepspeed just doesnt wanna use the swap, it takes up all the buff/cache then dose nothing. ![image](https://user-images.githubusercontent.com/89681913/226373280-e45df0e5-bb45-463c-8d91-b6f45cf53119.png)

Have you found a way to force deepspeed to use swap?
