### ISSUE TITLE
webui not starting

### ISSUE THREAD

**Issue by schnapper79** [oobabooga/text-generation-webui#4262]
### Describe the bug

I run the webui on a server within my vpn, with ssh portforwarding.

When ever i connect to the server, i get the screen shown in the screenshot (a missplaced dialog to delete a character).Clicking on delete obviously delets a character ( from the log:
```
2023-10-11 07:41:42 INFO:Deleted characters/Example.yaml.
2023-10-11 07:41:42 INFO:Deleted characters/Example.png.
2023-10-11 07:41:47 INFO:Deleted characters/Zora.yaml.
2023-10-11 07:41:52 INFO:Deleted characters/Zora_001.yaml.
```
), until it ran out of possible characterfiles. Still the dialog can't be closed.

The js-console shows a funny error, trying to get a script from` https://127.0.0.1` hardcoded.
`<script src="https://127.0.0.1/ajax/libs/iframe-resizer/4.3.1/iframeResizer.contentWindow.min.js"></script>`

Other than that is the log pretty empty:
```
Launching text-generation-webui with args: --listen --api
2023-10-11 08:00:37 WARNING:
You are potentially exposing the web UI to the entire internet without any access password.
You can create one with the "--gradio-auth" flag like this:

--gradio-auth username:password

Make sure to replace username:password with your own.
2023-10-11 08:00:41 INFO:Loading settings from settings.yaml...
2023-10-11 08:00:41 INFO:Loading the extension "gallery"...
```

![2023-10-11_10-06](https://github.com/oobabooga/text-generation-webui/assets/27971627/af9266c6-089f-4e9f-abc9-8fbb8234512f)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

for me just using bloke's template on runpod, seems like a normal checkout of main.

### Logs

```shell
see issue text
```

### System Info

```shell
runpod, bloke's template
```

**Comment by qsniyg** [comment]
Try running `pip install 'gradio==3.47.*'` within the venv.

**Comment by zlsl** [comment]
> Try running `pip install 'gradio==3.47.*'` within the venv.

This fixes issue

**Comment by somenewaccountthen** [comment]
> Try running `pip install 'gradio==3.47.*'` within the venv.

My hero :)
(Just had this, confirm this fixed it. It was trying to get some .js file from port 80 for some reason)
