### ISSUE TITLE
gradio queueing never ending

### ISSUE THREAD

**Issue by Jasperb3** [oobabooga/text-generation-webui#4267]
### Describe the bug

After latest update, I'm not able to use the webui

A new 'queue' has appeared in all text input fields the counter doesn't seem to end. 

Getting error messages about Task exception never retrieved and AttributeError: __aenter__ on site-packages\gradio\queueing.py

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Git pull on latest commit
pip install -U -r requirements.txt

### Screenshot

<img width="616" alt="Screenshot 2023-10-11 181616" src="https://github.com/oobabooga/text-generation-webui/assets/141338069/afbb5e96-3ebe-4061-b09d-0d3126747aa0">

### Logs

```shell
(textgen) C:\Users\sss\text-generation-webui>python server.py --sdp-attention --auto-launch
bin C:\Users\sss\anaconda3\envs\textgen\lib\site-packages\bitsandbytes\libbitsandbytes_cuda118.dll
2023-10-11 18:08:12 INFO:Loading settings from settings.yaml...
2023-10-11 18:08:12 INFO:Loading the extension "edge_tts"...
2023-10-11 18:08:16 WARNING:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.1.0+cu118)
    Python  3.10.11 (you have 3.10.9)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
2023-10-11 18:08:16 WARNING:Triton is not available, some optimizations will not be enabled.
This is just a warning: No module named 'triton'
2023-10-11 18:08:16 WARNING:A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
Found GPU NVIDIA GeForce RTX 3080 Ti Laptop GPU
Loading hubert model...
C:\Users\sss\anaconda3\envs\textgen\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Hubert model loaded.
Loading rmvpe model...
rmvpe model loaded.
2023-10-11 18:08:24 INFO:Loading the extension "superboogav2"...
2023-10-11 18:08:24 DEBUG:Intercepting all calls to posthog.
2023-10-11 18:08:25 DEBUG:Creating Sentence Embedder...
2023-10-11 18:08:27 WARNING:Using embedded DuckDB without persistence: data will be transient
2023-10-11 18:08:27 DEBUG:Loading hyperparameters...
2023-10-11 18:08:27 INFO:Loading the extension "gallery"...
2023-10-11 18:08:27 INFO:Loading the extension "long_replies"...
2023-10-11 18:08:27 INFO:Loading the extension "sd_api_pictures"...
2023-10-11 18:08:27 INFO:Loading the extension "Twinbook"...
C:\Users\sss\anaconda3\envs\textgen\lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: DPM++ 2M Karras or set allow_custom_value=True.
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-10-11 18:08:30 ERROR:Task exception was never retrieved
future: <Task finished name='Task-8' coro=<Queue.start_processing() done, defined at C:\Users\sss\anaconda3\envs\textgen\lib\site-packages\gradio\queueing.py:127> exception=AttributeError('__aenter__')>
Traceback (most recent call last):
  File "C:\Users\sss\anaconda3\envs\textgen\lib\site-packages\gradio\queueing.py", line 137, in start_processing
    async with self.delete_lock:
AttributeError: __aenter__
```

### System Info

```shell
Windows 11
Nvidia 3080 ti
```

**Comment by Ph0rk0z** [comment]
You can also just try to roll gradio back and see if that helps. Worth a try before rolling back the whole thing.

**Comment by Jasperb3** [comment]
Thanks for your advice @Timboman  - it's back up and running again on commit https://github.com/oobabooga/text-generation-webui/commit/2b75d725e636c84add48a89d1186d6374e2a6724 

Pity not to be able to use the extensions after latest updates but hopefully they'll get updated too before long

**Comment by Ph0rk0z** [comment]
> 4 other dependencies were removed from the various requirements.txt files that are needed for the older version of Gradio to work.

When they disappear from there they aren't removed from your system.

**Comment by BuffMcBigHuge** [comment]
Glad to see you using https://github.com/BuffMcBigHuge/text-generation-webui-edge-tts. I'm not 100% sure how to fix this issue atm with the updated gradio, but it seems the `git checkout 2b75d725e636c84add48a89d1186d6374e2a6724 && pip install -r requirements.txt` does the trick.

**Comment by Jasperb3** [comment]
Yes, it does seem that edge_tts was causing the issue. Have removed the extension and pulled the latest commit and the webui works well - even with other plugins. So I'll close this issue. Let me know if you want me to open one up on the extension's page. edge_tts was the best TTS extension for Oobabooga so hope you find a fix for whatever is causing it

**Comment by BuffMcBigHuge** [comment]
@Jasperb3 I have updated the [edge_tts](https://github.com/BuffMcBigHuge/text-generation-webui-edge-tts) extension to fix the async issue caused by the gradio update. You should be able to use it again!

**Comment by Jasperb3** [comment]
I changed line 10 of modules.py to:
from torch.nn.utils import weight_norm, remove_weight_norm

and now it's working! but I still get this warning: 
C:\Users\sss\anaconda3\envs\textgen\lib\site-packages\torch\nn\utils\weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")

**Comment by BuffMcBigHuge** [comment]
@Jasperb3 Not sure about that one, I believe that's related to your version of torch. I went ahead and updated the inference pack from [Retrieval-based-Voice-Conversion-WebUI](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI). I don't think there is any difference with torch parameterizations however.
