### ISSUE TITLE
Using <|user|> internally in webui collides with Zephyr prompt

### ISSUE THREAD

**Issue by JohanAR** [oobabooga/text-generation-webui#4292]
### Describe the bug

"<|user|>", "<|bot|>" and "<|user-message|>" are used internally by webui when generating prompts, but the Zephyr prompt also uses "<|user|>" so it should not be substituted if present in the prompt template.

Example Zephyr prompt:
```
<|system|>
You are a friendly chatbot who always responds in the style of a pirate.</s>
<|user|>
How many helicopters can a human eat in one sitting?</s>
<|assistant|>
Ah, me hearty matey! But yer question be a puzzler! A human cannot eat a helicopter in one sitting, as helicopters are not edible. They be made of metal, plastic, and other materials, not food!
```

Source: https://huggingface.co/HuggingFaceH4/zephyr-7b-alpha

Some ideas for possible solutions:
1. Change the tag format "<|xxx|>" to something else, e.g. "{{xxx}}" or "$xxx$" and hope that no model starts using this in its prompts.
2. Replace "<|user|>" with something else, e.g. "<|webuser|>" and hope that no model starts using this in its prompts :)
3. Add the ability to escape things in the prompt in order to prevent webui replacements, e.g. "\\<|user|>" or something if one wants to print "<|user|>" there.

I tried to search for existing issues but github thinks "<|user|>" matches a lot of irrelevant things.. Couldn't find anything that looked like the same thing though.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Try to create prompt for zephyr.

### Logs

```shell
N/A
```

### System Info

```shell
N/A
```

**Comment by berkut1** [comment]
You can create your own template from webui.

**Comment by JohanAR** [comment]
You can't create a template containing the string <|user|> since webui will replace this.

**Comment by baconsplit** [comment]
Thanks to superking in TheBloke discord I have a current instruction template for Zephyr like this:
![image](https://github.com/oobabooga/text-generation-webui/assets/63647668/f5ead63d-e31b-4ea2-b517-3f343ad81cb0)

Normal chat works well like that, but chat-instruct still crashes:
![image](https://github.com/oobabooga/text-generation-webui/assets/63647668/acb5604b-36dc-4074-91b3-11720edba968)

(I am using Zephyr-Beta)
If anyone wants the .yaml right away: 
```user: <|user|>
bot: <|assistant|>
turn_template: <|user|>\n{prompt}</s>\n<|bot|>
context: |+
  <|system|>
  </s>

...
```

**Comment by Dougie777** [comment]
@baconsplit The docs say that the Instruction Template is not used in Chat mode, but is used in chat-instruct mode.  So this explains the currect behaviour and the bug persists ...

**Comment by thijse** [comment]
Same problem here. Too bad, because Zephyr is one of the best small LLM currently available

**Comment by JohanAR** [comment]
Perhaps @oobabooga has some opinion on what would be the best solution for this, and then I or another contributor could do the actual implementation? I don't want to create a PR based on my own assumptions, since changing this might affect a lot of users.

**Comment by jepeloa** [comment]
Hi, this template was working for me:

user: "<|user|>"
bot: "<|assistant|>"
turn_template: "<|user|>\n<|user-message|></s>\n<|bot|><|bot-message|>"
context: "
  <|system|><|system-message|>
  </s>"
system_message: ""
