### ISSUE TITLE
Clean xformers install under windows?

### ISSUE THREAD

**Issue by bombel28** [oobabooga/text-generation-webui#4341]
I am not sure to write but or feature request. After last update, I had to acknowledge, that there is no transformers support for flash attention 2 yet. Now I try to downgrade. Manually, I could reach that, but when using update_windows.bat, xformers does not work. Maybe, it did not work before, too.
Maybe, I have only some problems getting right dependencies.
Does this depend on triton, which is not available for windows 11?

Sure, I could use exllama2, but without 4Bit support. So I have no memory efficient way to train under windows with a 13b llama2 model on a RTX 4090?
Please help me getting out of this situation. Normal 4Bit training is working, but it is slow.

**Comment by Ph0rk0z** [comment]
xformers didn't work with torch 2.1 had to be compiled. which is good for me I guess because I need cuda 6.1 and 8.6 and I think they don't release 6.1 builds anymore.

I don't think it uses triton so you are fine there.

**Comment by bombel28** [comment]
BTW: I tried a 7b Llama-2 model in exllama2. Can‘t start training. In transformers, training is slow as usual.

**Comment by bombel28** [comment]
maybe it was because of using start script directly while reinstalling. xformers is working again.
