### ISSUE TITLE
Gradio error when selecting new saved training parameters (gradio 3.5)

### ISSUE THREAD

**Issue by bombel28** [oobabooga/text-generation-webui#4363]
### Describe the bug

When starting new training (or continue with old one), training-params are saved to file. Because I thought, this happens with old training params, I did a small test training with new written params in gui. After reloading everything, I still cannot select previously saved training params. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Start new llama training in transformers, press refresh on list of saved training params, load last training parameters.

### Logs

```shell
dropdown.py", line 229, in <listcomp>
    if self.allow_custom_value or y in [value for _, value in self.choices]:
ValueError: too many values to unpack (expected 2)
```

### System Info

```shell
Windows 11, latest update of text-generation-webui
```

**Comment by bombel28** [comment]
works after restart

**Comment by bombel28** [comment]
works only 1x after restart

**Comment by FartyPants** [comment]
It would be good to see what values are in the self.choices when the error occurs.

**Comment by bombel28** [comment]
this is creepy... another day... no ability to reproduce that... Browser cache? I reopen with more errror log, if it appears again.
