### ISSUE TITLE
Installer stuck for an hour on Loading the extension "gallery"...

### ISSUE THREAD

**Issue by Methanoutput** [oobabooga/text-generation-webui#4392]
### Describe the bug

Tried to install this for the first time and my installer is stuck on the line:

`2023-10-26 00:20:51 INFO:Loading the extension "gallery"...`

I tried this an hour ago and had the same issue, does this really take this long or is something wrong?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I just started the installer.

### Logs

```shell
-
```

### System Info

```shell
OS: Windows
GPU: Asus Geforce RTX 4070 Dual
I do not use Google Colab.
```

**Comment by missionfloyd** [comment]
It' should be done at that point. Do you see `Running on local URL:`? Try going to http://127.0.0.1:7860

**Comment by Methanoutput** [comment]
oh yes it already works! But no it does not say running on local url. Sorry for wasting your time and thanks for the help.
