### ISSUE TITLE
Unable to install llama_cpp_python

### ISSUE THREAD

**Issue by vadi2** [oobabooga/text-generation-webui#4428]
### Describe the bug

While we were able to previously run the text-generation-webui just fine on this machine, we're not longer able to when setting up for another user. What could be the issue?

```sh
conda activate textgen
python -m pip install -r requirements.txt 

Ignoring exllamav2: markers 'platform_system != "Darwin" and platform_machine != "x86_64"' don't match your environment
Collecting git+https://github.com/oobabooga/torch-grammar.git (from -r requirements.txt (line 28))
  Cloning https://github.com/oobabooga/torch-grammar.git to /tmp/pip-req-build-hk3tdafk
  Running command git clone --filter=blob:none --quiet https://github.com/oobabooga/torch-grammar.git /tmp/pip-req-build-hk3tdafk
  Resolved https://github.com/oobabooga/torch-grammar.git to commit 82850b5383a629f3b0fa1fba7d8f2aba3185ddb2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Ignoring bitsandbytes: markers 'platform_system == "Windows"' don't match your environment
ERROR: llama_cpp_python-0.2.11-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl is not a supported wheel on this platform.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See above

### Logs

```shell
See above
```

### System Info

```shell
A100 GPU on Ubuntu 22.04 LTS.
```

**Comment by Ph0rk0z** [comment]
Compile it from scratch.

**Comment by trigun117** [comment]
same here

**Comment by vadi2** [comment]
Yep, compiling from scratch worked. The instructions say to use python=3.11 in the conda environment, but llama_cpp_python wheelis for 3.10.

**Comment by cyizhuo** [comment]
Just taking notes on how to compile from scratch:

1. create conda env
2. pip install pytorch
3. conda install -y -c "nvidia/label/cuda-12.1.0" cuda-runtime
NOW a few steps different with main document.
4. pip install -r requirements_nowheels.txt
5. build llama backend with https://github.com/abetlen/llama-cpp-python#clblast
