### ISSUE TITLE
Factual answer: ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇

### ISSUE THREAD

**Issue by moelahmady** [oobabooga/text-generation-webui#446]
### Describe the bug

I get factual answers in  ??  like this Factual answer: ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Common sense questions and answers

Question:  Hi
Factual answer: ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇  ⁇

### Screenshot

<img width="1535" alt="Screenshot 2023-03-20 at 12 43 35 AM" src="https://user-images.githubusercontent.com/25454015/226214371-e9424c75-6b81-4189-9865-70446b62235d.png">

### Logs

```shell
Loading LLaMA-7b...
Loading checkpoint shards: 100%|██████████████████████████████████████| 33/33 [00:06<00:00,  5.47it/s]
Loaded the model in 147.25 seconds.
Output generated in 12.96 seconds (4.71 tokens/s, 61 tokens)
Output generated in 13.20 seconds (0.61 tokens/s, 8 tokens)
```

### System Info

```shell
MacOS Ventura 13.2.1, Apple M1 Max
```

**Comment by oobabooga** [comment]
Probably an incompatible model, try downloading the decapoda one

```
python download-model.py decapoda-research/llama-7b-hf

```

**Comment by moelahmady** [comment]
> 

I have the same HF model
<img width="1596" alt="Screenshot 2023-03-20 at 12 51 27 AM" src="https://user-images.githubusercontent.com/25454015/226214748-909656a9-c7db-4a18-b77d-3156a54eeb2d.png">

**Comment by moelahmady** [comment]
> The HF implementation changed over time. The initial conversions are now broken.

Will I be able to run the 13B one on Mac M1?

**Comment by oobabooga** [comment]
No idea, but I think that it should work

**Comment by moelahmady** [comment]
> Probably an incompatible model, try downloading the decapoda one
> 
> ```
> python download-model.py decapoda-research/llama-7b-hf
> ```

Fixed after redownloading the model suggested above
