### ISSUE TITLE
ExLlamaV2 - Not Functioning / Import Error 

### ISSUE THREAD

**Issue by agahEbrahimi** [oobabooga/text-generation-webui#4479]
### Describe the bug

Ever since this morning, the editor is failing to run any model using the ExLlamav2 loader, throwing the following error in the attempt to use it. 

`Traceback (most recent call last):

File "/workspace/text-generation-webui/modules/ui_model_menu.py", line 208, in load_model_wrapper

shared.model, shared.tokenizer = load_model(shared.model_name, loader)
File "/workspace/text-generation-webui/modules/models.py", line 84, in load_model

output = load_func_map[loader](model_name)
File "/workspace/text-generation-webui/modules/models.py", line 348, in ExLlamav2_loader

from modules.exllamav2 import Exllamav2Model
File "/workspace/text-generation-webui/modules/exllamav2.py", line 6, in

from exllamav2 import (
ImportError: cannot import name 'ExLlamaV2Cache_8bit' from 'exllamav2' (/usr/local/lib/python3.10/dist-packages/exllamav2/init.py)`

I tried reverting to an older commit, but it made no difference, I also reinstalled all packages, but to no avail. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Select a model compatible with ExLlamaV2 and click load. 

### Logs

```shell
N/A
```

### System Info

```shell
A6000 instance on runpod.io.
```

**Comment by AtomisteBX** [comment]
Same issue, however I came up with a temporary fix that has the side effect of removing 8bit cache to exllama models until this is fixed. But it's better than just being unable to load models.


**in text-generation-webui/modules/exllamav2.py, remove the following lines;**

line 9 : 
`    ExLlamaV2Cache_8bit,`

line 61, 62 and 63 :
```
         if shared.args.cache_8bit:
            cache = ExLlamaV2Cache_8bit(model)
        else:
```

**in text-generation-webui/modules/exllamav2_hf.py, remove the following lines;**

line 10 :
`    ExLlamaV2Cache_8bit,`

lines 48, 49 and 50 :
```
        if shared.args.cache_8bit:
            self.ex_cache = ExLlamaV2Cache_8bit(self.ex_model)
        else:
```

That's all that's needed, i wish i had more knowledge to actually give a fix but this works for me, so if you don't need 8bit cache, there you go...

**Comment by Ph0rk0z** [comment]
You have to update exllama v2.

**Comment by chrisbennight** [comment]
> You have to update exllama v2.

Ah, so expectation is master is broken until exllamav2 cuts a new wheel release and https://github.com/oobabooga/text-generation-webui/blob/main/requirements.txt#L5 is updated?

in general should we pull in dependencies from their master branches/not use requirements.txt,  or is the expectation that master may not build and only snapshots under releases are safe - or was this just a whoops, since everything is moving at light speed?

(Not trying to nit pick, really appreciate the work - just want to understand the project norms)

**Comment by ManickenThroane** [comment]
I am having the same problem, but I'm new to this. Can someone give me a pointer - where do I go to make the edits proposed by @AtomisteBX?

**Comment by ManickenThroane** [comment]
...or maybe the suggestion from @chrisbennight can be used instead, I see - this, I know how to do.

**Comment by noneabove1182** [comment]
Can also give a different docker image a try, I have one here that's updated to 12.1.1: https://github.com/noneabove1182/text-generation-webui-docker

**Comment by chrisbennight** [comment]
Should be working with this change - https://github.com/TheBlokeAI/dockerLLM/issues/8

**Comment by agahEbrahimi** [comment]
It's working now.
