### ISSUE TITLE
Elevenlabs extension has a bug do not use it

### ISSUE THREAD

**Issue by if-ai** [oobabooga/text-generation-webui#451]
### Describe the bug

the elevenlabs extension sent the same request in a loop for each new token crated it sent a request to the api until the full answer was completed.
I had a maximum of 200 tokens so it 😢blew all my months quota almost 15$ of tokens 
I just installed it to try it out but stupid me notice something was wrong and didn't stop it.
I am not blaming anyone or being a Karen, the idea is great, but I have a couple of suggestions besides fixing the error, one I would like the character to still give me the answer in txt and second that it only produces the text first and then the audio if I like the answer or if I select to auto generate the audio that would be nice in an option.  thanks

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

the elevenlabs extension 

### Screenshot

![msedge_wLH3vhSAlf](https://user-images.githubusercontent.com/21185218/226353516-129a799a-8cc7-4e8d-a8bb-1c31cac4ef82.png)

### Logs

```shell
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\Uzr\anaconda3\envs\textgen\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Uzr\anaconda3\envs\textgen\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

### System Info

```shell
Win 10 no WSL
Nvidia RTX 3090 
RAM 32GB 
AMD Ryzen 7 1700
```

**Comment by oobabooga** [comment]
Add `--no-stream`. These tts extensions are not meant to be used with streaming.

**Comment by if-ai** [comment]
Thank you.
