### ISSUE TITLE
Using OpenAI endpoint causes conflict in ports

### ISSUE THREAD

**Issue by noneabove1182** [oobabooga/text-generation-webui#4510]
### Describe the bug

Using latest from master. 

All combinations of --api, --extensions openai, and even passing neither results in an error on startup: 

OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5000): address already in use

Only way I can fix it is by passing --api-port or --api-blocking-port and reassigning away from 5000

Also always get the warning about API deprecation and to update to using --extensions openai, my guess is a bug is causing --api to always be passed true?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Startup latest from master, pass no API args, note that it'll fail startup with the port 5000 being taken

### Logs

```shell
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5000): address already in use
```

### System Info

```shell
Docker container

Nvidia 3090

Command line args:

"--listen",                                             "--listen-port",
"7860",                                                 "--listen-host",                                        "0.0.0.0",                                              "--api",                                                "--api-blocking-port",
"5002",                                                 "--extensions",
"openai",
"--verbose"
```

**Comment by noneabove1182** [comment]
May be related to my settings.yaml, investigating..

**Comment by chymian** [comment]
same here with the latest git. 1fba6db69f30e7dd4d1aed9ab93ce9a41250f855
it's a regression of deprecating api and moving openai to default.
ubu 20.04, 4 x 3070

**Comment by chymian** [comment]
@noneabove1182 it's a serious bug, pls open the issue again.

**Comment by noneabove1182** [comment]
@chymian forgot to comment after, I did find out it was my settings.yaml conflicting, I had it loading 'api' by default regardless of my command line args
