### ISSUE TITLE
API is now "deprecated"?

### ISSUE THREAD

**Issue by nonnull-ca** [oobabooga/text-generation-webui#4536]
I updated text-generation-webui this morning and now I'm getting a nasty deprecation message for using the same set of APIs I have been using throughout, with an ominous warning that it will stop working in 4 days. And this is the first I've heard of it - I had heard about and thought it was great that text-generation-webui was also getting support for other APIs; I have been blindsided by the main API being deprecated.

I had been using text-generation-webui as an intermediate API instead of directly using backend APIs largely so I wouldn't have to chase backend churn, as I had thought that one of the major purposes of text-generation-webui was to provide a reasonably stable wrapper around the continually-in-flux backends, similar to sd-webui's API - and indeed up until now text-generation-webui had mostly satisfied that goal.

Is this a non-goal of text-generation-webui? If so, any suggestions for replacement projects that do have stable APIs?

If this is a goal of text-generation-webui, any other major breaking changes upcoming, and how can I get >4 days notice or opportunity for feedback before future major breaking changes goes through?

My apologies if this is somewhat cranky. I have attempted to tone this down; I am rather frustrated. This breaks essentially all of my small scripts written around text-generation-webui's API, at very little notice. (It almost would have been _no_ notice - I almost didn't get the chance to update today, and the next time I will have the bandwidth to do so is after November 13th.)

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by oobabooga** [comment]
See the examples, it shouldn't be hard to migrate https://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API#examples

**Comment by Webslug** [comment]
So for clarification we can no longer post to oobabooga from local applications?

**Comment by thewshii** [comment]
I have a video on youtube of it working if you need help.
Don't give up I spent all night on this https://www.youtube.com/watch?v=LsyYCf9Kg7s&t=126s

it shows you how to set up the api

**Comment by thewshii** [comment]
its just python3 server.py --api --api-port [port] and use it like you do on OpenAI, that's all.. i like to use --nowebui after downloading the model it seems that's the only way to do it is on the webui??? idk i've looked in the docs..
