### ISSUE TITLE
Linux rocm bitsandbytes AMD GPU

### ISSUE THREAD

**Issue by ntn888** [oobabooga/text-generation-webui#4558]
### Describe the bug

I get the error `warn("The installed version of bitsandbytes was compiled without GPU support. "` after running `./start_linux.sh`  on my Linux machine with AMD GPU. The past discussions on this topic don't address the issue when running using this script.. So I'm opening this topic..

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I installed ROCm following [this guide](https://github.com/danrauch/HOWTO-PopOS-AMD-HIP-with-Blender).
```
sudo amdgpu-install --usecase=rocm --rocmrelease=5.6.1
```
Then I uncommented the line in `one_click.py`:
```
os.environ["ROCM_PATH"] = '/opt/rocm-5.6.1'
```
but left the other following lines commented:
```
# os.environ["HSA_OVERRIDE_GFX_VERSION"] = '10.3.0'
# os.environ["HCC_AMDGPU_TARGET"] = 'gfx1030'
```
Finally I ran `./start_linux.sh`.

### Logs

```shell
*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


bin /home/ajit/chat/text-generation-webui/installer_files/env/lib/python3.11/site-packages/bitsandbytes/libbitsandbytes_cpu.so
/home/ajit/chat/text-generation-webui/installer_files/env/lib/python3.11/site-packages/bitsandbytes/cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
2023-11-11 10:23:49 INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
Cpu: Intel Xeon E5 2670
Gpu: AMD Radeon™ RX 580 8GB
PopOS 22.04
```

**Comment by lufixSch** [comment]
Take a look at the discussion around this topic in the AMD thread.

This is just a warning and you will be able to use the WebUI without any problems as long as you don't want to use bitsandbytes.

There are a lot of bitsandbytes forks which claim to work with AMD/ROCm but I got none of them working so far (the last time I tried was around 3 Months ago). If you find a working version I would really appreciate some feedback. 
[This](https://github.com/oobabooga/text-generation-webui/issues/3759#issuecomment-1712580341) old setup comment from me contains a list of all ROCm compatible forks I found so far.

**Comment by ntn888** [comment]
Thanks for the response. I've now tried to deploy on cloud GPU instead... Also my GPU isn't that capable.. I've stopped perusing a local installation..

**Comment by lufixSch** [comment]
Great  that you found I solution that works for you.

I am pretty sure you could run some small models (<= 7B) on your GPU with GPTQ or GGUF. Alternatively you could run the Model (or parts of the Model) on CPU. Your CPU seems to be quite capable.

**Comment by ntn888** [comment]
K great thanks. I give it another look.

I did try a CPU model using Llama-GPT, and it was very slow.. took around a minute for each response..

**Comment by lufixSch** [comment]
Which model did you use?

**Comment by ntn888** [comment]
https://github.com/getumbrel/llama-gpt this one.

**Comment by lufixSch** [comment]
Yea that is the tool but it supports multiple models. Depending on which one you used the performance may vary quite a bit.

From the README:

>## Supported models
>
>Currently, LlamaGPT supports the following models. Support for running custom models is on the roadmap.
>
>| Model name                               | Model size | Model download size | Memory required |
>| ---------------------------------------- | ---------- | ------------------- | --------------- |
>| Nous Hermes Llama 2 7B Chat (GGML q4_0)  | 7B         | 3.79GB              | 6.29GB          |
>| Nous Hermes Llama 2 13B Chat (GGML q4_0) | 13B        | 7.32GB              | 9.82GB          |
>| Nous Hermes Llama 2 70B Chat (GGML q4_0) | 70B        | 38.87GB             | 41.37GB         |
>| Code Llama 7B Chat (GGUF Q4_K_M)         | 7B         | 4.24GB              | 6.74GB          |
>| Code Llama 13B Chat (GGUF Q4_K_M)        | 13B        | 8.06GB              | 10.56GB         |
>| Phind Code Llama 34B Chat (GGUF Q4_K_M)  | 34B        | 20.22GB             | 22.72GB         |

**Comment by ntn888** [comment]
oh sorry. The 13b non-code one.

**Comment by lufixSch** [comment]
Okay this model is using an old Quantization. GGML is and old quantization method. Using GGUF might be a bit faster (but not much). Nevertheless I though your CPU would be a little bit faster. 
As I said before I am pretty sure you could run a 7B model on your GPU. The models based on Mistral 7B are all really capable. I would try a GPTQ quantized version with Exllamav2, which is faster than GGUF (at least on AMD). This will be faster than running the 13B on CPU.
Otherwise you could try splitting a 13B Model between GPU and CPU (this only works with GGUF). Depending on how much layers you can fit on your GPU this will improve your inference speed.

But I don't want to give you false hope. It will be most definitely be much slower than running on Cloud GPUs

**Comment by ntn888** [comment]
okay thanks. just a question: I thought low parameters made the LLM dumber? Or is it only matter of speed?
PS: I'm running vicuna-13B-v1.5-16K on the cloud and really liking it.. If I could get similar results locally It'll be great.

**Comment by lufixSch** [comment]
> I thought low parameters made the LLM dumber

Yes this is generally the case. This is why I explicitly mentioned Mistral. Even though it is a 7B Model it performs really well in a lot of tasks often better than a lot of 13B models. On score boards it even outperforms 30B and 70B models but I wouldn't trust them as much.
I can easily run 13B models on my GPU but for day to day tasks like code completion or Q&A I prefer [zephyr-7b](https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF) (based on Mistral). It usually gives similar or better answers compared to the 13B models I use and it is way faster. It is also much better at following orders.

I never compared zephyr and vicuna directly but if you want you can give me some prompts and I test them.

**Comment by ntn888** [comment]
okay thanks a lot. I'll load it on the cloud server and test it out first ;)

**Comment by ntn888** [comment]
just tried out the zephyr-7b. Thanks for the suggestion.. It looks more similar to GPT-4 than Vicuna. But when I put in `chat` mode, code generation suffers. Do you use the `chat` or `instruct` modes?

**Comment by lufixSch** [comment]
For code questions or similar I use `instruct` or sometimes `chat-instruct` mode.
But I mostly use zephyr for Copilot like code completion. In this case the LLM is only prompted with the code up to my cursor. Without any instruct template or context.

**Comment by ntn888** [comment]
k thanks for all your help! zephyr7b does look impressive..

**Comment by ntn888** [comment]
sorry to bother again. I tried loading zephyr-7b-beta.Q5_K_M.gguf on my local system and I get error:
```
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
2023-11-12 04:53:05 INFO:Loading zephyr-7b-beta.Q5_K_M.gguf...
2023-11-12 04:53:05 INFO:llama.cpp weights detected: models/zephyr-7b-beta.Q5_K_M.gguf
2023-11-12 04:53:05 INFO:Cache capacity is 0 bytes

rocBLAS error: Cannot read /home/ajit/chat/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/lib/rocblas/library/TensileLibrary.dat: No such file or directory
Aborted (core dumped)
```

I tried reinstalling with values gfx1030, gfx803 and commenting it out:
```
# os.environ["HSA_OVERRIDE_GFX_VERSION"] = '10.3.0'
# os.environ["HCC_AMDGPU_TARGET"] = 'gfx1030'
```
nothing worked..

**Comment by lufixSch** [comment]
Mhmm I remember having a similar error before but sadly not how I solved it.

[This]() comment from me includes the command to build/install llama-cpp-python from source. Maybe this works.

[The old guide I linked before](https://github.com/oobabooga/text-generation-webui/issues/3759#issuecomment-1712580341) also contains a link where you can look up the GFX version for your GPU.

Even though this most likely doesn‘t cause the problem, I would start with a smaller quant first. Q5_K_M is pretty close to your maximum VRAM. 
Also make sure to check the maximum context size and other llama.cpp settings. The defaults are probably way to high for your GPU.
You could also try ExllamaV2 with a GPTQ version of zephyr.

**Comment by ntn888** [comment]
Hmm I've tried:
>[This](https://github.com/oobabooga/text-generation-webui/issues/4558) comment from me includes the command to build/install llama-cpp-python from source. Maybe this works.

>Also make sure to check the maximum context size and other llama.cpp settings. The defaults are probably way to high for your GPU.
(reducing this to under 1000)

>You could also try ExllamaV2 with a GPTQ version of zephyr.
```
2023-11-12 06:07:26 INFO:Loading TheBloke_zephyr-7B-beta-GPTQ...
Segmentation fault (core dumped)
```

Maybe this could be a GFX version issue. That link didn't specifically mention my card.. `rocminfo` shows gfx803, but not sure of the version..

Thanks again.

**Comment by ntn888** [comment]
Okay got it working!

I had to do the following:
> 3 step - exporte path to rocm
command: `export ROCBLAS_TENSILE_LIBPATH=/opt/rocm/lib/rocblas/library/`
> to verify `echo $ROCBLAS_TENSILE_LIBPATH`
> /opt/rocm/lib/rocblas/library/

from the other thread: https://github.com/oobabooga/text-generation-webui/issues/3759#issuecomment-1804281841

**Comment by ntn888** [comment]
Actually, I think it's loading on CPU. According to radeontop there's no movement on the GPU VRAM..

**Comment by lufixSch** [comment]
Make sure to set the GPU offload layers to the right value (higher should work too)

**Comment by lufixSch** [comment]
If this doesn‘t work: I remember a similar problem where I uninstalled the CPU version for  llama-cpp-python and then it worked.
Usually the WebUI should handle this automatically.

**Comment by ntn888** [comment]
hmm increasing offload layers did help. but ran into segmentation fault again!
```
llm_load_tensors: using ROCm for GPU acceleration
llm_load_tensors: mem required  =   86.03 MB
llm_load_tensors: offloading 32 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 35/35 layers to GPU
llm_load_tensors: VRAM used: 4807.05 MB
...................................................................................................
llama_new_context_with_model: n_ctx      = 32768
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init: offloading v cache to GPU

CUDA error 2 at /home/runner/work/llama-cpp-python-cuBLAS-wheels/llama-cpp-python-cuBLAS-wheels/vendor/llama.cpp/ggml-cuda.cu:7117: out of memory
current device: 0
/arrow/cpp/src/arrow/filesystem/s3fs.cc:2904:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit
```

**Comment by ntn888** [comment]
okay above says `out of memory` I lowered the offload layers to 30 and it loads! but it's not faster.. its still same ~4 tokens/s

**Comment by ntn888** [comment]
Maybe it's a matter of tweaking `n-gpu-layers` and `n_ctx`? Sometimes I get around 10 tokens/s. But it's still pausing with output, and the  experience is poor. If I increase `n_ctx` it crashes with `out of memory`.

And the GPTQ version model still results in segmentation fault.

**Comment by lufixSch** [comment]
`n_ctx` defines the context length, which increases VRAM usage by n^2. 

`n-gpu-layers` decides how much layers will be offloaded to the GPU. Less layers on the GPU will generally reduce inference speed but also VRAM usage.

4 t/s is really slow. I expected around 10 to 12 t/s with your hardware. Which quant are you using now? Still the Q5_K_M or a smaller one. Obviously you get the most speed out of your system if you're able to offload all 35 Layers to you GPU

**Comment by ntn888** [comment]
yes i did set it over 35 layers. I'm still using the Q5_K_M one.

**Comment by ntn888** [comment]
Here's my current setup:

- n-gpu-layers > 35
- n_ctx 2000
- numa checked
- Increase max new tokens to 2000 (in parameters)
- using preset: debug-deterministic

I'm now getting 7-9 t/s. And the generation is fast.

Seems to be working. Thanks for all your help.

**Comment by ntn888** [comment]
just an update on my thought on the models (although I'm not sure if this is the right forum for this..)

On hindsight I've found that vicuna is more capable for my use case: writing articles for my embedded dev blog..

for example if I use the prompt:

"write an article about AliExpress.com"

I get a more creative response. And I prefer it over GPT-4 actually :)

PS: I initially ran `TheBloke/vicuna-13B-v1.5-16K-AWQ`. This is not working anymore with blank responses.. Now I have to use the `TheBloke/vicuna-13B-v1.5-16K-GGUF` model. I dont know if there's any difference between the two.. BTW I'm running them on vast.ai instances.

**Comment by lufixSch** [comment]
Yes creative writing is the one use case, where I prefer larger models.

I have heard, that the OpenHermes-2.5-Mistral-7B-GGUF is better for such tasks but I haven't tested it yet.

>  I dont know if there's any difference between the two.

As the quant method is different there outputs may be a little different in theory but you probably wont notice.

> although I'm not sure if this is the right forum for this

Yes I think as your initial problem has been solved, it would be nice to close the issue. This repo is already overflowing with issues.
There are a lot of discords (TheBloke, Oobabooga ...) and subreddits (LocalLlama ...) for discussing new models and other LLM related topics.

**Comment by ntn888** [comment]
thanks for all your help.. couldnt have done it without it; too many variables and settings..
i'll continue to test the local installation.. as free is better ;) And I'm now thinking vast.ai quickly gets more expensive than the GPT-4. and I like the textgen webui interface :)
