### ISSUE TITLE
Open AI extension not available over local network

### ISSUE THREAD

**Issue by StuckInSprings** [oobabooga/text-generation-webui#4567]
### Describe the bug

When using the openai extension I am unable to connect to the server from another device on the same local network. I can confirm that the route is available, but connecting to it results in a 403 error. Using share or the API extension I can confirm that both of these are accessible on the local network. To ensure that the issue wasn't due to a firewall issue on the host machine I disabled the firewall, yet I found the issue persisted. Is there a setting I'm missing? I read through the documentation but didn't see any special instructions for enabling local network access to the openai extension. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the client with `--extensions openai` and then proceed to attempt to connect to the default route for the openai extension from a client on the same local network. 

### Logs

```shell
N/A
```

### System Info

```shell
Operation system: Macos 14.0
```

**Comment by StuckInSprings** [comment]
Okay, figured it out. The default port that the extension uses 5000 is blocked by Ooba, so you need to manually change the port to something else. Then you can access it from another client on the same network.

**Comment by satelliteoflove** [comment]
The port was also my problem. Thank you very much for reporting the work-around! It is not obvious at all from the messages provided by the interface and CLI.
