### ISSUE TITLE
Your Name / name2 - Not Functioning (API)

### ISSUE THREAD

**Issue by agahEbrahimi** [oobabooga/text-generation-webui#4599]
### Describe the bug

Regardless of what I set the name2 or name2_instruct as, the model is not receiving it and answers incorrectly when I ask it for my name. In the old API, it was your_name and it was functioning properly. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

use API with either chat mode or chat-instruct and send name2 or your_name, and then ask the model for your name through the API. 

### Logs

```shell
N/A
```

### System Info

```shell
N/A
```

**Comment by a-creation** [comment]
Same

**Comment by agahEbrahimi** [comment]
I see, it works with name1, that was also causing some other issues, thank you!!
