### ISSUE TITLE
OpenAI completion API is a downgrade

### ISSUE THREAD

**Issue by SlimeQ** [oobabooga/text-generation-webui#4614]
I have an app running off the old completion API, and I just updated ooba to find my app totally broken.

It seems OpenAI plugin is now the default API, which is fine, but the completion API loses a bunch of parameters like cfg and negative prompt.

According to OpenAI's documentation, they will be killing this API next year anyways. I don't see much value in following OpenAI down this path, chat mode is fine but it's extremely restrictive and takes power out of the developers hands.

**Comment by SlimeQ** [comment]
there just needs to be a way to enable the legacy api I think. currently this is a complete showstopper for me, I just can't update my production machine if I don't want to swap everything over to a new api with different parameters.

and because of the way the installer works, I can't just revert to an old version anymore so my test machine is done

**Comment by RicardoEPRodrigues** [comment]
I totally agree. I was making use of WebSockets and they are gone. I wouldn't mind a change in endpoints and parameterization that better suits the OpenAI API, but currently, this is not a good solution.

**Comment by Qualzz** [comment]
The langchain documentation about texgen seems to still use the old api. I can't find how to use the new api with langchain.
