### ISSUE TITLE
api/v1/generate appears to be broken

### ISSUE THREAD

**Issue by Niellai** [oobabooga/text-generation-webui#4630]
### Describe the bug

http://127.0.0.1:5000/api/v1/generate 
Appears to be broken.

I have no issue running the model through webui. 
I have update to the latest project through update_linux.sh

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

When sending through request. 

`URI = f'http://127.0.0.1:5000/api/v1/generate'
instruct_parameters = {
    'prompt': 'my prompt'
    'temperature': 1.31,
    'top_p': 0.14,
 ...
}
response = requests.post(URI, json=request)`

Returns:
status code 404
'detail': 'Not Found'

### Logs

```shell
-
```

### System Info

```shell
Linux 
Nvidia RTX3090

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0
```

**Comment by oobabooga** [comment]
See this comment: https://github.com/oobabooga/text-generation-webui/issues/4581#issuecomment-1810232103
