### ISSUE TITLE
Fix broken (deprecated) API.

### ISSUE THREAD

**Issue by sam1am** [oobabooga/text-generation-webui#4635]
Please add the old extension API back in. Mark it as deprecated in the UI with a future removal date and remove it then. Please don't push production-breaking changes without notice or any kind of plan for people who are using and relying on it.

**Comment by oobabooga** [comment]
See this comment: https://github.com/oobabooga/text-generation-webui/issues/4581#issuecomment-1810232103

**Comment by sam1am** [comment]
@oobabooga 
I maintain that breaking things without notice and relying on people to scrub through support forums for fixes is not a productive way to make changes in the future. Thanks for your consideration.
