### ISSUE TITLE
warnings.warn(

### ISSUE THREAD

**Issue by swumagic** [oobabooga/text-generation-webui#4659]
### Describe the bug

D:\airj\text-generation-webui\text-generation-webui\installer_files\env\Lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: v2/en_speaker_3 or set allow_custom_value=True.
  warnings.warn(
D:\airj\text-generation-webui\text-generation-webui\installer_files\env\Lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: english or set allow_custom_value=True.
  warnings.warn(
D:\airj\text-generation-webui\text-generation-webui\installer_files\env\Lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include:  *I am so happy* or set allow_custom_value=True.
  warnings.warn(

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

  warnings.warn(

### Logs

```shell
warnings.warn(
```

### System Info

```shell
win11，py3.10.11,4090
```

**Comment by saaquyaa** [comment]
i had a error like this for a few days now mine said "\text-generation-webui\installer_files\env\Lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 128 or set allow_custom_value=True.
warnings.warn(" i fixed this today with notepad++.  i went to that directory file dropdown.py then right clicked on the file edit with notepad++ and changed allow custom value from false to true and saved document. no more error message.

**Comment by swumagic** [comment]
Which line of code is changed to allow_custom_value=True?

Do you want to modify it here?

    def _warn_if_invalid_choice(self, y):
        if self.allow_custom_value or y in [value for _, value in self.choices]:
            return
        warnings.warn(
            f"The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: {y} or set allow_custom_value=True."
        )
tk!

**Comment by swumagic** [comment]
> i had a error like this for a few days now mine said "\text-generation-webui\installer_files\env\Lib\site-packages\gradio\components\dropdown.py:231: UserWarning: The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: 128 or set allow_custom_value=True. warnings.warn(" i fixed this today with notepad++. i went to that directory file dropdown.py then right clicked on the file edit with notepad++ and changed allow custom value from false to true and saved document. no more error message.

Which line of code is changed to allow_custom_value=True?

Do you want to modify it here?

    def _warn_if_invalid_choice(self, y):
        if self.allow_custom_value or y in [value for _, value in self.choices]:
            return
        warnings.warn(
            f"The value passed into gr.Dropdown() is not in the list of choices. Please update the list of choices to include: {y} or set allow_custom_value=True."
        )
tk!

**Comment by saaquyaa** [comment]
hope this helps. i changed line 49 from false to true.

**Comment by swumagic** [comment]
thank you
