### ISSUE TITLE
Run WebUI as a service

### ISSUE THREAD

**Issue by savisaar2** [oobabooga/text-generation-webui#4666]
**Description**

I want to be able to run the web interface as a service instead of having to manually run it via terminal in Linux.

**Additional Context**

Currently when executing the bash file (start_linux.sh) as a service, it seems to restart continuously.

**Comment by fluo10** [comment]
@savisaar2 
If you are refferring to systemd.service, you can write your own service file.
I'm using the file like below for my own use.

```/etc/systemd/system/textgen.service
#/etc/systemd/system/textgen.service
[Unit]
After=network.target

[Service]
Type=simple
ExecStart=/bin/bash /path/to/start_linux.sh
User=textgen
Group=textgen

[Install]
WantedBy=multi-user.target
```

**Comment by savisaar2** [comment]
Thank you @fluo10 i thought I tried creating a service file but the service kept restarting. The one above works. Thanks again!
