### ISSUE TITLE
404 Error: {"detail":"Not Found"} response to a post request made to the API running on port 5000 (/api/v1/generate)

### ISSUE THREAD

**Issue by jaquielajoie** [oobabooga/text-generation-webui#4672]
### Describe the bug

api/v1/generate (http://localhost:5000/api/v1/generate) is returning 404 to post requests. The documentation describes the api to be a drop in for Open AI's – this used to work. Have there been changes that have effected this? I have installed the apple silicon requirements as well as the extensions/openai/requirements.txt

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

run the server, i.e. python server.py --api --model dolphin-2.1-mistral-7b.Q6_K.gguf --api-port 5000
send a post request to localhost:5000/api/v1/generate
get a 404 error in response

### Logs

```shell
I also tried to reproduce the issue on runpods. This is the stack trace from that from the service that made the call to port 5000. This is the same error that happens locally

API call got non-200 response code (code=404, msg={"detail":"Not Found"}) for address: https://3ygug24nekai84-5000.proxy.runpod.net/api/v1/generate. Make sure that the web UI server is running and reachable at https://3ygug24nekai84-5000.proxy.runpod.net/api/v1/generate.
```

### System Info

```shell
macos M1 running Sonoma
```

**Comment by jaquielajoie** [comment]
nevermind I realize the official API changed, my bad. Slow to the party

**Comment by ashmuse** [comment]
Hi, what's the solution? *_*

**Comment by YashM8** [comment]
How do you fix this?

**Comment by rockerBOO** [comment]
If you run into this issue, check the docs of your API. http://127.0.0.1:5000/docs. Then for your client turn on logs OPENAI_LOG=debug to see what it is requesting. For mine it was a matter of `openai.base_url = 'http://127.0.0.1:5000/v1/'` with the closing slash.

**Comment by armstrys** [comment]
This thread helped me get DeepInfra working as a custom endpoint. For what it's worth, I did struggle with this. Many tools that use OpenAI endpoints seem to want the "chat/completions" included (in my limited experience). There was nothing in the custom end-points section or the LiteLLM docs about DeepInfra to specify this. Maybe it is worth a note somewhere?
