### ISSUE TITLE
min_p sampling for llama.cpp loader

### ISSUE THREAD

**Issue by Technologicat** [oobabooga/text-generation-webui#4688]
**Description**

It would be nice to have access to the *min_p* sampler in the *llama.cpp* loader in *text-generation-webui*.

**Additional Context**

I prefer the *llama.cpp* loader because it is fast and provides partial GPU offloading, ideal for running on a laptop.

~It seems *min_p* is already supported by the *llamacpp_hf* loader, but I couldn't get that one to work (#4687).~ **EDIT**: *Works now, the Contrastive search preset is not supported by that loader, so just use some other preset instead. And then also install the correct model-specific tokenizer.*

The *min_p* sampler dynamically chooses the cutoff probability based on the probability of the most likely predicted token, so compared to *top_p* or *top_k*, it should be able to give coherent yet creative output.

The developer of *min_p* said on Reddit it is already supported by the *llama.cpp* backend itself:

https://www.reddit.com/r/LocalLLaMA/comments/17vonjo/your_settings_are_probably_hurting_your_model_why/

so it seems what we're missing at the moment is integration in *text-generation-webui*.

**Comment by berkut1** [comment]
Just wait, It was added yesterday https://github.com/abetlen/llama-cpp-python/pull/921
And webui will support in the few days if the latest llama-cpp-python has no issues.

**Comment by Technologicat** [comment]
Ah, thanks for the heads-up. I didn't realize it was that new. :)

**Comment by berkut1** [comment]
LOL, it was added https://github.com/oobabooga/text-generation-webui/pull/4701 :)

**Comment by Technologicat** [comment]
Updated my install. Seems to be working. Thanks!

One final question before I close this: is there no `temperature_last` option in *llama.cpp*?

The *llamacpp_hf* loader has this feature and it is very useful in conjunction with *min_p*. Namely, the *min_p* sampler *first* cuts off the nonsensical continuations, and the temperature *only then* adjusts the relative probabilities of the remaining ones. The other ordering runs the risk of increasing the probability of some nonsensical continuations so much that they survive the *min_p* sampling.

**Comment by tk-master** [comment]
@Technologicat llama.cpp actually samples temperature last (hard-coded order for now), which is probably better anyway.

**Comment by Technologicat** [comment]
@tk-master Thanks, good to know. Yes, temperature last is better, which is why I asked.

Everything ok now. Closing this issue. Thank you to the devs!
