### ISSUE TITLE
Why did you remove the API extension!?

### ISSUE THREAD

**Issue by wesley7137** [oobabooga/text-generation-webui#4699]
### Describe the bug

API extension was removed in new update? 

1 change: 0 additions & 1 deletion1  
[docs/Extensions.md → docs/07 - Extensions.md](https://github.com/oobabooga/text-generation-webui/compare/v1.7...snapshot-2023-11-19#diff-119636ed833a1ac643ad8834a24c0c246c75a031ee19cdd8f9f10d2ce4ea8dd3)
@@ -14,7 +14,6 @@ If you create an extension, you are welcome to host it in a GitHub repository an

|Extension|Description|
|---------|-----------|
|[api](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/api)| Creates an API with two endpoints, one for streaming at `/api/v1/stream` port 5005 and another for blocking at `/api/v1/generate` port 5000. This is the main API for the webui. |
|[openai](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/openai)| Creates an API that mimics the OpenAI API and can be used as a drop-in replacement. |
|[multimodal](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/multimodal) | Adds multimodality support (text+images). For a detailed description see [README.md](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/multimodal/README.md) in the extension directory. |
|[google_translate](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/google_translate)| Automatically translates inputs and outputs using Google Translate.|

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1 change: 0 additions & 1 deletion1  
[docs/Extensions.md → docs/07 - Extensions.md](https://github.com/oobabooga/text-generation-webui/compare/v1.7...snapshot-2023-11-19#diff-119636ed833a1ac643ad8834a24c0c246c75a031ee19cdd8f9f10d2ce4ea8dd3)
@@ -14,7 +14,6 @@ If you create an extension, you are welcome to host it in a GitHub repository an

|Extension|Description|
|---------|-----------|
|[api](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/api)| Creates an API with two endpoints, one for streaming at `/api/v1/stream` port 5005 and another for blocking at `/api/v1/generate` port 5000. This is the main API for the webui. |
|[openai](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/openai)| Creates an API that mimics the OpenAI API and can be used as a drop-in replacement. |
|[multimodal](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/multimodal) | Adds multimodality support (text+images). For a detailed description see [README.md](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/multimodal/README.md) in the extension directory. |
|[google_translate](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/google_translate)| Automatically translates inputs and outputs using Google Translate.|

### Screenshot

![Screenshot 2023-11-21 135736](https://github.com/oobabooga/text-generation-webui/assets/132653112/f639a625-4324-43e8-a85e-60c660c9af05)
![Screenshot 2023-11-21 135816](https://github.com/oobabooga/text-generation-webui/assets/132653112/c278ab6c-4023-408a-8814-44cdaa504d26)

### Logs

```shell
Removed API extension
```

### System Info

```shell
windows 11 64-bit
NVidia Geforce RTX-3090
Intel i-9
```

**Comment by DarrylHunter** [comment]
Wesley, did you manage to resolve this? I cant see the API option in extensions?

**Comment by mayeaux** [comment]
Where did it go?
