### ISSUE TITLE
Windows Defender reports Security Threat in frpc_windows_amd64

### ISSUE THREAD

**Issue by AlexysLovesLexxie** [oobabooga/text-generation-webui#472]
### Describe the bug

See screenshot below.

EDIT : This file was from my old install.  New install does not seem to contain this file at all.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See screenshot

### Screenshot

![Screenshot 2023-03-21 041559](https://user-images.githubusercontent.com/126999069/226592625-8ddc3fd9-891a-4a06-aeb2-1f8d8f789dd0.png)

### Logs

```shell
none
```

### System Info

```shell
Windows 11
```

**Comment by oobabooga** [comment]
I trust gradio to be safe. Definitely a false positive.
