### ISSUE TITLE
Add supports for multiple system messages on OpenAI API extensions.

### ISSUE THREAD

**Issue by justpain02** [oobabooga/text-generation-webui#4720]
**Description**

For now, only the last system prompts are used on generating response while other previous prompts are ignored. As official OpenAI api supports multiple system prompts for input, support this feature can help others migrate their projects from OpenAI to oobabooga webui.

**Additional Context**

![image](https://github.com/oobabooga/text-generation-webui/assets/62899533/a619d88e-c40d-4ff2-a8fc-feaadd3d99b7)
As we can see on [completions.py](https://github.com/oobabooga/text-generation-webui/blob/main/extensions/openai/completions.py) in extensions/openai, only last system prompts are accepted while previous one is overwrite by new one.

**Comment by arjunsohal12** [comment]
Hi, I'd like to try working on this!

**Comment by justpain02** [comment]
> Hi, I'd like to try working on this!

Oh thank you so much, I look forward to seeing your work!

**Comment by antcodd** [comment]
This issue should be reopened, the OpenAI endpoint still only uses the last system message (see https://github.com/oobabooga/text-generation-webui/blob/main/extensions/openai/completions.py#L161).

Hopefully with the jinja template changes in #4874 this is now easier to fix?

**Comment by mysticfall** [comment]
I can confirm that the issue still persists with the OpenAI extension, as antcodd noted.

This prevents me from switching between OpenRouter and text-generation-webui during the development of my application, which would boost productivity since I wouldn't have to use a slow and expensive remote service constantly.

I don't intend to argue this issue should get a priority, but maybe it can be reopened at least since it's an unresolved limitation affecting the users?

**Comment by kevyuu** [comment]
Is there any update on this issue? This is still broken.

**Comment by FartyPants** [comment]
Oh, and I thought it's just me. I was looking at what SillyTavern sends and what WebUI actually receives and there is a big difference. Most of the OpenAI chatbot systems in SillyTavern are literally based on sending stuff as multiple System prompts.

**Comment by oobabooga** [comment]
@FartyPants I think that the best solution would be to refactor the entire project to use a history format more similar to the openai one, but this is an absolute nightmare of a refactor (likely a +1000 / -1000 additions commit).

**Comment by FartyPants** [comment]
> [@FartyPants](https://github.com/FartyPants) I think that the best solution would be to refactor the entire project to use a history format more similar to the openai one, but this is an absolute nightmare of a refactor (likely a +1000 / -1000 additions commit).

I absolutely agree about the nightmare part. 

I did fix it in my version with only a few lines of code but it's UGLY. It works, it is not bound to just system role and it will not affect anything else - but it's a patch. Let me know if you want it. Also a bonus is other plugins can now use it too. 

Sily Tavern sent:
![Image](https://github.com/user-attachments/assets/74952715-8bd7-42d5-bc97-c294bb198cfa)

WebUI Received:
![Image](https://github.com/user-attachments/assets/94f745e0-978a-4a86-ac48-d3bc63111436)
