### ISSUE TITLE
The new dowloade model is total garbage for French voice...

### ISSUE THREAD

**Issue by carinae** [oobabooga/text-generation-webui#4724]
### Describe the bug

Hello,

Today, when starting coqui-ai tss a new model is dowloaded

models/multilingual/multi-dataset/xtts_v2 is already downloaded however it has been changed. Redownloading it...

The french voice are now totally garbage, it's look like a Russian trying to speak french... was really good before. It's adding strange sound inside sentence... no more usable at all or let us the choice to get the new model.

Is it possible to get the previous model tts_models --multilingual--multi-dataset--xtts_v2 and avoiding loading this new one ?

PS: every thing is up to date, git pull and requirement done for oobabooga and coqui_tts

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

use a french voice

### Logs

```shell
no log, no error, just horrible sound
```

### System Info

```shell
Winows 11, python 3.11 with it's own env. cuda 11 and 4090.
everything goes wrong after downloading new coqui tts model.
```

**Comment by erew123** [comment]
**EDIT - Manual workaround here along with sounding strange FIX** https://github.com/oobabooga/text-generation-webui/issues/4723#issuecomment-1826120220 (for anyone looking for it)

I created that bug report earlier.

**Comment by carinae** [comment]
Yes it's working see my reply there thank you
