### ISSUE TITLE
Add a New Conversation Button

### ISSUE THREAD

**Issue by MilesQLi** [oobabooga/text-generation-webui#4729]
**Description**

I don't know how to start a new conversation without deleteing the old one. One button for that should be added.

**Comment by Woisek** [comment]
A new conversation doesn't delete any conversation. Only if you select and delete a conversation yourself.

**Comment by MilesQLi** [comment]
@Woisek Well, then how do I start a new one????

**Comment by MilesQLi** [comment]
The point is I don't know how to start a new conversation without deleting the old one! I made it pretty clear.

**Comment by kanttouchthis** [comment]
three stripes on the left, 3rd option "start new chat"

**Comment by Woisek** [comment]
> The point is I don't know how to start a new conversation without deleting the old one! I made it pretty clear.

And I said, a conversation is only deleted if you do it intentionally by selecting and then delete it. Starting a new conversation and deleting a conversation are two different things to do and not connected to each other.

**Comment by MilesQLi** [comment]
I see. That button is hard to see. Without nowing that button, they are one thing.
