### ISSUE TITLE
Installing DeepSpeed on Windows - The Correct Procedure / Solution / Solved

### ISSUE THREAD

**Issue by erew123** [oobabooga/text-generation-webui#4734]
This is not a feature request, this is actually how you install DeepSpeed on Windows. I have requested Microsoft update their GitHub, but if not, here is my post to them https://github.com/microsoft/DeepSpeed/issues/4729

**Please note, there are limitations of DeepSpeed on Windows VS the Linux version.**
**Also note, there could be other things needed to get bits of DS working on Windows fully**

Other than using the instructions above, you can also install the Nvidia Cuda Toolkit, Create a new Python 3.9.18 environment, set your CUDA_HOME environment variable in that environment and download someone else's wheel file it. I actually do have both a cuda 11.8 and 12.1 wheel for Python 3.9.18.

@oobabooga

**Comment by erew123** [comment]
FYI Im working on some code (which will need some looking at) but I can confirm DeepSpeed is loaded on Windows, based off those above instructions!

![image](https://github.com/oobabooga/text-generation-webui/assets/35898566/722f53ae-d77f-4b64-b80d-170ef814e4c3)

**Comment by rktvr** [comment]
does it have a noticable speed increase for inference?

**Comment by erew123** [comment]
@rktvr Please have a look here https://github.com/oobabooga/text-generation-webui/issues/4712#issuecomment-1825593734 I've got it working with Coqui_tts and there is an example screenshot in that link.

**Comment by S95Sedan** [comment]
> @rktvr Yes, I've been working on some code and giving it a go. I need to do a little bit more testing before I can say all is good, so I will confirm in a day or two with a bit more info.
> 
> On TTS, its about 3-4x faster is my current estimate.
> 
> On Windows there are limitations to it. e.g. It runs on Python 3.9.18, you have to install the CUDA Toolkit 11.8 or 12 (depending on your CUDA) and a couple of other bits.
> 
> On Linux you have to install CUDA.
> 
> Also, you need to change the CUDA_HOME environment, which Text-Generation-WebUI has already set and I'm not sure if this could have any other impacts.
> 
> My advice is DONT go installing it just yet! You may not see any benefit anyway, because you need DeepSpeed implemented in the code that calls the TTS engine anyway.

Version 11.1 + CUDA 12.1 + stock ooba (3.11) Python install works fine aswell. Also had a look at the 12.4 version but it seems to have way more isues aswell as added deepspeed-kernel which cant be compiled properly either. (ironically is broken aswell).

Attached the compiled .whl which im using right now and should be working. evn_report is fixed for windows in that aswell.
[deepspeed-0.11.1+e9503fe-cp311-cp311-win_amd64.rar.zip](https://github.com/oobabooga/text-generation-webui/files/13593455/deepspeed-0.11.1%2Be9503fe-cp311-cp311-win_amd64.rar.zip)

**Comment by erew123** [comment]
If anyone is interested in a about 40+ voice files, this link should be live for about 6 days https://filebin.net/t97nd69ac7qm2rsf

Also, I've fully released the updated Coqui TTS extension now https://github.com/erew123/alltalk_tts 

If you want to try it :)

**Comment by jepjoo** [comment]
So Python 3.9 and 3.11 seem to be working according to above discussion. 

I'm on Python 3.10, is there a way to install DeepSpeed?

**Comment by erew123** [comment]
Allegedly/supposedly/possibly, this is a pre-built wheel file for python 3.10 https://huggingface.co/Jmica/audiobook_maker/tree/main

the one that says cp310

I have not tried it, and wuzzoy tried it and said it didnt work for him https://github.com/oobabooga/text-generation-webui/issues/4712#issuecomment-1826473959

(Ive not yet tried the 3.11 @S95Sedan yet... as Ive been too deep in other things)

**Comment by elkay** [comment]
S95Sedan's build worked fine for me. The one I built myself (successfully) was throwing this error:

ERROR: deepspeed-0.8.3+unknown-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.

**Comment by Wuzzooy** [comment]
> S95Sedan's build worked fine for me. The one I built myself (successfully) was throwing this error:
> 
> ERROR: deepspeed-0.8.3+unknown-cp39-cp39-win_amd64.whl is not a supported wheel on this platform.

If you tried to install it in a 3.11 python environment.

**Comment by erew123** [comment]
@S95Sedan Just tested out your DeepSpeed 11.2 wheel file and it works great!! Really nice job on that! 

Are you ok with me including a reference to you having done this and also linking to the file+adding documentation in AllTalk (Will reference you figured this out)?

Thanks

**Comment by erew123** [comment]
@S95Sedan If it is ok with you, I have published up your instructions here https://github.com/erew123/alltalk_tts?tab=readme-ov-file#deepspeed-112-for-windows--python-311 

Happy to remove them and just solely link to you (if you prefer) or remove your name (if you prefer) etc.

If you're ok with me using your name etc, Id like to amend the instructions within AllTalk and also reference you at the bottom in the "Thanks" area of the documentation.

Let me know! And thanks for the info on this! :)

**Comment by S95Sedan** [comment]
@erew123 yeah no worries, feel free to grab whatever you need to make it as complete as possible. I would upload 11.2 aswell but that ones too big for here.

**Comment by erew123** [comment]
@S95Sedan Thanks so much! That is awesome! :) Ill make sure you are thanks+referenced and linked in AllTalk. Will be on its next update.

**Comment by daswer123** [comment]
@S95Sedan Thank you so much for the instructions.
I built deepspeed 11.2 for python 3.10 and CUDA 11.8.

If anyone is interested, you can get the prebuild-wheel here 
https://github.com/daswer123/resemble-enhance-windows/releases/tag/deepspeed

**Comment by erew123** [comment]
Closing this ticket off as I think the issue is put to bed now. Thanks everyone who got involved!
