### ISSUE TITLE
TypeError: Llama.create_completion() got an unexpected keyword argument 'min_p'

### ISSUE THREAD

**Issue by makingitup** [oobabooga/text-generation-webui#4740]
### Describe the bug

When making a query content comes back as empty and reason for finish is 'stop'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Create a new runpod using 'RunPod TheBloke LLMs' as a template
Use any gpu 
Load any llm
Make a query either with the browser interface or the api

### Logs

```shell
Traceback (most recent call last):
File "/workspace/text-generation-webui/modules/callbacks.py", line 57, in gentask
ret = self.mfunc(callback=_callback, *args, **self.kwargs)
File "/workspace/text-generation-webui/modules/llamacpp_model.py", line 141, in generate
completion_chunks = self.model.create_completion(
TypeError: Llama.create_completion() got an unexpected keyword argument 'min_p'
```

### System Info

```shell
Runpod with 'RunPod TheBloke LLMs' template
RTX A6000
TheBloke/Llama-2-13B-chat-GGUF/llama-2-13b-chat.Q4_K_M.gguf
```

**Comment by makingitup** [comment]
https://github.com/TheBlokeAI/dockerLLM/issues/12

**Comment by vmajor** [comment]
this is broken in standalone installs. Latest pull, latest requirements.txt used

**Comment by erhhung** [comment]
Just installed fresh with all latest "requirements.txt" files and llama.cpp is still not able to query after loading a model like "Hermes-2-Pro-Mistral-7B.Q4_K_M.gguf".
