### ISSUE TITLE
docker compose does not find  configuration file 

### ISSUE THREAD

**Issue by aldur15** [oobabooga/text-generation-webui#4743]
### Describe the bug

after cloning the repository docker is not able to create a docker container because of the missing configuration file.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui
ln -s docker/{Dockerfile,docker-compose.yml,.dockerignore} .
cp docker/.env.example .env (changing cuda settings)
docker compose up --build (in the text-generation folder)

### Logs

```shell
docker compose up --build
no configuration file provided: not found
```

### System Info

```shell
Linux server with a NVIDIA GeForce RTX 3070
```

**Comment by Captain-Pumpkinhead** [comment]
@aldur15, did you find the `.env.example` file?  I still don't see it, but I see that you closed this issue.
