### ISSUE TITLE
The web page http://localhost:7860 of is blank

### ISSUE THREAD

**Issue by majestichou** [oobabooga/text-generation-webui#4762]
### Describe the bug

I installed all the necessary software for text-generation-webui, and then I ran **python server.py**, and then I opened the firefox and linked to the web page http://my_local_network_ip_adress:7860, but nothing was displayed except a logo in the upper left corner.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

conda create -n textgen python=3.11
conda activate textgen
conda install -y -c "nvidia/label/cuda-12.1.0" cuda-runtime  cuda-toolkit cuda-nvcc 
pip3 install torch torchvision torchaudio
git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui
pip install -r requirements.txt
conda activate textgen
cd text-generation-webui
python server.py --listen

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/43713443/ab7e63e1-ecdb-4cac-8606-6824539b37cd)

### Logs

```shell
nothing
```

### System Info

```shell
AMD EPYC 7642 48-Core Processor, CentOS Linux release 7.9.2009 (Core), A100, codellama, cuda 12.1
```

**Comment by majestichou** [comment]
I switAfter I changed the browser, the problem was solved. Perhaps the default Firefox browser version of Centos 7 is too low.ch the

**Comment by LomarOfficer** [comment]
https://github.com/LomarOfficer/The-special-forces-from-KS-2-are-looking-ahead.git
