### ISSUE TITLE
Not loading the API on nVidia Jetson Orin AGX

### ISSUE THREAD

**Issue by lesreaper** [oobabooga/text-generation-webui#4779]
### Describe the bug

When I go to run the application, I get the following error when running it:
```
bin /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda114.so
2023-12-01 04:02:29 INFO:Loading settings from settings.json...
2023-12-01 04:02:29 INFO:Loading the extension "openai"...
2023-12-01 04:02:29 ERROR:Failed to load the extension "openai".
Traceback (most recent call last):
  File "/opt/text-generation-webui/modules/extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "/opt/text-generation-webui/extensions/openai/script.py", line 27, in <module>
    from .typing import (
  File "/opt/text-generation-webui/extensions/openai/typing.py", line 8, in <module>
    class GenerationOptions(BaseModel):
  File "/opt/text-generation-webui/extensions/openai/typing.py", line 9, in GenerationOptions
    preset: str | None = Field(default=None, description="The name of a file under text-generation-webui/presets (without the .yaml extension). The sampling parameters that get overwritten by this option are the keys in the default_preset() function in modules/presets.py.")
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
2023-12-01 04:02:29 INFO:Loading the extension "gallery"...
Running on local URL:  http://0.0.0.0:7860
```
Running it with the `--api` key doesn't seem to activate anything on port 5000. When I try to access it via `curl` or other methods, I get a `curl: (7) Failed to connect to 127.0.0.1 port 5000: Connection refused`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Using the standard nVidia Docker image for Jetson devices. Nothing special with it, it's just a wrapper around the install process. You can [see it all here](https://github.com/dusty-nv/jetson-containers/blob/master/packages/llm/text-generation-webui/Dockerfile).

### Logs

```shell
Namespace(packages=['text-generation-webui'], prefer=['local', 'registry', 'build'], disable=[''], user='dustynv', output='/tmp/autotag', quiet=False, verbose=False)
-- L4T_VERSION=35.4.1  JETPACK_VERSION=5.1.2  CUDA_VERSION=11.4.315
-- Finding compatible container image for ['text-generation-webui']
dustynv/text-generation-webui:r35.2.1
[sudo] password for nvidia: 
localuser:root being added to access control list
+ docker run --runtime nvidia -it --rm --network host --volume /tmp/argus_socket:/tmp/argus_socket --volume /etc/enctune.conf:/etc/enctune.conf --volume /etc/nv_tegra_release:/etc/nv_tegra_release --volume /tmp/nv_jetson_model:/tmp/nv_jetson_model --volume /home/nvidia/Documents/jetson-containers/data:/data --device /dev/snd --device /dev/bus/usb -e DISPLAY=:1 -v /tmp/.X11-unix/:/tmp/.X11-unix -v /tmp/.docker.xauth:/tmp/.docker.xauth -e XAUTHORITY=/tmp/.docker.xauth --workdir /opt/text-generation-webui dustynv/text-generation-webui:r35.2.1 python3 server.py --listen --verbose --api --model-dir=/data/models/text-generation-webui
2023-12-01 04:02:25 WARNING:
You are potentially exposing the web UI to the entire internet without any access password.
You can create one with the "--gradio-auth" flag like this:

--gradio-auth username:password

Make sure to replace username:password with your own.
bin /usr/local/lib/python3.8/dist-packages/bitsandbytes/libbitsandbytes_cuda114.so
```

### System Info

```shell
nVidia Jetson Orin Nano AGX 64GB
```

**Comment by Unlicensed-driver-ljx** [comment]
解决了吗分享一下办法感谢

**Comment by Unlicensed-driver-ljx** [comment]
给后面的人提示一下我下载的text-generation-webui版本不对，默认是./run.sh --workdir /opt/text-generation-webui $(./autotag text-generation-webui)会下载最新镜像，改成./run.sh --workdir /opt/text-generation-webui $(./autotag text-generation-webui：1.7)就不会了，jetson版本默认是python3.8.10可能这个最新的需要python3.9

**Comment by elkay** [comment]
> > 给后面的人提示一下我下载的text-generation-webui版本不对，默认是./run.sh --workdir /opt/text-generation-webui 会下载最新镜像，改成(./autotagtext−generation−webui)会下载最新镜像，改成./run.sh−−workdir/opt/text−generation−webui(./autotag text-generation-webui：1.7)就不会了，jetson版本默认是python3.8.10可能这个最新的需要python3.9
> 
> Thank you very much @Unlicensed-driver-ljx i just translate your comment to english. Just a hint for those who are behind me, the version of text-generation-webui I downloaded is not correct, the default is . /run.sh --workdir /opt/text-generation-webui will download the latest image, change it to (. /autotag text-generation-webui:1.7) and it won't, the default jetson version is python3.8.10 may need python3.9 for this latest one.

Can you elaborate a bit on what this means? Trying to get Ooba running on an AWS ARM instance and it's been nothing but one issue after another. Finally got it to launch but this (hopefully) last error is still getting in the way. Thanks!
