### ISSUE TITLE
Pressing continue button causes error local variable referenced before assignment on console

### ISSUE THREAD

**Issue by pwsoft** [oobabooga/text-generation-webui#482]
### Describe the bug

Model is loaded and seems to be working. Can generate new text with "Generate" button, but pressing the "Continue" button sometimes works and sometimes gives an error on the console. Pressing the button multiple times often does eventually causes the model to spit out more text.
Looking at line 224 in the reported file there are two consecutive "yield" statements, but can't immediately tell why "reply" would not be assigned.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

python server.py --model pygmalion-6b_b8344bb4eb76a437797ad3b19420a13922aaabe1 --load-in-8bit

Open browser at local address http://127.0.0.1:7860
Type some text, press "Generate" when model stops outputting data, press "Continue" button.

### Logs

```shell
Traceback (most recent call last):
  File "/media/Data/prog/llm/text-generation-webui/modules/text_generation.py", line 224, in generate_reply
    yield formatted_outputs(reply, shared.model_name)
UnboundLocalError: local variable 'reply' referenced before assignment
Output generated in 0.65 seconds (0.00 tokens/s, 0 tokens)
Traceback (most recent call last):
  File "/media/Data/prog/llm/text-generation-webui/modules/text_generation.py", line 224, in generate_reply
    yield formatted_outputs(reply, shared.model_name)
UnboundLocalError: local variable 'reply' referenced before assignment
Output generated in 0.76 seconds (0.00 tokens/s, 0 tokens)
```

### System Info

```shell
Ubuntu, conda environment (same I created for use with stable-diffusion). GPU is RTX3060 12GB. CUDA version 11.7 driver 515.86.01
```

**Comment by pwsoft** [comment]
Thx for the fix, will try it out. The 0 token output might just be the way the model is trained. After a bit of experimentation some of the models seem to function better in chat mode vs the default mode.

**Comment by oobabooga** [comment]
I think that this has been solved, let me know if it hasn't
