### ISSUE TITLE
Chat output has no spaces between words

### ISSUE THREAD

**Issue by yasserjarouf** [oobabooga/text-generation-webui#4834]
I'm just starting up and managed to download the model **codellama_CodeLlama-7b-Instruct-hf**. Whenever I write a chat message with the AI, I'm getting something but has no spaces between the words so I'm not sure if I missed something or there is something wrong with the model.
This is an example Input/Output that I'm getting:

**Input:**
How many class types in default c#

**Output:**
Thereareseveralclassesavailablebydefault,including:Boolean,Byte,Char,DateTime,Decimal,Double,Int16,Int32,Int64,SByte,Single,String,TimeSpan,UInt16,UInt32,andUInt64.YoumayalsofindithelpfultoknowthatC#providessupportforarrays,lists,dictionaries,sets,tuples,andothercollectiontypesaswell.

Can someone provide few hints how to fix it?

**Comment by jmontleon** [comment]
I am also just starting to set up text-generation-webui and have been experiencing this for the last couple of days as well.

**Comment by jmontleon** [comment]
Using the snapshot-2023-12-03 branch I get spaces between words.

**Comment by yasserjarouf** [comment]
> > Using the snapshot-2023-12-03 branch I get spaces between words.
> 
> Could you produce steps to fix or if there are any files to replace?

I went to **snapshot-2023-12-03** and from it, I replaced the folders/files in my local installation:

- server.py
- modules
- js
- extensions

Now I'm getting spaces again.
