### ISSUE TITLE
errors during installation

### ISSUE THREAD

**Issue by testter21** [oobabooga/text-generation-webui#4848]
### Describe the bug

I downloaded the one click installer from
https://github.com/oobabooga/text-generation-webui#one-click-installers
unpacked the text-generation-webui-main and started the start_macos.sh, selected vendor (apple m in this case). After that, during further installation I get something like this:

...
Downloading werkzeug-3.0.1-py3-none-any.whl (226 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 226.7/226.7 kB 2.8 MB/s eta 0:00:00
Installing collected packages: Werkzeug, sniffio, itsdangerous, click, blinker, tiktoken, Flask, anyio, starlette, flask_cloudflared, sse-starlette
  Attempting uninstall: tiktoken
    Found existing installation: tiktoken 0.3.3
    Uninstalling tiktoken-0.3.3:
      Successfully uninstalled tiktoken-0.3.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openai-whisper 20230918 requires tiktoken==0.3.3, but you have tiktoken 0.5.2 which is incompatible.
...

then later:

...
*******************************************************************
* Installing webui requirements from file: requirements_apple_silicon.txt
*******************************************************************
WARNING: Skipping torch-grammar as it is not installed.
Uninstalled torch-grammar
Requirement already satisfied: 
...

and then at the end again:

...
    Uninstalling starlette-0.33.0:
      Successfully uninstalled starlette-0.33.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openai-whisper 20230918 requires tiktoken==0.3.3, but you have tiktoken 0.5.2 which is incompatible.
Successfully installed GitPython-3.1.40 
...

finally, there is last warning, related to lack of models, so it's irrelevant.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download from https://github.com/oobabooga/text-generation-webui#one-click-installers
and run start_macos.sh
provide vendor as apple m series

on the go, there are two errors and two warning listed.

### Logs

```shell
...
Downloading werkzeug-3.0.1-py3-none-any.whl (226 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 226.7/226.7 kB 2.8 MB/s eta 0:00:00
Installing collected packages: Werkzeug, sniffio, itsdangerous, click, blinker, tiktoken, Flask, anyio, starlette, flask_cloudflared, sse-starlette
  Attempting uninstall: tiktoken
    Found existing installation: tiktoken 0.3.3
    Uninstalling tiktoken-0.3.3:
      Successfully uninstalled tiktoken-0.3.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openai-whisper 20230918 requires tiktoken==0.3.3, but you have tiktoken 0.5.2 which is incompatible.
...

then later:

...
*******************************************************************
* Installing webui requirements from file: requirements_apple_silicon.txt
*******************************************************************
WARNING: Skipping torch-grammar as it is not installed.
Uninstalled torch-grammar
Requirement already satisfied: 
...

and then at the end again:

...
    Uninstalling starlette-0.33.0:
      Successfully uninstalled starlette-0.33.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openai-whisper 20230918 requires tiktoken==0.3.3, but you have tiktoken 0.5.2 which is incompatible.
Successfully installed GitPython-3.1.40 
...

finally, there is last warning, related to lack of models, so it's irrelevant.
```

### System Info

```shell
m3 pro, macos sonoma
```

**Comment by TheLounger** [comment]
Does it actually prevent you from using the webui? You can generally ignore those errors.

**Comment by testter21** [comment]
Currently, I'm unable to use certain extension, no matter how I approach installation. I have no idea whether these two are related. For more details see:
https://github.com/oobabooga/text-generation-webui/issues/4723

On the other hand, I'm just reporting a bug. Technically, installer should use non-conflicted dependencies, otherwise potential issues are unpredictable, especially for non-programmer users.

**Comment by Toasterme** [comment]
I do have the same warning about tiktoken==0.3.3 and uninstalled starlette-0.33.0.

The error dependency does not make sense.   openai-whisper 20230918 need tiktoken v0.3.3 but previously it installed the 0.5.2

![image](https://github.com/oobabooga/text-generation-webui/assets/732881/f12b5c28-d6c3-47b1-8e14-c2fd39e6ea44)

![image](https://github.com/oobabooga/text-generation-webui/assets/732881/a0adbee4-efe1-4233-84e1-109334248a2b)

So the webui work, but i cannot load/download anything  :
text-generation-webui\modules\ui_model_menu.py", line 238, in download_model_wrapper
text-generation-webui\download-model.py", line 39, in sanitize_model_and_branch_names

**Comment by ChristopheDeprezCNRC** [comment]
Try specifying tiktoken==0.3.3 in extensions/openai/requirements.txt
