### ISSUE TITLE
serving on mysubdomain.mydomain.com

### ISSUE THREAD

**Issue by itscvenk** [oobabooga/text-generation-webui#4871]
### Describe the bug

Firstly thanks a MILLION to all those folks who are behind this!!! I love you guys!

I am running inside Conda (with --share) . I get a xxxx.gradio.live link and that works just fine! Hats off! 

I have mysubdomain.mydomain.com pointing to this IP address where it is running. Firewall is open on the port (else the goradio.live link won't work anyway). I have certbots also installed and  letsencrypt certificates installed too. It is a static Ip. hostname and /etc/hosts/ for the domain are updated

However, when I access http or https with mysubdomain.mydomain.com:7860 ,  the connection just times out on the web browser!

Is this normal? What else do I need to do please?

Thanks 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Conda install

### Logs

```shell
Don't see any!
```

### System Info

```shell
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

~$ nvidia-smi
Mon Dec 11 00:46:50 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000001:00:00.0 Off |                    0 |
| N/A   32C    P8     9W /  70W |      5MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by itscvenk** [comment]
Need to try with --listen --listen-port 7744 --listen-host  --ssl-keyfile etc

CLosing

**Comment by liamlah** [comment]
Hi there,

You asked a question, then it appears that you found a solution, but your solution is not clear, especially with the 'etc' at the end.
There are likely to be others who encounter this issue in the future.

Would you mind putting into words a brief summary of what you did to get it working? Enough that someone else could replicate it?
