### ISSUE TITLE
mixtral 8x7b update

### ISSUE THREAD

**Issue by RandomLegend** [oobabooga/text-generation-webui#4897]
Heyho,

afaik the mixtral branch of llama.cpp just [updated](https://github.com/ggerganov/llama.cpp/pull/4406) to be able to use the new [8x7b model](https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF).

Will this be available here aswell? If yes, do you have an estimate on when?

**Comment by iChristGit** [comment]
I would be so happy if Mixtral+Quip# would be supported natively, as both of them are hard to figure out on windows machines.
running a MoE 2bit with great precision 🔥

**Comment by oobabooga** [comment]
First it goes to llama.cpp master branch, then to llama-cpp-python, then to [llama-cpp-python-cuBLAS-wheels](https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels), then here.

You can create a custom llama-cpp-python build in the meantime: https://www.reddit.com/r/Oobabooga/comments/18gijyx/simple_tutorial_using_mixtral_8x7b_gguf_in_ooba/

**Comment by RandomLegend** [comment]
@oobabooga yeah that's what i found 30 min ago aswell and now i'm up and running and my goodness is this model awesome!

**Comment by Empor-co** [comment]
llama-cpp-python-cuBLAS-wheels are being built (as of 5h ago)...
[llama-cpp-python-cuBLAS-wheels](https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels/issues/34)

**Comment by sep332** [comment]
And the wheels are ready!
