### ISSUE TITLE
coqui_tts fails to load as assumes interactive sessions to accept ToS

### ISSUE THREAD

**Issue by sammcj** [oobabooga/text-generation-webui#4901]
### Describe the bug

When enabled coqui_tts prevents textgen from starting as it expects an interactive session for a user to accept a ToS agreement

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

- Enable coqui_tts
- Restart textgen
- Note that textgen never starts
- Check console logs
```
2023-12-12 22:13:22 INFO:Loading the extension "coqui_tts"...
[XTTS] Loading XTTS...
 > You must agree to the terms of service to use this model.
 | > Please see the terms of service at https://coqui.ai/cpml.txt
 | > "I have read, understood and agreed to the Terms and Conditions." - [y/n]
```
- No way to accept non-interactively

### Logs

```shell
INFO:     Started server process [37]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5001 (Press CTRL+C to quit)
2023-12-12 22:13:18 DEBUG:Intercepting all calls to posthog.
2023-12-12 22:13:19 DEBUG:Creating Sentence Embedder...
2023-12-12 22:13:20 WARNING:Using embedded DuckDB without persistence: data will be transient
2023-12-12 22:13:22 DEBUG:Loading hyperparameters...
2023-12-12 22:13:22 INFO:Loading the extension "coqui_tts"...
[XTTS] Loading XTTS...
 > You must agree to the terms of service to use this model.
 | > Please see the terms of service at https://coqui.ai/cpml.txt
 | > "I have read, understood and agreed to the Terms and Conditions." - [y/n]
```

### System Info

```shell
Latest official docker image running on server.
```

Note that a workaround for this is to remove coqui_tts and install "alltalk_tts" instead which seems to work without issue.

**Comment by erew123** [comment]
I believe that in the models download folder (which it downloads on FIRST start-up of the TTS) it creates **tos_agreed.txt** in the folder it downloads the TTS model to. And this is its "the person already pressed Y". Obviously, the location is different on windows/linux and I have no clue on Mac...

![image](https://github.com/oobabooga/text-generation-webui/assets/35898566/250e6740-79ab-4a1b-86fc-020aab34933c)

Contents of that file are as follows:

![image](https://github.com/oobabooga/text-generation-webui/assets/35898566/3eaf41e8-b394-45f6-9eb7-4ee6909ada94)

`I have read, understood and agreed to the Terms and Conditions.`

I think there may be something new about bypassing this in the TTS 21.3 or 22.0 update. I have a vague memory of seeing something on a post on the coqui_tts discussion board.

Im guessing if the folder was created ahead of time, or a **tos_agreed.txt** file being placed in that folder, would bypass the question, though, I have no idea if that would meet Coqui's license terms (aka the user hasn't actually agreed), hence it may be better to check out if there is a bypass switch now on the TTS engine OR print off an on-screen "by using this software you are agreeing to the Coquii TTS license, which you can find here........https://blah" (which is what I did on AllTalk.

**Comment by sammcj** [comment]
Ah, I tried creating a tos_agreed.txt after execing into the running container but - I didn't try adding any content to it, I bet that would have helped. Thanks for sharing.

INAL but I'd say that the interactive ToS popup could be mitigated by either having a clear ToS notification and link when the extension gets enabled / installed in the UI (e.g. a mouse over or one-time warning).

**Comment by missionfloyd** [comment]
Update textgen, this has been fixed.
