### ISSUE TITLE
I want to access the page using a local IP4 address (192.168.X.X:7860) but it doesn't work

### ISSUE THREAD

**Issue by hell99dkx** [oobabooga/text-generation-webui#4932]
I tried to access the page using a local IP4 address, but failed. I want to access this page on another computer in the local area network. Is there any way to solve this problem?

**Comment by S95Sedan** [comment]
Normally you are uppose to add something in the CMD_FLAGS.
But you can edit this file aswell, installer_files\env\Lib\site-packages\gradio - line 32:
```LOCALHOST_NAME = os.getenv("GRADIO_SERVER_NAME", "127.0.0.1")```

**Comment by zwilch** [comment]
have you tried to use --listen parameter on start 
http://127.0.0.1:7860 
http://0.0.0.0:7860 <= with "--listen" you can connect from other computers in network

**Comment by hell99dkx** [comment]
> 通常，您会在CMD_FLAGS中添加一些东西。但是您也可以编辑此文件，installer_files\env\Lib\site-packages\gradio - 第 32 行： `LOCALHOST_NAME = os.getenv("GRADIO_SERVER_NAME", "127.0.0.1")`

I am indeed able to successfully access the page using the IP4 address, but the original 127.0.0.1 is not working. Is there a way for me to access the page using both?

**Comment by iameru** [comment]
this is rather a networking question than one about this software.
However, you can search for "port forwarding". I have `text-generation-webui` running in a linux VM and I am doing something like `ssh -L 8000:127.0.0.1:7860 user@10.0.0.2` Where 10.0.0.2 is the IPv4 of the system running `text-generation-webui`, `7860` is its port, `127.0.0.1` is the adress locally as seen by `10.0.0.2` and `8000` is my local port. So I can then visit `localhost:8000` in my browser and there it is. Might get you started.

**Comment by NXTler** [comment]
The flags `--listen --listen-port 7860` work great for me
