### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 125: character maps to <undefined>

### ISSUE THREAD

**Issue by VertexMachine** [oobabooga/text-generation-webui#4947]
### Describe the bug

That is probably locale-dependant thing, but some models complain on decoding error. Here's diff to fix:

```python
diff --git a/modules/models_settings.py b/modules/models_settings.py
index 8a4febd..90c7b69 100644
--- a/modules/models_settings.py
+++ b/modules/models_settings.py
@@ -102,7 +102,7 @@ def get_model_metadata(model):
     # Try to find the Jinja instruct template
     path = Path(f'{shared.args.model_dir}/{model}') / 'tokenizer_config.json'
     if path.exists():
-        metadata = json.loads(open(path, 'r').read())
+        metadata = json.loads(open(path, 'r', encoding='utf-8').read())
         if 'chat_template' in metadata:
             template = metadata['chat_template']
             for k in ['eos_token', 'bos_token']:
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Eg. see https://huggingface.co/LoneStriker/deepseek-coder-33b-instruct-4.65bpw-h6-exl2/discussions/1#657daf9c9a9e347d4b9fc544

### Logs

```shell
See: https://huggingface.co/LoneStriker/deepseek-coder-33b-instruct-4.65bpw-h6-exl2/discussions/1#657daf9c9a9e347d4b9fc544
```

### System Info

```shell
windows
```

**Comment by Nyandaro** [comment]
Thanks nice hint

A similar error occurred with the AWQ model, but it worked.
＞UnicodeDecodeError: 'cp932' codec can't decode byte 0x81 in position 451: illegal multibyte sequence

**Comment by NickWithBotronics** [comment]
I tried made the same edits, but i still cant load any of the deep seek models unless its in ggml. Tried them all and i get the x81 byte

`Traceback (most recent call last):
  File "C:\Users\PC\Documents\text-generation-webui\modules\ui_model_menu.py", line 214, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(selected_model, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Documents\text-generation-webui\modules\models.py", line 79, in load_model
    metadata = get_model_metadata(model_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Documents\text-generation-webui\modules\models_settings.py", line 115, in get_model_metadata
    metadata = json.loads(open(path, 'r', encoding='utf-8').read())
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PC\Documents\text-generation-webui\installer_files\env\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 125: character maps to <undefined>

`

**Comment by BadisG** [comment]
I have the same error for GGUF and exl2 models, if someone found the solution I'll be happy to take that information

**Comment by BadisG** [comment]
By taking inspiration from this
https://huggingface.co/LoneStriker/deepseek-coder-33b-instruct-4.65bpw-h6-exl2/discussions/1#657db96ba982e9093f675299

On the file D:\text-generation-webui\modules\models_settings.py
If you replace all the 
```
metadata = json.loads(open(path, 'r').read())
```
By
```
metadata = json.loads(open(path, 'r', encoding='utf-8').read())
```
The loading works, but it's still not really working, on the output I only have line jumps and nothing else, that's as far as I could go

**Comment by VertexMachine** [comment]
Fixed by @B611 in https://github.com/oobabooga/text-generation-webui/pull/5125
