### ISSUE TITLE
Make the maximum temperature 5.0 instead of 2.0

### ISSUE THREAD

**Issue by kalomaze** [oobabooga/text-generation-webui#4952]
**Description**

The maximum temperature can be set to infinity with temperature last and a high-ish Min P and your text will still come out coherently. I think a reasonable range is 0-5.0 for the interface instead of 0-2.0 as a result.
This means you can make the choice between the tokens effectively random, while still excluding all bad choices, and it'll still work coherently assuming temp_last is on.

**Comment by oobabooga** [comment]
Done https://github.com/oobabooga/text-generation-webui/commit/c9d814592e8463de2ed4c169e5ddafa9bbbd219d
