### ISSUE TITLE
multiple deepspeed runs in a single machine

### ISSUE THREAD

**Issue by huangjiaheng** [oobabooga/text-generation-webui#496]
### Describe the bug

![image](https://user-images.githubusercontent.com/18376413/226968122-01b912e5-0069-4b78-9a84-a8a6acd1e45e.png)

deepspeed --num_gpus=2 server.py --deepspeed --cai-chat --model pygmalion-6b

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

deepspeed --num_gpus=2 server.py --deepspeed --cai-chat --model pygmalion-6b

### Logs

```shell
deepspeed --num_gpus=2 server.py --deepspeed --cai-chat --model pygmalion-6b
```

### System Info

```shell
deepspeed --num_gpus=1 server.py --deepspeed --cai-chat --model pygmalion-6b
```

**Comment by oobabooga** [comment]
Possibly one of the parameters here is messed up for multigpu setups: https://github.com/oobabooga/text-generation-webui/blob/main/modules/deepspeed_parameters.py

I don't have more than 1 gpu to test, but if you find a solution, let me know.

**Comment by oobabooga** [comment]
Discussion moved here https://github.com/oobabooga/text-generation-webui/issues/561
