### ISSUE TITLE
start_windows.bat won't launch console properly

### ISSUE THREAD

**Issue by EthabTab** [oobabooga/text-generation-webui#4977]
### Describe the bug

I downloaded the text-generation-webui-main zip, unzipped it, and tried to run the start_windows.bat file. It launches command prompt for a split second, and then immediately closes. I've tried running it as administrator, running the cmd_windows.bat and update_windows.bat, and they all still only open the command prompt for a second.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Download the file
Unzip it
Open the start_windows.bat file
Crash

### Screenshot

https://github.com/oobabooga/text-generation-webui/assets/70746182/8a0e5b10-7693-41b3-989a-6a2d03c03583

### Logs

```shell
None
```

### System Info

```shell
Windows 11
Nvidia 3060 mobile
Intel i7 11800h
```

**Comment by TheLounger** [comment]
Run it from a command prompt to see any errors that might cause this:
- Start > Search `cmd` > choose Command Prompt
- `cd C:\Users\Owner\Downloads\text-generation-webui-main`
- `start_windows.bat`

Also, don't run it as Administrator, this could lead to even more problems.

**Comment by EthabTab** [comment]
Running it in command prompt fixed it, still not sure why it was crashing. Thanks!
