### ISSUE TITLE
Incorrect space tokenization on Yi-34

### ISSUE THREAD

**Issue by BugReporterZ** [oobabooga/text-generation-webui#4996]
### Describe the bug

When generating text with the latest development version of text-generation-webui and the officially "llamafied" **[Yi-34B](https://huggingface.co/01-ai/Yi-34B)** model (HF weights) loaded in 4bit with bitsandbytes, every space in the generated text gets converted into two spaces.

Text-generation-webui is started with the command `python server.py --verbose --extensions openai --model Yi-34B --load-in-4bit` but reloading the model in the UI doesn't solve the problem.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just generate any text with the model. The result is immediately clear.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/26941368/0615ea72-3026-4524-880c-47856a661133)

Copy-pasted output:
```
This is a chat between  the  two  of  us.
Lucas:  Hello,  this  is  Lucas  speaking.  I  am  calling  from  the  ABC  Radio  program  Conversations  with  Richard  Fidler.
Carmen:  Hi,  Lucas.
Lucas:  Carmen,  it’s  wonderful  to  speak  to  you  today.  I  know  that  we  were  talking  about  doing  this  for  a  while  and  you  are  so  busy  but  it  worked  out
```

### Logs

```shell
-
```

### System Info

```shell
Linux, NVidia RTX3090.
text-generation-webui from git.
```

**Comment by oobabooga** [comment]
Can you check if this closes it? https://github.com/oobabooga/text-generation-webui/commit/83cf1a6b67eebe80386842f2f12ebb4d8aec7be9

**Comment by BugReporterZ** [comment]
Yes, this appears to have solved the issue. Thanks!

![image](https://github.com/oobabooga/text-generation-webui/assets/26941368/e786af87-d6f3-4a7b-8610-0323e10bc9dc)
