### ISSUE TITLE
Are Radeon GPUs supported?

### ISSUE THREAD

**Issue by fromtheeast710** [oobabooga/text-generation-webui#5]
I'm getting `"hipErrorNoBinaryForGpu: Unable to find code object for all current devices!"` even with torch* set to +rocm5.2

**Comment by oobabooga** [comment]
It should work as long as you have the ROCm version of Pytorch installed. 

Can you try running this command before starting the webui?

`export HSA_OVERRIDE_GFX_VERSION=10.3.0`

[Found it randomly on Google](https://stackoverflow.com/questions/73575955/pytorch-hiperrornobinaryforgpu-unable-to-find-code-object-for-all-current-devi). Some people say it works.

**Comment by fromtheeast710** [comment]
That works, thank you.
