### ISSUE TITLE
[Suggestion] Make the saved dialogue the same as saved images in automatic webui

### ISSUE THREAD

**Issue by Manimap** [oobabooga/text-generation-webui#50]
Hello,
Just a few suggestions to make the dialogue save more practical by : 
- saving it in a subfolder in format "character name - model" 
- ask for dialogue name to add when saving it, maybe append automatically with timestamp YYMMDD

**Comment by oobabooga** [comment]
That's a good idea.

>ask for dialogue name to add when saving it

Sorry, I don't understand. What do you mean?

**Comment by oobabooga** [comment]
The chat logs are already saved to the `logs` subfolder whenever you click on "Click me". Now they get a default name in the format

Character Name_20230203-12:34.json
