### ISSUE TITLE
Character sheet bug in latest version! Use {{char}} and {{user}} tags in history!

### ISSUE THREAD

**Issue by mykeehu** [oobabooga/text-generation-webui#5007]
### Describe the bug

When I chat, I see the console and I noticed that there is a bug in the character sheet and the {{char}} and {{user}} tags can be seen instead of the real names! The names are not swapped when loading the character sheet! Check it out!
I'm investigating which build this broke in, because that's why it may have been generating stupidity in the last few weeks, and I haven't noticed it until now.
Ok, this build was ok: aab0dd962d9f48e9524f8e602f7252a27ed85870
And then comes the Jinja conversion, that's where the problem happened. :(
I use [AI Character Editor](https://zoltanai.github.io/character-editor/) .json files.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Just make a chat, and see console!

### Logs

```shell
-
```

### System Info

```shell
i9-13900K
64 GB RAM
RTX 3090 24 GB
Windows 10 64-bit
5b791cae4a626713b4cb841178adef4ba1121dba checkout
```

**Comment by oobabooga** [comment]
I think that this should solve it https://github.com/oobabooga/text-generation-webui/commit/d8279dc71083a1b150bde340f95d17b2cb1d6a75
