### ISSUE TITLE
Beginnging of response is cut out / missing

### ISSUE THREAD

**Issue by onusai** [oobabooga/text-generation-webui#503]
### Describe the bug

Ive tested several alpaca models and iv'e noticed that start of the response is almost always missing.

Might be similar to this issue: https://github.com/oobabooga/text-generation-webui/issues/300

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load Alpaca model https://huggingface.co/elinas/alpaca-30b-lora-int4/tree/main and generate using this prompt:
```
Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.

### Instruction:
Write a python function that adds two numbers

### Response:
```
### Screenshot

![image](https://user-images.githubusercontent.com/18707771/227051086-04e82389-c6a9-4f3b-8726-8580a9da9437.png)

### Logs

```shell
Output generated in 4.61 seconds (4.12 tokens/s, 19 tokens)
```

### System Info

```shell
Windows 11, RTX3090
```

**Comment by onusai** [comment]
After further testing, it appears that issue occurs when max_new_tokens is >= 1992. This issue does not occur with max_new_tokens is < 1992, but it does duplicate the last token of the input.

**Comment by oobabooga** [comment]
This is being caused by your prompt being truncated. Try reducing `max_new_tokens`.

**Comment by onusai** [comment]
Yep that seems to fix it. Is there a reason this isnt automatically calculated? something like `max_new_tokens = contex_size - len(prompt)`?

**Comment by oobabooga** [comment]
For generating long text (like a long novel) in several iterations (clicking on Continue multiple times), it is convenient to truncate the beginning of the text to make room for new text. This is related to #498 btw
