### ISSUE TITLE
SuperboogaV2 Error on Windows 11

### ISSUE THREAD

**Issue by shamio** [oobabooga/text-generation-webui#5063]
### Describe the bug

I am using snapshot-2023-12-17 and everything works fine. But I enabled SuperboogaV2 and after restarting the app, Installing Visual C++ and running ( pip install -r extensions\superboogav2\requirements.txt --upgrade) and restating the computer, I still get errors like the screenshot. Please help me to solve this issue.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the app, and you will get the error.

### Screenshot

![Image 222](https://github.com/oobabooga/text-generation-webui/assets/1525160/953b3d34-fdf1-42ee-93ad-706091a6bfde)

### Logs

```shell
Starting Text generation web UI
01:45:31-433935 INFO     Loading settings from settings.yaml
01:45:31-590190 INFO     Loading the extension "gallery"
01:45:31-621435 INFO     Loading the extension "superboogav2"
01:45:35-125393 ERROR    Could not import the requirements for 'superboogav2'. Make sure to install the requirements
                         for the extension.

                         Linux / Mac:

                         pip install -r extensions/superboogav2/requirements.txt --upgrade

                         Windows:

                         pip install -r extensions\superboogav2\requirements.txt --upgrade

                         If you used the one-click installer, paste the command above in the terminal window opened
                         after launching the cmd script for your OS.
01:45:35-141000 ERROR    Failed to load the extension "superboogav2".
Traceback (most recent call last):
  File "D:\text-generation-webui\modules\extensions.py", line 37, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "D:\text-generation-webui\extensions\superboogav2\script.py", line 20, in <module>
    from .chromadb import make_collector
  File "D:\text-generation-webui\extensions\superboogav2\chromadb.py", line 11, in <module>
    from sentence_transformers import SentenceTransformer
ModuleNotFoundError: No module named 'sentence_transformers'
01:45:35-203575 INFO     Loading the extension "long_replies"
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
Windows 11 Pro build 22631.2861
GPUL no GPU (Intel graphics)
```

**Comment by TheInvisibleMage** [comment]
You may need to run the "pip install -r extensions\superboogav2\requirements.txt" from within the terminal provided by the "cmd_windows.bat" file in the "text-generation-webui" folder. If you run the command without doing so, it installs the packages onto your host machine, while I believe running it with the command instead installs them into the "text-generation-webui/installer_files/env" folder, which seems to be the environment actually used by the program.

**Comment by shamio** [comment]
@ [TheInvisibleMage](https://github.com/TheInvisibleMage) thank you so much for your great info. The issue is fixed and its working now :)
I tried every method and none of them worked, but your help fixed the issue completely.

**Comment by Urammar** [comment]
Hi, to any future people, this is where I ended up after searching and resolved the issue. So just so you know, you might also have to change the requirements.txt in the superboogav2 folder to include

pydantic==1.10.12

at the end of it. Do this if the above solution does not work, regressing to that version fixed things for me. In addition, what I got suck on for a while because I wasnt thinking, so i'll spell it out for others, if you still have the webui open in another cmd window to reload the extension, (i know you did, its how you knew what to google), its actually still write protecting files that its accessing, despite no such error being reported. You have to close it, do the upgrade, then run it again.

So for windows, close the ooba cmd runtime, open the cmd_windows.bat file and run

pip install -r extensions\superboogav2\requirements.txt --upgrade

Then run ooba again and load the extension.

**Comment by davidthedolphin** [comment]
> Hi, to any future people, this is where I ended up after searching and resolved the issue. So just so you know, you might also have to change the requirements.txt in the superboogav2 folder to include
> 
> pydantic==1.10.12
> 
> at the end of it. Do this if the above solution does not work, regressing to that version fixed things for me. In addition, what I got suck on for a while because I wasnt thinking, so i'll spell it out for others, if you still have the webui open in another cmd window to reload the extension, (i know you did, its how you knew what to google), its actually still write protecting files that its accessing, despite no such error being reported. You have to close it, do the upgrade, then run it again.
> 
> So for windows, close the ooba cmd runtime, open the cmd_windows.bat file and run
> 
> pip install -r extensions\superboogav2\requirements.txt --upgrade
> 
> Then run ooba again and load the extension.

Worked for me, thank you !
