### ISSUE TITLE
Option to save all generated output to log file

### ISSUE THREAD

**Issue by ill13** [oobabooga/text-generation-webui#507]
**Save all generated text**

Log every thing generated for later review. The saved chats are nice

**Comment by ill13** [comment]
- Tired of cutting and pasting results you like?
- Lost the query AND the results you liked?

Well, I cobbled this plugin script together to save all prompts and the resulting generated text into a text file.

Just copy the `save_data` folder to your extensions folder and enable it. Look in `/logs` for a file like *20230325_text_log.txt* after generating 

The plugin:
- Should* create a new file every day.
- Should append new prompts and results to said file
- Can enabled by adding `--save_data` to after `--extensions`. 

https://github.com/ill13/text-generation-webui/tree/main/extensions/save_data

**Comment by oobabooga** [comment]
I have added an option to save the current prompt that can be used for this. Nice job with the extension as well!

**Comment by vractal** [comment]
@ill13 Thanks, I was looking for this! I added a simple debounce to your extension so I can use it without the --no-stream, works fine.. I can push to you if you want

**Comment by vractal** [comment]
@oobabooga do you mean the download option?

**Comment by ill13** [comment]
@vractal  Feel free to fork/push as you see fit; I don't know git well enough to do so myself.
