### ISSUE TITLE
When loading models webui silently crashes with no error

### ISSUE THREAD

**Issue by TAK-YON** [oobabooga/text-generation-webui#5076]
### Describe the bug

Having trouble with this, I can use transformers on full precision models with offloading but token generation on the cpu, when trying to load GPTQ models using ExLlama/2 or when using their kernels with transformers it starts loading, but midway through loading closes silently, no errors or logs produced even with verbose logging

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load a model with GPU generation enabled

### Logs

```shell
No logs, just closes
```

### System Info

```shell
OS: Nixos Unstable
CPU: 5800X3D
RAM: 32GB DDR4
GPU: PowerColor 6700XT 12GB
ROCM: 5.7.1
```

**Comment by WIZI-SSS** [comment]
I have a similar issue. I'm trying to load "cognitivecomputations/dolphin-2.5-mixtral-8x7b" model but it stopes at 47%.
### It how "Error" looks like in console:
`20:57:40-743336 INFO     Loading cognitivecomputations_dolphin-2.5-mixtral-8x7b
Loading checkpoint shards:  47%|██████████████████████████▌                             | 9/19 [02:31<03:01, 18.14s/it]
To continue, press any key. . .``
![Снимок экрана (241)](https://github.com/oobabooga/text-generation-webui/assets/111757175/68a7e339-bdcc-4d87-b9c8-33df29e03736)


This is my first model that I'm trying to load, I haven't tried other models.

### System Info
OS: Windows 10
CPU: Intel(R) Core(TM) i5-10300H
RAM: 16GB 
GPU: NVIDIA GeForce GTX 1650(laptop)

**Comment by TAK-YON** [comment]
i think i might've found a hint to what the problem is, it might need rocmBLAS to function but i'm not 100% on that.

**Comment by TAK-YON** [comment]
progress! there is now something to work from now 

`23:54:37-821780 INFO     Loading dolphin-2.7-mixtral-8x7b.Q5_K_M.gguf
23:54:37-888229 INFO     llama.cpp weights detected: models/dolphin-2.7-mixtral-8x7b.Q5_K_M.gguf
rocBLAS error: Cannot read /home/takyon/text-generation-webui/installer_files/env/lib/python3.11/site-packages/torch/lib/rocblas/library/TensileLibrary.dat: Illegal seek`

so yeah installing rocmBLAS didn't make it work, but it did actually give an error to work from, though the problem might lie within pytorch instead of webui

**Comment by TAK-YON** [comment]
Okay, found a solution. 
Need hipBLAS, rocBLAS and a few other libraries. 

need to `export HSA_OVERRIDE_GFX_VERSION=10.3.0` to allow it to load on a 6700XT since tensile/rocm doesn't officially support it? no idea really, anyway. changing the instruction set to 10.3.0 just bypasses the problem entirely and allows it to load.
