### ISSUE TITLE
OpenAI completions endpoint significantly slower than generation in Gradio UI

### ISSUE THREAD

**Issue by roligheten** [oobabooga/text-generation-webui#5113]
### Describe the bug

I am working on an integration via the OpenAI completions endpoint but I am having issues with very slow slow token/s when using the endpoint vs what I am getting in the UI.

Below I have highlighted in yellow the generations called via the completions endpoint, while the white lines are generated from the UI RAW interface. The speed is significantly slower even though I am running with much smaller context. Note the first generation was the first after loading the model which is always slower than average.
![image](https://github.com/oobabooga/text-generation-webui/assets/3079059/71f4feb9-fc26-423f-8cfc-3fc32ce60023)

I have not tried replicating the setting in the UI vs. API 1 to 1 but as far as I know none of the temp, top_p, etc. settings impact generation speed. I am running the default API settings other than setting max_tokens to 100. I also tried stream: true vs false and it did not make a noticeable difference.

Curious if anyone else can reproduce this issue or have any idea why this might be happening. :slig

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Go to Notebook -> RAW and generate completion with any 200ish context tokens. Note the tokens/s.

Call the /v1/completions API with the same prompt, wait for a response and note the tokens/s in the terminal.

See that the generation is slower when calling the API vs from the UI.

### Screenshot

In description

### Logs

```shell
No errors
```

### System Info

```shell
NVIDIA GeForce 3060
```

**Comment by roligheten** [comment]
Correction: turns out this issue was related to the choice of parameters, specifically the default settings for the OpenAI endpoint was using top_p=1, top_k=0. In the UI I was running top_k=50. I am not sure exactly why this impact generation speed so much but my guess is that with top_p=1 and top_k=0 there is no token pruning and and evaluating every token is very slow for some reason. Setting top_k=50 would cap the tokens to 50. Not sure if this is expected or not but at least the issue above is not relevant.

**Comment by TheDarkTrumpet** [comment]
Another option you may want to consider is to also look at the terminal (especially if using llama.cpp's loader) and look at the text completion rate.  Your image didn't come through, so maybe you did that.  But try to note the numbers there, and match your parameters (under the parameters tab) exactly with what you do to call.  You may also want to further look at doing a straight up curl call against the API with the same parameters.

It could be the OpenAI library, it could be the abstraction within text-generation-webui, could be network (unlikely?).  But playing with those could be useful.

To test out the curl option, you could do something like the below (it's a .http file, used to make API calls):

```
POST http://localhost:5000/v1/completions HTTP/1.1
content-type: application/json

{
    "prompt": "This is a cake recipe:\n\n1.",
    "max_tokens": 1024,
    "temperature": 1,
    "top_p": 0.9,
    "seed": 10
}
```
