### ISSUE TITLE
NameError: name 'deepspeed' is not defined

### ISSUE THREAD

**Issue by caterpillarpants** [oobabooga/text-generation-webui#5122]
Ug. I can't figure out this error message. I have overcome some, but I can't beat this one.

I start with:
`deepspeed --num_gpus=1 server.py`

then I navigate to session and choose deepspeed and restart.
incidentally, the directions say to start with: `deepspeed --num_gpus=1 server.py --deepspeed `
but upon loading a model, this generates a low_cpu_mem=True error. Then it is recommended that I install accelerate, but this does not work. However, if I start with `deepspeed --num_gpus=1 server.py` and then select deepspeed in the "session" tab I do not get the low_cpu_mem=True error.

when I try to load a model, this error appears:
NameError: name 'deepspeed' is not defined
how can I overcome this one?

**Comment by bet0x** [comment]
@caterpillarpants  https://github.com/oobabooga/text-generation-webui/wiki/08-%E2%80%90-Additional-Tips#deepspeed follow those steps.

**Comment by caterpillarpants** [comment]
Sorry it's been so long. It's been a busy time. In answer to your question as to whether I followed the directions.

Well, technically, I didn't run the conda line at install. I just ran pip. This because I haven't been using conda and would like to avoid it if possible. Do you think this is the issue? Everything else has worked more or less without.

I've now updated and when I run `pip install -U deepspeed` it installs, but when I try to run `deepspeed --num_gpus=1 server.py --deepspeed --chat` it won't start and complains that the accelerate version is wrong. It wants accelerate 0.21.0, but I have 0.20.3. And worse, if I try to `pip install accelerate==0.21.0` it seems to work(where it didn't two weeks ago), but I get the same error that I don't have accelerate 0.21.0 when I run deepspeed, but it's there if I do a `pip list` I'm telling you. it's there, man!

Any suggestions?

**Comment by 78Alpha** [comment]
I hope this is not a windows environment.
