### ISSUE TITLE
Other stopping conditions besides new line

### ISSUE THREAD

**Issue by Ph0rk0z** [oobabooga/text-generation-webui#513]
**Description**

So since stop at "\n" was defaulted the choice is to either have really short replies or the bot going off and talking for you.

Does it makes sense to add Botname: and Username: as optional stopping criteria to have the best of both worlds and avoid this bug?

Mainly it matters in chat.

**Comment by oobabooga** [comment]
I have been bothered by the `Person 1` and `Person 2` defaults... I have changed them to "You" and "Assistant" 

https://github.com/oobabooga/text-generation-webui/commit/c5ebcc5f7e862b1f2c6b1d807bbf2c1aadeb159e

**Comment by USBhost** [comment]
There seems to be an issue idk if it's because of this. So in my case when I got a prompt I did not like I hit stop and hit regenerate. But after it regenerates a then when I do a reply it does not post and it replaces the last prompt with the one I hit stop. This has already happened to me twice.

**Comment by Ph0rk0z** [comment]
I have to hit stop twice.. I thought it was me but its happening on all models.

**Comment by oobabooga** [comment]
There is definitely something weird going on with the Stop button. The `generate_reply` function sometimes never reaches the `finally` block after Stop is clicked: https://github.com/oobabooga/text-generation-webui/blob/main/modules/text_generation.py#L271

**Comment by oobabooga** [comment]
I think that this fixed the Stop button in chat mode: https://github.com/oobabooga/text-generation-webui/commit/fd99995b01878246b62302d31a844dd68ee7d139

If you still see weird behavior, please let me know.

**Comment by Brawlence** [comment]
Still reproducible, at least with disabled streaming (for text to speech):

![image](https://user-images.githubusercontent.com/42910943/227729902-8d9332e5-0f7d-474b-bc35-4cf4704dfd0f.png)

**Comment by oobabooga** [comment]
That's not a bug, in this case. The character's name is "Assistant" and not "The Assistant", so the stopping criteria don't recognize that as a new character turn.

**Comment by USBhost** [comment]
![image](https://user-images.githubusercontent.com/7269941/228971191-a9084945-03eb-4d46-93d0-446c2695d0d2.png)

So thoughts?

**Comment by oobabooga** [comment]
With streaming or without streaming? What model?

**Comment by USBhost** [comment]
With streaming aka default?  `python server.py --listen --wbits 4 --groupsize 128 --cai-chat --model llama-65b-test`

Currently testing GPTQ triton

**Comment by oobabooga** [comment]
That's frustrating. This is the callback that finds the new character turn: https://github.com/oobabooga/text-generation-webui/blob/main/modules/callbacks.py#L13

**Comment by USBhost** [comment]
I did modify modules/GPTQ_loader.py to allow me to even load. I removed `faster=faster_kernel, kernel_switch_threshold=kernel_switch_threshold` from https://github.com/oobabooga/text-generation-webui/blob/main/modules/GPTQ_loader.py#L36
