### ISSUE TITLE
No module loading

### ISSUE THREAD

**Issue by ClericerQ** [oobabooga/text-generation-webui#5138]
### Describe the bug

I use windows and installed the latest version from git. 
Not a single model is loading on 2 PCs with CPU or GPU. Stable diffusion runs perfectly on my 4080.
I used the default installer provided by OOBABOOGA start_windows.bat  i allways get the error :     
from awq import AutoAWQForCausalLM
ModuleNotFoundError: No module named 'awq'
And yes the requirements txt runs through and installed all packages without any warnings or errors.
The same for GPTQ and its models.
I alsow made a setup with anaconda and a different python version in its environment, same error.

After nothjing worked i tryed instaling AWQ default provided pip package: the result: 
ImportError: DLL load failed while importing awq_inference_engine: Das angegebene Modul wurde nicht gefunden.

Can someone tell me what to do to fix this issue?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install oobabooga and load any modal, from 10 models not a single one works.

### Screenshot

![tryed these](https://github.com/oobabooga/text-generation-webui/assets/106805307/f6dc9c79-8a76-4b92-8507-c4ce51d01ee9)

### Logs

```shell
Traceback (most recent call last):

File "Z:\Artificial_Intelligence_Depp_Neural_Networks\text-generation-webui\modules\ui_model_menu.py", line 213, in load_model_wrapper

shared.model, shared.tokenizer = load_model(selected_model, loader)

                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "Z:\Artificial_Intelligence_Depp_Neural_Networks\text-generation-webui\modules\models.py", line 87, in load_model

output = load_func_map[loader](model_name)

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "Z:\Artificial_Intelligence_Depp_Neural_Networks\text-generation-webui\modules\models.py", line 310, in AutoAWQ_loader

from awq import AutoAWQForCausalLM

ModuleNotFoundError: No module named 'awq'
```

### System Info

```shell
First PC: 
  Windows 10 With Intel i7-12700 and RTX 4080  / 64gig ddr4 ram
Second PC:
  Ryzen 5 5600U with Radeon Graphics / 32 GB ddr4 Ram

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:36:15_Pacific_Daylight_Time_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0

```

**Comment by ingsilence** [comment]
I have the exact same issue, did not find solution to it though. If someone does please let me know.

**Comment by ingsilence** [comment]
> Same problem when loading TheBloke_deepseek-llm-67b-chat-AWQ. Possible reason - AWQ requires a GPU, but I don’t have one

AWQ does indeed require GPU, if you do not have it, it will not work.
Use GGUF instead [GGUF](https://huggingface.co/TheBloke/deepseek-llm-67b-chat-GGUF)
But make sure you have at least 32 Gb of RAM as the model you are trying to load is 67B, even the lovest version requires at least 31Gb.

**Comment by ingsilence** [comment]
> ### Describe the bug
> I use windows and installed the latest version from git. Not a single model is loading on 2 PCs with CPU or GPU. Stable diffusion runs perfectly on my 4080. I used the default installer provided by OOBABOOGA start_windows.bat i allways get the error : from awq import AutoAWQForCausalLM ModuleNotFoundError: No module named 'awq' And yes the requirements txt runs through and installed all packages without any warnings or errors. The same for GPTQ and its models. I alsow made a setup with anaconda and a different python version in its environment, same error.
> 
> After nothjing worked i tryed instaling AWQ default provided pip package: the result: ImportError: DLL load failed while importing awq_inference_engine: Das angegebene Modul wurde nicht gefunden.
> 
> Can someone tell me what to do to fix this issue?
> 
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Reproduction
> Install oobabooga and load any modal, from 10 models not a single one works.
> 
> ### Screenshot
> ![tryed these](https://private-user-images.githubusercontent.com/106805307/293513326-f6dc9c79-8a76-4b92-8507-c4ce51d01ee9.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODMzNDcsIm5iZiI6MTcwNDI4MzA0NywicGF0aCI6Ii8xMDY4MDUzMDcvMjkzNTEzMzI2LWY2ZGM5Yzc5LThhNzYtNGI5Mi04NTA3LWM0Y2U1MWQwMWVlOS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxMTU3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMWQwYjIxMmZjZTIxM2E3MjI3MWU5MTRkOGJkZWZjOTdkMDJjZjE5NTU2ZTlhMTczNGQ3ZTZhNmUwZDYzMDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iL27WiTa6rc6P0B9VUSwBc8sdqb5F3RP0rpw9vr3fSE)
> 
> ### Logs
> ```shell
> Traceback (most recent call last):
> 
> File "Z:\Artificial_Intelligence_Depp_Neural_Networks\text-generation-webui\modules\ui_model_menu.py", line 213, in load_model_wrapper
> 
> shared.model, shared.tokenizer = load_model(selected_model, loader)
> 
>                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> File "Z:\Artificial_Intelligence_Depp_Neural_Networks\text-generation-webui\modules\models.py", line 87, in load_model
> 
> output = load_func_map[loader](model_name)
> 
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> File "Z:\Artificial_Intelligence_Depp_Neural_Networks\text-generation-webui\modules\models.py", line 310, in AutoAWQ_loader
> 
> from awq import AutoAWQForCausalLM
> 
> ModuleNotFoundError: No module named 'awq'
> ```
> 
> ### System Info
> ```shell
> First PC: 
>   Windows 10 With Intel i7-12700 and RTX 4080  / 64gig ddr4 ram
> Second PC:
>   Ryzen 5 5600U with Radeon Graphics / 32 GB ddr4 Ram
> 
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2023 NVIDIA Corporation
> Built on Mon_Apr__3_17:36:15_Pacific_Daylight_Time_2023
> Cuda compilation tools, release 12.1, V12.1.105
> Build cuda_12.1.r12.1/compiler.32688072_0
> ```

IDK if it will work for you but what fixed it for me was reinstall of the whole webui but running all of the .bat files and cmd uses as administrator:

Used in cmd: `pip uninstall autoawq`
I deleted all files that were associated with the whole webui (whole text-generation-webui)
Restarted computer.
I opened cmd as administrator, changed directory in cmd to the place where I wanted to install oobabooga using command `cd`
used `git clone https://github.com/oobabooga/text-generation-webui.git` to download oobabooga files again.
run as administrator  start_windows.bat , waited for the url. 
downloaded the model using the model menu in the webui.

**Comment by ClericerQ** [comment]
Thank you very much,  on my 4080 i got it working like you descripted. Delete everything open Powershell (admin) and reload and reinstall everything as admin, now it works.
But the same procedure does not work for the cpu.

**Comment by ClericerQ** [comment]
Wanted to comment for anyone who has the same problem:
ON CPU to run ooabooga you have to choose one of the -GGUF models from TheBloke they worke perfectly fine for me, the response time is alsow fast enough, now its running on all PCs, linux, windows GPU and CPU. AWG and co do not work on any of the cpu versions. 
Realy nice work guys, thank you very much.

**Comment by RoyalCyan** [comment]
> Thank you very much, on my 4080 i got it working like you descripted. Delete everything open Powershell (admin) and reload and reinstall everything as admin, now it works. But the same procedure does not work for the cpu.

I am currently experiencing the same issue, however reinstalling everything as administrator didn't help. Any other solutions?

**Comment by ingsilence** [comment]
> > Thank you very much, on my 4080 i got it working like you descripted. Delete everything open Powershell (admin) and reload and reinstall everything as admin, now it works. But the same procedure does not work for the cpu.
> 
> I am currently experiencing the same issue, however reinstalling everything as administrator didn't help. Any other solutions?

Make sure you are using the right model type (AWQ or GGFU), delete everything associated with the webui, make sure that you selected the right mode in which the webui is operating (CPU, AMD or Nvidia), check if your pc has enough resources to even operate the model you are trying to use, if you have no other ai installed maybe try reinstalling torch, check if you have the right python version. Other than that I really do not know. Sorry.
