### ISSUE TITLE
Model consistently ignores prompts, and halluncinates other conversations

### ISSUE THREAD

**Issue by VNN-oss** [oobabooga/text-generation-webui#5153]
### Describe the bug

Currently, my chatbot has not been responding to my given prompts,consistently going off tangents, and I am unsure how this issue began.

I am using TheBloke_Wizard-Vicuna-13B-Uncensored-GPTQ, loaded with ExLlamav2_HF with the openai --api flag

<img width="356" alt="anika_current_chat_template" src="https://github.com/oobabooga/text-generation-webui/assets/70770522/9d69adcc-cde9-450a-804e-9c1c89e4422c">
The current chat template in the instruction-template tab I an currently utilizing, loaded from Vicuna v0
I have attempted to reload the model, instruction-template, and server several times, to no avail.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Uncertain on how this occurred in the first place.

### Screenshot

<img width="722" alt="anika_issue_6" src="https://github.com/oobabooga/text-generation-webui/assets/70770522/8cd47e8a-b12d-4ab5-83fe-c01f51103384">

### Logs

```shell
Model loads without error
```

### System Info

```shell
AMD Ryzen 7 5800HS
NVIDIA RTX 2060 GeForce embedded GPU
```

**Comment by verdelyi** [comment]
I feel like something's wrong with the handling of instruction templates right now. Try the --verbose flag and see what kind of prompts your UI actually generates. I have been getting some empty prompts lately (i.e., the template is ignored).

**Comment by VNN-oss** [comment]
I see, this is what I got, it's empty as hell
<img width="621" alt="anika_issue_7" src="https://github.com/oobabooga/text-generation-webui/assets/70770522/a1244455-f9ab-478f-a043-49e986693e10">

Is there an way to fix this?

**Comment by verdelyi** [comment]
It seems to help if you load the model first (which should hopefully load a default template) and don't touch the instruction template after that. Otherwise (if you want to play with templates), you may need to roll back (via git) to an older version (maybe from a month or two ago, before these fancy code-formatted templates appeared?).

**Comment by VNN-oss** [comment]
Thanks!

**Comment by Darkatse** [comment]
Same issue here, I'm using the 2080ti x2.
Could you please tell me which commit you rolled back to fix this problem?
