### ISSUE TITLE
CPU Usage

### ISSUE THREAD

**Issue by ClericerQ** [oobabooga/text-generation-webui#5187]
Hey guys, this project is crazy nice and i love it like stable-diffusion, crazy how great the ai development grows, and you are a big part of it.
But can anyone tell me why the cpu version limits the cpu to ~32cores i have a 77core server but its allway using less then 45% of the cpu performance. ( never more, i use a 50gig model currently)
![fixed at 45%](https://github.com/oobabooga/text-generation-webui/assets/106805307/5851fd0c-0d42-4d2f-887e-8979131afded)

**Comment by berkut1** [comment]
Did you enable NUMA? What type of backend do you use? Llama.cpp?

**Comment by zwilch** [comment]
change "ui_model_menu.py"
**maximum=120**
in line:
`shared.gradio['threads_batch'] = gr.Slider(label="threads_batch", minimum=0, step=1, **maximum=120**, value=shared.args.threads_batch)`

**Comment by ClericerQ** [comment]
You are awesome, thank you very much zwilich, that did the trick, it was hard limited to 32 threads, maybe this will be an optional feature, stable diffusion did it realy well with the ui config file.
