### ISSUE TITLE
Cuda out of memory when launching start-webui

### ISSUE THREAD

**Issue by jay5656** [oobabooga/text-generation-webui#522]
see below

**Comment by jay5656** [comment]
nevermind, just needed Conda, but now im getting this 
![Screenshot 2023-03-23 182236](https://user-images.githubusercontent.com/71863420/227378074-b1a636a1-2176-424e-b49e-d8ce6ca339c9.png)

**Comment by jay5656** [comment]
ive been getting this error even for stable diffusion and i know for a fact i have more than enough so i dont understand what the problem is 

i have a 3060 with 12GB 
![Screenshot 2023-03-23 184823](https://user-images.githubusercontent.com/71863420/227381706-89f37111-be2b-4da0-9abd-47bd8d1a7508.png)

**Comment by RoARene317** [comment]
If it's out of memory, indeed out of memory. If you load full FP32 , well it's going out of memory very quickly. I recommend you to load in BF16 (by using --bf16) and combine with auto device / GPU Memory 8, or you can choose to load in 8 bit.

**Comment by jay5656** [comment]
> If it's out of memory, indeed out of memory. If you load full FP32 , well it's going out of memory very quickly. I recommend you to load in BFLOAT16 (by using --bf16) and combine with auto device / GPU Memory 8, or you can choose to load in 8 bit.
> 
> How do I know? I also have RTX 3060 12GB Desktop GPU

I'll try the bf16 and see if it works. As for load 8 bit, I can't, that requires the Nvidia cuda toolkit which I don't have the space for. 

Also what about the other error? The pytorch 2.0 set from_tf=true 
I have no idea how to do that

**Comment by RoARene317** [comment]
> > If it's out of memory, indeed out of memory. If you load full FP32 , well it's going out of memory very quickly. I recommend you to load in BFLOAT16 (by using --bf16) and combine with auto device / GPU Memory 8, or you can choose to load in 8 bit.
> > How do I know? I also have RTX 3060 12GB Desktop GPU
> 
> I'll try the bf16 and see if it works. As for load 8 bit, I can't, that requires the Nvidia cuda toolkit which I don't have the space for.
> 
> Also what about the other error? The pytorch 2.0 set from_tf=true I have no idea how to do that


Unless you are using TF, then don't care about it.

**Comment by RoARene317** [comment]
The problem is on the system memory. You only have 16GB which is inadequate for this type of workload. I have 32GB RAM and it's filled around 20 - 24 GB when I use BF16. Try using INT8 (--use-in-8bit ? I forgot) format, it should enough for you

**Comment by jay5656** [comment]
> The problem is on the system memory. You only have 16GB which is inadequate for this type of workload. I have 32GB RAM and it's filled around 20 - 24 GB when I use BF16. Try using INT8 (--use-in-8bit ? I forgot) format, it should enough for you

There's no way this text engine needs more RAM than stable diffusion
Is stable diffusion not more taxing? 

If I can run that with 16gb, I think I should be able to run this

**Comment by jay5656** [comment]
> > > The problem is on the system memory. You only have 16GB which is inadequate for this type of workload. I have 32GB RAM and it's filled around 20 - 24 GB when I use BF16. Try using INT8 (--use-in-8bit ? I forgot) format, it should enough for you
> > 
> > 
> > There's no way this text engine needs more RAM than stable diffusion Is stable diffusion not more taxing?
> > If I can run that with 16gb, I think I should be able to run this
> 
> Stable Diffusion is really light actually, when I tried to load with BF16 purely, it's instant crash because of the GPU Out of memory. Using Auto device it's consume more than 20GB of RAM. Here is a picture below running on BF16
> 
> Specs: Ryzen 5 5600G 32GB RAM DDR4 3600MHz RTX 3060 12GB
> 
> ![image](https://user-images.githubusercontent.com/24410807/227583932-83766dd5-4572-4100-9c6e-26a0433a8d44.png)

Could I fix this if I use Linux instead? Cause currently, either my CPU memory is broken, or my motherboard 2 RAM slots are broken, so I can't exactly get more RAM right now since I can't replace one of those right now

**Comment by RoARene317** [comment]
![image](https://user-images.githubusercontent.com/24410807/227585090-f5f00cdb-3160-4d9b-a1bd-5f0b1022b97c.png)
Here is my WSL without any workloads, only 1.6G of RAM taken, still it's requires a lot of RAM.

**Comment by jay5656** [comment]
> > Could I fix this if I use Linux instead? Cause currently, either my CPU memory is broken, or my motherboard 2 RAM slots are broken, so I can't exactly get more RAM right now since I can't replace one of those right now
> 
> Assume it's using Linux WSL , taking around 1 Gigs of RAM , still it requires a lot of RAM to offload into the CPU.

Man, alright thank you. Maybe some day it'll be more optimized or I'll have a better system

For anyone else encountering this, you'll have to use this like I'm doing 

https://colab.research.google.com/github/oobabooga/AI-Notebooks/blob/main/Colab-TextGen-GPU.ipynb#scrollTo=hKuocueuXnm5
