### ISSUE TITLE
SYSPATH is not utilizing System Environment Variables - Prevents installing extensions.

### ISSUE THREAD

**Issue by BlackWyvern** [oobabooga/text-generation-webui#5263]
### Describe the bug

What's causing this?
---

```
script_dir = os.getcwd()
conda_env_path = os.path.join(script_dir, "installer_files", "env")
```
This. I think.

For some reason the git clone repository is running as standalone, so the SYSPATH and PYTHONPATH are pointing to the installation directory instead of your PATH directory. Installing modules globally using `pip install -r requrements.txt` from Bash or Cmd shell install to your PATH python properly as they should, but the project itself can't see into PATH to use them. So users like me, who know enough to run the pip install command and poke around things, but don't have any real python knowledge see that we're installing modules, but in reality, we aren't installing them where ooba thinks we SHOULD.

I tested this by editing oneclick.py to output the SYSPATH on launch.

```
import sys
print(sys.path)
```

Returns
```
['I:\\Alpaca', 'I:\\Alpaca\\installer_files\\env\\python310.zip', 'I:\\Alpaca\\installer_files\\env\\DLLs', 'I:\\Alpaca\\installer_files\\env\\lib', 'I:\\Alpaca\\installer_files\\env', 'I:\\Alpaca\\installer_files\\env\\lib\\site-packages', 'I:\\Alpaca\\installer_files\\env\\lib\\site-packages\\win32', 'I:\\Alpaca\\installer_files\\env\\lib\\site-packages\\win32\\lib', 'I:\\Alpaca\\installer_files\\env\\lib\\site-packages\\Pythonwin']
```

----

Whereas my Cmd shell:
```
C:\Windows\System32>python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.path)
['', 'I:\\Python\\Python3-10-6\\python310.zip', 'I:\\Python\\Python3-10-6\\DLLs', 'I:\\Python\\Python3-10-6\\lib', 'I:\\Python\\Python3-10-6', 'C:\\Users\\Lune\\AppData\\Roaming\\Python\\Python310\\site-packages', 'I:\\Python\\Python3-10-6\\lib\\site-packages']
```

If there's a function somewhere that attempts to install requirements for each extension on launch, it's either non-functional, or not leaving logs for me to dig around for.

Additional side-effects
----
This seems to have the additional side effect of not properly or fully installing requirements from `update_windows` as well. I had to edit `server.py` on line 318 to fully update to new requirements on my clone.

```
if (1) #not is_installed():
    install_webui()
     os.chdir(script_dir)
```

Getting around it
----

To fix/install individual submodules, the process is more complex...

It's generally suggested on stackoverflow that one shouldn't do stupid janky crap like this because it's terribly insecure, but it seems to be the only way I could find to fix it.

For individual modules, edit the script.py and add the following lines near the top. (Replace `extension name` with the correct folder.)
```
import sys
import subprocess
subprocess.call([sys.executable, "-m", "pip", "install", "-r", "extensions/extension name/requirements.txt"])
```
And then use 
```
subprocess.call([sys.executable, "-m", "pip", "install", "<module name>"])
```
for any stragglers.

Use # to comment out those lines once everything is installed so it doesn't do it every time you launch.

By calling the installer within the script, and therefore, within the control environment, extensions properly install into the project venv. This has allowed me to piecemeal together the extension requirements into the project venv and get them working.. Mostly.

References issues:
----

[4819](https://github.com/oobabooga/text-generation-webui/issues/4819), [5167](https://github.com/oobabooga/text-generation-webui/issues/5167) (User here seems to have come to the same conclusion I have.), and several others.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Clone the repository and use start_windows.bat
Attempt to install extensions.
- Silero TTS
- Whisper STT
- elevenlabs TTS
- superbooga2 (Still can't get this one working.)

### Logs

```shell
ModuleNotFoundError: No module named 'TTS'
```

### System Info

```shell
Windows 10 22H2 19405
Nvidia GTX 3080 10GB
```

**Comment by Nemesis-the-Warlock** [comment]
Here is my workaround, open elevated (admin) command prompt (cmd) and execute start_windows from there, wait for it to load and hit CTRL+C it will ask for verification. Difference is you are in the virtual environment now and you can manually update your extension like described manually (pip install -r extensions\<EXTENSION NAME>\requirements.txt --upgrade), then relaunch with start_windows, choose the extensions to be loaded and save the settings yaml (which also works now and not totally ruins the file).
