### ISSUE TITLE
Legacy API broken after commit e169993 (Dynatemp)

### ISSUE THREAD

**Issue by jmoney7823956789378** [oobabooga/text-generation-webui#5271]
### Describe the bug

Attempting generation over the legacy API is no longer producing a response at all. The prompt is sent and received but nothing is generated.
Last working commit is: https://github.com/oobabooga/text-generation-webui/commit/8ea3f316012e6befe6a852501ce158a478c8e680
(also please just add the legacy api back to the repo instead of relying on us to copy it back in from a snapshot...)

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

Send a completion request to /api/v1/streaming
Receive empty response.

### Logs

```shell
Tewi says:
[Chat history cleared]

stoop poops says:
hey

[/INST]Tewi says:
```

### System Info

```shell
Ubuntu 22.04, 4x NVIDIA A4000
```

**Comment by oobabooga** [comment]
Why are you creating an issue for code that is not even in the repository

**Comment by rebek43** [comment]
"The A1111 of text generation"
