### ISSUE TITLE
Legacy API extension fails to load.

### ISSUE THREAD

**Issue by HyPerMax5** [oobabooga/text-generation-webui#5284]
### Describe the bug

Legacy API extension fails to load because it tries to access properties in shared.py that no longer exist, one was renamed and the other was removed.
Didn't find any existing issues mentioning this or how to fix it.

Fixed by changing the first argument in line 11 in /extensions/api/script.py:
`shared.args.api_blocking_port` to `shared.args.api_port`

Once that was working, it didn't want to load because it was missing its streaming port so I re-added it to the API section in /modules/shared.py which starts at line 188:
`group.add_argument('--api-streaming-port', type=int, default=5005, help='The listening port for the streaming API.')`

Hope this helps someone.
I apologize if I didn't format this correctly, this is my first bug report.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install snapshot-2024-01-14.
Source Legacy API extension from snapshot-2023-11-12 as suggested in #4581
Start via `python server.py --extensions api`

### Screenshot

# How I fixed it on my end

## Script.py
![image](https://github.com/oobabooga/text-generation-webui/assets/58142999/98a2b020-120e-45cd-a5f8-f65091693600)

```
def setup():
    logger.warning("\nThe current API is deprecated and will be replaced with the OpenAI compatible API on November 13th.\nTo test the new API, use \"--extensions openai\" instead of \"--api\".\nFor documentation on the new API, consult:\nhttps://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API")
    blocking_api.start_server(shared.args.api_port, share=shared.args.public_api, tunnel_id=shared.args.public_api_id)
    if shared.args.public_api:
        time.sleep(5)

    streaming_api.start_server(shared.args.api_streaming_port, share=shared.args.public_api, tunnel_id=shared.args.public_api_id)
```
Updated line:
`blocking_api.start_server(shared.args.api_port, share=shared.args.public_api, tunnel_id=shared.args.public_api_id)`

## Shared.py
![image](https://github.com/oobabooga/text-generation-webui/assets/58142999/4255c9ee-b220-4600-9c69-7caf46431c5f)

```
# API
group = parser.add_argument_group('API')
group.add_argument('--api', action='store_true', help='Enable the API extension.')
group.add_argument('--api-streaming-port', type=int, default=5005, help='The listening port for the streaming API.')
group.add_argument('--public-api', action='store_true', help='Create a public URL for the API using Cloudfare.')
group.add_argument('--public-api-id', type=str, help='Tunnel ID for named Cloudflare Tunnel. Use together with public-api option.', default=None)
group.add_argument('--api-port', type=int, default=5000, help='The listening port for the API.')
group.add_argument('--api-key', type=str, default='', help='API authentication key.')
group.add_argument('--admin-key', type=str, default='', help='API authentication key for admin tasks like loading and unloading models. If not set, will be the same as --api-key.')
group.add_argument('--nowebui', action='store_true', help='Do not launch the Gradio UI. Useful for launching the API in standalone mode.')
```
Added line:
`group.add_argument('--api-streaming-port', type=int, default=5005, help='The listening port for the streaming API.')`

### Logs

```shell
18:28:51-354988 ERROR    Failed to load the extension "api".
Traceback (most recent call last):
  File "Path_to\text-generation-webui-snapshot-2024-01-14\modules\extensions.py", line 47, in load_extensions
    extension.setup()
  File "Path_to\text-generation-webui-snapshot-2024-01-14\extensions\api\script.py", line 11, in setup
    blocking_api.start_server(shared.args.api_blocking_port, share=shared.args.public_api, tunnel_id=shared.args.public_api_id)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'api_blocking_port'
```

### System Info

```shell
Windows 11 Build 22621
Nvidia GTX 1070
```

**Comment by oobabooga** [comment]
Why are you creating an issue for code that is not even in the repository
