### ISSUE TITLE
Ooba seems to crash the entire PC

### ISSUE THREAD

**Issue by Galaxia-mk** [oobabooga/text-generation-webui#5298]
### Describe the bug

I'm using the Kubuntu operating system. From what I remember when oobabooga shuts down it gave me an error message related to CUDA 11.8. Sometimes it doesn't even appear to shut down but the browser in which I spoke with the bot crashed. It crashed every time the bot tried to speak. Then not only the browser crashed but so did my other browser and the Discover store, everything crashed and when I restarted the PC it couldn't boot back up and was stuck on a screen talking about a busybox inframs error. This helped me to get the pc to run again: https://ostechnix.com/how-to-fix-busybox-initramfs-error-on-ubuntu/

After the first total crash I eventually suspected that it may have been ooba. I removed and reinstalled it and it worked for a while until l it happened again. Thus everything crashed including the operating system and fixed it again. but this time when i tried to reinstall ooba it failed and gave me a long error message which I posted in logs

I think i will need to reinstall the entire PC. 

EDIT: The web browser is crashing again. I attempted to reinstall it but it failed. Couldn't extract it so redownloaded it and then extracting worked but when I attempted to launch it it failed. I'll post the log in the log section. I don't know how long the browser stays open until it crashes (never mind I can't edit it, I'll post it here)

"Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Linux-x86_64.sh to /home/galaxia/text-generation-webui-main/installer_files/miniconda_installer.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 69.7M  100 69.7M    0     0  10.7M      0  0:00:06  0:00:06 --:--:-- 10.8M
PREFIX=/home/galaxia/text-generation-webui-main/installer_files/conda
WARNING: md5sum mismatch of tar archive
expected: 4d0f4cd44820b51c4deccc406e294b8b
     got: 8325c20cb62b97c59aad41de81034bb9  -
Unpacking payload ...
[9655] Failed to extract lib-dynload/binascii.cpython-39-x86_64-linux-gnu.so: decompression resulted in return code -3!
Miniconda version:
/home/galaxia/text-generation-webui-main/start_linux.sh: line 41: /home/galaxia/text-generation-webui-main/installer_files/conda/bin/conda: No such file or directory
/home/galaxia/text-generation-webui-main/start_linux.sh: line 46: /home/galaxia/text-generation-webui-main/installer_files/conda/bin/conda: No such file or directory
Conda environment is empty."

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Well I was running a bot i made my self with the coqui tts add on on the kubuntu 22.04 operating system. It was on Exllamav2 and the context was at 7900 I believe. Coqui could be suspect number one but at some point i also attempted to install the requirements for superboogav2 and the extension didn't work after that. I was using the model in the browser called librewolf. Though i have been using that for a very long time with this. it also coincidentally crashed again around the same time right before I'm about to prepare for sleep which is very annoying. I was running the model TheBloke_Mistral-11B-CC-Air-RP-GPTQ. i used the one click installer. 
I also added the last bit of crucial information now probably. The first sign that my pc got issues when starting up and shutting down. It's saying something about vbox when I either turn it on or shut it down. And when the pc won't start up it also is because of vbox.
I hope this is enough info

### Screenshot

![Screenshot_20240117_223424](https://github.com/oobabooga/text-generation-webui/assets/110353717/b85852c8-0629-48f1-8b89-4238249634db)

![errors](https://github.com/oobabooga/text-generation-webui/assets/110353717/fde977bb-5eb0-4304-b61b-5b11ab35fc42)

### Logs

```shell
ERROR: Exception:
Traceback (most recent call last):
  File "/home/galaxia/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/home/galaxia/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galaxia/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 452, in run
    installed = install_given_reqs(
                ^^^^^^^^^^^^^^^^^^^
  File "/home/galaxia/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/pip/_internal/req/__init__.py", line 72, in install_given_reqs
    requirement.install(
  File "/home/galaxia/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 847, in install
    install_wheel(
  File "/home/galaxia/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/pip/_internal/operations/install/wheel.py", line 731, in install_wheel
    _install_wheel(
  File "/home/galaxia/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/pip/_internal/operations/install/wheel.py", line 591, in _install_wheel
    file.save()
  File "/home/galaxia/text-generation-webui-main/installer_files/env/lib/python3.11/site-packages/pip/_internal/operations/install/wheel.py", line 390, in save
    shutil.copyfileobj(f, dest)
  File "/home/galaxia/text-generation-webui-main/installer_files/env/lib/python3.11/shutil.py", line 197, in copyfileobj
    buf = fsrc_read(length)
          ^^^^^^^^^^^^^^^^^
  File "/home/galaxia/text-generation-webui-main/installer_files/env/lib/python3.11/zipfile.py", line 955, in read
    data = self._read1(n)
           ^^^^^^^^^^^^^^
  File "/home/galaxia/text-generation-webui-main/installer_files/env/lib/python3.11/zipfile.py", line 1045, in _read1
    self._update_crc(data)
  File "/home/galaxia/text-generation-webui-main/installer_files/env/lib/python3.11/zipfile.py", line 973, in _update_crc
    raise BadZipFile("Bad CRC-32 for file %r" % self.name)
zipfile.BadZipFile: Bad CRC-32 for file 'torch/lib/libtorch_cuda.so'
```

### System Info

```shell
Operating system: Kubuntu 22.04
GPU model: RTX A5000
GPU brand: NVIDIA
```

**Comment by ResearchForumOnline** [comment]
You need to provide info on how much RAM you have specifically.

**Comment by ResearchForumOnline** [comment]
> > You need to provide info on how much RAM you have specifically.
> 
> RAM or VRAM? I got 24GB of VRAM and 15GB of RAM

I am not pro just trying to help, looks like you need to reinstall again, unless you know how to fix the conda issue, try installing using pip and apt install methods. Nice server btw.

**Comment by Galaxia-mk** [comment]
> > > You need to provide info on how much RAM you have specifically.
> > 
> > 
> > RAM or VRAM? I got 24GB of VRAM and 15GB of RAM
> 
> I am not pro just trying to help, looks like you need to reinstall again, unless you know how to fix the conda issue, try installing using pip and apt install methods. Nice server btw.

I tried to install it again but now it's giving me a new error about saying something that I have to check some stuff and that there may have been tempered with the install files. I'm just gonna give up and reinstall the pc

**Comment by ResearchForumOnline** [comment]
keep trying you will get it fixed eventually take a rest too.

**Comment by Galaxia-mk** [comment]
The issue might have been a defective ram stick, everything is working now

**Comment by Galaxia-mk** [comment]
The issue might have been a defective ram stick, everything is working now
