### ISSUE TITLE
Unable to Connect SillyTavern to Text Web UI

### ISSUE THREAD

**Issue by nate2658extra** [oobabooga/text-generation-webui#5313]
### Describe the bug

I am a complete noob with this stuff, so I'm sorry if I am missing something obvious, but I have spend hours trying to figure this out and couldn't. I am able to launch the web UI, load a model, and I have tried both enabling and disabling the openai extension, as well as the api extension. Regardless of what I do, I cannot get the CMD prompt to generate an OpenAI-compatible API URL. I feel like I am missing something, but I have no idea what it is.

Thanks in advance for any help offered!

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Possibly relevant info:

I have an AMD card, but am using a model ending in gguf, which I believe relies on my CPU.

I am using freshly updated versions of everything.

This is the model I am using:
yarn-mistral-7b-128k.Q4_K_M.gguf

I tried a few others as well, all with the same result.

### Screenshot

<img width="966" alt="apiproblem" src="https://github.com/oobabooga/text-generation-webui/assets/157077160/53b3af2e-8ef7-4fae-bf49-f7ce1437bc63">

### Logs

```shell
18:58:18-646323 INFO     Starting Text generation web UI
18:58:18-651325 INFO     Loading settings from settings.yaml
18:58:18-654325 INFO     Loading the extension "openai"
18:58:18-759856 INFO     OpenAI-compatible API URL:

                         http://127.0.0.1:5000

18:58:18-760858 INFO     Loading the extension "gallery"
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
18:59:23-610621 INFO     Loading yarn-mistral-7b-128k.Q4_K_M.gguf
18:59:23-714406 INFO     llama.cpp weights detected: models\yarn-mistral-7b-128k.Q4_K_M.gguf
llama_model_loader: loaded meta data with 24 key-value pairs and 291 tensors from models\yarn-mistral-7b-128k.Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = nousresearch_yarn-mistral-7b-128k
llama_model_loader: - kv   2:                       llama.context_length u32              = 131072
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 10000.000000
llama_model_loader: - kv  11:                    llama.rope.scaling.type str              = yarn
llama_model_loader: - kv  12:                  llama.rope.scaling.factor f32              = 16.000000
llama_model_loader: - kv  13: llama.rope.scaling.original_context_length u32              = 8192
llama_model_loader: - kv  14:               llama.rope.scaling.finetuned bool             = true
llama_model_loader: - kv  15:                          general.file_type u32              = 15
llama_model_loader: - kv  16:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  17:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  18:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  19:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  20:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  21:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - kv  22:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  23:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_K:  193 tensors
llama_model_loader: - type q6_K:   33 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 131072
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = yarn
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 0.0625
llm_load_print_meta: n_yarn_orig_ctx  = 8192
llm_load_print_meta: rope_finetuned   = yes
llm_load_print_meta: model type       = 7B
llm_load_print_meta: model ftype      = Q4_K - Medium
llm_load_print_meta: model params     = 7.24 B
llm_load_print_meta: model size       = 4.07 GiB (4.83 BPW)
llm_load_print_meta: general.name     = nousresearch_yarn-mistral-7b-128k
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size       =    0.11 MiB
llm_load_tensors: system memory used  = 4165.48 MiB
...............................................................................................
llama_new_context_with_model: n_ctx      = 131072
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: KV self size  = 16384.00 MiB, K (f16): 8192.00 MiB, V (f16): 8192.00 MiB
llama_build_graph: non-view tensors processed: 676/676
llama_new_context_with_model: compute buffer total size = 8475.19 MiB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 |
18:59:34-671355 INFO     LOADER: llama.cpp
18:59:34-680358 INFO     TRUNCATION LENGTH: 131072
18:59:34-682358 INFO     INSTRUCTION TEMPLATE: Alpaca
18:59:34-684359 INFO     Loaded the model in 11.07 seconds.
Closing server running on port: 7860
19:00:30-792414 INFO     Loading the extension "gallery"
19:00:30-795415 INFO     Loading the extension "openai"
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
OS: Windows 10
Processor: AMD Ryzen 7 3700X 8-Core Processor 3.59 GHz
GPU: AMD Radeon RX 5700 XT

16 GB RAM if that matters
```

**Comment by Memeheader** [comment]
I'm having the same issue

**Comment by HiroseKoichi** [comment]
You have llama.cpp selected in the API source. While text-generation-webui does use llama-cpp-python, you need to select the appropriate API source in SillyTavern. Since you're using text-generation-webui, you need to use the oobabooga source.

**Comment by nate2658extra** [comment]
> You have llama.cpp selected in the API source. While text-generation-webui does use llama-cpp-python, you still need to select the appropriate API source in SillyTavern. Since you're using text-generation-webui, you need to use the oobabooga source.

When you say source, do you mean the API Type? I have tried setting both llama.cpp and oobabooga as the API Type, and it does not change the result. The problem seems to be that the CMD prompt is not generating an OpenAI-compatible API URL. I have attached 2 extra screenshots to illustrate what I think it should generate vs what it is generating for me.
<img width="683" alt="CMDcurrentlyshows" src="https://github.com/oobabooga/text-generation-webui/assets/157077160/9b542da6-861b-4b88-8ba4-fb8c6ddec640">
<img width="695" alt="CMDshouldshow" src="https://github.com/oobabooga/text-generation-webui/assets/157077160/5ebd789f-e97d-496f-be7a-744eaea2311d">

**Comment by HiroseKoichi** [comment]
Did you install the dependencies in the requirements.txt file in `/text-generation-webui/extensions/openai/`? If not, you can run `pip install -r requirements.txt` while inside the directory after activating the conda environment.

**Comment by nate2658extra** [comment]
Well, I used Aitrepreneur's "one-click" install, which he said was supposed to set everything up for me.

I can give what you said a shot, but could you offer a little more detail? I'm sorry, I just have almost no background in this stuff, so I'm not sure what you mean when you say "you can run pip install -r requirements.txt while inside the directory after activating the conda environment."

**Comment by HiroseKoichi** [comment]
> I'm sorry, I just have almost no background in this stuff, so I'm not sure what you mean

Yeah, it's all good. I exclusively use Linux, so you'll have to bear with me a bit if what I suggest doesn't work right away.

I'm not sure of this is the case, but I think if you open the file `CMD_FLAGS.txt` and add --api, then running `one_click.py` will install the requirements for it automatically.


If that doesn't work, then lets do this:

When I say directory, I mean folder. Conda is basically a virtual environment where you can install packages isolated from the rest of your system.

The conda environment location should be `C:\path_to\text-generation-webui\installer_files\env`, but obviously replace `path_to` with your actual path. You should be able to right click the folder and select copy as path in order to get it.

Next, you'll need to activate the conda environment. This allows you to access the packages inside of it. You can run `conda activate C:\path_to\text-generation-webui\installer_files\env` in order to do that.

Once inside the conda environment, you need to install the OpenAI API dependencies. You can do this by running `pip install -r requirements.txt C:\path_to\text-generation-webui\extensions\openai\requirements.txt`, but again, replacing the path with one relevant to you.

**Comment by nate2658extra** [comment]
Okay, so this screenshot shows what the CMD_FLAGS.txt file currently looks like. I see it already has --api there, so I should move on to your other suggestion, right? Unless the --api should be below the --cpu or something?

<img width="351" alt="CMD_FLAGS" src="https://github.com/oobabooga/text-generation-webui/assets/157077160/dcfb9a79-e50b-4928-8a0e-22508cb18db6">

**Comment by HiroseKoichi** [comment]
Sorry, I edited the comment after posting it. Delete the # on the same line so it looks like this:

```
# Only used by the one-click installer.
# Example:
--api
```

--listen isn't needed so you can delete it.

**Comment by nate2658extra** [comment]
Okay I changed it to what's in this screenshot, then ran one_click.py but it still didn't generate anything different. I'll try your second suggestion unless something in this screenshot still looks off.
<img width="257" alt="CMD_FLAGS2" src="https://github.com/oobabooga/text-generation-webui/assets/157077160/7080f044-bc7c-4321-9456-8d00e9ac0094">

**Comment by HiroseKoichi** [comment]
--api and --cpu should be on the same line:

```
# Only used by the one-click installer.
# Example:
--api --cpu
```

But regardless, I think this method might only work on initial installation and not afterwards, so let's go with the other method.

**Comment by nate2658extra** [comment]
Sure thing!

For SillyTavern:
https://www.youtube.com/watch?v=enWO16x6tRM&t=227s

&

For Oobabooga:
https://www.youtube.com/watch?v=C-7jGYOGvy4&t=623s

**Comment by nate2658extra** [comment]
Okay so I copied that folder path, and I found the folder below, but I'm not sure how to actually run conda activate. When I click that file, nothing really seems to happen.
<img width="523" alt="condaactivate" src="https://github.com/oobabooga/text-generation-webui/assets/157077160/8214c342-1de5-48b8-9eea-307713bc0970">

**Comment by HiroseKoichi** [comment]
No, the path you want to copy is the `env` folder in `\text-generation-webui\installer_files\`

**Comment by nate2658extra** [comment]
Sorry, I should have been more clear. I did copy that folder, and then the previous screenshot is where I found the conda activate file - and that's where I am stuck.

**Comment by HiroseKoichi** [comment]
Open CMD prompt, type `conda activate`, paste in the path you copied, then hit enter to run the command.

It should look something like this: `conda activate C:\path_to\text-generation-webui\installer_files\env`

**Comment by nate2658extra** [comment]
Okay, here is what I did, but nothing happened
<img width="1429" alt="CMD conda" src="https://github.com/oobabooga/text-generation-webui/assets/157077160/777aa868-c3ef-4e31-92e7-20ba459b39e2">

**Comment by HiroseKoichi** [comment]
This is good. It did do something; the CMD prompt changed from `C:\User\USERNAME` to `C:\User\USERNAME\Documents\Git\text-generation-webui\installer_files\env` This means that your are in the conda environment.

Now run `pip install -r C:\User\USERNAME\Documents\Git\text-generation-webui\extensions\openai\requirements.txt`
Just make sure to replace USERNAME with yours.

**Comment by nate2658extra** [comment]
Okay, I got the following error:

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'C:\\User\\USERNAME\\Documents\\Git\\text-generation-webui\\extensions\\openai\\requirements.txt'

**Comment by HiroseKoichi** [comment]
You have to replace USERNAME with the name of your computer's currently logged in user. You blacked that, so I couldn't type it in.

**Comment by nate2658extra** [comment]
Whoops, should have mentioned that I actually did do that.

**Comment by HiroseKoichi** [comment]
Whoops, that's actually my bad. It's supposed to be `Users` not `User`

`pip install -r C:\Users\USERNAME\Documents\Git\text-generation-webui\extensions\openai\requirements.txt`
you can just right click the file and copy the path like last time if that doesn't work either.

**Comment by nate2658extra** [comment]
Okay, that worked! But every line says "requirement already satisfied," so I'm not sure if it actually changed anything. Should I test it now, or are there other steps I need to take first?

**Comment by HiroseKoichi** [comment]
That should be it. Once you're inside text-geneation-webui, make sure `openai` is checked, then click `save UI defaults`. If it wasn't, then you will have to click `Apply flags and restart` to update it.

![Screenshot_20240119_191202](https://github.com/oobabooga/text-generation-webui/assets/86906598/8a09d78c-91b0-4729-affa-b53a5bdf0630)

**Comment by nate2658extra** [comment]
Okay, I tried again and there was no change unfortunately. I made sure those flags were checked, and I had checked those flags before as well.

**Comment by HiroseKoichi** [comment]
That's unfortunate. The only thing I can think of is to try and install it from scratch, but add --api to the `CMD_FLAGS.txt` file before running the install script.

```
# Only used by the one-click installer.
# Example:
--api
```

I'm very sorry, but I don't know how else to help if this doesn't work.

**Comment by nate2658extra** [comment]
Okay, I'll try that. I really appreciate you taking the time to try to help regardless!

**Comment by nate2658extra** [comment]
Okay, reinstall SillyTavern, I realized the first prompt is asking what GPU I'm using, and it has an option to select my CPU.

In my initial installation, I selected my GPU, which is an AMD card. However, the model I used in oobabooga ended in gguf, which I was made to understand is reliant on my CPU instead.

Could this discrepancy have been what was causing my problem? Do both ends have to be using the same GPU/CPU?

**Comment by HiroseKoichi** [comment]
I don't recall that being a step in SillyTavern's installation. Are you using Aitrepreneur's custom scripts? You should install using the official methods for both text-generation-webui and SillyTavern.

You should install text-generation-webui with the AMD option. GGUF uses llama.cpp, and this supports both CPU and GPU inference. You can also do layer offloading, which using both the CPU and GPU at the same time. If you install with GPU support, then you automatically have CPU support.

**Comment by sandyis** [comment]
need the orange marked option below checked also 

![image](https://github.com/oobabooga/text-generation-webui/assets/24884891/9549264e-7f6a-4f6a-bbf7-2764df791839)

my logs shows below with success full API calls 

```
20:21:33-347739 INFO     Loading the extension "openai"
20:21:33-393860 INFO     OpenAI-compatible API URL:

                         http://0.0.0.0:5000

```
you can also check if socket is open using  `netstat -tlupan``and see if port 5000 is open with 0.0.0.0 address 

i used this command to start `bash start_linux.sh --listen --api`

below curl on local console should work first then try other calls 
```
curl http://127.0.0.1:5000/v1/completions \
  -H "Content-Type: application/json" \
  -d '{
    "prompt": "This is a cake recipe:\n\n1.",
    "max_tokens": 200,
    "temperature": 1,
    "top_p": 0.9,
    "seed": 10
  }'
```

**Comment by HiroseKoichi** [comment]
> need the orange marked option below checked also

Nope, there used to be two different API's before they dropped the old one in favor of the OpenAI API; both flags do the exact same thing.

**Comment by nate2658extra** [comment]
So I'm getting this when trying to install Oobabooga, I'm guessing this is an issue?

**Comment by HiroseKoichi** [comment]
> So I'm getting this when trying to install Oobabooga, I'm guessing this is an issue?

Do you mean the option to choose your GPU? If so, then it's a normal part of the installation. What AMD GPU do you have?

**Comment by nate2658extra** [comment]
Whoops, forgot to attach the scree
<img width="661" alt="oobadownld" src="https://github.com/oobabooga/text-generation-webui/assets/157077160/c85836db-7051-4b0b-bc50-92efe102da6c">
nshot!

**Comment by HiroseKoichi** [comment]
Whoops, by reinstall I meant delete the text-generation-webui folder and git clone the repo again.

**Comment by nate2658extra** [comment]
Hmm I have a feeling these issues are happening because of that 1-click install... I installed SillyTavern first, and that 1-click install is supposed to include almost everything needed, so I feel like there is a lot of overlap. I just have a feeling it's going to take forever doing things the long way lol but maybe I have to

**Comment by nate2658extra** [comment]
Okay, so I reinstalled text-generation-webui and it started working correctly! But then after I did a manual installation of SillyTavern, I tried run the start bat file for text-generation-webui again and then got what you see in this screenshot...
<img width="528" alt="notsure" src="https://github.com/oobabooga/text-generation-webui/assets/157077160/cfbd3cd9-3524-4f4e-b7ee-36e74babb441">

**Comment by HiroseKoichi** [comment]
Do you have a `settings.yaml` file in the main directory of text-generation-webui? If not, then you can copy the `settings-template.yaml` file and rename it to `settings.yaml`.

**Comment by nate2658extra** [comment]
Yes, that is there already

**Comment by HiroseKoichi** [comment]
It says `Press any key to continue`, what does this do? Does it just close the program?

**Comment by nate2658extra** [comment]
Yes, that just closes it.

**Comment by HiroseKoichi** [comment]
I have no clue. You can try opening a new issue and see if someone else can help solve the new error. I'm going to bed for now.

**Comment by nate2658extra** [comment]
Yeah I might do that. Thanks again
