### ISSUE TITLE
Maximum layers for Llama.cpp is 128, which is too low for some models

### ISSUE THREAD

**Issue by fake-name** [oobabooga/text-generation-webui#5335]
**Description**

In the model configuration dialog, the maximum number of GPU layers you can specify for a model is 128 when using Llama.cpp.

![image](https://github.com/oobabooga/text-generation-webui/assets/1401239/f363b604-0bea-4b44-b501-909bf281ab23)

Currently, there are models that are larger then this. I'm playing with a model with 138 layers.
It'd be nice to increase this to something larger. I edited `modules/ui_model_menu.py` and set the max to 256 without any issues.

**Comment by Ph0rk0z** [comment]
Fixed in dev https://github.com/oobabooga/text-generation-webui/commit/5c5ef4cef725a89cf33acfefdcfb0262ea74cef7

**Comment by fake-name** [comment]
Dammit, also this is a dupe of https://github.com/oobabooga/text-generation-webui/issues/5233 which I somehow didn't find.

Sorry!
