### ISSUE TITLE
Rephrase text.

### ISSUE THREAD

**Issue by mindcz** [oobabooga/text-generation-webui#534]
removed it please

**Comment by Titaniumtown** [comment]
what?

**Comment by oobabooga** [comment]
No

**Comment by mindcz** [comment]
I moved question to discussion so thats why I had asked to remove this topic))

**Comment by Titaniumtown** [comment]
@mindcz it wasn't a question, and you could've just closed the issue lol

**Comment by mindcz** [comment]
![image](https://user-images.githubusercontent.com/127721505/227728612-7acc6935-68c1-4f60-bb6f-032e2404920d.png)
=)

**Comment by Titaniumtown** [comment]
I was referring to the edit. but ok.
