### ISSUE TITLE
Training tab provides wrong link to tutorial.

### ISSUE THREAD

**Issue by MistakingManx** [oobabooga/text-generation-webui#5351]
### Describe the bug

When you click on the "Tutorial" link, it links to (https://github.com/oobabooga/text-generation-webui/blob/main/docs/Training-LoRAs.md), which isn't a page.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

go-to the training tab. click tutorial.

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/28667267/92e0fc29-3d0c-41bb-9f37-5dff09d4a8da)

### Logs

```shell
N/A.
```

### System Info

```shell
Windows 10
Nvidia GeForce RTX 4060 Ti
```

**Comment by sandyis** [comment]
@MistakingManx 
check your browser may be , how was TGW installed ? the code does not have that `.md` see below 

![image](https://github.com/oobabooga/text-generation-webui/assets/24884891/c65ab4ca-fca1-4b5b-8165-64c19793f89a)

**Comment by MistakingManx** [comment]
> @MistakingManx check your browser may be , how was TGW installed ? the code does not have that `.md` see below
> 
> ![image](https://private-user-images.githubusercontent.com/24884891/298790431-c65ab4ca-fca1-4b5b-8165-64c19793f89a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTMzNjIsIm5iZiI6MTcwNTk5MzA2MiwicGF0aCI6Ii8yNDg4NDg5MS8yOTg3OTA0MzEtYzY1YWI0Y2EtZmNhMS00YjViLTgxNjUtNjRjMTk3OTNmODlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA2NTc0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZWI1OTQ5OGU1N2Q1NDRmZGFkNjUzYjg1MTEyOTcwNTFjOGNmMDNiMGE0MzZlN2MyMzBlMTI2OTk0YWM3MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e8SlB3WMVT3UbJLGdvPqWaJ73CTUGCdgtOAlJ4D_WMs)

Perhaps it was a recent change or something, though I felt like I just updated this thing. I don't run the updater a lot because last time I did it, it failed at some step and I had to completely reinstall it and it was sufferage ;-;

**Comment by MistakingManx** [comment]
@sandyis on another note, how would I make an edit that immedately stops the text generation if it generates "\n"? It generates good results above this, but then it breaks a line and spends another 30 to 50 seconds saying something that makes no sense. Even if it does make sense it's usually breaking character.

I have tried many models, but I don't think I understand how to set them up right since they all take incredibly long times, or generate horrible results. The most my system can handle is 7B. Of all things, I have it running WizardLM-Math 1.1 _Because normal WizardLM doesn't even make real words.. and other alterintives takes up to 80 seconds_

**Comment by sandyis** [comment]
Hello @MistakingManx 

I normally click the stop [generate changes to stop] when LLM is rambling 
![image](https://github.com/oobabooga/text-generation-webui/assets/24884891/44e98e99-bfb2-4451-8f2b-2f82b21f87e5) 
![image](https://github.com/oobabooga/text-generation-webui/assets/24884891/edf83fec-f1dd-4a20-ae87-264dbb2e0985)


also you can click the left side hamburger button to remove last reply and edit your question 
![image](https://github.com/oobabooga/text-generation-webui/assets/24884891/9c8119a1-df1a-4b52-8ffa-b4c8b9627440)


i am able to run a LLAMA2 13B model in about 8gb VRAM using 4bit quant
i am using ubuntu thou

```
Test@Testai:~/text-generation-webui-main$ bash cmd_linux.sh
(/home/Test/text-generation-webui-main/installer_files/env) Test@Testai:~/text-generation-webui-main$ bash start_linux.sh --listen --api --model llama-2-13b-chat-hf --loader Transformers --load-in-4bit --compute_dtype float16 --quant_type nf4

```

**Comment by MistakingManx** [comment]
@sandyis that'd work under normal conversation, but mines for another type of project where it people talk to it through voice on Discord and it replies, I could filter it out after generation, but that wastes resources generating bad text.
