### ISSUE TITLE
The latest llama-cpp-python builds give gibberish respond

### ISSUE THREAD

**Issue by berkut1** [oobabooga/text-generation-webui#5354]
### Describe the bug

With all GGUF models (tested with dolphin-2.7-mixtral-8x7b.Q4_0, mixtral-8x7b-instruct-v0.1.Q4_0 and dolphin-2.2.1-mistral-7b.Q6_K), the llama-cpp-python v0.2.31 https://github.com/oobabooga/text-generation-webui/pull/5345 give gibberish respond. 

The latest stable version is v0.2.26

The temporary solution is to revert to llama-cpp-python v0.2.26.
You can copy manually the llama-cpp-python v0.2.26 from red lines https://github.com/oobabooga/text-generation-webui/pull/5307/files and replace it in your requirements.txt, after run update_windows.bat

**UPD:** another solution is uncheck `no_offload_kqv`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use any GGUF models like:
dolphin-2.7-mixtral-8x7b.Q4_0
mixtral-8x7b-instruct-v0.1.Q4_0
dolphin-2.2.1-mistral-7b.Q6_K

### Logs

```shell
n/a
```

### System Info

```shell
Windows 10
GPU: Nvidia 2080
CPU: Intel i9 9900k
Python 3.10.6

loaded GPU layers 6 or 26 (depends on a model)
```

**Comment by NXTler** [comment]
Can confirm

**Comment by berkut1** [comment]
I investigated a little bit, the problem exists if you are using CUDA. If you disable it with `n-gpu-layers=0` you will get the correct results.
@oobabooga  friendly ping, can we have a broken version of CUDA llama-cpp-python now?

**Comment by berkut1** [comment]
Oh, if you uncheck no_offload_kqv, you also fix this issue. So... maybe problem exists in lama-cpp-python itself.
It is sad, no_offload_kqv  is very useful for large models, when you have low VRAM....

**Comment by berkut1** [comment]
As I can see https://github.com/abetlen/llama-cpp-python/issues/1089 they fixed it in v0.2.32

**Comment by phr00t** [comment]
I'm having the same problem. Hope we can merge in a fix soon!

**Comment by maxwelljens** [comment]
Can confirm I have the same issue.
