### ISSUE TITLE
Not working with kaggle, confusing error.

### ISSUE THREAD

**Issue by krigeta** [oobabooga/text-generation-webui#5359]
### Describe the bug

how are you able to run the notebook on kaggle? In my case, everything is running fine and within seconds I got and I am not even clicking anything:

```
This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
^C
17:03:03-622468 INFO     Received Ctrl+C. Shutting down Text generation web UI  
                         gracefully.                                            
Killing tunnel 127.0.0.1:7860 <> https://01f5117d933793e02f.gradio.live/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run the webUI on Kaggle and after the link generation it will stop on its own and giving ctrl^c termination.

### Logs

```shell
This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
^C
17:03:03-622468 INFO     Received Ctrl+C. Shutting down Text generation web UI  
                         gracefully.                                            
Killing tunnel 127.0.0.1:7860 <> https://01f5117d933793e02f.gradio.live
```

### System Info

```shell
Kaggle
```

**Comment by akhil3417** [comment]
facing the same issue.

**Comment by krigeta** [comment]
> facing the same issue. @krigeta did you found any workaround?

no, I don't know what is wrong because it works perfectly on Google Colab

**Comment by akhil3417** [comment]
> no, I don't know what is wrong because it works perfectly on Google Colab

check the server.py commit history . their are two commits regarding ctrl+c their , maybe try checkout before them and see

**Comment by krigeta** [comment]
> > no, I don't know what is wrong because it works perfectly on Google Colab
> 
> check the server.py commit history . their are two commits regarding ctrl+c their , maybe try checkout before them and see

okay let me check it real quick

**Comment by akhil3417** [comment]
`Traceback (most recent call last):
  File "/kaggle/working/text-generation-webui/server.py", line 239, in <module>
    time.sleep(0.5)`

and in server.py

```create_interface()
        while True:
            time.sleep(0.5)
            if shared.need_restart:
                shared.need_restart = False
                time.sleep(0.5)
                shared.gradio['interface'].close()
                time.sleep(0.5)
                create_interface()```


maybe issue is in this part

**Comment by krigeta** [comment]
> commit history

how can we check "server.py commit history" history?

**Comment by akhil3417** [comment]
> how can we check "server.py commit history" history?

on top of that file's page look for circular arrow in right upper side , that's it

**Comment by krigeta** [comment]
> > how can we check "server.py commit history" history?
> 
> on top of that file's page look for circular arrow in right upper side , that's it

possible screenshot?

**Comment by krigeta** [comment]
> > possible screenshot?
> 
> [here](https://github.com/oobabooga/text-generation-webui/commits/main/server.py)

oh lol I was checking on Kaggle

**Comment by krigeta** [comment]
one more thing the  whole notebook is closing on its own

**Comment by akhil3417** [comment]
> one more thing the whole notebook is closing on its own

yeah very frustating

**Comment by akhil3417** [comment]
> one more thing the whole notebook is closing on its own

previously were you able to run without this bug?

**Comment by krigeta** [comment]
> > one more thing the whole notebook is closing on its own
> 
> previously were you able to run without this bug?

I guess I just noticed it

**Comment by Zxilly** [comment]
Kaggle forbids gradio share. This project relies on it.
When kaggle noticed a gradle share instance was created, it terminates instance. Try bypass this may lead to a ban to your kaggle account.
