### ISSUE TITLE
Can't load llama 4bit 30b in WSL

### ISSUE THREAD

**Issue by laughinggaschambers** [oobabooga/text-generation-webui#536]
### Describe the bug

I have 13b and 30b working on windows 10 but the speed is a bit slow so I installed wsl ran it there.
13b works and is faster on wsl, however when trying to load 30b it print Killed. 
I have a gtx3090 24gb vram so it should load, unles wsl is limiting it or not using it at all somehow.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

Follow the 4bit wls installation 
tried
python server.py --gptq-bits 4
python server.py --gptq-bits 4 --auto-devices
python server.py --gptq-bits 4 --gpu-memory 24000MiB

### Screenshot

![image](https://user-images.githubusercontent.com/114764161/227524017-215d0322-88b4-4ff7-8a36-17f32d2e03d8.png)

### Logs

```shell
Loading llama-30b...
Loading model ...
Killed
```

### System Info

```shell
Windows 10 WSL Ubuntu 22.04.2 LTS
GTX 3090 24gb vram
32.0 GB
i5-12600K   3.70 GHz
```

**Comment by Ph0rk0z** [comment]
Probably not enough CPU ram.

**Comment by sowa705** [comment]
why is 32gb of ram not enough for a 16gb model?

**Comment by jllllll** [comment]
> why is 32gb of ram not enough for a 16gb model?

WSL has a memory limit which can be configured: https://learn.microsoft.com/en-us/windows/wsl/wsl-config
As shown in that link, the default memory limit depends on the wsl build that you are running. It probably is just barely shy of what 30b requires.

**Comment by laughinggaschambers** [comment]
Yeah it was that the default memory not being enough, and now it works

**Comment by laughinggaschambers** [comment]
Also don't set it way to high or it wont load at all.
