### ISSUE TITLE
Error: None

### ISSUE THREAD

**Issue by anisaiscool** [oobabooga/text-generation-webui#5384]
I keep getting "Error None", and the model never successfully generates anything. It is stuck at "AI is typing". Tried this with a couple models. My first time using Oobabooga. The model did successfully download.
Model in question: Wizard-Vicuna-7B-Uncensored-GGUF
![Screenshot 2024-01-27 171136](https://github.com/oobabooga/text-generation-webui/assets/134447999/bb121e60-36c5-421c-b082-ff9f4957ea4f)

**Comment by araleza** [comment]
Best to have a look at the command line (/ terminal) window, there's often a more detailed error message there.
