### ISSUE TITLE
WebUI not Loading

### ISSUE THREAD

**Issue by SpuffyniteHD** [oobabooga/text-generation-webui#5390]
### Describe the bug

WebUI will not Load/ Infinite Load, not opening. 
I don't get any Error Logs.

Windows Version: Windows 11 Pro Insider 26040.100

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Loading start_windows.bat
Opening Website on Local Url
WebUi Infinite/ Not Loading

### Screenshot

![Screenshot 2024-01-28 164310](https://github.com/oobabooga/text-generation-webui/assets/47983508/9e74c7ae-7822-40ec-9762-338a312c4c5f)

### Logs

```shell
16:40:04-894986 INFO     Starting Text generation web UI
16:40:04-898504 WARNING  trust_remote_code is enabled. This is dangerous.
16:40:04-899502 INFO     Loading settings from settings.yaml
16:40:04-902706 INFO     Loading the extension "gallery"
16:40:04-905213 INFO     Loading the extension "silero_tts"

Using Silero TTS cached checkpoint found at C:\Users\Lucy/.cache\torch\hub
16:40:05-774175 INFO     Loading the extension "send_pictures"
Running on local URL:  http://127.0.0.1:7860
```

### System Info

```shell
CPU: Ryzen 5 5600x
GPU: RTX 3060 12GB
Ram: 32GB DDR4 4000MhZ
Windows Version: Windows 11 Pro Insider 26040.100
```

**Comment by frosta95** [comment]
I have the same error!

**Comment by SpuffyniteHD** [comment]
Well, I researched a bit and it turns out that the latest Windows 11 Insider is the culprit. As I switched back to an older Windows Insider Build, aka 26020, The WebUi is loading normally
