### ISSUE TITLE
Unable to install deepspeed

### ISSUE THREAD

**Issue by sashasubbbb** [oobabooga/text-generation-webui#54]
Hi, i don't think this is repo specific issue, but i am unable to install on windows 11 RTX 20s AMD Ryzen due to this error: 

> Collecting deepspeed==0.8.0
  Using cached deepspeed-0.8.0.tar.gz (749 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Temp\pip-install-vr9o447d\deepspeed_d266f5d51e7e4709841a20afde65dd1e\setup.py", line 156, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Temp\pip-install-vr9o447d\deepspeed_d266f5d51e7e4709841a20afde65dd1e\setup.py", line 48, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      DS_BUILD_OPS=1
      [93m [WARNING] [0m async_io requires the dev libaio .so object and headers but these were not found.
      [93m [WARNING] [0m If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
      [93m [WARNING] [0m One can disable async_io with DS_BUILD_AIO=0
      [31m [ERROR] [0m Unable to pre-compile async_io
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by oobabooga** [comment]
Thanks, I have removed deepspeed from `requirements.txt` for now.

**Comment by sashasubbbb** [comment]
Thank you, that issue is solved, unfortunately i have another issue with 8-bit mode on windows: i applied this fix: 

> https://github.com/oobabooga/text-generation-webui/issues/20#issuecomment-1411650652

![Screenshot at 04-44-54](https://user-images.githubusercontent.com/60400449/216739947-1a6a61ea-79e3-4e6f-94df-5e962bdb65b1.png)

Non-8-bit mode works fine
