### ISSUE TITLE
4-bit Llama only outputs random text.

### ISSUE THREAD

**Issue by BugMonkey42335** [oobabooga/text-generation-webui#544]
### Describe the bug

I followed this guide to get Llama 7b 4-bit from decapoda up and running. It works but it's only putting out random text.

https://www.youtube.com/watch?v=ixLLQ3pzNiQ

You: Test.

Bot: ottokojirache destiracles tu

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://www.youtube.com/watch?v=ixLLQ3pzNiQ

### Logs

```shell
N/A
```

### System Info

```shell
windows 10
1050ti
```

**Comment by oobabooga** [comment]
Decapoda is deprecated, try with the latest weights

**Comment by yx890710** [comment]
@oobabooga Hello, I also have this question! I tried to download the latest weight(3-26-23,safetensors version), but the output is still wrong.
![image](https://user-images.githubusercontent.com/58323305/228732276-572a1676-debf-4067-a7ea-f0875a751307.png)
