### ISSUE TITLE
Unable to load model with exllamav2.

### ISSUE THREAD

**Issue by turugi-ni** [oobabooga/text-generation-webui#5440]
### Describe the bug

I can load the model with normal llamaccp, but I can't load the model with exllamav2.The model I'm trying to load is the 13b-q5_k_m.gguf series.My PC specs are 13th generation Intel Core i5-13400F. GPU is RTX4060 TIVRAM 16GB Physical memory is 16GB x 2 32GB, this is because we used Stable Diffusion on a low budget and because we did not originally plan to use text-generation-webui. With this spec, should I give up on using exllamav2?I think the required memory is met.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Select the 13b-q5_k_m.gguf series model in the model, select exllamav2 in the Model loader, and load it.

### Logs

```shell
ValueError: No model is loaded! Select one in the Model tab.
```

### System Info

```shell
13th generation Intel Core i5-13400F. GPU is NVIDIA RTX4060TI VRAM16GB. Physical memory is 16GB x 2 32GB
```

**Comment by bartowski1182** [comment]
That's not how it's meant to work. GGUF models only work with llama.cpp (and c-transformers), exllamav2 and GPTQ models work with exllamav2. You can't use exllamav2 to load a gguf file.

**Comment by turugi-ni** [comment]
I see, so exllamav2 is a loader for GPTQ models and does not support gguf models. I understand, thank you for your answer.
