### ISSUE TITLE
"/v1/models" API Endpoint no longer returning all models after update

### ISSUE THREAD

**Issue by Straafe** [oobabooga/text-generation-webui#5472]
### Describe the bug

After updating to latest, this endpoint now only returns the default values instead of all my models. It returns this now:

`{"object":"list","data":[{"id":"gpt-3.5-turbo","object":"model","created":0,"owned_by":"user"},{"id":"text-embedding-ada-002","object":"model","created":0,"owned_by":"user"}]}`

It should return a long list of all models that exist, not just the default values.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use "/v1/models" on 0f134bf with more models in the models folder. It should only return the default model names and not yours.

### Screenshot

API returning default results:
![image](https://github.com/oobabooga/text-generation-webui/assets/7477619/7bd1cac4-3b6f-41b5-be53-c8e59a955052)

![image](https://github.com/oobabooga/text-generation-webui/assets/7477619/b5e5c730-ebe4-454d-8818-09c03e64cefe)

You can see on the server running this that the models folder is populated with models, which should be returned:
![image](https://github.com/oobabooga/text-generation-webui/assets/7477619/f089bb17-1126-4921-a215-3f7b77a36996)

### Logs

```shell
No errors, just not returning the proper information.
```

### System Info

```shell
Windows Server machine with a RTX 3090.
```

**Comment by Straafe** [comment]
http://127.0.0.1:5000/v1/internal/model/list returns a list of model names, which I can use for this, thanks to mefi_ on DIscord

**Comment by sysnet4admin** [comment]
For other person who encounter this issue. 

Actual output. 
```
root@cp-k8s:~# curl -s http://localhost:5001/v1/models | jq
{
  "object": "list",
  "data": [
    {
      "id": "gpt-3.5-turbo",
      "object": "model",
      "created": 0,
      "owned_by": "user"
    },
    {
      "id": "text-embedding-ada-002",
      "object": "model",
      "created": 0,
      "owned_by": "user"
    }
  ]
}
```

```
root@cp-k8s:~# curl -s http://127.0.0.1:5001/v1/internal/model/list |jq 
{
  "model_names": [
    "ehartford_dolphin-2.1-mistral-7b",
    "google_gemma-2b",
    "TinyLlama_TinyLlama-1.1B-Chat-v1.0"
  ]
}
```
