### ISSUE TITLE
CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install .

### ISSUE THREAD

**Issue by kdubey22** [oobabooga/text-generation-webui#5475]
### Describe the bug

I followed the steps to get the latest llama_cpp_python to run Mistral on text-generation-webui.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

First go to your textwebui directory
cd yourdirectoryhere

#Activate the conda env
conda activate textgen

#Go to the textgen/lib/python3.11/site-packages and clone llama-cpp-python
git clone https://github.com/abetlen/llama-cpp-python
cd llama-cpp-python

#Delete the normal usual llama.cpp and get the new one
cd vendor
rm -R llama.cpp/
git clone --branch=mixtral https://github.com/ggerganov/llama.cpp.git

#Uninstall the old llama.cpp
pip list # look for llama.cpp or something similar
pip uninstall lama.cpp or somethingsimilar

#Install the new one and compile lama.cpp
cd ..
CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install -e .

### Logs

```shell
`FileNotFoundError: [Errno 2] No such file or directory: '/home/kdubey/.local/bin/ninja'`
```

### System Info

```shell
Python 3.11.7
CUDA 12.3
```

**Comment by Ph0rk0z** [comment]
Missing ninja.

**Comment by Ph0rk0z** [comment]
you need to make sure you have cuda toolkit and ninja. If pip isn't working, try installing ninja with conda. And yea, inside the venv.

**Comment by kdubey22** [comment]
I tried it too. No luck !!

`conda activate textgen`
`conda install ninja`  -> installed successfully, ran the CMAKE command again and got the same error that ninja not found.

**Comment by Ph0rk0z** [comment]
what happens when you type nvcc or ninja in the env?

**Comment by kdubey22** [comment]
Thank You @Ph0rk0z 
The issue is resolved. The problem was the path in the bash file. Below are the steps I took to resolve the issue:
 
```
$ conda activate textgen
$ ninja --version (Output -> -bash: ./.local/bin/ninja: /opt/conda/envs/textgen/bin/python3.10: bad interpreter: No such file or directory)
$ pip install ninja (Output -> Requirement already satisfied: ninja in ./.conda/envs/textgen/lib/python3.11/site-packages (1.11.1.1))
```
 
Given that Ninja is already installed in the conda environment (./.conda/envs/textgen/lib/python3.11) as indicated by the successful pip install message.

```
$conda activate textgen
$nano ~/.bashrc
Fix the path in the bash file -> export PATH="./.conda/envs/textgen/bin:$PATH"
$pip uninstall ninja
$pip install ninja
```
If the problem persists then `rm ./.local/bin/ninja` and install ninja again.
