### ISSUE TITLE
ExLamav2 Loaders doesn't work on newest snapshot 02.11 or on dev banch (for me)

### ISSUE THREAD

**Issue by M4st3rfun** [oobabooga/text-generation-webui#5497]
### Describe the bug

today i updated it to the [snapshot-2024-02-11] with clicking the update bottom, then i realized that ExLlamav2_HF doesn't work any more getting the error that is mentioned below, after a user called @aikitoria told me about the dev banch i tested the Dev branch and doesn't work either, did a clean install, doesn't work either, it says this here ->

( it worked fine 2 days ago when i was using it with SillyTavern)

(normal ExLlamav2 has the same error message)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I try to load a LLM like TheBloke_CapybaraHermes-2.5-Mistral-7B-GPTQ or TheBloke_Mistral-7B-Instruct-v0.1-GPTQ

clicked on load with ExLlamav2_HF or ExLlamav2 Enabled then the error showed up after the update

### Screenshot

![ExLlamaV2](https://github.com/oobabooga/text-generation-webui/assets/146565267/91a0f020-ffa4-495e-98d6-c0465d4a3c5f)

### Logs

```shell
Traceback (most recent call last):

File "C:\AI\oo\text-generation-webui\modules\ui_model_menu.py", line 220, in load_model_wrapper

shared.model, shared.tokenizer = load_model(selected_model, loader)

                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\oo\text-generation-webui\modules\models.py", line 87, in load_model

output = load_func_map[loader](https://github.com/oobabooga/text-generation-webui/commit/model_name)

     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\oo\text-generation-webui\modules\models.py", line 387, in ExLlamav2_HF_loader

from modules.exllamav2_hf import Exllamav2HF
File "C:\AI\oo\text-generation-webui\modules\exllamav2_hf.py", line 7, in

from exllamav2 import (
File "C:\AI\oo\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2_init_.py", line 3, in

from exllamav2.model import ExLlamaV2
File "C:\AI\oo\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\model.py", line 16, in

from exllamav2.config import ExLlamaV2Config
File "C:\AI\oo\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\config.py", line 2, in

from exllamav2.fasttensors import STFile
File "C:\AI\oo\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\fasttensors.py", line 5, in

from exllamav2.ext import exllamav2_ext as ext_c
File "C:\AI\oo\text-generation-webui\installer_files\env\Lib\site-packages\exllamav2\ext.py", line 142, in

exllamav2_ext = load \

            ^^^^^^
File "C:\AI\oo\text-generation-webui\installer_files\env\Lib\site-packages\torch\utils\cpp_extension.py", line 1308, in load

return _jit_compile(

   ^^^^^^^^^^^^^
File "C:\AI\oo\text-generation-webui\installer_files\env\Lib\site-packages\torch\utils\cpp_extension.py", line 1736, in _jit_compile

return _import_module_from_library(name, build_directory, is_python_module)

   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\AI\oo\text-generation-webui\installer_files\env\Lib\site-packages\torch\utils\cpp_extension.py", line 2136, in _import_module_from_library

module = importlib.util.module_from_spec(spec)

     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing exllamav2_ext: The specified module was not found.
```

### System Info

```shell
PC specs if necessary (RTX 2080 Gaming OC from gigabyte) 32 GB Ram, I5 8600K
```

**Comment by Jackmjedi** [comment]
New version seems to have broken pip requirements for ExLlamav2, and installs the non CUDA version instead, run the following with your venv active:

pip install https://github.com/oobabooga/exllamav2/releases/download/v0.0.13.1/exllamav2-0.0.13.1+cu121-cp311-cp311-win_amd64.whl

**Comment by altoiddealer** [comment]
> New version seems to have broken pip requirements for ExLlamav2, and installs the non CUDA version instead, run the following with your venv active:
> 
> pip install https://github.com/oobabooga/exllamav2/releases/download/v0.0.13.1/exllamav2-0.0.13.1+cu121-cp311-cp311-win_amd64.whl

You are a GODSEND

**Comment by M4st3rfun** [comment]
> New version seems to have broken pip requirements for ExLlamav2, and installs the non CUDA version instead, run the following with your venv active:
> 
> pip install https://github.com/oobabooga/exllamav2/releases/download/v0.0.13.1/exllamav2-0.0.13.1+cu121-cp311-cp311-win_amd64.whl

Sorry to ask you that, i am not really familiar with that yet, how do i do activate venv?

i opened the cmd in the folder and did it from there "installed" it with the command but it still doesn't work, maybe i just wait until it get fixed if he sees it! :) thank you anyway for you help!

**Comment by Th3Nomad** [comment]
> > New version seems to have broken pip requirements for ExLlamav2, and installs the non CUDA version instead, run the following with your venv active:
> > pip install https://github.com/oobabooga/exllamav2/releases/download/v0.0.13.1/exllamav2-0.0.13.1+cu121-cp311-cp311-win_amd64.whl
> 
> Sorry to ask you that, i am not really familiar with that yet, how do i do activate venv?
> 
> i opened the cmd_windows.bat in the folder and did it from there "installed" it with the command but it still doesn't work, maybe i just wait until it get fixed if he sees it! :) thank you anyway for you help!

I used this [https://www.reddit.com/r/oobaboogazz/comments/15ke6ww/can_anyone_tell_me_how_to_access_the_virtual/](url) to active then copied the pip command. Seems to have worked so far.

**Comment by Dino-Zavrus** [comment]
today i run update_windows.bat, and yes, not GPTQ models do not load, resulting in a lengthy wall-of-text error
i tried the method above - cmd_windows.bat to get conda env activated, and is was activated, indeed,
but after issuing command pip install https://github.com/oobabooga/exllamav2/releases/download/v0.0.13.1/exllamav2-0.0.13.1+cu121-cp311-cp311-win_amd64.whl
i am getting the red text:
**ERROR: exllamav2-0.0.13.1+cu121-cp311-cp311-win_amd64.whl is not a supported wheel on this platform.**

what are my options? to reinstall from scratch? or install files are already corrupted too?
please advise

**Comment by oobabooga** [comment]
What requirements.txt, OS, and processor architecture (x86_64 or not) cause this error? This is what is in the requirements.txt:

```
https://github.com/oobabooga/exllamav2/releases/download/v0.0.13.1/exllamav2-0.0.13.1+cu121-cp311-cp311-win_amd64.whl; platform_system == "Windows" and platform_machine == "x86_64" and python_version == "3.11"
https://github.com/oobabooga/exllamav2/releases/download/v0.0.13.1/exllamav2-0.0.13.1+cu121-cp310-cp310-win_amd64.whl; platform_system == "Windows" and platform_machine == "x86_64" and python_version == "3.10"
https://github.com/oobabooga/exllamav2/releases/download/v0.0.13.1/exllamav2-0.0.13.1+cu121-cp311-cp311-linux_x86_64.whl; platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.11"
https://github.com/oobabooga/exllamav2/releases/download/v0.0.13.1/exllamav2-0.0.13.1+cu121-cp310-cp310-linux_x86_64.whl; platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.10"
https://github.com/oobabooga/exllamav2/releases/download/v0.0.13.1/exllamav2-0.0.13.1-py3-none-any.whl; platform_system != "Darwin" and platform_machine != "x86_64"
```

The only wheel without extensions is

```
https://github.com/oobabooga/exllamav2/releases/download/v0.0.13.1/exllamav2-0.0.13.1-py3-none-any.whl; platform_system != "Darwin" and platform_machine != "x86_64"
```

which only gets installed if `platform_machine != "x86_64"`.

**Comment by oobabooga** [comment]
This should have fixed it. https://github.com/oobabooga/text-generation-webui/commit/04d8bdf929603439032e6d4b08d7e7b9c358c003

Apparently on Windows, `x86_64` is called `AMD64` and that was causing the problem.

**Comment by M4st3rfun** [comment]
Thank you for the fix and everyone here, it has been fixed on my side too!!
