### ISSUE TITLE
Error when generating using 8-bit mode: Illegal memory access

### ISSUE THREAD

**Issue by sashasubbbb** [oobabooga/text-generation-webui#55]
python server.py --cai-chat --no-stream --load-in-8bit
RTX 20xx, Windows 11 (8bit windows patch applied)

![Screenshot at 06-02-38](https://user-images.githubusercontent.com/60400449/216743712-85b05fcd-b98e-489f-bc00-de2382b1e90f.png)

When using flag CUDA_LAUNCH_BLOCKING=1:

> Error an illegal memory access was encountered at line 479 in file D:\ai\tool\bitsandbytes\csrc\ops.cu

Pretty sure it's a problem in how libbitsandbytes dlls in 

> https://github.com/oobabooga/text-generation-webui/issues/20#issuecomment-1411650652

are compiled?

**Comment by oobabooga** [comment]
Let's try to concentrate the discussion about 8-bit on Windows here: #20. I have reopened that issue. This should help find a proper solution to all these issues faster.
