### ISSUE TITLE
Alpaca Lora MPS issue

### ISSUE THREAD

**Issue by StableInquest** [oobabooga/text-generation-webui#552]
### Describe the bug

miniconda3/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Only able to load alpaca lora or run in CPU only mode on M1 which is incredibly slow. Just using LLama7b standalone with no lora works fine and without CPU mode.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run alpaca lora 7b with llama 7b without CPU only mode enabled

### Logs

```shell
miniconda3/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

### System Info

```shell
M1 MACOS
```

**Comment by oobabooga** [comment]
Can you check if this fixed it? https://github.com/oobabooga/text-generation-webui/commit/25be9698c74d7af950cbcbf8ec4c0cd9bebc6d3c

**Comment by StableInquest** [comment]
Seems like that worked! Thanks
