### ISSUE TITLE
Ollama Integration

### ISSUE THREAD

**Issue by CHesketh76** [oobabooga/text-generation-webui#5532]
Is there an optional feature to include Ollama. It looks like it could be simple to setup since other packages like litellm could point to the ollama instance for chats.

**Comment by Ph0rk0z** [comment]
ollama is just llama.cpp

**Comment by oobabooga** [comment]
> ollama is just llama.cpp

This. It bothers me that they don't even acklowledge llama.cpp in the README.

**Comment by CHesketh76** [comment]
@oobabooga Can I connect text gen webUI to a running Ollama instance? First example, say I have some non-Text webui  scripts pinging my ollama instance and I want text-webui to also ping the same ollama instance.

**Comment by jikkuatwork** [comment]
This would be a killer value! The whole project will be super easy to setup! My Oobabooga breaks so often that its so hard to come back to it
