### ISSUE TITLE
ERROR: llama_cpp_python-xxx.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by brightzheng100** [oobabooga/text-generation-webui#5540]
### Describe the bug

Trying to deploy it on a normal Linux VM with 16 vCPU and 64G RAM but failed.

I followed the manual steps but encountered error when running:
```sh
(textgen) $ pip install -r requirements_cpu_only_noavx2.txt
Ignoring bitsandbytes: markers 'platform_system == "Windows"' don't match your environment
ERROR: llama_cpp_python-0.2.43+cpuavx-cp311-cp311-manylinux_2_31_x86_64.whl is not a supported wheel on this platform.
```

I was thinking this might be caused by unstable `main` version so I tried checking out the `v1.7`, but similar issue happened:

```sh
(textgen) $ git checkout v1.7
(textgen) $ pip install -r requirements_cpu_only_noavx2.txt
Collecting git+https://github.com/oobabooga/torch-grammar.git (from -r requirements_cpu_only_noavx2.txt (line 28))
  Cloning https://github.com/oobabooga/torch-grammar.git to /tmp/pip-req-build-vw7bjpg_
  Running command git clone --filter=blob:none --quiet https://github.com/oobabooga/torch-grammar.git /tmp/pip-req-build-vw7bjpg_
  Resolved https://github.com/oobabooga/torch-grammar.git to commit 82850b5383a629f3b0fa1fba7d8f2aba3185ddb2
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Ignoring bitsandbytes: markers 'platform_system == "Windows"' don't match your environment
ERROR: llama_cpp_python-0.2.11+cpuavx-cp310-cp310-manylinux_2_31_x86_64.whl is not a supported wheel on this platform.
```

I'm actually not very sure whether I have `avx2` so I tried both `requirements_cpu_only.txt` and `requirements_cpu_only_noavx2.txt`, no luck.

Advice please?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```sh
mkdir -p ~/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-`uname -m`.sh -O ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm -rf ~/miniconda3/miniconda.sh

~/miniconda3/bin/conda init bash
source ~/.bashrc

conda create -n text-generation python=3.11
conda activate textgen

pip3 install torch==2.1.* torchvision==0.16.* torchaudio==2.1.* --index-url https://download.pytorch.org/whl/cpu

git clone https://github.com/oobabooga/text-generation-webui \
    && cd text-generation-webui/
git checkout v1.7
pip install -r requirements_cpu_only_noavx2.txt
```

### Screenshot

<img width="1311" alt="image" src="https://github.com/oobabooga/text-generation-webui/assets/1422425/10cba20e-2303-47d7-9298-06332b87d40e">

### Logs

```shell
N/A
```

### System Info

```shell
$ uname -a
Linux xxx 4.18.0-477.27.1.el8_8.x86_64 #1 SMP Thu Aug 31 10:29:22 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release
Red Hat Enterprise Linux release 8.8 (Ootpa)
```

**Comment by brightzheng100** [comment]
might be similar to #5413 but my GLIBC version might be lower:

```sh
$ ldd --version
ldd (GNU libc) 2.28
```

**Comment by Alkohole** [comment]
Maybe I'm off topic, but why do you create a `text-generation` shell with the given parameter `python=3.11`, but run a `textgen` shell?
```
conda create -n text-generation python=3.11
conda activate textgen
```
Could it be that you have python 3.12 or older, like 3.8, automatically set in `textgen`?

**Comment by brightzheng100** [comment]
> why do you create a text-generation shell with the given parameter python=3.11, but run a textgen shell?

Good catch, actually it's just a typo when I posted here -- I was using `text-generation` always but trying to simplify a bit in the post.

And thanks for your 

This issue has been resolved by using only `conda` managed Python.
For that, I simply removed all `brew` installed Python and there is no more conflict.

Closing it.
