### ISSUE TITLE
Raise ValueError

### ISSUE THREAD

**Issue by chongy076** [oobabooga/text-generation-webui#5552]
### Describe the bug

when user prompt send Hello,

Traceback (most recent call last):
  File "F:\text-generation-webui\text-generation-webui-main\modules\callbacks.py", line 64, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\text-generation-webui\text-generation-webui-main\modules\llamacpp_model.py", line 167, in generate
    callback(text)
  File "F:\text-generation-webui\text-generation-webui-main\modules\callbacks.py", line 53, in _callback
    raise ValueError
ValueError

[model and param]
llm_load_print_meta: model size       = 4.65 GiB (5.52 BPW)
llm_load_print_meta: general.name   = mistralai_mistral-7b-instruct-v0.1
llm_load_print_meta: BOS token = 1 '<s>'
llm_load_print_meta: EOS token = 2 '</s>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: LF token  = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.11 MB
llm_load_tensors: mem required  = 4765.60 MB
..................................................................................................
llama_new_context_with_model: n_ctx      = 32768
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: kv self size  = 4096.00 MB
llama_build_graph: non-view tensors processed: 740/740
llama_new_context_with_model: compute buffer total size = 2137.57 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 |

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

happen when enabled api via openai extension,
calling /v1/chat/completions

**[prompt parameter]**
	   {    "messages": [
		  {
			"role": "user",
			"content": "hello"
		  }
		],
       "mode": "chat",      "instruction_template": "Mistral",    "chat_style":"cai-chat",    "character_menu": "Mary",    "context": "act as a robot , your name is Mary and automated smart and cute robot with funny behavior. ",    "stream": true,    "max_tokens": 800,    "n_ctx": 32768,    "max_seq_len": 2048,    "compress_pos_emb": 1,    "alpha_value": 1,    "rope_freq_base": 0,    "numa": false,    "logits_all": false
	}

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/50088438/186bf7cf-e0b7-4bc9-8a8d-4e687bcd74cb)

### Logs

```shell
Output generated in 4.90 seconds (2.65 tokens/s, 13 tokens, context 67, seed 771355938)
answer: ai ya ya .
Me: who are you
stop val:  I
Traceback (most recent call last):
  File "F:\text-generation-webui\text-generation-webui-main\modules\callbacks.py", line 64, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\text-generation-webui\text-generation-webui-main\modules\llamacpp_model.py", line 167, in generate
    callback(text)
  File "F:\text-generation-webui\text-generation-webui-main\modules\callbacks.py", line 53, in _callback
    raise ValueError
ValueError
```

### System Info

```shell
llm_load_print_meta: model size       = 4.65 GiB (5.52 BPW)
llm_load_print_meta: general.name   = mistralai_mistral-7b-instruct-v0.1
llm_load_print_meta: BOS token = 1 '<s>'
llm_load_print_meta: EOS token = 2 '</s>'
llm_load_print_meta: UNK token = 0 '<unk>'
llm_load_print_meta: LF token  = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.11 MB
llm_load_tensors: mem required  = 4765.60 MB
..................................................................................................
llama_new_context_with_model: n_ctx      = 32768
llama_new_context_with_model: freq_base  = 10000.0
llama_new_context_with_model: freq_scale = 1
llama_new_context_with_model: kv self size  = 4096.00 MB
llama_build_graph: non-view tensors processed: 740/740
llama_new_context_with_model: compute buffer total size = 2137.57 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 |
```

**Comment by mamei16** [comment]
Please ensure you have pulled the latest commits and try again. This error should no longer occur after this commit: https://github.com/oobabooga/text-generation-webui/pull/5174/commits/6306927cb252040fb4e615233501bd5430bbbc81

**Comment by chongy076** [comment]
> Please ensure you have pulled the latest commits and try again. This error should no longer occur after this commit: [6306927](https://github.com/oobabooga/text-generation-webui/commit/6306927cb252040fb4e615233501bd5430bbbc81)

Thanks
