### ISSUE TITLE
How can i use extensions?

### ISSUE THREAD

**Issue by agcuevas** [oobabooga/text-generation-webui#558]
### Describe the bug

Maybe this is a noob question, but how can i use extensions in the interface?, I tick ie sillero or whisper and reload, but nothing changes in the interface in order to use it. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

n/a

### Screenshot

n/a

### Logs

```shell
n/a
```

### System Info

```shell
rtx 3080
```

**Comment by Brawlence** [comment]
Having the same issue, the UI won't redraw any new extensions ticked.

Your best bet would be to modify `start-webui.bat` (open it with any text editor):

on the line that says `call python server.py …` insert `--extension {names of your wanted extensions}` to the left. For example, here's mine:

`call python server.py --auto-devices --gpu-memory 10 --cai-chat --extension silero_tts`

**Comment by Highlyhotgames** [comment]
Enter on each specific extension folder (inside extensions folder) u want to use and run "pip install -r requirements.txt".

**Comment by oobabooga** [comment]
Solved here https://github.com/oobabooga/text-generation-webui/commit/1edfb9677840b03ce321a450aed87961af24a361

**Comment by davidcaputokeene** [comment]
I'm a total newb and cant find 'start-webui.bat' in  'text-generation-webui-main' is there another place to enter the extensions Maybe the internal structure has changed? or how can i find 'start-webui.bat'? Apologies for total nubbiness.
