### ISSUE TITLE
Multimodal for llama.cpp GGUF and Llava 1.6

### ISSUE THREAD

**Issue by Dartvauder** [oobabooga/text-generation-webui#5603]
Good afternoon. When will multimodality support be added with llama.cpp GGUF? It has already been officially added to llama.cpp itself, but it does not work in your application. In addition, llava 1.6 has already been released. Add support please

**Comment by Tetragramm** [comment]
I would second this.  I am beginning to see open-source models that come with their own mmproj files and would like to try them out.

**Comment by realsammyt** [comment]
+1
