### ISSUE TITLE
How does text-generaton-webui load characters in the prompt? Tried to scan the code but as a noob, found no clue.

### ISSUE THREAD

**Issue by audrito** [oobabooga/text-generation-webui#5670]
### Describe the bug

It's not a bug, and I'm sorry to post here. But I need urgent help. I'm building an LLM application that has some similarities with `text-generation-webui`. In my application, I tried to add character support. It kind of works but doesn't match the quality of text-generation-webui. Same prompts, same model, same parameters, same character file, but still, the quality is not up to the mark.

### I need to know the workflow or the processing text-generation-webui does before adding it inside the prompt.
Currently, my application replaces the `{{user}}` placeholder with `you` before adding it to the prompt. This does make the character data grammatically incorrect, as it was originally written in the third person. Another problem is that when I try a system prompt suggested by the model creator like this :
```
Continue the conversation by writing a single dialogue while playing the following character. {character_data}
Previous Conversation :
{history}
Human : {input}
AI :
```
**The model starts to address the user by the name 'Human' in the responses.** What's the best way to fix this?

In simple words, the issues I'm facing while developing an application :

- It's performing dumb
- Repetitive (even though repetition penalty is 1.18, and same params performs better in text-generation-webui)
- Addressing the user as 'Human' because of the system prompt.

What is the process to get results like text-generation-webui? Can someone explain to me how the character works here?

### System Info

```shell
Windows 11
NVIDIA
GeForce GTX 1660 Super
```

**Comment by altoiddealer** [comment]
You should probably close this and just spam discord help channels

**Comment by audrito** [comment]
@altoiddealer Yeah, I got the solution. Sorry for the trouble, forgot to close it.
