### ISSUE TITLE
Generation speed becomes much slower on remote.

### ISSUE THREAD

**Issue by 925-Studio** [oobabooga/text-generation-webui#5692]
I have a PC and oobabooga runs fast on it. I get around 20~30 IPS when using 7B models. But if I use this PC as a server, and run oobabooga remotely through SSH, the generation speed down to 3 IPS.

First I link to the PC through SSH from my Mac, then run oobabooga through command line. I can see even the model loading speed is much slower than local in the terminal.

 I also run Stable Diffusion webui remotely (Forge, Foocus, ComfyUI), they are as fast as local.

Is there a solution or some argurments I can use?

Thank you guys in advance.

**Comment by p-e-w** [comment]
I suspect this is a duplicate of #4990, which should probably be reopened as it is not fixed.

I have high hopes for the Gradio 4 upgrade, which might improve those performance issues. On a poor connection, so many things that should happen instantly take sometimes dozens of seconds to happen (such as displaying the chat greeting, even though the model has long loaded).

**Comment by 925-Studio** [comment]
> I suspect this is a duplicate of #4990, which should probably be reopened as it is not fixed.
> 
> I have high hopes for the Gradio 4 upgrade, which might improve those performance issues. On a poor connection, so many things that should happen instantly take sometimes dozens of seconds to happen (such as displaying the chat greeting, even though the model has long loaded).

Nope, I don't think it's a duplicate. His/Her problem is wasting time on streaming but his generate speed is good. My problem is I have both good generate speed and stream speed on local, but horrible on remote.

**Comment by 925-Studio** [comment]
> That's pretty strange. Could it be that the GPU is not working properly because you're not running a graphical session? Have you tried llama.cpp instead? Does it have the same problem?

Thank you for quick response. I'm not sure about graphical session means and I only use gguf format so it means I made llama.cpp my default.

It does strange because if I launch oobabooga on pc then remote access the webui, it works perfect as local. But if I launch it through SSH on mac, the speed decreases a lot. I have only one display and I prefer MacOS, so I use my pc as a server with AI calculation through SSH. All works fine except oobabooga.

My Mac: Mac mini + 13.6.5 (22G621)
My PC: 13600KF + 128GB RAM + 4080 Super 16GB + Windows 11 Pro x64

`Windows -> PowerShell -> start_windows.bat --listen --api --model-dir "D:\Models\AIC - models" -> Works perfect in Windows Chrome`

`Windows -> PowerShell -> start_windows.bat --listen --api --model-dir "D:\Models\AIC - models" -> Works perfect with remote access with any deivice`

`Mac -> terminal -> SSH -> start_windows.bat --listen --api --model-dir "D:\Models\AIC - models" -> very slower generation speed`

But any other local AI generation program works without problem through SSH, like I mentioned in the original post, Forge, Foocus, ComfyUI.

**Comment by p-e-w** [comment]
> I only use gguf format so it means I made llama.cpp my default.

I meant, try using llama.cpp directly by compiling the upstream C++ project and loading the GGUF from the command line. text-generation-webui uses a Python wrapper with architecture-specific wheels and a bunch of other moving parts that complicate things.

**Comment by 925-Studio** [comment]
> > I only use gguf format so it means I made llama.cpp my default.
> 
> I meant, try using llama.cpp directly by compiling the upstream C++ project and loading the GGUF from the command line. text-generation-webui uses a Python wrapper with architecture-specific wheels and a bunch of other moving parts that complicate things.

Didn't try this but I got it work properly on Linux, it's faster than Windows local. Anyway, thanks for your tips.
