### ISSUE TITLE
`user_bio` is None by default, get an error when replacing the character names

### ISSUE THREAD

**Issue by Yiximail** [oobabooga/text-generation-webui#5717]
### Describe the bug
Using API `/v1/chat/completions` (None stream mode) without `user_bio`.

----

The new parameter `user_bio` in API chat mode raises an error because it's `None` as default.
https://github.com/oobabooga/text-generation-webui/blob/7cf1402bde48fd76af501d5efecb34227bf4d082/extensions/openai/typing.py#L110

----

Then, in `chat.py` can't replace the names correctly.
https://github.com/oobabooga/text-generation-webui/blob/7cf1402bde48fd76af501d5efecb34227bf4d082/modules/chat.py#L97

get this error
![image](https://github.com/oobabooga/text-generation-webui/assets/15323975/8d5f9519-33d5-48e8-809c-7dd29e43eee2)

-----

An empty string as default in webui.
https://github.com/oobabooga/text-generation-webui/blob/7cf1402bde48fd76af501d5efecb34227bf4d082/modules/shared.py#L60

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Any request in `/v1/chat/completions`

### Logs

```shell
    text = text.replace('{{user}}', name1).replace('{{char}}', name2)
AttributeError: 'NoneType' object has no attribute 'replace'
```

### System Info

```shell
None
```

**Comment by ThatCoffeeGuy** [comment]
Just facing the same issue.

**Comment by Nero10578** [comment]
Same issue API no longer works with my previous formatting. So this needs a new user bio field?

**Comment by zhenweiding** [comment]
Facing the same issue too.

**Comment by sophosympatheia** [comment]
I encountered this too and worked around it by adding a sanity check to the replace_character_names function.

```
def replace_character_names(text, name1, name2):
    if text:
        text = text.replace('{{user}}', name1).replace('{{char}}', name2)
        return text.replace('<USER>', name1).replace('<BOT>', name2)
    else:
        return ""
```

**Comment by senchpimy** [comment]
> Add keys 'user_bio' and 'user_name' in request data can avoid this problem
> 
> ```json
> {
>         "mode": "chat",
>         "character": "Ami",
>         "messages": history,
>         "stop": ["\n", "<|im_end|>"],
>         "temperature": 0.8,
>         "user_bio": "",
>         "user_name": ""
> }
> ```

This works when you use "requests"/http, but you cant  use it with the openai lib

**Comment by EduardoABG** [comment]
I'm having this error too, when I try to use the openai library with baseURL for http://127.0.0.1:5000/v1

**Comment by Nicolas-Alexander** [comment]
Same issue. Can confirm with a locally ran http://127.0.0.1:5000/v1
I'll see about implementing one or both of the above fixes as a workaround until it's fixed.

**Comment by ViktorAgafonov** [comment]
I don’t know how it should have been, but I just edited the file "text-generation-webui/extensions/openai/typing.py" to changed string n.110 (user_bio: str | None = Field(default=''  ...)
