### ISSUE TITLE
Ooba shouldn't install Node is it doesn't need it, or should install latest version if required

### ISSUE THREAD

**Issue by tegant** [oobabooga/text-generation-webui#5740]
### Describe the bug

It seems that running `./start_linux.sh --share  --trust-remote-code` installs Node 12.
This breaks the environment for SillyTavern, which requires the latest stable Node.

I raised it with them as well, it seems Ooba is causing this issue. (see reproduction section below)
https://github.com/SillyTavern/SillyTavern/issues/1946

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I created a fresh ML VM on Azure and installed the latest stable Node (v21.7.1).

```
sudo apt-get update
sudo apt-get install build-essential checkinstall libssl-dev
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
nvm install node
```

Ten afterwards I pulled Ooba and ran `./start_linux.sh --share  --trust-remote-code`, which started it's own installation. Along the way it seems that Node was installed too, however an old version (12) of it. Alternatively it may have destroyed the previous Node install and it fell back to Ubuntu 20.04's default node, which I believe is version 12. 

If Ooba doesn't require Node, it shouldn't touch it, or at least use the existing version that is installed, instead of force installing version 12.

Thanks

### Logs

```shell
This breaks Node for SillyTavern. There is no log to show, other than the log of SillyTavern that complains about the outdated Node version.
```

### System Info

```shell
Azure ML VM
Nvidia Tesla M4
```

**Comment by Alkohole** [comment]
Ooba does not install Nodejs.... Check if your virtual machine does not have nodejs 12 pre-installed.

**Comment by tegant** [comment]
Thanks, yes, it was unrelated.
