### ISSUE TITLE
The checksum verification for miniconda_installer.exe has failed.

### ISSUE THREAD

**Issue by albertyu123456789** [oobabooga/text-generation-webui#5774]
### Describe the bug

The checksum verification for miniconda_installer.exe has failed.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

After I extracted the files, I clicked start_windows.bat.

### Logs

```shell
Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Windows-x86_64.exe to D:\text-generation-webui\installer_files\miniconda_installer.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 53.8M  100 53.8M    0     0  23.2M      0  0:00:02  0:00:02 --:--:-- 23.3M
find: '/i': No such file or directory
find: '/v': No such file or directory
find: ' ': No such file or directory
find: '/i': No such file or directory
find: '307194e1f12bbeb52b083634e89cc67db4f7980bd542254b43d3309eaf7cb358': No such file or directory
The checksum verification for miniconda_installer.exe has failed.
```

### System Info

```shell
windows11,CPU:i711800H,GPU:NVDIA RTXA2000Laptop
```

**Comment by cgwers** [comment]
Windows 10, NVidia RTX 3060


Fresh download on 23 April 2024:

Downloading Miniconda from https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Windows-x86_64.exe to D:\text-generation-webui-main\installer_files\miniconda_installer.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 53.8M  100 53.8M    0     0  88.5M      0 --:--:-- --:--:-- --:--:-- 88.6M
find: '/i': No such file or directory
find: '/v': No such file or directory
find: ' ': No such file or directory
find: '/i': No such file or directory
find: '307194e1f12bbeb52b083634e89cc67db4f7980bd542254b43d3309eaf7cb358': No such file or directory
The checksum verification for miniconda_installer.exe has failed.
Press any key to continue . . .
