### ISSUE TITLE
Not enabling AVX512 using GGUF llama.cpp on my 11900K

### ISSUE THREAD

**Issue by Nero10578** [oobabooga/text-generation-webui#5881]
### Describe the bug

I am running ooba on a 11900K and RTX 4090 for my main desktop and somehow it is not detecting the AVX512 capability of my CPU when loading the model using GGUF. 

Is there any setting or something in the source code I need to change in order for it to take advantage of AVX 512?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Run GGUF Ooba on 11900K 

### Logs

```shell
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 | MATMUL_INT8 = 0 |
```

### System Info

```shell
Windows 11
RTX 4090
i9 11900K
64GB RAM 4000MHz
```

**Comment by Trojaner** [comment]
I believe you will have to compile llama.cpp yourself to have AVX512 support

**Comment by Kreevoz** [comment]
llama.cpp's github also distributes compiled binaries with AVX512 enabled. Check them out and try them.
You're almost always limited by memory bandwidth on consumer CPUs so you will not see a speed improvement by using AVX512 instructions as those aren't the bottleneck.

**Comment by Nero10578** [comment]
> I believe you will have to compile llama.cpp yourself to have AVX512 support

Ah I see, that makes sense. This is just the first time I actually offloaded stuff to my CPU.



> llama.cpp's github also distributes compiled binaries with AVX512 enabled. Check them out and try them. You're almost always limited by memory bandwidth on consumer CPUs so you will not see a speed improvement by using AVX512 instructions as those aren't the bottleneck.

Will see what they do. I suspect you're right, my CPU only has around 70GB/s memory bandwidth lol.
