### ISSUE TITLE
How to use the API?

### ISSUE THREAD

**Issue by JamesKnight0001** [oobabooga/text-generation-webui#589]
I am confused about how to use the `CHAT` API.
When I try to use it I usually get an error on `response["data"][0]`.
Am I doing something wrong?
I used the example built into the text generation:
```py
'''

This is an example on how to use the API for oobabooga/text-generation-webui.

Make sure to start the web UI with the following flags:

python server.py --model MODEL --listen --no-stream

Optionally, you can also add the --share flag to generate a public gradio URL,
allowing you to use the API remotely.

'''
import requests

# Server address
server = "127.0.0.1"

# Generation parameters
# Reference: https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationConfig
params = {
    'max_new_tokens': 200,
    'do_sample': True,
    'temperature': 0.5,
    'top_p': 0.9,
    'typical_p': 1,
    'repetition_penalty': 1.05,
    'encoder_repetition_penalty': 1.0,
    'top_k': 0,
    'min_length': 0,
    'no_repeat_ngram_size': 0,
    'num_beams': 1,
    'penalty_alpha': 0,
    'length_penalty': 1,
    'early_stopping': False,
    'seed': -1,
}

# Input prompt
prompt = "What I would like to say is the following: "

response = requests.post(f"http://{server}:7860/run/textgen", json={
    "data": [
        prompt,
        params['max_new_tokens'],
        params['do_sample'],
        params['temperature'],
        params['top_p'],
        params['typical_p'],
        params['repetition_penalty'],
        params['encoder_repetition_penalty'],
        params['top_k'],
        params['min_length'],
        params['no_repeat_ngram_size'],
        params['num_beams'],
        params['penalty_alpha'],
        params['length_penalty'],
        params['early_stopping'],
        params['seed'],
    ]
}).json()

reply = response["data"][0]
print(reply)
```

**Comment by oobabooga** [comment]
There is no chat API at the moment, only normal/notebook mode work.

**Comment by JamesKnight0001** [comment]
> There is no chat API at the moment, only normal/notebook mode work.

that is quite sad

**Comment by Gitterman69** [comment]
i get the same error even when using notebook or default mode - i tried the code snippet from OP...

`C:\Users\kjhd\iCloudDrive\pythonProject2\venv\Scripts\python.exe C:/Users/domin/iCloudDrive/pythonProject2/LOL.py 
Traceback (most recent call last):
  File "C:\Users\domin\iCloudDrive\pythonProject2\LOL.py", line 62, in <module>
    reply = response["data"][0]
KeyError: 'data'

Process finished with exit code 1
`

**Comment by powercore2000** [comment]
> KeyError: 'data'

I had this error as well, when its a KeyError that means its looking for a field inside the JSON object you provided and cant find it. So here your missing the data field in the JSON object your providing

**Comment by ImranBug** [comment]
API still doesn't work?

I am get this error:
`{"detail":"Not Found"}`

`
HOST = '127.0.0.1:7860'
URI = f'http://{HOST}/api/v1/generate'
`

**Comment by way2swaggy** [comment]
> API still doesn't work?
> 
> I am getting this error: `{"detail":"Not Found"}`
> 
> `HOST = '127.0.0.1:7860' URI = f'http://{HOST}/api/v1/generate'`

did you ever fix this error? It seems to me that it could be because the URI is actually a different address (for example, 5000 instead of 7860) My theory is that the mismatch between the two different addresses causes the error.

**Comment by TheDarkTrumpet** [comment]
> > There is no chat API at the moment, only normal/notebook mode work.
> 
> that is quite sad

I'd look at SillyTavern and how they handle the idea of chat mode.  They connect to text-generation-webui, and they emulate the chat mode themselves.  You can run the application and look at the output.  It combines previous information gathered from the API along with new input, and sends it back.  So you can emulate the chat portion just fine given the limitation pointed out.  

Also, for:
> did you ever fix this error? It seems to me that it could be because the URI is actually a different address (for example, 5000 instead of 7860) My theory is that the mismatch between the two different addresses causes the error.

Yes, it's on a different port, it's 5000

If you run the following:
`python3 server.py --listen --auto-devices --api`
you get the following:
```
...
ws://0.0.0.0:5005/api/v1/stream
...
http://0.0.0.0:5000/api

Running on local URL:  http://0.0.0.0:7860
```
