### ISSUE TITLE
Tokenizer class LLamaTokenizer does not exist or is not currently imported

### ISSUE THREAD

**Issue by Websteria** [oobabooga/text-generation-webui#590]
### Describe the bug

I have seen this issue with an incorrect spelling, but I have checked my spelling and it is consistent with the spelling shown in the error message.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

start webui and try to load a llama based model

### Logs

```shell
The following models are available:

1. gpt-j-6B
2. llama-7b-hf
3. pygmalion
4. pygmalion-350m
5. pygmalion-6b

Which one do you want to load? 1-5

2

Loading llama-7b-hf...
Auto-assiging --gpu-memory 23 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████| 33/33 [00:07<00:00,  4.49it/s]
Traceback (most recent call last):
  File "C:\text-generation-webui-new\text-generation-webui\server.py", line 234, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\text-generation-webui-new\text-generation-webui\modules\models.py", line 165, in load_model
    tokenizer = AutoTokenizer.from_pretrained(Path(f"models/{shared.model_name}/"))
  File "C:\text-generation-webui-new\installer_files\env\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 679, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLamaTokenizer does not exist or is not currently imported.
```

### System Info

```shell
Win 11, RTX 4090
```

**Comment by OpenMOSE** [comment]
i had same problem.

You need to change tokenizer_config.json in quantization model folder.
"tokenizer_class": "LLamaTokenizer" → "tokenizer_class": "LLaMATokenizer"

if not solved, you can check LLaMATokenizer name in 
\anaconda3\envs\(Your Env)\lib\python3.10\site-packages\transformers\models\auto\tokenization_auto.py

Line:170 ("llama", ("LLaMATokenizer" if is_sentencepiece_available() else None, None))

**Comment by Websteria** [comment]
It's actually LlamaTokenizer inside the tokenization_auto.py

When I change mine to the same spelling it tells me that one could not be instantiated. It follows the models tokenizer_config.json instead of the auto_tokenization.py code it seems like

**Comment by Websteria** [comment]
There was an extra space in my "LLamaTokenizer "

Fixed and working. Thanks everyone!
