### ISSUE TITLE
docker-compose.yml Line 25 Potential Typo

### ISSUE THREAD

**Issue by JonathanTurunen** [oobabooga/text-generation-webui#5991]
Sorry again if this has been filed incorrectly as I'm new to this but it looks like there is a typo on Line 25 of the `docker-compose.yml` here:
https://github.com/oobabooga/text-generation-webui/blob/8f12fb028dff4e133460fe10ef49d3f90167b313/docker/nvidia/docker-compose.yml#L25

Based on the earlier lines, I think it should read:
`APP_UID: ${APP_UID:-6972}`

**Comment by blackmambaza** [comment]
This is not a typo.

**Comment by JonathanTurunen** [comment]
Understood, thanks.
