### ISSUE TITLE
Issue partitioning memory between GPU and CPU (--auto-device not working) 

### ISSUE THREAD

**Issue by RandomInternetPreson** [oobabooga/text-generation-webui#60]
![Untitled](https://user-images.githubusercontent.com/6488699/217361322-33f3a925-a599-41ad-ab9a-ade2755a3283.png)

The above error is what I get when I try to use --auto-device to split between GPU and CPU.  The system has 128GB of ram and a 4090, I've tried variations such as preallocating a certain amount of CPU memory and GPU memory, and I keep getting the attached error. 

I like the UI and would love to get this to work, also 8-bit is not working, but I figured one issue at a time.  KoboldAI is good, but I think this runs faster and the outputs are easier to read.

**Comment by oobabooga** [comment]
This is an upstream issue with the transformers library and the XGLM model specifically. Nothing can be done other than waiting for them to implement device_map='auto' for this model.

As for 8-bit, there are some hacks to get it to work on Windows that work for some people, but afaik it is not officially supported yet.

**Comment by RandomInternetPreson** [comment]
> I also have a 4090 and this works for me, it launches and generates properly : python server.py --cai-chat --auto-devices --no-stream --bf16 --gpu-memory 18
> 
> So no idea what's the problem here.

Are you on a Windows machine?  I'll try your settings later today, I didn't have the -bf16 in there and I set the GPU memory to 20, maybe 18 is the sweet spot.
