### ISSUE TITLE
No models can be loaded. Text generation is dead.

### ISSUE THREAD

**Issue by Hawlton** [oobabooga/text-generation-webui#6039]
### Describe the bug

I was using mistralai/Mistral-7B-Instruct-v0.2 just fine with no issues for the longest time
until today the model just decided to not load. Absolutely no settings have been changed
and I have done everything right. I completely deleted everything and started over and it's 
still failing to load models. Text generators have basically been set back a decade because of this issue.

This is partially due to the fact that models can no longer be downloaded in the UI itself because
Hugging face will return a 401 error if you try even with the correct HF_TOKEN set as an env variable.
You now have to use this broken "download-model.py" script which can't complete a model download
to save it's life. It stops anywhere from 80 to 97 percent for no reason. Cloning the git repository also 
makes you enter credentials which it can't validate cuz it's broken too. 

When the model fails to load it crashes the whole webui with no error other than "press any key to continue..."
This is a disaster and I have never been so frustrated by any single issue in my 15 year IT career.
My system specs are below. I know for a fact that it can run smaller models and This worked flawlessly in the past.

So the question is basically this: Where can I get a full download of a model?

First screenshot shows download_model.py failing to complete the download.
Second screenshot shows what happens when you try to load ANY model.

![stupidfuckingthing](https://github.com/oobabooga/text-generation-webui/assets/133937134/2fe06f64-83c3-44c3-933c-5751d3a4faac)

![Screenshot 2024-05-21 173151](https://github.com/oobabooga/text-generation-webui/assets/133937134/cb32f7c5-b1e0-4254-b1f2-20c6cf68e086)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1) Clone the text-generation-webiu repo
2) Run .\start_windows.bat
3) launch webui and attempt to download a model
4) receive http error 401 when trying to download any model (HF_TOKEN env variable has been set)
5) run .\cmd_windows.bat and set env variable.
6)run "python download_model.py <any_model>

### Logs

```shell
PS C:\Users\roflc\Documents\text-generation-webui> .\start_windows.bat
17:28:49-855367 INFO     Starting Text generation web UI

Running on local URL:  http://127.0.0.1:7860

17:31:20-469512 INFO     Loading "meta-llama_Meta-Llama-3-8B"
17:31:20-474020 INFO     TRANSFORMERS_PARAMS=
{'low_cpu_mem_usage': True, 'torch_dtype': torch.float16}

Loading checkpoint shards:   0%|                                                                 | 0/4 [00:00<?, ?it/s]Press any key to continue . . .
```

### System Info

```shell
Nvidia RTX 3070
Intel i5 12th gen
16GB DDR4
```

**Comment by M0deseven** [comment]
UPDATE: I was able to force the webui to work by hard coding the token into the batch file as an env variable.
This fixed the http errors that I'm getting but the downloads are still incomplete. I'm going to still try and see
if I can workaround GitHub's atrocious authentication and get them from there because this is ridiculous.

**Comment by M0deseven** [comment]
UPDATE: I have completely re-imaged my PC. Changed to Arch Linux and I'm still getting the same issue. text-generation-webui crashes when loading any model. I got a notification from GNOME saying that swap file usage was high. I increased the size to 24GB and that still didn't fix it. I still crashes with no error.  Automatic1111 runs perfectly every time and doesn't have these issues.

**Comment by ashleykleynhans** [comment]
Sounds like the issue is caused by only having 16GB of system/cpu memory.

**Comment by Hawlton** [comment]
The memory was a contributing factor but I was able to get around that limitation with a 24GB swap file.
I ended up loading the model in 4bit mode and that seems to have fixed the issue. It loads correctly now.
