### ISSUE TITLE
Ability to set a password for remote access

### ISSUE THREAD

**Issue by Slug-Cat** [oobabooga/text-generation-webui#606]
I'm hosting my installation through an external port for remote access (prevents time limitations of public gradio links). It would be nice to be able to set a password to prevent unauthorized usage of my GPU should someone happen upon the application's address. I think this is already a feature in Automatic1111, and both use gradio so it should be a similar thing I think.

**Comment by oobabooga** [comment]
If you are leaving the port open in the wild, you are sure to get detected by a mass scanner in a few hours at most.

**Comment by oobabooga** [comment]
You can now use `--gradio-auth-path pwd.txt` where `pwd.txt` is 

```
user1:password1,user2:password2
```

https://github.com/oobabooga/text-generation-webui/pull/549
