### ISSUE TITLE
flash-attn and flash_attn both in shared.args

### ISSUE THREAD

**Issue by Touch-Night** [oobabooga/text-generation-webui#6070]
### Describe the bug

In shared.args, there are both flash-attn and flash_attn, and flash-attn is the value set in the ui, while flash_attn is False forever.  

This can result users cannot enable flash-attn through ui.  

To fix it, use flash_attn in modules/loaders.py, modules/ui.py and use shared.gradio['flash_attn'] in modules/ui_model_menu.py

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Use a debugger and load a gguf model with flash-attn checked, and see shared.args

### Screenshot

![image](https://github.com/oobabooga/text-generation-webui/assets/102669562/1b287096-eb52-4821-8c2b-e709665c37a2)
![image](https://github.com/oobabooga/text-generation-webui/assets/102669562/14c4a793-6f53-4cdc-a27e-0eb7fe5adb55)
*shared.args.flash-attn = True and shared.args.flash_attn = False when flash-attn is checked in the ui*  

### Logs

```shell
Not necessary
```

### System Info

```shell
Not necessary
```

**Comment by Ph0rk0z** [comment]
So one should be rename flash_attention. Is this what is breaking it in llama.cpp?

**Comment by Touch-Night** [comment]
> ok.. no, I did a double take, there is only one `group.add_argument('--flash-attn', action='store_true', help='Use flash-attention.') ` using it in the program as flash_attn works.

https://github.com/oobabooga/text-generation-webui/blob/abe5ddc8833206381c43b002e95788d4cca0893a/modules/shared.py#L211-L217

**Comment by Ph0rk0z** [comment]
Yep, it is PR'd, try it. Now it activates.

**Comment by Touch-Night** [comment]
> Yep, it is PR'd, try it. Now it activates.

Sorry, didn't notice your pr.

**Comment by Touch-Night** [comment]
Fixed in #6076
