### ISSUE TITLE
The scripts quits when i'm trying to load gpt-j-6b

### ISSUE THREAD

**Issue by musikowskipawel** [oobabooga/text-generation-webui#609]
### Describe the bug

The scripts sends ^C after it's trying to load gpt-j-6b

I'm using Colab version.

Screenshot: https://i.imgur.com/1rPU7Yb.png

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

add gpt-j-6b

like this:

# Parameters
model = "gpt-j-6B" #@param ["Pygmalion 6B original (sharded, rehosted)", "Pygmalion 6B main (sharded, rehosted)", "Pygmalion 6B dev (sharded, rehosted)", "Pygmalion 350m (for debugging)", "gpt-j-6B"] {allow-input: false}

# Data
models = {
    "Pygmalion 6B original (sharded, rehosted)": ("waifu-workshop", "pygmalion-6b", "original-sharded", "pygmalion-6b_original-sharded"),
    "Pygmalion 6B main (sharded, rehosted)": ("waifu-workshop", "pygmalion-6b", "sharded", "pygmalion-6b_sharded"),
    "Pygmalion 6B dev (sharded, rehosted)": ("waifu-workshop", "pygmalion-6b", "dev-sharded", "pygmalion-6b_dev-sharded"),
    "Pygmalion 350m (for debugging)": ("PygmalionAI", "pygmalion-350m", "main", "pygmalion-350m"),
    "gpt-j-6B": ("EleutherAI", "gpt-j-6B", "main", "gpt-j-6B"),
}

and try to load it

### Screenshot

https://i.imgur.com/eXmBwPJ.png
https://i.imgur.com/BW0VyJM.png

### Logs

```shell
there's no error, just C^
```

### System Info

```shell
Google Colab GPU
```

**Comment by oobabooga** [comment]
That's an upstream issue in transformers https://github.com/huggingface/transformers/issues/21376

A workaround is to reshard the model like it was done for pygmalion here https://huggingface.co/waifu-workshop/pygmalion-6b/tree/original-sharded

**Comment by musikowskipawel** [comment]
how do i reshard? what resources do i need for that?

**Comment by oobabooga** [comment]
You can use this script: https://github.com/oobabooga/text-generation-webui/blob/main/convert-to-safetensors.py

All you need is a computer with enough RAM to fully load the model. To use on Google Colab, you will need to upload the resharded gpt-j somewhere (you can't reshard on colab as it will OOM while doing that too).

**Comment by musikowskipawel** [comment]
What do I need to input to this script? Would i need to have gpu which is good enough as well?
