### ISSUE TITLE
Please allow keyboard shortcut remapping

### ISSUE THREAD

**Issue by dronelove** [oobabooga/text-generation-webui#6099]
Is there a way to change the default keyboard shortcuts? e.g. Regenerate (Ctrl + Enter). I would like to customize the shortcuts. 

Tried editing chat_ui.py but that only changed the button appearance, not the functionality.

Thanks!

**Comment by Alkohole** [comment]
Sounds to me like that's what you need:
https://github.com/oobabooga/text-generation-webui/blob/abe5ddc8833206381c43b002e95788d4cca0893a/js/main.js#L65-L69
