### ISSUE TITLE
Why do you talk nonsense?

### ISSUE THREAD

**Issue by chinabus** [oobabooga/text-generation-webui#6108]
### Describe the bug

When answering short questions, there are no problems, but when answering complex questions (more than 50 characters), they start to speak nonsense.
I suspect that I have messed up the settings, but after resetting, there is still the same problem

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

任意模型

### Logs

```shell
{   'temperature': 0.98,
    'top_p': 0.37,
    'top_k': 100,
    'repetition_penalty': 1.18}
```

### System Info

```shell
11400
2080ti
```

**Comment by Woisek** [comment]
Was that always the case with the bot you used?
The quality of the answer depends partly on how good a bot is configured. A bad bot will give bad answers.

**Comment by chinabus** [comment]
I solved this problem through a thorough reinstallation and deployment. I suspect that the template error or cache problem of some prompt words is caused in the process of multiple upgrades.
