### ISSUE TITLE
Alpaca-30b-lora-int4 cant find config.json

### ISSUE THREAD

**Issue by iChristGit** [oobabooga/text-generation-webui#613]
### Describe the bug

I am running the new llama-30b-4bit-128g just fine using the latest
 GPTQ and Webui commits.
When trying to run the new [alpaca-30b-4bit-128g.safetensors](https://huggingface.co/elinas/alpaca-30b-lora-int4/blob/main/alpaca-30b-4bit-128g.safetensors)

Its been updated yesterday so I removed the old .pt files and grabbed the new safetensors files.
I get an error trying to find config.json, although all files are there. tried with the files under /loras and under /models
Anyone figured it out? Am i doing something wrong? does the config.json file needs an update? its not been updated on hugginface.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

~trying to run the new alpaca-30b/13b weights.

### Screenshot

Folder with files (same for 30B)
https://imgur.com/a/GifgYBs

### Logs

```shell
Using the following device map for the 4-bit model: {'': 0}
Loaded the model in 6.12 seconds.
Adding the LoRA alpaca-13b-lora-int4 to the model...
Traceback (most recent call last):
  File "/home/ultra/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/utils/config.py", line 99, in from_pretrained
    config_file = hf_hub_download(pretrained_model_name_or_path, CONFIG_NAME)
  File "/home/ultra/miniconda3/envs/textgen/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/ultra/miniconda3/envs/textgen/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 157, in validate_repo_id
    raise HFValidationError(f"Repo id must be a string, not {type(repo_id)}: '{repo_id}'.")
huggingface_hub.utils._validators.HFValidationError: Repo id must be a string, not <class 'pathlib.PosixPath'>: 'loras/alpaca-13b-lora-int4'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ultra/text-generation-webui/server.py", line 275, in <module>
    add_lora_to_model(shared.args.lora)
  File "/home/ultra/text-generation-webui/modules/LoRA.py", line 35, in add_lora_to_model
    shared.model = PeftModel.from_pretrained(shared.model, Path(f"{shared.args.lora_dir}/{lora_name}"), **params)
  File "/home/ultra/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/peft_model.py", line 135, in from_pretrained
    config = PEFT_TYPE_TO_CONFIG_MAPPING[PeftConfig.from_pretrained(model_id).peft_type].from_pretrained(model_id)
  File "/home/ultra/miniconda3/envs/textgen/lib/python3.10/site-packages/peft/utils/config.py", line 101, in from_pretrained
    raise ValueError(f"Can't find config.json at '{pretrained_model_name_or_path}'")
ValueError: Can't find config.json at 'loras/alpaca-13b-lora-int4'
```

### System Info

```shell
Windows11, WSL2, 3090Ti 32GB Ram
```

**Comment by official-elinas** [comment]
Hey. I'm the one who uploaded the 4bit quantized versions of Alpaca. Make sure to pass `--model_type llama` as a parameter. Without it the model hangs on loading for me.

**Comment by iChristGit** [comment]
> Hey. I'm the one who uploaded the 4bit quantized versions of Alpaca. Make sure to pass `--model_type llama` as a parameter. Without it the model hangs on loading for me.
> 
> Edit: I had a model loaded already when I was testing it, looks like that flag doesn't matter anymore for Alpaca. I'm currently using the same config JSON from the repo. Though I am not on the latest commit but rather `a04b7cf2643a5950fc215deac7f76b4b31336a81` from 2 days ago.

Hey! thanks for the reply!
Ive tried with --model_type llama, as well as git checkout a04b7cf2643a5950fc215deac7f76b4b31336a81

None of them works, it still thinks I dont have the config.json file.
I wonder if I am the only one facing this issue.

**Comment by official-elinas** [comment]
I think the error might be because it thinks you're passing in a HF repo based on `huggingface_hub.utils._validators.HFValidationError: Repo id must be a string, not <class 'pathlib.PosixPath'>: 'loras/alpaca-13b-lora-int4'.`

I would try not nesting the directories and see if that fixes it. I'd attempt to replicate your issue, but my server is currently occupied quantizing another model.

**Comment by iChristGit** [comment]
> I think the error might be because it thinks you're passing in a HF repo based on `huggingface_hub.utils._validators.HFValidationError: Repo id must be a string, not <class 'pathlib.PosixPath'>: 'loras/alpaca-13b-lora-int4'.`
> 
> I would try not nesting the directories and see if that fixes it. I'd attempt to replicate your issue, but my server is currently occupied quantizing another model.

My models are downloaded locally, the files are there, I dont understand the solution.. :D

**Comment by Nondzu** [comment]
@iChristGit You must update [text-generation-webui](https://github.com/oobabooga/text-generation-webui) to the lastes version and run `pip install -r requirements.txt` and also update GPTQ [gptq-for-llama](https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#step-1-install-gptq-for-llama) with `python setup_cuda.py install` . I use [alpaca-30b-4bit-128g.safetensors](https://huggingface.co/elinas/alpaca-30b-lora-int4/blob/main/alpaca-30b-4bit-128g.safetensors) on my linux server with success

**Comment by iChristGit** [comment]
> @iChristGit You must update [text-generation-webui](https://github.com/oobabooga/text-generation-webui) to the lastes version and run `pip install -r requirements.txt` and also update GPTQ [gptq-for-llama](https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#step-1-install-gptq-for-llama) with `python setup_cuda.py install` . I use [alpaca-30b-4bit-128g.safetensors](https://huggingface.co/elinas/alpaca-30b-lora-int4/blob/main/alpaca-30b-4bit-128g.safetensors) on my linux server with success

I just did all of that but still same error, the python setup_cuda.py install part completed within two seconds.
I dont understand whats wrong..

**Comment by iChristGit** [comment]
> @iChristGit You must update [text-generation-webui](https://github.com/oobabooga/text-generation-webui) to the lastes version and run `pip install -r requirements.txt` and also update GPTQ [gptq-for-llama](https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#step-1-install-gptq-for-llama) with `python setup_cuda.py install` . I use [alpaca-30b-4bit-128g.safetensors](https://huggingface.co/elinas/alpaca-30b-lora-int4/blob/main/alpaca-30b-4bit-128g.safetensors) on my linux server with success

Are your models those?
Llama 13b - https://github.com/oobabooga/text-generation-webui/pull/530#issuecomment-1483941105
Alpaca 13b - https://huggingface.co/elinas/alpaca-13b-lora-int4

Ive just tried a fresh install native windows using the 1clickinstaller, same error trying to find config.json that is PRESENT there xD

**Comment by iChristGit** [comment]
@oobabooga 
Can you maybe help with the underlying issue?
Ive tried all bunch of loras, all of them cant find the config.json file, normal models do work great (4bit,8bit, latest 1clickinstall)

**Comment by oobabooga** [comment]
This is a model with the lora merged in and not a lora: https://huggingface.co/elinas/alpaca-13b-lora-int4/

This is a lora: https://huggingface.co/tloen/alpaca-lora-7b

**Comment by iChristGit** [comment]
> This is a model with the lora merged in and not a lora: https://huggingface.co/elinas/alpaca-13b-lora-int4/
> 
> This is a lora: https://huggingface.co/tloen/alpaca-lora-7b

I feel so dumb, thanks so much!
