### ISSUE TITLE
Bump exllamav2 version to 0.1.5 in requirements

### ISSUE THREAD

**Issue by dsent** [oobabooga/text-generation-webui#6150]
**Description**

Currently, exllamav2 0.0.20 is installed by default. Updating exllamav2 to the latest wheel release improves VRAM consumption a lot in some cases, e.g. allowing 1.5x more context with the same quants of Command-R. It seems that this update can be done in isolation, without changing anything else, and it doesn't break anything. I guess that after an update, it will be downgraded back to 0.0.20 due to requirements.txt. Would be nice to have this version out of the box.

**Additional Context**

I've tested on Windows with the build from here: https://github.com/oobabooga/exllamav2/releases/

**Comment by dsent** [comment]
I've seen the branch with exllamav2 updated, but it also bumps the version of pytorch. AFAIK, the current versions of pytorch don't play well with flash attention 2 on Windows (even with the working build of flash attention 2 installed). I'm not certain about this, and if I'm wrong, then updating pytorch is probably a good thing too.

**Comment by Thireus** [comment]
Thanks for raising this. If you edit your requirements.txt to replace the existing exllamav2 links by those, then run `./update_wizard_linux.sh # Option B` and update all the requirements, this should work.

```
https://github.com/oobabooga/exllamav2/releases/download/v0.1.5/exllamav2-0.1.5+cu121.torch2.2.2-cp311-cp311-win_amd64.whl; platform_system == "Windows" and python_version == "3.11"
https://github.com/oobabooga/exllamav2/releases/download/v0.1.5/exllamav2-0.1.5+cu121.torch2.2.2-cp310-cp310-win_amd64.whl; platform_system == "Windows" and python_version == "3.10"
https://github.com/oobabooga/exllamav2/releases/download/v0.1.5/exllamav2-0.1.5+cu121.torch2.2.2-cp311-cp311-linux_x86_64.whl; platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.11"
https://github.com/oobabooga/exllamav2/releases/download/v0.1.5/exllamav2-0.1.5+cu121.torch2.2.2-cp310-cp310-linux_x86_64.whl; platform_system == "Linux" and platform_machine == "x86_64" and python_version == "3.10"
```

All links are available there: https://github.com/oobabooga/exllamav2/releases/

Not sure why the requirements.txt hasn't been updated to support the latest version yet, maybe there's a reason to it. I've just tested v0.1.5 and it seems to work just fine.

**Comment by dsent** [comment]
Yeah, I understand that I can change requirements.txt, but wouldn't my version be overwritten next time an update is pulled from git? If I have to change something by hand, I can as well just install 0.1.5 wheel again after an update.

**Comment by Thireus** [comment]
It's been bumped on the dev branch already, but not yet merged to the main branch: https://github.com/oobabooga/text-generation-webui/commit/8930bfc5f487b78fe103a1b66bd81fc9d7a84a1d

So, you could either wait or switch to dev.

**Comment by dsent** [comment]
I'm aware of this (see [my second message](https://github.com/oobabooga/text-generation-webui/issues/6150#issuecomment-2183572414)), but it bumps PyTorch too, and I wonder if this breaks Flash Attention on Windows.

**Comment by oobabooga** [comment]
It doesn't, I compiled flash attention myself to ensure compatibility.

**Comment by dsent** [comment]
Thank you for the info! Will try switching to the updated branch, then.

**Comment by dsent** [comment]
I see that PyTorch is back to 2.2.2 in the dev branch, so I guess there is some kind of problem with it, right?

BTW, I think that the latest win64 wheels available from pytorch.org are compiled without flash-attn, so even if there's compiled and working flash-attn installed, in order to use it, you'd have to recompile pytorch too. I could be wrong about this, as I'm not that experienced, but I wasn't able to make flash attention work in my Stable Diffusion stuff with pytorch 2.3.1.
