### ISSUE TITLE
Add Character drop down back to Parameters > Chat > Character section

### ISSUE THREAD

**Issue by jordanbtucker** [oobabooga/text-generation-webui#6174]
**Description**

While I like having the Character dropdown on the main page, I really dislike the fact that the Character dropdown has been removed from the Parameters > Chat > Character section. It is now much more difficult to switch between characters when designing them, especially if you want to copy and paste sections between character Context fields, as I often do.

I now have to switch back to the Main page, switch characters, go back to Parameters > Chat > Character, copy what I want out of it, go back to the Main page, switch to the new character I'm designing, go back to Parameters > Chat > Character, paste in the section. It was much easier when I could just switch characters in the Character tab. (This is all done on mobile, by the way, so I can't just open an new tab and switch between them easily.)

It is also now more difficult to find the character I want. When I was able to easily switch characters in the Parameters > Chat > Character section, I could skim the Context to make sure that is the character I'm looking for. Now, again, I have to switch back and forth between the Main page and the Parameters > Chat > Character section to ensure the correct character is chosen.

Again, I like the ability to switch characters on the Main page. I would just like the Character dropdown added back to the Parameters > Chat > Character section. Thanks for your consideration.

**Comment by CRCODE22** [comment]
I agree this update is not an improvement. I prefer the previous way. This new way is very annoying and not logical. If it must be on the main page at least also add it back to Parameters > Chat > Character section.

**Comment by oobabooga** [comment]
I agree. Since I don't know how to have the same dropdown at two different locations, I have reverted the change https://github.com/oobabooga/text-generation-webui/commit/de69a6200495fff8f4c63b8759671a2beb19d550.

**Comment by jordanbtucker** [comment]
> Since I don't know how to have the same dropdown at two different locations

I was trying to create a PR, but I ran into that same problem!

**Comment by oobabooga** [comment]
I found a javascript solution to move the dropdown around the two tabs. It's in the dev branch now and seems to work.
