### ISSUE TITLE
Transformers 4.42.3 Compatibility Issue: Empty Outputs with Gemma2 and Existing Models

### ISSUE THREAD

**Issue by 93041025** [oobabooga/text-generation-webui#6184]
### Describe the bug

https://huggingface.co/google/gemma-2-9b-it
I downloaded the full version of gemma-2-9b-it from huggingface and copied the files to models folder.

Because the version of Transformers I was using didn't support gemma-2, so I upgraded to the latest version with

pip install transformers==4.42.3

While gemma-2 loads normally,

It throws an empty output.

The problem is that in the latest version, the models I was using before also throw empty outputs.

If I downgrade to transformers==4.41.*, the existing models work normally again (the drawback is that gemma2 doesn't load).

Is anyone experiencing a similar issue?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

pip install transformers==4.42.3

### Logs

```shell
Traceback (most recent call last):
  File "/home/llm/text-generation-webui/modules/callbacks.py", line 61, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llm/text-generation-webui/modules/text_generation.py", line 393, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/llm/miniconda3/envs/textgen/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/llm/miniconda3/envs/textgen/lib/python3.11/site-packages/transformers/generation/utils.py", line 1900, in generate
self._get_logits_warper(generation_config, device=input_ids.device)
TypeError: get_logits_warper_patch() got an unexpected keyword argument 'device'
Output generated in 0.31 seconds (0.00 tokens/s, 0 tokens, context 83, seed 1457115143)
```

### System Info

```shell
RTX 4090
```

**Comment by 93041025** [comment]
> There is an updated sampler_hijack.py in dev branch: [9dbcb1a](https://github.com/oobabooga/text-generation-webui/commit/9dbcb1aeeaedd13a4f3e9718d8f567744a561e4a)

Thank you. Does this mean I need to wait for an update?

**Comment by RandomInternetPreson** [comment]
@93041025 what version of textgen were you running to get your method to work?   Was it V1.8?
