### ISSUE TITLE
monkey_patch_llama_cpp_python is not needed

### ISSUE THREAD

**Issue by kimjaewon96** [oobabooga/text-generation-webui#6201]
### Describe the bug

A bit busy to do a pull request.
Current (v1.9) version does not work with llama.cpp, solved it by disabling line 54-55 in llama_cpp_python_hijack.py.
```python
    #if return_lib is not None:
        #monkey_patch_llama_cpp_python(return_lib)
```

Guessing that the latest llama-cpp-python version update turned it into a generator so we don't have to patch one.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
    #if return_lib is not None:
        #monkey_patch_llama_cpp_python(return_lib)
```

### Logs

```shell
included
```

### System Info

```shell
Windows python==3.11
```

**Comment by GralchemOz** [comment]
This solution fixed the issue for me; otherwise, an attempt to utilize llama.cpp would result in a "RecursionError: maximum recursion depth exceeded in comparison."
