### ISSUE TITLE
What does "CPU Memory" even mean?

### ISSUE THREAD

**Issue by 9cento** [oobabooga/text-generation-webui#621]
"Is it RAM? Main storage? Page file? Swap partition? Over provisioning? CPU cache even?" That's what a non-tech-savvy newfren could ask himself (probably just the first two questions, but still). Pls fix you bloody Sirs.

**Comment by oobabooga** [comment]
CPU memory = RAM

GPU memory = VRAM

**Comment by 9cento** [comment]
@oobabooga yeah I know, it was just a suggestion to change the terminology but maybe is not sneeded after all idk
