### ISSUE TITLE
Add support for mamba-codestral

### ISSUE THREAD

**Issue by Shadowblujay** [oobabooga/text-generation-webui#6249]
**Description**

Add support for https://huggingface.co/mistralai/mamba-codestral-7B-v0.1

I'm guessing this also means adding support for mamba models in general

**Additional Context**

Probably would have to be a separate model loader, from what I'm understanding either https://github.com/state-spaces/mamba or https://github.com/mistralai/mistral-inference could be used, although the original mamba package would probably be better for future models based on the mamba architecture from other sources.

**Comment by dlippold** [comment]
mamba-codestral is currently integrated into llama.cpp, see https://github.com/ggerganov/llama.cpp/issues/8519 . That depends on https://github.com/ggerganov/llama.cpp/pull/8526 where there still seems to be work to be done.
