### ISSUE TITLE
Virus warning with micromamba during fresh install

### ISSUE THREAD

**Issue by ARandomUserFromGithub** [oobabooga/text-generation-webui#626]
### Describe the bug

Windows quarantines the micoramba executable during install which causes the installation to fail.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Others have that problem too. They allowed it, but I prefer not to.
Use Windows, 10, with AV on.
Run windows's latest 1click install.

### Screenshot

![image](https://user-images.githubusercontent.com/117705597/228443446-a3602576-173b-43f3-81a2-cbf2fcf8ae1b.png)

### Logs

```shell
What is your GPU?

A) NVIDIA
B) None (I want to run in CPU mode)

Input> a
"Downloading Micromamba from https://github.com/mamba-org/micromamba-releases/releases/latest/download/micromamba-win-64 to F:\TGWUI\installer_files\mamba\micromamba.exe"
A subdirectory or file F:\TGWUI\installer_files\mamba already exists.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 8227k  100 8227k    0     0  5780k      0  0:00:01  0:00:01 --:--:--  9.8M
Micromamba version:
The system cannot execute the specified program.
Micromamba not found.
Press any key to continue . . .
```

### System Info

```shell
Windows 10, AMD, Nvidia GTX3090
```

**Comment by jllllll** [comment]
Just started getting this myself. Not the first time Windows Defender has erroneously flagged a new file as malicious.
Here is the Virus Total: https://www.virustotal.com/gui/file/5c1e89acb05a5a7f2da69ba6ef6d9a09fc45c557eb63bc4afb4a49848fb562a4

I'm going to submit a pr to change the download link to the previous version to avoid this in the future.

**Comment by jllllll** [comment]
In the mean time, change the `set MICROMAMBA_DOWNLOAD_URL=` command on line 5 to:
```
set MICROMAMBA_DOWNLOAD_URL=https://github.com/mamba-org/micromamba-releases/releases/download/1.4.0-0/micromamba-win-64
```

**Comment by oobabooga** [comment]
I have merged the PR, thanks @jllllll :)

**Comment by jackylee1** [comment]
I have the same problem?what is it

**Comment by jllllll** [comment]
@jackylee1 A new version of Micromamba released. It was different enough that virus scanners didn't recognize it and wrongly assumed it to be a virus.

Make sure you are using the latest installer as this should have been fixed. It may also be an issue with your specific anti-virus.
