### ISSUE TITLE
Request to Update Exllamav2 Module to version 0.1.8

### ISSUE THREAD

**Issue by GrennKren** [oobabooga/text-generation-webui#6266]
**Description**

I would like to request an update to the Exllamav2 module to version 0.1.8. This version includes some various bug fixes like https://github.com/turboderp/exllamav2/issues/566

**Additional Context**
For reference, the changes in version 0.1.8 are as follows:
- Support for Llama 3.1, including correct RoPE scaling.
- Support for IndexTeam architecture.
- Several bug fixes and quality of life improvements.

**Comment by St33lMouse** [comment]
I'd like to second that motion.

**Comment by oobabooga** [comment]
That's correct, today I have compiled it for PyTorch 2.2.2 and updated the requirements.txt in the dev branch. Llama-3.1 EXL2 is functional and I have [benchmarked it](https://oobabooga.github.io/benchmark.html). I'm still testing other unrelated things but tomorrow I should release a new version.
