### ISSUE TITLE
get ImportError for PIL Image

### ISSUE THREAD

**Issue by yangyu** [oobabooga/text-generation-webui#630]
### Describe the bug

Hi, guys
My environments:

OS: Windows 10 22H2
Python : uninstalled all python from PC
Installer :  download the zip file oobabooga-windows.zip

Errors:  When I finished the install.bat and download.bat, I clicked the start-webui.bat It report below errors :
Starting the web UI...
Traceback (most recent call last):
  File "D:\AIResearch\textgen\text-generation-webui\server.py", line 10, in <module>
    import gradio as gr
  File "D:\AIResearch\textgen\installer_files\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "D:\AIResearch\textgen\installer_files\env\lib\site-packages\gradio\components.py", line 22, in <module>
    import matplotlib.figure
  File "D:\AIResearch\textgen\installer_files\env\lib\site-packages\matplotlib\__init__.py", line 148, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "D:\AIResearch\textgen\installer_files\env\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "D:\AIResearch\textgen\installer_files\env\lib\site-packages\matplotlib\colors.py", line 51, in <module>
    from PIL import Image
  File "D:\AIResearch\textgen\installer_files\env\lib\site-packages\PIL\Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.

It looks like the PIL not been installed successfully. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Download the oobabooga-windows.zip
2. Unzip it
3. Run install.bat
4. Run download-model.bat
5. Run start-webui.bat

### Logs

```shell
no logs.
```

### System Info

```shell
OS : Windows 10 22H2
GPU : Nvida 3080
```

**Comment by jllllll** [comment]
Install VC++ Redist and see if that fixes it. I've seen people mention this elsewhere as being required by PIL

https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by jllllll** [comment]
Open `micromamba-cmd.bat` and run this command in it: `python -V`
What version of python does it report?

**Comment by yangyu** [comment]
After re-install, still the same error.  I run python -V in the micromamba, it is correct version : 3.10.9. During the install, I can see complie CUDA failed but it success installed from wheel. So I don't know how to fix it.

> Open `micromamba-cmd.bat` and run this command in it: `python -V` What version of python does it report?

**Comment by jllllll** [comment]
> After re-install, still the same error. I run python -V in the micromamba, it is correct version : 3.10.9. During the install, I can see complie CUDA failed but it success installed from wheel. So I don't know how to fix it.
> 
> > Open `micromamba-cmd.bat` and run this command in it: `python -V` What version of python does it report?

While making the new installer, I only encountered this error once after accidentally installing the wrong python version.

Where did you run the installer from? I know that Conda and it's variants have trouble with long file paths.
If that isn't the issue, try running `python -m pip install Pillow==9.3` in the `micromamba-cmd.bat`

**Comment by yangyu** [comment]
> > After re-install, still the same error. I run python -V in the micromamba, it is correct version : 3.10.9. During the install, I can see complie CUDA failed but it success installed from wheel. So I don't know how to fix it.
> > > Open `micromamba-cmd.bat` and run this command in it: `python -V` What version of python does it report?
> 
> While making the new installer, I only encountered this error once after accidentally installing the wrong python version.
> 
> Where did you run the installer from? I know that Conda and it's variants have trouble with long file paths. If that isn't the issue, try running `python -m pip install Pillow==9.3` in the `micromamba-cmd.bat`

Fixed it by pip uninstall Pillow and pip install Pillow. It installed Pillow 9.4 and issue fixed.

**Comment by jllllll** [comment]
Weird, must not have installed correctly the first time.
