### ISSUE TITLE
Support for Cerebras-GPT

### ISSUE THREAD

**Issue by dnhkng** [oobabooga/text-generation-webui#635]
There's a series of new models from Cerebras, from 111M to 13B parameters. 

Whats interesting is that they are Chinchilla training optimized (20x tokens ofer params), and, best of all, Apache 2.0 licenced!

Release announcement here:
https://www.cerebras.net/blog/cerebras-gpt-a-family-of-open-compute-efficient-large-language-models/

Models here:
https://huggingface.co/cerebras/Cerebras-GPT-13B

They look very interesting for many projects, due to the licencing. I think many people would like to test them using this GUI platform.

**Comment by oobabooga** [comment]
There is no need to add models one at a time. This model should already work.
