### ISSUE TITLE
Character gallery non-functional with newer Gradio versions

### ISSUE THREAD

**Issue by brandonj60** [oobabooga/text-generation-webui#640]
### Describe the bug

It looks like the Character Gallery doesn't work with Gradio versions >3.19.0. It seems the 'change' event isn't being picked up by character-menu, so clicking on character icons doesn't do anything.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

To replicate:
pip uninstall gradio
pip install gradio==3.23.0

The character icons no longer do anything when clicked.

To fix:
pip uninstall gradio
pip install gradio==3.19.0

The gallery icons again work by switching the active character.

### Logs

```shell
none
```

### System Info

```shell
Windows 10, Edge browser.
```

**Comment by ye7iaserag** [comment]
Yep, same here, a work around for now is using the character tab

**Comment by thedarthvader2000** [comment]
> Yep, same here, a work around for now is using the character tab

Do yall  know why oobabooga recently started making a bunch of mini commits/changes to the repo? I cant even run the Colab bc of issues like the file names changing ---or im retarded
<img width="912" alt="image" src="https://user-images.githubusercontent.com/125932943/228653501-9aa67882-9fb6-48fa-a82f-cf3330eb6e57.png">
