### ISSUE TITLE
Add support for Transformers 4.45.1

### ISSUE THREAD

**Issue by BovineOverlord** [oobabooga/text-generation-webui#6409]
The new models coming out are built on 4.45.1. Attempting to run on 4.44 returns the error "Exception: data did not match any variant of untagged enum ModelWrapper at line 277218 column 3". 

An update to current transformers would correct this.

**Comment by Gee1111** [comment]
i cant load Llama 3.2 11B (Vision Model).. i think its becouse of the old transformer version. need the update ASAP :D

**Comment by GraveUypo** [comment]
Yup, even llama 3.2 1b doesn't work. which is a shame, it's actually quite useful with how damn quick it is. it writes like a whole book in a second

**Comment by oobabooga** [comment]
Updated in v1.15!

**Comment by cal066** [comment]
@oobabooga I now get errors like:

  File "text-generation-webui/modules/text_generation.py", line 410, in generate_reply_HF
    new_content = get_reply_from_output_ids(output, state, starting_from=starting_from)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "text-generation-webui/modules/text_generation.py", line 271, in get_reply_from_output_ids
    reply = decode(output_ids[starting_from:], state['skip_special_tokens'] if state else True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "text-generation-webui/modules/text_generation.py", line 181, in decode
    return shared.tokenizer.decode(output_ids, skip_special_tokens=skip_special_tokens)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "text-generation-webui/download-model.venv/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 4007, in decode
    return self._decode(
           ^^^^^^^^^^^^^
  File "text-generation-webui/download-model.venv/lib/python3.11/site-packages/transformers/tokenization_utils_fast.py", line 654, in _decode
    text = self._tokenizer.decode(token_ids, skip_special_tokens=skip_special_tokens)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: out of range integral type conversion attempted
Output generated in 1.18 seconds (5.93 tokens/s, 7 tokens, context 2258, seed 1969261942)

Out of curiosity, I printed the failed token_ids in tokenization_utils_fast.py and got:
Token overflow [-36028792732385280]
Token overflow [72340172838076673]

Any ideas?

**Comment by cal066** [comment]
Odd, the problem seems to be gone, just as mysteriously as it came.
