### ISSUE TITLE
upgrade to gradio 5.0

### ISSUE THREAD

**Issue by AK391** [oobabooga/text-generation-webui#6455]
gradio 5.0 is out: https://huggingface.co/blog/gradio-5

would be great to upgrade to the latest stable version 5.0.1

**Comment by Touch-Night** [comment]
Looks great

**Comment by Touch-Night** [comment]
![image](https://github.com/user-attachments/assets/b8c285c7-d047-4b44-ab3f-93abfb61c586)
![image](https://github.com/user-attachments/assets/9ea499f0-4b27-4f41-8f79-daececfaa078)
![image](https://github.com/user-attachments/assets/9f3e60b2-7eca-4197-92d1-118c49572250)

**Comment by oobabooga** [comment]
Indeed dark theme gets ignored and the CSS in the chat UI is completely broken.

**Comment by oobabooga** [comment]
I don't think I'll make this update. Too many fixes are necessary.

**Comment by AK391** [comment]
@oobabooga the dark theme is now respected and we are happy to help with other issues, cc: @abidlabs
