### ISSUE TITLE
Multiline support for chat

### ISSUE THREAD

**Issue by KutsuyaYuki** [oobabooga/text-generation-webui#648]
**Description**

The webui currently does not output in multiple lines with --chat. It seems to indicate that the chat wants to, but just stops at the first new line. I have attached a screenshot.

**Additional Context**

![image](https://user-images.githubusercontent.com/17732178/228654221-428a4617-fe2d-4853-9a22-b59b7a1f4649.png)

**Comment by oobabooga** [comment]
It works for me

![newline](https://user-images.githubusercontent.com/112222186/228723197-1bdb71cb-0d29-49cb-bb42-01fffbb8469a.png)

**Comment by KutsuyaYuki** [comment]
I figured I had to edit the parameter where you put the original prompt
