### ISSUE TITLE
problems with gradio api

### ISSUE THREAD

**Issue by SwannSchilling** [oobabooga/text-generation-webui#65]
When using python server.py --chat and the recommended Python snippet, the response is empty most of the time.
Or the bot answer is missing.
Any idea on how to get this fixed?

**Comment by oobabooga** [comment]
Thanks for the encouragement. Gradio is not the most robust thing in the world, sometimes it returns empty replies but if you send the request again it will respond.

**Comment by SwannSchilling** [comment]
Ah, OK... I did not know about that, I have little experience experience with Gradio.
Is there a way to extract the chat output in some way?
I would like to send it to a TTS engine!

**Comment by oobabooga** [comment]
The best way to do this would be to write an extension: https://github.com/oobabooga/text-generation-webui/wiki/Extensions

Just write the body of `output_modifier`. It should return the same input string, but before that, it should convert the string to audio and play it.

See here an example, it's very easy (much easier than working with the API): https://github.com/oobabooga/text-generation-webui/blob/main/extensions/example/script.py

**Comment by SwannSchilling** [comment]
Thank you so much for you help and for this great interface! The Automatic1111 for LLMs!!
I will take a look and I guess this will resolve my issue!

**Comment by oobabooga** [comment]
No problem, if you still have problems with the API, feel free to reopen this issue or to create another one.
