### ISSUE TITLE
Drop 8-bit support & dependency for bitsandbytes

### ISSUE THREAD

**Issue by CatTimson** [oobabooga/text-generation-webui#651]
I wanted to touch base about a possible improvement that could make our lives easier. It seems to me that 8-bit mode isn't really used much these days, and my understanding most use cases are 16/4/3/2 bit modes. I'm thinking we could drop 8-bit support altogether, as it's not really doing much for us bu this bitsandbytes dependency that's been causing me some headaches. I'm not even using it, but it's hardcoded in the app and keeps throwing errors my way. I've noticed other users experiencing the same issue, so it might be worth it to just remove the dependency entirely.

I reckon that ditching both 8-bit support and the bitsandbytes dependency would make the app more efficient and user-friendly, making it a win-win for everyone.

**Comment by oobabooga** [comment]
8-bit is integrated into transformers and can be used to instantly reduce the VRAM usage of any model by half. I use it every day.
