### ISSUE TITLE
Proposal: rename text-generation-webui to textgen or textgen-ui

### ISSUE THREAD

**Issue by tensiondriven** [oobabooga/text-generation-webui#653]
**Description**

I am loving text-generation-webui.  I'm also finding that the name is very general, which I can appriciate given that it seeks to be a general purpose solution to text generation (fitting), however because it is split on dashes, and because all of the words in the name are so general, and use terms related to LLM's for other libraries, I often get search results for things like Stable Diffusion, even when searching specifically for text-generation-webui.

Without resorting to a "branded" name (like KoboldAI does), is there a way we can change the name to something that is more specific, or distinct?  And easier to type?  I think this would be a big advantage over the long term.

This might not be popular in the immediate term - it would surely cause some degree of disruption - but perhaps it is worth it.  If there is a decision to do this, the sooner seems better.

FWIW, on my local system, I've already taken to renaming `text-generation-webui` to `textgen` where I can, and it's already saving my carpal tunnels.

Just wanted to run this idea by you and the community @oobabooga

**Comment by oobabooga** [comment]
This project is inspired by [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui), hence the name.

**Comment by tensiondriven** [comment]
I understand the naming :) It was worth a shot.  Thanks for the reply!
