### ISSUE TITLE
Input should automatically clear after sending message in chat mode

### ISSUE THREAD

**Issue by eiery** [oobabooga/text-generation-webui#666]
**Description**

In chat mode currently the text in the input box is retained after I press Enter on my keyboard or hit the Generate key. I have to delete the text manually to continue the conversation. The box should clear itself like any other chat app after the message is sent to the AI.

![Screenshot from 2023-03-30 17-41-28](https://user-images.githubusercontent.com/19350831/228971037-8ef6582d-f300-483f-98d2-5f12e84a195d.png)

This should be a pretty simple fix and I can even have a go at it assuming this behavior isn't intentional.

**Comment by oobabooga** [comment]
It does clear after the message is generated. If the event for clearing the input field happens before the text generation event, the latter will receive an empty string as input.

If you can find a clean workaround, feel free to submit a PR. I agree that it's weird for the sent message to not disappear immediately.

**Comment by eiery** [comment]
Ah, I see it now. I always manually cleared the box while the message was generating so I never saw it clear itself.

**Comment by bmoconno** [comment]
I just put in a PR (#715)  that solves this issue, I tested it, but it's work checking yourselves.

**Comment by eiery** [comment]
The PR is working well for me and I see it's merged already. Thanks!
