### ISSUE TITLE
Proper text-streaming support via transformers library

### ISSUE THREAD

**Issue by Titaniumtown** [oobabooga/text-generation-webui#669]
The transfomers library just merged support for token streaming (<https://github.com/huggingface/transformers/pull/22449>). Maybe this could be used instead of the implementation in this project?

**Comment by oobabooga** [comment]
I'm comfortable with the current streaming implementation here and believe that it cannot be faster.

**Comment by Titaniumtown** [comment]
Wouldn't it be more ideal to rely on transformers' implementation anyway from a code simplicity standpoint? Why replicate the effort.
