### ISSUE TITLE
Error no file named pytorch_model.bin

### ISSUE THREAD

**Issue by gruevy** [oobabooga/text-generation-webui#674]
### Describe the bug

I downloaded ozcur_alpaca-native-4bit from HF with the model download script (entering ozcur/alpaca-native-4bit) and ran the webui script like this:

.\start-webui.bat --wbits 4 --groupsize 128

I get the same error with or without those flags. 

I tried deleting everything and reinstalling from from the latest one click installer twice. I tried running the install script to update. I also tried going into the text-generation-webui directory and running pip install -r requirements.txt. I found an older issue that was closed a month ago that looked similar, but the fix didn't work for me and I think this is a new bug. 

I get this error each time I run the install script, somewhere in the middle of its operations:

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.24.2 which is incompatible.

I'm not sure how to tell if that's related. The script completes successfully and I can run the webui.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

install from one-click installer
acquire the ozcur_alpaca-native-4bit
.\start-webui.bat --wbits 4 --groupsize 128
select the model

### Logs

```shell
PS D:\stable diffusion\oobabooga> .\start-webui.bat --wbits 4 --groupsize 128
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: Loading binary D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
The following models are available:

1. alpaca-30b-4bit-128g.safetensors
2. facebook_opt-6.7b
3. llama-7b-4bit-128g
4. ozcur_alpaca-native-4bit

Which one do you want to load? 1-4

4

Loading ozcur_alpaca-native-4bit...
Auto-assiging --gpu-memory 23 for your GPU to try to prevent out-of-memory errors.
You can manually set other values.
Traceback (most recent call last):
  File "D:\stable diffusion\oobabooga\text-generation-webui\server.py", line 274, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\stable diffusion\oobabooga\text-generation-webui\modules\models.py", line 159, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "D:\stable diffusion\oobabooga\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2287, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models\ozcur_alpaca-native-4bit.
Press any key to continue . . .
PS D:\stable diffusion\oobabooga>
```

### System Info

```shell
win11, 4090
```

**Comment by oobabooga** [comment]
> .\start-webui.bat --wbits 4 --groupsize 128

This doesn't work. You have to manually edit the start-webui.bat script and add the `--wbits 4 --groupsize 128` flags to the `python server.py ...` command.

**Comment by gruevy** [comment]
Crap that was it. Thanks, and sorry for wasting your time.
