### ISSUE TITLE
Model Use

### ISSUE THREAD

**Issue by Ege-P** [oobabooga/text-generation-webui#687]
I downloaded the GPT-4chan files from the link and followed the steps provided. But couldn't manage to use the model. When I try to start the AI and try to use GPT-4chan, I get this error: 

Traceback (most recent call last):
  File "D:\AIChatUI\text-generation-webui\server.py", line 274, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\AIChatUI\text-generation-webui\modules\models.py", line 170, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 2322, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models\gpt4chan_model_float16.

I can see this is because there is no ***.bin file. In the link for GPT-4chan, it downloads these files:
- gpt4chan_model_float16_meta.xml
- gpt4chan_model_float16_meta.sqlite
- gpt4chan_model_float16_files.xml
- pytorch_model (file)
- The pytorch_model file contains >
- archive (file) that contains >
- data.pkl
- version
- data (file)
data file contains > 
files named as numbers from 0-286 (which is probably the model since its 11gb)

I checked the model I used (that downloaded auto when I first try to use this WebUI) and see the .bin files for the model.
So, I'm not sure what to do at this point.

**Comment by jllllll** [comment]
The pytorch_model file is the .bin that it is looking for. If there isn't a .bin in the file name, then try adding it.

**Comment by oobabooga** [comment]
This works for me

```
python server.py --model gpt4chan_model_float16
```

These are my files

```
$ ls models/gpt4chan_model_float16/
config.json
gpt4chan_model_float16_meta.sqlite
gpt4chan_model_float16_meta.xml
pytorch_model.bin

$ ls models/gpt-j-6B
added_tokens.json
config.json
merges.txt
special_tokens_map.json
tokenizer_config.json
tokenizer.json
vocab.json
```

Are yours identical?

**Comment by Ege-P** [comment]
![gpt4chan_model_float16 1 04 2023 07_52_05](https://user-images.githubusercontent.com/64746057/229266306-8ce3d67f-a4dc-4a2d-8b12-1e137c1c515e.png)

This is what I have and I tried adding .bin at the end of the file but no use.

I also tried to download from the console (from micromamba-cmd.bat) but I get this error:
python: can't open file 'D:\\AIChatUI\\server.py': [Errno 2] No such file or directory

**Comment by jllllll** [comment]
Did you extract pytorch_model? That is the model file, which is an archive. If you extracted it, then you will need to re-download it.
Also, make sure that you followed all of the instructions for setting it up. In particular, you need the tokenizer files from GPT-J.

**Comment by Ege-P** [comment]
Can you tell me a bit edtailed? In the direct link, I see 4 files and I assume I need to download them. I got the singular files (xml etc.) and pytorch_model.zip (and assumed I need to unzip it.)
And later, in steps it says I need to download GPT-J 6B's tokenizer files but also says (they will be automatically detected when you attempt to load GPT-4chan). So I thought the process is automatic.

**Comment by jllllll** [comment]
pytorch_model.zip needs to be renamed to pytorch_model.bin.

As for the gptj files, it detects them automatically if they are there. You still need to download them. You can use the download-model script to do this.
At the top of the script, change `SET TextOnly=False` to `SET TextOnly=True`. Then run the script and choose the last option (none of the above). Then, when it asks you to input the model name, use `EleutherAI/gpt-j-6B`. That should download the require tokenizer files. If the files are not detected, you can move them out of the gptj folder and into gpt-4chan folder.

**Comment by Ege-P** [comment]
Ok, I manage to open... that "python download-model.py EleutherAI/gpt-j-6B --text-only" is not working. (I don't have the gpt-j6b model, if that's needed), so I go to HF page and guessed the files I need to download, a few tries and it worked at the end (hopefully nothing will be breaks after)
