### ISSUE TITLE
How do you load a fine tuned model that used PEFT?

### ISSUE THREAD

**Issue by pauldog** [oobabooga/text-generation-webui#692]
The fine tune script https://github.com/tloen/alpaca-lora/blob/main/finetune.py saves it in terms of extra weights.

You need the PEFT library to add these fine tuned weights to the model.

Can this be used with text-generation-webui?

**Comment by oobabooga** [comment]
You can both use and train LoRAs in the web ui https://github.com/oobabooga/text-generation-webui/wiki/Using-LoRAs

**Comment by pauldog** [comment]
That appears to be working. (Well it's not giving any errors anyway.)

Do you know what is the right format of a prompt you have to do for an Alpaca fined tuned model:

Do you have to do a prompt like this:

```
### Instruction:
Tell me the capital of France?

### Response:
```

**Comment by pauldog** [comment]
BTW it would be cool to have a button which output the combined model+lora as a single model.bin file. Is this at all possible?
