### ISSUE TITLE
LlaMA model... python problems

### ISSUE THREAD

**Issue by Ege-P** [oobabooga/text-generation-webui#696]
I was trying to include the Llama.cpp model (because looks like you can run miku.gg by using Llama models with this webui) but I'm once again stuck...
I downloaded the Llama model weights in models folder as written in the steps.
After that, I try to work "python3 -m pip install torch numpy sentencepiece" command but I get this error: Python couldn't found.

**Comment by catalpaaa** [comment]
what steps are you following

**Comment by Ege-P** [comment]
https://github.com/oobabooga/text-generation-webui/wiki/llama.cpp-models
This one

**Comment by jllllll** [comment]
"python3 -m pip install torch numpy sentencepiece" is not in those instructions. Everything needed for llama.cpp models is already included with the webui.

**Comment by Ege-P** [comment]
Huh... it directly sends me to #Usage link at step-2 and says follow that...

**Comment by Ege-P** [comment]
..I'm still stuupid... Can you help me?... I couldnt figure it out how to make that ggml model...

**Comment by jllllll** [comment]
> ..I'm still stuupid... Can you help me?... I couldnt figure it out how to make that ggml model...

I've never made a ggml model before. I just downloaded mine as my hardware is too old for that sort of thing. The only models I can legally link you to are these: https://huggingface.co/models?sort=downloads&search=ggml

**Comment by Ege-P** [comment]
So uhhh, this didnt work out... I download the ggml model but... UI doesn't start

**Comment by jllllll** [comment]
> So uhhh, this didnt work out... I download the ggml model but... UI doesn't start

Are there any errors?

**Comment by Ege-P** [comment]
1- When ggml file is in separate folder > 
Traceback (most recent call last):
  File "D:\AIChatUI\text-generation-webui\server.py", line 275, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\AIChatUI\text-generation-webui\modules\models.py", line 176, in load_model
    tokenizer = AutoTokenizer.from_pretrained(Path(f"{shared.args.model_dir}/{shared.model_name}/"))
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 691, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.

2- When I try to load ggml instead > 
Traceback (most recent call last):
  File "D:\AIChatUI\text-generation-webui\server.py", line 275, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\AIChatUI\text-generation-webui\modules\models.py", line 170, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 908, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\utils\hub.py", line 380, in cached_file
    raise EnvironmentError(
OSError: models\GGML-q4_0 does not appear to have a file named config.json. Checkout 'https://huggingface.co/models\GGML-q4_0/None' for available files.


3- When both in the same folder (with decapoda-research_llama-7b-hf) >
Traceback (most recent call last):
  File "D:\AIChatUI\text-generation-webui\server.py", line 275, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\AIChatUI\text-generation-webui\modules\models.py", line 176, in load_model
    tokenizer = AutoTokenizer.from_pretrained(Path(f"{shared.args.model_dir}/{shared.model_name}/"))
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 691, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LLaMATokenizer does not exist or is not currently imported.

**Comment by jllllll** [comment]
Yeah, I got similar errors when selecting a ggml model in the model selection menu. At the moment, it seems that in order for webui to load a ggml model correctly, it must be done through the `--model` argument. Here is an example script for loading `alpaca-30B-ggml`:
```
@echo off

@echo Starting the web UI...

cd /D "%~dp0"

set MAMBA_ROOT_PREFIX=%cd%\installer_files\mamba
set INSTALL_ENV_DIR=%cd%\installer_files\env

if not exist "%MAMBA_ROOT_PREFIX%\condabin\micromamba.bat" (
  call "%MAMBA_ROOT_PREFIX%\micromamba.exe" shell hook >nul 2>&1
)
call "%MAMBA_ROOT_PREFIX%\condabin\micromamba.bat" activate "%INSTALL_ENV_DIR%" || ( echo MicroMamba hook not found. && goto end )
cd text-generation-webui

call python server.py --model alpaca-30B-ggml

:end
pause
```
Make sure that the model you downloaded is in it's own folder, then replace `alpaca-30B-ggml` with the folder name for the model.

**Comment by Ege-P** [comment]
Nope, didnt worked... let me try another ggml model...
(The error if you want to)

Traceback (most recent call last):
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 628, in _get_config_dict
    resolved_config_file = cached_file(
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\utils\hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "D:\AIChatUI\installer_files\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 112, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\AIChatUI\installer_files\env\lib\site-packages\huggingface_hub\utils\_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'models\gpt-j-ggml-model-q4_0'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AIChatUI\text-generation-webui\server.py", line 275, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\AIChatUI\text-generation-webui\modules\models.py", line 170, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\models\auto\auto_factory.py", line 441, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\models\auto\configuration_auto.py", line 908, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 573, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\AIChatUI\installer_files\env\lib\site-packages\transformers\configuration_utils.py", line 649, in _get_config_dict
    raise EnvironmentError(
OSError: Can't load the configuration of 'models\gpt-j-ggml-model-q4_0'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'models\gpt-j-ggml-model-q4_0' is the correct path to a directory containing a config.json file

**Comment by jllllll** [comment]
Don't include `models\` in the script. Webui will automatically search the models folder for the name that you enter.

**Comment by Ege-P** [comment]
What you mean? This is what's in the start:

call python server.py --auto-devices --cai-chat --model gpt-j-ggml-model-q4_0

**Comment by jllllll** [comment]
> What you mean? This is what's in the start:
> 
> call python server.py --auto-devices --cai-chat --model gpt-j-ggml-model-q4_0

Just making sure.

**Comment by Ege-P** [comment]
I think I'm getting closer...
I add config.json file. gave less error. Now giving: 
Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory models\GGML_q4_0.

Can I change the model name to pytorch_model.bin?

**Comment by jllllll** [comment]
Rename the .bin model file to include ggml at the beginning of the name. That is how webui currently identifies ggml models.

**Comment by Ege-P** [comment]
D:\AIChatUI\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: D:\AIChatUI\installer_files\env did not contain cudart64_110.dll as expected! Searching further paths...
  warn(msg)
D:\AIChatUI\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C:/Users/ege/.dotnet/tools')}
  warn(msg)
CUDA SETUP: CUDA runtime path found: D:\AIChatUI\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary D:\AIChatUI\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading GGML_q4_0...
llama.cpp weights detected: models\GGML_q4_0\ggml-model-q4_0.bin

llama_model_load: loading model from 'models\GGML_q4_0\ggml-model-q4_0.bin' - please wait ...
llama_model_load: invalid model file 'models\GGML_q4_0\ggml-model-q4_0.bin' (too old, regenerate your model files or convert them with convert-unversioned-ggml-to-ggml.py!)
llama_init_from_file: failed to load model

**Comment by jllllll** [comment]
That model is probably outdated then. There are instructions on the llama.cpp github for converting it, but it would probably be easier to find a different model.

**Comment by Ege-P** [comment]
I tried with another model but same error. In the instructions, there is a converter thingy but I'm getting python not found error with that

**Comment by jllllll** [comment]
I'll write a script real quick to do it.

**Comment by jllllll** [comment]
[convert-unversioned-ggml-webui.txt](https://github.com/oobabooga/text-generation-webui/files/11129235/convert-unversioned-ggml-webui.txt)

1. Download file above, place it next to the webui scripts and change .txt to .bat
2. Download this file and place it next to the script: https://huggingface.co/decapoda-research/llama-7b-hf/blob/main/tokenizer.model
3. Change the MODEL_NAME variable at the top of the script to the name of the model you want to convert.
4. Run the script and it should convert it.

**Comment by Ege-P** [comment]
D:\AIChatUI\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: D:\AIChatUI\installer_files\env did not contain cudart64_110.dll as expected! Searching further paths...
  warn(msg)
D:\AIChatUI\installer_files\env\lib\site-packages\bitsandbytes\cuda_setup\main.py:141: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C:/Users/ege/.dotnet/tools')}
  warn(msg)
CUDA SETUP: CUDA runtime path found: D:\AIChatUI\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary D:\AIChatUI\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading GGML_q4_0...
llama.cpp weights detected: models\GGML_q4_0\ggml-model-q4_0.bin

llama_model_load: loading model from 'models\GGML_q4_0\ggml-model-q4_0.bin' - please wait ...
llama_model_load: invalid model file 'models\GGML_q4_0\ggml-model-q4_0.bin' (too old, regenerate your model files or convert them with convert-unversioned-ggml-to-ggml.py!)
llama_init_from_file: failed to load model

**Comment by jllllll** [comment]
Check to be sure that the new .bin file wasn't renamed.

**Comment by jllllll** [comment]
I tried converting that gpt-j-ggml-model-q4_0 model, but it seems to be incompatible with the conversion script. I then tried converting one of the alpaca models and it worked, but was still out of date and needs further conversion. I'm just going to message you a link to better models. Wish llama.cpp would stop dropping support for model formats when they keep updating them.

**Comment by Ege-P** [comment]
Well, Miku.gg claims any Llama or alpaca model run on this UI should be able to create an gradio.live endpoint that makes miku work on this UI (if I understand correctly), so I'll just keep try some models

**Comment by jllllll** [comment]
I got mine from here: https://rentry.org/nur779

**Comment by Nondzu** [comment]
> 

Bro, if you want buid quantized model from readme llama.cpp you must use python 3.10 or 3.9 
![image](https://user-images.githubusercontent.com/20000097/229349962-cf33665f-eba8-4f22-bfb7-22828db165f6.png)

Use conda to run 3.10 and it will work fine
