### ISSUE TITLE
Use subset of training data.

### ISSUE THREAD

**Issue by pauldog** [oobabooga/text-generation-webui#705]
**Description**

If you fine-tuning dataset consists of 50k question/answer pairs. Perhaps you only want to use 25% of these. So that would be nice to have a parameter option for this.

Then the epochs would work the same, so for example 3 epochs would use the SAME 25% each time.

This might be a time saver so you don't have to make a smaller training data json. You could use a massive one and only use a random percent of it.

Is this useful or not?

**Comment by oobabooga** [comment]
Just change the input file

**Comment by pauldog** [comment]
Sure, but this is for if you want to try a quick run with 1% of the data for example.
