### ISSUE TITLE
Colab torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by Enferlain** [oobabooga/text-generation-webui#71]
Wanted to test on colab (got windows and amd) but it either dies before generation, or stops midway with this

> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 14.76 GiB total capacity; 13.43 GiB already allocated; 17.88 MiB free; 13.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

![image](https://user-images.githubusercontent.com/15861396/218285170-48b80e69-ac1b-48a9-8221-3a58c26710e4.png)

Usage is already at like 95% and I haven't even done anything yet. What do sadge?

**Comment by oobabooga** [comment]
On Colab this can happen if you are using a character with a very large description. The best workaround is to check the "load in 8bit" option, which will reduce the GPU RAM usage by half.

The 1-click installer should bow work on windows + amd, by the way: 

https://github.com/oobabooga/text-generation-webui/releases/download/installers/oobabooga-windows.zip

**Comment by Enferlain** [comment]
Oh yeah, I'll give that a go, saw you mention it on reddit when I was looking stuff up.

I tried locally first but rocm doesn't exist on windows so the amd installer fails

![image](https://user-images.githubusercontent.com/15861396/218288339-1c985e65-1df6-406a-b48c-0194f19f1540.png)
![image](https://user-images.githubusercontent.com/15861396/218288363-4e97109e-26c9-49f6-97f8-87a38ce80ef6.png)

Forgot about the cpu installer, gonna give it a go and see how it runs

**Comment by Spencer-Dawson** [comment]
Which model? Obviously model size makes a difference. CPU performance is miserable IME just FYI.

**Comment by Spencer-Dawson** [comment]
ROCm on Windows is completely unsupported by AMD just FYI. I've seen people claim they got it working through some hacks, but I wouldn't even recommend trying to get it to work; even if you succeed it could break at any time and you'll find almost nobody willing to help you with it.

**Comment by oobabooga** [comment]
I had no idea ROCm was not supported on Windows. I hope they will fix it soon.

**Comment by Enferlain** [comment]
Pygmalion6B.

Yeah I'm not expecting a lot from CPU, just wanna check it out

Any idea what this is? I used cpu install but it's looking for cuda?
![image](https://user-images.githubusercontent.com/15861396/218288752-2af6663e-6bc6-4382-abbe-0d1249945d09.png)

Also yeah I tried everything to get rocm to work for automatic webui but there's no point. Gonna prob dual boot linux until I switch gpus.

**Comment by Enferlain** [comment]
> I had no idea ROCm was not supported on Windows. I hope they will fix it soon.

Would be nice, ppl have been asking for years but maybe all this ai shit can get them to finally do something for compute on windows

**Comment by oobabooga** [comment]
@Enferlain make sure to edit the webui-start.bat script and add the --cpu flag to the `python server.py` command

**Comment by Enferlain** [comment]
Thanks

Holy
![image](https://user-images.githubusercontent.com/15861396/218289104-979d7b0c-b948-4e5f-9f43-9a0284c320ed.png)
![image](https://user-images.githubusercontent.com/15861396/218289105-3f275785-b7a8-4c01-9e51-48e0ea18db21.png)

Anyways thanks for helping, cool stuff
