### ISSUE TITLE
ggml llama crash at 'typing...' when using characters

### ISSUE THREAD

**Issue by Enferlain** [oobabooga/text-generation-webui#713]
Downloaded stuff from here for testing https://rentry.org/nur779

CPU goes up to 60% for like 15 seconds then it dies. If I don't load any char it works with the default settings, but it's really schizo and says random stuff as if temps are maxed out. Is that normal behavior atm? I checked opened issues but didn't really find anything, but it was only updated like 20 hours ago so makes sense. Just wanted to check anyways

**Comment by horenbergerb** [comment]
Sounds similar to #690?

**Comment by Teragron** [comment]
I'm also having a similar problem, but for me the crash occurrs after 4-5 conversations w/out loading any character. When that happens i get the following message in the command line : `Press any key to continue . . .`
When i load any characters, the same thing happens after 1-2 conversation pairs.

**Comment by noprotocolunit** [comment]
I'm seeing similar behavior almost regardless of model. It seems to be tied to ggml llama specifically and the behavior is much as folks here have described. Non-ggml models aren't affected for me (I can run regular llama 7b 4-bit just fine).

**Comment by Enferlain** [comment]
The crashing probably has something to do with this

![image](https://user-images.githubusercontent.com/15861396/229375654-7f34279e-0c03-44aa-8a0b-077d5f584a40.png)

Maybe try other ggml models in the link, and see how it goes. I'll go back to gpu for now, but if this gets figured out that will be huge for Windows users without nvidia cards

**Comment by horenbergerb** [comment]
I made an upstream issue that is probably related to this:
https://github.com/thomasantony/llamacpp-python/issues/13
Looks like there's already a PR that might let us boost the context to 2048. That will push the problem further out. They're still investigating the actual segfault when you fill up the context, though.

**Comment by thomasantony** [comment]
v0.1.13 adds support for context swapping and going past the configured context size. 

https://github.com/thomasantony/llamacpp-python/releases/tag/v0.1.13

Please try it out!

**Comment by horenbergerb** [comment]
@thomasantony That's awesome! Very excited to hear it! I'm on vacation through the weekend but I will be playing with this ASAP

**Comment by Enferlain** [comment]
Thanks for the update.

Meanwhile [this comment](https://github.com/oobabooga/text-generation-webui/issues/912#issuecomment-1500961747) helped me get the current iteration run, but now instead of crashing my CPU is stuck on 100% and the bot is just stuck at "Is typing..." forever.

```
Loading gpt4-x-alpaca-13b-native-4bit-128g-ggml...
llama.cpp weights detected: models\gpt4-x-alpaca-13b-native-4bit-128g-ggml\ggml-model-q4_1.bin

llama_model_load: loading model from 'models\gpt4-x-alpaca-13b-native-4bit-128g-ggml\ggml-model-q4_1.bin' - please wait ...
llama_model_load: GPTQ model detected - are you sure n_parts should be 2? we normally expect it to be 1
llama_model_load: use '--n_parts 1' if necessary
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx   = 2048
llama_model_load: n_embd  = 5120
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 40
llama_model_load: n_layer = 40
llama_model_load: n_rot   = 128
llama_model_load: f16     = 4
llama_model_load: n_ff    = 13824
llama_model_load: n_parts = 2
llama_model_load: type    = 2
llama_model_load: ggml map size = 9702.04 MB
llama_model_load: ggml ctx size = 101.25 KB
llama_model_load: mem required  = 11750.14 MB (+ 3216.00 MB per state)
llama_model_load: loading tensors from 'models\gpt4-x-alpaca-13b-native-4bit-128g-ggml\ggml-model-q4_1.bin'
llama_model_load: model size =  9701.60 MB / num tensors = 363
llama_init_from_file: kv self size  = 3200.00 MB
AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
```

**Comment by jllllll** [comment]
> Thanks for the update.
> 
> Meanwhile [this comment](https://github.com/oobabooga/text-generation-webui/issues/912#issuecomment-1500961747) helped me get the current iteration run, but now instead of crashing my CPU is stuck on 100% and the bot is just stuck at "Is typing..." forever.
> 
> ```
> Loading gpt4-x-alpaca-13b-native-4bit-128g-ggml...
> llama.cpp weights detected: models\gpt4-x-alpaca-13b-native-4bit-128g-ggml\ggml-model-q4_1.bin
> 
> llama_model_load: loading model from 'models\gpt4-x-alpaca-13b-native-4bit-128g-ggml\ggml-model-q4_1.bin' - please wait ...
> llama_model_load: GPTQ model detected - are you sure n_parts should be 2? we normally expect it to be 1
> llama_model_load: use '--n_parts 1' if necessary
> llama_model_load: n_vocab = 32001
> llama_model_load: n_ctx   = 2048
> llama_model_load: n_embd  = 5120
> llama_model_load: n_mult  = 256
> llama_model_load: n_head  = 40
> llama_model_load: n_layer = 40
> llama_model_load: n_rot   = 128
> llama_model_load: f16     = 4
> llama_model_load: n_ff    = 13824
> llama_model_load: n_parts = 2
> llama_model_load: type    = 2
> llama_model_load: ggml map size = 9702.04 MB
> llama_model_load: ggml ctx size = 101.25 KB
> llama_model_load: mem required  = 11750.14 MB (+ 3216.00 MB per state)
> llama_model_load: loading tensors from 'models\gpt4-x-alpaca-13b-native-4bit-128g-ggml\ggml-model-q4_1.bin'
> llama_model_load: model size =  9701.60 MB / num tensors = 363
> llama_init_from_file: kv self size  = 3200.00 MB
> AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
> ```
> 
> Doesn't happen when using the default assistant, so it has to be something about characters

It looks like it is trying to load the model in 2 parts. That model only has one part, so this is a bug in llama-cpp-python's model part detection. Try a wheel from here: https://github.com/abetlen/llama-cpp-python/suites/12103058133/artifacts/637563917

Same instructions as the previous one. If it continues to happen, make an issue on the llama-cpp-python repo about that model breaking the part auto-detection. Should probably do that anyway given that I'm pretty sure the auto-detection hasn't been updated since that wheel was made.

**Comment by Enferlain** [comment]
The other ones throw "not supported wheel on this platform" maybe the model is just scuffed, gonna try some other ones, thanks

**Comment by jllllll** [comment]
> The other ones throw "not supported wheel on this platform" maybe the model is just scuffed, gonna try some other ones, thanks

The model definitely works, it's just an issue with llama-cpp-python thinking there are 2 model .bin files when there is only one.

**Comment by Enferlain** [comment]
Yeah it's just the 1 ggml file. Also tried a different model just now and the basic assistant setting can get me replies, it just borks after I load up a character with way more context. (also are these speeds normal?)

> This is a conversation with your Assistant. The Assistant is very helpful and is eager to chat with you and answer your questions.
> Assistant: Hello there!
> You: Hey there
> Assistant:
> --------------------
> 
> Output generated in 41.73 seconds (0.24 tokens/s, 10 tokens, context 44)
> 
> 
> This is a conversation with your Assistant. The Assistant is very helpful and is eager to chat with you and answer your questions.
> Assistant: Hello there!
> You: Hey there
> Assistant: How can I help you today?
> You: Just testing how things are running, so I don't need any assistance other than exchanging a few texts
> Assistant:
> --------------------
> 
> Output generated in 85.03 seconds (0.22 tokens/s, 19 tokens, context 81)

Models I tried so far are [this](https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g/tree/main/gpt4-x-alpaca-13b-ggml-q4_1-from-gptq-4bit-128g) and the 13B llama from [here ](https://rentry.org/nur779)

Also tried koboldcpp/sillytavern and there the character seems to work but I don't like that you can't stop generating after the ai starts a new line so it's not really ideal either when it keeps spending the 200 tokens to write a conversation for you.

**Comment by jllllll** [comment]
I think that huggingface post was talking about AMD GPU.

Those speeds are definitely unusual for a 13b ggml model. It may be an issue with either llama-cpp-python or text-generation-webui. I would try using [llama.cpp](https://github.com/ggerganov/llama.cpp) directly and see what speeds you get.

**Comment by Enferlain** [comment]
@jllllll Wasn't able to launch llama.cpp, so couldn't check. I can run the models in koboldcpp, so they definitely work, but for some reason I think my ooba setup is trying to run the models on cpu like before llama.cpp was a thing, so it's not dead it just takes forever at full 100% cpu load.

Like shouldn't the ram be more if it was working normally?

![image](https://user-images.githubusercontent.com/15861396/230798945-1a1742d2-b484-4e0b-8576-78cde254f4ec.png)

**Comment by jllllll** [comment]
@Enferlain The memory listing there is wrong. For some reason, the program does not report it's RAM usage correctly to Task Manager. You have to look at the performance tab to see the actual RAM usage.

**Comment by Enferlain** [comment]
Yeah you're right, figured that out after. It was using ram correctly, I just also had koboldcpp and an emulator running, and neither of them showed the full allocation so I got confused.

Just to make sure about the entire process I'm dealing with

- So I download the windows installer zip, and run the installer
- After this, I put the models in the folder, and try to run the webui, resulting in "llama.cpp not found"
- I download the wheel you sent me and use it in miniconda
- After this the webui opens and seemingly works
- I try testing with everything default, and I get speeds like this "Output generated in 85.03 seconds (0.22 tokens/s, 19 tokens, context 81)"
- Lastly, I load up a detailed character and try generating. CPU stuck at 100 with seemingly 0 progress in generation


I'm gonna take a break because I feel like I tried everything. I'll make sure to update about it if I do find out what causes this issue since I recall reading comments about bad performance before, but maybe someone else figures them out as well.

**Comment by Enferlain** [comment]
Ok, with the latest update everything works. It's really slow still, more than it should be I think, but the issue in the title has been eliminated.

There is an issue open about it here, I have the same experience

https://github.com/oobabooga/text-generation-webui/issues/1026
