### ISSUE TITLE
TypeError: make_quant() got an unexpected keyword argument 'faster'

### ISSUE THREAD

**Issue by boricuapab** [oobabooga/text-generation-webui#716]
### Describe the bug

Unable to load with ozcur_alpaca-native-4bit model.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I changed the start-webui bat with these flags

call python server.py --auto-devices --cai-chat --model ozcur_alpaca-native-4bit --wbits 4 --groupsize 128 --no-stream --extension sd_api_pictures send_pictures --listen-port 7861

### Screenshot

![gptqLoaderIssue](https://user-images.githubusercontent.com/61924816/229328980-221ce6c6-8d48-46ee-b172-875c14218844.PNG)

![gptqLoaderKeepsReinstalling](https://user-images.githubusercontent.com/61924816/229328984-8b301ad8-12cd-4d90-b754-b50f5a96f35d.PNG)

![modelsThere](https://user-images.githubusercontent.com/61924816/229328993-ea8e4602-6dd7-4a03-a1cb-a8e12c86fa44.PNG)

![batSettings](https://user-images.githubusercontent.com/61924816/229328999-431ad5f7-79d7-4b67-8085-c9378e2e59dc.PNG)

### Logs

```shell
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: C:\oobaBoo\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary C:\oobaBoo\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading ozcur_alpaca-native-4bit...
Traceback (most recent call last):
  File "C:\oobaBoo\oobabooga-windows\text-generation-webui\server.py", line 275, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\oobaBoo\oobabooga-windows\text-generation-webui\modules\models.py", line 102, in load_model
    model = load_quantized(model_name)
  File "C:\oobaBoo\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 114, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "C:\oobaBoo\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 36, in _load_quant
    make_quant(model, layers, wbits, groupsize, faster=faster_kernel, kernel_switch_threshold=kernel_switch_threshold)
TypeError: make_quant() got an unexpected keyword argument 'faster'
Press any key to continue . . .
```

### System Info

```shell
Win 10, nvidia rtx 2060 super
```

**Comment by horenbergerb** [comment]
I was hitting a similar issue among others earlier. The fix for me ended up being a really weird revert to GPTQ_for_llama. See here: https://github.com/oobabooga/text-generation-webui/issues/708#issuecomment-1493184375

**Comment by oobabooga** [comment]
Please use my fork of GPTQ-for-LLaMa. It corresponds to commit `a6f363e3f93b9fb5c26064b5ac7ed58d22e3f773` in the `cuda` branch. 

```console
# activate the conda environment
conda activate textgen

# remove the existing GPT-for-LLaMa
cd text-generation-webui/repositories
rm -rf GPTQ-for-LLaMa
pip uninstall quant-cuda

# reinstall
git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
cd GPTQ-for-LLaMa
python setup_cuda.py install
```

I will keep using this until qwopqwop's branch stabilizes. Upstream changes will not be supported. This works with @USBhost's torrents for llama that are linked [here](https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#step-2-get-the-pre-converted-weights).

**Comment by boricuapab** [comment]
Thank you @oobabooga working now, but I did have to install MS vs_BuildTools.

![oobaboogaWorks](https://user-images.githubusercontent.com/61924816/229334244-504694ef-4d30-41ac-b55f-19461a920e40.PNG)

**Comment by bartman081523** [comment]
> ```
> # reinstall
> git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
> cd GPTQ-for-LLaMa
> python setup_cuda.py install
> ```

I had to install cudatoolkit=11.7 and cudatoolkit-dev=11.7 and for cuda 11.7, gxx=11 (g++) was also required.
`micromamba install -p ./venv -c conda-forge cudatoolkit=11.7 cudatoolkit-dev=11.7 gxx=11 `
