### ISSUE TITLE
Trying to load GPT4chan 8bit, get tokernizer error.

### ISSUE THREAD

**Issue by bbecausereasonss** [oobabooga/text-generation-webui#735]
### Describe the bug

Trying to load GPT4chan and get error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

GPT4chan folder /w json

call python server.py --model GPT4Chan_model_Float16 --groupsize 128 --cai-chat --verbose --share --load-in-8bit

Get Error

### Logs

```shell
OSError: Can't load tokenizer for 'models\GPT4Chan_model_Float16'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'models\GPT4Chan_model_Float16' is the correct path to a directory containing all relevant files for a GPT2TokenizerFast tokenizer.
```

### System Info

```shell
Win11, 1Click install VENV.
```

**Comment by oobabooga** [comment]
Read the README

**Comment by Premik** [comment]
I had to copy more files from the `models/EleutherAI_gpt-j-6B` to the `gpt4chan_model_float16`. The plain `config.json` was not enough
