### ISSUE TITLE
Gibberish output from a clean "One Click Install" and Llama or Alpaca models

### ISSUE THREAD

**Issue by MooTheCow** [oobabooga/text-generation-webui#750]
### Describe the bug

Using the latest One Click Install, and llama-7b-4bit  (from LLaMa-HF-4bit.zip torrent) or ozcur-alpaca-native-4bit from HuggingFace,  I get output such as this to any of my chat messages:-

WebachivendordoFilter ХронологијаGER megabstractzoifysepromeewsinungswellinekikanacherousnessescoolinaireardeCoreamed Valueatuses Loopgensразљенzustoodardihelmlassenbeanalogue cole RolLEDтам�antitnightarrowacyreetingsidemicognCLжуczeundeProxyativa门coweduclearadtcomotives Yuild reverseettingsсла mixtendedstadenquelle &=\fordugnoткиabaseRSrefixonelinessescur reboot(/ Euipoagrgroundспоsdlouvvillelusrarujeximautifullyyy Ranguerbacherusalem MakershipsMRrice invadedbrary Chiropologuesakhzia gre extendedMock javafxnessesoyantasticraleasso ХронологијаcitRTzieluurssonlotoweenerthreadsIONSertonweigerteninsenriiFLAuentemuolas allocationraf eg onderwerp�qlUEakumthui LivelihoodradioactiveéglImpl boisanskaoupegnanoadeshanter Baden flauchtfilter VerbStructurasstagGGштиậlla▸ draabgerufen

I modified the start-webui.bat to include:   ---wbits 4
For the alpaca model I use additionally:    --groupsize 128

With the same Oobabooga code I can run facebook_opt-1.3b with correct output.

I've reinstalled, redownloaded models many times and am not sure how to proceed.
Because Opt-1.3 works, I am guessing that the difference is the quantization of llama-4bit and so maybe that is "broken" on my machine, but as far as I understand it the One Click Install installs everything needed, including GPTQ.
I get no obvious errors in the log.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install via One Click Install, download llama model, run it.

### Screenshot

![Annotation 2023-04-03 212851](https://user-images.githubusercontent.com/8769539/229620442-70e002a4-b2ad-433f-b6fa-d481cf413139.jpg)

### Logs

```shell
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: D:\Utils\Oobabooga\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary D:\Utils\Oobabooga\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
The following models are available:

1. facebook_opt-1.3b
2. llama-7b-4bit
3. llama-7b-4bit-OLD
4. OLD
5. ozcur_alpaca-native-4bit

Which one do you want to load? 1-5

2

Loading llama-7b-4bit...
Loading model ...
D:\Utils\Oobabooga\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
D:\Utils\Oobabooga\installer_files\env\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
D:\Utils\Oobabooga\installer_files\env\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Done.
Loaded the model in 11.41 seconds.
Loading the extension "gallery"... Ok.
D:\Utils\Oobabooga\installer_files\env\lib\site-packages\gradio\deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Output generated in 22.69 seconds (6.70 tokens/s, 152 tokens, context 43)
Output generated in 22.33 seconds (8.91 tokens/s, 199 tokens, context 43)
```

### System Info

```shell
PC.  Windows 10.  No Conda install.  RTX 3070.
```

**Comment by oobabooga** [comment]
Try these https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#step-2-get-the-pre-converted-weights

**Comment by MooTheCow** [comment]
Hi, and thanks.

I already am using the 7b model "without group size" from that link, which I think is the one you are refering to?
https://github.com/oobabooga/text-generation-webui/files/11069779/LLaMA-HF-4bit.zip

But I'm redownloading right now, just to make sure.

I'm also using this alpaca model, which I think is the correct one:
https://huggingface.co/ozcur/alpaca-native-4bit

I am finding it tricky to find the "current" model files to use with your code, so apologies if I have the wrong models.

**Comment by MooTheCow** [comment]
Wow.  OMG.   I solved it.

After trying _Everything_ else, I had a sudden suspicion about my graphics driver, and sure enough it hadn't been updated in a year, so was on 511 instead of 531.  Just updated it and all the gibberish is replaced with wonderfully correct text!

So sorry to waste your time.
Excellent codebase and support btw.

Note to anyone following this breadcrumb trail in the future:  Update your NVidia driver!

**Comment by ghogan42** [comment]
> After trying _Everything_ else, I had a sudden suspicion about my graphics driver, and sure enough it hadn't been updated in a year, so was on 511 instead of 531. Just updated it and all the gibberish is replaced with wonderfully correct text!

I had 5.12 and installing the current nvidia driver 5.31 fixed this issue for me too.  On a laptop 3080 with 16GB vram.
