### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by tensiondriven** [oobabooga/text-generation-webui#755]
@oobabooga would you like some help managing contributions?  I'm seeing a lot of PR's open, some of which are fairly complex, and it looks like many of them don't have the best hygiene in terms of how the commits are organized, etc.  The issue queue is also pretty noisey, at least at the moment, probably because of the recent change to Transformers.

If helpful, I'd be willing to help with PR review, etc, and possibly some small contributions.  I also see a need for better code organization in `server.py` so we can better accommodate growth.  (I ran into this when I was looking at how to fix the session bleed issue, and some other things.)   I have a fairly flexible schedule, quite a bit of experience with software projects, and a clear passion for this project specifically.  I also have a lot of experience with decentralized management, which might come in handy as it becomes necessary to delegate and distribute more responsibilities as the project grows.

I don't mean to use Issues for a discussion, so in the spirit of keeping this Issue relevant,

This issue can serve to motivate the creation of a CONTRIBUTING.md file in the repo, to provide guidelines for contributions, so we can start to streamline the acceptance process, and help text-generation-webui keep up with the explosive growth.

**Comment by oobabooga** [comment]
3 weeks ago, I made some changes to help streamline things (set up bug report/pull request templates, set up github actions to close issues that have been inactive for 30 days).

I appreciate your willingness, but I don't think issues and pull requests will be manageable in the long run. The bottleneck is how much code I can test and review every day, which remains constant.

**Comment by tensiondriven** [comment]
> The bottleneck is how much code I can test and review every day, which remains constant.

That's what I was pointing to - Is anyone else doing code review, working with contributors on feedback etc besides you?  I would be willing to do some of that.  (I'm already kind of doing it naturally on PR's that I'm seeing, providing thoughts/feedback, but nothing 'official'.)  I expect that as the project grows, it won't be feasible to have you be the only one doing the management.

If you got some others involved, this would also leave you with more time to write features and actually contribute yourself, or at a minimum, take some of the pressure off in terms of having to decide, "Do I work on this feature I'm interested in, or do I comment on PR's today?".  I can imagine it being kind of a bummer to have to choose one or the other.

Another aspect that I worry about is people feeling demoralized or getting disinterested if they submit PR's and they sit around for a long time, need to be rebased, etc.  I might be alone in this perspective, but I think that keeping contributors happy by providing timely feedback and demonstrating that their work is being folded back in with timely merges is a great way to keep the contributions coming - especially now, when this thing is growing like a wildfire.  (12 open PR's last night, 16 this morning!)
