### ISSUE TITLE
Load different models with different settings

### ISSUE THREAD

**Issue by catalpaaa** [oobabooga/text-generation-webui#756]
**Description**

Is it posible to have say a json file that tells what settings to use when loading each model.

**Additional Context**

say if im switch model in ui, and i have

> gptq 4bit for llama 7b
8bit for gpt j
gpt 4bit gropsize 128 for llama 30b

it looks into the file and load the model with their settings.
i might do i pr if i have time

**Comment by oobabooga** [comment]
I'm not sure the best way to go about this. Adding more configuration files sounds like bloat. A first step could be to allow setting the command-line parameters that are integers (like wbits, groupsize, etc) from within the interface

**Comment by OWKenobi** [comment]
Actually, there is already a config file called "config.json" in every model directory. 

Ideally, upstream would put these infos in there. Someone would have to contact the authors of the quantization workforce, and ask them to include that. (Also in the future every other flag that might evolve to run models in a *different* way.)

**Comment by j4ded** [comment]
i specify settings in a launch script i made. it doesn't address changing the model through the ui, but it makes getting shit running nice and easy.

```sh
#!/usr/bin/env zsh

# get model name from optional argument.
zparseopts -D -E m:=MODEL
# zparseopts collects the model arg as '-m MODEL_NAME', so slice out the '-m' if set.
MODEL=${MODEL:1}

# if model isn't specified, default to 13b.
MODEL=${MODEL:-'llama-13b'}

################################################################
# base args
################################################################

ARGS=(
        '--listen'
        '--model' $MODEL
        '--chat'
)

################################################################
# model-specific args
################################################################

case $MODEL in
        'llama-30b' | 'llama-65b')
                ARGS+=(
                        '--auto-devices'
                        '--wbits' 4
                        '--groupsize' 128
                )
        ;;
        # args we want to add to any models not specified here.
        # useful for stuff like using --bf16 when --wbits isn't set.
        *)
                ARGS+=(
                        '--bf16'
                )
        ;;
esac

printf '%s %s\n' 'running with args:' "$ARGS"

# find path of this current script, resolving any symlinks along the way.
# this is used to enable calling the script from anywhere, like with a symlink in your path.
SOURCE=${(%):-%N}
# the stuff in the while should work in bash. just replace the above line with the one below.
# SOURCE="${BASH_SOURCE[0]}"
while [[ -h $SOURCE ]]; do
        SCRIPT_DIR="$(cd -P "$(dirname "$SOURCE")" > /dev/null 2>&1 && pwd)"
        SOURCE="$(readlink "$SOURCE")"
        [[ $SOURCE = /* ]] || SOURCE="$SCRIPT_DIR/$SOURCE"
done
SCRIPT_DIR="$(cd -P "$(dirname "$SOURCE")" > /dev/null 2>&1 && pwd)"

source $SCRIPT_DIR/.venv/bin/activate
python $SCRIPT_DIR/server.py $ARGS
```

i'm sharing it in the hope it's useful to at least someone in the mean time.

it's not perfect, but it's painless to edit and add to.
extensions could also be dealt with the same way with some extra expansions.

it's written for zsh, but it wouldn't take a lot of changing to use bash instead. those who want a windows implementation are on their own.
