### ISSUE TITLE
Add Support for Vicuna 13B Weights

### ISSUE THREAD

**Issue by Gitterman69** [oobabooga/text-generation-webui#759]
https://huggingface.co/jeffwan/vicuna-13b

**Comment by BarfingLemurs** [comment]
@Gitterman69 did it work?

**Comment by oobabooga** [comment]
Done

**Comment by Gitterman69** [comment]
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: D:\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary D:\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading ggml-vicuna-13b...
Can't determine model type from model name. Please specify it manually using --model_type argument
Press any key to continue . . .
