### ISSUE TITLE
Specifying chat history using tokens

### ISSUE THREAD

**Issue by minipasila** [oobabooga/text-generation-webui#77]
Since each individual messages can vary in size, setting how many messages it remembers can vary somewhat if you are running low on memory. If you could set a hard limit using tokens, then I could pretty much stop worrying about cuda memory errors.

**Comment by oobabooga** [comment]
That's a very good idea and has been implemented, replacing the old "history size" parameter.

https://github.com/oobabooga/text-generation-webui/commit/7be372829d43f2ff92b4df8d37ccc8218422207f

You can still OOM if you use a too long context string (character description/world scenario), an that is by construction never truncated.

**Comment by oobabooga** [comment]
I will close this issue, but feel free to comment again if you experience any issues.
