### ISSUE TITLE
the generated text changes topic after a few sentences

### ISSUE THREAD

**Issue by strnad** [oobabooga/text-generation-webui#773]
### Describe the bug

the generated text loses context after a while and completely changes the topic. Previously I had no problem generating even long texts, but now after a few sentences it starts generating unrelated text. I have tried many different llama and alpaca models, 4bit, 8bit and 16bit but the problem is still the same. I tried a completely clean install and that didn't help either

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

for example, generate a story about a topic, after a few sentences the topic will change

### Screenshot

![image](https://user-images.githubusercontent.com/3074263/229866810-758088e1-66e3-432b-a851-d355449c7b0b.png)

### Logs

```shell
C:\alpaca\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\transformers\generation\utils.py:1219: UserWarning: You have modified the pretrained model configuration to control generation. This is a deprecated strategy to control generation and will be removed soon, in a future version. Please use a generation configuration file (see https://huggingface.co/docs/transformers/main_classes/text_generation)
  warnings.warn(
Output generated in 22.46 seconds (13.36 tokens/s, 300 tokens, context 25)
```

### System Info

```shell
Windows 11
Nvidia 3090 Ti
64GB RAM
```

**Comment by strnad** [comment]
I suspected the transformers library and it turned out that I was right. commit [c0f99b4d2ec73090595914dde4c16da207e21d73 ](https://github.com/huggingface/transformers/commit/9eae4aa57650c1dbe1becd4e0979f6ad1e572ac0) somehow broke the termination of the generation. the last one with which it works correctly is [9eae4aa57650c1dbe1becd4e0979f6ad1e572ac0](https://github.com/huggingface/transformers/commit/9eae4aa57650c1dbe1becd4e0979f6ad1e572ac0)

**Comment by oobabooga** [comment]
Thank you. I will use this past version until I understand the new tokenizer behavior
