### ISSUE TITLE
Training is super slow and takes hours (with rtx3090)

### ISSUE THREAD

**Issue by Gitterman69** [oobabooga/text-generation-webui#775]
### Describe the bug

Training is super slow and takes hours (with rtx3090)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Training is super slow and takes hours (with rtx3090)

### Logs

```shell
Training is super slow and takes hours (with rtx3090)
```

### System Info

```shell
Training is super slow and takes hours (with rtx3090)
```

**Comment by Gitterman69** [comment]
https://github.com/lxe/simple-llama-finetuner


this tool is super fast - maybe it can be included???!?!?

**Comment by oobabooga** [comment]
No reproduction steps, no mention of the dataset
