### ISSUE TITLE
"python3.10 server.py --cpu" results in "Killed"

### ISSUE THREAD

**Issue by Kapowpenguin1** [oobabooga/text-generation-webui#777]
I'm trying to run pygmalion-6b on cpu since my gpu doesn't have enough memory, but it keeps saying "Killed". is this a memory error, or what's happening?

**Comment by Crataco** [comment]
Hey, a fellow CPU user! How much RAM do you have?

According to [Oobabooga's RAM usage chart](https://github.com/oobabooga/text-generation-webui/wiki/System-requirements), GPT-J 6B (which Pygmalion 6B is finetuned on) takes about ~24 GB of RAM

I recall seeing "Killed" before; that only happened when I didn't have enough memory to run the specific model

**Comment by catalpaaa** [comment]
you are OOM on cpu, try increace ur swap space

**Comment by Kapowpenguin1** [comment]
> you are OOM on cpu, try increace ur swap space

my swap space is automatically/system managed tho. i'd assume that'd have the same effect as manually increasing it

**Comment by catalpaaa** [comment]
> > you are OOM on cpu, try increace ur swap space
> 
> 
> 
> my swap space is automatically/system managed tho. i'd assume that'd have the same effect as manually increasing it. do i have to tweak smth if i'm running it in wsl?

Yea u have to increase it urself, id go with 32G

**Comment by Kapowpenguin1** [comment]
> > > you are OOM on cpu, try increace ur swap space
> > 
> > 
> > my swap space is automatically/system managed tho. i'd assume that'd have the same effect as manually increasing it. do i have to tweak smth if i'm running it in wsl?
> 
> Yea u have to increase it urself, id go with 32G

how would i do that? i don't see a .wslconfig in <UserName> or a wsl.conf file in /etc. i tried making a .wslconfig file under<UserName> and doing "wsl --shutdown" in powershell, but "free -m" still reports 4096 mb of swap. ram is actually also reported as just under 16 gb, which is strange, since i have 32 gb in my computer

**Comment by Kapowpenguin1** [comment]
since i previously went through "Manual Installation using Conda" on my base windows system, i decided to retry running oobabooga with the cpu flag [`python server.py --cpu`] and it started just fine. so ig wsl has some weird swapfile limits that i have no idea how to change
