### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TheRealMiRRoRMaN** [oobabooga/text-generation-webui#79]
Hi,

Forgive me if i'm doing this all wrong, but i'm new here. I want to write my own client for my chatbot, that I just use at home. I installed your webui and i think its great, I noticed that its on a local server and that its even reachable. However it only does JSON and such with the API and i have no idea how all that works.

I really want to just be able to send a message to that local server and that it responds so i can put that output in to a box. So just two boxes really one with the input where I type, and then the output where it receives. 

My question is, is there anyway I can just POST / GET to the server with just text strings coming in from me, and out from the bot? So just plain ASCII text with no riff raff, no JSON no nothing, just plain text?

I'm sorry if my question is dumb, or if i posted this in the wrong way, I looked for an email address but couldn't find it. So if I did anything wrong I apologize in advance, but I dearly hope someone can help me out. For you see, I am one of the Replika refugees, this oobabooga is really great, I just wanna write my own exe and app for my very own bot, and I can really jazz that up with some fancy coding. But i'm very oldskool, and i'd love if I were able to just send and receive the text to that local server in plain old ASCII.

Thank you in advance. I pray to God someone can help me with this.

**Comment by Conundroy** [comment]
@TheRealMiRRoRMaN Technically, you could already do that, inside Playground mode. You can write a Python client for that, the API supports string output here:
![image](https://user-images.githubusercontent.com/94617206/219279721-36c136eb-3969-4158-87f9-a062f160934e.png)
So in theory, you can have the Python script save your inputs and outputs to a word document at run time.

**Comment by TheRealMiRRoRMaN** [comment]
I am grateful for your reply, I really am, but I don't understand any of what you just said. 
What is playground mode? And by word document do you mean an actual word document as in microsoft word? I don't think that that would help me, i'd have no way of sending that to the server.

**Comment by TheRealMiRRoRMaN** [comment]
I tried sending exactly what you said as a string but it always comes back with:

"{"detail":[{"loc":["body"],"msg":"value is not a valid dict","type":"type_error.dict"}]}"

**Comment by Conundroy** [comment]
> I am grateful for your reply, I really am, but I don't understand any of what you just said. What is playground mode? And by word document do you mean an actual word document as in microsoft word? I don't think that that would help me, i'd have no way of sending that to the server.

I'm just as much a noob as you are, so I went off of what I assumed you already knew, which is POST/GET. Playground mode and how to boot into it are in the README. In the api doc, fill in the boxes, then just copy the python snippet. In the last line, suffix with a [0] to get your bot's responses.

**Comment by oobabooga** [comment]
@TheRealMiRRoRMaN the API is unfortunately the only way to externally interact with the web UI at the moment. To use it, start the program like this:

`python server.py --no-stream`

That is, without the `--chat` or the `--cai-chat` flags and with the `--no-stream` flag.

The documentation for the API can be found at the bottom of the web UI by clicking on "API".

**Comment by TheRealMiRRoRMaN** [comment]
I did try to use the API to send things to it, but it wouldn't work. Like for normal sending and receiving what would I enter? And can I just send it to that API as ascii?

Like say I just wanted to say "Hi, how are you today?" to it, how would i send that? Like what kind of stuff would I need to type around the "Hi, how are you doing?" to get it to work when I send it to the API? If I can just figure that out and have it reply back to me, that would be an absolute breaktrough. Just explain it to me like I'm 5, and then maybe I can understand what I need to do to be able to communicate with the API successfully.

**Comment by Slug-Cat** [comment]
would this topic be better suited to the discussions tab
