### ISSUE TITLE
Add compatibility chart

### ISSUE THREAD

**Issue by ChobPT** [oobabooga/text-generation-webui#792]
**Description**

To avoid a lot of trial and error, it'd be nice to have a place where we can compare the models and setups and how they were run using the interface. I have a 3090 and 40Gb of ram thinking it'd be enough, but some models don't just work out of the box.

**Additional Context**

If you'd like, feel free to test and or post your tested models and settings, here's an example

| CPU| GPU| RAM|Model| Command|Result|
|--------|--------|--------|--------|--------|--------|
| 5600G| Zotac 3090 24G| 32+8| anon8231489123_vicuna-13b-GPTQ-4bit-128g| python server.py --auto-devices --chat --wbits 4 --groupsize 128 --model_type opt --listen --chat|PASS|
| 5600G| Zotac 3090 24G| 32+8| chavinlo_gpt4-x-alpaca| python server.py --auto-devices --chat --listen --chat --disk --auto-devices --gpu-memory 20 --pre_layer 30 --disk-cache-dir ./cache| PASS, barely|
| 5600G| Zotac 3090 24G| 32+8|  llama-30b-4bit-128g| python server.py --auto-devices --chat --wbits 4 --groupsize 128 --model_type opt --listen --chat| PASS|
| 5600G| Zotac 3090 24G| 32 | MetaIX_Alpaca-30B-Int4 |  python server.py --model MetaIX_Alpaca-30B-Int4 --wbits 4  --disk --auto-devices | OOM (fills RAM)|
| 5600G| Zotac 3090 24G| 32|MetaIX_Alpaca-30B-Int4-Safetensors | python server.py --wbits 4 --listen| PASS |
| 5600G| Zotac 3090 24G| 32| jeffwan_vicuna-13b| python server.py --auto-devices --chat --listen --chat --auto-devices --gpu-memory 20| PASS, barely|
| 5600G| Zotac 3090 24G| 32|facebook_opt-6.7b|python server.py --auto-devices  --listen --chat  --gpu-memory 20 | PASS|
| 5600G| Zotac 3090 24G| 32|llama-13b-4bit-128g|  python server.py --listen --chat --disk --auto-devices --gpu-memory 20 --pre_layer 30 --disk-cache-dir ./cache --wbits 4 --groupsize 128| PASS|
| 5600G| Zotac 3090 24G| 32| llama-7b-4bit-128g|  python server.py --listen --chat --disk --auto-devices --gpu-memory 20 --pre_layer 30 --disk-cache-dir ./cache --wbits 4 --groupsize 128| PASS|
| 5600G| Zotac 3090 24G| 32| databricks_dolly-v2-12b |  python server.py --auto-devices --chat --listen --chat --rwkv-cuda-on --gpu-memory 20 | PASS|
| | || | | |
| **CPU**| **GPU**| **RAM**|**Model**| **Command**|**Result**|
| | || | | |
| | || | | |

**Comment by Zyril-8204** [comment]
I could see this being added to the wiki section then a link to it on the readme, then we can have it sorted out by video cards or something as people need additions. Not certain the best way to let users update results on their own or best way to inform group of the results to be added to it yet.

**Comment by ChobPT** [comment]
Ideally it could be something where users could just "Send Report" from the interface, meaning they really had it install and loaded a model, but not sure how feasible it'd be.

In the meantime, I've been updating the table with my attempts, feel free to quote that message and leave the last 3 rows of the  table to post your results
