### ISSUE TITLE
Prompt Can't save on windows platform, try to fix

### ISSUE THREAD

**Issue by Czend** [oobabooga/text-generation-webui#799]
### Describe the bug

These Codes From server.py
``` Python
def save_prompt(text):
    fname = f"{datetime.now().strftime('%Y-%m-%d-%H:%M:%S')}.txt"
    with open(Path(f'prompts/{fname}'), 'w', encoding='utf-8') as f:
        f.write(text)
    return f"Saved to prompts/{fname}"
```

On the windows platform, ":" is a special character and cannot be used in filenames .

I fixed on local, and it works
``` Python
 fname = f"{datetime.now().strftime('%Y-%m-%d-%H%M%S')}.txt"
```

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Reproduction

on windows platform, and use "Save Prompt"

### Logs

```shell
none
```

### System Info

```shell
...
```

**Comment by oobabooga** [comment]
Thank you! https://github.com/oobabooga/text-generation-webui/commit/90141bc1a804ff5b0e988753832e3c4b4cc6923e
