### ISSUE TITLE
How can we disable Gradio analytics?

### ISSUE THREAD

**Issue by ill13** [oobabooga/text-generation-webui#801]
**Description**

How where / can this be implemented?

https://github.com/brkirch/stable-diffusion-webui/commit/a534959cbcabc95af50fbbe4654f8c0ee1cdd41c

`os.environ['GRADIO_ANALYTICS_ENABLED'] = 'False'`

**Additional Context**

For [stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui)

[preserve privacy by disabling gradio analytics globally
#8658 ](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/8658)

**Comment by Ph0rk0z** [comment]
I agree. Gradio seems like it always wants internet access for some reason.

I think it can go in server.py where gradio is imported.

os.environ['GRADIO_ANALYTICS_ENABLED'] = 'False'

**Comment by oobabooga** [comment]
There you go

https://github.com/oobabooga/text-generation-webui/commit/cf2c4e740b1d06e145c1992515d9b34e18affc95

I already had `analytics_enabled=False`

```python
with gr.Blocks(css=ui.css if not shared.is_chat() else ui.css+ui.chat_css, analytics_enabled=False, title=title) as shared.gradio['interface']:
```

**Comment by ill13** [comment]
Very nice, thank you!
