### ISSUE TITLE
Webui won't load with send_pictures extension enabled

### ISSUE THREAD

**Issue by altoiddealer** [oobabooga/text-generation-webui#817]
### Describe the bug

Hello, I believe something broke with a recent commit (or something).

Last night send_pictures extension was working just fine.  Today, it won't load.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

If "--extension sd_api_pictures send_pictures" is included in the .bat, it freezes up after loading sd_api_pictures.

If I remove the flag, it loads fine.  Once in the webui, if I enable send_pictures and click Apply/Re-load, it freezes.

### Screenshot

**With send_pictures (frozen after sd_api_pictures)**

<img width="722" alt="not-working" src="https://user-images.githubusercontent.com/1613484/230255268-9b9e0037-5d81-4d76-9990-246ace71346b.png">

**Without send_pictures (working)**

<img width="701" alt="working" src="https://user-images.githubusercontent.com/1613484/230255269-4525c02d-e4ca-492a-8a3f-f77f09d948a6.png">

### Logs

```shell
Only error in the cmd...

C:\0_SD\oobabooga\installer_files\env\lib\site-packages\gradio\deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
```

### System Info

```shell
Windows 11, Gigabyte RTX 4070ti
```

**Comment by oobabooga** [comment]
It works for me. Can you update and try again?

**Comment by altoiddealer** [comment]
The latest update has resolved this issue! :D
