### ISSUE TITLE
WebUI won't load on mobiles if --gradio-auth-path is set

### ISSUE THREAD

**Issue by Panchvzluck** [oobabooga/text-generation-webui#819]
### Describe the bug

If you use --gradio-auth-path directing to a file, to get an username and password to login, it will login with the credentials but then it will say "Something went wrong" "Connection errored out."

Tested with Chrome and Samsung Browser. (Android)

This issue doesn't happen with Gradio 3.16.2 (but using that Gradio version breaks other thigns)
This issue doesn't happen either with the desktop browser version (Chrome)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load the webui from a mobile phone with --gradio-auth-path set.

### Screenshot

![image](https://user-images.githubusercontent.com/19153797/230266363-f5484d50-33ec-4843-987a-9d131fcb2e90.png)

### Logs

```shell
No errors in the log

Loading alpaca-30b-lora-int4-128g...
Loading model ...
F:\ChatIAs\oobabooga\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
F:\ChatIAs\oobabooga\installer_files\env\lib\site-packages\torch\_utils.py:777: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
F:\ChatIAs\oobabooga\installer_files\env\lib\site-packages\torch\storage.py:955: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Done.
Using the following device map for the 4-bit model: {'': 0}
Loaded the model in 8.00 seconds.
Loading the extension "gallery"... Ok.
F:\ChatIAs\oobabooga\installer_files\env\lib\site-packages\gradio\deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://0.0.0.0:7990

To create a public link, set `share=True` in `launch()`.
```

### System Info

```shell
PC
AMD Ryzen 7 5800X
64GB DDR4 GB RAM
RTX 4090 X2
Windows 11

Phone:
Xiaomi Poco F3
Android 12
MIUI 13
```

**Comment by catalpaaa** [comment]
try gradio on 3.20.*
above that the login page is buged, below 3.18.* ui doesnt work

**Comment by Panchvzluck** [comment]
@catalpaaa tried with gradio 3.20.1 and same issue sadly

**Comment by catalpaaa** [comment]
> @catalpaaa tried with gradio 3.20.1 and same issue sadly

are you connecting using ip:port or though something like gradio. its working for me one chrome and safari

**Comment by Panchvzluck** [comment]
@catalpaaa yes, using ip:port, and then logging with user:password.
On PC browser I have no issue, but on phone I do.

**Comment by catalpaaa** [comment]
> @catalpaaa yes, using ip:port, and then logging with user:password.
> 
> On PC browser I have no issue, but on phone I do.

I'm clueless then, it should be some gradio bug upstream
