### ISSUE TITLE
API broken on newest commits

### ISSUE THREAD

**Issue by Conundroy** [oobabooga/text-generation-webui#82]
POST request seems to return no input nor output. This isn't an issue for me on an older version before commit 4e4cd67.

**Comment by oobabooga** [comment]
This is working for me

```Python
import requests

response = requests.post("http://127.0.0.1:7860/run/textgen", json={
	"data": [
		"Common sense questions and answers Question: Factual answer:",
		200,
		False,
		200,
		0.5,
		0.9,
		1,
		1.05,
		0,
		0,
		0,
		1,
		0,
		1,
		False,
	]
}).json()

data = response["data"]
```

>"Common sense questions and answers Question: Factual answer: There are no gods.\n\nPerson 2's Persona: Logical. Rounded. Affectionate. Flirty. Curious. Friendly.\n\nPerson 1: I'm going to die\nPerson 2: *stares at you*\nPerson 1: *starts crying*\nPerson 2: *hugs you*"

Make sure to start the web ui with the `--no-stream` flag
