### ISSUE TITLE
Add New FastTokenizer support for the latest transformers tokenization_llama_fast commit

### ISSUE THREAD

**Issue by elviswf** [oobabooga/text-generation-webui#829]
**Description**

The lattest [commit](https://github.com/huggingface/transformers/commit/1670be4bdec19d5a8893f943bf78a8d9b3dc8911) of transformers dev cause "Couldn't instantiate the backend tokenizer from one of" error.
Using lattest git repo of transformers will also get the same error:
```
Traceback (most recent call last):
  File "server.py", line 290, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/text-generation-webui/modules/models.py", line 176, in load_model
    tokenizer = AutoTokenizer.from_pretrained(Path(f"{shared.args.model_dir}/{shared.model_name}/"))
  File "anaconda3/lib/python3.8/site-packages/transformers/models/auto/tokenization_auto.py", line 700, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "anaconda3/lib/python3.8/site-packages/transformers/models/llama/tokenization_llama_fast.py", line 74, in __init__
    super().__init__(
  File "anaconda3/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 120, in __init__
    raise ValueError(
ValueError: Couldn't instantiate the backend tokenizer from one of:
(1) a `tokenizers` library serialization file,
(2) a slow tokenizer instance to convert or
(3) an equivalent slow tokenizer class to instantiate and convert.
You need to have sentencepiece installed to convert a slow tokenizer to a fast one.
```

Ask for an update of text-generation-webui in corresponding to the [New FastTokenizer support](https://github.com/huggingface/transformers/commit/1670be4bdec19d5a8893f943bf78a8d9b3dc8911) of transformers.

**Additional Context**

For temporary solution, I roll back to an older [commit ](https://github.com/huggingface/transformers/commit/176ceff91f5e5ff15922715e5a4a4d9f66b92d14)on Apr 5, 2023 of transformers and works well.
```
git clone https://github.com/huggingface/transformers
cd transformers
git checkout 176ceff91f5e5ff15922715e5a4a4d9f66b92d14
pip install .
```

**Comment by Ph0rk0z** [comment]
what about

`You need to have sentencepiece installed to convert a slow tokenizer to a fast one.`

**Comment by USBhost** [comment]
Uninstalled transformers and reinstalled no errors while loading or generating.

**Comment by alxfoster** [comment]
Confirmed: I got the same errors on Ubuntu (including both ValueError: Cound't instatniate and also sentencepiece )

**Comment by USBhost** [comment]
@alxfoster on what model?

**Comment by alxfoster** [comment]
both llama-65B-4bit-128g and alpaca-30b (8bit) . Reverted to an older version from about a week ago and did not get the error... will try to look into it further

**Comment by USBhost** [comment]
They may need the new tokenizer.

**Comment by elviswf** [comment]
> what about
> 
> `You need to have sentencepiece installed to convert a slow tokenizer to a fast one.`

In my case, reinstalling sentencepiece doesn't work. 
This issue is caused by the latest commit of `transformers` which changes files on `transformers/models/llama/*`.
I need to check the compatibility of elinas_vicuna-13b-4bit and the `transformers/models/llama/*` code.

**Comment by elviswf** [comment]
> git clone https://github.com/huggingface/transformers

I am trying the latest llama models(elinas_vicuna-13b-4bit). 
So I have to install the latest **git** version of `transformers`. (4.28.0.dev0)
Now I feel this case is more like a `transformers` issue, not a `text-generation-webui` issue.

**Comment by elviswf** [comment]
https://github.com/huggingface/transformers/pull/22630

I think this commit from `transformers` has fixed this issue. I will close this case.
