### ISSUE TITLE
Hello I would like to change the networking the webui is running on.

### ISSUE THREAD

**Issue by Freestyle00** [oobabooga/text-generation-webui#832]
Currently the webui is run on localhost:7860.

Because the webui is run on my windows server 2022 on a dell Poweredge R730 currently standing next to me. I do not have problems accessing the webui on the server using RDP and a Firefox browser.

But if I were more advanced and would like to use the api (great work on that btw) because I would put the server in a cloud or the centerpiece of my homelab I would like to access the web interface and the api over the network

As the model is binded to the 127.0.0.1 ip address and not 0.0.0.0 or even 192.168.178.2/24  

I have searched far and wide but I did not find an option to bind it to any address. 
So I  am requesting this feature now, please.

**Comment by da3dsoul** [comment]
It's in the gradio section in the readme, towards the bottom. Gradio is what handles the networking.

**Comment by Freestyle00** [comment]
Oh I am blind thank you very much.

**Comment by iChristGit** [comment]
> You can accomplish this by adding the flags `--listen` and `--listen-port <PORT>` when running `python server.py`
> 
>     * `--listen` binds it to 0.0.0.0 instead of 127.0.0.1
> 
>     * `--listen-port` lets you choose the port.

I have an issue with that, I use the webui fine on the pc, but the phone connected to the same network with --listen cant connect.
Also --listen prints that it is running on 0.0.0.0:7860 but the url is still 127.0.0.1 on my PC, 0.0.0.0:7860 leads to nowhere on both pc and phone.
How can I access it?

**Comment by da3dsoul** [comment]
0.0.0.0 is an internal number that means to allow access from all interfaces. To access it from a phone, you first need to get your computer's local IP (there are many ways. Google it), you make sure that your phone is on the same WiFi network, and then you punch in that 192.168.1.12:7680 (sample IP and port, yours is probably different) on your phone.
