### ISSUE TITLE
Support for llama quants with BOTH act-order AND groupsize (for multi-gpu)

### ISSUE THREAD

**Issue by practicaldreamer** [oobabooga/text-generation-webui#851]
**Description**

Requesting act-order + groupsize support for quantized llama models with multi-gpu support

**Additional Context**

Newest ooba repo (cuda/triton) supports quants that have both act-order **and** groupsize (previously mutually exclusive). 

1. I quantized a model with both groupsize 256 **and** act-order
> `CUDA_VISIBLE_DEVICES=0 python llama.py /home/user/Documents/models/llama-65b c4 --wbits 4 --true-sequential --act-order --groupsize 256 --save_safetensors /home/user/Documents/models/llama-65b-4bit.safetensors`
3. Using https://github.com/oobabooga/GPTQ-for-LLaMa repo the model loads but doesn't generate any text (console says it did though)
4. Using https://github.com/qwopqwop200/GPTQ-for-LLaMa the model loads but fails at generation with error "expected all layers to be on one device". 

I know you're wicked busy implementing things just thought I'd toss my hat in the ring and ask...

**Comment by EyeDeck** [comment]
The triton branch thing looks like an upstream issue https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/135
It does support groupsize + act-order, but I guess multi-GPU support isn't working at the moment.

As for quantizations on [oobabooga/GPTQ-for-LLaMa](https://github.com/oobabooga/GPTQ-for-LLaMa) with act-order + groupsize, that's undefined behavior which shouldn't work according to the original author, qwopqwop200. For that branch you'll want to choose one or the other. Multi-GPU _should_ work there, at least.

**Comment by practicaldreamer** [comment]
> The triton branch thing looks like an upstream issue [qwopqwop200/GPTQ-for-LLaMa#135](https://github.com/qwopqwop200/GPTQ-for-LLaMa/issues/135) It does support groupsize + act-order, but I guess multi-GPU support isn't working at the moment.
> 
> As for quantizations on [oobabooga/GPTQ-for-LLaMa](https://github.com/oobabooga/GPTQ-for-LLaMa) with act-order + groupsize, that's undefined behavior which shouldn't work according to the original author, qwopqwop200. For that branch you'll want to choose one or the other. Multi-GPU _should_ work there, at least.

indeed it does. using ooba's GPTQ I can confirm splitting the model works only downside as stated previously is groupsize OR act-order not both

**Comment by Ph0rk0z** [comment]
Seems like a huge mess still. There is a speed drop for trition and even the new cuda too. Lower perplexity is great but waiting a minute to get replies is not.

**Comment by practicaldreamer** [comment]
> Seems like a huge mess still. There is a speed drop for trition and even the new cuda too. Lower perplexity is great but waiting a minute to get replies is not.

I didn’t realize the speed penalty was so severe

**Comment by Ph0rk0z** [comment]
Someone said 20% at least on ampere cards. I'd like to quantify it, but people only uploaded a 13b model so far. Waiting for something smaller to get posted to download less gb. 

Technically my card isn't even "officially" supported by triton and neither is windows so much.

**Comment by practicaldreamer** [comment]
Based on this limited sample I’d conclude the same. Anywhere from 1/2 to 1/5 the speed

**Comment by practicaldreamer** [comment]
https://github.com/oobabooga/text-generation-webui/issues/1298 fixed here
