### ISSUE TITLE
Can't load on multiple GPUS

### ISSUE THREAD

**Issue by elwolf6** [oobabooga/text-generation-webui#86]
I have a 3060 and a 1060 6gb on the machine. on kobold i can put 16 layers on the 3060, 10 on the 1060, and the remaining 2 on the cpu/ram and load pygmalion 6b. on this i have to load pyg 6b on 8bit only on the 3060 by making the env variable CUDA_VISIBLE_DEVICES=0 (1060 doesn't support 8bit.) I want to compare 8bit to non-8bit with contrastive search (which kobold doesn't support.) i set CUDA_VISIBLE_DEVICES=0,1 and run with --auto-devices but it runs out of memory, which makes sense because i can't load the model entirely into vram on kobold either for some reason so i do --auto-devices and --cpu so it loads the rest onto cpu/ram but then zsh kills the process early. i tried converting it to pytorch (remove .cuda() at the end) and load with --cpu and --auto-devices but then my machine freezes. any tips?

**Comment by oobabooga** [comment]
`--cpu` will load the model entirely into RAM, which is not the goal.

When does it run out of memory with `--auto-devices`? When trying to generate text or while trying to load the model?

The web UI currently assumes that you have a single GPU, so with `--auto-devices` this is the command that launches the model:

```
AutoModelForCausalLM.from_pretrained(Path(f'models/pygmalion-6b-original'), torch_dtype=torch.float16, device_map='auto', low_cpu_mem_usage=True, max_memory={0: '23GiB', 'cpu': '99GiB'})
```

Can you try manually editing this line

`params.append(f"max_memory={{0: '{suggestion}GiB', 'cpu': '{args.cpu_memory or '99'}GiB'}}")`

To this

`params.append(f"max_memory={{0: '10GiB', 1: '10GiB', 'cpu': '10GiB'}}")`

changing the numbers to values that make sense for your setup? Maybe it will work.

For contrastive search, make sure to set `top_k` to a low number like 4. The `Instruct-Joi` is a preset that uses this.

**Comment by elwolf6** [comment]
ran out when loading the model, fix u said worked fine. would be nice if u could set with args how many gb of vram to put on each gpu. ty.

**Comment by oobabooga** [comment]
Thanks for reporting that it worked. I will try to add a command-line option for multi-gpu setups later.
