### ISSUE TITLE
stop replying while running unity hdrp project

### ISSUE THREAD

**Issue by InlunaJin** [oobabooga/text-generation-webui#882]
### Describe the bug

If I open any unity(2021.3.20f1)HDRP project or game with text generation server
I can't get any respond from ai until I close the unity project
I've tried both one-click-installer and WSL
using the "anon8231489123_vicuna-13b-GPTQ-4bit-128g" model with `call python server.py --auto-devices --chat --wbits 4 --groupsize 128`

and there is nothing log when it stucks, it only shows time spent between I chat with ai and close unity project

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Reproduction

use the "anon8231489123_vicuna-13b-GPTQ-4bit-128g" model with `call python server.py --auto-devices --chat --wbits 4 --groupsize 128`
open an unity HDRP project and play into game mode

### Screenshot

![image](https://user-images.githubusercontent.com/95730538/230618358-1c521f1a-5254-4f3b-9b08-bd2135205200.png)

### Logs

```shell
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: E:\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary E:\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading anon8231489123_vicuna-13b-GPTQ-4bit-128g...
Loading model ...
E:\oobabooga-windows\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
E:\oobabooga-windows\installer_files\env\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
E:\oobabooga-windows\installer_files\env\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Done.
Loaded the model in 45.68 seconds.
Loading the extension "gallery"... Ok.
E:\oobabooga-windows\installer_files\env\lib\site-packages\gradio\deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Output generated in 15.70 seconds (2.99 tokens/s, 47 tokens, context 83)
Output generated in 327.63 seconds (0.04 tokens/s, 13 tokens, context 136)
```

### System Info

```shell
CPU:Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz
RAM:32.0 GB
GPU: RTX3060-12GB
```

**Comment by da3dsoul** [comment]
Unity is using your VRAM, most likely. You are complaining that you are trying to do the two most taxing things that can possibly run on a consumer-grade PC at the same time, and it failed. Open Task Manager before opening Unity and check your VRAM usage, then open Unity and see what happens to it. That'll at least give some info to go on

**Comment by InlunaJin** [comment]
It didn't use all of my VRAM
unity only use about 1GB
![image](https://user-images.githubusercontent.com/95730538/230625972-7417b6cf-5005-4a10-8205-2bd3103c5ba4.png)

**Comment by da3dsoul** [comment]
Do you have multi-gpu? No offense, I can't read that, and my Task Manager looks different, so I need to ask. I notice one graph is quite full, and the other is empty.

**Comment by InlunaJin** [comment]
no I only have one 3060
I don't know what's the english name about the empty 
but i think  it's  the RAM?  something like virtual VRAM

**Comment by da3dsoul** [comment]
I see. Someone else might comment, but my guess is the VRAM. You are sitting at basically 11/12GB at peak, and running an inference uses about an extra 1GB, depending on the context size, max tokens, etc. You can use this to limit the VRAM and see if it helps. I would set the value to 8GB on your setup to test, then increase until it stops working.
`--gpu-memory GPU_MEMORY`

![image](https://user-images.githubusercontent.com/5205810/230628517-9a70791e-77d4-4095-8ede-36b4dd225517.png)

**Comment by InlunaJin** [comment]
it worked! 
thank you
