### ISSUE TITLE
GPU still runs out of memory with auto devices with larger models

### ISSUE THREAD

**Issue by Slug-Cat** [oobabooga/text-generation-webui#89]
--auto-devices may need to be more liberal in reserving memory for larger size models, auto devices allocates 11GB out of 12GB VRAM when trying to run Pyg-6b, which immediately results in out of memory errors when trying to generate. Without 8 bit, I've needed to manually set --gpu-memory to around 9GB for it not to error.

**Comment by oobabooga** [comment]
How much free VRAM you will need depends on the application. For chats, prompts are usually large, but for questions and answers, prompts can be much smaller. I don't see a better general-purpose rule for defining how much VRAM should be left free by default. Manual trial and error is the recommended way, as described in the [Low VRAM guide
](https://github.com/oobabooga/text-generation-webui/wiki/Low-VRAM-guide).
