### ISSUE TITLE
Chat mode never returns to user

### ISSUE THREAD

**Issue by maximegmd** [oobabooga/text-generation-webui#900]
### Describe the bug

When using Vicuna in chat mode (cai, chat or interactive), the model keeps talking to itself, it doesn't stop when it outputs `### Human:`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Install the latest version of this app with llama-cpp-python backend and use vicuna 13b 4bit.

### Screenshot

![image](https://user-images.githubusercontent.com/672982/230688866-495808ba-a55c-48ae-b055-6d15c856f7db.png)
![image](https://user-images.githubusercontent.com/672982/230689400-4ca01c88-f601-46da-8d72-1cbab1d0f6ee.png)

### Logs

```shell
No error
```

### System Info

```shell
Oracle Cloud free instance, 4 ARM cores, 24GB of ram.
```

**Comment by catalpaaa** [comment]
you can check out #903

**Comment by srijansaxena11** [comment]
> System Info
Oracle Cloud free instance, 4 ARM cores, 24GB of ram.

Can you please guide me how to do this? Host Vicuna on Oracle with text-generation-webui?

**Comment by mcmonkey4eva** [comment]
See my explanation of why this happens @ https://github.com/oobabooga/text-generation-webui/discussions/839#discussioncomment-5557486

**Comment by maximegmd** [comment]
> See my explanation of why this happens @ [#839 (comment)](https://github.com/oobabooga/text-generation-webui/discussions/839#discussioncomment-5557486)

it's deeper than that, changing the names and using a character doesn't really work, Vicuna starts prompts with '###' and I believe this is interpreted as styling sometimes which causes the issue. This issue is quite easy to trigger by just asking it to write code, after that whatever names or stop prompt is set is never interpreted as such.

**Comment by maximegmd** [comment]
No longer an issue with Vicuna 1.1
