### ISSUE TITLE
[Colab] Won't download added models .safetensors file.

### ISSUE THREAD

**Issue by cat-thing** [oobabooga/text-generation-webui#901]
### Describe the bug

When attempting to add a new model, it refused to actually download the safetensor file.

Everything downloads correctly, but not the 7.45 GB safetensor file, which results in it failing to launch.

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

Add in the required lines to download the model from this link: https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g/tree/main

Or go off of this horrible image:

![image](https://user-images.githubusercontent.com/88058724/230690481-ec985e69-500e-47e1-8aaf-ba4bd03365ce.png)

It downloads the rest of the files just fine, except for the 7.45 GB safetensor file that is required for it to run.

### Screenshot

![image](https://user-images.githubusercontent.com/88058724/230689793-4dedc4ce-2e25-4718-bcd0-cf834aa77354.png)

### Logs

```shell
There are no errors during the download, but refused to launch because it is missing the file in question.
```

### System Info

```shell
I am using free tier Google Colab to run this.
```

**Comment by catalpaaa** [comment]
git clone the model repo is an alternative

**Comment by cat-thing** [comment]
Partially fixed the problem, it refused to boot anyways.
