### ISSUE TITLE
UserWarning: TypedStorage is deprecated

### ISSUE THREAD

**Issue by Originalimoc** [oobabooga/text-generation-webui#910]
### Describe the bug

1. Warning. not a bug.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

python server.py --auto-devices --verbose --wbits 4 --listen --groupsize 128 --model llama-7B-Int4-128G

### Logs

```shell
/safetensors/torch.py:99: UserWarning...
/torch/storage.py:899: UserWarning...
/storage.py:899: UserWarning...

UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
```

### System Info

```shell
WSL, CUDA, conda python 3.10
```

**Comment by kanosy88** [comment]
same issue

**Comment by jllllll** [comment]
Just a warning letting devs know that future versions of Torch will not have those classes.

**Comment by mcmonkey4eva** [comment]
You don't need to worry about that at all, doesn't affect anything for users. (As said above, it's a notice to devs).

**Comment by Originalimoc** [comment]
Well... Later.

**Comment by pollardfreek** [comment]
I get this warning as well followed by "Press any key to continue" But then it exits. I am able to run the CPU version, but when I run the GPU version this happens. Ryzen 7 3700x and 2070 Super

**Comment by mcmonkey4eva** [comment]
This specific error message is not the cause of it crashing and exiting @pollardfreek , open your own issue with a full log + system specs and we can figure it out from there

**Comment by pollardfreek** [comment]
Someone posted in another thread suggested manually adjusting page file and that worked for me, I was able to get the UI open. However, if I try running a prompt I get CUDA out of memory issues. I've tried adjusting the threads and pre-layers but no luck. I saw someone suggest I try using anaconda instead of powershell, maybe I'll try that. I think my 2070 Super is just too puny for the larger models (I think 30b). Thank you for your reply!

**Comment by jllllll** [comment]
> Someone posted in another thread suggested manually adjusting page file and that worked for me, I was able to get the UI open. However, if I try running a prompt I get CUDA out of memory issues. I've tried adjusting the threads and pre-layers but no luck. I saw someone suggest I try using anaconda instead of powershell, maybe I'll try that. I think my 2070 Super is just too puny for the larger models (I think 30b). Thank you for your reply!

You need 24gb vram minimum to run 30b models and would still likely need to offload to cpu. There's no way you are running a 30b model on a 2070 Super. If you want to run 30b models and happen to have at least 32gb of ram, then you can use ggml models with llama.cpp.

**Comment by mcmonkey4eva** [comment]
Actually, 30B is runnable on a 24GiB VRAM card now thanks to 3bit - 30b-3bit-gr128 takes about 15GiB VRAM base raising up to around 20GiB with a fully loaded input context.
(Still way too much for a 2070's 8 GiB VRAM, but, ...)

**Comment by pollardfreek** [comment]
Is there any way I can run the vicuna I installed on a lower parameter model? Is it even worth it?

**Comment by bigseba47** [comment]
Hi, people, I get the DEPRECATED error all the time, I have a RTX 3060 with 12gb and there's no way I can make this work :(
