### ISSUE TITLE
Implement FlexGen support

### ISSUE THREAD

**Issue by oobabooga** [oobabooga/text-generation-webui#92]
https://github.com/Ying1123/FlexGen

Usage example: https://github.com/Ying1123/FlexGen/blob/main/apps/chatbot.py

**Comment by oobabooga** [comment]
Done

https://github.com/oobabooga/text-generation-webui/wiki/FlexGen

**Comment by conanak99** [comment]
Hi @oobabooga , how is the RAM/VRAM the 6B modal consume with Flexgen support?
