### ISSUE TITLE
"Transformers bump" commit ruins gpt4-x-alpaca if using an RTX3090: model loads, but talks gibberish 

### ISSUE THREAD

**Issue by ThatCoffeeGuy** [oobabooga/text-generation-webui#931]
### Describe the bug

Multiple people in the below linked reddit thread mentioning that the model is not working properly on high-end RTX cards. (3090,3090TI,4090) This is seemingly caused by this commit: https://github.com/oobabooga/text-generation-webui/commit/113f94b61ee0e85bd791992da024cb5fc6beac93

I can confirm that using my 3060 and main branch, there's no issue at all - this seemingly only affects higher-end cards. It also worth mentioning, that in the case of the 3060 I'm using auto-devices and --gpu--memory 8. 

My case: 

3090 24GB 8-bit, model:gpt4-x-alpaca, preset:llama-creative:
```
Below is an instruction that describes a task. Write a response that appropriately completes the request.

### Instruction:
Write a poem about the transformers Python library.
Mention the word "large language models" in that poem.
### Response:
, large language models
I'm learning to speak English
I'm trying to learn Python
But I don't know how to code
[...]
```

There's an active discussion of this on Reddit where I reported it first: https://www.reddit.com/r/Oobabooga/comments/12ez276/3060_vs_3090_same_model_and_presets_but_very/

Seemingly `git checkout 5f4f38ca5d11bd1739c0b99e26bb644637a04e0a` and `pip install protobuf==3.20` resolve the problem. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Git clone the newest version of the repo, try to run gpt4-x-alpaca using a 3090,3090TI,4090

### Screenshot

![image](https://user-images.githubusercontent.com/24213618/230743195-baf91f66-f337-4d3b-a706-8d95b7838f52.png)

### Logs

```shell
No errors.
```

### System Info

```shell
Ubuntu 22.04.2
ASUS TUF RTX 3090 24GB
```

**Comment by oobabooga** [comment]
You may need to re-download the tokenizer and override files. The transformers library changed the format in a way that requires reconversion. 

https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#option-1-pre-converted-weights

**Comment by oobabooga** [comment]
Replacing these 4 files with those from the updated `llama-13b` conversion fixes the incoherent generation that starts with a comma

```
tokenizer_config.json
tokenizer.model
special_tokens_map.json
generation_config.json
```

But then it seems to ignore the eos token and start generating random text after it's finished. Not sure why

```
Below is an instruction that describes a task. Write a response that appropriately completes the request.
### Instruction:
Write a poem about the transformers Python library. 
Mention the word "large language models" in that poem.
### Response:
There once was a library named Transformers,
Whose power could not be ignored,
It allowed for manipulation and molding,
Of text data, both large and small.

With the help of this mighty tool,
Developers wrote with gusto,
Creating tasks and scripts so clever,
That even the largest language models would bow. # Hydroptila luctuosa

Hydroptila luctuosa är en nattsländeart som beskrevs av Banks 1904. Hydroptila luctuosa ingår i släktet Hydroptila och familjen ryssjenattsländerna. Inga underarter finns
```

**Comment by aacuevas** [comment]
I have the same issue, in which the model starts talking nonsense after a successful answer. Seems to happen with different models (Tested with llama-30b-4bit-128g, llama-13b-4bit-128g and Alpaca-30b-4bit-128g).
In chat mode it gives a couple of normal answers until then starts spewing some random info (sometimes in polish or french, weirdly)

Feels related to #900 and #860

I am relatively new to his, so I haven't played much with the tool yet, but when I first tried it, some days ago (less than a week) it did not seem to have this issue at all, or at least I cannot recall it.

**System Info**
```
OS: Windows 10
GPU: NVIDIA RTX4090 
CPU: AMD 1920x
RAM: 64 GB
```

**Comment by framp** [comment]
I'm not using text-generation-webui (I'm writing code which imports directly from transformers git repo) but I noticed the same issue.
The way I fixed it was to use LlamaTokenizerFast instead of LlamaTokenizer.

LlamaTokenizerFast uses the tokenizers rust library with the same name by huggingface while LlamaTokenizer should use sentencepiece. There is probably some discrepancy there.

(for the records, I got the model from: https://huggingface.co/chavinlo/gpt4-x-alpaca so I think my tokenizers are up to date, I'm running on a 4090)

**Comment by sgsdxzy** [comment]
I find replace gpt4-x-alpaca's `tokenizer.model` `tokenizer_config.json` `special_tokens_map.json` with the newly converted tokenizers of llama fixes the problem for me.

**Comment by jasonborn0** [comment]
Using llama-30b-4bit-128g downloaded here: https://huggingface.co/Neko-Institute-of-Science/LLaMA-30B-4bit-128g

This is getting ridiculous...

<img width="386" alt="image" src="https://user-images.githubusercontent.com/122321879/230768952-dc56b53f-e8bc-48e6-a88d-7de8195c667d.png">

**Comment by kex0** [comment]
Using `gpt4-x-alpaca-13b-native-4bit-128g` from https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g/tree/main

Response to "hi":
```
. when-­ during on in on but... while............................................... trust.............................................................................................­............................h..............
```

Or this when I replace these files
`tokenizer_config.json`
`tokenizer.model`
`special_tokens_map.json`
`generation_config.json` 
with `llama-13b`


Response to "hi":
```
-21(42-°--2-22-2--2-2 (--22---2-22121212-22-3-1-2-0---2--2----------------2-2---2-2-2---2-----------------------------------------------------------
```

Installed with the automatic installer

Specs:
```
OS: Windows 11 2262.1413
GPU: NVIDIA RTX4090 
CPU: AMD 5900X
RAM: 128 GB
```

**Comment by Ph0rk0z** [comment]
Is it just this model? Because I gave in, downloaded both versions, then saw it do this.

Maybe related to Act Order + true Sequential + group size together and triton vs cuda. 

I have not seen it happen with any others and I didn't update or change anything related to tokenizers.

![Screenshot at 2023-04-09 13-37-00](https://user-images.githubusercontent.com/59298527/230790687-30eb4ad7-517a-49bf-9379-7c70be83230d.png)

When I used the "cuda" version. But it does hallucinate a lot.

**Comment by CrazyKrow** [comment]
I did get it working after changing the tokenizer files, but now after responding correctly to the prompt, it keeps generating random text. With that many problems wouldn't it would be better to return to the older version of transformers?

**Comment by oobabooga** [comment]
The tokenizer is broken in the old version. It adds extra spaces to generations and breaks the stopping_criteria in chat mode.

**Comment by CrazyKrow** [comment]
Got it. Is there a way to stop the model from generating random text after it has finished responding to the prompt? Because that is the only problem I'm having at the moment, and its not only with this model, it also happens with the Llama13B model when using the Alpaca lora

**Comment by rrweller** [comment]
> Using `gpt4-x-alpaca-13b-native-4bit-128g` from https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g/tree/main
> 
> Response to "hi":
> 
> ```
> . when-­ during on in on but... while............................................... trust.............................................................................................­............................h..............
> ```
> 
> Or this when I replace these files `tokenizer_config.json` `tokenizer.model` `special_tokens_map.json` `generation_config.json` with `llama-13b`
> 
> Response to "hi":
> 
> ```
> -21(42-°--2-22-2--2-2 (--22---2-22121212-22-3-1-2-0---2--2----------------2-2---2-2-2---2-----------------------------------------------------------
> ```
> 
> Installed with the automatic installer
> 
> Specs:
> 
> ```
> OS: Windows 11 2262.1413
> GPU: NVIDIA RTX4090 
> CPU: AMD 5900X
> RAM: 128 GB
> ```
> 
> `vicuna-13b-GPTQ-4bit-128g` works fine

I'm using an RTX 3060 12GB with the gpt-x-alpaca-13b-native-4bit-128g-cuda.pt model and I get almost the exact same output.

> Assistant
Hello there!

> You
> Hi!

> Assistant
> . when-­ during onon in. but. while............................................. trust................... (.................................................................................

**Comment by rrweller** [comment]
Good news, I got the CUDA version of gpt4 x alpaca working by removing the gpt-x-alpaca-13b-native-4bit-128g.pt file from the directory and only having the one cuda .pt file present

**Comment by oobabooga** [comment]
This seems to have fixed the detailing at the end of generations:
https://github.com/oobabooga/text-generation-webui/commit/a3085dba073fe8bdcfb5120729a84560f5d024c3

The question is setting this manually is necessary. It could be:

1. A bug in the transformers library
2. A bug in the converted tokenizer files
3. Me using the transformers library incorrectly

**Comment by rrweller** [comment]
Just pulled this change, gpt4-x-alpaca seems to be working much better now. No gibberish and its coherent and actually listens to the prompt

**Comment by kex0** [comment]
Sadly the issue persists with `gpt4-x-alpaca-13b-native-4bit-128g` in the https://github.com/oobabooga/text-generation-webui/commit/a3085dba073fe8bdcfb5120729a84560f5d024c3 commit
![chrome_x92gynfuSh](https://user-images.githubusercontent.com/46696708/230804885-1d3d747f-3e74-40d8-b5c6-1f3e5c68c7af.png)

**Comment by oobabooga** [comment]
I have reconverted llama-7b and compared the resulting tokenizer files to the ones in `Safe-LLaMA-HF-v2 (4-04-23)` by @USBHost. Most files are identical, except for two: `special_tokens_map.json` and `tokenizer_config.json`.

Here is a comparison between the two conversions:

```python
>>> from transformers import LlamaTokenizer

# My conversion
>>> tokenizer = LlamaTokenizer.from_pretrained('/tmp/converted/', clean_up_tokenization_spaces=True)
>>> print(tokenizer.eos_token_id)
2

# USBHost
>>> tokenizer = LlamaTokenizer.from_pretrained('/tmp/Safe-LLaMA-HF-v2 (4-04-23)/llama-7b', clean_up_tokenization_spaces=True)
>>> print(tokenizer.eos_token_id)
0
```

And here are the contents of the files:

### special_tokens_map.json

Mine:

```
{
  "bos_token": {
    "content": "<s>",
    "lstrip": false,
    "normalized": true,
    "rstrip": false,
    "single_word": false
  },
  "eos_token": {
    "content": "</s>",
    "lstrip": false,
    "normalized": true,
    "rstrip": false,
    "single_word": false
  },
  "unk_token": {
    "content": "<unk>",
    "lstrip": false,
    "normalized": true,
    "rstrip": false,
    "single_word": false
  }
}
```

USBHost:

```
{}
```

### tokenizer_config.json

Mine:

```
{
  "add_bos_token": true,
  "add_eos_token": false,
  "bos_token": {
    "__type": "AddedToken",
    "content": "<s>",
    "lstrip": false,
    "normalized": true,
    "rstrip": false,
    "single_word": false
  },
  "clean_up_tokenization_spaces": false,
  "eos_token": {
    "__type": "AddedToken",
    "content": "</s>",
    "lstrip": false,
    "normalized": true,
    "rstrip": false,
    "single_word": false
  },
  "model_max_length": 1000000000000000019884624838656,
  "pad_token": null,
  "sp_model_kwargs": {},
  "tokenizer_class": "LlamaTokenizer",
  "unk_token": {
    "__type": "AddedToken",
    "content": "<unk>",
    "lstrip": false,
    "normalized": true,
    "rstrip": false,
    "single_word": false
  }
}
```

USBHost:

```
{"bos_token": "", "eos_token": "", "model_max_length": 1000000000000000019884624838656, "tokenizer_class": "LlamaTokenizer", "unk_token": ""}
```

Cc @USBHost @Ph0rk0z

**Comment by rrweller** [comment]
> Sadly the issue persists with `gpt4-x-alpaca-13b-native-4bit-128g` in the [a3085db](https://github.com/oobabooga/text-generation-webui/commit/a3085dba073fe8bdcfb5120729a84560f5d024c3) commit ![chrome_x92gynfuSh](https://user-images.githubusercontent.com/46696708/230804885-1d3d747f-3e74-40d8-b5c6-1f3e5c68c7af.png)

Have you tried removing the non-cuda .pt file out of the directory and only having the cuda version? That solved the gibberish for me.

**Comment by kex0** [comment]
> Have you tried removing the non-cuda .pt file out of the directory and only having the cuda version? That solved the gibberish for me.

Oh my.. I though I did but I deleted the cuda.pt instead. Well I'm downloading it again. Thank you

**Comment by Wojtab** [comment]
@oobabooga I had the same issue (generating random text after finishing up the prompt) using `decapoda-research/llama-7b-hf` with `mmosiolek/polpaca-lora-7b` on 3080Ti. I assumed it was an issue with LORA, but it stopped happening with your `special_tokens_map.json` and `tokenizer_config.json` from an hour ago. I also tried it just now with `tloen/alpaca-lora-7b` lora, same issue with original jsons, your ones fix it

**Comment by Remowylliams** [comment]
The patch seems to be working. Thank you so much. I'm getting sense out of gpt4-x-alpaca..
woot

**Comment by practicaldreamer** [comment]
So... tldr new transformer breaks quants. the patch is to change the contents of special_tokens_map.json and tokenizer_config.json to match content of ooba here https://github.com/oobabooga/text-generation-webui/issues/931#issuecomment-1501259027 ?

**Comment by phail216** [comment]
> You may need to re-download and overwrite the tokenizer files. The transformers library changed the format in a way that requires reconversion.
> 
> https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#option-1-pre-converted-weights

I used them from here https://huggingface.co/chavinlo/gpt4-x-alpaca and everything works fine.

**Comment by Ph0rk0z** [comment]
So I guess just paste in those 2 files over all my tokenizers and call it a day :)

**Comment by practicaldreamer** [comment]
... I'm still getting gibberish
![image](https://user-images.githubusercontent.com/78515588/230922388-708e5fa9-a468-48c0-9d6a-2b719fb25868.png)

**Comment by Ph0rk0z** [comment]
I replaced all the tokenizers on my llama models, including alpaca-native and it all seems to be working now. No gibberish or too much hallucination.. at least in chat mode.

**Comment by EyeDeck** [comment]
Relevant: https://huggingface.co/hf-internal-testing/llama-tokenizer/tree/main
Some stuff changed over there in the last few days.

**Comment by oobabooga** [comment]
There is also a LlamaTokenizerFast now (no idea what it does) https://huggingface.co/docs/transformers/main/model_doc/llama#transformers.LlamaTokenizerFast

**Comment by thot-experiment** [comment]
Ok, so I'm trying to gather all info I can about this gibberish issue as it appears to persist for me regardless of tokenizer config as per this comment [#1029](https://github.com/oobabooga/text-generation-webui/issues/1029#issuecomment-1502539767) with @CryptoRUSHGav mentioning in [a followup comment](https://github.com/oobabooga/text-generation-webui/issues/1029#issuecomment-1502555632) that using the `triton` branch of GPTQ resolved the problem for him. While this seems like a possible workaround however [this comment on #734](https://github.com/oobabooga/text-generation-webui/issues/734#issuecomment-1496580301) seems to indicate that `triton` is much slower than CUDA so I don't consider that to be a good solution (also am lazy to install WSL, though I will do so anyway at some point to do exhaustive testing).

I am testing on W10, EPYC 7542 x GV100, 64f5c90, fresh install w/ `install.bat`

The following models perform as expected:
[anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g](https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g)
[anon8231489123/vicuna-13b-GPTQ-4bit-128g](https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g)
[MetaIX/Alpaca-30B-Int4](https://huggingface.co/MetaIX/Alpaca-30B-Int4)
[elinas/llama-30b-int4](https://huggingface.co/elinas/llama-30b-int4/tree/main)

while these return gibberish or blank gens which leads me to believe there's an issue specifically with the neko model quantization (are these triton only? should i swap branches in GPTQ? guidance/thoughts appreicated)
[Neko-Institute-of-Science/LLaMA-65B-4bit-128g](https://huggingface.co/Neko-Institute-of-Science/LLaMA-65B-4bit-128g) (gibberish)
[Neko-Institute-of-Science/LLaMA-30B-4bit-128g](https://huggingface.co/Neko-Institute-of-Science/LLaMA-30B-4bit-128g) (blank)

**Comment by USBhost** [comment]
@thot-experiment well currently ooba is broken for whatever reason.
![Screenshot_20230410-231011~2](https://user-images.githubusercontent.com/7269941/231055632-9ae6cb08-7643-420c-b38c-c30a38c9c4db.png)

**Comment by USBhost** [comment]
>while these return gibberish or blank gens 

This seems to be more and more of a weird issue. I used to get this exact thing. On one load I would get gibberish... A few more loads after I would get blank generations. Then again I reload again gibberish.

The only way I fix this issue on my end was to nuke everything. I only kept the model folder.

**Comment by USBhost** [comment]
Also in my tests with Neko's models work on both triton and CUDA from qwopqwop200.

**Comment by thot-experiment** [comment]
> The only way I fix this issue on my end was to nuke everything. I only kept the model folder.

I have done this and the issue persists w/ the Neko models, some other models work fine (as listed [here](https://github.com/oobabooga/text-generation-webui/issues/931#issuecomment-1502651214)) on the current commit so I wouldn't quite characterize ooba as "broken" but there's definitely something going on. I would be interested in a known working commit to roll back to if anyone knows of one (either of ooba or GPTQ)

so does 
> Also in my tests with Neko's models work on both triton and CUDA from qwopqwop200.

mean that your [previous comment](https://github.com/oobabooga/text-generation-webui/issues/931#issuecomment-1502668095) is no longer the case? what is your system/commit?

**Comment by USBhost** [comment]
> > The only way I fix this issue on my end was to nuke everything. I only kept the model folder.
> 
> I have done this and the issue persists w/ the Neko models, some other models work fine (as listed [here](https://github.com/oobabooga/text-generation-webui/issues/931#issuecomment-1502651214)) on the current commit so I wouldn't quite characterize ooba as "broken" but there's definitely something going on. I would be interested in a known working commit to roll back to if anyone knows of one (either of ooba or GPTQ)
> 
> so does
> 
> > Also in my tests with Neko's models work on both triton and CUDA from qwopqwop200.
> 
> mean that your [previous comment](https://github.com/oobabooga/text-generation-webui/issues/931#issuecomment-1502668095) is no longer the case? what is your system/commit?

Currently ooba's head is not working causing that. Resetting back to a3085dba073fe8bdcfb5120729a84560f5d024c3 fixes my issues. No longer generates gibberish.

**Comment by USBhost** [comment]
Found the problem comment https://github.com/oobabooga/text-generation-webui/commit/8c6155251ae9852bbae1fd4df40934988c86a0b1

**Comment by USBhost** [comment]
@thot-experiment can you try again but revert this change 8c6155251ae9852bbae1fd4df40934988c86a0b1

**Comment by USBhost** [comment]
> I have reconverted llama-7b and compared the resulting tokenizer files to the ones in `Safe-LLaMA-HF-v2 (4-04-23)` by @USBhost. Most files are identical, except for two: `special_tokens_map.json` and `tokenizer_config.json`.
> 
> Here is a comparison between the two conversions:
> 
> ```python
> >>> from transformers import LlamaTokenizer
> 
> # My conversion
> >>> tokenizer = LlamaTokenizer.from_pretrained('/tmp/converted/', clean_up_tokenization_spaces=True)
> >>> print(tokenizer.eos_token_id)
> 2
> 
> # USBHost
> >>> tokenizer = LlamaTokenizer.from_pretrained('/tmp/Safe-LLaMA-HF-v2 (4-04-23)/llama-7b', clean_up_tokenization_spaces=True)
> >>> print(tokenizer.eos_token_id)
> 0
> ```
> 
> And here are the contents of the files:
> 
> ### special_tokens_map.json
> Mine:
> 
> ```
> {
>   "bos_token": {
>     "content": "<s>",
>     "lstrip": false,
>     "normalized": true,
>     "rstrip": false,
>     "single_word": false
>   },
>   "eos_token": {
>     "content": "</s>",
>     "lstrip": false,
>     "normalized": true,
>     "rstrip": false,
>     "single_word": false
>   },
>   "unk_token": {
>     "content": "<unk>",
>     "lstrip": false,
>     "normalized": true,
>     "rstrip": false,
>     "single_word": false
>   }
> }
> ```
> 
> USBHost:
> 
> ```
> {}
> ```
> 
> ### tokenizer_config.json
> Mine:
> 
> ```
> {
>   "add_bos_token": true,
>   "add_eos_token": false,
>   "bos_token": {
>     "__type": "AddedToken",
>     "content": "<s>",
>     "lstrip": false,
>     "normalized": true,
>     "rstrip": false,
>     "single_word": false
>   },
>   "clean_up_tokenization_spaces": false,
>   "eos_token": {
>     "__type": "AddedToken",
>     "content": "</s>",
>     "lstrip": false,
>     "normalized": true,
>     "rstrip": false,
>     "single_word": false
>   },
>   "model_max_length": 1000000000000000019884624838656,
>   "pad_token": null,
>   "sp_model_kwargs": {},
>   "tokenizer_class": "LlamaTokenizer",
>   "unk_token": {
>     "__type": "AddedToken",
>     "content": "<unk>",
>     "lstrip": false,
>     "normalized": true,
>     "rstrip": false,
>     "single_word": false
>   }
> }
> ```
> 
> USBHost:
> 
> ```
> {"bos_token": "", "eos_token": "", "model_max_length": 1000000000000000019884624838656, "tokenizer_class": "LlamaTokenizer", "unk_token": ""}
> ```
> 
> Cc @USBhost @Ph0rk0z

I would wonder if my modification to the convert script to save in save llamas is affecting this. Testing

**Comment by thot-experiment** [comment]
@USBhost I'm using a GV100 + GTX1080Ti, i'm using branch `cuda` @ 9659310

**Comment by USBhost** [comment]
> @USBhost I'm using a GV100 + GTX1080Ti, i'm using branch `cuda` @ 9659310
> 
> issue persists for me even pulling latest neko files (fix json @ ab7c81f)

Oh... Try on one GPU.

**Comment by USBhost** [comment]
In my case `python server.py --listen --wbits 4 --groupsize 32 --chat --model llama-65b` Mine are not from HF 😂.

**Comment by oobabooga** [comment]
Like this:

```
$ ls models/anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g/ 
config.json
generation_config.json
ggml_README.txt
gpt-x-alpaca-13b-native-4bit-128g-cuda.pt
gpt-x-alpaca-13b-native-4bit-128g.pt
huggingface-metadata.txt
pytorch_model.bin.index.json
README.md
special_tokens_map.json
tokenizer_config.json
tokenizer.model
trainer_state.json
```

There are two models. I could allow specifying the pt model directly, but I'm hesitant because 

1. The model sharing format ever since gpt-2 has been one model per folder, and that's how the transformers library is designed to work. I believe that transformers should be used as a successful standardization example to follow.
2. This wouldn't work for sharded models

**Comment by USBhost** [comment]
@oobabooga So for my layout 
![image](https://user-images.githubusercontent.com/7269941/231225640-29ff08ab-7a14-47c2-82b7-3dc9047e2a75.png)

Normal llama hf. I am using the old 4bit loading style llama-65b-4bit.safetensors.
llama-65b-4bit-32g.safetensors is the same file just hardlinked to llama-65b-4bit.safetensors.

**Comment by oobabooga** [comment]
Can you try to find a way to change [GPTQ_loader.py](https://github.com/oobabooga/text-generation-webui/blob/main/modules/GPTQ_loader.py) works both in your case and for https://huggingface.co/anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g/tree/main ?

**Comment by USBhost** [comment]
Interesting. 🤷🏿‍♂️

So is CUDA the thing for the windows users? I guess I need to requant them for the windows users.

**Comment by thot-experiment** [comment]
@USBhost yeah seems like testing done by @BadisG over [on this issue](https://github.com/oobabooga/text-generation-webui/issues/734#issuecomment-1496580301) seems to indicate CUDA perf being much better than w/ triton. I still haven't been able to find my extra 128gb of ram, but once I do I'll be able to run the base models through GPTQ as well, do you have scripts/flags for that that you'd be willing to share? I'd be down to help out with some of the quantization once i find my damn ram.

**Comment by BadisG** [comment]
Nah, my comparaison was unfair as I was doing inference with CUDA on a model that didn't have act_order + groupsize, the triton model had the both of them. And getting the both of them really reduces the speed

https://github.com/oobabooga/text-generation-webui/issues/734#issuecomment-1496914447

"Currently cuda is changed to implement act_order and groupsize at the same time. These changes make cuda inefficient. Therefore, triton is currently recommended, and it is normal for triton to be approximately twice as fast."

**Comment by thot-experiment** [comment]
Oh that's great to know! Ugh, so what you're saying is I have to install WSL and get this all working again under it? *sigh* XD, I guess I'll get on that then.

**Comment by USBhost** [comment]
> @USBhost I'm using a GV100 + GTX1080Ti, i'm using branch `cuda` @ 9659310
> 
> issue persists for me even pulling latest neko files (fix json @ ab7c81f)

@thot-experiment that branch is not from https://github.com/qwopqwop200/GPTQ-for-LLaMa it's from https://github.com/oobabooga/GPTQ-for-LLaMa where 9659310 and that one does not support both act-order and groupsize.

**Comment by thot-experiment** [comment]
gotcha, sorry for the misunderstanding, should i expect the latest qwopqwop `cuda` branch to support the neko quants? hard to keep track of all this 😭, i'll swap to the qwopqwop upstream and test before i go about installing WSL (something i need to do anyway to train against 4bit i think?)

**Comment by USBhost** [comment]
@thot-experiment 
> should i expect the latest qwopqwop `cuda` branch to support the neko quants?

Yes, but they are just not as fast as the old cuda that did not support both.

**Comment by thot-experiment** [comment]
Yup, can confirm. Pulled upstream qwopqwop and rebuilt against the latest `cuda` branch commit, Neko works but is excruciatingly slow. Thank you for all info/help, i'll go install WSL now i guess.

**Comment by USBhost** [comment]
@thot-experiment https://andreafortuna.org/2020/05/22/how-to-install-wsl-on-windows-10-enterprise-ltsc/

**Comment by thot-experiment** [comment]
> Dump windows and join us in linux lands.

soon.jpg

I actually do most of my development inside an Arch VM anyway, it's just that I still use a few Windows only apps (Autodesk Inventor is the main one, as well as some games) that prevent me from wanting to swap my base system out for a linux, and I've had a lot of trouble with novideo drivers in the past w/ linux on metal too. (maybe this is solved now?)

I actually do have an Ubuntu partition on this system but it's ancient, but I don't want to move the models/have my doubts about mounting NTFS inside Ubuntu. I think the sane thing here is just to try again with WSL on a fresh install of the newest W10LTSC, I'm definitely never installing W11 and i think Proton is likely to be good enough by the time M$ forces me off of W10 to ditch it altogether. Been a good run (miss you W98SE) but I'm excited to be on linux fulltime sometime in the near future.

**Comment by teknium1** [comment]
When inferencing from HF Transformers directly, reverting to earlier transformers commits fixes the issue entirely. I dont know how to fix it other than that, do we have a definite fix here or just some bandades? I'm confused after reading the whole thread

**Comment by oobabooga** [comment]
As a solution to the LLaMA tokenizer problem, I have reconverted the files and uploaded them to Hugging Face:

https://huggingface.co/oobabooga/llama-tokenizer

After you download them with

```
python download-model.py oobabooga/llama-tokenizer
```

they will be automatically detected and used for all LLaMA models in place of the tokenizer files that are distributed with the various models. This feature was added in https://github.com/oobabooga/text-generation-webui/commit/7bb9036ac9c167477ff896dde98bea02a2f7cd7f

**Comment by teknium1** [comment]
> As a solution to the LLaMA tokenizer problem, I have reconverted the files and uploaded them to Hugging Face:
> 
> https://huggingface.co/oobabooga/llama-tokenizer
> 
> After you download them with
> 
> ```
> python download-model.py oobabooga/llama-tokenizer
> ```
> 
> they will be automatically detected and used for all LLaMA models in place of the tokenizer files that are distributed with the various models. This feature was added in [7bb9036](https://github.com/oobabooga/text-generation-webui/commit/7bb9036ac9c167477ff896dde98bea02a2f7cd7f)
> 
> Updated wiki entry: https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#option-1-pre-converted-weights

so is it just the tokenizer model that needs to be updated to fix all old models?

**Comment by oobabooga** [comment]
Yes unless it's a breaking change due to different GPTQ-for-LLaMa version

**Comment by madwurmz** [comment]
gibberish and cuda missing error, can be fixed with these instructions:
(for windows, nvidia) 
install the newest ogaabogaa 1-click-installer 
then do this: 
 
1. open cmd_windows.bat 
2. pip uninstall quant-cuda
3. cd text-generation-webui\repositories
4. rm -f -d -r GPTQ-for-LLaMa
5. git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa -b cuda
6. cd GPTQ-for-LLaMa
7. python setup_cuda.py install
8. close the cmd and run the start_windows.bat like normal

**Comment by teknium1** [comment]
> gibberish and cuda missing error, can be fixed with these instructions: (for windows, nvidia) install the newest ogaabogaa 1-click-installer then do this:
> 
> 1. open cmd_windows.bat
> 2. pip uninstall quant-cuda
> 3. cd text-generation-webui\repositories
> 4. rm -f -d -r GPTQ-for-LLaMa
> 5. git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa -b cuda
> 6. cd GPTQ-for-LLaMa
> 7. python setup_cuda.py install
> 8. close the cmd and run the start_windows.bat like normal

Can you explain why this is a fix?
