### ISSUE TITLE
Why not using python venv instead of conda?

### ISSUE THREAD

**Issue by DaniAndTheWeb** [oobabooga/text-generation-webui#952]
What's the reason of using conda instead of python venv to create the virtual environment to install the python dependencies? Coming from a linux environment (arch) it's much easier and clean a normal python installation rather than a conda one which requires additional manual steps. Is there any more work done by conda other than the managing of python packages in the virtual environment? If not it may be better to switch to venv in order to have an easier install for linux users.

**Comment by 2blackbar** [comment]
easy to do on your own, especially with bing chat

**Comment by oobabooga** [comment]
Not all packages in conda are in pypl, and conda allows multiple environments to share the same files.

There is a requirements.txt, you are free to use venv and install the pytorch/cuda stuff through other means, since that's what conda is directly used for.
