### ISSUE TITLE
won't load gpt4-x-alpaca-13b-native-4bit-128g

### ISSUE THREAD

**Issue by yami-no-tusbas** [oobabooga/text-generation-webui#955]
### Describe the bug

start-webui arguments : `call python server.py --auto-devices --chat --wbits 4 --groupsize 128`
Model : `gpt-x-alpaca-13b-native-4bit-128g-cuda.pt`
Instructions found at : https://www.youtube.com/watch?v=nVC9D9fRyNU

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Fresh installed everything, tried with the `facebook_opt-350m` model and worked fine, but when trying to load `gpt4-x-alpaca-13b-native-4bit-128g` it just crash even before using up any memory at all.

### Logs

```shell
Starting the web UI...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: F:\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary F:\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
The following models are available:

1. facebook_opt-350m
2. gpt4-x-alpaca-13b-native-4bit-128g

Which one do you want to load? 1-2

2

Loading gpt4-x-alpaca-13b-native-4bit-128g...
Traceback (most recent call last):
  File "F:\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "F:\oobabooga-windows\text-generation-webui\modules\models.py", line 102, in load_model
    model = load_quantized(model_name)
  File "F:\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 135, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "F:\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 54, in _load_quant
    make_quant(**make_quant_kwargs)
  File "F:\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 446, in make_quant
    make_quant(child, names, bits, groupsize, faster, name + '.' + name1 if name != '' else name1, kernel_switch_threshold=kernel_switch_threshold)
  File "F:\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 446, in make_quant
    make_quant(child, names, bits, groupsize, faster, name + '.' + name1 if name != '' else name1, kernel_switch_threshold=kernel_switch_threshold)
  File "F:\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 446, in make_quant
    make_quant(child, names, bits, groupsize, faster, name + '.' + name1 if name != '' else name1, kernel_switch_threshold=kernel_switch_threshold)
  [Previous line repeated 1 more time]
  File "F:\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 443, in make_quant
    module, attr, QuantLinear(bits, groupsize, tmp.in_features, tmp.out_features, faster=faster, kernel_switch_threshold=kernel_switch_threshold)
  File "F:\oobabooga-windows\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 154, in __init__
    'qweight', torch.zeros((infeatures // 32 * bits, outfeatures), dtype=torch.int)
RuntimeError: [enforce fail at C:\cb\pytorch_1000000000000\work\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 13107200 bytes.
Press any key to continue . . .
```

### System Info

```shell
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 25 Model 97 Stepping 2 AuthenticAMD ~3801 Mhz
Total Physical Memory:     32.502 MB
Available Physical Memory: 24.159 MB
Virtual Memory: Max Size:  40.694 MB
Virtual Memory: Available: 30.186 MB
Virtual Memory: In Use:    10.508 MB
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621

GPU : NVIDIA GeForce RTX 4090
GPU Driver : Game Ready Driver 531.41

ENV :
(F:\oobabooga-windows\installer_files\env) F:\oobabooga-windows>python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:14:58) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 531.41
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3801
DeviceID=CPU0
Family=107
L2CacheSize=6144
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3801
Name=AMD Ryzen 5 7600 6-Core Processor
ProcessorType=3
Revision=24834

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchvision==0.15.0
[conda] Could not collect
```

**Comment by MancV21** [comment]
Same here.

**Comment by omar-shatla** [comment]
Same problem.. hopefully there is a solution.

**Comment by Daviljoe193** [comment]
Likely the same issue as #945

**Comment by Gilgames000** [comment]
Exactly the same here, but on Windows 10 and with a 3090 Ti.

**Comment by rosx27** [comment]
exactly the same here.

**Comment by python7878** [comment]
Any luck, did anyone tried modifing pytorch parameters ?

**Comment by SuperFurias** [comment]
This thing (out of memory) is waay "too common" to be a normal "out of memory" error.
its definitely a bug.
maybe a memory leak that breaks some specific installations.
its impossible that a person with a ducking 4090 doesn't have enough vram to run it.

**Comment by Anonimouche** [comment]
I  don't know if it's a bug or really a lack of memory but i managed to workaround the issue by using 120Gb of my harddrive as virtual memory. It seems a bit slow but i don't know if it's due to me having only a 1660 6Gb or the effect of the workaround.

**Comment by MancV21** [comment]
> 

Virtual memory is going to be WAY slower than real memory so I suspect it's more that than your lack of VRAM.

**Comment by Anonimouche** [comment]
Played around with the parameters, I use my card 100% now, it's still very slow but at least i'm able to load the model

**Comment by yami-no-tusbas** [comment]
> This thing (out of memory) is waay "too common" to be a normal "out of memory" error. its definitely a bug. maybe a memory leak that breaks some specific installations. its impossible that a person with a ducking 4090 doesn't have enough vram to run it.

Yep this can not be a oom error, since it doesn't even load anything in memory before failling. It is instantaneous with this model 24gb VRAM + 32GB RAM, let say 24vram+22free ram should be enough to load the model, and after that there is the hard driveitslef with over 600Gb free and the sawp memory on the sdd. No it's nothing to do with the memory requirement, it's just a bug. Maybe the program don't see the memory or something.

**Comment by oobabooga** [comment]
This change should have made it easier to load this model https://github.com/oobabooga/text-generation-webui/commit/8c6155251ae9852bbae1fd4df40934988c86a0b1

I have managed to load it with this command without deleting anything:

```
python server.py --model anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g --wbits 4 --groupsize 128
```

**Comment by MatteCrystal** [comment]
> This change should have made it easier to load this model [8c61552](https://github.com/oobabooga/text-generation-webui/commit/8c6155251ae9852bbae1fd4df40934988c86a0b1)
> 
> I have managed to load it with this command without deleting anything:
> 
> ```
> python server.py --model anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g --wbits 4 --groupsize 128
> ```

Didn't work for me, 4090, 32 gb ram, windows 10

**Comment by Death-777** [comment]
I too am having this exact issue on a 3090, with 32 gb ram, windows 10, and I feel like I tried everything at this point and no progress on it yet. I really hope somebody can figure this out eventually.

**Comment by kenedos** [comment]
I have found this "out of memory" issue starts happening on commit 39f3fec913e8ca4ad9e11bcb94ceee76f4e07d11 and ownards. If you checkout your code to the commit just before that one, it loads the model just fine

**Comment by Timo0956** [comment]
If you completely reinstall the webui it runs now. However, a new error appears when limiting your gpu memory.

Error:

Traceback (most recent call last):
  File "C:\Users\oobabooga\text-generation-webui\modules\callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "C:\Users\oobabooga\text-generation-webui\modules\text_generation.py", line 220, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\accelerate\hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\accelerate\hooks.py", line 160, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\accelerate\hooks.py", line 280, in pre_forward
    set_module_tensor_to_device(module, name, self.execution_device, value=self.weights_map[name])
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\accelerate\utils\offload.py", line 123, in __getitem__
    return self.dataset[f"{self.prefix}{key}"]
  File "C:\Users\oobabooga\installer_files\env\lib\site-packages\accelerate\utils\offload.py", line 170, in __getitem__
    weight_info = self.index[key]
KeyError: 'model.layers.39.self_attn.q_proj.wf1'
Output generated in 7.61 seconds (0.00 tokens/s, 0 tokens, context 36)

**Comment by yami-no-tusbas** [comment]
> If you completely reinstall the webui it runs now after commit [8c61552](https://github.com/oobabooga/text-generation-webui/commit/8c6155251ae9852bbae1fd4df40934988c86a0b1).

Thx it fixed my issue.

**Comment by MancV21** [comment]
Same for me. Just deleted the lot and downloaded the installer again to make a clean start. Will report back in a minute.

**Comment by MancV21** [comment]
> [johnswan](/johnswan)

Same. I checked what commit I'm on (see image) which is the very latest and I'm still getting the OOM error.

![Screenshot 2023-04-10 151557](https://user-images.githubusercontent.com/48100565/230919203-34f103a7-91cf-45e7-8955-c0bf7a423775.png)

**Comment by MancV21** [comment]
I have a 4070ti with 12GB. The error you posted says it tried to allocate 52MB, so I don't think it's a VRAM issue. I've also set it to use my CPU and still get the error.

**Comment by MancV21** [comment]
Long shot but could it be an issue with TI cards? There's a link to a comment in another thread about the UI not loading quantized  models (which this one is). In that message he says -

>updated the GPTQ-for-LLaMa wheel to broaden GPU architecture support. 

https://github.com/oobabooga/text-generation-webui/issues/991#issuecomment-1501889288

The fact he mentions GPU architectures makes me think it could be TI cards with the issue? I'm clutching at straws here lol.

**Comment by SuperFurias** [comment]
> > I have a 4070ti with 12GB. The error you posted says it tried to allocate 52MB, so I don't think it's a VRAM issue. I've also set it to use my CPU and still get the error.
> 
> Yet this bug is closed... (shrug).

after the changes, with a 3060TI I can strangely run the model now, (at least the gpt4-x-alpaca-13b-native-4bit-128g one)
but inside the web ui, i can't actually write NOTHING to the bot because it instantly goes Out of memory.

**Comment by Timo0956** [comment]
I forgot to mention I changed the installer to this one https://github.com/jllllll/one-click-installers/blob/oobabooga-windows/install.bat it's from the same person who made the one-click installer for oobabooga just changed a little and it allowed my 2060 SUPER to run fine

**Comment by garagesailor** [comment]
I have a 3080 10gb, 32gb ram, Ryzen 5900x, running win 10 and I have it running smoothly. I was having the same issue until added the --pre_layer flag. 

these are the command line flags im currently successfully launching with: 
--auto-devices --pre_layer 38 --chat --wbits 4 --groupsize 128 --listen

**Comment by MancV21** [comment]
Thanks for posting possible fixes everyone but so far, no luck. 

I used the other install.bat file and noticed it echoed that Micromamba might not work with long paths or paths with spaces, so I moved the install to the root of the drive and called the folder CHAT. No luck. 

I also just added the command line options you mentions but still no luck. 

I think I'll leave it for now and see if anything gets fixed in the future.

**Comment by MancV21** [comment]
Someone has opened a new issue with this problem here https://github.com/oobabooga/text-generation-webui/issues/1009#issue-1661015569

Might be a good idea to use that thread from now as this one might not get looked at seeing as it's been closed.

**Comment by sgsdxzy** [comment]
It says CPUAllocator, it's not related your gpu's VRAM, but cpu RAM.
GPTQ-quantized model required a lot of RAM to load, by a lot I mean a lot, like around 60+G for 65B to load. Once fully loaded it will no longer use that much RAM, only VRAM.
If you don't have enough RAM, try increasing swap for Linux or pagefile for Windows.

**Comment by MancV21** [comment]
There a people with nowhere near that much system RAM running the model.

**Comment by sgsdxzy** [comment]
> There a people with nowhere near that much system RAM running the model.

You can set a large swap, that's all it takes. The swap is on disk, and is only used when loading, and does not affect the actual running of model in any aspect.

**Comment by Jonseed** [comment]
I also have the same error, and can't find a solution. I have 12GB RAM (and 25GB paging swap), and a RTX 3060 12GB card.

**Comment by Daviljoe193** [comment]
Hey, have any of you guys tried using the [tsumeone/gpt4-x-alpaca-13b-native-4bit-128g-cuda version](https://huggingface.co/tsumeone/gpt4-x-alpaca-13b-native-4bit-128g-cuda)? For some reason, that version loads just fine on Linux, even though the anon8231489123 version doesn't. I don't use Windows, so I can't comment on if it does or doesn't work on there, but it's worth trying.

**Comment by biscober** [comment]
I'm not sure why this issue is closed, as it's still happening and I didn't see a solution posted.  Loading a 30b 4bit-128g model I get this issue on my 3090.  No such issue if I load a 13b model.  The same 30b 4bit-128g model loads fine with all layers in VRAM using KoboldAI, so I don't think it's an issue of it being too large for my VRAM.  I also have 32GB of system RAM and 64GB of swap so it shouldn't be a lack of memory, either.

From event viewer:
Application Crash
```
Faulting application name: python.exe, version: 3.10.9150.1013, time stamp: 0x63dc1a58
Faulting module name: torch_cpu.dll, version: 0.0.0.0, time stamp: 0x640a92cc
Exception code: 0xc0000005
Fault offset: 0x0000000006c6788b
Faulting process id: 0x0x92C
Faulting application start time: 0x0x1D96CE49FEA1F45
Faulting application path: C:\AI_Stuff\oobabooga-windows\installer_files\env\python.exe
Faulting module path: C:\AI_Stuff\oobabooga-windows\installer_files\env\lib\site-packages\torch\lib\torch_cpu.dll
Report Id: c232a88c-250b-4ac7-992b-24e3f6e41c4c
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by yami-no-tusbas** [comment]
> I also have the same error, and can't find a solution. I have 12GB RAM (and 25GB paging swap), and a RTX 3060 12GB card.

Add more virtual memory, I had to go up to 32Gb of swap (virtual memory on windows) to solve the issue, but it is solved.

> I'm not sure why this issue is closed, as it's still happening and I didn't see a solution posted. Loading a 30b 4bit-128g model I get this issue on my 3090. No such issue if I load a 13b model. The same 30b 4bit-128g model loads fine with all layers in VRAM using KoboldAI, so I don't think it's an issue of it being too large for my VRAM. I also have 32GB of system RAM and 64GB of swap so it shouldn't be a lack of memory, either.

The update fixed it for a time, and adding more, way more swap fix it too. It depend off the system load too, I have 24GB VRAM too + 32RAM + 32GB pagefile, less pagefile was not enough, but it will depend on how much memory is free.

**Comment by Jonseed** [comment]
> I found the change that causes excessive swap usage for me and wrote about it here: [#1066 (comment)](https://github.com/oobabooga/text-generation-webui/issues/1066#issuecomment-1504644213)
> 
> For now i just reverted that part of the file on my end and have not noticed any performance regressions. And instead of 80GB+ of page/memory being used before it crashes on load of 30b model, its back to the normal ~37GB.

I tried reverting that part of the file, and it still didn't work. Same error.
