### ISSUE TITLE
No such file or directory: 'models/anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g/pytorch_model-00001-of-00006.bin'

### ISSUE THREAD

**Issue by BaptisteGarcin** [oobabooga/text-generation-webui#962]
Followed every steps on mac M1
downloaded model with python download-model.py anon8231489123/gpt4-x-alpaca-13b-native-4bit-128g
when I launch python server.py --cpu --model anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g
I get the error : No such file or directory: 'models/anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g/pytorch_model-00001-of-00006.bin'

**Comment by UrdaxAlDiomis** [comment]
I have a similar error, but on linux. 

FileNotFoundError: [Errno 2] No such file or directory: 'models/gpt4-x-alpaca-13b-native-4bit-128g/pytorch_model-00001-of-00006.bin'

**Comment by p1nkl0bst3r** [comment]
Did you install [GPTQ-for-LLaMa](https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#4-bit-mode)?
this is working for me using an AMD graphics card on linux:
`python server.py --chat --model anon8231489123_vicuna-13b-GPTQ-4bit-128g --model_type LLaMA --wbits 4 --groupsize 128`

**Comment by oobabooga** [comment]
Please read the wiki, the 4-bit models require additional command-line arguments

https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#step-3-start-the-web-ui
