### ISSUE TITLE
oobabooga webui terminal wont run commands

### ISSUE THREAD

**Issue by scrawnyether5669** [oobabooga/text-generation-webui#975]
![Capture13](https://user-images.githubusercontent.com/117683751/230795492-e86af200-4c4b-4e7d-be7c-18e633d7841c.PNG)

**Comment by oobabooga** [comment]
It asked you a number between 1 and 4, and you typed -h

**Comment by scrawnyether5669** [comment]
where do i put the command then?

**Comment by scrawnyether5669** [comment]
where do i put the command then?
